### ISSUE TITLE
Allow "empty" values for required fields (number-0, boolean-false)

### ISSUE THREAD

**Issue by ChrisMGeo** [pocketbase/pocketbase#1011]
Maybe I'm thinking and going about this wrong, but aren't required fields, ones for which a value must be provided? If so, wouldn't it be correct to be able to initialize and edit fields to be "empty" like 0, false, etc.
Using `pocketbase_0.7.10_windows_amd64`.

**Comment by ChrisMGeo** [comment]
Maybe make it easier in the UI, by providing a checkmark on optional fields to indicate that you're passing a value to it?

**Comment by ChrisMGeo** [comment]
mainBuildingID is an optional field:
![image](https://user-images.githubusercontent.com/44679968/201500309-253e540e-60db-4f27-abe8-c954a7d97cc2.png)
![image](https://user-images.githubusercontent.com/44679968/201500328-cf69e4df-08cf-4dbe-a3d5-9d0f3c34ea6b.png)

**Comment by ganigeorgiev** [comment]
@ChrisMGeo PocketBase doesn't support `null` for the field values (_with exception for the `json` type_) and instead uses zero-defaults. For number that is `0`, for string - empty string, etc. More information on this will be available soon, but you could find a table with all supported values in https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0.
