### ISSUE TITLE
pocketbase don't serve

### ISSUE THREAD

**Issue by deleonjuan** [pocketbase/pocketbase#106]
when i run  `./pocketbase serve`, the server goes on
but then when i try to go to http://localhost:8090/_/, it shows nothing
a few seconds later the server fall

the only message i get is this:
![image](https://user-images.githubusercontent.com/31250630/178884636-d0b026cb-7c98-44d5-8653-dcf72e2ae980.png)

pocketbase version: 0.2.4
windows version: Windows 10 Pro 21H2 19044.1766

**Comment by noxware** [comment]
I also had problems trying pocketbase in a windows computer. I ended up trying it in WSL.

**Comment by ganigeorgiev** [comment]
@deleonjuan Could you  try starting the application with `--http="127.0.0.1:8090"`, aka.:
```sh
./pocketbase.exe serve --http="127.0.0.1:8090"
```

I have the Windows 10 Enterprise Eveliation 21H2 virtual machine and it works as expected for me.
Another thing that may cause this is maybe a firewall/antivirus software that prevents binding to the port.
