### ISSUE TITLE
[feature request] [auth] passwordless/magic link authentication

### ISSUE THREAD

**Issue by nandox5** [pocketbase/pocketbase#1078]
How difficult would it be to add passwordless or magic link authentication? If time allows, i’d like to submit a request for a possible addition. 

Next-auth and passport i believe have it, in case you need to get some ideas.

 Ideally, this Would include an option for inviting new users (by admins) as well as an option for self sign ups allowed by admin/configured to allow self sign ups

have a good day.

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/119.
