### ISSUE TITLE
[FeatureReq] Simple username/pass login without e-mail

### ISSUE THREAD

**Issue by RShadowhand** [pocketbase/pocketbase#108]
It'd be amazing if there was an auth method for username/password login for internal projects, without the need for an email address.
No registration process as user accounts would be created by an in-organization administrator.

Great project, keep up the good work!

**Comment by ganigeorgiev** [comment]
Thanks for the suggestion, but for now this is not planned and it will introduce unnecessary complications:
- how  the user will reset his/her password
- what about user verification
- changing usernames
- how to combine with the additional OAuth2 authentication if enabled (currently we use the email from the returned OAuth2 profle to sign-in/sign-up the user)
- etc.
