### ISSUE TITLE
Feature Request: Send E-Mail Endpoint

### ISSUE THREAD

**Issue by firewave-remo** [pocketbase/pocketbase#1080]
Thank you very much for your work on PocketBase. Saw it in a Video and gave it a shot.

I tried to replace one of my backends with PocketBase and the only roadblock I face is that I need to be able to send E-Mails from my backend. Since all the E-Mail Settings are already there, I hope this might be doable.

2 Possibilities come to my mind.
1. It would be enough if there is an endpoint where I would have to pass everything. (Subject, Recipients, Body)
2. I am able to define templates like it's already there for "Verification", "Password reset", and "Confirm email change") and only provide the Recipients and the Template I would like to use.

**Comment by ganigeorgiev** [comment]
Currently you can send custom emails only if you [extend PocketBase](https://pocketbase.io/docs/use-as-framework/), eg.:

```go
app.NewMailClient().Send(&mailer.Message{
    From: "test1@example.com",
    To: "test2@example.com",
    Subject: "Demo 123",
    HTML: "...",
})
```
_(I'll add it to the documentation sometime later this week)_

Sending and configuring custom emails from the UI currently is not possible but eventually will be handled as part of the [Collection triggers #317 issue](https://github.com/pocketbase/pocketbase/issues/317).

**Comment by ikmolbo** [comment]
I'd love to see this without having to extend PocketBase. Would it be possible to send mails via the JS SDK?

Thank you for your work - PocketBase looks truly outstanding.

**Comment by ganigeorgiev** [comment]
@ikmolbo 

> Would it be possible to send mails via the JS SDK?

No, for now this is not planned. Even if it is added it will require to authenticate as admin, meaning that you'll have to execute it server-side anyway (as part of the PocketBase instance, in a node handler, etc.).

Option to bind to the app hooks with JS will be available in the near future (similar to the recent JS migrations support), or in other words, sending custom emails with JS hook will look something like this:

```js
app.newMailClient().send(new EmailMessage({
    from: "test1@example.com",
    to: "test2@example.com",
    subject: "Demo 123",
    html: "...",
}))
```
