### ISSUE TITLE
Boolean field marked nonempty treats False as empty

### ISSUE THREAD

**Issue by theswampire** [pocketbase/pocketbase#1085]
### Situation
There is collection with a **boolean** field marked as **nonempty**.
When creating a new Record or editing an existing Record using the Web UI, you are forced to check the toggle of this nonempty field. Otherwise an error message pops up, saying "Missing required value".

There is no way to change it to **False**.

---

I don't know where the form validation occurs but I suspect a truthiness check that treats **False** like an empty value.

**Comment by ganigeorgiev** [comment]
This is working as expected. PocketBase doesn't support `null` as field value (with exception to the `json` field type) and uses zero-defaults.

List with all supported values for each field type could be found in https://pocketbase.io/docs/collections/.

If you hover on the "Nonempty" tooltip there should be also an explanation what "nonempty" means (for `bool` fields that is not `false`).

**Comment by theswampire** [comment]
I'm still a little confused.
Is there a use case for having a field that is always True?
