### ISSUE TITLE
Realtime delete events are not sent

### ISSUE THREAD

**Issue by itterheim** [pocketbase/pocketbase#109]
``delete`` event created after ``OnRecordAfterDeleteRequest`` in [apis/realtime.go](https://github.com/pocketbase/pocketbase/blob/master/apis/realtime.go) is not sent.

I tried to track down where the problem is:

[apis/realtime.go#L265](https://github.com/pocketbase/pocketbase/blob/master/apis/realtime.go#L265)
```go
	foundRecord, err := api.app.Dao().FindRecordById(record.Collection(), record.Id, ruleFunc)
	if err == nil && foundRecord != nil {
		return true
	}

	return false
```

Before the event is sent to a client, ``canAccessRecord`` checks whether the record exists in the database and if it can be accessed according to rules. It always returns ``false`` and the event is not sent because the record is already deleted.

**Comment by ganigeorgiev** [comment]
Since this may be a blocker for someone, I've released a hotfix for this in [v0.2.7 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.2.7).

I'll revisit the realtime integration tests this weekend.
