### ISSUE TITLE
Feature Request: Reorder records in relation field

### ISSUE THREAD

**Issue by sonovice** [pocketbase/pocketbase#1161]
Thank you for this amazing project!

I would love to have the ability to reorder the records in a relation field. Currently, I have to be very careful when modeling this manually. Sometimes I have hundreds of entries, making this a very error prone or even undoable task.

Background: I have a big collection of "songs" that I want to put into ordered "playlists".

Somewhat related is #881 which would make a lot of sense in this case.

**Comment by ganigeorgiev** [comment]
You can change the order of a multi-relation entries programmatically by updating the order of the rel ids in the rel field array. For example:

```js
pb.collection('playlists').update("PLAYLIST_ID", {
   songs: ['SONG_ID2', 'SONG_ID1', 'SONG_ID3'],
})
```

Relations reordering in the Admin UI will be handled as part of the planned Relations picker improvements in https://github.com/pocketbase/pocketbase/issues/976 (_I've just updated the issue and added a note to drag&drop sorting_).

**Comment by sonovice** [comment]
Thank you for the quick response, that sounds fantastic. 👍
