### ISSUE TITLE
Feature Request: Exposing logs as prometheus endpoint

### ISSUE THREAD

**Issue by sonovice** [pocketbase/pocketbase#1167]
Hi,

it would be very helpful to expose the logs etc. as a [prometheus](https://prometheus.io/) endpoint. That would allow for better monitoring/alerting in case things go south.

**Comment by bscott** [comment]
Prometheus is usually for exposing metrics at `/metrics` endpoint, not really logs. If your running Pocketbase in Docker or Kubernetes, usually you would capture logs from STDOUT using FluentD as an example.

**Comment by pr0ton11** [comment]
But a /metrics endpoint would indeed not be bad

**Comment by emkrawiec** [comment]
Hey, pocketbase uses echo for routing and it has its own prometheus middleware.

https://echo.labstack.com/middleware/prometheus/

Only issue I reported that package is depended on echo v4 and pocketbase uses v5. However it looks like it's only one file so you can get it, change dependency to echo v5 and try it.

**Comment by ganigeorgiev** [comment]
The logs are refactored and generalized in `master`, but for now I decided to not implement a Prometheus endpoint as I personally don't have a use case for it and most likely users will want at some point to define their own custom metrics and therefore I think this will be better left to external middlewares like the one linked from above.

Depending on the users demand I may revisit it, but for now remains out of the scope for v1.
