### ISSUE TITLE
Pocketbase not serving pb_public by default

### ISSUE THREAD

**Issue by jufracaqui** [pocketbase/pocketbase#1185]
Hello. Thank you for the amazing work!

In the [Basics - Introduction - Docs](https://pocketbase.io/docs) is stated that

`if pb_public directory exists, serves the static content from it (html, css, images, etc.)`

But I do not think it is working as expected.

On `main.go:73` is the code that enables the functionality, but it is not working.
```
app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
    // serves static files from the provided public dir (if exists)
    e.Router.GET("/*", apis.StaticDirectoryHandler(os.DirFS(publicDir), indexFallback))
    return nil
})
```

A workaround I have done on my project is to add the route manually, just under the creation of a new Pocketbase app, and it is working as expected now.

```
app = pocketbase.New()

app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
    // serves static files from the provided public dir (if exists)
    e.Router.GET("/*", apis.StaticDirectoryHandler(os.DirFS("./pb_public"), true))
    return nil
})
```

Thank you!

**Comment by ganigeorgiev** [comment]
The `pb_public` is registered by default only for the prebuilt executable.

When extending PocketBase, aka. embedding it in your Go app, you have to register it manually.

You can see the default prebuilt executable commands in:

```
// v0.8
https://github.com/pocketbase/pocketbase/blob/v0.8.0/examples/base/main.go

// upcoming v0.9
https://github.com/pocketbase/pocketbase/blob/master/examples/base/main.go
```

**Comment by ishanray** [comment]
@ganigeorgiev it would be nice to list all the changes required when using it as a framework to match the prebuilt executable.
so far i have:

- auto migration enable
- manually register publicDir
