### ISSUE TITLE
Feature Request: Add simple login with username and password

### ISSUE THREAD

**Issue by deleonjuan** [pocketbase/pocketbase#120]
Hi guys, i think simple authentication with just username and password would be great for small projects
or maybe a new 'encripted field' for password storage, then we can make a custom user table
thx

**Comment by ganigeorgiev** [comment]
Ah, this was asked previously but it seems to be a common feature request so I will reconsider it, but it's a low priority for now (I'll post soon a roadmap for v1.0.0).

**Comment by ganigeorgiev** [comment]
This is now available as part of the [v0.8.0-rc1 pre-release](https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1).
