### ISSUE TITLE
Connection Refused - pocketbase on linux server

### ISSUE THREAD

**Issue by gianlucafiore** [pocketbase/pocketbase#121]
Hello!, I'm have this small cloud server (ubuntu v18 and also try v20), and I can't  connect  to simple /_
![image](https://user-images.githubusercontent.com/50465150/179118740-3366f0c9-99dd-452d-849c-e11f50eb1bf1.png)
![image](https://user-images.githubusercontent.com/50465150/179117745-5e9e304e-75a7-4250-9a05-10ac9e8a42b1.png)

Firewall ports TCP/UDP are open 80, 8090, 433 etc...

**Comment by ganigeorgiev** [comment]
Oh, It could be a lot of things. There is not enough info to debug this.
My guess is that there is a firewall (could be a separate service from your vps) that blocks the 8090 port or there is some local network configuration that is mising. You could try several things:
- start with `--http="127.0.0.1:8090"`, eg. `./pocketbase serve --htp="127.0.0.1:8090"`
- use 80 port eg. `./pocketbase serve --htp="127.0.0.1:80"` and try to access directly the ip of your server
- contact your vps provider support

**Comment by gianlucafiore** [comment]
Perfect, thank You very much. I will try this later 👌

**Comment by gianlucafiore** [comment]
![image](https://user-images.githubusercontent.com/50465150/179216447-1ee284ab-c958-40ff-8039-d2e0420099ad.png)
### I tried this and it worked! 

![image](https://user-images.githubusercontent.com/50465150/179216606-0563f139-1d99-4376-b697-8329f2d5d34e.png)

the previous two (with localhost) did not work
