### ISSUE TITLE
List/search endpoints should support selecting specific fields

### ISSUE THREAD

**Issue by IgnisDa** [pocketbase/pocketbase#1218]
Thanks for the awesome project!

I have a usecase where I want to get all records via the `.getFullList()` method. However since there is no way to select only specific fields, the endpoint returns all the data which results in a lot of bandwidth usage. Ideally, I want to select only some specific fields.

```ts
await pb.collection('notes').getFullList<Note>(200, {
    sort: '-created',
    selectFields: 'id,writtenBy'
});  
```

A mututally exclusive `excludeFields` would go a long way too.

Thanks again!

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/1174 and https://github.com/pocketbase/pocketbase/discussions/354.

It may be considered in the future, but for now it is out of scope for v1.
