### ISSUE TITLE
Add "Clear" button to the datetime fields

### ISSUE THREAD

**Issue by IgnisDa** [pocketbase/pocketbase#1219]
## Bug description

I have a nullable datetime field in a collection. For a record, I have set the datetime field to a value. However, now I want to remove this value and set it to `null`. This is not possible via the admin UI.

Before:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/60938164/206660729-8f608c1c-ab66-48a0-91ca-e6a78adae07c.png">

(`Save changes` button is disabled without any changes)

After:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/60938164/206660822-15d8c9ef-b600-43cb-a181-7a198ef9c02c.png">

(`Save changes` button is still disabled even after I removed the `wasWrittenOn` field value usin backspace)

## Possible Solution

Have a small `X` at the end of each nullable input which can set the value of that input to `null` (with a tooltip saying so).

**Comment by ganigeorgiev** [comment]
PocketBase doesn't support `null` for the field values (see https://pocketbase.io/docs/collections/).

You should be able to clear the text input but I'll consider adding a button to make it more clear.

**Comment by ganigeorgiev** [comment]
Should be fixed in the latest [v0.9.1 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.9.1).
