### ISSUE TITLE
Boolean type not accepting false on gui

### ISSUE THREAD

**Issue by azizvc** [pocketbase/pocketbase#1246]
![image](https://user-images.githubusercontent.com/10561123/207034498-78b0601a-ab27-40ac-a967-f050ec391886.png)

**Comment by ganigeorgiev** [comment]
This is working as expected. When a field is marked as "Nonempty/Required" it allows only `true` for the `bool` field value (there is a tooltip to the "Nonempty/Required" toggle that explain the behavior).

Please note that PocketBase doesn't support `null` values (with the exception of the `json` type field) and uses zero-defaults (for a list with all supported values you can check https://pocketbase.io/docs/collections/).
