### ISSUE TITLE
Provide Pocketbase version in Settings Application Component

### ISSUE THREAD

**Issue by gevera** [pocketbase/pocketbase#1285]
By providing a simple version string like so _v0.10.0_  in the admin panel, it will be easier to track the upgrades.  Right now, I had to rely on the new /api/health endpoint to make sure that I've successfully upgraded from  0.8 to 0.10. It will be more convenient to just glance to the Application Settings to see the current version of Pocketbase. Besides, additional info could be added later, like the RAM, memory taken by the DB etc. Maybe even add a link to Sponsorship or Donation for this project. Anyways, thank you for this awesome tool. Loving it

**Comment by ganigeorgiev** [comment]
You can find the PocketBase version in the Admin UI in the bottom-right corner, but I may consider printing it also in the Settings > Application section in the future.

Alternatively, if you are using the prebuilt executable, you can check the current version with `./pocketbase --version`.

**Comment by gevera** [comment]
Oh wow, I totally missed that. Thanks for quick reply. Cheers
