### ISSUE TITLE
Feature Request: Multiple Projects

### ISSUE THREAD

**Issue by greendesertsnow** [pocketbase/pocketbase#1305]
Can you please enable people to have multiple projects on one installation. That's the single most crucial different Pockerbase and Appwrite, with the later one you can have as many projects you want and your users, functions, databases do not mix.

Basically its just a overhead table that separates one project from another. But it makes users have PB as an incubator for many projects.

**Comment by ganigeorgiev** [comment]
No, sorry this is not planned. You can also check https://github.com/pocketbase/pocketbase/issues/324, https://github.com/pocketbase/pocketbase/discussions/97#discussioncomment-3139409, https://github.com/pocketbase/pocketbase/discussions/180 and probably others.

It is better and easier to maintain a single project per database file.
