### ISSUE TITLE
How to get the total number in a collection directly?

### ISSUE THREAD

**Issue by kuerme** [pocketbase/pocketbase#1310]
According to the documentation, the collection data and total number can be obtained through the list/search api, but is there any way to directly obtain the total number without other data?

**Comment by ganigeorgiev** [comment]
No, sorry. Aggregation type of queries are not possible via the web API at the moment.

The easiest workaround would be to request a getList with single item:

```js
const { totalItems } = await pb.collection("example").getList(1, 1);
```


If you are embedding PocketBase in your Go app, you can also create your own endpoint and execute a raw query to count your collection records. You can find some info in https://pocketbase.io/docs/database/.


There are plans in the future to add support for a new "View" collection type, which will allow specyfing a raw SQL query from the UI and it will create an API endpoint for you, but this will be handled in [#311](https://github.com/pocketbase/pocketbase/issues/311#issuecomment-1312790397).

**Comment by kuerme** [comment]
Thanks for your answer and look forward to new features in the future

**Comment by RayyanNafees** [comment]
> The easiest workaround would be to request a getList with single item:

This workaround gives the total number of records in a collection right ?

**Comment by ganigeorgiev** [comment]
@RayyanNafees This is an old issue but Yes, the suggested `getList(1, 1)` call should return a response containing `totalItems` field.

If you need more complex aggregations, you can create a [View collection](https://pocketbase.io/docs/collections/#view-collection) with your custom SQL `SELECT` query.

**Comment by kabs9000** [comment]
Hi, we're trying this and getting totalItems = undefined
Do you know why this could be and how to fix it?

**Comment by ganigeorgiev** [comment]
@kabs9000 Without details how you are sending the requests I don't think I can help you.

If you are not able to resolve your issue, please open a new [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more info about your use case and some reproducible steps.
