### ISSUE TITLE
@collectionId and @collectionName in UI RecordSelectOption

### ISSUE THREAD

**Issue by dhall2** [pocketbase/pocketbase#1322]
I noticed in a relation picker on `v0.10.2` the `id` and one additional field is included for context. In my case, it included `collectionId`. 

![image](https://user-images.githubusercontent.com/74067220/208775581-03509b16-ce8e-4747-88a6-adc780f9ebc5.png)

Looking through the UI code, props are filtered against a list of excluded meta props.
https://github.com/pocketbase/pocketbase/blob/b9922e484320a91a809e663dd1ee1a94ddc30a97/ui/src/components/records/RecordSelectOption.svelte#L5

It appears these were renamed in `v0.8.0`:
https://github.com/pocketbase/pocketbase/blob/15c05b9679121b895b7570a3c5813c6aa44c7cf7/CHANGELOG.md?plain=1#L355

Would a PR for this be welcome?

**Comment by ganigeorgiev** [comment]
Yes, thank you for noticing it. I'll remove it in the next release.

The relation picker UI will change anyway in PocketBase v0.12 in relation to #976.
