### ISSUE TITLE
Boolean field conflict with Required

### ISSUE THREAD

**Issue by felipebhz** [pocketbase/pocketbase#1324]
**Change suggested:**
- To remove the `nonempty` option from the `Boolean` field as this can lead to misleading settings as this cannot be `false` *(which is one of the Boolean options)*

![image](https://user-images.githubusercontent.com/1553350/208791180-e7d3e86b-3bbf-417f-a5d8-d85530d2ce3a.png)

**Comment by ganigeorgiev** [comment]
This is working as expected. When a `bool` field is marked as "Nonempty/Required" it adds a non-false constraint. PocketBase doesn't have `null` as field value (please check https://pocketbase.io/docs/collections/#overview) and will always store the zero-default of the field (_*the only exception is the `json` field type_).

If you hover on the "Nonempty" tooltip you'll find a tooltip with explanation what "Nonempty" in this context means.

Or in other words, if you want your `bool` to accept both `true` and `false` values, then don't mark it as "Nonempty".
