### ISSUE TITLE
Bug: API does not check user minimum password length on update

### ISSUE THREAD

**Issue by SethBurkart123** [pocketbase/pocketbase#1327]
If an empty string is submitted as the password:
```javascript
const record = await pb.collection('users').update('RECORD_ID', {
     "password": "",
    "passwordConfirm": "",
    "oldPassword": "12345678",
});
```
Pocketbase will update the users password to that empty string contrary to the minimum password parameter inside the collection options menu.

**Comment by ganigeorgiev** [comment]
I cannot reproduce the issue. Before PocketBase v0.10 we were **ignoring** the password change if the password is empty (you can try login with the old password and will see that **the empty password change actually is not applied**).

In v0.10 we now trigger the required password validators if any of the password change field is set.
