### ISSUE TITLE
Pocket Base Job Scheduler

### ISSUE THREAD

**Issue by silverdevelopper** [pocketbase/pocketbase#1355]
PocketBase should have a cron job scheduler like in Firebase.

**Comment by ganigeorgiev** [comment]
I don't think there is need to be part of the core package. Developers are free to use whatever cron/scheduler mechanism they want when using [PocketBase as framework](https://pocketbase.io/docs/use-as-framework/) _(In the future there are also plans to allow binding to the app hooks with JS and goja)._
