### ISSUE TITLE
Cant upload video (1.9gb)

### ISSUE THREAD

**Issue by Zilonis123** [pocketbase/pocketbase#1391]
I have a collection called home movies and i have a file field in the collection with a limit of 25000000 bytes. But whenever i try to upload a video of 1.9gb it says something went wrong with the request, but when i upload a small video it works fine. Everything i do is through the admin ui

**Comment by ganigeorgiev** [comment]
Could you start PocketBase with `--debug` and see if there is a more detailed error message from the console?

Do you have a reverse proxy (eg. nginx, apache, etc.) that has body size limit?

Also please note that form-data requests larger than 32MB will be stored temporary on the disk, so you need to have at least 2gb free disk space in your case.

**Comment by Zilonis123** [comment]
ok ill try to run the command and i will see what the error is.

I have enough space ~200gb

**Comment by ganigeorgiev** [comment]
I've just tested it locally. The only way I can simulate an error with large files (excluding 
 lack of disk space) is if the upload takes too much time and the request is being timeouted.

Currently the read timeout is 60s but for large file upload this may not be sufficient and I'll consider increasing it with the next release to 180s (and eventually make it configurable).

**Comment by Zilonis123** [comment]
That definetly is the case then. Hopefully this i fixed soon.

My upload takes about a minute
