### ISSUE TITLE
Feature Request: Allow expanded properties to be aliased

### ISSUE THREAD

**Issue by GD-coding** [pocketbase/pocketbase#1396]
Would it be possible to use aliased names for expanded fields rather than the expansion name? An example being

original query
```
const items = await pb.collection('originalCollection').getFullList(null, {
  expand: 'relatedCollection(originalCollection)',
});
```

suggestion query
```
const items = await pb.collection('originalCollection').getFullList(null, {
  expand: 'relatedCollection(originalCollection) as newName', // or relatedCollection(originalCollection):newName
});`

**Comment by ganigeorgiev** [comment]
No, sorry. I think this will cause confusion and even conflict with other rel field names.

In the near future there are plans for "view" collection type per https://github.com/pocketbase/pocketbase/issues/311#issuecomment-1312790397, which will allow users to define their own query in case the expand is too complex/verbose.
