### ISSUE TITLE
`OnRecordAfterCreateRequest` Not Triggered when using `AuthWithOAuth2`

### ISSUE THREAD

**Issue by ezynda3** [pocketbase/pocketbase#1398]
I'm extending pocketbase and hooking into `app.OnRecordAfterCreateRequest()` and it works fine on normal user creation but when a user is created as a result of `AuthWithOAuth2` the hook is never triggered. Is there a special hook for this?

**Comment by ganigeorgiev** [comment]
No. The `*Request` hooks are triggered only on API request for the specific action.

If you want to detect changes to your users record from everywhere, including internal triggered creates/updates as in the case with `authWithOAuth2`, you can listen to the [`OnModel*` hooks](https://pocketbase.io/docs/event-hooks/#db-hooks):

```go
app.OnModelAfterCreate().Add(func(e *core.ModelEvent) error {
	record, ok := e.Model.(*models.Record)

	if !ok || record.Collection().Name != "users" {
		// not a users model
		//
		// note: in the near future we'll have support for specyfing this
		// as of the `OnModelAfterCreate("users").Add(...)`
		return nil
	}

	// do something with the created record...
	record.Set("someField", "example")

	return app.Dao().SaveRecord(record)
})
```

Dedicated hooks for the `auth-with-password` and `auth-with-oauth2` endpoints will be added in v0.11/v0.12 with https://github.com/pocketbase/pocketbase/issues/1240.

**Comment by ezynda3** [comment]
Thanks!
