### ISSUE TITLE
Add UID Field and Add Search box for Relation dropdown

### ISSUE THREAD

**Issue by hungcrush** [pocketbase/pocketbase#1399]
Hi ~ 

Sorry may I'm wasting your time, I just asking, 

1. do you think about UID Field then attach with another field (like title) then enable Unique option
2. Can we add search box for Relation Dropdown, the current UI is not good when relation field has a lot of data..

**Comment by ganigeorgiev** [comment]
This is already in the [roadmap](https://github.com/orgs/pocketbase/projects/2) and will be handled as part of the planned relation picker UI improvements in https://github.com/pocketbase/pocketbase/issues/976 (most likely in v0.12/v0.13).
