### ISSUE TITLE
text overflow in dashboard filter field

### ISSUE THREAD

**Issue by jaasonw** [pocketbase/pocketbase#1416]
So don't ask why I'm performing such a query but a sufficiently large query overflows in this textbox

![image](https://user-images.githubusercontent.com/8981287/209866623-d7162cf3-5bd9-47fc-9bbe-4099eb7cafe1.png)

**Comment by ganigeorgiev** [comment]
Thanks, I've pushed a fix in `master` and it will be available with the next release (most likely next week).

The wrapped text expression will now expand the searchbar like this:

![searchbar_screenshot](https://i.imgur.com/Lf2Sv4L.png)
