### ISSUE TITLE
Is there a way to limit the ammount of requrests a user can do in a specific time?

### ISSUE THREAD

**Issue by fprackwieser** [pocketbase/pocketbase#1419]
Is there any way to implement a limit of requests / actions a user can do?

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/1232.

My general recommendation is that if you need more finer network controls (ip blacklist/whitelist, rate limiter, multiple apps, etc.) to use a reverse proxy, eg. nginx (_example config could be found in https://pocketbase.io/docs/going-to-production/#using-reverse-proxy_).
