### ISSUE TITLE
Feature Request: API to call Shell commands

### ISSUE THREAD

**Issue by The-Awesome-Tools** [pocketbase/pocketbase#1432]
I am developing an application using PocketBase. The system requires to run some `Shell` commands. It would be great if there can be an API endpoint to call system command and get the output. Example:
```
query: 'whoami'
returns: 'root'
```

**Comment by ganigeorgiev** [comment]
Sorry, this is not planned. There are too many edge cases.

You can handle this on your own if you [use PocketBase as framework](https://pocketbase.io/docs/use-as-framework/).
