### ISSUE TITLE
Number 0 is not displayed in collection preview

### ISSUE THREAD

**Issue by tohodakilla** [pocketbase/pocketbase#1447]
When a number field has value 0 it is not displayed in collection preview.
![Screenshot from 2022-12-31 08-54-33](https://user-images.githubusercontent.com/1858683/210129807-fb87bed6-154f-4fe6-ab6c-0ed403a825d2.png)

**Comment by ganigeorgiev** [comment]
Thanks. I've pushed a fix in `master` and it will be available with the next release (probably sometime next week).
