### ISSUE TITLE
Feature Request: Self-reference

### ISSUE THREAD

**Issue by ProfEibe** [pocketbase/pocketbase#1451]
It would be great if I could reference one entry on another in the same table?

So that one column in the table can be a reference on the ID of the same.

**Comment by ganigeorgiev** [comment]
This should be already supported, but the collection need to be saved first.

The relations management UI will be refactored in v0.12/v0.13 together with https://github.com/pocketbase/pocketbase/issues/976.

**Comment by ProfEibe** [comment]
Ah alright. Than sry for the interuption :)
