### ISSUE TITLE
Firewall Admin dashboard UI, email 2fa

### ISSUE THREAD

**Issue by ktown007** [pocketbase/pocketbase#1452]
Feature Request.

In Settings add a whitelist list of networks that can access the Admin dashboard UI.  The default can be `0.0.0.0/0`. This will allow for an extra factor of security to the public facing Admin UI. 

Another idea is to serve the Admin UI on a different port to support network level firewall rules or restrict admin UI to a private network.

In Settings add an option for admin UI 2fa. A pin via email would be an easy free solution. 

These two features at the minimum to will check the _Security Officers_ boxes :)

**Comment by ganigeorgiev** [comment]
Some of the requests (eg. the admin email code confirmation) are in my todo and eventually will be added in the future, but for now if you need more advanced network controls like IP whitelist/blacklist, rate limiter, etc. my recommendation is to use a reverse proxy (nginx, apache, caddy, etc.) OR extend PocketBase and provide the functionality on your own via a router middleware.

You can also check https://github.com/pocketbase/pocketbase/issues/1232.

**Comment by ktown007** [comment]
@ganigeorgiev That is a good point about using reverse proxy for firewall rules. Think of this as a wish list to keep to one executable full backend. A build in solution for devs without the web severs or access to firewalls.

re "admin email code confirmation": Do you mean a verification email on first setup(makes sense)? I was thinking a 2fa check on each login attempt from a new device. This has been on all the latest security checklists.

**Comment by ganigeorgiev** [comment]
> I was thinking a 2fa check on each login attempt from a new device. This has been on all the latest security checklists.

Yep, that's exactly what I meant by "email code confirmation". It will be added in the near future but there are no fixed ETAs.
