### ISSUE TITLE
Sign binary

### ISSUE THREAD

**Issue by bscott** [pocketbase/pocketbase#146]
Would be nice if we can get the binary signed to avoid these:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/191290/179371385-3b51afcb-5b2c-47fd-8965-d459f635af24.png">

**Comment by ganigeorgiev** [comment]
Reading the documentation for signing in https://developer.apple.com/developer-id/ it seems that this require having a mac and Apple ID and I have neither of them.

I'll close the PR, since there is nothing much I can do to prevent this message to show.
