### ISSUE TITLE
Expansion doesn't seem to expand multiple relations at the same level.

### ISSUE THREAD

**Issue by chezzzer** [pocketbase/pocketbase#1463]
Hello all, thanks so much for developing Pocketbase, it's such a better alternative to some of the other backends out there.

I am having some trouble expanding multiple relations in the same collection, for instance, this is my collection:

```
community
  ...
  - badges: relation[]
  - modules: relation[]
  - settings: relation
  ...
```

My expand string is this: `settings.tags,badges,modules`.

But I only get modules expanded to an array:

```js
{
  ...
  expand: {
    modules: [{...}],
    settings: {...}
  }
  ...
}
```

Is this some sort of bug or am I not doing this right? Hope you can help.

Thanks!

**Comment by ganigeorgiev** [comment]
@chezzzer I'm not able to reproduce it.

Please make sure that you are using the [latest PocketBase v0.10.4](https://github.com/pocketbase/pocketbase/releases/tag/v0.10.4) (it has some fixes related to the rel expansion) AND that the **View API rule** access for each of your expanded rel collection is satisfied.

If non of the above helps, please attach as json your collections configuration (Admin UI > Settings > Export collections) and I'll test in more details.

**Comment by chezzzer** [comment]
Yes it was the permissions, totally mind blanked that. Thanks!
