### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by bscott** [pocketbase/pocketbase#147]
Would love to start contributing, could we get a `CONTRIBUTING.md` created with some guidelines?

**Comment by ganigeorgiev** [comment]
I've created a [CONTRIBUTING.md](https://github.com/pocketbase/pocketbase/blob/master/CONTRIBUTING.md) with some notes how to prepare a PR for changes in the Go code and in the Admin UI.
Feel free to let me know (or create PR) if there is something else that could be added or changed.

_More detailed instructions and documentaiton about the packages and how PocketBase works in general (currently we have only [code documentation](https://pkg.go.dev/github.com/pocketbase/pocketbase)) is in the [roadmap](https://github.com/orgs/pocketbase/projects/2) but we'll have to first stabilize a little the API internals._
