### ISSUE TITLE
Feature Request: Allow to create new "select" value if it doesn't exist

### ISSUE THREAD

**Issue by Fuchsoria** [pocketbase/pocketbase#1475]
For example, we have here optionA, optionB, optionC. But we will allow on frontend side for user to send a request with extra value optionD, which we don't have in our list. For such cases, it makes sense to have a checkbox in field settings to enable autocreate of this value.
![image](https://user-images.githubusercontent.com/43413472/210288505-218ad2ab-1933-4e68-a87c-92dfb45bf560.png)

**Comment by ganigeorgiev** [comment]
I think this will be confusing and difficult to restrict who can add or update options.

The `select` field works only with predetermined choices. If you want to allow arbitrary number of choices, I'd recommend creating a separate collection with its own API rules and link it with a `relation` field.
