### ISSUE TITLE
GDPR Issues

### ISSUE THREAD

**Issue by dhalucario** [pocketbase/pocketbase#1477]
Hey, I started testing PocketBase recently and I am genuinely loving the experience so far. One issue I encountered though is that you the service is logging full IP addresses. I could not find any options to partially censor IP's. Otherwise this might be quite a huge issue for european devs.

https://gdpr.eu/eu-gdpr-personal-data/

**Comment by ganigeorgiev** [comment]
I don't think there is a GDPR issue here.

The IPs (the remote address and the "real" client IP) in the logs are just server-side access logs. They are not associated to a user session, nor contains any user-identifiable information.

In any case, you can completely disable the logs by setting "Admin UI > Settings > Application > Logs max days retention" to `0` OR you can [extend PocketBase](https://pocketbase.io/docs/use-as-framework/) and hide/redact the IPs in the logs by using the `LogsDao()` before save callbacks, something like:

```go
package main

import (
	"log"

	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/daos"
	"github.com/pocketbase/pocketbase/models"
)

func redactLog(eventDao *daos.Dao, m models.Model) error {
	requestModel, ok := m.(*models.Request)
	if !ok {
		return nil
	}

	requestModel.UserIp = "[demo_redact]"
	requestModel.RemoteIp = "[demo_redact]"
	requestModel.UserAgent = "[demo_redact]"
	requestModel.Referer = "https://pocketbase.io"

	return nil
}

func main() {
	app := pocketbase.New()

	app.OnAfterBootstrap().Add(func(e *core.BootstrapEvent) error {
		app.LogsDao().BeforeCreateFunc = redactLog
		app.LogsDao().BeforeUpdateFunc = redactLog

		return nil
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}

```
