### ISSUE TITLE
Access oauth2 refresh tokens alongside accessTokens

### ISSUE THREAD

**Issue by 1danielcoelho** [pocketbase/pocketbase#1487]
Hello!

I'm trying to build a small app that involves using oauth2 to sign in with Twitter, but also retain tokens and access the Twitter API "offline" (without the user being actively logged in). 

I can receive the access token via the return value of `authWithOAuth2`, however the refresh token is nowhere to be found. These access tokens expire in 60 days I believe, so I want to be able to refresh them.

I assume that that `accessToken` value returned from `authWithOAuth2` is in fact the final access token that is returned by the oauth login workflow (and not just the authorization token), so at that point it is too late for me to request the refresh tokens myself. 

I think I can retrieve the intermediate *authorization* token (the 'code' in the url search params on the redirect page), but I don't think there is any way of securely retrieving the access/refresh token pair directly from the Twitter oauth2 endpoints and then handle the login purely on the frontend, as I'd need the Twitter client secret to make the request. 

Is there any way of retrieving those refresh tokens and/or refreshing those accessTokens? This is sort of blocking my entire app.

(Also that wouldn't be what `pb.collection(collectionIdOrName).authRefresh()` does, would it?)

Thanks!

**Comment by ganigeorgiev** [comment]
I'll consider returning the refresh token alongside the access token in the OAuth2 user response in the next release (most likely at the end of this week).

> Also that wouldn't be what `pb.collection(collectionIdOrName).authRefresh()` does, would it?

No, the `authRefresh()` call is only for the PocketBase token and user data.

**Comment by ganigeorgiev** [comment]
The refresh token was added in the v0.11 branch (`filter-enhacements`).

**Comment by 1danielcoelho** [comment]
Wow, that is crazy! Thank you so much for the instant response and commit!

Looking forward to the next release then, that's awesome.
