### ISSUE TITLE
Unexpected empty data object in error response for failed authentication

### ISSUE THREAD

**Issue by jerebtw** [pocketbase/pocketbase#1488]
I have noticed that when an authentication attempt fails, the returned error object does not contain the expected data. This makes it difficult to determine the root cause of the failure.

Example error object:
```json
{
  "url": "https://x.de/api/collections/users/auth-with-password",
  "status": 400,
  "data": {
    "code": 400,
    "message": "Failed to authenticate.",
    "data": {}
  },
  "isAbort": false,
  "originalError": null,
  "name": "ClientResponseError 400"
}
```

The code i used:
```ts
try {
	const record = await pb
		.collection("users")
		.authWithPassword("Test@gmail.com", "TestTestTestTest");
	console.log(record);
} catch (e) {
	console.error(e);
	console.error(JSON.stringify(e, null, 2));
}
```

**Comment by ganigeorgiev** [comment]
The auth error messages are deliberately generic to prevent to some extend accounts enumeration (see for example the owasp recommendations - https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-and-error-messages).

You can find a more detailed error log in the "Admin UI > Logs" and/or when starting PocketBase with `--debug`.

**Comment by jerebtw** [comment]
Okay, thanks 😄

**Comment by jerebtw** [comment]
Maybe it would be good if the explanation would be added to the docs
