### ISSUE TITLE
[Admin GUI] Duplicate content in the admin settings

### ISSUE THREAD

**Issue by SimonLoir** [pocketbase/pocketbase#1498]
Hello, I found a bug in the settings section of the admin GUI. 

The steps to reproduce can be found in the following gif : 
![ezgif-3-0c90912505](https://user-images.githubusercontent.com/17649337/210852555-ace84bdc-79bd-43a4-80a2-f1d592ceaac7.gif)
- Go to the "Auth providers" page in the settings section of the admin panel
- Enable a sign-in method
- Leave the client secret and client id blank
- Click "Save changes"
- Go to the logs page (or any other page)

It happens when switching from the auth providers page to an other page if an error occured before. 
If the user provides valid information afterwards, the bug does not occur.

**Comment by ganigeorgiev** [comment]
Thank you. I've submitted a fix in the temporary v0.11.0 branch (`filter-enhancements`) and it will be available with the next release soon.
