### ISSUE TITLE
#Number field validation

### ISSUE THREAD

**Issue by mcaple** [pocketbase/pocketbase#1504]
Created a number field with a minimum value of 0 and a maximum of 200 and made the field non empty.

If I now create a record and set this field to 0, when I hit save I get an error saying 'Missing required value.'

**Comment by ganigeorgiev** [comment]
This is similar to https://github.com/pocketbase/pocketbase/issues/1360, https://github.com/pocketbase/pocketbase/issues/1011, https://github.com/pocketbase/pocketbase/issues/907 and probably others.

In short, it is working as intended. When you mark a number as "Nonempty" it will require the field value to be != 0 (there is a toolltip alongside the toggle that explains what the constraints will require).

Note that PocketBase doesn't store `null` for field values (with exception for the `json` field type) and uses zero-defaults (table with the supported values could be found in https://pocketbase.io/docs/collections/#overview).

In any case, the "Nonempty" was renamed to "Nonzero" to make it more clear in the upcoming v0.11 release branch (`filter-enhancements`).

**Comment by mcaple** [comment]
Thanks for that, was so excited to offer some feedback. Will look through closed issues next time. Awesome product!
