### ISSUE TITLE
Feature Request: Add link to Website/Docs to Admin UI

### ISSUE THREAD

**Issue by TimHi** [pocketbase/pocketbase#1523]
Starting with Pocketbase I find myself going to the docs a lot and a lot of time it's from the admin ui, clicking on the version number, clicking on the repo, clicking on the website, clicking on Documentation (one could argue that I make this complicated myself).

I think there is enough free space to add a link to the website/docs next to the version number in the corner:
![image](https://user-images.githubusercontent.com/10931525/211171795-ae27cbc3-32cb-4d22-9542-6b73b0112525.png)

**Comment by ganigeorgiev** [comment]
I'm not sure how useful that would be but I'll consider it in a future version.

_Just for info, if you haven't figured it out already, you can find documentation for each individual collection by clicking on the "API Preview"._

**Comment by TimHi** [comment]
I saw it, but my personal preference is having the full doc page open. But I understand this is really a QoL feature from my pov, not sure how others handle it.

**Comment by ganigeorgiev** [comment]
Added it `master`.

**Comment by TimHi** [comment]
That was insanely fast, thank you! :D
