### ISSUE TITLE
Serving pocketbase from a  reverse proxy in a route other than root route `/` always resolves to 404 not found

### ISSUE THREAD

**Issue by Mr-M1M3** [pocketbase/pocketbase#1524]
Recently, I've been trying to serve pocketbase in `/pocket` route. I've set up an NginX config to do so, however, I always get 404 not found error. My NginX config kind of looks like this:

```
server {
        listen 80;
        listen [::]:80;

        server_name {MY_DOMAIN} www.{MY_DOMAIN};

        return 302 https://$server_name$request_uri;
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        ssl_certificate /etc/ssl/website/public.pem;
        ssl_certificate_key /etc/ssl/website/private.pem;

        server_name {MY_DOMAIN} www.{MY_DOMAIN};

        root /var/www/html/;

        index index.html index.htm;

        location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-By $remote_addr;

                proxy_pass "http://127.0.0.1:4000";
        }

       location /pocket {
               proxy_set_header Host $http_host;
               proxy_set_header X-Forwarded-By $remote_addr;

               proxy_pass "http://127.0.0.1:8090";
       }

}
```

What I think is, when we pass request came to `/pocket` route, the URL pathname does not change. So, we are hitting indirectly to a route that doesn't exist in pocoetbase ( which kinda look like this to `pocketbase` when we want admin dashboard: `/pocket/_`). Is there a way to fix it from NginX itself? Or, pocketbase needs some change?

**Comment by hungcrush** [comment]
What if we use sub domain ? `pocket.yourdomain.com` 😬 😬

**Comment by ganigeorgiev** [comment]
@Mr-M1M3 Ah, I think you need a rewrite rule, eg.:

```nginx
location /pocket {
    rewrite ^/pocket(.*) /$1 break;

    ...
}
```

**Comment by Mr-M1M3** [comment]
> @Mr-M1M3 Ah, I think you need a rewrite rule, eg.:
> 
> ```nginx
> location /pocket {
>     rewrite ^/pocket(.*) /$1 break;
> 
>     ...
> }
> ```

Hey, that doesn't seem to be working. Can you provide full locatio context? Also, are you sure that the regex is the correct one? Shouldn't the regex end with with a $ sign?

**Comment by ganigeorgiev** [comment]
@Mr-M1M3 Sorry, I haven't tested the above. It was just an example. I'll try to find sometime next week to test the subpath setup in more depth and eventually update the nginx example config.

And yes, the regex should end with `$`. For more complete examples you can check https://www.nginx.com/blog/creating-nginx-rewrite-rules/.

**Comment by Mr-M1M3** [comment]
> @Mr-M1M3 Sorry, I haven't tested the above. It was just an example. I'll try to find sometime next week to test the subpath setup in more depth and eventually update the nginx example config.
> 
> And yes, the regex should end with `$`. For more complete examples you can check https://www.nginx.com/blog/creating-nginx-rewrite-rules/ and https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite.

Thanks for your concern ^_^ ^_^ ^_^

**Comment by Mr-M1M3** [comment]
@ganigeorgiev Hello, I managed to fix it by the help of ChatGPT. ChatGPT told me turn `proxy_redirect` to off and it worked justas expected. Sorry, for not mentioning that, although other valid api routes returned 404, visiting `/pocket/_` redirected to `/_`.

**Comment by sonyarianto** [comment]
Hi, I do like this in Nginx.

```
location /v2 {
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    proxy_read_timeout 180s;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://service-pocketbase:8090;
  }
```

when I access using api.xxx.com/v2 it display like this.

```
{
    "code": 404,
    "message": "Not Found.",
    "data": {}
}
```

What I am missing here? Thanks in advance.

**Comment by ganigeorgiev** [comment]
@sonyarianto I think you may need a rewrite rule before the `proxy_pass` directive, something like:

```nginx
rewrite /v2/(.*) /$1  break;
```

**Comment by sonyarianto** [comment]
@ganigeorgiev wow thank you for quick answers :) It works now. Just share mine here.

```
location /v2 {
    rewrite /v2/(.*) /$1  break;

    proxy_set_header Connection '';
    proxy_http_version 1.1;
    proxy_read_timeout 180s;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-By $remote_addr;

    proxy_pass http://service-pocketbase:8090;
  }
```

then now I can access it via https://api.xxxxx.com/v2/_/

Now I have /v1 (back-end using PHP), /v2 (back-end using Pocketbase), /v3 (back-end using pure Go), /v4 (back-end using Rust) etc hahaha. Nice :)

Again thank you @ganigeorgiev for Pocketbase.
