### ISSUE TITLE
Protect access file url storage With Authorization token

### ISSUE THREAD

**Issue by triadmoko** [pocketbase/pocketbase#1527]
Hey, I recently learned about Pocketbase and I'm really fond of its ease of use.
how to protect my file using public storage url. Only certain users can access the file?

**Comment by ganigeorgiev** [comment]
Private/Protected files are currently not supported but it is planned for v0.13/v.14.

You can subscribe/watch issue https://github.com/pocketbase/pocketbase/issues/215.
