### ISSUE TITLE
Feature request: custom email notifications 

### ISSUE THREAD

**Issue by BarishNamazov** [pocketbase/pocketbase#1546]
Hi, I have been using pocketbase and enjoying it so far, thanks for the efforts!

I was wondering what you think about custom email notifications (sent to given email) that happen after a rule is satisfied during create/update. A very simple case is a notification on create. It would be very helpful when I want to know when there's a new record (could be e.g. a new user or a new survey result entered), or want to notify my user when there's new record related to them. I understand that email templating and more complex cases require adding and keeping track of new variables (some possibly exposed to the template, e.g. the total number of records), but I believe access to variables like those in API rules/filters can be made to work most of the cases.

This is something that can be done with extending the api by implementing routes in Go, but I think it could be a neat feature in pocketbase.

**Comment by ganigeorgiev** [comment]
This will be handled eventually in https://github.com/pocketbase/pocketbase/issues/317.
