### ISSUE TITLE
Feature request: Add IP localization to dashboard

### ISSUE THREAD

**Issue by peterscodee** [pocketbase/pocketbase#1549]
## Proposal
I would like to request a new feature that adds country flags behind IP addresses in the dashboard for better analysis.

One of the key benefits of this feature would be the ability to quickly and easily identify the geographical location of each IP address. This information can be useful for a variety of purposes, such as analyzing traffic patterns, identifying potential security threats, and optimizing performance.

In addition, displaying this information directly in the dashboard would provide a more visual and intuitive way of understanding the data, making it easier to analyze and draw insights from the IP address information.

 In the future, this feature could be extended to include region-level data and charts for even more granular analysis.

I believe this feature would be valuable for many users and hope it can be implemented in a future update. 

## Solution
I have done some initial research and believe that this feature can be implemented relatively easily.
- It is not feasible to utilize an API service for this project due to prohibitive licensing terms or costs
- After researching various options, I have found that https://lite.ip2location.com/ is a good solution for this use case
- This solution does not utilize an API. Instead, it offers regularly updated IP databases which can be downloaded locally. The downloaded database in a bin format can be accessed and searched through a provided package for searching. To ensure the data remains current, it is recommended to download the database BIN file on a monthly basis. The lite version of this solution is sufficient for our needs and the paid version is not required. It should be noted that a disclaimer must be included in the dashboard indicating that the data is sourced from ip2location.com for IP address lookup purposes.

## Example
Download the database under https://download.ip2location.com/lite/ 
(direct link: https://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.BIN.ZIP)
This should be done once a month.

Go code to research the country of the IP:
```go
package main

import (
	"fmt"
	"github.com/ip2location/ip2location-go/v9"
)

func main() {
	db, err := ip2location.OpenDB("./IP2LOCATION-LITE-DB1.BIN")

	if err != nil {
		fmt.Print(err)
		return
	}
	ip := "8.8.8.8" //replace with desired ip
	results, err := db.Get_all(ip)

	if err != nil {
		fmt.Print(err)
		return
	}

	fmt.Printf("country_short: %s\n", results.Country_short)
	fmt.Printf("country_long: %s\n", results.Country_long)

	db.Close()
}

```

Output: 
```
country_short: US
country_long: United States of America
```

**Comment by ganigeorgiev** [comment]
This for now is out of the scope for v1.

It adds very little to the project, while having too many cons:

- it will increase the binary size with ~2-3mb
- it requires regular updates of the prebuilt executables and I don't want to force the user to download a newer version (_we don't have automatic updates yet_)
- it could slow down log writes (or will have to implement some post-processing mechanism)
- it requires attribution (_and I'm not sure whether this attribution could be only in the PocketBase doc/site or will need to be place inside the dashboard so that its available with each distribution_)
