### ISSUE TITLE
Proposal: Use jsondiff in tests to have clear output

### ISSUE THREAD

**Issue by iamelevich** [pocketbase/pocketbase#1559]
For now when you are running tests and have some errors it's pretty hard to find out difference due to big JSON. For example: migrations failed test output:
![CleanShot 2023-01-10 at 22 28 22@2x](https://user-images.githubusercontent.com/46163087/211666222-9c3b2a7d-3b86-428a-be92-f9373f696b9f.png)
It's not easy to find where is an error. So I propose to use https://pkg.go.dev/github.com/nsf/jsondiff or similar tool to simplify test writing job.

Will be glad to hear your thoughts.

**Comment by ganigeorgiev** [comment]
Thanks for the suggestion but I don't think the extra dependency is worth the effort.

We can eventually integrate a more sophisticated testing and assert framework in the future, but for now the std go test utils and output are good enough.
