### ISSUE TITLE
Could I change the system fields (id)

### ISSUE THREAD

**Issue by Ahmed-Abdella** [pocketbase/pocketbase#1560]
I am building a blog, and I use pocketbase the problem comes when I want to get one post, I need the URL parameter to be a slug instead of the id, now I can't get the post using getOne since it requires the id. Can the id be changed to the slug instead?

**Comment by ganigeorgiev** [comment]
No, the `id` once set can't be changed.

You can create instead a custom unique `text` field `slug` and use the `getFirstListItem()` to query it, eg. something like:

```js
const record = await pb.collection('example').getFirstListItem(`slug="${slug}"`);
```

**Comment by Ahmed-Abdella** [comment]
Now it works, thanks a lot
