### ISSUE TITLE
Bug: Copy button on export collections page does not actually copy to clipboard

### ISSUE THREAD

**Issue by jdiaz0705** [pocketbase/pocketbase#1572]
I thought it was a client issue, but I have noticed on Windows 11, MacOS Big Sur, and Linux Mint that the collections copy button does not work. This isn't a huge deal, but I thought I would just add it to the list! :smile:

**Comment by jdiaz0705** [comment]
I just checked on Firefox 108 and Chrome 108 in both normal and incognito mode on Linux Mint. Checked again on Windows Chrome 108 in Incognito mode and still can't click to copy. No errors in console.

Just to confirm, I am clicking this button and trying to paste elsewhere.
![image](https://user-images.githubusercontent.com/38111327/211848501-db884de9-4fa0-436e-a3d3-86280befdd1b.png)

I did just notice that I am quite a bit behind on PocketBase v0.9.2... This may be the problem. Thanks for looking in to it.

**Comment by ganigeorgiev** [comment]
What do you mean "can't click to copy"? Can you reproduce it in the live demo - https://pocketbase.io/demo

Is the button not accessible? Maybe is a z-index issue but I can't reproduce it.

The "Copy" button will not work on older browsers that don't have the `Navigator.clipboard` API or browsers that don't allow access to the clipboard.

**Comment by jdiaz0705** [comment]
I can click the copy button. The notification appears that it copied to clipboard, but it doesn't actually copy to my clipboard. 

I tested on the live demo and was not able to reproduce. It must be a version issue or client side. 

Thanks again.
