### ISSUE TITLE
Support encryption - SQLCIPHER

### ISSUE THREAD

**Issue by zakaria-chahboun** [pocketbase/pocketbase#1584]
First of all Thanks for this amazing project 🌷

I want to try `pocketbase` with my project which is a desktop application.
Is there any plan to support encryption  `SQLCIPHER`?

**Comment by ganigeorgiev** [comment]
No, at least for v1 there are no plans to add support for the `SQLCIPHER` extension out of the box.

To be honest I'm not even sure how this will work with the cgo-free sqlite driver that we are using by default. You may wan to check https://gitlab.com/cznic/sqlite/-/issues/105.
