### ISSUE TITLE
CLI schema import

### ISSUE THREAD

**Issue by auroraanna** [pocketbase/pocketbase#1587]
I would like to be able to import pocketbase schemas from the commandline in addition to the GUI. This would help in automating setting up pocketbase.

**Comment by ganigeorgiev** [comment]
With v0.9+ we have external JS migrations support in addition to the [Go migrations](https://pocketbase.io/docs/migrations/) (_more documentation will be available with v0.13/v0.14 release and the support for JS app hooks_).

You can use `./pocketbase migrate collections` to export a snapshot of all your collections configuration. The file will be created in a `pb_migrations` directory and all migrations inside it will be automatically executed on `serve`.
