### ISSUE TITLE
Integration Google Cloud Stograge

### ISSUE THREAD

**Issue by triadmoko** [pocketbase/pocketbase#1595]
Hi, I really enjoy using pocketbase. I've been using it in a number of projects lately. I have problems with storage. currently pocketbase supports AWS-S3 cloud storage. Are there any additional features for integration with Google-Cloud-Storage in the near future?

**Comment by ganigeorgiev** [comment]
PocketBase has integration with any S3 API compatible storage, not just AWS.

As far as I know, GCS has optional S3 interop api, but I haven't tested it and I'm not sure if it works.

Support for other storage mechanisms for now is not planned.
