### ISSUE TITLE
Feature request: case-insensitive unique columns

### ISSUE THREAD

**Issue by helenfufu** [pocketbase/pocketbase#1602]
Would it be feasible to add an option for case-insensitivity to the unique option on columns (beyond only the default for `auth.username`)? 

Use case: I currently have a column `{collection}.username`, which I have marked as unique. I've been writing custom logic to check case-insensitive uniqueness as I noticed the  `IsRecordValueUnique` is only case-insensitive for `auth.username` [here](https://github.com/pocketbase/pocketbase/blob/c1921aeef8b28f9df66d5be3143e0c39dd079bec/daos/record.go#L172-L174) and case-_sensitive_ for all other collections/fields. It would be very helpful to have a generalizable case-insensitive unique option for any column. How I imagine this might look: have a toggle on admin UI for each column to be either `Unique (Case Sensitive)`  or `Unique (Case Insensitive)`, where the `Case Insensitive` option would make `expr` [here](https://github.com/pocketbase/pocketbase/blob/c1921aeef8b28f9df66d5be3143e0c39dd079bec/daos/record.go#L186) take on a similar form as the `auth.username` `expr` [above](https://github.com/pocketbase/pocketbase/blob/c1921aeef8b28f9df66d5be3143e0c39dd079bec/daos/record.go#L172-L174). This would be immensely helpful to avoid implementing manually, and from first glance seems doable simply by extending logic (? please lmk if wrong) 

Did a bit of browsing and saw two similar discussions:
1. https://github.com/pocketbase/pocketbase/discussions/638 - which I have been referencing for manual case-insensitivity checks.
2. https://github.com/pocketbase/pocketbase/issues/627 - which does not concern me too much as I think the case-insensitive uniqueness feature would still be beneficial ASCII only.

I didn't see any exact duplicate issues/discussions, but sorry if I missed something. Thanks in adv for considering!

**Comment by ganigeorgiev** [comment]
I'm not sure about this. For now this is out of the roadmap because it will be confusing since it will work only with ASCII characters and the `text` field.

I already have it in my todo to think for a better control over the unique constraints since currently you can't also ignore zero-values, but that will be handled together with #542 and #544.

**Comment by helenfufu** [comment]
Thanks for the context and workaround. Understood why unique constraints require some extra thought beyond this request.

Follow-up Q: Do you have a suggestion for how to best handle uniqueness errors from both the collection's field schema (case sensitive, configured via Admin UI) and the workaround index (case insensitive, configured via the custom migration)? When the case sensitive unique constraint is violated, I am able to catch the specific error in `OnBeforeApiError` with something like
```go
	violatesUniqueConstraint := false
	if errorOnUsername, ok := apiError.Data["username"]; ok {
		if errorOnUsername, ok := errorOnUsername.(map[string]string); ok {
			violatesUniqueConstraint = errorOnUsername["code"] == "validation_not_unique"
		}
	}
	if violatesUniqueConstraint {
		...
	}
```
because the API error looks like
```json
{
    "code": 400,
    "message": "Failed to create record.",
    "data": {
        "username": {
            "code": "validation_not_unique",
            "message": "Value must be unique."
        }
    }
}
```
If possible, I'd also like to catch the specific case-insensitive error (based on your suggested index workaround), but only see
```json
{
    "code": 400,
    "message": "Failed to create record.",
    "data": {}
}
```
despite this error in the logs `2023/01/15 12:59:49 UNIQUE constraint failed: index 'idx_example_table_username'`. The returned error does not give much to go on beyond the code or message. Is there an alternative to simply catching all `400 Failed to create record` errors and assuming they're due to either one of the unique constraint violation?

I've tried seeing if the other lower level hooks get triggered for either error, i.e. catching the errors / adding extra validation at the request level with `OnRecordBeforeCreateRequest` or DB level with `OnModelBeforeCreate`, but no luck since I don't even see these hooks getting triggered; so far have only been able to catch the error at the API level 🤔

**Comment by helenfufu** [comment]
@ganigeorgiev Thanks for the context and workaround. Understood why unique constraints require some extra thought beyond this request.

Follow-up Q: Do you have a suggestion for how to best handle uniqueness errors from both the collection's field schema (case sensitive, configured via Admin UI) and the workaround index (case insensitive, configured via the custom migration)? When the case sensitive unique constraint is violated, I am able to catch the specific error in `OnBeforeApiError` with something like
```go
	violatesUniqueConstraint := false
	if errorOnUsername, ok := apiError.Data["username"]; ok {
		if errorOnUsername, ok := errorOnUsername.(map[string]string); ok {
			violatesUniqueConstraint = errorOnUsername["code"] == "validation_not_unique"
		}
	}
	if violatesUniqueConstraint {
		...
	}
```
because the API error looks like
```json
{
    "code": 400,
    "message": "Failed to create record.",
    "data": {
        "username": {
            "code": "validation_not_unique",
            "message": "Value must be unique."
        }
    }
}
```
If possible, I'd also like to catch the specific case-insensitive error (based on your suggested index workaround), but only see
```json
{
    "code": 400,
    "message": "Failed to create record.",
    "data": {}
}
```
despite this error in the logs `2023/01/15 12:59:49 UNIQUE constraint failed: index 'idx_example_table_username'`. The returned error does not give much to go on beyond the code or message. Is there an alternative to simply catching all `400 Failed to create record` errors and assuming they're due to either one of the unique constraint violation?

I've tried seeing if the other lower level hooks get triggered for either error, i.e. catching the errors / adding extra validation at the request level with `OnRecordBeforeCreateRequest` or DB level with `OnModelBeforeCreate`, but no luck since I don't even see these hooks getting triggered; so far have only been able to catch the error at the API level 🤔

**Comment by ganigeorgiev** [comment]
Since it is a DB error we are not returning it directly in the response because it could contain sensitive information.

You can access and overwrite the response errors using the [`OnBeforeApiError`](https://pocketbase.io/docs/event-hooks/#app-hooks) hook but it may not be so "easy" to detect the unique field error (unless manually checking the error message). One hacky workaround could be (_I haven't tested it_):

```go
app.OnBeforeApiError().Add(func(e *core.ApiErrorEvent) error {
	apiError, _ := e.Error.(*apis.ApiError)

	// modify the error response data
	if apiError.RawData().(error).Error() == "UNIQUE constraint failed: index 'idx_example_table_username'" {
		apiError.Data["username"] = map[string]string{
			"code":    "validation_not_unique",
			"message": "Value must be unique.",
		}
	}

	return nil
})
```
