### ISSUE TITLE
mime type filter doesn't work for markdown files

### ISSUE THREAD

**Issue by TeFiLeDo** [pocketbase/pocketbase#1619]
I tried to create a collection with a file field and set the mime type field to `text/markdown`. 

Then I tried to create a record, however I only get this message: `The following mime types are only allowed: text/markdown.`

It doesn't matter whether the file name ends in `.md` or `.markdown` either.

**Comment by ganigeorgiev** [comment]
You can find all supported validator mimetypes in https://github.com/gabriel-vasile/mimetype/blob/master/supported_mimes.md.

It seems that markdown is not in the list. You can try opening an [issue/PR in the upstream library](https://github.com/gabriel-vasile/mimetype) but I'm not sure how the validation will work to be honest and whether it will be possible to reliable detect the mimetype only based on the content of the file.

My recommendation would be to use `text/plain` or `text/html` instead.

**Comment by TeFiLeDo** [comment]
Ah, I understand, thank you. 

Might be a good idea to mention that list in the UI, and only allow supported mime types in the field.
