### ISSUE TITLE
Make api.authResponse method public

### ISSUE THREAD

**Issue by iamelevich** [pocketbase/pocketbase#1623]
### Problem
Hard to implement custom auth the same way as in core package, because some methods are private.

### Proposition
Make authResponse method public to have ability return the same auth response as pocketbase.
https://github.com/pocketbase/pocketbase/blob/c1921aeef8b28f9df66d5be3143e0c39dd079bec/apis/record_auth.go#L54

**Comment by ganigeorgiev** [comment]
I'll consider exporting it in the next v0.12.0 release.

**Comment by ganigeorgiev** [comment]
The method was exported as `apis.RecordAuthResponse(app, httpContext, record, meta)` in the `develop` branch and it will be available with the next v0.12.0 release soon.

**Comment by ganigeorgiev** [comment]
The method was exported as `apis.RecordAuthResponse(app, httpContext, record, meta)` in the `develop` branch and it will be available with the next v0.12.0 release soon.
