### ISSUE TITLE
Feature Request: Show which file is failing the upload

### ISSUE THREAD

**Issue by jnatmorris** [pocketbase/pocketbase#1651]
As I'm working on uploading hundreds of csv files, to soon be thousands of files, into pocketbase being able to upload many files together is amazing. I thank the developers for making that possible.

One feature that would be very helpful when uploading masses of files is to be able to see which file exactly is failing to pass the MIME type check. Noting here, that while all my files have the proper .csv ending some files are still failing the check, probably due to my clumsiness, not PB. I'm not suggesting to upload all other files and hold back the one(s) that are  failing, but just to visually see a border around, or underline below, the failing file(s) would be an amazing addition. 

Cheers!

**Comment by ganigeorgiev** [comment]
This will be a breaking change if we update the error response format for the file upload validators and for now I don't think it is worth doing it.

A more detailed upload error message were added in the `develop` branch that should help identifying more easily the failed upload.
