### ISSUE TITLE
[filter rules]: `@now` doesn't seem to work correctly

### ISSUE THREAD

**Issue by anhtuank7c** [pocketbase/pocketbase#1653]
I have a collection that have a `published` field type `Date`.

I would like to limit data by filter rules to just able list all the data which have `published < @now`.
I set the collection rules to `@collection.posts.published < @now`, the problem comes right away.
* If the collection contains any documents that have published in the future (`> @now`), query will always return an empty result
* If the collection contains all documents that have published in the past (`< @now`), query return data as expected.

I wonder this is an issue or am I miss something?
I having PocketBase version `0.11.3`

**Comment by ganigeorgiev** [comment]
PocketBase [v0.11.0+](https://github.com/pocketbase/pocketbase/releases/tag/v0.11.0) comes with multi-match/match-all support.

When you apply the filter `@collection.posts.published < @now` it will require every record from the `posts` collection to satisfy the condition. If you want "any/at least one of" type of constraint you can prefix the operator with `?` (_this will be documented better in the near future):

```
@collection.posts.published ?< @now
```

Also please note that the `@collection` filter is a "join" filter allowing you to filter unrelated collection records. If in your case `published` is a direct field in your collection then you can just use:

```
published < @now
```

More info about the filters you can find in https://pocketbase.io/docs/api-rules-and-filters/#filters-syntax.

**Comment by anhtuank7c** [comment]
@ganigeorgiev Amazing.
Thank you so much for your support.
