### ISSUE TITLE
Feature Request: Duplicate the Existing Collections and Records

### ISSUE THREAD

**Issue by mmv-dev** [pocketbase/pocketbase#1656]
Hi there,
Great work with pocketbase❤️.

## **Feature** : Duplicate
Just a small request, when we select the record on the dashboard, it only shows "delete" option, please add "duplicate" option as well if possible. Same to be done for collections as well. 

## **Why**
If we make schema changes in the dashboard, the logic may break. This will enable us to make schema changes without interfering with the logic that is currently in place. And makes iteration much easier and flexible.

Cheers

**Comment by jnatmorris** [comment]
I'd love to see this too extended to collections such that it's possible to "copy and paste" the SQL table structure (column names, types, ect...)  rather than pain stinkingly redeclaring the same table structure in another collection. Only portion I'd be uncertain of copying is the relations, but still copying the relations column.

**Comment by ganigeorgiev** [comment]
A "Duplicate" dropdown option for Collections and Records was implemented in the `develop` branch and will be available with the next v0.12.0 release.

**Comment by mmv-dev** [comment]
> A "Duplicate" dropdown option for Collections and Records was implemented in the `develop` branch and will be available with the next v0.12.0 release.

Awesome, thanks

**Comment by hungcrush** [comment]
@ganigeorgiev After duplicated, it will create new Collection with empty record. So what do you think if we allow change `Field Type` ? Now we can't change the field type
![CleanShot 2023-01-26 at 13 56 26](https://user-images.githubusercontent.com/8098916/214775214-b38d75db-4ab9-4541-b7eb-99215f59e071.png)

**Comment by ganigeorgiev** [comment]
@hungcrush Thanks, I'll consider resetting the field ids on duplicate to allow editing.
