### ISSUE TITLE
Feature request: "expand" query parameter when subscribe to collections or records.

### ISSUE THREAD

**Issue by mmv-dev** [pocketbase/pocketbase#1657]
It would be awesome if we could add an option to expand when subscribed to a collection or a record. This would save the extra api calls when we have a multiple relationships in the record.

Cheers

**Comment by mmv-dev** [comment]
Is there any technical difficulty in implementing this feature? If so can you provide an alternative solution to work with.

**Comment by ganigeorgiev** [comment]
Is there any technical difficulty in implementing this feature?

I have some performance concerns and will have to research it a little more. Eventually this will be handled together with https://github.com/pocketbase/pocketbase/issues/527 to allow providing a `?filter` like support to the realtime api, but other tasks for now are with higher priority (_if you haven't already, you can check the current tasks priority and roadmap in https://github.com/orgs/pocketbase/projects/2_).

>  If so can you provide an alternative solution to work with.

On realtime change event you can send a regular `getOne(e.record.id, { expand: "..." })` request.

**Comment by ZedLove** [comment]
@ganigeorgiev Are you suggesting using `getOne()` (or similar `async` record method) inside the callback passed to `subscribe()`? If so, it seems like the type for the callback should be broadened to include `async` functions, as it currently only expects a function of this type: `(data: RecordSubscription<T>) => void`

**Comment by YugoCode** [comment]
@ZedLove @ganigeorgiev I'm also trying to fetch data from the database on a realtime change event, but I get `"Cannot use keyword 'await' outside an async function"`. Here is my SvelteKit code:

```
	onMount(async () => {
		pb.collection('boards').subscribe('*', function (e) {
			let records = await pb.collection('cards').getFullList('', {
				filter: `board.project.id="${projectID}"`,
				expand: 'board'
			});

			let transformedData = transformKanbanData(serializeNonePOJOs(records));
			data = {
				tasks: transformedData
			};
		});
	});
```

How can I fix this issue? Thanks! :)

**Comment by ganigeorgiev** [comment]
@YugoCode You can wrap it in a local `async` function.

Returning a `Promise` in the callback doesn't make much sense, although I agree that is not very convenient and I'll consider eventually changing the return types during the planned realtime refactoring in the near future.

**Comment by danibjor** [comment]
> @ZedLove @ganigeorgiev I'm also trying to fetch data from the database on a realtime change event, but I get `"Cannot use keyword 'await' outside an async function"`. Here is my SvelteKit code:
> 
> ```
> 	onMount(async () => {
> 		pb.collection('boards').subscribe('*', function (e) {
> 			let records = await pb.collection('cards').getFullList('', {
> 				filter: `board.project.id="${projectID}"`,
> 				expand: 'board'
> 			});
> 
> 			let transformedData = transformKanbanData(serializeNonePOJOs(records));
> 			data = {
> 				tasks: transformedData
> 			};
> 		});
> 	});
> ```
> 
> How can I fix this issue? Thanks! :)

You should also use the cleanup function to avoid memory leaks.

// we need to scope the unsubscription variable outside the onMount, so we can reach it when un mounting the component / cleaning up.
var unsubscribe;

onMount( () => {
	// wrap the async stuff
	const subscribe = async () => {
		unsubscribe = pb.collection('boards').subscribe('*', function (e) {
			let records = await pb.collection('cards').getFullList('', {
				filter: `board.project.id="${projectID}"`,
				expand: 'board'
			});
			let transformedData = transformKanbanData(serializeNonePOJOs(records));
			data = {
				tasks: transformedData
			};
		});
	}
});

// not sure what the correct lifecycle method is (don't know too much Svelte), but something like
onUnMount(() => {
	// clean up and unsubscribe to avoid memory leaks
	unsubscribe && unsubscribe();
})

**Comment by raizdev** [comment]
I hope this will be implemented aswell.

**Comment by jorishaenseler15** [comment]
I am also pretty interested in the feature to filter in realtime 😎🤩

**Comment by ganigeorgiev** [comment]
Experimental `filter`, `expand`, `fields`, custom query and headers parameters support for the realtime subscription was added in the `develop` branch. There are some minor polishing details that needs to be done, but if you are curious you can test it with the [v0.20.0-rc prerelease](https://github.com/pocketbase/pocketbase/releases/tag/v0.20.0-rc).
