### ISSUE TITLE
in collections api, recored paggination is not working correctly

### ISSUE THREAD

**Issue by alinapso** [pocketbase/pocketbase#1659]
on PB v0.11.3 

when calling the api api/collections/<collection-name>/records?page=2&perPage=20
I have 5

 recoreds in the collection, I was expecting to get empty result, but for some reason it is returning the same resualt as ?page=1&perPage=20

![1-20](https://user-images.githubusercontent.com/57593645/213888550-6d3b8bfc-b657-4423-a3ee-ca9658c88d1f.png)
![2-20](https://user-images.githubusercontent.com/57593645/213888552-d449e162-bb5f-4a45-a7aa-81cab7f697dd.png)

**Comment by ganigeorgiev** [comment]
This is working correctly. The `page` query parameter is normalized and automatically "capped" to the max possible number so even if you provide 99999 for example it will always return the `totalPages` page results (in your case that is 1).
