### ISSUE TITLE
Is it possible to add periodic action?

### ISSUE THREAD

**Issue by manishionc** [pocketbase/pocketbase#1662]
I want to add entry on a specific time given by the user.

**Comment by IceWreck** [comment]
Yeah, use pocketbase as a go framework then add a ticker or use some cron like go library to run jobs at a time.

**Comment by ganigeorgiev** [comment]
As IceWreck mentioned, you'll have to [use Go and PocketBase as framework](https://pocketbase.io/docs/use-as-framework/) (_option to bind to the app hooks with JS will be also available in the future_).
