### ISSUE TITLE
Is it possible to use webhooks ?

### ISSUE THREAD

**Issue by manishionc** [pocketbase/pocketbase#1663]
I want to add a new record using a web hook for certain things is it possible?

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand your use case, but if you [use PocketBase as framework](https://pocketbase.io/docs/use-as-framework) you'll be able to bind to the [app hooks](https://pocketbase.io/docs/event-hooks/) and [fetch/create/update/delete records using the Dao helpers](https://pocketbase.io/docs/record-methods/).

Alternatively, if you have a SSR node stack, you can also attach to your webhook with it and just send a request from the node server to PocketBase to update your data.
You can also authorize as admin with the SDKs, eg.: `pb.admins.authWithPassword(...)` (admins have access to everything and API rules don't apply for them).
