### ISSUE TITLE
Bug: OAuth2 sign up makes AuthStore null

### ISSUE THREAD

**Issue by Guiguerreiro39** [pocketbase/pocketbase#1676]
Hello,
I'm experimenting with Sveltekit and Pocketbase and, when trying to sign up a user using OAuth2 (specifically Github), everything goes well except that the AuthStore, when trying to redirect to the home page, becomes empty, meaning the user is not authenticated and thus sent to the login page again (since my '/' is a protected route). I've checked and, when performing the actions in the redirect, the AuthStore is set accordingly as well as the `pb_auth` token but immediately gone after the redirect happens... Below is a video demonstrating this. I've tried several possible solutions but without any success:
- Take out the hooks for protected routes
- Try to set headers to response and send the response with a redirect
- AuthStore.refresh()

This only happens when performing the sign up of the user using OAuth2. After the first try, the login using OAuth2 works perfectly.

```js
/* server.ts /redirect */
export const GET: RequestHandler = async ({ locals, url, cookies }: RequestEvent) => {
	const redirectURL = `${url.origin}/redirect`;
	const authMethods = await locals.pb?.collection('users').listAuthMethods();
	const code = url.searchParams.get('code') || '';
	const state = url.searchParams.get('state') || '';

	if (!authMethods?.authProviders) {
		console.error('No auth providers');
		throw redirect(303, '/login');
	}

	const provider = authMethods.authProviders.find((p) => p.name === cookies.get('providerName'));

	if (!provider) {
		console.error('Provider does not exist');
		throw redirect(303, '/login');
	}

	if (cookies.get('providerState') !== state) {
		console.error('State does not match');
		throw redirect(303, '/login');
	}

	if (!locals.pb) {
		console.error('Pocketbase not initialized');
		throw redirect(303, '/login');
	}

	try {
		await locals.pb
			?.collection('users')
			.authWithOAuth2(provider.name, code, provider.codeVerifier, redirectURL);
	} catch (err) {
		console.error('Error while logging with auth provider: ', err);
		throw redirect(303, '/login');
	}

	throw redirect(303, '/')
};
```

```js
/* hooks.ts */
const pocketBaseHandler: Handle = async ({ event, resolve }) => {
	event.locals.pb = new PocketBase('http://127.0.0.1:8090');
	event.locals.pb.authStore.loadFromCookie(event.request.headers.get('cookie') || '');

	if (event.locals.pb.authStore.isValid) {
		event.locals.user = event.locals.pb.authStore.model;
	}

	const response: Response = await resolve(event);

	// TODO: secure before deployment
	response.headers.set('set-cookie', event.locals.pb.authStore.exportToCookie({ secure: false }));

	return response;
};

const protectedRoutesHandler: Handle = async ({ event, resolve }) => {
	if (event.route.id?.startsWith('/(app)') && !event.locals.pb?.authStore.isValid) {
		throw redirect(303, '/login');
	}

	if (event.route.id?.startsWith('/(auth)') && event.locals.pb?.authStore.isValid) {
		throw redirect(303, '/');
	}

	return await resolve(event);
};
```

https://user-images.githubusercontent.com/11543544/214281925-a79beee9-910e-4eb1-a1ef-b060d43d2407.mov

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the issue locally by following the plain JS example in https://pocketbase.io/docs/authentication/#web-oauth2-integration/.

The problem here I think is related to the thrown redirect and how browsers handle the cookie `SameSite=strict` policy. You can find similar discussion in https://github.com/pocketbase/pocketbase/discussions/903#discussioncomment-4369424.

To confirm that the authStore is actually updated you can try also to `console.log(locals.pb.authStore.isValid)` right after the `authWithOAuth2` call.
