### ISSUE TITLE
Feature Request: Darkmode

### ISSUE THREAD

**Issue by snorresovold** [pocketbase/pocketbase#1696]
A lot of devs use darkmode on most of their tools, Pocketbase is one of a few tools that don´t have darkmode. This hurts devs eyes and is very uncomfortable.

I´ll fork the project and work on this a bit myself but i thought an issue would be appropriate.

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/407.

Dart mode for now is very low priority (at least until we stabilize the API and UI changes).
If you haven't already, you can check the current roadmap and tasks priority in https://github.com/orgs/pocketbase/projects/2.
