### ISSUE TITLE
Too many redirections

### ISSUE THREAD

**Issue by spy16** [pocketbase/pocketbase#1704]
I am using Pocketbase as framework along with SvelteKit (with `adapter-static`) for frontend.

I want to embed the svelte build into the final binary itself and serve it.

```golang
package main

//go:generate yarn
//go:generate yarn build
//go:embed all:build/**
var embedFS embed.FS

func main() {
	app := pocketbase.New()

	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.StaticFS("/", echo.MustSubFS(embedFS, "build"))
		return nil
	})

        _ = app.Start()
}
```

To ensure svelte generates properly nested (`app/index.html` instead of `app.html`, etc.), i have set `export const trailingSlash = "always"` as well. [Reference](https://kit.svelte.dev/docs/adapter-static#usage)

But when I open the `/app` route, it redirects to `/app/` and then keeps redirecting to same route (request URL is `/app/` and the redirection location received is also `/app/`) until `ERR_TOO_MANY_REDIRECTIONS` is hit.

Could this be bug in the trailing slash handling?

**Comment by spy16** [comment]
```curl
❯ curl localhost:8090/app/ -v
*   Trying 127.0.0.1:8090...
* Connected to localhost (127.0.0.1) port 8090 (#0)
> GET /app/ HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: /app/
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< Date: Sun, 29 Jan 2023 06:55:30 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

Even when the request is for `/app/` the server still thinks it's for `/app` and tries to send it to `/app/`.

I tried inspecting runtime values: At [this location](https://github.com/labstack/echo/blob/v5_alpha/echo.go#L515), the `URL.Path` param value actually is `/app` all the time. 

Not sure if there is a middleware or something stripping trailing slahes.

**Comment by spy16** [comment]
I think found the issue [here](https://github.com/pocketbase/pocketbase/blob/master/apis/base.go#L37):

Except for admin UI routes (i.e., `/_/`), it's stripping all trailing slashes:

```golang
e.Pre(middleware.RemoveTrailingSlashWithConfig(middleware.RemoveTrailingSlashConfig{
  Skipper: func(c echo.Context) bool {
	  // ignore Admin UI route(s)
	  return strings.HasPrefix(c.Request().URL.Path, trailedAdminPath)
  },
}))
```

**Comment by ganigeorgiev** [comment]
Instead of `e.Router.StaticFS`, use `apis.StaticDirectoryHandler`.

```go
e.Router.GET("/*", apis.StaticDirectoryHandler(os.DirFS("path/to/your/dir"), indexFallback))
```

_This will be documented better in the future (or the trailing slash middleware will be removed_).
