### ISSUE TITLE
Scroll bar not visible after login

### ISSUE THREAD

**Issue by jerebtw** [pocketbase/pocketbase#1719]
If you edit a row and then delete the browser cookies and save the changes, you will be taken back to the login page and when you log in again, the scroll bar will not be visible.

**Comment by ganigeorgiev** [comment]
This is related to https://github.com/pocketbase/pocketbase/issues/1718.

When closing the panel the `overlay-active` class is not getting removed. I'm currently doing some cleanup and will try to cut a little bit later a v0.12.1 release.
