### ISSUE TITLE
The Edit Form Panel need more contrast for the input fields

### ISSUE THREAD

**Issue by jonathan-martz** [pocketbase/pocketbase#1742]
My Problem is that i dont know where to click, i often edit records and in my opinion it sucks to find the Field. :D

**Comment by ganigeorgiev** [comment]
I've darkened the grey colors with ~5% in `master`:


![colors_comparison](https://i.imgur.com/V6fpBB1.png)
(left-old; right-new)

The change will be available with the next minor release sometime later this week.
