### ISSUE TITLE
verified: must be a valid value

### ISSUE THREAD

**Issue by itsgoofer** [pocketbase/pocketbase#1756]
Creating a user posting this payload

```
{
    "email": "g@gmail.com",
    "emailVisibility": true,
    "password": "12345678",
    "passwordConfirm": "12345678",
    "verified": true
}
```
I'm getting the following error (from log):

```
{
  "errorMessage": "verified: must be a valid value."
}
```

I've seen in the docs that `verified` is an optional `Boolean` param. When I try to register a user without that parameter, the user gets created and I get a status of 200. 

Ideas?

**Comment by ganigeorgiev** [comment]
Regular users can't change directly their `verified` status (only admins and those with "Manage" permissions can modify the field).

I've added it in my todo to eventually provide a more helpful error message in the future.
