### ISSUE TITLE
Feature Request : Keycloak OAuth2/OIDC support

### ISSUE THREAD

**Issue by mskarbek** [pocketbase/pocketbase#1760]
Hi, I would like to be able to authenticate in PocketBase with Keycloak-based OIDC implementation.
I would like to implement that functionality and close this issue with PR.

**Comment by ganigeorgiev** [comment]
User contributions for external OAuth2 providers are welcomed.

As a reference you can use the latest OAuth2 integrations like:

- Gitea #1643: https://github.com/pocketbase/pocketbase/commit/4c73e16f5404383ed73aa13d4643b477f68ff48e

- Authentik #1377: https://github.com/pocketbase/pocketbase/commit/6d08a5f36fb92ac00409c9405a7c8d0d5f9f18d5

(_you can ignore the generated ui/dist files_)

**Comment by mKlooney** [comment]
Hello,
would be really nice, thought about it too, but first come first served.
@mskarbek let me know if I can support you!

**Comment by ganigeorgiev** [comment]
As noted in https://github.com/pocketbase/pocketbase/pull/1806#issuecomment-1425551536, a dedicated Keycloak provider may not be actually necessary and a generic OIDC one should suffice.

I'll consider renaming the existing Authentik OAuth2 provider to OIDC in the next v0.13.0 release.
