### ISSUE TITLE
Incorrect error: (Empty) value must be unique

### ISSUE THREAD

**Issue by babakfp** [pocketbase/pocketbase#1766]
![Screenshot 2023-02-03 174529](https://user-images.githubusercontent.com/44144724/216740027-66db4c1b-402a-4539-8009-cdfccbfc83eb.png)

**Comment by babakfp** [comment]
![Screenshot 2023-02-03 174932](https://user-images.githubusercontent.com/44144724/216740102-cbdf9624-3a3c-47f5-9019-b153054a34ca.png)

**Comment by ganigeorgiev** [comment]
I think this is similar to https://github.com/pocketbase/pocketbase/issues/1755.

Most likely you probably have another record with empty videos.
