### ISSUE TITLE
Feature Request: Android server

### ISSUE THREAD

**Issue by abdulhakam** [pocketbase/pocketbase#1768]
Hi, as you know older android devices(from about 2013?) are pretty capable enough to be used as home servers, unfortunately, they are either thrown away or are put in some box to be found years later, but still working( as in my case found 6 of em) even though hardware-wise they can be use as home servers for smart home servers or data storages. if there could be a pocketbase like android app which could be able to store files locally and also provide restish api to access that, it would give another use to those old devices.( although there are some solutions such as using termux to run linux to run pocketbase, some device don't allow it). there are some server software for android but they are not open source.

**Comment by ganigeorgiev** [comment]
I haven't tested it, but you can try with the `armv7` and `arm64` linux builds from the ["Assets" section in the releases page](https://github.com/pocketbase/pocketbase/releases).

If the above doesn't work, then you can try to build PocketBase on the android device on your own following the instructions from https://github.com/pocketbase/pocketbase#running-and-building.


The non-cgo driver (when `CGO_ENABLED=0`) can run only on the following platforms:

```
$GOOS   $GOARCH
darwin  amd64
darwin  arm64
freebsd amd64
freebsd arm64
linux   386
linux   amd64
linux   arm
linux   arm64
linux   ppc64le
linux   riscv64
windows amd64
windows arm64
```

The cgo driver (when `CGO_ENABLED=1`) should be able to run on any go GOOS (including android) and GOARCH targets:

```
$GOOS     $GOARCH
aix       ppc64
android   386
android   amd64
android   arm
android   arm64
darwin    amd64
darwin    arm64
dragonfly amd64
freebsd   386
freebsd   amd64
freebsd   arm
illumos   amd64
ios       arm64
js        wasm
linux     386
linux     amd64
linux     arm
linux     arm64
linux     loong64
linux     mips
linux     mipsle
linux     mips64
linux     mips64le
linux     ppc64
linux     ppc64le
linux     riscv64
linux     s390x
netbsd    386
netbsd    amd64
netbsd    arm
openbsd   386
openbsd   amd64
openbsd   arm
openbsd   arm64
plan9     386
plan9     amd64
plan9     arm
solaris   amd64
windows   386
windows   amd64
windows   arm
windows   arm64
```

**Comment by rohitsangwan01** [comment]
@abdulhakam @ganigeorgiev i think this would be helpful 
https://rohitsangwan.hashnode.dev/run-pocketbase-from-mobile
