### ISSUE TITLE
Set max length of username

### ISSUE THREAD

**Issue by quandabase** [pocketbase/pocketbase#1769]
Current username max length is 150 chars,  it's too long.
How to set max length of username?

**Comment by ganigeorgiev** [comment]
This is not supported at the moment (_I'll consider exposing the username regex in v0.13/v0.14, which should allow to also specify a min/max length_).

As a workaround for now, if you want to limit the username length, you can do it client-side or overwrite/filter the value with a [before model/record event hook](https://pocketbase.io/docs/event-hooks/).
