### ISSUE TITLE
Feature Request: Pocketbase Upgrade command

### ISSUE THREAD

**Issue by TitoMitto** [pocketbase/pocketbase#1782]
It would be nice to have a way to upgrade to the latest pocketbase version. This could be modeled like`deno upgrade` where whenever a new version of pocketbase has been released the upgrade command helps in downloading and setting up the old pb_data folder to be able to use the new version of pocket base. The command `pocketbase upgrade` could be a time saving addition

**Comment by ganigeorgiev** [comment]
It is already in the [roadmap](https://github.com/orgs/pocketbase/projects/2).

The existing temp `upgrade` command eventually will be repurposed but for now this is a low priority.

**Comment by TitoMitto** [comment]
Thanks for the fast feedback
