### ISSUE TITLE
need help with filter, roles

### ISSUE THREAD

**Issue by raizdev** [pocketbase/pocketbase#1789]
How does roles work?

For example, I've created role field with option (super-admin, manager) in users collection.
What I want is that only super-admin can retrieve the fulll list and the specific users without the admin role only their row.

image

I tried to use @request.auth.role = 'super-admin' but the list is still empty

**Comment by ganigeorgiev** [comment]
_Closing since this seems the same as https://github.com/pocketbase/pocketbase/discussions/1787._
