### ISSUE TITLE
Overlay Issue on User's Settings

### ISSUE THREAD

**Issue by ChrisLegaxy** [pocketbase/pocketbase#18]
![image](https://user-images.githubusercontent.com/34526718/177960153-9a92efca-de51-4eb2-9565-4a4cd5e096e6.png)

I see there's a minor overlay issue with the `New Collection Button` when we have more collections.

I think it can be fixed by changing the `.app-sidebar` class z-index from 1 -> 2

Haven't get the chance to really dive down into the codebase, so no PR from my side 😅

**Comment by ganigeorgiev** [comment]
This should be fixed in v0.1.1
