### ISSUE TITLE
Allow custom file extensions

### ISSUE THREAD

**Issue by joranmulderij** [pocketbase/pocketbase#1816]
Could you make it so that users can define a custom file extension as the filter? I don't know if there is a reason for this, but it should just be possible to select a list of file extensions instead of a list of mime types.

**Comment by ganigeorgiev** [comment]
The file extension cannot be trusted and files aren't required to have them.

In v0.12.0+ the file options in the Admin UI were updated so you should be able to search the mime type by the extension:

![file options](https://i.imgur.com/sedV0XS.png)
