### ISSUE TITLE
Proposal to add HTTP3 support to Pocketbase using Quick-Go

### ISSUE THREAD

**Issue by dxvid-pts** [pocketbase/pocketbase#1818]
Pocketbase is a powerful backend that provides efficient and scalable data storage and retrieval. However, as of now, it does not support the HTTP3 protocol. In light of the recent advancements in web technologies and the increasing popularity of HTTP3, it is imperative to add support for this protocol to Pocketbase.

I propose that we add HTTP3 support to Pocketbase using the [Quick-Go](https://github.com/quic-go/quic-go) library. Quick-Go is an open-source library that provides a fast and easy way to integrate HTTP3 into Go-based applications. It provides a comprehensive set of functions and abstractions that simplify the process of adding HTTP3 to existing Go applications.

The addition of HTTP3 support to Pocketbase would greatly enhance its functionality and make it a more versatile and efficient tool for web developers. Moreover, it would keep Pocketbase up-to-date with the latest advancements in web technologies and ensure that it remains a competitive and valuable tool for years to come.

Please let me know your thoughts on this proposal, and if there is anything else I can do to help. Thank you for your time and consideration

**Comment by ganigeorgiev** [comment]
Thank you for the suggestion but for now this is out of the scope and I'd prefer first this to be implemented in the standard library - https://github.com/golang/go/issues/32204, rather then relying on an external dependency just for this.

There are plans in the future to expose the api initialization and make it more granular, which will eventual allow users to start whatever http listener they want, but this is currently a very low priority.

If you haven't already, you can check our roadmap and current tasks priorities in https://github.com/orgs/pocketbase/projects/2.
