### ISSUE TITLE
Feature request: API authentication via cookie

### ISSUE THREAD

**Issue by yawaramin** [pocketbase/pocketbase#1825]
It would be very useful to be able to authenticate and get back a cookie. Any web client is configured to handle them will greatly simplify the process of using the API. E.g. suppose it worked like this:

```
$ alias client='curl --cookie cookies.txt --cookie-jar cookies.txt'
$ client --include -d "identity=$EMAIL_ADDR" -d "password=$PASSWORD" http://127.0.0.1:8090/api/admins/auth-with-password
HTTP/1.1 200 OK
Set-Cookie: token=a.long.auth.token
...other headers...

{"admin":{...
```

Then we could take advantage of automatic cookie management to authenticate on every request:

```
# Automatically send the `token` cookie
$ client http://127.0.0.1:8090/api/...
```

This is of course just using curl's built-in cookie jar, any reasonable web client (like a browser) has some form of automatic cookie management built-in.

Note that this is backwards-compatible with the current flow. People who want to continue using the `Authorization` header can do so.

**Comment by ganigeorgiev** [comment]
Sorry, there are no plans at least for now to add integrated support for cookies.

If you want to allow authorization as cookie, you can check https://github.com/pocketbase/pocketbase/discussions/989#discussioncomment-4109411.
Similarly, you can also attach another middleware that will write the auth cookie to the response before returning it to the client.

**Comment by yawaramin** [comment]
Understood, thank you.
