### ISSUE TITLE
Suggestion: role based data returns

### ISSUE THREAD

**Issue by Mellbin** [pocketbase/pocketbase#1828]
Hi, 

I've been using PocketBase for a non-profit org that organizes BOYC LAN events and so far i've been loving working with it.

I did run into to a pickle not far back when I wanted to have a Admin page for viewing all the users that have registered etc.
This was that I wanted their emails to show up so email vis had to be set to true, and it works fine by setting up the user that way.

But my thinking was that there should be some way to make decisions on what data to return depending on the user that makes the request.

A full list for admins and a "normal" list for users would work but I think it would be even better to have some custom logic on what data gets returned etc.

**Comment by ganigeorgiev** [comment]
I don't understand what do you mean by "have some custom logic on what data gets returned".

You can control and filter what data the user can see based on your collection API rules.
**API rules acts acts also as records filter!**
Additionally, there is nothing stopping you to create a "role" field in your `users` collection and set a rule like:

```js
@request.auth.role = "manager" && status="active"
```

The above will math records that:

- have `status` "active"
- the authenticated user has role "manager"

More information and some examples on the possible access controls could be found in https://pocketbase.io/docs/collections/#auth-collection.

---

_Roles for the admins accounts for now are out of the scope for v1, but it is in my todo to consider it once the other more major tasks are completed._

**Comment by Mellbin** [comment]
Sorry for being unclear in the first message,

What I meant was having column level security added to the api.

table:
Email, age, phone, username.

"admin" list, (not pocketbase admin but in moderator or whatever you would like to call it"

Email, age, phone, username.

"user list"

Age, username.

So if a "user" uses the API, only 2 cols will be returned, but the "admin" will get the whole table returned.

**Comment by ganigeorgiev** [comment]
This is not planned since it is not clear based on what and how the constraints will be applied.

You can manually filter the response fields if you attach to the available record app hooks - https://pocketbase.io/docs/event-hooks/#record-crud-api-hooks (to overwrite the default response body you have to call `hook.StopPropagation`).

In the next v0.13.0 release there will be support for a new "View" collection type, that will allow creating a new collection from subset of another collection fields (_or composite of multiple ones_).

**Comment by Mellbin** [comment]
Thanks for the response, the "View" collections sounds like a really good feature.

And thanks again for all the work you have put in on PocketBase!
