### ISSUE TITLE
React Native and Realtime

### ISSUE THREAD

**Issue by redbaron76** [pocketbase/pocketbase#1830]
First of all, thank you for your great tool!

Then, is there any known issue with React Native and Realtime subscriptions?
Anytime I try to `.subscribe(...)`, a `Possible Unhandled Promise Rejection` rises and in console I find a `ReferenceError: Property 'EventSource' doesn't exist`.

Did not find any reference in the Documentation about it.
thanks

**Comment by ganigeorgiev** [comment]
`EventSource` is not available natively in React Native and you'll have to load  a polyfill. For example:

```js
import eventsource from "react-native-sse";

global.EventSource = eventsource;
```

This and other caveats can be found in https://github.com/pocketbase/js-sdk#nodejs-via-npm.
