### ISSUE TITLE
Feature Request: Changing Sorting on collections 

### ISSUE THREAD

**Issue by Jomyy** [pocketbase/pocketbase#1855]
at the moment the newest item just sits on top of the list 
maybe add an option to reverse this so the newest item is on the bottom

**Comment by ganigeorgiev** [comment]
Do you mean the collections in the sidebar or the table listing with the collection records?

If it is the latter, you can change the sort of the records in the table by clicking on the column headers.

Changing the sorting of the collections in the sidebar was requested previously but it may clutter the UI unnecessary and for now it is out of the scope. Eventually in the future we may add a dropdown/toggle option near the sidebar search panel to allow changing the order, but for simplicity currently the following "auto" sort behavior is applied:
- show the collections in the following order by their type: "auth", "base", "view" (_will be available in the next release_)
- sort by their created date ASC, aka. the last created will be at the bottom of the list within its type group

**Comment by duytbp** [comment]
@ganigeorgiev Should we make it sorted by type then by name (instead of created_date)? 

I think it's common that we prefix table name with feature/module. For example: `hr_` or `survey_`

**Comment by ganigeorgiev** [comment]
@duytbp Hm, I use the `created` field since newly created collections will always be appended within their group and the behavior is predictable, but maybe sort by name would be more intuitive. I'm not really sure, I'll have to think a little more on it.

**Comment by Jomyy** [comment]
I think you should be able to sort it by different factors like date created and date created in reverse and so on

**Comment by duytbp** [comment]
For my case I have some tables added much later as the schema evolves, and navigating collections is just a little bit inconvenient

Appreciate for your work on PocketBase. I hope you have enough time away from computer and enjoy life

**Comment by showtime73** [comment]
.
