### ISSUE TITLE
404 when trying authWithPassword

### ISSUE THREAD

**Issue by deyvidm** [pocketbase/pocketbase#1862]
Fellas, what am I doing wrong. I followed the docs precisely, yet my console shows a 404 when trying to auth with Password. 
```
<!DOCTYPE html>
<html>
<body>
    <script src="./pocketbase.umd.js"></script>
    <script type="text/javascript">
        const pb = new PocketBase('http://127.0.0.1:8090');
        pb.admins.authWithPassword("deyvidm@gmail.com", "abc123123")
    </script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/16841661/219390408-d95efed5-afbc-4a62-9b06-ec9eea000511.png)

I'm running Firefox 109.0.1 on Linux Mint 21.1

Latest Pocketbase is running on local:8090 

All ideas are welcome! I hate to pollute the issues page with user error

**Comment by ganigeorgiev** [comment]
I'm not sure how to reproduce the issue.

Are you able to access the PocketBase Admin UI and sign-in from there?

If yes, could you inspect the request data and compare it to your call ("Inspect tool > Network > {find the auth-with-password request} > Headers" )?

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the 404 error.

The only way I can think the `authWithPassword()` call could return 404 is if you are using an older (< 0.8.0) PocketBase executable version (you can find your current PocketBase version in the bottom-right corner of the Admin UI or run `./pocketbase --version`).

If that's not the case, please provide a minimal reproducible repo and I'll try to investigate it.

**Comment by deyvidm** [comment]
thank you gani, it seems I was wrong. my Pocketbase version was way behind the latest release! thanks for the quick replies.

**Comment by ganigeorgiev** [comment]
If you want to preserve your existing data, you can check the [Migrate from v0.7.x guide](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md#migrate-from-v07x) (the temp `upgrade` command is still available with the latest binaries, so you should be able to directly migrate to the latest version).
