### ISSUE TITLE
typo: logs page ("referer")

### ISSUE THREAD

**Issue by Bellisario** [pocketbase/pocketbase#1875]
On logs page I see the word "referer" but it should actually be written "referrer".

**Comment by ganigeorgiev** [comment]
The "referer" comes from the HTTP header with the same name - https://en.wikipedia.org/wiki/HTTP_referer.

It is indeed a misspelling but it is a common thing and I'm not sure if it is worth fixing it:

> The proper spelling of this word is referrer. It was misspelled years ago in an earlier version of the HTTP standard, and before this was noticed and corrected, this spelling became incorporated into so much software that the Internet Engineering Task Force (IETF) chose not to correct the spelling in HTTP/1.1.
