### ISSUE TITLE
Update multiple records at once

### ISSUE THREAD

**Issue by Bouchtaoui** [pocketbase/pocketbase#1886]
Hi guys,

First, once again, thank you for this great project!
I want to know if it's possible to update multiple records at once.
For example, I have a list of todo items that can be reordered by the user. The order of the items needs to be stored every time the user changes the order. The position of each item is stored in a record property "index". That's why I need to update multiple records with their new index value. _(If you guys know a better and more efficient technique, let me know)_

I just use vanilla JS by the way and PB JS SDK.

**Comment by ganigeorgiev** [comment]
Transactional bulk create/update/delete is not supported via the web APIs at the moment and you have to send individual update requests for each record.

You can also check https://github.com/pocketbase/pocketbase/discussions/1642, https://github.com/pocketbase/pocketbase/discussions/1594, and others.
