### ISSUE TITLE
Add support for ACID transaction to JavaScript SDK

### ISSUE THREAD

**Issue by ryu-man** [pocketbase/pocketbase#1892]
Currently, Pocketbase supports CRUD operations on a single entity, which is not ideal for scenarios where you need a lot of changes to be applied as one block, and for that ACID transitions are needed, It will be a great addition to implement this feature

**Comment by ganigeorgiev** [comment]
Bulk transactional create/update/delete will be eventually handled as part of #48.

_You can also check https://github.com/pocketbase/pocketbase/issues/580, https://github.com/pocketbase/pocketbase/discussions/1642, https://github.com/pocketbase/pocketbase/discussions/1108 and probably others._
