### ISSUE TITLE
PocketBase Resets everytime

### ISSUE THREAD

**Issue by YusufSuleman** [pocketbase/pocketbase#1909]
Hello, Everytime I close PocketBase with ^C. It resets all data is lost. How do I fix this, I am on Arch Linux btw (Arch btw is a joke in the Arch Community, had to do it.). Installed from the AUR. It happens to a certain point. The first time, it fully reseted to default. Now, it had reseted to an empty base with one less column. How do I fix this?

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean. There is no official aur PcoketBase package I don't recommend using it. Download the binary for your platform from the [GitHub releases page](https://github.com/pocketbase/pocketbase/releases) or https://pocketbase.io/docs/.

Make sure that you have read/write access to the `pb_data` directory. By default this directory will be created next to the executable. If you want to change the directory location, use the `--dir` flag.
