### ISSUE TITLE
Client-side SDK for Go

### ISSUE THREAD

**Issue by humanfriend22** [pocketbase/pocketbase#1928]
Since `pocketbase` allows users to integrate it into their own buisness logic, it would make sense to allow said logic to modify the database. I can't seem to find a way to do this directly with `pocketbase.New()` but I've probably missed something.

If this is not the case, a client side SDK for Go would be much appreciated. Currently, I am using the rest api to interact with the database.

**Comment by trevorstarick** [comment]
You should be able to either use the info mentioned here: https://pocketbase.io/docs/database along with https://pocketbase.io/docs/collection-methods/ and https://pocketbase.io/docs/record-methods/; or if you're adventurous, connect directly to the database via your SQLite driver of choice (by default Pocketbase uses https://pkg.go.dev/modernc.org/sqlite unless you explicitly have CGO enabled which in that case it uses https://pkg.go.dev/github.com/mattn/go-sqlite3)

**Comment by ganigeorgiev** [comment]
@humanfriend22 There is no official client-side SDK for Go. A community one exists (see https://github.com/pocketbase/pocketbase/discussions/995#discussioncomment-4186108) but I haven't tested it and cannot provide support for it.

As trevorstarick mentioned, If you want to extend PocketBase with your own custom business logic, please check the provided link. For general overview, if you haven't already, you could read https://pocketbase.io/docs/use-as-framework/.

**Comment by humanfriend22** [comment]
Thank you, I don't know how I missed that! I can't seem to find how to list all records in a collection in the docs. I tried `app.Dao().RecordQuery(collection).All(&records)` but it's giving me a memory error

**Comment by ganigeorgiev** [comment]
@humanfriend22 Please open a new [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with the exact error and a little more details what you are doing. It is hard to tell what is the issue without a complete context how and when you run the above code.

Also keep in mind that `app.Dao()` can be accessed only after the application has been started or bootstrapped, aka. you need to wrap the above in an [`OnBeforeServe` or  `OnAfterBootstrap` hook](https://pocketbase.io/docs/event-hooks/):

```go
app.OnAfterBootstrap().Add(func(e *core.BootstrapEvent) error {
    // do something with the app.Dao()...

    return nil
})
```

The above is mentioned in the [godocs of `pocketbase.New()`](https://pkg.go.dev/github.com/pocketbase/pocketbase#New), but I'll consider documenting it better in the near future.

**Comment by humanfriend22** [comment]
Yes, I found that I had to use `e.App.Dao` instead of `app.Dao`:
```go
app.OnAfterBootstrap().Add(func(e *core.BootstrapEvent) error {
    // do something with the e.app.Dao()...

    return nil
})
```

**Comment by ganigeorgiev** [comment]
@humanfriend22 `e.App.Dao()` and `app.Dao()` both refer to the same struct.

The bootstrap event guarantees that the database connection, the app settings, etc. has been initialized and ready for use.
