### ISSUE TITLE
Support for fts5

### ISSUE THREAD

**Issue by jet10000** [pocketbase/pocketbase#193]
Thanks

**Comment by tryffel** [comment]
Actually, fts5 would provide some considerable benefits, e.g.:
- search all columns
- logical operators 
- trigram tokenizer (experimental, simple typo tolerant search) 

But I doubt that these are not actually implemented in the Go native build?

**Comment by ganigeorgiev** [comment]
@tryffel [modernc.org/sqlite](https://gitlab.com/cznic/sqlite) seems to have the extension enabled by default - https://gitlab.com/cznic/sqlite/-/blob/master/generator.go#L158, but this doesn't seem to be the case with [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3) and you'll need to use the `fts5` build tag if you have CGO enabled.

I don't mind creating a custom build and allow the fts5 integration by default, but there are other things that I'm not sure how to integrate them properly without complicating too much the internals:

- We have to research how to manage the fts5 virtual table. As far as I know, sqlite doesn't allow `ALTER` constraints after the virtual table is created so this practically means that we will have to drop and recreate it every time when a new collection field is renamed/added/removed.
- Most of the time you don't need a full text search so probably this should be a Collection option if we decide to implement it.
- We have to decide on non ambiguous syntax to use with the filters, preferably a unique token that doesn't require lookahead parsing.

Personally, I rarely have a need for full text search support and I think it will lead to a lot of complications and therefore, at least for v1.0.0, I don't plan to work on it, but if anyone else have the time to work on this, please share and outline your ideas before proceeding.

I still think that a simple `LIKE/NOT LIKE` wildcard query is more than enough for most applications, but if someone really needs a full text support in their app, for now I would recommend to use a specialized library like [bleve](https://github.com/blevesearch/bleve) or [bluge](https://github.com/blugelabs/bluge).

**Comment by hakim89** [comment]
Actually I came across PocketBase because I was looking at other solutions similar to Firebase that does offer FTD where Firebase does not offer this feature. If you want FTS in firebase they tell you to go use third party application like Elasticsearch or similar. 

FTS being native to SQLite gives PocketBase a huge advantage and I think this is a great idea to implement. Or maybe some help in the right direction on how to do a custom build with FTS flags enabled.

**Comment by Odas0R** [comment]
I agree @ganigeorgiev. Haven't tried `pocketbase` yet, but from what I can see you can quickly build an FTS endpoint by extending the go app. 

Just set some hooks on the data you want to index, update the documents of those indexes and create a simple API that queries those documents (using X,Y,Z libraries like the ones mentioned above).

Isn't that the idea? Or will this not work?

**Comment by sonovice** [comment]
Since pocketbase is also usable as a framework, I would really appreciate having the FTS5 extension. Even if it is (for now) not exposed to any pocketbase endpoints, it would be of great value in case of custom endpoints/functions.

**Comment by ganigeorgiev** [comment]
@sonovice The fts5 extension is already enabled by default in the non-cgo sqlite version but there are no built-in mechanisms in PocketBase to manage the full-text views and develops have to handle it on their own. If you are building with `CGO_ENABLED=1`, you'll also have to use the `fts5` tag, aka. `go build -tags "fts5"`.

For a low-level db access, you can find some examples in https://pocketbase.io/docs/database/ and the [dbx package](https://pkg.go.dev/github.com/pocketbase/dbx).

**Comment by sonovice** [comment]
@ganigeorgiev Thanks for the fast response. However, excecuting something like
```go
q := app.Dao().DB().NewQuery("CREATE VIRTUAL TABLE search USING fts5(id, title, content);")
if _, err := q.Execute(); err != nil {
    fmt.Printf("%v", err)
}
```
 using pocketbase as a framework, I get the error `no such module: fts5`. Since I merely used pocketbase by importing `"github.com/pocketbase/pocketbase"` like in the examples from the documentaion, shouldn't it use non-cgo with FTS5 enabled by default?

**Comment by ganigeorgiev** [comment]
@sonovice

>  shouldn't it use non-cgo with FTS5 enabled by default?

It depends on your Go installation. You can check the `CGO_ENABLED` env variable whether cgo is enabled. To run without cgo:
```
CGO_ENABLED=0 go run main.go serve
```

**Comment by sonovice** [comment]
@ganigeorgiev Indeed, I had to explicitly set the env var to disable cgo. Works now, thank you.

**Comment by rodydavis** [comment]
On thing you can do with the virtual table is not use it to store the column names but rather a single virtual table for all collections or a virtual table per collection.

This is how I offer fts5 for a collection client side in SQLite:
https://github.com/rodydavis/firestore_sqlite/blob/df29015df0715dc5e92d8eaaf68ab9cfc4a9c03d/lib/src/database/sql/search.drift

**Comment by rodydavis** [comment]
Last night I was able to make a drop in file that can add fts5 to any collection. You need to extend PocketBase with go, and build with the correct tag in cgo.

```
go run --tags "fts5" . serve
```

It is as simple as adding the file to your project and importing it:

```go
package main

import (
	"github.com/pocketbase/pocketbase"
	"github.com/rodydavis/pocketbase_extensions/plugins"
)

func main() {
	app := pocketbase.New()
        
        // Add a list of collections to add the index for and keep up to date
	plugins.FullTextSearch(app, "posts", "documents")
	...
        if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

This will create a virtual fts5 table and keep it up to date with any record or collection changes.

It also exposes a route where you can search from the client:
`http://127.0.0.1:8090/api/collections/[COLLECTION_NAME_OR_ID]/records/fts?search=[FTS5 QUERY HERE]`

Code for the plugin:

```go
package plugins

import (
	"fmt"
	"strings"

	"github.com/labstack/echo/v5"
	"github.com/pocketbase/dbx"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/models"
)

// https://www.sqlite.org/fts5.html#external_content_tables
func FullTextSearch(app *pocketbase.PocketBase, collections ...string) {
	app.OnAfterBootstrap().Add(func(e *core.BootstrapEvent) error {
		for _, target := range collections {
			err := createCollectionFts(app, target)
			if err != nil {
				app.Logger().Error(fmt.Sprint(err))
				return err
			}

		}
		return nil
	})
	app.OnCollectionAfterCreateRequest().Add(func(e *core.CollectionCreateEvent) error {
		target := e.Collection.Name
		for _, col := range collections {
			if col == target {
				err := createCollectionFts(app, target)
				if err != nil {
					app.Logger().Error(fmt.Sprint(err))
					return err
				}
			}
		}
		return nil
	})
	app.OnCollectionAfterUpdateRequest().Add(func(e *core.CollectionUpdateEvent) error {
		target := e.Collection.Name
		for _, col := range collections {
			if col == target {
				err := deleteCollectionFts(app, target)
				if err != nil {
					app.Logger().Error(fmt.Sprint(err))
					return err
				}
				err = createCollectionFts(app, target)
				if err != nil {
					app.Logger().Error(fmt.Sprint(err))
					return err
				}
			}
		}
		return nil
	})
	app.OnCollectionAfterDeleteRequest().Add(func(e *core.CollectionDeleteEvent) error {
		target := e.Collection.Name
		for _, col := range collections {
			if col == target {
				err := deleteCollectionFts(app, target)
				if err != nil {
					app.Logger().Error(fmt.Sprint(err))
					return err
				}
			}
		}
		return nil
	})
	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		group := e.Router.Group("/api/collections/:collectionIdOrName/records", apis.ActivityLogger(app))
		group.GET("/fts", func(c echo.Context) error {
			target := c.PathParam("collectionIdOrName")
			if _, err := app.Dao().FindCollectionByNameOrId(target); err != nil {
				app.Logger().Error(fmt.Sprint(err))
				return err
			}
			tbl := target // collection.TableName()
			q := c.QueryParam("search")
			if q == "" {
				return c.NoContent(204)
			}
			var query strings.Builder
			query.WriteString("SELECT * ") // rank as '@rank'
			query.WriteString("FROM " + tbl + "_fts ")
			// query.WriteString("INNER JOIN " + tbl + " tbl ON tbl.id = " + tbl + "_fts._id ")
			query.WriteString("WHERE " + tbl + "_fts MATCH {:q} ")
			query.WriteString("ORDER BY rank;")

			results := []dbx.NullStringMap{}
			err := app.Dao().DB().
				NewQuery(query.String()).
				Bind(dbx.Params{"q": q}).
				All(&results)
			if err != nil {
				app.Logger().Error(fmt.Sprint(err))
				return err
			}
			app.Logger().Info(fmt.Sprint(results))

			c.Response().Header().Set(echo.HeaderContentType, "application/json")
			items := []map[string]any{}
			for _, result := range results {
				m := make(map[string]interface{})
				for key := range result {
					val := result[key]
					value, err := val.Value()
					if err != nil || !val.Valid {
						m[key] = nil
					} else {
						m[key] = value
					}
				}
				items = append(items, m)
			}

			// TODO: Paging result
			return c.JSON(200, items)

		})
		return nil
	})
}

func createCollectionFts(app *pocketbase.PocketBase, target string) error {
	collection, err := app.Dao().FindCollectionByNameOrId(target)
	if err != nil {
		app.Logger().Error(fmt.Sprint(err))
		return err
	}
	fields := collectionFields(collection, "id")
	exists, _ := checkIfTableExists(app, target+"_fts")
	app.Logger().Info("exists: " + fmt.Sprint(exists))

	if !exists {
		tbl := "`" + target + "`"
		var stmt strings.Builder
		stmt.WriteString("CREATE VIRTUAL TABLE " + target + "_fts USING FTS5 (")
		stmt.WriteString("  " + strings.Join(fields, ", ") + ",")
		stmt.WriteString("  content=" + target + ",")
		// stmt.WriteString("  content=''")
		// stmt.WriteString("  content_rowid='id'")
		stmt.WriteString(");")
		app.Logger().Info(stmt.String())
		if _, err := app.Dao().DB().NewQuery(stmt.String()).Execute(); err != nil {
			app.Logger().Error(fmt.Sprint(err))
			return err
		}

		stmt.Reset()
		stmt.WriteString("CREATE TRIGGER  " + target + "_fts_insert AFTER INSERT ON " + tbl + " BEGIN ")
		stmt.WriteString("  INSERT INTO " + target + "_fts(" + strings.Join(fields, ", ") + ")")
		stmt.WriteString("  VALUES (" + strings.Join(surround(fields, "new.", ""), ", ") + ");")
		stmt.WriteString("END;")
		app.Logger().Info(stmt.String())
		if _, err := app.Dao().DB().NewQuery(stmt.String()).Execute(); err != nil {
			app.Logger().Error(fmt.Sprint(err))
			return err
		}

		stmt.Reset()
		stmt.WriteString("CREATE TRIGGER  " + target + "_fts_update AFTER UPDATE ON " + tbl + " BEGIN ")
		stmt.WriteString("  INSERT INTO " + target + "_fts(" + target + "_fts, " + strings.Join(fields, ", ") + ")")
		stmt.WriteString("  VALUES ('delete', " + strings.Join(surround(fields, "old.", ""), ", ") + ");")
		stmt.WriteString("  INSERT INTO " + target + "_fts(" + strings.Join(fields, ", ") + ")")
		stmt.WriteString("  VALUES (" + strings.Join(surround(fields, "new.", ""), ", ") + ");")
		stmt.WriteString("END;")
		app.Logger().Info(stmt.String())
		if _, err := app.Dao().DB().NewQuery(stmt.String()).Execute(); err != nil {
			app.Logger().Error(fmt.Sprint(err))
			return err
		}

		stmt.Reset()
		stmt.WriteString("CREATE TRIGGER  " + target + "_fts_delete AFTER DELETE ON " + tbl + " BEGIN ")
		stmt.WriteString("  INSERT INTO " + target + "_fts(" + target + "_fts, " + strings.Join(fields, ", ") + ")")
		stmt.WriteString("  VALUES ('delete', " + strings.Join(surround(fields, "old.", ""), ", ") + ");")
		stmt.WriteString("END;")
		app.Logger().Info(stmt.String())
		if _, err := app.Dao().DB().NewQuery(stmt.String()).Execute(); err != nil {
			app.Logger().Error(fmt.Sprint(err))
			return err
		}
	}

	err = syncCollection(app, target)
	if err != nil {
		app.Logger().Error(fmt.Sprint(err))
		return err
	}

	return nil
}

func deleteCollectionFts(app *pocketbase.PocketBase, target string) error {
	var stmt strings.Builder
	stmt.WriteString("DROP TABLE IF EXISTS {:table_name}")

	app.Logger().Info(stmt.String())
	if _, err := app.Dao().DB().NewQuery(stmt.String()).Bind(dbx.Params{"table_name": target}).Execute(); err != nil {
		app.Logger().Error(fmt.Sprint(err))
		return err
	}

	return nil
}

func checkIfTableExists(app *pocketbase.PocketBase, target string) (bool, error) {
	type Meta struct {
		Name string `db:"name" json:"name"`
	}

	meta := &Meta{}

	var stmt strings.Builder
	stmt.WriteString("SELECT name FROM sqlite_master ")
	stmt.WriteString("WHERE type='table' ")
	stmt.WriteString("AND name = {:table_name};")

	app.Logger().Info(stmt.String())
	if err := app.Dao().DB().NewQuery(stmt.String()).Bind(dbx.Params{"table_name": target}).One(&meta); err != nil {
		app.Logger().Error(fmt.Sprint(err))
		return false, err
	}

	valid := meta != nil
	return valid, nil
}

func syncCollection(app *pocketbase.PocketBase, target string) error {
	var stmt strings.Builder
	stmt.WriteString("INSERT INTO " + target + "_fts(" + target + "_fts) VALUES('rebuild');")
	// stmt.WriteString("INSERT INTO " + target + "_fts SELECT " + strings.Join(fields, ", ") + " FROM " + target)
	app.Logger().Info(stmt.String())
	if _, err := app.Dao().DB().NewQuery(stmt.String()).Execute(); err != nil {
		app.Logger().Error(fmt.Sprint(err))
		return err
	}

	return nil
}

func collectionFields(collection *models.Collection, id string) []string {
	fields := []string{id}
	for _, field := range collection.Schema.Fields() {
		name := field.Name
		fields = append(fields, name)
	}
	return fields
}

func surround(items []string, prefix string, suffix string) []string {
	results := []string{}
	for i := 0; i < len(items); i++ {
		item := items[i]
		results = append(results, prefix+item+suffix)
	}
	return results
}
```

https://gist.github.com/rodydavis/d74f360f8554b898aa709152b2e0dea9

**Comment by ganigeorgiev** [comment]
_Old issues cleanup: I'm closing it as I don't plan having full text search builtin in PocketBase for now. I may reconsider it in case a more prominent or blocker use case arise but for now remains out of the scope._
