### ISSUE TITLE
Feature Request: Advanced Filtering & Sorting (qs or the like)

### ISSUE THREAD

**Issue by iocron** [pocketbase/pocketbase#1945]
Just a feature idea (because it saved us a lot of time dealing with data query filtering). It would be awesome to have some similar features of the qs library (https://github.com/ljharb/qs) for filtering and sorting. Similar to how strapi implemented it: 

https://docs.strapi.io/dev-docs/api/rest/filters-locale-publication
https://docs.strapi.io/dev-docs/api/rest/sort-pagination

**Comment by ganigeorgiev** [comment]
I don't see what qs has to do with the strapi api.
We already have `?filter` and `?sort` query parameters support.

You can find more info about the parameters in the "API preview" panel for your collection or in the generic [Web APIs docs](https://pocketbase.io/docs/api-records/).


Support for filter builder (not just string expression) is in my todo but [other tasks are with higher priority](https://github.com/orgs/pocketbase/projects/2) and for now remains out of the scope of v1.

**Comment by iocron** [comment]
@ganigeorgiev Thanks for info, I'll be looking forward to v1 and beyond :) Sadly I can't develop in golang (yet) to help, but that might change in the future.
