### ISSUE TITLE
Feature request: add a subscription for when authentication status changes (onAuthStateChange)

### ISSUE THREAD

**Issue by sagudelo1200** [pocketbase/pocketbase#195]
Thank you for this application, it is amazing!!!

This function would be very useful for handling authentication and private routes.

It is executed every time there are changes in authentication, login, logout, among others and could return an 'event' variable to identify what changed and another variable 'session' containing null if the session was closed or the object with the user data and the token.

**Comment by ganigeorgiev** [comment]
PocketBase doesn't really have sessions, so it doesn't have a logout action (it is completely stateless, we don't even keep the tokens in the database). There is already `OnUserAuthRequest` hook (see https://pocketbase.io/docs/event-hooks/#user-hooks) that is triggered every time when an auth token is generated from an API request.

Could you elaborate more on your use case?

**Comment by sagudelo1200** [comment]
Forget it, I was talking about the JS SDK but I think I'll be able to mimic this with the client.AuthStore

sorry for the issue where it doesn't belong
