### ISSUE TITLE
How To Start without "serve" argument

### ISSUE THREAD

**Issue by humanfriend22** [pocketbase/pocketbase#1963]
I am using PocketBase as a library to encapsulate my own REST API but I want to be able to just "double-click" in Finder to start my app without have to use the cli to run "./pocketbase serve". How can I achieve this within in the library itself?

Even if this isn't possible, it might be a nice feature to consider for the future.

**Comment by michal-kapala** [comment]
You could create and run a bash script that executes `pocketbase serve` or invoke the system command directly from your API controller

**Comment by humanfriend22** [comment]
Yeah, I'm actually having to write another Go script that runs my main server so I can have a cross-platform binary that I can double-click to start.

**Comment by humanfriend22** [comment]
I tried this but I can't seem to find a cross-platform solution. How do you suggest I implement your solution.

**Comment by ganigeorgiev** [comment]
@humanfriend22 If you want to start programmatically the web server, you can check https://github.com/pocketbase/pocketbase/discussions/1684.

**Comment by humanfriend22** [comment]
Thank you! It works. Here is the link for any future developers: [https://github.com/pocketbase/pocketbase/discussions/1684#discussioncomment-4776798](https://github.com/pocketbase/pocketbase/discussions/1684#discussioncomment-4776798).
