### ISSUE TITLE
support inverse relationship 

### ISSUE THREAD

**Issue by ryu-man** [pocketbase/pocketbase#1983]
Let's say we have: a `User` has many `Comment`s -> to model this we will create a relation column named `client` on the `Comment` table, this is good but we want to fetch each user with their comments.

Currently, we can declare the inverse relation by creating a relation column of type `many` named `comments` on the `User` table then we set its value to an array of comments, this is good as a workaround but it's not ideal

An ideal solution could be to introduce a new relation called `Inverse` other than `Single` and `Many`, to declare a column of this relation type we specify the target table and a column, an inverse relation should be auto-calculated when a record is created on the other side and it should not be updated manually

**Comment by ganigeorgiev** [comment]
Please check https://pocketbase.io/docs/expanding-relations/#indirect-expand.

`?filter` and `?sort` support for indirect relations is already in the [roadmap](https://github.com/orgs/pocketbase/projects/2).

**Comment by ryu-man** [comment]
that is great! except I don't know why using `comments(post)` instead of just `comments` in the results?

**Comment by ganigeorgiev** [comment]
Because you can have more than one reference to the collection.

**Comment by ryu-man** [comment]
Okay that makes sense to me
