### ISSUE TITLE
Add the current pocketable version to the admin panel

### ISSUE THREAD

**Issue by OtisGoodman** [pocketbase/pocketbase#1987]
I am in the process of writing my own pocketable SDK for Kotlin and I think it would be really nice to have the current Pocketbase version under the logo. Does this fit with your current design standards? Could I submit a pull request adding this feature?

<img width="278" alt="Screenshot 2023-03-05 at 7 38 31 PM" src="https://user-images.githubusercontent.com/34663132/223000726-cc086c06-3c04-43fe-b176-d01cb5b22e5f.png">

**Comment by ganigeorgiev** [comment]
The PocketBase version should be already available in the bottom-right corner of the Admin UI.
