### ISSUE TITLE
pocketbase serve fails to start the server on Windows 11

### ISSUE THREAD

**Issue by rudylattae** [pocketbase/pocketbase#199]
I haven't tried it on other platforms only Windows 11.

## Environment
OS: Windows 11 Home 64bit, build: 22000.795
Processor: Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz   1.50 GHz
RAM: 16.0 GB (15.8 GB usable)

## What is the observed behavior?
```powershell
❯ .\pocketbase.exe serve
> Server started at: http://localhost:8090
  - REST API: http://localhost:8090/api/
  - Admin UI: http://localhost:8090/_/
2022/07/22 23:20:14 listen tcp: lookup localhost on 192.168.1.1:53: no such host
```
It then exits.
When I go to http://localhost:8090/_/ I get "connection refused"

Output with --debug option set
```powershell
❯ .\pocketbase.exe serve --debug
[0.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
[0.00ms] CREATE TABLE IF NOT EXISTS `_migrations` (file VARCHAR(255) PRIMARY KEY NOT NULL, applied INTEGER NOT NULL)
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1640988000_init.go' LIMIT 1
[0.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
> Server started at: http://localhost:8090
  - REST API: http://localhost:8090/api/
  - Admin UI: http://localhost:8090/_/
2022/07/22 23:31:39 listen tcp: lookup localhost on 192.168.1.1:53: no such host
```

## What is the expected behavior?
I expect the server to start up and listen on the port it tried to bind to.
I expect to see the Admin UI when I go to the URL for the Admin UI.

**Comment by ganigeorgiev** [comment]
I think this is the same as in https://github.com/pocketbase/pocketbase/issues/52, https://github.com/pocketbase/pocketbase/issues/106.

It seems that on some Windows installations the `localhost` loopback address is not in the hosts file.
You could try starting the server with `127.0.0.1` instead of the default `localhost`:
```sh
.\pocketbase serve --http="127.0.0.1:8090"
```

**Comment by rudylattae** [comment]
My search-fu failed me. I didn't find those similar issues.

I will try your suggestion and report back.

Based on the responses there, I expect the workaround will succeed.

**Comment by rudylattae** [comment]
Worked! Thanks a bunch 👍
