### ISSUE TITLE
Add option to get updates for specific columns of a record in realtime 

### ISSUE THREAD

**Issue by elsacutealways** [pocketbase/pocketbase#1991]

**Comment by ganigeorgiev** [comment]
This looks similar to https://github.com/pocketbase/pocketbase/discussions/521.

At the moment the realtime subscription events will be triggered on any record change. If you want to filter the records only by a specific column, you'll have to do it manually in the subscribe callback. Eventual support similar to the `?filter` query param will be added as part of https://github.com/pocketbase/pocketbase/issues/527.

**Comment by elsacutealways** [comment]
I want to get not full records, collection has 5 columns, I need only 3 columns in realtime

**Comment by ganigeorgiev** [comment]
I understand. I may consider in the future extending the planned [`?fields` selector](https://github.com/orgs/pocketbase/projects/2?pane=issue&itemId=16153865) scope for the regular retrieve actions and add support for the realtime events, but for now this remains out of the scope.
