### ISSUE TITLE
Feature Request:  add an option to pick certain directory/drive as a file storage

### ISSUE THREAD

**Issue by Kevand** [pocketbase/pocketbase#2000]
By looking at the storage options, i realised that there is no option to change default file storage directory to any other directory/drive on
my server. That would be really usefull for pepole that use separate drive to store their files.

**Comment by ganigeorgiev** [comment]
This should be already supported but for the entire `pb_data` (aka. db file(s) + uploaded files) if you provide the `--dir` flag. You can find more info about the available flags with  `--help`.

**Comment by sshrshnv** [comment]
@ganigeorgiev Ideally, two disks can be used on the server, a fast SSD for SQLite, and a cheap HDD for media files, so I would also really like to be able to change the path only for storage.

**Comment by ganigeorgiev** [comment]
@sshrshnv For now there are no plans for this as operating on multiple different partitions could have some unintended side-effects (e.g. cross-device link errors).

For now if you really want to use a different disk for the file storage you can mount it on OS level at the `pb_data/storage` path (that is what I do currently when mounting an external volume disk in [Presentator](https://github.com/pocketbase/pocketbase/discussions/4254)).
