### ISSUE TITLE
pb_public not being served

### ISSUE THREAD

**Issue by humanfriend22** [pocketbase/pocketbase#2017]
I see in the docs' Intro, `pb_public` will be statically served at `/`. I have created `pb_public` and it's doesn't seem to work. I get a 404 Not Found error when trying to view the static files.

<img width="753" alt="Screenshot 2023-03-08 at 7 23 44 PM" src="https://user-images.githubusercontent.com/75396937/223909093-7f0286d9-0f7f-4e23-a14c-e4f965acb1ac.png">

**Comment by ganigeorgiev** [comment]
As @Nikhil1920 mentioned, if you use PocketBase as framework, make sure to register the static route as shown in the base example above.

If you are using the prebuilt executable, make sure that the process have read access to the directory.

If you are still not able to pinpoint the exact cause of the issue, please file a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details about your setup.
