### ISSUE TITLE
Feature Idea: Add Blur hash to image uploads

### ISSUE THREAD

**Issue by xRealNeon** [pocketbase/pocketbase#2024]
This could be useful to some users.
https://blurha.sh/

The Blur hash could be generated as the user uploads the image.

**Comment by ganigeorgiev** [comment]
Thank you for the suggestion but for now this is out of the scope of [v1](https://github.com/orgs/pocketbase/projects/2).

If you want to show a blurred image while loading the original, you can request a small thumb, expand it and and blur it with CSS.

**Comment by danibjor** [comment]
You can easily create the BlurHash on the client, and when saving the file, store the BlurHash alongside the file on that record. Did this a while back, worked like a charm. 

You then get the BlurHash when fetching the record, so it's ready to use. No need to go the extra mile to create it every time / or fetch thumb to create it. It's only a few characters (20-30 or so), so it's easy to defend storing it on the record next to the file.
