### ISSUE TITLE
Feature Request: simple username authentication

### ISSUE THREAD

**Issue by auliabismar** [pocketbase/pocketbase#203]
How can we add similar authentication functionality using only username and password? I only see option to authenticate using email/password and OAuth2. The background of this request is: in some places, using email considered annoying, especially in the elder society or government offices.

**Comment by ganigeorgiev** [comment]
Currently PocketBase doesn't support authentication with username and password.

This is already planned and it will be implemented in the future. You can subscribe to this issue - #120.
