### ISSUE TITLE
Feature request: Use the file upload api to handle TinyMCE's image storage 

### ISSUE THREAD

**Issue by laamfun** [pocketbase/pocketbase#2031]
Version: 0.13.2
At present, rich_editor image storage is stored in base64, which is unrealistic in actual use. Whether the function of using the file upload api to process the pictures of the rich text editor will be completed later

**Comment by laamfun** [comment]
By the way, is this feature intended to generate a corresponding field in record to manage images uploaded by the rich text editor

**Comment by ganigeorgiev** [comment]
You can check https://github.com/pocketbase/pocketbase/discussions/1975.

The file upload editor UI may change in the future but for now remains out of the scope for v1.
