### ISSUE TITLE
unique email validation bug

### ISSUE THREAD

**Issue by quandabase** [pocketbase/pocketbase#2040]
User can sign up same email by using uppercase email domain
<img width="1076" alt="Screenshot 2023-03-11 at 1 03 32 PM" src="https://user-images.githubusercontent.com/89780085/224468190-32fcff2a-6965-4750-b8ea-1a28eb388a5f.png">

**Comment by ganigeorgiev** [comment]
Emails are case sensitive. Please check https://github.com/pocketbase/pocketbase/discussions/756.
