### ISSUE TITLE
pocketbase serve error: The requested URL could not be retrieved 

### ISSUE THREAD

**Issue by bobwatcherx** [pocketbase/pocketbase#205]
command success execution , but canot open in browser
[mabok-81ms pocketbase]# ./pocketbase serve --http="127.0.0.1:8090"
> Server started at: http://127.0.0.1:8090
  - REST API: http://127.0.0.1:8090/api/
  - Admin UI: http://127.0.0.1:8090/_/

info :
os : Mabox Linux
browser : firefox 101.0.1 (64-bit)
based : arch linux

**Comment by ganigeorgiev** [comment]
I've never encountered this error before. Could you provide a little more info about your setup:
- Do you have apache/nginx running that could conflict with the localhost address?
- If you have selinux enabled (`sestatus`), could you try to temporary disable it (eg. `setenforce 0`)?
- Is there any specific reason why you have to start the executable with `127.0.0.1` and not with the default `localhost`?
- Could you also add the `--debug` flag to the command and see if a more detailed error is logged in the console?

**Comment by bobwatcherx** [comment]
> I've never encountered this error before. Could you provide a little more info about your setup:
> 
>     * Do you use a VPN/proxy?
> 
>     * Do you have apache/nginx running that could conflict with the localhost address?
> 
>     * If you have selinux enabled (`sestatus`), could you try to temporary disable it (eg. `setenforce 0`)?
> 
>     * Is there any specific reason why you have to start the executable with `127.0.0.1` and not with the default `localhost` (if there is nothing private, could you post the content of your `/etc/hosts` file)?
> 
>     * Could you also add the `--debug` flag to the serve command and see if a more detailed error is logged in the console?

solved thanks
i create new user , but verification email not send in my inbox
I want to activate less secure apps
but google has disabled it

I've set smtp to be like this:
smtp:smtp.gmail.com
ports :465
