### ISSUE TITLE
proposal: Rust SDK

### ISSUE THREAD

**Issue by Netwyn** [pocketbase/pocketbase#2050]
I would be more than willing to create the SDK, but backing from the PocketBase team would be good too.

**Comment by Netwyn** [comment]
Clarification: the SDK would be written just like the Dart or JS SDKS, just in Rust. Naming conventions would be Rust-specific, but the overall design would be the same as the other SDKs.

**Comment by ganigeorgiev** [comment]
You can check https://github.com/pocketbase/pocketbase/discussions/391.

User contributions are welcomed.
