### ISSUE TITLE
Does pocketbase provide us with native GoLang types for our collections? 

### ISSUE THREAD

**Issue by deyvidm** [pocketbase/pocketbase#2062]
The JS SDK for pocketbase is complemented by [this JS library](https://github.com/patmood/pocketbase-typegen), which is able to extract TypeScript types from the Pocketbase schema. 

I'm curious if Golang types are also available to us, perhaps  through the use of a similar tool, or just natively through Pocketbase?

**Comment by ganigeorgiev** [comment]
There is no dynamic code generation at the moment. This eventually might be added in the future but for now is left out of the scope for v1.

When [using PocketBase as framework](https://pocketbase.io/docs/use-as-framework/) you can access the recod fields using the available [`Get*` record helpers](https://pocketbase.io/docs/record-methods/#getset-record-fields).

You also have the option to create your own custom model types - https://pocketbase.io/docs/custom-models/, but you have to map the colelction fields on your own. Also keep in mind that the [`OnRecord*` event hooks](https://pocketbase.io/docs/event-hooks/#record-crud-api-hooks) are triggered only for `models.Record`.

**Comment by deyvidm** [comment]
Thank you, Gani.
