### ISSUE TITLE
Issues with querying user data in +server.ts context

### ISSUE THREAD

**Issue by Elliott-Green** [pocketbase/pocketbase#2077]
Hi!

I have a +page.server.ts to register and log in my users to pocketbase auth. Works great. 

From a callback to +server.ts, I'm trying to do basic queries against pb, but keep getting errors.

```ts
const records = await locals.pb.collection("users").getFirstListItem(`email="e@dsa.com"`);
ClientResponseError 404: The requested resource wasn't found.
```

locals.pb is being set correctly, so I can access the pocketbase middleware.
I tried changing the List/Search / View permissions on the users table to empty - but I still get the same errors for fetching the data.
That email exists
Because it's in a server context, I don't think any authstore or auth is set - is there a way I can still access this as an admin without authing?

**Comment by ganigeorgiev** [comment]
Regular users can search by the user email only if it is marked public, aka. `emailVisibility` is set to `true`.

> Because it's in a server context, I don't think any authstore or auth is set - is there a way I can still access this as an admin without authing?

If you want to authenticate as admin in a server context, you can create a new inline/local SDK instance and call:

```js
const adminClient = new PocketBase(locals.pb.baseUrl);

await adminClient.admins.authWithPassword("test@example.com", "1234567890"); // could be loaded from env variables

const records = await adminClient.collection("users").getFirstListItem(`email="e@dsa.com"`);
```

**Comment by Elliott-Green** [comment]
Thank you!
