### ISSUE TITLE
Next.js 13 (appDir) and JavaScript SDK

### ISSUE THREAD

**Issue by aretrace** [pocketbase/pocketbase#2078]
Is there any documentation/examples on using the js sdk with the app directory new to Next.js 13? I'm having trouble using the sdk with client-rendered components (using the 'use client' directive), server components are working as expected so far.

Here is an example: https://codesandbox.io/p/sandbox/tla-njs-app-dir-k5xpz3?file=%2Fsrc%2Fapp%2Fns.tsx

**Comment by ganigeorgiev** [comment]
There is no official documentation or examples with Next.js 13.

You could find some users provided examples in https://github.com/pocketbase/js-sdk/issues/69.

I personally don't have experience with Next.js 13 and as far as I know the app directory is still in beta and has limited functionality.
