### ISSUE TITLE
Request: Add .prettierrc file and eslint

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [pocketbase/pocketbase#2094]
This came up during my work on #2093 where even though my prettier extension recognized your settings inside the package.json it seemed to also use other rules. Therefore I would suggest to put all prettier rules inside a .prettierrc file (maybe even extend from airbnb-rules + your current rules on top?)

While we are at it, how about also using eslint?

I can cook up a PR for a prettier/eslint config myself if you want. 🙂

**Comment by ganigeorgiev** [comment]
There is already a prettier configuration in the package.json.

I don't think there is a need for eslint config at the moment.

Also please check the note in https://github.com/pocketbase/pocketbase#contributing if you decide to contribute.
