### ISSUE TITLE
Feature Request: Send email with pocketbase backend

### ISSUE THREAD

**Issue by loganmac** [pocketbase/pocketbase#2111]
I'm using pocketbase, and we only have one other type of transactional email (notified when a user is mentioned in a comment). It would be really nice to be able to use the pocket sdk to send that email since you already go through the effort of setting the server up to send emails, either just from the server or by configuring something like mailgun.

It would be even nicer if you could allow configuration to send an email based on a template whenever a specific kind of record is created, for example.

I'd be happy to talk through the details of this feature, if and how you might like to see it implemented, and work on an implementation for it.

**Comment by danfascia** [comment]
This is a great idea. I’d probably keep it very simple and create an SDK function to send an email with a defined HTML payload.

Another neat piece of software you can use is listmonk (also a nice minimal Go app) for this functionality and then you also get bulk sending for marketing.

Dan

**Comment by heyarviind** [comment]
I was thinking of the same and it would be very useful if we create templates within the admin dashboard and trigger the email using the apis.

**Comment by seredenkodenis** [comment]
Hello @ganigeorgiev!
I have some free time and I will be happy to make a UI for this feature :)

Maybe someone want to make a backend?

**Comment by mdashx** [comment]
You can do something like this pretty easily if you use Pocketbase as a framework:

```
	app.OnRecordAfterCreateRequest().Add(func(e *core.RecordCreateEvent) error {
		if e.Record.Collection().Name == "orders" {
                    err = smtp.SendMail(smtp_server, auth, email_address, to, msg)
                }
        }
```

This matches the example given bhy @loganmac 
>It would be even nicer if you could allow configuration to send an email based on a template whenever a specific kind of record is created, for example.

I agree that this is very useful. 

@heyarviind brings up triggering via the API. I haven't thought about it enough to have a feeling about if it's a good solution, but it's definitely cleaner than trying to configure the backend to send emails based on some condition that could more easily be expressed by adding a few lines of Go to the server.

`pb.sendMail(emailAddress, template)`

^^this kind of sounds like it might be useful.

So on the frontend, a user makes a purchase, now I want to send out two emails:

```
pb.sendMail(adminAddress, purchaseNotificationEmailTemplate)
pb.sendMail(userAddress, thanksForPurchaseEmailTemplate)
```

**Comment by ajayyy123** [comment]
yeah I am also looking to send mails to user if this available its great feature
pb.sendMail(adminAddress, purchaseNotificationEmailTemplate)
pb.sendMail(userAddress, thanksForPurchaseEmailTemplate)

**Comment by miguelgargallo** [comment]
> bu

It would be great to:

- [ ] send email with the possibility to attach a file, temporary or limit the downloads (this will allow the admin to send files to users, without the need of comprising security)

**Comment by miguelgargallo** [comment]
> yeah I am also looking to send mails to user if this available its great feature pb.sendMail(adminAddress, purchaseNotificationEmailTemplate) pb.sendMail(userAddress, thanksForPurchaseEmailTemplate)

> bu

It would be great to:

- [ ] send email with the possibility to attach a file, temporary or limit the downloads (this will allow the admin to send files to users, without the need of comprising security)
- [ ] send email as "magic link" alternative
- [ ] use the JavaScript API to send custom template emails

**Comment by ganigeorgiev** [comment]
I'm closing this issue as with the v0.17.0+ relase users can send emails with JS on app level - https://pocketbase.io/docs/js-sending-emails/.

Sending emails with the web APIs for now remains out of the roadmap because technically only admins can send custom emails safely and I think the above covers those and other use cases (eg. allow [templates composition](https://pocketbase.io/docs/js-rendering-templates/)).
