### ISSUE TITLE
How to fix the net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by rdev32** [pocketbase/pocketbase#214]
Usually with firebase this problem is solved by adding the cors module but how do you do that with pocketbase?

**Comment by ganigeorgiev** [comment]
Hi, I'm not sure what actually you are referring to.

The above `ERR_SSL_PROTOCOL_ERROR` is usually thrown when you are trying to access https resource from a http only host?

If that's not your case, could you share a little more details on your setup and when do you receive this error (logs from the console/network tab will be also helpful)

**Comment by rdev32** [comment]
thanks, the problem was that firefox always puts https to all urls. I turned off that annoying setting and now its working.
