### ISSUE TITLE
Thumbnails not working with webp images.

### ISSUE THREAD

**Issue by RenFontes** [pocketbase/pocketbase#2141]
Thumbnails seem to work perfectly if the image is saved in jpg or png, for webp the returned file is the same size as the original file.

<img width="853" alt="webp thumbnails" src="https://user-images.githubusercontent.com/4439396/227382449-0a4ac875-5855-455b-b985-f47d63014c91.png">

**Comment by ganigeorgiev** [comment]
WEBP is currently not supported as thumb format. Please check https://github.com/pocketbase/pocketbase/issues/825.
