### ISSUE TITLE
Get user authstore email.

### ISSUE THREAD

**Issue by StickOnAStick** [pocketbase/pocketbase#2145]

**Comment by ganigeorgiev** [comment]
I see that you've updated your question. Regular user can't "search/fetch" users by their email unless the `emailVisibility` flag is set to `true`.

**Comment by StickOnAStick** [comment]
> I see that you've updated your question. Regular users can't "search/fetch" users by their email unless the `emailVisibility` flag is set to `true`.

When debugging, I removed all the users API rules, but I'm still receiving a resource not found issue.

**Comment by ganigeorgiev** [comment]
@StickOnAStick You've edited your question several times and I'm confused and don't understand what you are asking.

Please file a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details what you are trying to do and why.

**Comment by StickOnAStick** [comment]
> @StickOnAStick You've edited your question several times and I'm confused and don't understand what you are asking.
> 
> Please file a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details what you are trying to do and why.

Discovered the issue was with multiple projects using pocketbase. The authstore from my current project was referencing an authstore of another project; which was not active, then returning the wrong user ID. Thereby making retrieving the user by the ID provided via authStore impossible. 

Apologies for the confusion and lack of commenting skills. I didn't quite understand the issue myself.
