### ISSUE TITLE
Tests failed (Windows)

### ISSUE THREAD

**Issue by Hemiun** [pocketbase/pocketbase#2165]
I fork pocketbase project and try to run tests. 
Some tests failed: [test results.txt](https://github.com/pocketbase/pocketbase/files/11077736/res.txt)
This problem occurs only on windows. If i use debian all tests are successful.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it with a Windows 10 VM and I don't think this is PocketBase related. Make sure that the binary have read/modify access to the os temp directory.

**Comment by ganigeorgiev** [comment]
Another possible issue could be if you have an antivirus software that it is conflicting with the test file operations and/or is inserting meta files inside the directories making the checks for empty directory to fail (aka. similar to the `:Zone.Identifier` files in https://github.com/pocketbase/pocketbase/issues/1468).
