### ISSUE TITLE
Feature request: custom content types

### ISSUE THREAD

**Issue by regisin** [pocketbase/pocketbase#2170]
The mime type I'm looking for is not listed: `audio/m4a`. There's only `audio/x-m4a` which doesn't allow me to upload some files. I don't want to make any processing before storing the file. That said, I was wondering if there's a way to add custom mime types to a file field. I can only search, and if the type is not in that list, I'm lost.

**Comment by ganigeorgiev** [comment]
List with all supported MIME types could be found in https://github.com/gabriel-vasile/mimetype/blob/master/supported_mimes.md.

There is no mechanism to add custom mime types. Instead it will be better to file an issue or PR in the upstream repo - https://github.com/gabriel-vasile. To be honest I'm not sure what is difference between `audio/mp4`, `audio/x-m4a`, `audio/m4a`. All as far as I understand represent some audio data within MPEG4 container and they may not have distinct (or at least not easily) bytes signature.
