### ISSUE TITLE
Upload existing files by URL

### ISSUE THREAD

**Issue by rajeshg** [pocketbase/pocketbase#2181]
I would like to be able to migrate existing files to pocketbase, where the files are already located on a S3 bucket. Since the file already exists in the desired location (the same bucket that my pocketbase is uploading files to), I would like to just upload the metadata of the existing files (like URL, filename) along with the relationship to a model.

Use case:
Migrate a list of posts with images. Only the image urls are provided, as the files themselves don't need to be reuploaded through pocketbase

From the documentation, it's not clear if there is a way to do that. https://pocketbase.io/docs/files-handling/

**Comment by jpoles1** [comment]
I also have a use case where a feature like this would be very helpful!

**Comment by A2-NieR** [comment]
@rajeshg @jpoles1 I had a similar case where I needed to update the oauth2 avatar from users. Solved it like this:

```ts
const response = await fetch(authData.meta?.avatarUrl);
const blob = await response.blob();

const file = new File([blob], 'avatar.png', { type: blob.type });

await pb.collection('users').update(authData.record.id, {
	avatar: file
});

```

Hope this helps.
