### ISSUE TITLE
Feature Request: Add Redis Cache support

### ISSUE THREAD

**Issue by gevera** [pocketbase/pocketbase#2204]
By incorporating Redis Cache into PocketBase project, it could provide users with a faster, more reliable experience while improving scalability. 

1.  Improved performance: Redis Cache can significantly improve the performance of Pocketbase by storing frequently accessed data in memory, which can reduce the time it takes to retrieve data from disk. This can be particularly beneficial for applications that require low latency, such as real-time messaging systems or high-traffic web applications.

2.  Scalability: Redis Cache is also highly scalable, which means it can handle increasing amounts of data without slowing down. This can be important for projects  that need to support growing user bases or increasing amounts of data.

3.  Data synchronization: Redis Cache can be used to synchronize data between different instances of your Pocketbase application, which can help ensure that all instances of your application have access to the same data.

4.   Session management: Redis Cache can be used to manage user sessions in Pocketbase, which can help improve security and user experience by allowing users to easily log in and out of your application.

5.   Real-time analytics: Redis Cache supports real-time analytics, which can be valuable for Pocketbase projects that require real-time data analysis and processing.

Just like with S3 Storage in File Storage Settings, an option for Caching where one will add a Redis endpoint or something similar.

**Comment by ganigeorgiev** [comment]
Sorry, but this is out of the scope for v1 for now.
PocketBase lives only on a single server and for me having a redis cache doesn't make much sense in this scenario. Performance, Scaling and data synchronization between multiple instances will not magically be improved or handled by just adding a cache store.
