### ISSUE TITLE
Feature Request: More Display Field options for relation fields

### ISSUE THREAD

**Issue by Sadragos** [pocketbase/pocketbase#2206]
It would be really useful if there were more options for the display field option. I'd be especially interested in nested display / joins.

For example:

- user (id, username, email)
- group (id, owner -> user.id, name) _(here we can use user.username as display)_
- book (id, group -> group.id, name) _(Here I'd like to show the username together with the group name)_

This feature would be useful for many to many relations in my optinion.

**Comment by ganigeorgiev** [comment]
I'm not entirely sure that I understand the request.

The available "Display fields" allows selecting one or more direct fields from the relation:
![display_fields_screenshot](https://i.imgur.com/SiJntHW.png).

Support for non-direct fields (eg. nested relation fields) as part of the "Display fields" option for now are not planned as it may complicate the UI unnecessary and the behavior could be ambigious with multiple nested `relation` fields.

**Comment by Sadragos** [comment]
Ok, I understand it is not planned for now. 

As for the UI I was thinking of a similar syntax that is used in filters. So in my example from above I'd be able to simply enter "user.username" and the click "add as nested", that only pops into the list if no other option is valid - this way the existing UI would not have to be changed at all.
