### ISSUE TITLE
Feature request: Allow for custom id to be set when you initialize a new row

### ISSUE THREAD

**Issue by kaytitulaer3820** [pocketbase/pocketbase#2211]
Title basicly explains everything. I would like to be able to set the id myself. Pocketbase is great but for the things i want to use it it would be greate to be able to set my own id's.

**Comment by ganigeorgiev** [comment]
You should be able to do that already if you submit the `id` field with your create data.

The only limitation at the moment is that it needs to be 15 chars string, but eventually in the future this will be "loosen" and we allow any unique value.

You can also define any `id` value (without the 15 chars limit) using the [`OnModelBeforeCreate` hook](https://pocketbase.io/docs/event-hooks/#db-hooks).
