### ISSUE TITLE
Admin UI, logs meta are displayed incorrectly in Firefox

### ISSUE THREAD

**Issue by cuire** [pocketbase/pocketbase#2221]
Logs meta section are not visible in latest Firefox. 
I can't find a bug report, but I did find a related stackoverflow  [thread ](https://stackoverflow.com/questions/3215553/make-a-div-fill-an-entire-table-cell/73399942#73399942). Its recomendes to set the `td` height to 100%. I tested it, it solves the problem. 

I will continue the research and write if there is no better solution.

Pocketbase version 0.14.2

![image](https://user-images.githubusercontent.com/81014305/230092356-c99ae650-8b57-4584-8559-49514a0a5e71.png)

**Comment by ganigeorgiev** [comment]
This seems to be caused by the `overflow` style of the `.code-wrapper` element. I'll push a fix sometime later today.

**Comment by ganigeorgiev** [comment]
I've added a wrapper div that seems to fix the `overflow` issue in `master`.

The "fix" will be available with the next minor v0.14.3 release sometime later this week.
