### ISSUE TITLE
Feature Request: Self update

### ISSUE THREAD

**Issue by pluja** [pocketbase/pocketbase#2222]
It would be great if Pocketbase could self-update to the latest version by a command like `pocketbase self-update` just [like restic](https://restic.readthedocs.io/en/latest/020_installation.html?highlight=self-update#stable-releases) has :)

**Comment by ganigeorgiev** [comment]
It is already in the [roadmap](https://github.com/orgs/pocketbase/projects/2?pane=issue&itemId=7205701), but for now remains a low priority.
