### ISSUE TITLE
deploy in a sub-path

### ISSUE THREAD

**Issue by tommyblue** [pocketbase/pocketbase#223]
Hi, I would like to deploy pocketbase to a sub-path of the domain `http://<url>/admin`, The nginx configuration is the following:

```
    location /admin {
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        proxy_read_timeout 180s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite /admin/(.*) /$1  break;
        proxy_redirect     off;
        proxy_pass http://localhost:8090;
    }
```

This only partially works, because pocketbase still makes calls against `http://<url>/_/<resource>`. How can I tell pocketbase it's deployed on a subpath? Setting the application url in the settings page doesn't work.

To make it work I had to add a new `location` to nginx, redirecting all calls to `/_/` but I'd like to avoid it:

```
    location /_/ {
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        proxy_read_timeout 180s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect     off;
        proxy_pass http://localhost:8090;
    }
```

**Comment by ganigeorgiev** [comment]
Hi, thanks for reporting it. Indeed at the moment the prebuilt Admin UI [uses an absolute path (`/`) as  API url address](https://github.com/pocketbase/pocketbase/blob/master/ui/.env#L2) and this cannot be changed without building the ui manually.

I'll try to fix it in the next v0.4.0 release, but for now you'll have to use an additional rewrite/redirect rule as a workaround (eg. `/api/...` to `/admin/api/...`).

**Comment by tommyblue** [comment]
hey thanks for the quick reply. I'll then leave this nginx configuration or build the app in the docker-compose configuration I'm using 🖖🏼

**Comment by ganigeorgiev** [comment]
A fix was relased in [v0.3.3](https://github.com/pocketbase/pocketbase/releases/tag/v0.3.3) -  the absolute prebuilt backend url (`/`) in the Admin UI was replaced with a relative one (`../`) so now it should send requests correctly to the sub-path deployed backend.

I've tested the fix locally, but if someone is still experiencing the same issue, please let me know and I'll investigate it further.

**Comment by ganigeorgiev** [comment]
@tommyblue Actually the fix from v0.3.3 works only on the dev environment because I forgot that in the vite configuration we were also using a conditional base path depending whether we are building for prod or dev environment (which is why locally worked). Another fix that removes the discrepancies between the 2 environments was added in master (https://github.com/pocketbase/pocketbase/commit/6292e6cc2e0b62a62d06b98155170664d1393f64) and will be available with the next minor bugfix/feature release.

**Comment by rdpascua** [comment]
I followed @tommyblue nginx configuration and still can't make sub-path works, Do I need to anything else? Tried either nginx/apache but no luck.

**Comment by ganigeorgiev** [comment]
@rdpascua Please open a new Q&A discussion with information about your nginx/apache configuration.

**Comment by tommyblue** [comment]
> @tommyblue Actually the fix from v0.3.3 works only on the dev environment because I forgot that in the vite configuration we were also using a conditional base path depending whether we are building for prod or dev environment (which is why locally worked). Another fix that removes the discrepancies between the 2 environments was added in master ([6292e6c](https://github.com/pocketbase/pocketbase/commit/6292e6cc2e0b62a62d06b98155170664d1393f64)) and will be available with the next minor bugfix/feature release.

@ganigeorgiev was that minor release released?

**Comment by ganigeorgiev** [comment]
@tommyblue yes, but there are other quirks related to the subpath handling. I've just commented in https://github.com/pocketbase/pocketbase/discussions/1802#discussioncomment-4892902

**Comment by ganigeorgiev** [comment]
@tommyblue Just to let you know that in [v0.13.0](https://github.com/pocketbase/pocketbase/releases/tag/v0.13.0) the subpath handling was updated and now it should work without the extra `location` redirects.

The only requirement for the subpath location block is to have a subpath `rewrite` rule.
If you are still facing issues with the subpath setup, please share your nginx config and I'll test it further.
