### ISSUE TITLE
S3 file storage not working with Google cloud storage since 0.14.1

### ISSUE THREAD

**Issue by joelml** [pocketbase/pocketbase#2231]
Hi! First of all, thanks for amazing work!

I've been using the s3 storage to connect to a bucket in GCS without a problem up until the latest changes to the AWS SDK.
PR: #1346 

I've been trying to figure out what could be wrong but I'm not skilled in Go unfortunately.
I'm getting an error (403) that the test file couldn't be uploaded and it doesn't matter if I'm upgrading from 0.14.0 or starting fresh at latest 0.14.2.
But using the same credentials for the s3 storage works fine going back to 0.14.0. (also using the old database).

Any ideas?

**Comment by ganigeorgiev** [comment]
Could you start the executable with `--debug` and check if there is a more detailed error message in the console?

**Comment by ganigeorgiev** [comment]
Hm, I think this could be related to https://github.com/aws/aws-sdk-go-v2/issues/1816, which means that it will require some special handling for GCS due to the changes of how v2 sign and send the request headers.

I'll consider a revert sometime later today.

**Comment by joelml** [comment]
Thank you for looking into this!

Using `--debug` only prints out the params being set as normal, nothing else.

**Comment by ganigeorgiev** [comment]
To avoid having a special implementation just for GCS, the AWS SDK change was reverted in [v0.14.3](https://github.com/pocketbase/pocketbase/releases/tag/v0.14.3) (we don't use any of the newer S3 apis anyway).
If you are still having difficulties with the S3 setup, feel free to let me know and I'll investigate it further.
_Note that `--debug` will show additional error messages in the console only during an action (aka. if you want to check the error with the v2 of the sdk you have to trigger S3 settings update)._
