### ISSUE TITLE
Feature Request: Add integration to watermellondb sync

### ISSUE THREAD

**Issue by GD-coding** [pocketbase/pocketbase#2239]
This might be a little early in development to request something like this. But for my use case on mobile development with react native, this would prove quite useful for offline capabilities.

### Documentation link

https://watermelondb.dev/Advanced/Sync.html

This would be very helpful in order to make changes to the local database offline. Then (once online) this would sync the local changes with the remote server.

Thank you for the amazing work on this so far!

**Comment by ganigeorgiev** [comment]
At least for now this is out of the scope for v1 (offline/local data sync in general is in my todo to research the available options but has a very low priority).
