### ISSUE TITLE
Support for Vector data type, distance search

### ISSUE THREAD

**Issue by danibjor** [pocketbase/pocketbase#2249]
Vector data type would be nice for some applications. Also being able to return results based on vector distance. 

AI applications would benefit from this. Got one project now, where the 128-dimensional vector are stored as json object, but querying these are really hard at the moment. Now we need to fetch the complete dataset, calculate distance on the server/client and return a subset as close match to the user.

**Comment by ganigeorgiev** [comment]
At least for now, this is out of the scope for v1.

If anyone want to works on it, feel free to outline your implementation idea and/or open a PR and I'll try to review it.
