### ISSUE TITLE
Option to disable collection editing for production deployments

### ISSUE THREAD

**Issue by sphinxc0re** [pocketbase/pocketbase#2262]
As a developer, I don't want to accidentally edit collections on a production instance of PocketBase. I expect this to be limited to local deployments.

I would like to have either a command line option or an environment variable to "lock down" the PocketBase instance in production deployments.

**Comment by ganigeorgiev** [comment]
You can hide the collection controls from the _Admin UI > Settings > Application > "Hide collection create and edit controls"_ toggle.

There is no built-in "locking" functionality (aka. preventing collection changes over the web APIs), but you can implement it on your own by attaching to the [`OnModelBeforeCreate("_collections")` and `OnModelBeforeUpdate("_collections")` hooks](https://pocketbase.io/docs/event-hooks/#db-hooks) and return an error based on some flag or env variable check.

This eventually may got simplified in the future depending on the users demand, but for now is left to the developer to handle on their own (_soon there will be also a JS app hooks api for those who don't feel comfortable working with Go_).
