### ISSUE TITLE
Feature request: Add support for 2FA or hardware key based authentication

### ISSUE THREAD

**Issue by itsemre** [pocketbase/pocketbase#2265]
Hello! I think that it would be great if we could have the option to use 2FA authentication in pocketbase, or even hardware based authentication. I think this is a necessity to have at least for the admin authentication. Are you planning to implement this feature? If not, how would I go about implementing something like this myself?

**Comment by ganigeorgiev** [comment]
You can check https://github.com/pocketbase/pocketbase/discussions/1553.
