### ISSUE TITLE
API: Filter with AND(&&) operator returns  a bad request(400) exception

### ISSUE THREAD

**Issue by Aimkeys-Sir** [pocketbase/pocketbase#2267]
I am trying to query for exhibitorClass(a join table) using exhibitor(id) and tradeClass. This returns a bad request.
```javascript
http://127.0.0.1:8090/api/collections/exhibitorClasses/records?filter=(exhibitor='${exhibitorID}'&&tradeClass='{tradeClass.id}')
``` 
All these works well
```javascript
http://127.0.0.1:8090/api/collections/exhibitorClasses/records?filter=(exhibitor='${exhibitorID}')
http://127.0.0.1:8090/api/collections/exhibitorClasses/records?filter=(exhibitor='${exhibitorID}')
http://127.0.0.1:8090/api/collections/exhibitorClasses/records?filter=(exhibitor='${exhibitorID}'||tradeClass='{tradeClass.id}')
``` 
This also returns bad request.
```javascript
http://127.0.0.1:8090/api/collections/exhibitorClasses/records?filter=(exhibitor='${exhibitorID}'&&created>'2023-04-11')
``` 
But this works.
```javascript
http://127.0.0.1:8090/api/collections/exhibitorClasses/records?filter=(created>'2023-04-11')
```

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the issue using the JS SDK and similar collections.

**If you are manually constructing the url, make sure that the `filter` query parameter is properly url encoded.**

You can start PocketBase with `--debug` for more detailed console error messages.

If that doesn't help, please provide more details what version of PocketBase you are using, what is `exhibitorID` and how you are sending the request in general (if possible, you can also export your collections configuration as JSON from the _Admin UI > Settings > Export collections_).
