### ISSUE TITLE
[QUESTION] Custom Queries?

### ISSUE THREAD

**Issue by Stetsed** [pocketbase/pocketbase#2281]
Good evening,

I am trying to add certain features to my program which involve features which are not implemented yet inside of PocketBase and require me to do raw SQL queries. This is things such as counting the amount of records, which right now is technically possible by querying all the records and then counting the amount in the frontend but this causes alot of extra unneeded data transfer.

I'm reading the documentation and I am kinda unclear about it, am I correct that to do raw SQL queries you have to write your own Go code as outlinged [here](https://pocketbase.io/docs/database/). Or is there a builtin way to query the API with a custom SQL query?

Hope to hear back soon because if I am able to execute raw SQL queries that would fix my last gripe with moving to PocketBase for everything.

**Comment by Stetsed** [comment]
Closing this as I see this is possible via a view collection

**Comment by Stetsed** [comment]
Reopening as my question still stands as * are not available via view collections right now, are they available via other methods?

**Comment by ganigeorgiev** [comment]
Why the lack of wildcard (`*`) is an issue for you use case? You can define the column explicitly and it should work with any query the same way as if `*` is used.

If you want to execute parameterized custom db queries then you have to [use PocketBase as framework](https://pocketbase.io/docs/use-as-framework/) and [query the database via the available db abstraction](https://pocketbase.io/docs/database/)
