### ISSUE TITLE
Customize Admin UI?

### ISSUE THREAD

**Issue by dmuraco3** [pocketbase/pocketbase#2291]
Is it possible to customize the UI for the admin panel? I'm wanting to make the admin panel more user friendly for my admins, but I don't see anything in the documentation for such a thing. I'm coming from Sanity, although being a CMS, I really enjoy the customizability of the front end. Is this possible in PocketBase?

**Comment by ganigeorgiev** [comment]
No, at the moment the Admin UI can't be customized. Eventually this might be handled with https://github.com/pocketbase/pocketbase/issues/898.

**Comment by juangiordana** [comment]
The Admin UI is near perfect craft. I'm really in awe with this project.

**Comment by dmuraco3** [comment]
> The Admin UI is near perfect craft. I'm really in awe with this project.

It's amazing for developers, however I'm wanting to customize the UI to be more straightforward for my less tech-savvy counterparts. What I'm asking for is probably out of scope for now, but I really enjoy the backend. I could roll out my own Admin Panel, but that's far more work than just customizing the existing panel.

**Comment by LHongy** [comment]
I guess cloning the project and modify this UI part of the code will do?
https://github.com/pocketbase/pocketbase/tree/master/ui
