### ISSUE TITLE
[ISSUE?] Issue getting data from getFullList

### ISSUE THREAD

**Issue by Stetsed** [pocketbase/pocketbase#2295]
Good evening,

I am currently working on an application that queries all data within the database to present a visualization. However I am running into a weird issue that the code below does not work as it returns that responseData is undefined. This only happen with the getFullList function as using getList it works fine? Is there a diffrence between these function that would mean what I am trying to do isn't possible. I see the requests getting sent to the database and it's responding so I am confused.

```<script lang="ts">
  import { onMount } from 'svelte';
  import { currentUser, pb} from "../../lib/pocketbase.ts";

  let responseData: any[] = [];
  let canvas: HTMLCanvasElement;
  let ctx: CanvasRenderingContext2D;

  const PIXEL_SIZE = 1;
  const MAX_ALPHA = 255;

  function drawPixel(x: number, y: number) {
    const imageData = ctx.getImageData(x, y, PIXEL_SIZE, PIXEL_SIZE);
    const alpha = imageData.data[3];

    if (alpha === MAX_ALPHA) {
      return;
    }

    imageData.data[3] = alpha + 1;
    ctx.putImageData(imageData, x, y);
  }

  onMount(async () => {
    ctx = canvas.getContext('2d');

    const resultList = await pb.collection('global_view').getFullList();
    responseData = await resultList.items;

    console.log('responseData', responseData);


    if (responseData) {
      for (let i = 0; i < responseData.length; i++) {
        const { x, z } = responseData[i];

        console.log("drawing pixel", x, z);

        drawPixel(x, z);
      }

      console.log("Resizing Canvas");
      // Resize canvas to fit content
      canvas.width = canvas.scrollWidth;
      canvas.height = canvas.scrollHeight;
    }
});
</script>

<canvas bind:this={canvas}></canvas>```

**Comment by ganigeorgiev** [comment]
`getFullList()` doesn't return a paginated list - it returns directly all record items as an array, aka. there is no `resultList.items`, just `resultList`.

)If you still have difficulties resolving the issue, please file a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a)._
