### ISSUE TITLE
Feature Request: Group collections

### ISSUE THREAD

**Issue by maxNodeJs** [pocketbase/pocketbase#2297]
First thanks for adding the option for view collections.
It would be helpful to Group the collections. Before the View Collection Type I guess this would not be so important. However, since we can create views, it would be helpful to be able to add groups whereby we can assign different collections to different groups.

If this is too much of a work, maybe start with grouping automatically the Base, Auth and View collections.

Thanks for all the hard work, and it's really amazing backend database, and the UI? is first class.

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean by _"grouping automatically the Base, Auth and View collections"_. Could you elaborate and/or give an example?

**Comment by ganigeorgiev** [comment]
I'm closing this issue for now.

If you are asking for visual collections grouping in the Admin UI, aka. to have categories or folders, for now this is not planned since it may clutter the interface unnecessary.

Feel free to provide more details to your feature request but for now the above remains out of the v1 scope.

**Comment by maxNodeJs** [comment]
Sure, sorry for not making myself clear.

For axample in the list of all collections we will have something like this.

Auth Collections ( Name of the Group )
  Users,
  Tenants
  any other Auth collection type
  
Base Collections ( Name of the Group )
  Companies
  Clients
  Jobs
  any other Base collection type

this list can grow to a lot of queries, and would be helpful if they are listed in a Group.

View Collections ( Name of the Group )*
  all_users
  posts_with_total_comments
  
I hope this is clearer :-)

If we can also create additional sub Group names in the views, this would help list the queries/views we create under our own Collection Group Name

for example Under Default Views Collection*, we can create additional Group Names for example Users View, Company Views, Accounts Views and so on.....

I sugests when we create or modify a collection, we can choose which Group to list the collection under. Or Drag and Drop :-)



> I'm closing this issue for now.
> 
> If you are asking for visual collections grouping in the Admin UI, aka. to have categories or folders, for now this is not planned since it may clutter the interface unnecessary.
> 
> Feel free to provide more details to your feature request but for now the above remains out of the v1 scope.

**Comment by jdiaz0705** [comment]
I like this idea, but I can understand that it would clutter the UI. Do you think we could at least be able to rearrange the order of the collections?
