### ISSUE TITLE
 Unable to use Cloudflare R2 with custom domain due to bucket requirement in pocketbase's S3 dashboard

### ISSUE THREAD

**Issue by AstroOrbis** [pocketbase/pocketbase#2300]
I'm trying to use Cloudflare R2 with S3 support in Pocketbase, but I've encountered an issue with making R2 publicly available using a custom domain. 

Steps to reproduce:

1. Go to the S3 dashboard in Pocketbase
2. Set the endpoint to https://storage.example.com (Objects are therefore stored at the root of this url: https://storage.example.com/hash1/hash2/image.png)
3. Observer that Pocketbase's S3 dashboard requires a bucket, which forces the use of a URL like https://storage.example.com/root/ for the root of R2, which is impossible with Cloudflare's R2 custom domains.

Observed behavior:
It seems that I'm unable to use Cloudflare R2 with a custom domain because pocketbase's S3 dashboard requires a bucket, which changes the URL structure.

Would anyone know how to use a custom domain R2 with the S3 dashboard?

**Comment by AstroOrbis** [comment]
Nevermind - I can use some clever URL manipulation on the frontend to get around this problem.

**Comment by ganigeorgiev** [comment]
@AstroOrbis _Note that in the Settings Storage UI there is also an option to "Force path-style addressing"._

**Comment by AstroOrbis** [comment]
I tried that with the format https://example.com, bucketname storage and path-style addressing on - Didn't work, but I did some substring URL replacement in the frontend to use the private URL in the backend but the public one in the frontend... best 20 lines I've ever spent
