### ISSUE TITLE
Feature Request: Webhooks / Collection triggers for file uploads

### ISSUE THREAD

**Issue by danfascia** [pocketbase/pocketbase#2310]
I've already seen the suggestion of webhooks, also seemingly called collection triggers and noted that it makes an appearance on the roadmap for v1.0 which is great.

May I ask if it would be possible to fire a hook after a file upload, because this is a super useful workflow for triggering something like encoding of video or CDN caching of files uploaded to an S3 compatible bucket.

I know there could be a suggestion that we could "use pocketbase as a go framework" but I think being realistic here, that is always going to be a niche interest since Go itself isn't that popular when compared with the node.js ecosystem for example.

Webhooks are appealing because they universally please everybody rather than just Golang enthusiasts.

**Comment by ganigeorgiev** [comment]
This will be handled eventually either as part of the https://github.com/pocketbase/pocketbase/issues/317 task AND/OR with the upcoming JS app hooks support with goja.
