### ISSUE TITLE
protected file url is still reachable without token

### ISSUE THREAD

**Issue by Guest-01** [pocketbase/pocketbase#2315]
here's how I tested and how you can replicate.

1. Make a collection with `File` field that has `protected` switched on.
2. upload a file (I personally tested with a png image) through admin UI's `+ new record` button.
3. Click a record and preview that file, your browser automatically shows uploaded img in new tab.
4. At top, it shows an URL that has `?token=BLAHBLAH~` at the end. (I guess this is the short-lived token)
5. Now remove that token part from the url. Refresh and image still shows.
6. Tried clearing cache and did it again in secret mode(incognito etc.) and is still approachable.

Am I doing something wrong? maybe it happens because I'm on the localhost?

I'm using pocketbase v0.15.0 windows version.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. Make sure that your collection's "View API rule" is not empty.

If that's not the case, please export your collections configuration (Admin UI > Settings > Export collections) and I'll try to investigate it further.
