### ISSUE TITLE
Feature Request: Support RTL content in rich-text-editor 

### ISSUE THREAD

**Issue by amirhhashemi** [pocketbase/pocketbase#2327]
I want to use Pocketbase in my Farsi (a Right To Left language) blog but unfortunately, your rich text editor doesn't give me control over the text direction so writing RTL content is kind of hard. It would be nice to have control over the text direction. 

Around 600M people speak an RTL language. I'm sure lots of people will appreciate this feature. Also it helps Pocketbase to get more global adoption.

I haven't played much with Svelte and TinyMCE so I can't implement it myself. But TinyMCE has a plugin for that and it should be relatively easy to implement: https://www.tiny.cloud/docs/plugins/opensource/directionality/

**Comment by ganigeorgiev** [comment]
I've enabled the directionality plugin in `master`:

![directionality_screenshot](https://i.imgur.com/hu8hJn1.png)

For new blank editors it'll also try to reuse the last explicitly set text direction (we keep the selection in `localStorage`).

The change will be available with the next minor v0.15.1 release sometime later this week.
