### ISSUE TITLE
Bug: Collection name can't start with a capital letter

### ISSUE THREAD

**Issue by amirhhashemi** [pocketbase/pocketbase#2334]
The first letter of a collection name can't be a capital letter. When I type a capital letter the lowercase version would be added. Not sure if it's intended but it doesn't make sense to me. Let me know if there is a particular reason for that.

**Comment by amirhhashemi** [comment]
Ok. So we shouldn't be able to use a capital letter in the entire name, not just the first letter. That could be improved.

**Comment by ganigeorgiev** [comment]
It is just a frontend normalization, part of the shared "slugify" behavior. I've removed it in the develop branch to comply with the server allowed regex (`^[a-zA-Z0-9][a-zA-Z0-9_]*$`).
