### ISSUE TITLE
Feature request: Expand relational field instead of adding "expand" item in API response

### ISSUE THREAD

**Issue by vtisnado** [pocketbase/pocketbase#2350]
Hi @ganigeorgiev I'm wondering if is possible to expand the relational field itself instead of adding the "expand" item with the fields of the related collection inside.

Currently if you have a `recipes` collection and want to get some fields of the related collection `ingredients` you need to add the `?expand=ingredients` to the query and will receive the response like this:

```
{
...
expand": {
        "ingredients": [
          {
            "collectionId": "ykil9v161rfy6sp",
            "collectionName": "ingredients",
            "id": "pj1970r4gk1ncaf",
            "name": "Chicken",
          },
          {
            "collectionId": "ykil9v161rfy6sp",
            "collectionName": "ingredients",
            "id": "ks2bg91p7nqb3ap",
            "name": "Salt",
          },
          {
            "collectionId": "ykil9v161rfy6sp",
            "collectionName": "ingredientes",
            "id": "s0zibxpy0cmyurj",
            "name": "Oil",
          },
        ]
      },
"recipe_name": "Fried Chickend",
"ingredients": [
        "pj1970r4gk1ncaf",
        "ks2bg91p7nqb3ap",
        "s0zibxpy0cmyurj",
        "b2dr876kbmxb0my"
      ], 
}
```

Why not just get off the expanded item and add all the fields requested to the relational item like this:

```
{
...
"recipe_name": "Fried Chickend",
"ingredients": [
          {
            "collectionId": "ykil9v161rfy6sp",
            "collectionName": "ingredients",
            "id": "pj1970r4gk1ncaf",
            "name": "Chicken",
          },
          {
            "collectionId": "ykil9v161rfy6sp",
            "collectionName": "ingredients",
            "id": "ks2bg91p7nqb3ap",
            "name": "Salt",
          },
          {
            "collectionId": "ykil9v161rfy6sp",
            "collectionName": "ingredientes",
            "id": "s0zibxpy0cmyurj",
            "name": "Oil",
          },
        ]
}
```

I think it looks a bit cleaner and intuitive.

**Comment by ganigeorgiev** [comment]
At least for now, there are no plans to change or add an option to change the returned data format.

Also please note that the items in the `expand` object may not necessarily be the exact same number that are stored as value for the record, because we are expanding only those records for which the client satisfies the View API rule of the related collection.
