### ISSUE TITLE
Wrong User IP

### ISSUE THREAD

**Issue by fly1ted** [pocketbase/pocketbase#2372]
Hosted on fly.io, I never get real user Ip but the Ip of the fly.io machine. I see that there's a mechanism in-place (https://github.com/pocketbase/pocketbase/blob/master/apis/middlewares.go#L327) to extract that but it doesn't work. In the example below 66.241.125.241 is the fly.io's server Ip not the stripe's which is the caller.  I have all my logs from  66.241.125.241. Interestingly echo context fmt.Println(c.RealIP()) prints real Ip

```go
e.Router.AddRoute(echo.Route{
			Method: http.MethodGet,
			Path:   "/api/mkSession",
			Handler: func(c echo.Context) error {

				fmt.Println(c.RealIP())
},
			Middlewares: []echo.MiddlewareFunc{
				apis.RequireAdminOrRecordAuth("users"),
				apis.ActivityLogger(app),
			},
		})
```

<img width="746" alt="image" src="https://user-images.githubusercontent.com/8587695/234933009-f8c92f25-1e35-4f46-bd95-904cf07a0864.png">

Any ideas where to start digging?

**Comment by ganigeorgiev** [comment]
Hm, there seems to be a special [`Fly-Client-IP` header](https://fly.io/docs/reference/runtime-environment/#fly-client-ip).

I'll add it in the `develop` branch sometime later today as a special case similar to the Cloudflare's `CF-Connecting-IP`.

**Comment by fly1ted** [comment]
Many thanks!

**Comment by ganigeorgiev** [comment]
I've added the `Fly-Client-IP` header check in the `develop` branch (it will be available with the next v0.16.0 release).

> Interestingly echo context fmt.Println(c.RealIP()) prints real Ip

It is most likely because the echo function uses the first "valid" IP from the `X-Forwarded-For` header list, while we use the last/right-most IP as it is the most "trusted" one.

**Comment by dschissler** [comment]
Maybe these header names should be configurable in the admin UI?  Or perhaps also via CLI arguments.

**Comment by ganigeorgiev** [comment]
@dschissler I think it will be too confusing having "knobs" for this but I've added it in my todo to keep it in mind when working on the planned "logs generalization" sometime in the future.

**Comment by dschissler** [comment]
There are so many services though.  Are you going to hardcode in a few dozen `X-` headers?

**Comment by ganigeorgiev** [comment]
@dschissler  It is expected that most services will use the `X-Real-IP` or the `X-Forwarded-For` common headers. We have fallback for those (I've updated the `X-Forwarded-For` parsing earlier to use the first non-empty leftmost-ish IP as it seems to be the closest to the "real IP", although different frameworks seems to disagree on this). For more advanced networking users can also always put a reverse proxy in front of PocketBase.

But in any case, as mentioned earlier, the logs will be refactored to support also non-request style logs and I'll have it in mind.
