### ISSUE TITLE
Feature Request: “personal data”, its “processing” and “data controllers” under the GDPR

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#2379]
Add an option to automate the GDPR (Europe) or CCPA (California) or IT ACT (India) or PIPL (China) THE APPI (Asia) implementation

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean. PocketBase by default doesn't use cookies and doesn't collect personal identifiable information. Could you elaborate?

**Comment by miguelgargallo** [comment]
Thank you for your interest. I am suggesting to add an option for PocketBase users collection to automate the process of collecting user consent for data privacy laws such as GDPR, CCPA, IT ACT, PIPL, and APPI, by the moment we have "verified", it would be nice to have one bolean labeled as "data" for data protection acceptance by the user.

This is an interesting suggestion as data privacy laws are becoming increasingly important and businesses must comply with them. By automating the process of collecting user consent with a check, PocketBase users would be able to easily comply with these laws without having to manually create screens and collections for each law.

I am passing this suggestion to the PocketBase development team for their consideration. Thank you for your time!

**Comment by ganigeorgiev** [comment]
> it would be nice to have one bolean labeled as "data" for data protection acceptance by the user.

`users` and any other auth collection can have as many other custom fields.

> By automating the process of collecting user consent with a check, PocketBase users would be able to easily comply with these laws without having to manually create screens and collections for each law.

But what process?

I'll close the issue for now since I don't think this can be generalized as it will depend what personal data your application is storing.

If you have an idea how this could be approached in a generic way, feel free to provide more details and I'll reconsider it.

**Comment by miguelgargallo** [comment]
Any country must comply with data regulation, because users from Europe in US projects must to comply with law data regulations, so a field of a box of "data accepted" should be a good implementation

**Comment by ganigeorgiev** [comment]
> so a field of a box of "data accepted" should be a good implementation

For me it doesn't make sense to define for every auth collection if there is no extra business logic binded to it. If you just want a `bool` check, you can add it on your own using the `bool` field type:

![bool_field](https://i.imgur.com/BVWTtDW.png).

**Comment by miguelgargallo** [comment]
Thanks! Yeah!
