### ISSUE TITLE
Feature Request: Filter view

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#2380]
A simple way to borrow a link to an employee, the goal is to allow them to filter on non twchnical way, and without permissions.

**Comment by ganigeorgiev** [comment]
At least for v1, the Admin UI is accessible only by admins. This may eventaully change in the future with https://github.com/pocketbase/pocketbase/issues/898.

**Comment by miguelgargallo** [comment]
Thanks
