### ISSUE TITLE
new  option - generate consecutive number in each record.

### ISSUE THREAD

**Issue by hdz-dev** [pocketbase/pocketbase#2396]
It would be possible to generate a new option in the creation of database fields for the automatic creation of a consecutive number each time a new record is saved, thanks for making this great project possible.

**Comment by ganigeorgiev** [comment]
Autoincrement-like type of field for now is not planned as it is not clear how it will be updated by the users (if at all).

Internally SQLite has a built-in rowid sequential counter that we could use without having to define a new read-only field type, but currently it is not exposed to the public web APIs and at least for v1 this for now remains out of the [roadmap](https://github.com/orgs/pocketbase/projects/2) (_I have it in my internal todo and eventually I may reconsider it in the future_).
