### ISSUE TITLE
xcf Error when importing

### ISSUE THREAD

**Issue by Dredious** [pocketbase/pocketbase#2404]
Using Svelkit, when importing PocketBase

import PocketBase from 'pocketbase'

It triggers below error

[vite] error while updating dependencies:
Error: Build failed with 1 error:
pocketbase:1:0: ERROR: Unexpected "\xcf"

Tried starting a new project, produces the same error.

**Comment by ganigeorgiev** [comment]
_Closing as duplicate of https://github.com/pocketbase/js-sdk/issues/190._
