### ISSUE TITLE
Feature Request: ability to set headers on client-side integration (SDKs)

### ISSUE THREAD

**Issue by usamashafiqs** [pocketbase/pocketbase#2409]
Currently, we do not have the ability to set custom headers on our API requests made through pocketbase SDKs. We would greatly benefit from having this capability so that we can include important metadata, such as headers, request identifiers, and user agent strings.

**Comment by ganigeorgiev** [comment]
The Dart SDK already support sending headers with the regular requests.

Custom headers (and eventually option to provide custom `fetch` implementation together with general refactoring to minimize the positional arguments) for the JS SDK is in my todo but for now remains a low priority.

As a temporary workaround, you can use directly `pb.send(reqOptions)` OR you can create your own wrapper and/or add the header via the ]`pb.beforeSend` global js hook](https://github.com/pocketbase/js-sdk#send-hooks).
