### ISSUE TITLE
Bug: duplicate records are being returned on the second page when using the @random sort.

### ISSUE THREAD

**Issue by usamashafiqs** [pocketbase/pocketbase#2439]
I have encountered an issue where duplicate records are being returned on the second page when using the ```@random``` sort.

### Additional Information
This issue seems to occur specifically when requesting the second page with the ```@random``` sort.

### Expected Behavior:
When using the ```@random``` sort on the second page, the API should return a unique set of data without any duplicates.

### Actual Behavior:
The API is returning duplicate records on the second page when the ```@random``` sort is applied.

**Comment by ganigeorgiev** [comment]
This is expected as we don't store information about any previously fetched records.

This was mentioned in the discussion when `@random` was introduced in https://github.com/pocketbase/pocketbase/discussions/1393#discussioncomment-4564922.
I'll consider documenting it better in the near future.
