### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by heoyongun** [pocketbase/pocketbase#244]
package.json info 

{
  "name": "backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "pocketbase": "^0.2.2"
  }
}

error message

![스크린샷, 2022-07-31 13-02-56](https://user-images.githubusercontent.com/6076067/182009500-c047169c-a717-46f2-b29b-46685fd9ed40.png)

**Comment by ganigeorgiev** [comment]
If you are using **Node < 17** then you'll need to load a `fetch()` polyfill.
To install it, run:
```
npm install cross-fetch --save
```

And load the below code somewhere before initializing the PocketBase client:
```js
require('cross-fetch/polyfill');
```

This is mentioned in the the JavaScript-SDK README - https://github.com/pocketbase/js-sdk#nodejs-via-npm

If the above doesn't work for you, please let me know and I'll investigate it further.
