### ISSUE TITLE
Feature Request: Direct Access to Related Entries from Single Relation Fields for Easier Management

### ISSUE THREAD

**Issue by sum117** [pocketbase/pocketbase#2440]
Dear maintainer,

I hope this message finds you well. Thanks for your awesome project. I am writing to request a feature enhancement for the Admin UI of Pocketbase that I believe would greatly improve the user experience and efficiency for administrators working with database collections.

Currently, when managing entries with single relations between collections, the Admin UI only displays the related entry's ID. As a result, I have to manually navigate to another table and search for the entry using its ID, which can be time-consuming and cumbersome.

To streamline this process, I would like to propose the following feature:

**Direct Access to Related Entries from Single Relation Fields:**

When clicking on a single relation field, the system should automatically redirect users to the specific related entry for quick and easy management. This feature would eliminate the need to manually search for related entries and would significantly increase efficiency when working with interconnected data.

Benefits of this feature include:

1. Improved user experience: Users can navigate through related entries more seamlessly, resulting in a smoother workflow.
2. Time savings: Administrators will save time by not having to search for related entries manually, allowing them to focus on other tasks.
3. Enhanced data management: By enabling direct access to related entries, users can more effectively manage and update interconnected data.

I believe this feature would be a valuable addition to the Pocketbase Admin UI and enhance the overall functionality of the platform. Thank you for considering my request, and I look forward to hearing your thoughts on this proposed enhancement.

Best regards,

John

**Comment by ganigeorgiev** [comment]
I've added it in my todo to consider enabling opening the edit panel from the relation picker, but I'm not sure if it will be a good idea to have the same behavior from the listing since it could result in accidental record edit.

For now this remains out of the [roadmap](https://github.com/orgs/pocketbase/projects/2) as there are already plenty of other more major tasks to work on, but if anyone wants to pick it feel free to file a PR and I'll review it.

**Comment by ganigeorgiev** [comment]
Side notes:

> the Admin UI only displays the related entry's ID.

You have the option to choose the displayable relation fields from the `relation` field options.

> I have to manually navigate to another table and search for the entry using its ID, which can be time-consuming and cumbersome.

When you click on the main record > "Open picker" you'll find a separate search and edit btn on hover over the related record (_as mentioned previously I'll consider also adding the edit btn in the relation picker overview/selections list_).
