### ISSUE TITLE
Feature request: file order in multiple file field

### ISSUE THREAD

**Issue by matteoboleso** [pocketbase/pocketbase#2445]
Hello

I'm using multiple file field as image gallery.
From the admin ui is not possible to change file order, the only way to do it is to delete and reupload in correct order.
Should be useful if admin ui permit files ordering.

Thanks for this fantastic tool.

**Comment by ganigeorgiev** [comment]
This is implemented in the `develop` branch and will be available with the upcoming v0.16.0 release soon (_most likely next week_).

_Note that already uploaded files and new files are sorted separately as we currently don't support on API level inserting a new file "in-between" the existing ones._
