### ISSUE TITLE
Feature Request: Allow the id field to be provided from the client

### ISSUE THREAD

**Issue by robitar** [pocketbase/pocketbase#246]
Firstly, thanks so much for putting this together, I've been playing around with it and it's really quite a thing!

As far as I can see, the id field is automatically generated when a record is created. If an `id` is provided in the request, its ignored. I'm putting together a demo of a local-first/CRDT data structure, which functions offline, and syncs records to the server when it comes back etc.

I can add my own 'key' field which is unique and required, but I still need to do an insert to get a hold of the generated id for any cross references, which is rather awkward. Would it be possible to support client-provided ids without too much churn?

**Comment by ganigeorgiev** [comment]
Allowing clients to set the `id` manually may have some unexpected side-effect when the id is used with some filter operators (see https://github.com/pocketbase/pocketbase/discussions/230#discussioncomment-3232141).

I'll have to think a little more on this, but support for client-provided ids will be added in the near future (this most likely will be also needed for https://github.com/pocketbase/pocketbase/issues/48).

**Comment by robitar** [comment]
Yes makes sense, I hadn't considered the data import scenario.

It also occurred to me that there's currently no 'sequence' value (like an autoincrement id etc) that gives you a stable monotonic row number. Something that lets you say "the last row I saw was x, give me everything greater than x". You can use a combination of creation and modification dates for this, but then you have to rely on the server clock never drifting backwards.

This is also useful for doing cursor style pagination.

Perhaps if a collection had a key generation strategy? Then you could choose between uuid/random, client provided, or autoincrementing sequence?

(Is it worth considering some kind of sequential uuid generation scheme as well? if tables get larger then a random primary can be problematic for performance, I'm not sure if this is true for SQLite, but they are using B trees, so I presume its a factor there)

**Comment by ganigeorgiev** [comment]
@robitar There is actually an internal sqlite sequential key but currently it's not exposed to the API (with the exception for the logs service) - `rowid` (https://www.sqlite.org/rowidtable.html).

**Comment by robitar** [comment]
Ah yes, sounds ideal. But I see what you mean, it would also be tricky to work into the API design, since Id/RowId would be confusing. Re providers, it seems reasonable enough to assume most database providers will support some kind of arbitrary sequence columns outside of primary keys (I'm familiar with MSSQL which finally supports this).

But I'd still be wary of the primary key being a random string. I'm also a big fan of SQLite, and think it's capable of a lot more than people give it credit for, but no database (even in memory) will perform fantastically when inserting and traversing over randomly distributed trees.

Anyway, I think supporting client id can address most of the issues for now (you can use a sequential guid which should perform just fine etc).

**Comment by ganigeorgiev** [comment]
>  it would also be tricky to work into the API design, since Id/RowId would be confusing

I agree.


> But I'd still be wary of the primary key being a random string.

From the SQLite docs:
_The PRIMARY KEY of a rowid table (if there is one) is usually not the true primary key for the table, in the sense that **it is not the unique key used by the underlying [B-tree](https://www.sqlite.org/fileformat2.html#btree) storage engine**._

Or in other words, the "primary key" that we use is treated more like just a unique non-null column.

So although it may not be the most efficient way in terms of column storage, I don't expect a very big difference in overall performance comparing to regular sequential key for example.
With time you certainly would experience some performance degradation with the grow of your database but this usually should be a concern only for very large applications for which PocketBase and its single server, vertical scale only approach, may not be really suitable.

A proper testbed will be created once we reach a little more stable version, but for now the dev experience is prioritized at expense of some small eventual performance penalty.

I've already starting working on import/export for the collections and custom client ids support will be shipped with it, I just need a little more time to ensure that it will not cause issues with the existing filters/api rules (my suggestion from https://github.com/pocketbase/pocketbase/discussions/230#discussioncomment-3232141 to use `json_each` instead of `LIKE` turned out that may not be the best choice since it practically is equivalent to a cartesian join with virtual table on the fly, so I'll have to think a little more on this before proceeding).

**Comment by robitar** [comment]
Fantastic, yes that makes perfect sense. Agreed re scaling, if the addition of an additional column would introduce big problems you're probably going to hit other limits before that!

Yea being able to automate/manage the configuration across dev/prod will be very useful!

This project is making me consider picking up a little Go!

**Comment by ganigeorgiev** [comment]
With [v0.4.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.4.0), all resource endpoints (records, collections, admins, users, etc.) now support specifying a custom insertion id during create.

Iit still must be a fixed 15 chars string to avoid security issues with existing Collection API filters. In future versions I'll consider adding an option to change this when using PocketBase as framework.

**Comment by davidhaley** [comment]
@ganigeorgiev

> Iit still must be a fixed 15 chars string to avoid security issues with existing Collection API filters. In future versions I'll consider adding an option to change this when using PocketBase as framework.

Thank you, I am trying to save objects from an external API, and they have ids of length 9. However, I get an error:

```
{
    "url": "http://127.0.0.1:8090/api/collections/carts/records",
    "status": 400,
    "data": {
        "code": 400,
        "message": "Something went wrong while processing your request.",
        "data": {
            "id": {
                "code": "validation_length_invalid",
                "message": "The length must be exactly 15."
            }
        }
    },
    "isAbort": false,
    "originalError": null,
    "name": "ClientResponseError 400"
}
```
I look forward to when we can provide unrestricted ids from the client.

**Comment by VittorioParagallo** [comment]
I've started using pocketbase by importing an existing project. I just discovered that the id must be exactly 15 chars lenght, while i succefully imported 16 chars id. Now that i'm creating new records i got the error that the lenght should be exactly 15 and it's a big problem for my use case. Is it planned to give freedom about the lenght of id? tnx

**Comment by ganigeorgiev** [comment]
@VittorioParagallo Yes, with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) users will have more control over the system fields.

**Comment by VittorioParagallo** [comment]
> @VittorioParagallo Yes, with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) users will have more control over the system fields.

@ganigeorgiev 
tnx a lot for your reply and, again, congratulation for your great job. I just finished to completely switch form supabase to pocketbase. So now i've to decide wether to wait for the refactoring of system fields or modify all my domain objects/dto/query to add another non system id field. any idee about the timing of the refactoring of system fields? 



> **Update:** I seem to be able to get around this for now by using `getList` and sending a custom query.
@davidhaley  can you explain me better? i feel I'm facing the same problem of yours.

**Comment by c-nv-s** [comment]
came looking for how I can use https://github.com/jetify-com/typeid or https://github.com/kpiljoong/orderlyid as the ``id`` field and seems this is still not possible yet 🥲

**Comment by ganigeorgiev** [comment]
@c-nv-s That's not true. With PocketBase v0.23+ you can change the `id` and its format but I usually would advice against doing that unless you have a really good reason to do otherwise.

![id_field](https://i.imgur.com/i3ZGWJP.png)

**Comment by ganigeorgiev** [comment]
@PylotLight If you want to specify a prefix/suffix as part of the autogenerated pattern then you can simply include it in the "Autogenerate pattern" field.

_It seems that you've deleted your comment. I'm going to lock this issue as it seems to attract just spam. If anybody has further questions, please open a new Q&A discussion but try to elaborate a little more on your use case and the "WHY" behind it to understand what actually you are trying to do._
