### ISSUE TITLE
Unable to send custom emails

### ISSUE THREAD

**Issue by ruvido** [pocketbase/pocketbase#2460]
Following the example on the docs, I have a collection called "users", trying to send custom emails after creation of new records:
```
app.OnRecordAfterCreateRequest("users").Add(func(e *core.RecordCreateEvent) error {
        message := &mailer.Message{
            From: mail.Address{
                Address: app.Settings().Meta.SenderAddress,
                Name:    app.Settings().Meta.SenderName,
            },
            To:      mail.Address{Address: e.Record.Email()},
            Subject: "YOUR_SUBJECT...",
            HTML:    "YOUR_HTML_BODY...",
            // bcc, cc, attachments and custom headers are also supported...
        }

        return app.NewMailClient().Send(message)
    })
```
However when I do 

`go run main.go serve`

I get the following error:

`./main.go:24:13: cannot use mail.Address{…} (value of type mail.Address) as []mail.Address value in struct literal`

Is it my fault or the docs are outdated?
Can someone help me correct the code?
Thanks

**Comment by ganigeorgiev** [comment]
To docs are incorrect. I'll update the examples sometime later today.

`To`, `Bcc` and `Cc` should be slice of `mail.Address` values, aka. you can try:

```go
app.OnRecordAfterCreateRequest("users").Add(func(e *core.RecordCreateEvent) error {
	message := &mailer.Message{
		From: mail.Address{
			Address: app.Settings().Meta.SenderAddress,
			Name:    app.Settings().Meta.SenderName,
		},
		To:      []mail.Address{{Address: e.Record.Email()}},
		Subject: "YOUR_SUBJECT...",
		HTML:    "YOUR_HTML_BODY...",
		// bcc, cc, attachments and custom headers are also supported...
	}

	return app.NewMailClient().Send(message)
})
```

(_you can also check the godoc for a list with all available Message fields and types - https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.15.3/tools/mailer#Message_)

**Comment by ruvido** [comment]
Holy c**p, that was fast!
Thanks a lot it works perferctly
F
