### ISSUE TITLE
Bug: Web API rule @request.headers.cookie and @request.headers.referer not working

### ISSUE THREAD

**Issue by mrbu-solutions** [pocketbase/pocketbase#2472]
Empty value returned for both @request.headers.cookie and @request.headers.referer when used in API rule/s.

(@request.headers.cookie ~ 'HRPortal' || @request.headers.referer ~ "/user/hr")

**Use case:**
I have a user with multiple roles (i.e. Employee, HR). 
User can switch roles via app switcher.

**Scenarios**
When user role is using Employee role, 'leaves' collection should only return the leaves requested by the user.
When user role is using HR role. 'leaves' collection should return all leave records.

I can't find any identifier from the request object (to know the current user's role) so I set the cookie to have the role ('set-cookie', 'app=HRPortal') and/or check the @request.headers.referer but it always return 0 record.

When I set the rule to @request.headers.cookie = "", it returns all the record which means that the cookie is empty.

**Alternative solution**
temporary solution would be to pass the role to the filter query param but this will leave my collection accessible by any role or by any authenticated users which is not desirable for a db design.

Versions and environment:
Pocketbase: ^0.14.4-rc
Frontend Framework: sveltekit
OS: windows 11
Browsers: edge (latest), chrome (latest)

**Request Header vs API rule:**
![image](https://github.com/pocketbase/pocketbase/assets/53817867/b2675543-3ef6-4555-92d2-87fe3e5c622e)

**Response Body vs Collection Records:**
![image](https://github.com/pocketbase/pocketbase/assets/53817867/c03e4219-e22f-498e-834c-c63f749b2a2a)

_API rule is for demonstration purposes only to show that @request.headers.cookie is not working, not the actual rules._

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it locally. Both the cookie and referer header are passed down to the `@request.headers.*` filter. We read all available headers and the only normalization we apply is normalizing the header name converting them to lowercase and replacing `-` with `_`. The value is passed as it is (**if there are multiple headers with the same name we will keep only the first value**).

The reported ^0.14.4-rc version I guess is for the JS SDK. The support for `@request.headers.*` filter comes with PocketBase v0.14+ executable (you can find your current version in the bottom-right corner in the Admin UI).

I don't have the full picture of your use case and I'm not entirely sure what you are trying to do, but keep in mind that everyone can send a cookie with the request so you shouldn't treat is a security control unless the cookie value is some fixed token. Sending a plain cookie value as in your case is no different than sending an additional query parameter in the url.
