### ISSUE TITLE
Empty an entire collection at once?

### ISSUE THREAD

**Issue by codeit-ninja** [pocketbase/pocketbase#2482]
Lets say I have a collection containing a million records and I want to empty this collection at once, whats currently the best way to do that?

I dont see an option inside the admin UI to empty a collection.

**Comment by ganigeorgiev** [comment]
There is no such option from the Admin UI at the moment. This will be handled as part of https://github.com/pocketbase/pocketbase/issues/2238.

Existing workarounds:

1. Use the `sqlite3` cli tool and run:
   ```sh
   sqlite3 ./pb_date/data.db 'delete from yourCollection'
   ```

2. Duplicate the existing collection (_Admin UI > Collections > Edit collection (settings cogwheel) > 3-dots menu > Duplicate_), delete the old collection and then rename the new collection back to the original.
