### ISSUE TITLE
Feature Request: Scrollable table body in /collections page (UI)

### ISSUE THREAD

**Issue by lirc572** [pocketbase/pocketbase#2505]
It would be nice if we can scroll the<tbody> in the /collections page (the one that lists collection records) so we can always see the table header when scrolling down.

This will also make it easier to find the horizontal scrollbar at the bottom when the content is long.

**Comment by georgexchelebiev** [comment]
This sounds like a good first contribution and I'm up for implementing it if it gets the go ahead.

**Comment by ganigeorgiev** [comment]
This is implemented in the `develop` branch and will be part of the next v0.19.0 release (_there are no ETAs yet_).

_If you want to test it locally:_

0. [Install Go 1.18+](https://go.dev/doc/install)
1. Checkout or clone the `develop` branch
   ```sh
   git clone https://github.com/pocketbase/pocketbase.git --branch develop --single-branch
   ```
2. Navigate to `examples/base`
3. Run `GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build` (_https://go.dev/doc/install/source#environment_)
4. Start the created executable by running `./base serve`.
