### ISSUE TITLE
Feature Request: Return Icon for each OAuth2 method when listing

### ISSUE THREAD

**Issue by dalurness** [pocketbase/pocketbase#2509]
Just for convenience it would be awesome if the `/auth-methods` endpoint included a url stored in the server to an icon for each OAuth2 method.

**Comment by ganigeorgiev** [comment]
This is not planned as it would be too dependent on the Admin UI.

It is better to provide the OAuth2 logos on your own client-side.

If you really want to use the existing Admin UI logos, you can request for example:

```
https://pocketbase.io/_/images/oauth2/{providerKey}.svg
```

But keep in mind that there are no guarantees that the above will not change in the future.
