### ISSUE TITLE
Admin UI: Select field search not showing - searchable={field.options?.values > 5}

### ISSUE THREAD

**Issue by maxNodeJs** [pocketbase/pocketbase#2510]
Admin UI, when creating collection and adding Select field all is fine, however when editing a record the select dropdown doesn't display the search facility.

I have checked the UI code and found in the SelectField component, you have searchable={field.options?.values > 5}. The values as you know is an Array of choices, and therefore it always return false. I guess it should be searchable={field.options?.values?.length > 5} ?

Unless you have done this on purpose to disable the search, it would be nice to have this facility back.

Thanks

**Comment by ganigeorgiev** [comment]
Yes, `length` was missing from the check. I've pushed a fix in the `develop` branch and it will be available with the upcoming v0.16.0 release (_most likely next week_).
