### ISSUE TITLE
Feature Request: notify realtime subscribers when a record becomes unavailable

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/pocketbase#2522]
Currently, in a collection has a list API view limiting user access to _some_ records (for example, shows only records with "visible" field set to true), and someone (maybe admin) changes item visibility (flips the "visible" field in my example), then:

* if previously _invisible_ record becomes **visible** - subscribers receive an "update" record
* if previously **visible** record becomes _invisible_ - subscribers don't receive any notification at all

I believe it would be good if subscribers would receive notification in the second case, too.

Although I'm not sure what's the best way to tell subscribers about this. Should it be "update" type message with all fields empty, to hint subscribers that record still exists, but is unavailable? Or maybe it's best to reuse "create"/"delete" event types for both of these cases? Or add new event types? I'll let @ganigeorgiev decide on this :)

This might also be relevant to "filter" support in #1657 - will subscribers receive notification when after a change record disappears from their filter?

**Comment by ganigeorgiev** [comment]
The invisible -> visible case should work if you subscribe for example to the wildcard topic of the collection (aka. `*`). You should receive a regular `update` record event.

For the visible -> invisible change notification - I don't think this can be implemented easily at the moment without complicating the internals and storing somewhere the previously sent client event messages and/or performing an additional access check before each record change (_which could have some performance penalty and eventually increase the messages latency_).

There are plans in the future to add support for offline data sync that eventually could include also this use case, but for now this remains out of the scope for v1.
