### ISSUE TITLE
Feature Request: Let admins authenticate users without password

### ISSUE THREAD

**Issue by vypxl** [pocketbase/pocketbase#2524]
I am playing around with passkey based login, and got it to work, the only problem is, when I successfully authenticated
the user with their passkey, I have no way to let pocketbase know that.

Until #406 is implemented, I want to propose a way for the backend to authenticate a user without their intervention.

Something along the lines of `pb.collection('users').authManual(userID)`. This could be set to only be accessible by admins, so the backend could authenticate as an admin and log in a user after they successfully presented a passkey.

**Comment by ganigeorgiev** [comment]
Option for admins to generate auth user tokens by user id eventually will be handled in https://github.com/pocketbase/pocketbase/issues/718.

As a workaround for now, you can [register a custom Go route](https://pocketbase.io/docs/router/#register-new-route) and use the [`tokens.NewRecordAuthToken()`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.16.0/tokens#NewRecordAuthToken) to return a record token by the record id (see also [Fetch single record](https://pocketbase.io/docs/record-methods/#fetch-single-record)).
