### ISSUE TITLE
Export Collections -> Download as JSON seems broken

### ISSUE THREAD

**Issue by john-yick** [pocketbase/pocketbase#2540]
Version: 0.16
Browser: Chrome

When pressing the "Download as JSON" nothing happens, but looking at the console it seems to be calling a function that does not exist.

```
index-3f8c6248.js:4 Uncaught ReferenceError: download is not defined
    at W.downloadJson (index-3f8c6248.js:4:131495)
    at f (index-3f8c6248.js:202:2340)
    at HTMLButtonElement._ (index-3f8c6248.js:202:2714)
```

**Comment by ganigeorgiev** [comment]
Thanks. I pushed a fix in `master` and it will be part of v0.16.1 sometime later today.
