### ISSUE TITLE
Feature Request: Option to automatically compress SQLite DB using sqlite-zstd

### ISSUE THREAD

**Issue by kevmodrome** [pocketbase/pocketbase#257]
There was recently a thread on HN that popped up about a new SQLite extension that lets you claw back some storage space without affecting performance: https://github.com/phiresky/sqlite-zstd

Would be neat to have this on by default. The benchmark shows some pretty sizable disk saving. [Announcement post here as well](https://phiresky.github.io/blog/2022/sqlite-zstd/).

**Comment by ganigeorgiev** [comment]
This looks interesting but it is very experimental at the moment and I'm not sure how portable the sqlite extension is and whether it would be easy to transpile and integrate into the CGO-free sqlite ([modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite)) that PocketBase is using by default.

For now this will remain out of the roadmap, but I'll keep an eye on the project.

**Comment by ganigeorgiev** [comment]
_Old issues cleanup: I'm closing this as I don't plan working on it. With the upcoming PocketBase v0.23 release users will have the option to specify custom `connectDB` function as part of the app config allowing custom SQLite builds if they needed (as long as they satisfy the std `database/sql` abstraction)._
