### ISSUE TITLE
Change HTML page of verification, password reset emails etc.

### ISSUE THREAD

**Issue by gdrose** [pocketbase/pocketbase#2576]
I was wondering if there was a way of changing the HTML body of the page that is being rendered after clicking on emails for example when verifying the account: 
![image](https://github.com/pocketbase/pocketbase/assets/63345060/d1e681b9-b284-43d0-9dee-ba1ab06d5e81)

I would like to just edit the close button to redirect to another page instead of closing (also add a little bit of styling).

**Comment by ganigeorgiev** [comment]
You can change the default email template actiuon url from:
_Admin UI > Settings > Mail Settings > {email template} > Edit the "Action URL" input:

![email_template screenshot](https://camo.githubusercontent.com/4e8846c56094d471e0cdb210aa1667dfd82e0d045b7cd2a00e18fc81764306db/68747470733a2f2f692e696d6775722e636f6d2f39356651514d522e706e67)

**Comment by gdrose** [comment]
This is not really what I'm going for, but I see what you're trying to say. I wanted to change the html body not of the email but of the page that's rendered once you click the `{APP_URL}/_/#/auth/confirm-verification/{TOKEN}` link. I would like to do this for a better user experience when going through the process of creating and verifying an account.

**Comment by ganigeorgiev** [comment]
> I wanted to change the html body not of the email but of the page that's rendered once you click the {APP_URL}/_/#/auth/confirm-verification/{TOKEN} link.

@gdrose That's why I suggested to provide your own custom url to the confirmation page, aka. change the "Action URL" input.

**Comment by HEAVYPOLY** [comment]
Hi, I would like for user to click verification link in email, become verified, then redirect to my site with verified account.  What is the recommended way to do this?

If I replace ACTION URL in the email with my pageurl I'm guessing it will skip the pockethost verification api.  Does the user still get verified somehow?

**Comment by ganigeorgiev** [comment]
@HEAVYPOLY If you provide your own custom "Action URL", you'll have to send `pb.collection("users").confirmVerification("TOKEN")` request from inside your custom page.

The verification token can be accessed from the URL that the user clicked.
When overridding the "Action URL" you can use the `{TOKEN}` placeholder as path or query parameter.
In case the token is passed as query parameter, you can access it using the native `URLSearchParams`:

```js
const params = new URLSearchParams(window.location.search);
console.log(params.get("token"));
```

**Comment by HEAVYPOLY** [comment]
Thanks for the quick reply @ganigeorgiev!  Something like this looks ok?:

```
const locationHandler = async () => {
	var location = window.location.hash.replace("#", "");
	if (location.length == 0) {
		location = "/";
	}
  if (location.startsWith('emailVerification')){
    console.log("EMAIL VERIFICATION ROUTE HIT ", pb.authStore, accessToken)
    var accessToken = new URLSearchParams(window.location.hash).get('access_token')
    pb.collection("users").confirmVerification(accessToken)
    pb.authStore.save(accessToken, null);
    await pb.collection("users").authRefresh()
  }
};
window.addEventListener("hashchange", locationHandler);
locationHandler();
```

**Comment by ganigeorgiev** [comment]
@HEAVYPOLY Not exactly. Note that the verification token is different from the auth token, so calling `pb.authStore.save(token)` in this case is incorrect and the following `authRefresh()` call will fail. If the user is not authenticated after clicking on the email, after the confirmation you have to redirect them to the login page.

**Comment by HEAVYPOLY** [comment]
Thanks.  This almost works:
the user is verified in pocketbase dashboard, but in console.log("EMAIL VERIFIED", pb.authStore.model) user verified = false
```
    var accessToken = new URLSearchParams(window.location.hash).get('access_token')
    console.log("EMAIL VERIFICATION ROUTE HIT ", pb.authStore, accessToken)
    await pb.collection("users").confirmVerification(accessToken)
    await pb.collection("users").authRefresh()
    user = pb.authStore.model
    console.log("EMAIL VERIFIED", pb.authStore.model)
    ```

**Comment by ganigeorgiev** [comment]
@HEAVYPOLY The above code should work if the current `confirmVerification()` is for the current authenticated user. If that's not the case, please provide a more complete code sample.

**Comment by HEAVYPOLY** [comment]
It's working now!  (forgot to push the authRefresh commit to dev server)
Thanks for the help.

Few more questions:
1.  Clicking link in email opens a duplicate tab of my webapp, is it possible to use the existing tab instead?
2.  Google is flagging the website as phishing / dangerous now.  Is this because of sending the token as hash in the URL?  
3.  If sending token in URL as hash is not safe, is it better to use default pocketbase verification link and realtime subscribe to user verified in the webapp?

**Comment by ganigeorgiev** [comment]
@HEAVYPOLY

> 1. ... is it possible to use the existing tab instead?

I don't think it is possible since the mail client doesn't have access to the other tabs and can't control which tab to "replace".

---

> 2. ... Is this because of sending the token as hash in the URL?
> 3. ... is it better to use default pocketbase verification link and realtime subscribe to user verified in the webapp?

No, I doubt that this is the case because the PocketBase url also contains the token. I'm not sure what could be the reason for flagging the website as dangerous but this could help:
- the email text doesn't have typos and text/words that are usually used in phishing email
- ensure that the link is using https
- the email is signed and has the correct DMARK, DKIM and SPF domain DNS records

**Comment by HEAVYPOLY** [comment]
Thanks, in that case maybe realtime subscription is the cleaner option vs opening duplicate tab of the webapp.

Realtime was so extremely easy to setup, I'm amazed!  Thanks for your amazing work on pocketbase.

**Comment by ivanpajon** [comment]
I was about to give up and I just came across this Pull Request by chance. I think the official documentation really needs to have this explanation of how to implement custom **pages** for the "_Verification_", "_Password reset_" and "_Confirm email change_" templates 🙏🏼

**Comment by MaRaMinden** [comment]
I think the easiest way to solve this for our app would be the ability to specify a redirect url directly within pocketbase that is called after the respective action (verification, reset, confirmation) has taken place in pocketbase. At least for us, it's totally fine to not have "our" design on the reset/verification/confirmation page itself, as long as the user is redirected to our site after the action has taken place.

**Comment by ganigeorgiev** [comment]
@MaRaMinden It is not clear to what actually you are replying. If you want to specify a custom reset/verification/etc. pages then you can do that by updating the url in the mail template from your collection options. If you need further help, please consider opening a new Q&A discussion with a little bit more details.

**Comment by MaRaMinden** [comment]
Apologies, will do, thanks so much for the quick reply and your work here!
