### ISSUE TITLE
Feature Request : 2 step verification

### ISSUE THREAD

**Issue by MehediHasannOvi** [pocketbase/pocketbase#2578]
1. please add 2 step verification on admin panel 
2. please add ip block

**Comment by ganigeorgiev** [comment]
Admin login with an additional email code verification is already in my todo but for now remains out of the scope (if you haven't already, you can check https://github.com/orgs/pocketbase/projects/2). Passkey/WebAuthn may also be implemented in the future as part of https://github.com/pocketbase/pocketbase/issues/406 but remains a low priority.

For IP whitelist/blacklist for now you can setup PocketBase behind a reverse proxy like nginx (for example https://pocketbase.io/docs/going-to-production/#using-reverse-proxy).
