### ISSUE TITLE
Bug: fetch in Node.js 18 results in ECONNREFUSED error

### ISSUE THREAD

**Issue by gltjk** [pocketbase/pocketbase#258]
Hi, I encountered a problem when I was trying to use the JavaScript SDK with a PocketBase server run locally.

After testing, I manage to drill it down to the following minimal reproduction:

```js
import PocketBase from './node_modules/.pnpm/pocketbase@0.3.0/node_modules/pocketbase/dist/pocketbase.es.mjs'

const url = 'http://localhost:8090'

console.log('---SDK---')

await sdk()

console.log('\n---Vanilla Fetch---')

await vanilla()

async function sdk () {
  const client = new PocketBase(url)
  return client.admins
    .authViaEmail('test@example.com', '123456')
    .then(() => console.log('ok'))
    .catch(err => console.log(err))
}

async function vanilla () {
  return fetch(url)
    .then(() => console.log('ok'))
    .catch(err => console.log(err))
}
```

The output is as follows:

```
-----SDK-----
(node:52800) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ClientResponseError 0: Something went wrong while processing your request.
    at new i (file:///.../node_modules/.pnpm/pocketbase@0.3.0/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2078)
    at file:///.../node_modules/.pnpm/pocketbase@0.3.0/node_modules/pocketbase/dist/pocketbase.es.mjs:1:23237
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///.../test.js:7:1 {
  url: '',
  status: 0,
  data: {},
  isAbort: false,
  originalError: null
}

-----Vanilla Fetch-----
TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:6277:34)
    at node:internal/deps/undici/undici:6602:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED ::1:8090
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 8090
  }
}
```

As is shown above, it seems that the PocketBase server refuses the request sent by `fetch` in Node.js, and thus leads to the unknown `ClientResponseError` with the JavaScript SDK.

However, when I tried Deno with the same code, everything worked just fine (the 400 error is expected given only sample authentication info is sent), and the output is as follows:

```
---SDK---
ClientResponseError 400: Failed to authenticate.
    at new i (file:///.../node_modules/.pnpm/pocketbase@0.3.0/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2078)
    at file:///.../node_modules/.pnpm/pocketbase@0.3.0/node_modules/pocketbase/dist/pocketbase.es.mjs:1:23237
    at async file:///.../test.js:7:1

---Vanilla Fetch---
ok
```

Here is the system info if necessary:

- OS: MacOS Monterey v12.4.0
- Node.js: v18.7.0
- Deno: v1.24.1
- PocketBase: v0.3.4
- PocketBase JavaScript SDK: v0.3.0

I am not sure what is happening, and hopes for an investigation from the community and, if possible, a solution. Thank you!

**Comment by ganigeorgiev** [comment]
@gltjk Could you make sure that the PocketBase backend is running (aka. is the Admin UI accessable)?

I'm not able to reproduce the issue. Just tested with Node v18.7.0 on Fedora with the latest PocketBase app and sdk versions:
```js
import PocketBase from "pocketbase";

const client = new PocketBase("https://pocketbase.io");

client.admins.authViaEmail(
  "test@example.com",
  "123456"
).then((result) => {
  console.log("Result:", result)
}).catch((err) => {
  console.log("error:", err)
});
```

You could try connecting to the live demo (https://pocketbase.io) as shown in the above to rule out eventual issue with nodejs.

Usually `ECONNREFUSED` is thrown when a connection with the server cannot be established - maybe there is a firewall or missing loopback address. You could also try starting the executable with explicit ipv4 localhost address, eg.:
`./pocketbase serve --http="127.0.0.1:8090"`

**Comment by gltjk** [comment]
@ganigeorgiev I am sure the backend is running, for Deno gives the correct result, and the Admin UI is accessible as well. I tried directly connecting to the live demo just now and both Node.js and Deno are working well. I suspect this might be a MacOS exclusive problem since I reproduced it on two MacBook Pros and one Mac Mini. I also tried restarting the executable with explicit ipv4 localhost address or different ports, and still got the same result: Deno worked but Node.js failed.

**Comment by ganigeorgiev** [comment]
@gltjk Actually I was able to reproduce it when using a local PocketBase instance. Try changing the `localhost` part with `127.0.0.1` when initializing the client, eg.:
```js
const client = new PocketBase("http://127.0.0.1:8090");
```

This is not specific to PocketBase, but I'm not sure why `localhost` in nodejs is resolved to `::1` (maybe is something related to how the underlying [dns.js](https://nodejs.org/api/dns.html) module resolves the host?).

**Comment by ganigeorgiev** [comment]
Another alternative if you don't want to change your nodejs code to use the ipv4 address localhost address is to start the executable with the ipv6 equivalent:
```
go run main.go serve --http="[::1]:8090"
```

**Comment by ganigeorgiev** [comment]
@gltjk I found the related nodejs issue - As mentioned in https://github.com/nodejs/node/issues/40537, It seems that in nodejs 17+ the default order the ip addresses are returned from the resolver/DNS has changed and ipv6 are with higher priority.
You can change this behavior by starting your node service with `--dns-result-order=ipv4first`.

**Comment by gltjk** [comment]
@ganigeorgiev Replacing ‘localhost’ with ‘127.0.0.1’ works. Thanks a lot for both the workaround and helping me discover a new feature since Node.js 17 that I’ve failed to notice. Maybe it would be clearer if you could accordingly update the examples in the documentation as well as JavaScript SDK’s readme? This way future users won’t get into the same trouble trying to run the examples. Anyway, I’ll consider this issue resolved. THX.
