### ISSUE TITLE
Feature request: Add option to toggle the visibility of the table listing columns in the Admin UI

### ISSUE THREAD

**Issue by linktohack** [pocketbase/pocketbase#259]
When the tables come with a lot of fields, allows user/admin to configure what he/she want to retrieve (API) or display (on the Admin Dashboard) is nice (and efficient)

We may want allow admin to arrange fields and/and or configure the length of the fields at some point or to not consider at for the sake of simplicity...

**Comment by ganigeorgiev** [comment]
For now I'll consider for the roadmap only the option to allow admins to show/hide the visible listing columns in the listings.

For filtering which api fields to be returned (both by users and admins) we can add a `?fields=...` query parameter, but I'll have to think a little more on this and may combine it with the ["hidden api fields" request](https://github.com/pocketbase/pocketbase/discussions/138) in the future.

**Comment by ganigeorgiev** [comment]
Option to toggle the visibility of the table admin columns was added in the latest [v0.8.0-rc1 pre-release](https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1).
