### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by JatinjayJAM** [pocketbase/pocketbase#2603]
I can't clear logs.

**Comment by ganigeorgiev** [comment]
To clear the logs you can temporary disable them by updating the _"Admin UI > Settings > Application > Logs max days retention" field  and set it to `0` (_it'll also run `VACUUM` on the logs db so the previously taken space also should be released_).

**Comment by JatinjayJAM** [comment]
> To clear the logs you can temporary disable them by updating the _"Admin UI > Settings > Application > Logs max days retention" field and set it to `0` (_it'll also run `VACUUM` on the logs db so the previously taken space also should be released_).

thank you
