### ISSUE TITLE
OIDC with a username which contains special characters

### ISSUE THREAD

**Issue by razem-io** [pocketbase/pocketbase#2606]
Hi, thank you for the fantastic project!

We are using PocketBase with Keycloak as an OIDC to authenticate our users. One of these users has special characters in its username. In the error case `ü`. The username then defaults to an `users12345` fallback. If I try to change the username manually to the correct one, I get an error: 

```
{
  "code": 400,
  "message": "Something went wrong while processing your request.",
  "data": {
    "username": {
      "code": "validation_match_invalid",
      "message": "Must be in a valid format."
    }
  }
}
```
If I replace the special characters, I am able to change the username.
I checked the documentation and haven't found any information about a restriction there. Is this intentional, or is this a bug?

**Comment by ganigeorgiev** [comment]
It is an existing limitation - currently usernames must comply with the `^[\w][\w\.]*$` pattern.

This eventually will change in the future as there are plans to convert the `username` field to a regular `text` field and allow users to customize its pattern and min length however they want (you can read more in https://github.com/pocketbase/pocketbase/discussions/2425#discussioncomment-5818276; it will be handled as part of task https://github.com/orgs/pocketbase/projects/2?pane=issue&itemId=28015952).
