### ISSUE TITLE
Feature Request: Thumbnails for videos

### ISSUE THREAD

**Issue by emanrdesu** [pocketbase/pocketbase#2608]
Title is self explanatory, I'd like to get thumbnails for video files in the database.
This can be done by adding in ffmpeg as a dependency.
Maybe ffmpeg doesn't have to be embedded, but maybe the pocketbase executable can check if the ffmpeg binary is in the system and use it if it does.

**Comment by ganigeorgiev** [comment]
This was requested previously in https://github.com/pocketbase/pocketbase/pull/91, but at least for now remains out of the scope for v1.
