### ISSUE TITLE
Patch API returns 404

### ISSUE THREAD

**Issue by User00092** [pocketbase/pocketbase#2624]
```py
response = httpx.patch(
	f'https://------/api/collections/VersaTool_userbase/records/:hyl5nyzovig8k0c',
	json={
		'username': f'{username}'
	},
	headers={
		'User-Agent': '5.0 (Windows NT 10.0; WOW64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
				            'Chrome/113.0.5666.197 Safari/537.36'
	}
)
json_data = response.json()
if response.status_code == 200:
	return {
		'status': True,
		'message': 'Successfully changed username.'
	}

elif response.status_code == 400:
	for i in json_data['data']:
		return {
			'status': False,
			'message': f'{i.title()}: {json_data["data"][i]["message"]}'
		}

elif response.status_code == 403:
	for i in json_data['data']:
		return {
			'status': False,
			'message': f'You are not allowed to perform this request. {json_data["data"][i]["message"]}'
		}

else:
	return {
		'status': False,
		'message': 'The requested resource wasn\'t found.'
	}
```

Output: {'status': False, 'message': "The requested resource wasn't found."}

I attempted to add an email to the JSON, but it was unsuccessful.
Maybe this is sleep deprivation kicking in, but I've tried everything I can in this state. 

![image](https://github.com/pocketbase/pocketbase/assets/103274860/f51464c4-3ea9-4810-ae44-81a4c2252735)
![image](https://github.com/pocketbase/pocketbase/assets/103274860/e1f879dd-04a3-4643-af50-c092486a70dc)

**Comment by User00092** [comment]
I would like to note that I'm on version 0.16.3.

**Comment by ganigeorgiev** [comment]
The url doesn't seem correct - there is a `:` in front of the id.

If that's not the case and it is just a typo in the example, make sure that your client request satisfy the collection Update API rule.

If the above doesn't help, please export your collections configuration as JSON (Admin UI > Settings > Export collections) and I'll try to investigate it further.
