### ISSUE TITLE
Feature request: disable creation of duplicate fields

### ISSUE THREAD

**Issue by theMackabu** [pocketbase/pocketbase#263]
Similar to the unique toggle, it would be a toggle in the collection settings to prevent 2 records with identical fields

**Comment by ganigeorgiev** [comment]
Just to make sure that I understand the request. For example if you have 3 fields - `title`, `description`, `status` you want the following behavior:
```
'test'     |  'lorem ipsum...'   |  'active'
---
'test'     |  'lorem ipsum...'   |  'active'     --- disallow (all 3 fields match)
---
'test'     |  'lorem ipsum...'   |  'changed'    --- allow (different status)
---
'test'     |  'changed'          |  'active'     --- allow (different description)
---
'changed'  |  'lorem ipsum...'   |  'active'     --- allow (different title)
```

Or in other words - you want a unique constraint that combines all collection fields, right?

This could be added, but I think it may cause some confusions when combined with the individual unique field constraint an I'm not sure how many users will actually use it.

Why do you need it in the first play - can you share your use case?

You can also accomplish this on your own by using the hooks and perform a custom query check OR add a multi-column unique index (that will also add a constraint) via DB migration (or directly with sqlite3 cli):
```sql
CREATE UNIQUE INDEX combined_unique_idx ON YOUR_TABLE (field1, field2, field3);
```

**Comment by theMackabu** [comment]
> you want a unique constraint that combines all collection fields, right?

yep thats correct

> Why do you need it in the first pla(ce) - can you share your use case?
The user is only allowed to have one of any type of relation:

- the user purchases a product
- the product is written to a record with the user id
- the user can now generate the download token using that record
- the record is created from a stripe webhook
- if the record already exists, cancel the stripe checkout

**Comment by ganigeorgiev** [comment]
I'm still not sure that I fully understand your use case, but if for example the stripe webhook fires multiple times and you want to prevent creating multiple records for the same event, you can make use of the following helper method (_I didn't test it_):

```go
func IsRecordUnique(dao *Dao, record *models.Record) bool {
	var exists bool

	expr := dbx.HashExp{}
	data := record.Data()
	for k, v := range data {
		expr[k] = v
	}

	err := dao.RecordQuery(record.Collection()).
		Select("count(*)").
		AndWhere(dbx.Not(dbx.HashExp{"id": record.Id})).
		AndWhere(expr).
		Limit(1).
		Row(&exists)

	return err == nil && !exists
}
```

I'm more inclined to add something like the above in the Dao, rather than add a collection setting in the API/Admin UI because the use case for this, at least to me, seems very user specific.

**Comment by theMackabu** [comment]
I found with dbx, a temporary way to handle this is
```go
			  expr := dbx.HashExp{"user": user.Id, "resource": c.PathParam("id")}
			  purchase, _ := app.Dao().FindRecordsByExpr(purchases, expr)
			  
			  if (len(purchase) > 0) {
				  return c.JSON(402, map[string]string{
						 "error": "Resource already purchased.",
						 "resource": c.PathParam("id"),
					 })
			  }
```

**Comment by theMackabu** [comment]
did we just comment at the same time

**Comment by theMackabu** [comment]
> I'm still not sure that I fully understand your use case, but if for example the stripe webhook fires multiple times and you want to prevent creating multiple records for the same event, you can make use of the following helper method (_I didn't test it_):
> 
> ```go
> func IsRecordUnique(dao *Dao, record *models.Record) bool {
> 	var exists bool
> 
> 	expr := dbx.HashExp{}
> 	data := record.Data()
> 	for k, v := range data {
> 		expr[k] = v
> 	}
> 
> 	err := dao.RecordQuery(record.Collection()).
> 		Select("count(*)").
> 		AndWhere(dbx.Not(dbx.HashExp{"id": record.Id})).
> 		AndWhere(expr).
> 		Limit(1).
> 		Row(&exists)
> 
> 	return err == nil && !exists
> }
> ```
> 
> I'm more inclined to add something like the above in the Dao, rather than add a collection setting in the API/Admin UI because the use case for this, at least to me, seems very user specific.

This feels like a much better solution, ill try it

**Comment by ganigeorgiev** [comment]
Your solution also is OK, but keep in mind that in my example I'm checking all fields of the record and this may not be what you are after, because in your example you are searching only for the `userId` and `resource` fields.

In any case, I'll close the issue for now because I think this is too user-land specific and it will be hard to generalize.
Depending on the user demand I may reconsider it, but for now I'll leave it out of the roadmap.
