### ISSUE TITLE
CommenHelper crashes from time to time

### ISSUE THREAD

**Issue by stevengpn** [pocketbase/pocketbase#2714]
It's very weird, CommenHelper .js works fine until made few changes to it, even rolled back to the original version.

#Uncaught SyntaxError: Unexpected token '.' (at CommonHelper.js?t=1686794553392:744:39)
It seems not happy with this syntax when it gets recompiled? 
` if (!text.length || !window?.navigator?.clipboard) {`

And it keeps coming to new similar issues after fixing each one of them, but there are just too many this kind of syntax.

Why?

**Comment by ganigeorgiev** [comment]
Similar to https://github.com/pocketbase/pocketbase/discussions/2716, please elaborate what you are trying to do and open a new discussion.

`CommonHelper` and the UI in general is not extendable and it is not intended to be used by user land code.
