### ISSUE TITLE
Feature request: Customizable id field

### ISSUE THREAD

**Issue by Voxeliorn** [pocketbase/pocketbase#2727]
in case you know that you will have a LOT of records. For example, you can go to settings and choose the length of IDs for each collection.  wow I'm so smart (I hope that this does not exist yet because I haven't found it 🥰🥰)

**Comment by ganigeorgiev** [comment]
If the only reason for a custom id length is the number of records, then you shouldn't really worry about this (_with the default random generator you can get up to ~36^15_).

The current default limit is 15 chars and it is there to preserve the API rules backward compatibility with earlier versions.

It may get removed sometime in the future, or at least made customizable, because other users also requested to be able to change it (eg. for UUID, KSUID, slugs, etc.), but for now remains a low priority.

**Comment by Voxeliorn** [comment]
> If the only reason for a custom id length is the number of records, then you shouldn't really worry about this (_with the default random generator you can get up to ~36^15_).
> 
> The current default limit is 15 chars and it is there to preserve the API rules backward compatibility with earlier versions.
> 
> It may get removed sometime in the future, or at least made customizable, because other users also requested to be able to change it (eg. for UUID, KSUID, slugs, etc.), but for now remains a low priority.

Why not make it so that ids can be from 3 to like 20 chars so you can just update and your old records can stay 15 chars or you can regenerate them idk (I don't even understand what you mean by API rules backward compatibility) but okay

**Comment by bl0ckO** [comment]
What is the best way to have numeric id?
1,2,3,4....

**Comment by mufidat3250** [comment]
@bl0ckO  kkk

**Comment by mufidat3250** [comment]
> @bl0ckO The current ID field is string only. You can define your own `number` field and create a unique index for it from the Admin UI.

kkk

**Comment by bl0ckO** [comment]
But then I can't use the JS sdk easily. Instead I might covert `number` to `string` and set as `id`
Like `000000000000001` `000000000000002` `000000000000003`...

**Comment by Voxeliorn** [comment]
whoa well this is active

> You do realize 36^15 is beyond anything any application will ever use right? and by the time you need more than this, you're loaded $, and changing this is trivial. Unless you're indexing atoms or something, why. 36^15 = 221,073,920,000,000,000,000,000~
> 
> You're trying to fix a problem that doesn't exist.
> 
> As far as making it less, you haven't even given a reason why.

well my math was wrong and i just realised so yeah....

**Comment by bl0ckO** [comment]
@ganigeorgiev I want todo this from JS SDK. Is this possible?
> @bl0ckO The current ID field is string only. You can define your own number field and create a unique index for it from the Admin UI.

**Comment by javea7171** [comment]
Would be good to have the option to use semantic IDs that convey meaning rather than just random characters.The primary key is included in every index so reducing its size should improve performance as well
