### ISSUE TITLE
Feature request: Linkedin auth

### ISSUE THREAD

**Issue by anggoran** [pocketbase/pocketbase#2729]
Linkedin auth can help developers to ensure that their users are credible, and best of all their [API is free](https://www.linkedin.com/legal/l/api-terms-of-use#:~:text=Costs%20and%20Fees). Maybe it can be implemented in Pocketbase

**Comment by ganigeorgiev** [comment]
I think this should be already supported if you use the universal OpenID Connect (`oidc`) provider - https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2.
