### ISSUE TITLE
Feature request: Add anonymous login feature for user side

### ISSUE THREAD

**Issue by prateekcode** [pocketbase/pocketbase#273]
There are certain cases when we need to read the Database without login and still, we want to show data to our users for that purpose Anonymous login feature can help. 
Did you get the idea of this feature?

**Comment by ganigeorgiev** [comment]
I think this is already supported through the [Collection API rules](https://pocketbase.io/docs/manage-collections/#collection-api-rules).

For example, let's say that you have a collection `articles` with a `status` select field. The following rule allows for everyone to access the `status='public'` records, while also restricting `status='membership'` access to only the registered users:
```
status = 'public' || (status = 'membership' && @request.user.id != "")
```

**Comment by ganigeorgiev** [comment]
@prateekcode I'll close the issue for now since this seems to be already covered, but if the above is not what you are looking for, please let me know and I'll review it more thoroughly.

**Comment by prateekcode** [comment]
Thanks, I'm going to use it in my next app Pocketbase as backend 😍. Is there any planning for a native Android SDK?

**Comment by ganigeorgiev** [comment]
> Is there any planning for a native Android SDK?

Unfortunately I have very little experience with Android development (Kotlin) and for now I don't plan working on native Android SDK.

Community contributions are more than welcome. If you want to work on this, you could check the [Dart SDK](https://github.com/pocketbase/dart-sdk) and emulate its API in Kotlin/Java.

**Comment by helmuthb** [comment]
Sorry for adding a comment on a closed issue...

I was thinking about a web-based chat and thought that would be a use case for an "anonymous login".
It would be more than just having access to data without being logged in. A user would be able to login anonymously - i.e. they would be a user identity, and the records they are allowed to create (according to rules) are tagged as created by them. Users would be able to see their chat messages and the replies they get, even though they would not have to login with username / password. Instead, with some API call they would be assigned a token (or some other kind of credentials) which identifies them uniquely as an anonymous entity.

**Comment by ganigeorgiev** [comment]
@helmuthb I understand the use case, but I don't think there is a need for a special auth type handling. In the next release (v0.8.0) the user email  field will no longer be required by default and will be a toggle option, so you'll be able to create a dummy/empty user with just a password that you can generate randomly and store locally on the client device (eg. localstorage) to allow "upgrades" by authenticating the anonymous user in the background and performing an update on the missing fields.
