### ISSUE TITLE
Feature Request: Apple/Google native sign-in

### ISSUE THREAD

**Issue by laeo** [pocketbase/pocketbase#2730]
Apple requires app use native sign-in instead of browser-based OAuth authentication, is there any plan to support this?

**Comment by ganigeorgiev** [comment]
> Apple requires app use native sign-in instead of browser-based OAuth authentication

I'm not aware of such requirement. As far as I know, the only requirement is to have "Sign-in with Apple", but it doesn't necessarily need to use the native apple sign-in:

> Apps that exclusively use a third-party or social login service (such as Facebook Login, Google Sign-In, Sign in with Twitter, Sign In with LinkedIn, Login with Amazon, or WeChat Login) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option.

In any case, I'm not planning adding support for native Apple auth. Even the existing Apple OAuth2 integration was very cumbersome to implement as I don't have apple developer account.

Users contribution are welcomed.
