### ISSUE TITLE
Feature request: Slow query logging in production

### ISSUE THREAD

**Issue by pnmcosta** [pocketbase/pocketbase#2741]
Hi,

I would like to be able to leverage https://github.com/pocketbase/dbx#logging-executed-sql-statements in production but only when the query/exec exceeds a configurable duration, e.g. >250ms.

I'm using PB as a platform and my custom queries/commands are all issued on `app.Dao()` and sometimes wrapped in a `RunInTransaction`. 

I've tried to see where I could tap into the `dbx`  behaviour on the `Dao` struct but I could not. It would be great if we could programmatically set the whole Dao with `QueryLogFunc` and `ExecLogFunc`.

Alternatively, it would also work if it covers the whole app and is configurable via settings.

Many thanks,

**Comment by ganigeorgiev** [comment]
I'll consider it with the logs generalization.

You have access to `QueryLogFunc` and `ExecLogFunc`, but internally we maintain 2 different connection pools (_mainly to reduce the memory usage when opening new connections and to minimize the `SQLITE_BUSY` errors_) and it's not very pretty:
```go
package main

import (
	"context"
	"database/sql"
	"log"
	"time"

	"github.com/fatih/color"
	"github.com/pocketbase/dbx"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/core"
)

func main() {
	app := pocketbase.New()

	app.OnAfterBootstrap().Add(func(e *core.BootstrapEvent) error {
		app.Dao().NonconcurrentDB().(*dbx.DB).QueryLogFunc = func(ctx context.Context, t time.Duration, sql string, rows *sql.Rows, err error) {
			// replace with your own custom log requirement...
			color.HiBlack("[%.2fms] %v\n", float64(t.Milliseconds()), sql)
		}
		app.Dao().ConcurrentDB().(*dbx.DB).QueryLogFunc = app.Dao().NonconcurrentDB().(*dbx.DB).QueryLogFunc

		app.Dao().NonconcurrentDB().(*dbx.DB).ExecLogFunc = func(ctx context.Context, t time.Duration, sql string, result sql.Result, err error) {
			// replace with your own custom log requirement...
			color.HiBlack("[%.2fms] %v\n", float64(t.Milliseconds()), sql)
		}
		app.Dao().ConcurrentDB().(*dbx.DB).ExecLogFunc = app.Dao().NonconcurrentDB().(*dbx.DB).ExecLogFunc

		return nil
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

(_not that the `sql` in the callback may not be valid SQL string and it is intended only for dev purposes_)

**Comment by pnmcosta** [comment]
Brilliant, I was missing the `(*dbx.DB)` type casting! Thank you so much.

**Comment by ganigeorgiev** [comment]
The above code sample should work no matter of the `app.IsDebug()` value as it is loaded in `OnAfterBootstrap()` and overwrites any previous state.

**Comment by pnmcosta** [comment]
Yeah I thought that too, I am also setting it `OnAfterBootstrap()`. But it definitely is not overriding the previous handlers. On compiled build it does so not to worried about.

**Comment by ganigeorgiev** [comment]
Could you provide an example?

**Comment by pnmcosta** [comment]
My source is wired up with a lot of parallel stuff, but I'd be happy to take a video and show it. Anywhere I could share with you privately?

**Comment by pnmcosta** [comment]
You're absolutely right, apologies, I must have been looking at a different output somehow, I've just retested this an in fact it overrides it correctly.

**Comment by ganigeorgiev** [comment]
I've decided to leave this out of the scope for now since already a lot of changes accumulated in `master` and this kindof overlap with the recent `execTime` addition to the request logs.

I have somewhere buried in my todo at later stage to consider adding "Alerts" that eventually will have slow queries report as one of the triggers.
