### ISSUE TITLE
Version 1.0 expected date

### ISSUE THREAD

**Issue by syedwalihasan** [pocketbase/pocketbase#2743]
Hi
What is the expected release date of 1.0 version.
Thanks
Wali

**Comment by ganigeorgiev** [comment]
Sorry, there are no fixed ETAs.

For details what is currently planned for v1, you can check https://github.com/orgs/pocketbase/projects/2/views/1.

**Comment by jimkoen** [comment]
> Sorry, there are no fixed ETAs.
> 
> For details what is currently planned for v1, you can check https://github.com/orgs/pocketbase/projects/2/views/1.

Are you ever going to do a feature freeze and then focus on an eventual 1.0 release?
Right now, your versioning system is deterring any developer who might actually want to use your work in a serious use case.

Please either clarify whether you use semver, whether the framework is still unstable and should not be used as part of apps or whether this is not ever planned at all (i.e. is this just an off time, not to be taken serious project).

**Comment by ganigeorgiev** [comment]
@jimkoen We already use semverm but until v1 is releases there is no backward compatability guarantee. For list of changes, please refer to the releases notes accompanying each [release](https://github.com/pocketbase/pocketbase/releases) or the [CHANGELOG.md](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md)

>  is this just an off time, not to be taken serious project

This kindof rub me the wrong way. This is a non-commercial open source project that I work on it on my free time and that I created for my own needs (see the footnote in the bottom of the readme and also https://github.com/pocketbase/pocketbase/discussions/3271). Whether you want to take it seriously is up to you to decide.
