### ISSUE TITLE
Expand data empty after login

### ISSUE THREAD

**Issue by edikurniawan-dev** [pocketbase/pocketbase#2764]
I'm login using this `const authData = await pb.collection('users').authWithPassword(username, password);` but when i `console.log(authData)` or i see pocketbase_auth in localstorage expand data is empty. If i call directly using url i got the expand data. How to fix this?
Thank you

Note : i don't rules in collection

**Comment by ganigeorgiev** [comment]
If you want to expand relations with the auth call, you have to pass the `expand` query parameter, similar as in the other regular getList/getOne requests:

```js
// note the empty body is for extra body params (this will most likely change in the near future)
await pb.collection('users').authWithPassword(username, password, {}, {
    expand: "yourRelField"
})
```

If that's not what you are trying to do, please file a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details.

**Comment by edikurniawan-dev** [comment]
Thank you @ganigeorgiev

**Comment by Salman9000** [comment]
`    const authData = await pb.collection("users")
      .authWithPassword<PBUserRecord>(user, password, {
        expand: "roles"
      `});``

auth data does not have expand in it? Why is that so? 

` {
    record: {
      avatar: '',
      collectionId: '_pb_users_auth_',
      collectionName: 'users',
      created: '2024-04-29 10:19:26.535Z',
      dashboard_options: null,
      email: 'salman.h@techinoviq.com',
      emailVisibility: false,
      favorite: 'mg7jso5gfhqiftc',
      id: '0v90hlpe1v77iq1',
      name: 'Salman Hanif',
      password_changed: true,
      phoneNumber: '12345',
      roles: [ 'lepwlniod7sk8t8' ],
      type: 'admin',
      updated: '2024-08-01 12:12:19.922Z',
      username: 'salman.hanif',
      verified: true
    },
    token: 
      'my token'
  }`
