### ISSUE TITLE
strings.Title is deprecated

### ISSUE THREAD

**Issue by dschissler** [pocketbase/pocketbase#2775]
https://github.com/pocketbase/pocketbase/commit/1cbf16b3bf8256f1b1b3224bf9b1a0bcaa8417e8

https://stackoverflow.com/a/72453258

https://pkg.go.dev/strings#Title

**Comment by ganigeorgiev** [comment]
Thanks, I'll consider replacing it later but for now I don't want to bring an extra package just for that.

**Comment by ganigeorgiev** [comment]
Oh, I actually I forgot that we already have a `inflector.UcFirst` helper...
