### ISSUE TITLE
Feature Request: Allow username-with-password / phone number / email sign-in method

### ISSUE THREAD

**Issue by zzzhouuu** [pocketbase/pocketbase#279]
Some places are more accustomed to using other ways to sign in (etc: phone number) rather than using email. We can choose whether to enable Sign in with Phone number or  Sign in with Email by configuration

**Comment by zzzhouuu** [comment]
Maybe we support each user having a unique primary email and primary phone and implementing Twilio SMS.
Use as framework implementing other send method

**Comment by ganigeorgiev** [comment]
Unfortunately the existing SMS apis are not unified and it is better to leave the implementation details to the users to handle on their own using the existing event hooks.

There is no need to add a fixed phone number field to the `User` model. Developer can define whatever fields they want in the user related `profiles` collection record.

**Comment by zzzhouuu** [comment]
How the current User API hooks implement login by phone，OnUserAuthRequest Triggered on each successful API User authentication request (sign-in, token refresh, etc.). maybe use as framework can implement?

**Comment by ganigeorgiev** [comment]
Yes, you'll have to use it as framework in order to implement your custom business logic. Here is an example locating a single user by a `phone` profiles field:

```go
package main

import (
    "log"
    "net/http"

    "github.com/labstack/echo/v5"
    "github.com/pocketbase/pocketbase"
    "github.com/pocketbase/pocketbase/apis"
    "github.com/pocketbase/pocketbase/core"
    "github.com/pocketbase/pocketbase/tokens"
)

func main() {
    app := pocketbase.New()

    app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
        // adds `POST /api/users/auth-via-phone` endoint
        e.Router.AddRoute(echo.Route{
            Method: http.MethodPost,
            Path:   "/api/users/auth-via-phone",
            Handler: func(c echo.Context) error {
                profiles, err := app.Dao().FindCollectionByNameOrId("profiles")
                if err != nil {
                    return err
                }

                // find the associated user profile
                profile, err := app.Dao().FindFirstRecordByData(profiles, "phone", c.QueryParam("phone"))
                if err != nil {
                    return err
                }

                // find the associated profile user
                user, err := app.Dao().FindUserById(profile.GetStringDataValue("userId"))
                if err != nil {
                    return err
                }

                // generate user token
                token, err := tokens.NewUserAuthToken(app, user)
                if err != nil {
                    return err
                }

                return c.JSON(http.StatusOK, map[string]any{
                    "token": token,
                    "user":  user,
                })
            },
        })

        return nil
    })

    if err := app.Start(); err != nil {
        log.Fatal(err)
    }
}
```

_The documentation will be updated with more in-depth info and advanced examples in the near future._

**Comment by zzzhouuu** [comment]
Thanks for your example, maybe later I can get the basic capabilities by using the username storage mobile phone and then use as framework can implement send SMS
