### ISSUE TITLE
Feature request: add select all records in record picker 

### ISSUE THREAD

**Issue by iMro0t** [pocketbase/pocketbase#2792]
for record type relation with multiple support it provides record picker in UI to pick single or multiple records as well as search filter. it's very useful but only missing select all option. i will be more convenient for adding 100s of records at once. also number of listed records will be useful information too

<img width="960" alt="image" src="https://github.com/pocketbase/pocketbase/assets/25949138/bc42ef56-fcc4-4648-a01f-f80cd4e240dc">

**Comment by ganigeorgiev** [comment]
I've added in my todo to consider eventually adding a number indicating the total found records, but option to "Select all" for now is not planned as it can't be implemented efficiently for large collections (the records in the picker list are lazy-loaded per 100 items on scrollend and merged with the currently selected ones).
