### ISSUE TITLE
Feature Request: Introducing "Secret" Field Type

### ISSUE THREAD

**Issue by HT808s** [pocketbase/pocketbase#2798]
# Context
You know when we need to store sensitive stuff like API keys, secret keys, and other hush-hush data in the database? Well, right now, it's up to us to make sure these data are encrypted before storing and decrypted when we need them. This back-and-forth can be a pain and sometimes it feels like a game of hide-and-seek where we're always "it".

# Proposal
So, let's spice things up with a new field type called "secret". What's cool about "secret"?

**It Does the Heavy Lifting**: When you store data in the 'secret' field, PocketBase would automatically encrypt it. And when you need that data back, it'll decrypt it on-the-fly for you. No more manual encrypt-decrypt shenanigans.

**Safety First**: By handling the encryption right at the database level, we're reducing the chance of data leaks from potential app vulnerabilities or breaches. Think of it as a safe within a safe.

# Potential Approach

We could use a tried-and-true encryption algorithm like AES-256 for the 'secret' field. The keys for encryption/decryption could be securely stored and managed using a Key Management Service (KMS) or we could bake them right into PocketBase.

# Benefits
Adding this feature would mean:

- Leveling up the security of any app using PocketBase.
- Saying goodbye to the hassle of dealing with client-side encryption and decryption.
- Making life easier for devs who need to interact with sensitive data.

# What's Next?
I'd love to hear your thoughts on this. Maybe there's already a simple way of doing this and this feature makes little sense 🤷  
Got any insights on potential challenges, or suggestions for improvements and alternative approaches? Let's get this conversation started!

**Comment by ganigeorgiev** [comment]
Something like this was requested before (eg. https://github.com/pocketbase/pocketbase/discussions/1835#discussioncomment-4946404), but for me the main issue with a `secret` field is that it is not clear how this field will be managed, who will have access to its value and whether the filter/sort operations will work at all.

Could you elaborate on your use case and how do you plan using it?

**Comment by mufidat3250** [comment]
> # Context
> You know when we need to store sensitive stuff like API keys, secret keys, and other hush-hush data in the database? Well, right now, it's up to us to make sure these data are encrypted before storing and decrypted when we need them. This back-and-forth can be a pain and sometimes it feels like a game of hide-and-seek where we're always "it".
> 
> # Proposal
> So, let's spice things up with a new field type called "secret". What's cool about "secret"?
> 
> **It Does the Heavy Lifting**: When you store data in the 'secret' field, PocketBase would automatically encrypt it. And when you need that data back, it'll decrypt it on-the-fly for you. No more manual encrypt-decrypt shenanigans.
> 
> **Safety First**: By handling the encryption right at the database level, we're reducing the chance of data leaks from potential app vulnerabilities or breaches. Think of it as a safe within a safe.
> 
> # Potential Approach
> We could use a tried-and-true encryption algorithm like AES-256 for the 'secret' field. The keys for encryption/decryption could be securely stored and managed using a Key Management Service (KMS) or we could bake them right into PocketBase.
> 
> # Benefits
> Adding this feature would mean:
> 
> * Leveling up the security of any app using PocketBase.
> * Saying goodbye to the hassle of dealing with client-side encryption and decryption.
> * Making life easier for devs who need to interact with sensitive data.
> 
> # What's Next?
> I'd love to hear your thoughts on this. Maybe there's already a simple way of doing this and this feature makes little sense shrug Got any insights on potential challenges, or suggestions for improvements and alternative approaches? Let's get this conversation started!

jjj

**Comment by mufidat3250** [comment]
> # Context
> You know when we need to store sensitive stuff like API keys, secret keys, and other hush-hush data in the database? Well, right now, it's up to us to make sure these data are encrypted before storing and decrypted when we need them. This back-and-forth can be a pain and sometimes it feels like a game of hide-and-seek where we're always "it".
> 
> # Proposal
> So, let's spice things up with a new field type called "secret". What's cool about "secret"?
> 
> **It Does the Heavy Lifting**: When you store data in the 'secret' field, PocketBase would automatically encrypt it. And when you need that data back, it'll decrypt it on-the-fly for you. No more manual encrypt-decrypt shenanigans.
> 
> **Safety First**: By handling the encryption right at the database level, we're reducing the chance of data leaks from potential app vulnerabilities or breaches. Think of it as a safe within a safe.
> 
> # Potential Approach
> We could use a tried-and-true encryption algorithm like AES-256 for the 'secret' field. The keys for encryption/decryption could be securely stored and managed using a Key Management Service (KMS) or we could bake them right into PocketBase.
> 
> # Benefits
> Adding this feature would mean:
> 
> * Leveling up the security of any app using PocketBase.
> * Saying goodbye to the hassle of dealing with client-side encryption and decryption.
> * Making life easier for devs who need to interact with sensitive data.
> 
> # What's Next?
> I'd love to hear your thoughts on this. Maybe there's already a simple way of doing this and this feature makes little sense shrug Got any insights


> # Context
> You know when we need to store sensitive stuff like API keys, secret keys, and other hush-hush data in the database? Well, right now, it's up to us to make sure these data are encrypted before storing and decrypted when we need them. This back-and-forth can be a pain and sometimes it feels like a game of hide-and-seek where we're always "it".
> 
> # Proposal
> So, let's spice things up with a new field type called "secret". What's cool about "secret"?
> 
> **It Does the Heavy Lifting**: When you store data in the 'secret' field, PocketBase would automatically encrypt it. And when you need that data back, it'll decrypt it on-the-fly for you. No more manual encrypt-decrypt shenanigans.
> 
> **Safety First**: By handling the encryption right at the database level, we're reducing the chance of data leaks from potential app vulnerabilities or breaches. Think of it as a safe within a safe.
> 
> # Potential Approach
> We could use a tried-and-true encryption algorithm like AES-256 for the 'secret' field. The keys for encryption/decryption could be securely stored and managed using a Key Management Service (KMS) or we could bake them right into PocketBase.
> 
> # Benefits
> Adding this feature would mean:
> 
> * Leveling up the security of any app using PocketBase.
> * Saying goodbye to the hassle of dealing with client-side encryption and decryption.
> * Making life easier for devs who need to interact with sensitive data.
> 
> # What's Njjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
> I'd love to hear your thoughts on this. Maybe there's already a simple way of doing this and this feature makes little sense shrug Got any insights on potential challenges, or suggestions for improvements and alternative approaches? Let's get this conversation started!



> Something like this was requested before (eg. [#1835 (comment)](https://github.com/pocketbase/pocketbase/discussions/1835#discussioncomment-4946404)), but for me the main issue with a `secret` field is that it is not clear how this field will be managed, who will have access to its value and whether the filter/sort operations will work at all.
> 
> Could you elaborate on your use case and how do you plan using it?

**Comment by lbensaad** [comment]
If the keys are stored in the database then the field is no more secret, because if some one manages to get the database, he will also get the keys in it, and easily decrypt the secret fields

**Comment by ganigeorgiev** [comment]
I'm closing this issues as it is lacking details and it is not clear to me how it could be implemented in a general way.

If users need encryption, they will have to attach to app event hooks and could use the built-in helpers [`security.Encrypt/Decrypt`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.17.1/tools/security) (the same helpers are also available if extended with JS under the [`$security` namespace](https://pocketbase.io/jsvm/modules/_security.html)).

**Comment by MahmoodKhalil57** [comment]
> I'm closing this issues as it is lacking details and it is not clear to me how it could be implemented in a general way.
> 
> If users need encryption, they will have to attach to app event hooks and could use the built-in helpers [`security.Encrypt/Decrypt`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.17.1/tools/security) (the same helpers are also available if extended with JS under the [`$security` namespace](https://pocketbase.io/jsvm/modules/_security.html)).

How do we decrypt and verify if we dont know the secret? is there a way to find the pocket base secret keys?
