### ISSUE TITLE
Feature Request: Add version number in the admin UI

### ISSUE THREAD

**Issue by aleda145** [pocketbase/pocketbase#280]
First, Thanks for an amazing project! 

Since the project is updating quite often with added features it would be great to easily see which version is currently running in the admin UI.  Maybe in something like an about page or some string at the bottom of the UI?

It was a little confusing to figure out which version I was actually running. I'm using it is a go package and extending the echo server with some custom API routes. I tried this: 
```shell
 ❯ go run main.go --version
[0.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
pocketbase version (untracked)
```
But the release on github prints the version correctly, so I suppose the version number is set when building the release? 

Of course I can just go check my go.mod file, which is what I did anyway!

Feel free to close the issue if you think it's not worth doing :smiley:

Thanks again for pocketbase! It was exactly what I needed, and I'm currently migrating my project's backend from a third party authentication service to pocketbase!

**Comment by ganigeorgiev** [comment]
Yes, the package version number is set only for the base prebuilt executables. This is done to allow user to override it when using PocketBase as framework and to set their own version.

Since the Admin UI is always embedded, I'll consider adding for the next release (v0.4 or v0.5) the version number somewhere in the footer.

**Comment by ganigeorgiev** [comment]
The build version number was added in [v0.4.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.4.0).
