### ISSUE TITLE
[bug] DELETE from client side JS results in 404 🐛🐛

### ISSUE THREAD

**Issue by tastycrayon** [pocketbase/pocketbase#2807]
### Problem
When I try to delete something from client-side, I get 404.
```ts
const handleDelete = async () => {
	try {
		const result = await pb.collection('rooms').delete(room.id, {});
		console.log({ result });
	} catch (err) {
		console.log({ err });
	}
};
```
You can see the `id` here.
![image](https://github.com/pocketbase/pocketbase/assets/37541747/77bde255-5496-43a0-972a-412c966bf254)
The error on console.
![image](https://github.com/pocketbase/pocketbase/assets/37541747/df446348-4aa4-4764-bd2a-9601d50961fe)
The error on network tab (id here)
![image](https://github.com/pocketbase/pocketbase/assets/37541747/55769b2b-e211-43dc-9595-eed638fb0b4b)
The logs on terminal (server)
![image](https://github.com/pocketbase/pocketbase/assets/37541747/d80f8f3b-cfdc-4f63-954a-0dd637216454)

I can delete the `rooms` from Pockebase admin panel fine, but not from API endpoint using JavaScript.

[full project link](https://github.com/tastycrayon/pb-svelte-chatapp/tree/main/server) where the error is.

**Comment by ganigeorgiev** [comment]
This is common error. Make sure that the client request satisfy the collection Delete API rule.

In case of an invalid API rule, we return 404 no matter of the current auth state.

**Comment by tastycrayon** [comment]
Is it possible to show the error (with `pocketbase serve --debug`) ?
