### ISSUE TITLE
Cant run the executable on Apple Silicon M2

### ISSUE THREAD

**Issue by uwussimo** [pocketbase/pocketbase#2819]
![Screenshot 2023-06-30 at 2 17 18 PM](https://github.com/pocketbase/pocketbase/assets/91214940/011aca26-d152-4a69-99f9-73a2f14268fe)

Terminal:
```bash
bash-3.2$ sudo ./pocketbase serve
Password:
Killed: 9
bash-3.2$
```

**Comment by danibjor** [comment]
You have to open Max Settings, Privacy, allow Pocketbase (should be your latest blocked app)

**Comment by uwussimo** [comment]
Because Apple Cannot Check For Malicious Software” Error

Open Finder
Traverse through to the “Applications” Folder
Highlight the software you are trying to Open
Press “control”
Right “Click” & Select “Open”


and then try again. 

It worked that way...
