### ISSUE TITLE
Subscription is triggering even after the delete function throws error.

### ISSUE THREAD

**Issue by sabikrahat** [pocketbase/pocketbase#2821]
Hello!

I have a collection named `vendors`. Whenever I delete a specific vendor it shows me an error. 

`
⛔ Vendor deletion: ClientException: {url: http://127.0.0.1:8090/api/collections/vendors/records/jc62n0vfhxe3kfq, isAbort: false, statusCode: 400, response: {code: 400, message: Failed to delete record. Make sure that the record is not part of a required relation reference., data: {}}, originalError: null}
`

I've no problem with this error. But as my delete function throws an error means.... the record isn't deleted. So why should my subscription of the vendor trigger an event?

`
💡 Stream {"action":"delete","record":{"id":"jc62n0vfhxe3kfq","created":"2023-06-14 13:36:31.682Z","updated":"2023-06-14 13:36:31.682Z","collectionId":"t3si1vfrp0ooi0f","collectionName":"vendors","expand":{},"address":"Lorem Ipsu ","creator":"hcgrqqn1zdsm3wf","description":"Lorem Ipsum","email":"a@vendor.com","name":"A Vendor","phone":"01234567890","updator":""}}
`

Here is the screenshot of my terminal

![image](https://github.com/pocketbase/pocketbase/assets/49031412/3f04e3f1-385e-4d02-88b0-b14b010b1591)

If anyone knows how to stop this unusual trigger or possible mistakes I've done. please let me know. Thank you.

**Comment by ganigeorgiev** [comment]
This is already fixed in the `develop` branch.

The reason for the above error is because in the current version we do "optimistic delete" and don't await the actual record delete operation to complete successfully to send the realtime message. In the `develop` branch there is a check that prepares the record delete event but sends it only if the `OnModelAfterDelete` get triggered.

**Comment by sabikrahat** [comment]
@ganigeorgiev I think this issue hasn't been solved in version 0.16.7. I have just updated it from 0.16.6 to 0.16.7. But still facing the issue. Can you please check it out?

Thank you.

**Comment by ganigeorgiev** [comment]
@sabikrahat Yes, the above mentioned changes are not part of v0.16.7 as they are currently only in the `develop` branch. The issue will  be resolved with the PocketBase v0.17.0 (_there are no fixed ETAs yet_).

**Comment by sabikrahat** [comment]
Oh okay... Thank you for your quick response.
