### ISSUE TITLE
API Preview generated code has quote issues

### ISSUE THREAD

**Issue by abeisgoat** [pocketbase/pocketbase#284]
The generated code snippet in the API Preview pane uses a single quote inside another single quote, thus making the code unusable. It should either be escaped or switched to double quotes.

Generated code:

```javascript
const resultList = await client.records.getList('collection', 1, 50, {
    filter: 'created >= '2022-01-01 00:00:00'',
});
```

Correct code

```javascript
const resultList = await client.records.getList('collection' 1, 50, {
    filter: 'created >= \'2022-01-01 00:00:00\'',
});
```

**Comment by ganigeorgiev** [comment]
Thanks for reporting it.

I've submitted a fix in the `export` branch. It will be available with the next release together with the changes related to the import/export of collections schema.
