### ISSUE TITLE
Feature Request: Records Cache

### ISSUE THREAD

**Issue by felix-schindler** [pocketbase/pocketbase#2850]
I have collections whose content changes very rarely. For these, it would be beneficial to be able to set a cache duration in the API rules.

**Comment by ganigeorgiev** [comment]
I'm not entirely sure that I understand what do you mean by "cache duration in the API rules", but at least for now there are no plans to add cache for the api requests as it will be difficult to generalize and may actually impact negatively the app performance if you keep a runtime cache per each user.

Developers can implement their own API cache mechanism externally either as [custom middleware](https://pocketbase.io/docs/router/#middlewares) or on a reverse-proxy level.

My general recommendation would be to not do caching, unless you have identified a specific slow request that hurt your application performance (_see also ["Many Small Queries Are Efficient In SQLite"](https://sqlite.org/np1queryprob.html)_).
