### ISSUE TITLE
Feature Request: CORS settings

### ISSUE THREAD

**Issue by felix-schindler** [pocketbase/pocketbase#2851]
It would be great if you could add CORS settings to the application settings to allow specific domains for API usage.

Alternatively, it would also work to add a `@request.url` object to the API rules, through which we could handle that case ourselves.

**Comment by ganigeorgiev** [comment]
This should be already supported when using the `--origins` flag:

```sh
./pocketbase serve --origins=domain1.com,domain2.com
```
_(all available flags can be explored with `--help`)_

Alternatively, you can also [register a custom middleware](https://pocketbase.io/docs/router/#middlewares) (_there will be more documentation with the next release_).

Note that CORS settings doesn't really prevent others for making requests to your API and shouldn't be relied on as a measure against external network access to your service.
