### ISSUE TITLE
Planetscale backend

### ISSUE THREAD

**Issue by ktown007** [pocketbase/pocketbase#2874]
SQLite is great. It would also be great to have the options to host db in Planetscale mysql.

**Comment by ganigeorgiev** [comment]
There are no plans for this at the moment. You can also check the discussion in https://github.com/pocketbase/pocketbase/discussions/14.

Eventual support for other SQL databases _may_ be added, mainly to support hosts with ephemeral storage, but for now this remains out of the roadmap.
