### ISSUE TITLE
feature request: add response time in the request log section

### ISSUE THREAD

**Issue by Jeyanthinath** [pocketbase/pocketbase#2875]
Currently the field doesn't have the response time section

![image](https://github.com/pocketbase/pocketbase/assets/2253649/9c0e786b-19d7-42da-9289-d1bde02bbfcf)

This will be helpful in identifying the bottlenecks in the system.

**Comment by ganigeorgiev** [comment]
`execTime` field was added to the refactored request logs data. The change will be available with the upcoming v0.20.0 release soon.
