### ISSUE TITLE
Feature Request: Add default timezone to display on timestamps

### ISSUE THREAD

**Issue by jaasonw** [pocketbase/pocketbase#2926]
Currently, the table views show timestamps in UTC, but I think it'd be nice if there could be a setting somewhere to change the displayed time zone

<img width="344" alt="image" src="https://github.com/pocketbase/pocketbase/assets/8981287/459f7c4d-ac26-4ed4-ac60-e8dc39b8d5d3">

**Comment by ganigeorgiev** [comment]
You can check https://github.com/pocketbase/pocketbase/discussions/1745.

This eventually may change in the future if introduce zone support in the filters, but for now is a low priority.
