### ISSUE TITLE
[FEAT] Emit 'Content-length' Header for get requests.

### ISSUE THREAD

**Issue by maxcodefaster** [pocketbase/pocketbase#2927]
It would be nice to have the 'Content-length' Header in the response Headers of get requests. Use cases would be when I query a lot of data and I want to show a progress indicator.

**Comment by ganigeorgiev** [comment]
I don't understand what do you mean. We already return the `Content-Length` header with the response. Here is an example from the live demo when accessing https://pocketbase.io/api/collections/posts/records:

![response_screenshot](https://i.imgur.com/fTCF5tQ.png).

If that's not what you mean, feel free to elaborate I'll investigate it further.
