### ISSUE TITLE
Feature Request: Add a custom path as an option for file field

### ISSUE THREAD

**Issue by freedjoe** [pocketbase/pocketbase#2945]
Please can you add a custom path for the file location as an optiona and in JSsdk?
like this
![Capture d'écran 2023-07-18 144555](https://github.com/pocketbase/pocketbase/assets/6552963/d40d071f-59e6-4876-b0b9-67398439f629)

**Comment by ganigeorgiev** [comment]
There are no plans for this as it will complicate the S3-local filesystem abstraction.

In general the end users shouldn't be concerned with the internal storage details so for me personally it doesn't make sense to provide an option in the SDKs or the web APIs.
