### ISSUE TITLE
Invalid Filters when doing multiple filters with JS SDK

### ISSUE THREAD

**Issue by indrazm** [pocketbase/pocketbase#2953]
Hey, I have an issue when i do multiple filter. 

Here is my code :

```js
async function getCurrentLesson(lessonSlug: string) {
  const data = await pocketbase.collection("enrolledLesson").getFullList({
    expand: "lesson,user",
    filter: `lesson.slug = "${lessonSlug}" & user = "tt4r03d33ggqfw9"`,
  });
  return data;
}
```

I know do filter using URL and i need to encode the URL, but here, i don't know where is the Problem

**Comment by ganigeorgiev** [comment]
The SDKs will take care for the encoding for you, but I think the above filter is incorrect because the "AND" operator should be `&&` (double ampersand).

If that's not the case, feel free to let me know and I'll investigate it further.
