### ISSUE TITLE
Feature request : Support for blob types

### ISSUE THREAD

**Issue by Zehir** [pocketbase/pocketbase#2961]
Hello, I have an use case in my app where I need to store a lot of configuration file that are binary but they are all tiny and would like to store them as blob instead of file.

Maybe an option in the file type to store them as blob instead of real file on the file system or on a s3 bucket ?

Thanks for your beautiful work on pocketbase

**Comment by ganigeorgiev** [comment]
Sorry, there are no plans for this (at least for v1). For me the cons maintaining it outweigh the limited use cases where having such option will be beneficial.

It will not only complicate the internals, but will cause also unnecessary confusion for the developers which storage to use and when. Additionally, we'll have to implement some special tool to allow migration from blob to file storage because I'm sure someone will end up with a use case where they've started with blob and later decided to increase the file size limit and now want to migrate to local/s3 filesystem.

**Comment by thetagML** [comment]
Hi!

First of all, Pocketbase is a great work with many features that can't be found elsewhere.

Well, I guess the binary format (for use only in code) would complement the pretty wide functionality of Pocketbase.
Sometimes, it is necessary. 
E.g. for encrypted data or relatively small binary files, e.g. images or similar.

Btw, encrypting the database or some fields may also be a good improvement. However, I'm sure it is not too easy to implement and has (severe) performance drawbacks. But when it is necessary, it should rather be used.

Another point would be this: a hook after login where somehow, another interface than the normal PB interface may be rendered. But also extending the PB interface of changing it may be a good feature, I guess several other users may agree. E. g. to add interface elements by code or remove (disable) interface elements.
This approach may simplify creating simple - more customized applications.
E.g. to access certain tables only for some users. A bit like, I would tell, Airtable where access to tables and records may be restricted on the basic interface that comes with PB.

If you like these ideas, I may open different tickets for these.

Laszlo

**Comment by thetagML** [comment]
P.S.: Anyway, I figured out that implementing blobs is not a too complex (impossible) job. Takes approx. a day to change the back-end and front-end (similar to files handling and e. g. to a textbox handling internally).
However, this means that I will need to patch all new PB updated version too.

**Comment by jockm** [comment]
I think this is shortsighted.  I need to store thumbnails in the database (and not the filesystem).  Its more efficient to store them in the database, nor is using blobs as obscure as you seem to think.

Its a field you can set and read, but not query on (except make `IS (NOT) NULL`, the decision can be made entirely off of the datatype of the field without adding anything else to the data structure.

Please reconsider
