### ISSUE TITLE
feature request: add Database field COMMENT 

### ISSUE THREAD

**Issue by zhenruyan** [pocketbase/pocketbase#2964]
```sql

  CREATE TABLE
    `usertables` (
      `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
      `user` int(11) unsigned NOT NULL COMMENT 'this is user id ',
      `age` int(11) unsigned NOT NULL COMMENT 'this is user age',
      PRIMARY KEY (`id`),
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8

```

It is hoped that the writing of database fields can be managed at the database level and in the back-end management interface commet

**Comment by ganigeorgiev** [comment]
At least for now there are no plans for adding support for field comments.

I may reconsider it in the future as it seems to be a common request (_see https://github.com/pocketbase/pocketbase/issues/2943, https://github.com/pocketbase/pocketbase/issues/1603 and probably others_).
