### ISSUE TITLE
Feature Request - ability to reorder by dragging 

### ISSUE THREAD

**Issue by manishionc** [pocketbase/pocketbase#2977]
It would be great if we can  reorder the collection item by dragging.

**Comment by ganigeorgiev** [comment]
Collection records don't have fixed order as it depends on the `sort` query parameter.

You can implement your own ordering mechanism (eg. with `order` field), but the Admin UI is not extendable at the moment.

**Comment by manishionc** [comment]
> Collection records don't have fixed order as it depends on the `sort` query parameter.
> 
> You can implement your own ordering mechanism (eg. with `order` field), but the Admin UI is not extendable at the moment.

Ok thanks
