### ISSUE TITLE
Admin UI flickering on orphan relations

### ISSUE THREAD

**Issue by Zehir** [pocketbase/pocketbase#3003]
This should not happen because the relation are deleted but when it does the UI get wild ( see #3000 )

But when you have a database with a broken relation the Admin UI is trying to open the record but can't find it.

When opening the record in edit mode the side panel is flickering and the app is sending a lot of requests to find the deleted record.

I got around 816 requests in less then 10 seconds. It's send requests until the side panel is open.
`GET http://127.0.0.1:8090/api/collections/q97y8xw37o2blnu/records?page=1&perPage=100&filter=id%3D%22353f983e-1616-47fe-a207-e8651d6836d5%22`
```json
{
  "page": 1,
  "perPage": 100,
  "totalItems": 0,
  "totalPages": 0,
  "items": []
}
```

The collection view with the not existing record ID (it's a view)
![image](https://github.com/pocketbase/pocketbase/assets/845225/ba1d19b2-a02d-4e13-85fd-a4e435c028cb)

The Chrome network debug windows
![image](https://github.com/pocketbase/pocketbase/assets/845225/a48ce7d9-63d5-4237-b097-b995ff785c7e)

**Comment by ganigeorgiev** [comment]
Yes, this is known issue (briefly mentioned in https://github.com/pocketbase/pocketbase/pull/2877#issuecomment-1627436662).

I have it in my todo and will be fixed with the change from #3000.
