### ISSUE TITLE
Cannot access FTP server

### ISSUE THREAD

**Issue by wayjack** [pocketbase/pocketbase#3005]
Hello, I recently created an account and am trying to log in to the FTP servers, but I keep getting a critical error... Happens when I run the provided FTP command in the Dashboard too: `ftp ftp://myemail@pockethost.io`

<img width="382" alt="Screenshot 2023-07-26 at 2 12 41 PM" src="https://github.com/pocketbase/pocketbase/assets/3822492/7fcaa9a9-8b46-4424-81aa-6dcdedbc6a2a">

**Comment by wayjack** [comment]
Nevermind, I can't read apparently. It worked when I provided my regular email without the % chars in FileZilla, but wouldn't work with the FTP url or command for some reason

**Comment by ganigeorgiev** [comment]
@wayjack _Please note that PocketHost is a separate project from PocketBase and you can find help for it in their repo - https://github.com/benallfree/pockethost._
