### ISSUE TITLE
Bug: API preview for delete record crashes the UI

### ISSUE THREAD

**Issue by aleda145** [pocketbase/pocketbase#301]
To reproduce:
1. https://pocketbase.io/demo/ (version  v0.4.1)
2. Click API preview for posts and then on Delete
3. UI crashes with the error below

`Uncaught (in promise) ReferenceError: CommonHelper is not defined` `[index.0d37b1b7.js:469:19](https://pocketbase.io/_/assets/index.0d37b1b7.js)` 

Seen in both firefox and chrome

**Comment by ganigeorgiev** [comment]
Thanks for reporting it!

This is a regression related to the change from `localhost` -> `127.0.0.1` replacement.

A fix was released in [v0.4.2](https://github.com/pocketbase/pocketbase/releases/tag/v0.4.2).
