### ISSUE TITLE
Reset password URL is incorrect resulting in 404

### ISSUE THREAD

**Issue by gapmiss** [pocketbase/pocketbase#302]
PocketBase v0.4.2

In the password reset email message, the URL is:

`http://localhost:8090/#/confirm-password-reset/eyJhbGciOiJ...OwP0pE`

and should be:

`http://localhost:8090/_/#/confirm-password-reset/eyJhbGciOiJ...OwP0pE`

Thanks

**Comment by ganigeorgiev** [comment]
Thanks for noticing it.

The admin reset password confirmation url and its unit test were updated in `master`.
The fix will be available with the next bugfix/feature release.
