### ISSUE TITLE
Not able to read body params in RecordAuthWithPasswordEvent

### ISSUE THREAD

**Issue by 0xTux** [pocketbase/pocketbase#3023]
PocketBase JS SDK's authWithPassword function allows you to send bodyParams and queryParams

```js
const authData = await pb
    .collection('users')
    .authWithPassword(
      'test',
      'test',
      { captchaFromBody: 'hello world' },
      { captchaFromQueryParam: 'hello world' },
    );
```
    
Here in the Go code, I'm trying to read those body params
    
 ```go
app.OnRecordBeforeAuthWithPasswordRequest().Add(func(e *core.RecordAuthWithPasswordEvent) error {
		
		// Get request body
		bodyParams := GetJSONRawBody(e.HttpContext)
		
		// Get request params
		queryParams := e.HttpContext.QueryParams()

		log.Printf("%v", bodyParams)
		log.Printf("%v", queryParams)

		return nil
	})
	
func GetJSONRawBody(c echo.Context) map[string]interface{} {
	jsonBody := make(map[string]interface{})
	err := json.NewDecoder(c.Request().Body).Decode(&jsonBody)
	if err != nil {
		return nil
	}
	return jsonBody
}

```

In the CLI, the queryParams are arriving as expected, while the request body is an empty map.
![image](https://github.com/pocketbase/pocketbase/assets/97862450/535a1041-f795-4411-b57c-ae4c51ce2685)

I assume this is because the body was read before the RecordAuthWithPasswordEvent was emitted, and the body parameters were not passed to the event.
https://github.com/pocketbase/pocketbase/blob/0c5305c1744f2041b135d963c684c0a3369c6a42/apis/record_auth.go#L268-L279

**Comment by ganigeorgiev** [comment]
You can't read the body once it is already read because it is a stream (the hooks are fired after loading and initializing the corresponding request action).

You can use the [`apis.RequestInfo()`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.17.0/apis#RequestInfo) to get a copy of the previously read request body.

I'll consider documenting it better sometime later next week.
