### ISSUE TITLE
Force file download

### ISSUE THREAD

**Issue by dedo1911** [pocketbase/pocketbase#3033]
Documentation says (https://pocketbase.io/docs/files-handling/):

> Additionally, to instruct the browser to always download the file instead of showing a preview when accessed directly, you can append the `?download `query parameter to the file url.

But looking at https://github.com/pocketbase/pocketbase/blob/master/apis/file.go the only QueryParam that are being used are `token` and `thumb`.

Was this a feature that has been removed or something that has never been implemented yet?

**Comment by ganigeorgiev** [comment]
The `download` query param is part of the serve handling - https://github.com/pocketbase/pocketbase/blob/b3f09ff045cfb915aea8a8334d0f4f17d236952d/tools/filesystem/filesystem.go#L326

**Comment by dedo1911** [comment]
@ganigeorgiev I didn't noticed that, thanks.
However it has to be specified it has to be true and not just being set. Took me a while to figure it out.
Docs could be improved here.

```
❯ curl -i "http://127.0.0.1:8090/api/files/i37o5ykupb5voix/ipqdssqswp3n8ns/example_TCfBbTqfhn.png"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=2592000, stale-while-revalidate=86400
Content-Disposition: inline; filename=example_TCfBbTqfhn.png
Content-Length: 42240
Content-Security-Policy: default-src 'none'; media-src 'self'; style-src 'unsafe-inline'; sandbox
Content-Type: image/png
Last-Modified: Mon, 31 Jul 2023 13:45:16 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```

```
curl -i "http://127.0.0.1:8090/api/files/i37o5ykupb5voix/ipqdssqswp3n8ns/example_TCfBbTqfhn.png?download"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=2592000, stale-while-revalidate=86400
Content-Disposition: inline; filename=example_TCfBbTqfhn.png
Content-Length: 42240
Content-Security-Policy: default-src 'none'; media-src 'self'; style-src 'unsafe-inline'; sandbox
Content-Type: image/png
Last-Modified: Mon, 31 Jul 2023 13:45:16 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```

```
❯ curl -i "http://127.0.0.1:8090/api/files/i37o5ykupb5voix/ipqdssqswp3n8ns/example_TCfBbTqfhn.png?download=true"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=2592000, stale-while-revalidate=86400
Content-Disposition: attachment; filename=example_TCfBbTqfhn.png
Content-Length: 42240
Content-Security-Policy: default-src 'none'; media-src 'self'; style-src 'unsafe-inline'; sandbox
Content-Type: image/png
Last-Modified: Mon, 31 Jul 2023 13:45:16 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```

**Comment by ganigeorgiev** [comment]
Yes, the parameter must have a "truthy" value.

I'll consider updating the documentation sometime later today.

**Comment by dedo1911** [comment]
@ganigeorgiev Just noticed it's also missing in the Web APIs Reference (https://pocketbase.io/docs/api-files/#download-fetch-file)

Thanks for the quick response and update!
