### ISSUE TITLE
Pocketbase CGO Update

### ISSUE THREAD

**Issue by dedo1911** [pocketbase/pocketbase#3053]
Running command `pocketbase update` using **linux_amd64_cgo** version, itdownloads the non-cgo flavour **linux_amd64**

<img width="1119" alt="image" src="https://github.com/pocketbase/pocketbase/assets/1364496/dde09a25-0fb0-4bc5-995a-e911dbbdd5cf">

**Comment by ganigeorgiev** [comment]
The cgo package in the releases is not recommended for general use as it is not portable (it is available only for linux and even then it may not work on all linux OSes).

The CGO build is there mainly to ensure that the tests pass successfully with the cgo driver as there are some minor differences between the pure Go SQLite and CGO one.

I'll consider documenting it better eventually in the future (or maybe configure the github release action to not output artifacts for the cgo build).
