### ISSUE TITLE
Feature Request: Related fields for "Display fields" for relations

### ISSUE THREAD

**Issue by sma** [pocketbase/pocketbase#3069]
I've a n:m relation between some model A and B to which itself has properties, so I introduced another model C and A has a multi-relation to C and C has a single-relation to B. Now, when looking at records of A, those C records have no useful "print string" for the Display fields setting of the relation field. Instead of just displaying `id` or any of its own fields, I'd love to display something like `b_id.name`.

**Comment by ganigeorgiev** [comment]
This was suggested before but as it is implemented I don't think it will be a good idea to add support for nested display fields as it would complicate too much the internals.

There are plans to [move the "Display fields" option](https://github.com/orgs/pocketbase/projects/2/views/1?pane=issue&itemId=26965654) from each relation field to their parent collection to avoid the duplication and once it is done it should cover the nested relation case.
