### ISSUE TITLE
POST request fails with 400 Failed to load the submitted data due to invalid formatting

### ISSUE THREAD

**Issue by Baltazore** [pocketbase/pocketbase#3078]
I am currently working on integration between PocketBase and EmberData.

By default EmberData (and many other data libraries) send on POST request `Content-Type: application/vnd.api+json` which fails at this moment (v 0.17.2) with wrong error. 

```
{
    "code": 400,
    "message": "Failed to load the submitted data due to invalid formatting.",
    "data": {}
}
```

As I can see in code [here](https://github.com/pocketbase/pocketbase/blob/master/forms/record_upsert.go#L130) it should result with more informative error. 

Unfortunately I cannot help fix this issue, but I thought it would be good to point it out. 

Thanks for your time.

**Comment by ganigeorgiev** [comment]
This is expected as we support only `application/json` and `multipart/form-data` requests.

You can get more detailed errors if you start the executable with `--debug` or check the request logs in the _Admin UI > Logs_.

**Comment by Baltazore** [comment]
Thanks for fast reply, missed info about `--debug` option, will definitely use it more. 

👍
