### ISSUE TITLE
View collection relation, error shows wrong message.

### ISSUE THREAD

**Issue by maxNodeJs** [pocketbase/pocketbase#3090]
I am sorry to see you have Disallowed relations to views from non-view collections. I have so many view collections setup throughout the database ( using views to show data related to relation fields filtered according to user types, companies rights such as organisation and many more in the query and the API rules for those views ) this way using the "recordpicker" shows only relevant data based on the query and API rules set for each view collection. Hard to explain all the logic here, but it made it easy to use view collections. Now as work around I will need to filter the data accordingly in the "recordpicker" for each collection and associated relation fields. Setting API rules on the base collections for this would make it very complicated.

The real issue is the error message given when trying to use view relation is incorrect, it says now allowed where it should be not allowed :-) Please see attached screenshot.
![Screenshot_20230808_101204](https://github.com/pocketbase/pocketbase/assets/55034782/c96c720d-88f8-4d7e-b9be-385dfed60817)

**Comment by ganigeorgiev** [comment]
Thanks, I've submitted a fix in `master`.

The reasons why the relations to view were disabled could be found in https://github.com/pocketbase/pocketbase/issues/3000#issuecomment-1651902352.
