### ISSUE TITLE
Feature Request: Allow triggering custom cron jobs

### ISSUE THREAD

**Issue by GD-coding** [pocketbase/pocketbase#3095]
Hello, amazing work on the app!

This feature request is for triggering custom cron jobs via the ui. You could create the cron jobs via pb_hooks or as extensions with go.

Thank you!

**Comment by ganigeorgiev** [comment]
For now this remains out of the roadmap as it'll be difficult to generalize, especially when using Go since you can have multiple cron timer instantiated each with different configuration or even use a completely different cron package.
