### ISSUE TITLE
Minor Bug: Cascade delete tool tip displaying active collection when creating new collection

### ISSUE THREAD

**Issue by Green-Ranger11** [pocketbase/pocketbase#3098]
When adding a relation in a ***new*** collection the tooltip always displays the selected collection in the background instead of just saying field.

For example, if you log in the active collection is automatically set to users. When you create a new collection and add a relation, the cascade delete tooltip will say something like:

> Whether on field record deletion to delete also the ***user*** (or the selected active collection in the background) associated records.

When it should be:

>Whether on field record deletion to delete also the ***field*** associated records.

I can't screenshot the tooltip unfortunately but I believe the issue is in https://github.com/pocketbase/pocketbase/blob/7d6b12a4ef5323c678fabb0b57334ef1934a285a/ui/src/components/collections/schema/SchemaFieldRelation.svelte#L209
because `$activeCollection` ***always*** has a value .

I was thinking of maybe passing a prop but I don't want to ruin this clean foreach loop by having one of the schemas have one prop separate from the others (maybe that's just me)
https://github.com/pocketbase/pocketbase/blob/7d6b12a4ef5323c678fabb0b57334ef1934a285a/ui/src/components/collections/CollectionFieldsTab.svelte#L133-L139
Maybe another way would be clear `$activeCollection` on creating a new collection?

Maybe there's a better way since I'm not too familiar with the UI codebase but I reckon it would be fine to just remove the `||` and just have it say `"field"`

**Comment by ganigeorgiev** [comment]
Yes, the use of `$activeCollection` is not correct here.

I'll consider removing it and generalize the message in order to to keep the current schema fields components separate from their collection model.

**Comment by ganigeorgiev** [comment]
I've updated the message (+ added some additional info for multiple relation fields) in `master`.

_In general the `relation` field options panel will slightly change in the next release as I'm planning of moving the "Display fields" to be as collection option instead to reduce the duplication when different relations to the same collection are created._
