### ISSUE TITLE
Bug: Cannot create admin via CLI before serve

### ISSUE THREAD

**Issue by djt** [pocketbase/pocketbase#3105]
Upon trying to create an admin after installation via the CLI, the following error is given.

`Failed to create new admin account: SQL logic error: no such table: _admins (1)`

I imagine this is because the table data structure has not yet been created, but it would be great to be able to effectively 'setup' the database prior to serving it. 

(In this context I am attempting to do it during a docker build)

**Comment by ganigeorgiev** [comment]
This is expected, although I agree that it is not documented very well. Custom console commands that automatically apply the migrations, only the `serve` does this.

You can run manually `./pocketbase migrate up` OR create the admin inside migration:
- Go - https://pocketbase.io/docs/go-migrations/#creating-new-admin
- JS - https://pocketbase.io/docs/js-migrations/#creating-new-admin

**Comment by djt** [comment]
Thank you very much, love the work you're doing.
