### ISSUE TITLE
Bug: Server must be restarted before CLI created admin is recognised

### ISSUE THREAD

**Issue by djt** [pocketbase/pocketbase#3106]
If serve is ran prior to an admin being created, and an admin is created via the CLI the webUI still expects an initial admin user to be created.  There is no way to log in with the CLI created admin until the server has been restarted.

**Comment by ganigeorgiev** [comment]
I've submitted a fix in `master` and it will be available with the next minor v0.17.4 release sometime later this week.

**Comment by djt** [comment]
Wonderful, thank you.
