### ISSUE TITLE
Computed/RawSQL field type

### ISSUE THREAD

**Issue by ganigeorgiev** [pocketbase/pocketbase#311]
This was discussed in https://github.com/pocketbase/pocketbase/discussions/289#discussioncomment-3370365 and https://github.com/pocketbase/pocketbase/discussions/265.

To allow simple computed response values and/or aggregations, we could define a new custom read-only field type that will accept a raw sqlite expression as a field option (`SUM()`, `COUNT()`, subquery or anything else that can be used as a `SELECT` column).

_Furthermore, the computed fields could be combined with the ["singleton style" type collections feature](https://github.com/pocketbase/pocketbase/issues/159), so that users will be able to create a simple reporting pages and apis._

**Comment by tonyhart7** [comment]
can its change other table field ?? like for example I want to reduce amount in product.qty if someone ordering that item ?

**Comment by ganigeorgiev** [comment]
@tonyhart7 No, this field type is intented only as read-only as part of the `SELECT` statement. You can use it for example to create an aggregation field, for example to automically calculate your product qty based on some sql query.

"Collection triggers" are intented to perform basic webhook-like changes (see #317).

**Comment by tonyhart7** [comment]
> @tonyhart7 No, this field type is intented only as read-only as part of a `SELECT` statement. You will be able to use it to create an aggregation field, for example to dynamically calculate your product qty based on some sql query.
> 
> "Collection triggers" are intented to perform basic webhook-like operations (see #317).

so I was whandering in sup**ase and they have the same feature like webhook that you mention 
while UI is pretty intuitive I think you can just make a like rule based using sql or same funtion like the one you use in rule base
so you dnt need make a new custom field and let the developer custom it for you

**Comment by ganigeorgiev** [comment]
@tonyhart7 I'm not sure that I understand your proposal.

This feature is expected to allow developers to enter a plain SQL string (eg. sqlite concat `firstName || ' ' || lastName`) in a read-only field type. The field value will be dynamic and computed everytime when you call for example `client.records.getOne()`.

The other feature, collection triggers #317, is for **post processing based on some event**. This is already supported by PocketBase if you use it as framework with the [event hooks](https://pocketbase.io/docs/event-hooks/), but #317 will try to simplify things a little by providing a UI for common post processing tasks.

**Comment by tonyhart7** [comment]
> @tonyhart7 I'm not sure that I understand your proposal.
> 
> This feature is expected to allow developers to enter a plain SQL string (eg. sqlite concat `firstName || ' ' || lastName`) in a read-only field type. The field value will be dynamic and computed everytime when you call for example `client.records.getOne()`.
> 
> The other feature, collection triggers #317, is for **post processing based on some event**. This is already supported by PocketBase if you use it as framework with the [event hooks](https://pocketbase.io/docs/event-hooks/), but #317 will try to simplify things a little by providing a UI for common hook actions, like making HTTP request(s) or sending a custom email.

Yeah that will do, what I mean is we can get some interactivity like Rule using same technology no ??
and I notice that postgress have plpgsql so complex query can can be split into smaller and yet effective set similiar to sql,
so I wonder where sqlite have same feature

**Comment by Frioo** [comment]
Definitely a great feature to have! Awaiting updates.

**Comment by oysteinsigholt** [comment]
@ganigeorgiev I have been playing with this use case, and have made a quick computed-on-read implementation backed by [sqlite generated columns](https://www.sqlite.org/gencol.html), over on [this branch](https://github.com/oysteinsigholt/pocketbase/tree/computed-text-sqlite-generated). 

The other alternative I'm exploring is computing the value on write using something like [govaluate](https://github.com/Knetic/govaluate) and writing the result to the database. My use case would benefit from having a materialized value for read performance, and a parsed expression to know which values depend on which. **Are you firm on the value being computed on read, and the expression being a sql expression?**

Computed-on-read demo:
![full_name](https://user-images.githubusercontent.com/6284064/201535943-e3749c59-4338-4706-9a20-d0c6f20388c6.gif)

**Comment by ganigeorgiev** [comment]
@oysteinsigholt

> Are you firm on the value being computed on read, and the expression being a sql expression?

Yes, at least that was the initial idea.

Couple weeks ago @iskaa02 created a PR for adding support for Views in https://github.com/pocketbase/pocketbase/pull/759 and I liked the idea but it needs to be implemented differently. I have it in my todo to research it in more details and eventually we may scrape this issue in favor of a new "View" collection type.

But for now this remain after the planned migrations flow improvements and filters enhancements.

**Comment by gevera** [comment]
Not sure if this is related or should I open an issue/proposal, would be great for generated columns based on preexisting ones For reference https://antonz.org/generated-columns

**Comment by tonyhart7** [comment]
> Not sure if this is related or should I open an issue/proposal, would be great for generated columns based on preexisting ones For reference https://antonz.org/generated-columns

or just use JSON data type

**Comment by ganigeorgiev** [comment]
Experimental "View" collection type was added in the `develop` branch and will be available soon with the next v0.13.0 release.

The "View" collection type extends the scope of this task, allowing users to define any custom `SELECT` query and convert that to a read-only collection.

If anyone wants to test it, feel free to checkout the [`develop` branch](https://github.com/pocketbase/pocketbase/tree/develop).

You can also read some notes on the implementaiton in https://github.com/pocketbase/pocketbase/pull/759#issuecomment-1435731789.

**Comment by lukepighetti** [comment]
would like to express my support for a computed column. while views are useful and do handle the use case of computed columns they locate the data away from the table we choose to enrich. this comes at the cost of two calls needed to the backend but the greater cost is for when using the CMS to interact with your data and the computed values are not directly available for viewing.

**Comment by ganigeorgiev** [comment]
@lukepighetti Sorry, I have no plans for now to revive this.

It is also not clear what exactly do you mean by _"read-only columns that contain data derived from"_ as this would depend on many factors including on the underlying json structure and cannot be easily generalized.

If you know upfront the data that is being inserted, I recommend to map it to dedicated collection fields, not `json`, as it usually tends to perform better and allows proper validations and more advanced filtering.
