### ISSUE TITLE
Pin Collections

### ISSUE THREAD

**Issue by brahmkshatriya** [pocketbase/pocketbase#3112]
A simple advancement, 
to pin specific collections before all of them are listed

![image](https://github.com/pocketbase/pocketbase/assets/69040506/a354d776-54a4-4807-9270-bfa8b0eb54da)

something like what google cloud has

**Comment by Greenheart** [comment]
While not a deal breaker for me, I like this feature.

Two ideas for how to implement this:

1. Should this be local for the current user? If so, this could be saved in localStorage

2. Or should this be for all users of the Pocketbase Admin UI? If so, this would need to be saved to the pocketbase collections config. Ideally this config should be possible to export/import together with other collections config. Perhaps this would be stored as `pinned: boolean` and showing the pinned collections on top - or they could all be ordered with an index (although that might be more complicated to implement).

**Comment by calumk** [comment]
In addition to this - is there. a specific reason they are not in alphabetical order, but in created-date order?

![image](https://github.com/pocketbase/pocketbase/assets/1183991/dfa624f3-db48-4dcc-9b88-e3c4e522aa19)

**Comment by ganigeorgiev** [comment]
_@calumk The collections are sorted in the sidebar first by their type (auth, base, view) and second by their name._

**Comment by thommorais** [comment]
I think it should be per user but persistent across devices.

**Comment by ganigeorgiev** [comment]
Basic sidebar control to "pin" collections was added in the `develop` branch as was requested several times already.

To avoid complicating the internals, for now the pinned state is stored just in localStorage.
