### ISSUE TITLE
Unable to edit collections and incorrect error message

### ISSUE THREAD

**Issue by felix-schindler** [pocketbase/pocketbase#3116]
I'm working with a view collection named "commission_distribution", which functions as expected. The column idEmployee within this collection also operates without any issues. Additionally, I have full capabilities to save and modify all view collections.

However, I'm encountering an error when attempting to modify the base and auth collections. Here's the error I received while editing the users collection:

![image](https://github.com/pocketbase/pocketbase/assets/65357346/255ba70a-7c9e-49dd-8b66-c57447bfba55)

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand the issue, nor how to reproduce it.

Please elaborate and provide details about:

- your PocketBase version
- your collections structure (_you can export it as JSON from Admin UI > Settings > Export collections_)
- reproducible steps

**Comment by ganigeorgiev** [comment]
If I understand correctly, you have a dependent view collection.

If that's the case, then the error is expected (_note that this is an raw SQL error_), aka. you have to delete first the column from the view.

I've added it in my todo to consider improving the collections errors reporting, but that will be handled for v0.18.0.

If that's not the case, please provide the above details and I'll investigate it further.

**Comment by felix-schindler** [comment]
I have to apologize, this wasn't an issue in PocketBase. The problem somehow was in the JOIN of the view query. I was just confused because the view worked fine (without any errors).

Instead of

```sql
FROM
  contracts c
  INNER JOIN (
    contractCommissionDistribution d
    INNER JOIN employees e ON d.employee = e.id
  ) ON c.id = d.contract
```

I'm now using

```sql
FROM
  contracts c
  INNER JOIN contractCommissionDistribution d ON c.id = d.contract
  INNER JOIN employees e ON d.employee = e.id
```
