### ISSUE TITLE
Cannot start a basic pocketbase project as a framework

### ISSUE THREAD

**Issue by Himujjal** [pocketbase/pocketbase#313]
Unable to run a basic project using pocketbase as a framework as directed in https://pocketbase.io/docs/use-as-framework. The following error pops up:

```sh
../../../my_code/go/pkg/mod/github.com/pocketbase/pocketbase@v0.4.2/ui/embed.go:10:12: pattern all:dist: no matching files found
```

### How to recreate the issue:

```sh
mkdir proj
cd proj
go mod init github.com/Himujjal/proj
touch main.go

# Add the content of `main.go` to be the example from https://pocketbase.io/docs/use-as-framework/

go mod tidy
go build main.go
```

The following error occurs:
```
../../../my_code/go/pkg/mod/github.com/pocketbase/pocketbase@v0.4.2/ui/embed.go:10:12: pattern all:dist: no matching files found
```

### My configs:

```
> go version
go version go1.17.7 darwin/amd64
```

**Comment by ganigeorgiev** [comment]
PocketBase requires go1.18+ to use as framework. Please update your go installation and try again.

**Comment by ganigeorgiev** [comment]
@Himujjal I'll close the issue since this was previously discussed here - https://github.com/pocketbase/pocketbase/discussions/46#discussioncomment-3139062 and most likely is the same, but if upgrading your go installation doesn't solve it, please let me know and I will investigate it further.
