### ISSUE TITLE
Endpoint seems wrong when updating ACL

### ISSUE THREAD

**Issue by symisz** [pocketbase/pocketbase#3130]
i get an error: The requested resource wasn't found.

404 (Not Found), showing the following endpoint in the console:
http://localhost:8080/api/collections/posts/records/posts 
```js
    async accessReader() {
      // Update collection ACL
      const collectionId = 'posts';
      const newAcl = {
        'reader': {
          'read': true
        }
      };
      try {
        const updatedCollection = await this.pb.collection('posts').update(collectionId, { acl: newAcl });
        console.log('Collection ACL updated:', updatedCollection);
      } catch (error) {
        console.error(error.message);
      }
    },
```

what i would expected the endpoint to be instead
http://localhost:8080/api/collections/posts/

**Comment by ganigeorgiev** [comment]
The above code sample doesn't seem correct.

1. `collectionId` is not an id.

2. `collection('posts').update(id, data)` is for updating a single collection record, not the collection itself.

3. You can get 404 response from the update call in case the client request doesn't satisfy the collection Update API rule (this is a side effect of the fact that  API rules are also filters; see the note in https://pocketbase.io/docs/api-rules-and-filters/#api-rules).

If the above doesn't help, please elaborate and provide more details about your use case and data structure in a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a).

**Comment by ganigeorgiev** [comment]
_Side-note: if you are looking for updating a collection configuration programatically, you can check https://pocketbase.io/docs/api-collections/._
