### ISSUE TITLE
Feature Request: Support for non-standard cron expressions (@-expressions)

### ISSUE THREAD

**Issue by seriousm4x** [pocketbase/pocketbase#3132]
I'd be nice to have support for cron expressions starting with @. For example:

- `@reboot` – run once at the startup
- `@yearly` or `@annualy` – run once a year
- `@monthly` – run once a month
- `@weekly` – run once a week
- `@daily` or `@midnight` – run once a day
- `@hourly` – run hourly

Im currently using [robfig/cron](https://github.com/robfig/cron) (which has support for this) but I want to migrate my project to pocketbase's built in cron.

**Comment by ganigeorgiev** [comment]
I'll consider defining the tokens as aliases to their corresponding cron expression, with exception of `@reboot` because for me personally is ambiguous and it is not clear when will execute as the cron package has no relation to the application startup process.

**Comment by seriousm4x** [comment]
> with exception of `@reboot`

Agree, doesn't make much sense in this context

**Comment by seriousm4x** [comment]
I forgot @every. This could be a little harder as I takes a string argument which needs to be parsed.
For example "@every 2m" or "every 1h".

**Comment by ganigeorgiev** [comment]
No, sorry `@every` is not planned as it will require a completely different parser and will complicate unnecessary the implementation.

**Comment by ganigeorgiev** [comment]
_I've added the macros in the `develop` branch and it will be available with the next v0.18.0 release (_there are no ETAs yet_)._

Note that there is nothing wrong of using a different cron package if you need something non-spec and more advanced.

_The current PocketBase `cron` util is very rudimentary ([it is under ~400 lines](https://github.com/pocketbase/pocketbase/tree/master/tools/cron)) and it was created primarily for the automated backups._
