### ISSUE TITLE
Feature request: Support name alias for expands

### ISSUE THREAD

**Issue by lbensaad** [pocketbase/pocketbase#3139]
Make it possible to rename expands. Similar to SQL aliases for renaming columns and tables in queries  using keyword `as`. For example: {expand: "user as author"} or {expand: "comments(post) as comments"}.

**Comment by ganigeorgiev** [comment]
This was requested before (https://github.com/pocketbase/pocketbase/issues/1396) but at least for now I'm reluctant adding support for it as it could results in collisions and will require extra validation which may not always be obvious as the expand can be invoked in different places both via user request and programmatically.

For now this remains out of the scope but in case there is too much users demand for it I may reconsider it in the future.
