### ISSUE TITLE
No Internet shows PocketBase as empty

### ISSUE THREAD

**Issue by adamshand** [pocketbase/pocketbase#3147]
Not sure if this counts as a bug, but it certainly surprised me.  I opened my laptop this morning and momentarily panicked when I saw this.  :-)

![image](https://github.com/pocketbase/pocketbase/assets/130651/8616dbba-8249-4c0b-9f21-61c506b0c7ed)

Then I realised my wifi was off, turned it back on and everything was okay. 

Would be nice if the UI differentiated between an empty PocketBase and an inability to reach the API. :-)

**Comment by ganigeorgiev** [comment]
I've pushed a small fix in the `develop` branch that will allow showing listing APIs connectivity errors as toast error notification.
