### ISSUE TITLE
Possible bug... or incorrect docs code.

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3150]
related to (https://github.com/pocketbase/pocketbase/issues/3149)
I tried making test file [test.pb.js.txt](https://github.com/pocketbase/pocketbase/files/12368867/test.pb.js.txt)

after checking console I see
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/b597c8bb-f9d9-4212-b0fb-c3aa9863e04f)
so i fought it might be bug... as I assume that it should printout a string... and not [object Object]
at least for httpContext

![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/5f364e73-c138-4109-b5f8-6a2c278d4ef0)

**Comment by ganigeorgiev** [comment]
The `console.log` in the examples are there just to show what fields are available, but that doesn't necessary mean that those fields have a public safe string representation.

For more details about the fields and their supported methods you can either "JSON.stringify" them or check the JSVM types reference - https://pocketbase.io/jsvm/index.html.

**Comment by ganigeorgiev** [comment]
_Side-note: you can also enable code intellisense and autocompletion if you reference the `types.d.ts` declarations - https://pocketbase.io/docs/js-overview/#typescript-declarations-and-code-completion_

**Comment by ganigeorgiev** [comment]
_Side-note2: For examples how to use `httpContext` you can also check https://pocketbase.io/docs/js-routing/ (`c` in the examples in the same as `e.httpContext`)_

**Comment by pietru2004** [comment]
ok, thank you
