### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3153]
I get
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/eb586707-4083-4f9a-97dc-ca4fe14c1ee0)
on running 
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/14249ac1-a995-4ef4-bd25-ef3e489daff2)
the part where record does not exist in catch does work, but the error shown in meta occurs for the `findFirstRecordByFilter`
also I have unique index
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/92d2e10f-4bff-46c9-8e7f-1e4db1c0533d)
item+owner, so each owner can have one record for each item they own...

of course I realize it might be my fault...
also I was getting error when `findFirstRecordByFilter` did not find any record... causing custom code to be stopped

**Comment by ganigeorgiev** [comment]
It is not a bug, or at least I can't see why it would be a bug.

The error indicates that it is from a db persist call, not from `findFirstRecordByFilter`, aka. where you call `saveRecord()`.

If that doesn't help, please provide more detailed code sample in a new [QA discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a).

**Comment by pietru2004** [comment]
ok
