### ISSUE TITLE
Feature Request: Additional data for CRUD response

### ISSUE THREAD

**Issue by curefatih** [pocketbase/pocketbase#3157]
Hi folks,
First things first - Thank you for this work.

I would like to ask about how we can send an additional payload along with the record request. I think there is no way we can add custom fields to responses. AFAIS Most of the CRUD routes are ending with `return e.HttpContext.JSON(http.StatusOK, e.Record)` 

I think it can be achievable by using `echo.Context.Set()` and `echo.Context.Get()` methods to move additional data over hooks and send the response in a field like `_extra`, and returning with the Record (by wrapping or adding a field to Record). I believe it can be useful for the fields that are calculated request-wise. WDYT?

Thanks!

**Comment by ganigeorgiev** [comment]
I think this already supported, although it is not documented very well at the moment.

If you want to send additional data with the [Record](https://pkg.go.dev/github.com/pocketbase/pocketbase/models#Record) model you can do something like:
```go
record.Set("something", 123)
record.WithUnknownData(true) // enable "something" to appear in the public serialization
```

**Comment by curefatih** [comment]
That was quick :) Thank you for that  @ganigeorgiev
