### ISSUE TITLE
Feature Request: Update the PocketBase version from the GUI

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#3160]
Feature Request: Update the PocketBase version from the GUI

The idea behind that, is to stay up to date by pressing update inside the Admin panel, from 0.15.7 to 0.15.8 for example. It displays you the "What's new on that version" and if a compatibility or a future broken staff, a warning to "auto fix" by the PocketBase instance, or "Perform changes manually" with a guide from github PocketBase docs and instructions on GUI

#3159

**Comment by ganigeorgiev** [comment]
Please don't open the same issue and discussion.

I have it in my todo but for now this is left aside as there is no easy way to handle autoupdates when PocketBase is used as Go framework.

**Comment by miguelgargallo** [comment]
> Please don't open the same issue and discussion.
> 
> I have it in my todo but for now this is left aside as there is no easy way to handle autoupdates when PocketBase is used as Go framework.

Understood, thanks
