### ISSUE TITLE
(Windows) Invalid module when using require in JS hooks 

### ISSUE THREAD

**Issue by jf908** [pocketbase/pocketbase#3163]
I have copied the exact usage from the documentation: https://pocketbase.io/docs/js-overview/#loading-modules
With a main.pb.js and utils.js in pb_hooks but I get an error message when I start up pocketbase:

```
2023/08/19 15:27:03 GoError: Invalid module at github.com/dop251/goja_nodejs/require.(*RequireModule).require-fm (native)
```

Platform:
Windows 11 ARM64

**Comment by ganigeorgiev** [comment]
I've just tested the example locally and I'm not able to reproduce it. Make sure that the correct path to the module is used.

Also note that the caveat about relative paths - https://pocketbase.io/docs/js-overview/#relative-paths.

Alternatively, you can also try specifying an absolute path to the file.

If the above doesn't help, please a provide a minimal reproducible repo and I'll try to investigate it (_it is possible to be platform specific as I'm testing on Linux, I'm not sure_).

**Comment by jf908** [comment]
Here is a minimal reproducible repo

https://github.com/jf908/pb_repro

**Comment by ganigeorgiev** [comment]
I have the same setup locally but I'm not able to reproduce it.

I don't have a Windows VM at the moment to test, but I also can't think of a reason why it won't work on Windows.

Are you sure that this is the code that you have locally?

Do you have parent level `node_modules` that eventually could conflict with the module?

Did you try specifying an absolute path?

**Comment by ganigeorgiev** [comment]
The only thing I guess that could be platform specific is the path to the file.

I'll try to setup a Windows VM sometime later today and will test it.

**Comment by jf908** [comment]
This is definitely the repo I'm testing with. No parent level node_modules. I get the same error no matter if path is relative or absolute and no matter which path separator I use.

Tested on macOS and it works.

Tested on a different Windows machine and it does not work, so pretty sure this is a Windows-only issue.

**Comment by ganigeorgiev** [comment]
I was able to reproduce it on a Windows 10 VM but I'm still not sure what is causing it.

It works with relative path, but as mentioned in https://pocketbase.io/docs/js-overview/#relative-paths, it is relative to the current working directory:

```js
onAfterBootstrap((e) => {
    const utils = require("./pb_hooks/utils.js")

    utils.hello("world")
})
```

For some reason when the path is absolute (__hooks is the absolute path to the `pb_hooks` dir_) it doesn't work, aka. the following fails to open:

```
C:\Users\IEUser\pb_hooks\utils.js
```

I'll try to investigate it further as I'm not sure if the issue is in the upstream [goja_nodejs repo](https://github.com/dop251/goja_nodejs) or it is something specific to Windows that we'll have to take care.

**Comment by ganigeorgiev** [comment]
_I've opened a PR in the upstream repo https://github.com/dop251/goja_nodejs/pull/61._

**Comment by jf908** [comment]
Excellent, thank you so much!
