### ISSUE TITLE
Default error on custom routes could be InternalServerError insted of BadRequest

### ISSUE THREAD

**Issue by npinochet** [pocketbase/pocketbase#3165]
Hello, thank you for maintaining this great project. I just wanted to raise a small complain regarding error handling on custom routes.
Consider the following route:
```Go
app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
    e.Router.GET("/hello/:name", func(c echo.Context) error {
        name := c.PathParam("name")
        if name == "" {
                return echo.NewHTTPError(http.StatusBadRequest, "missing param name")
       }
        if err := FetchUserByName(name); err != nil {
                return err
        }
        if err := LogUserActivity(name); err != nil {
                return err
        }
        if err := SayHelloToWorld(name); err != nil {
                return err
        }
        return c.String(http.StatusOK, "OK")
    })

    return nil
})
```
Each of those `return err` will end up as bad requests (400) for the client by default, which seems a bit off since it's not really a bad request, but an internal server error. This could be solved by specifying `echo.NewHTTPError(http.StatusInternalServerError, err)` instead of just `err`, but it feels like an extra unnecessary step that hurts the programming experience, considering that Echo does handles pure `err`s as internal server errors.

If this is intended behavior then I apologize and feel free to close this issue. Thank you for your time.

**Comment by ganigeorgiev** [comment]
It is intended behavior. All plain Go errors, with the exception of `sql.ErrNoRows`, are normalized as "400 Bad request" as generic request error.

If are free to "extend" the default `e.Router.HTTPErrorHandler` if you want to change the behavior.
