### ISSUE TITLE
How to use a subdomain without having to enter the "/_" after to get to the admin page?

### ISSUE THREAD

**Issue by oscadev** [pocketbase/pocketbase#3168]
I am using NGINX. I currently have pocketbase working with a subdomain admin.website.com, but I need to do admin.website.com/_ in order to reach the admin page. How do I make the admin portal work without the "/_" at the end?

Here is my server:

```
server {
    listen 80;
    server_name admin.website.com;
    client_max_body_size 50M;

    location / {
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        proxy_read_timeout 360s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://127.0.0.1:3000;
    }
}
```
Thanks!

**Comment by ganigeorgiev** [comment]
I don't think this is PocketBase related.

You can either try to change the address in the `proxy_pass` directive or use a [rewrite](https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite) rule.
