### ISSUE TITLE
Feature Request: Mobile friendly "Collections" web page

### ISSUE THREAD

**Issue by bbkane** [pocketbase/pocketbase#3169]
Hello! I'd like to make a few small pocketbase "apps" - a simple contact book, a meal logger, etc. To do this, I need to be able to view and enter info into the app from my phone. I really like the built-in collections UI for desktop, but to my dismay it doesn't appear to be mobile friendly.

Is there any interest in making the collections page mobile friendly? To be frank, though I'm slowly trying to learn how to code UIs, I don't have the skills to do this or I would offer to help.

![image](https://github.com/pocketbase/pocketbase/assets/6081085/bb62b35b-80f7-4334-aae0-fe3fc303ce24)

**Comment by ganigeorgiev** [comment]
This was requested before (see https://github.com/pocketbase/pocketbase/issues/2378, https://github.com/pocketbase/pocketbase/issues/19), but at least until we reach a more stable version for now this is not planned.

**Comment by bbkane** [comment]
Ah I must not have searched the issues correctly, thanks!
