### ISSUE TITLE
Feature Request: Send a custom email

### ISSUE THREAD

**Issue by uxsoft** [pocketbase/pocketbase#3178]
Hi,

Pocketbase already has a send an email functionality, but just for a few built in types of email. I'm building several applications, which have the need to send an additional email (invite a customer, send an invoice, ...). 

I'm not a GO developer and would like to avoid using pocketbase as SDK and expanding it to support additional emails that way, so for me it would be incredibly useful if I could add define custom email types & templates from the admin UI and trigger them w/ the javascript SDK.

What do you think?

**Comment by ganigeorgiev** [comment]
This for now is not planned (see also https://github.com/pocketbase/pocketbase/issues/2111).

If you want to send custom emails with JS you can use the JS `pb_hooks` - https://pocketbase.io/docs/js-sending-emails/.

**Comment by uxsoft** [comment]
Oh perfect, I missed that option, that will do for me.
