### ISSUE TITLE
cli return code should be non-zero at failure

### ISSUE THREAD

**Issue by frankpolte** [pocketbase/pocketbase#3182]
When trying/failing to update the password of a non-existing admin user via cli the return code should be non-zero e.g. 1

```bash
~/tmp/foo$ pocketbase admin update admin@foo.com  foofoo123
Admin with email admin@foo.com doesn't exist.
~/tmp/foo$ echo $?
0
```
I would like to do this
```bash
~/tmp/foo$ pocketbase admin update admin@foo.com  foofoo123 || pocketbase admin create admin@foo.com  foofoo123
```

**Comment by ganigeorgiev** [comment]
_See https://github.com/pocketbase/pocketbase/discussions/2738._

**Comment by ganigeorgiev** [comment]
Aditionally, if you want to create admins programmatically with some custom handling I'd suggest using migrations:

- Go - https://pocketbase.io/docs/go-migrations/#creating-new-admin
- JS - https://pocketbase.io/docs/js-migrations/#creating-new-admin

**Comment by frankpolte** [comment]
thanks
