### ISSUE TITLE
JSON syntax Highlight / Validate

### ISSUE THREAD

**Issue by calumk** [pocketbase/pocketbase#3191]
It would be really nice if the Admin UI had a json syntax highlight or at least a validator for the json field.

If you manually edit json in the json field, and you make a mistake, it will escape your entire json

eg: If i miss the comma in the array, then click save
``` 
"{"tags": ["Aaa" "Bbb"]}
```

pocketbase saves it as the following

``` 
"{\r\n  \"tags\": [\r\n    \"Aaa\"\r\n    \"Bbb\"\r\n  ]\r\n}"
```

obviously if this is a massive JSON then this is quite a pain to undo!

Since the field is specifically JSON, I see no harm in running a JSON.parse before the save command is executed to avoid this kind of simple human error - it could always have a toggle switch to enable/disable validation if there is some reason you might want to save invalid json (maybe if people are using jsonc)

**Comment by ganigeorgiev** [comment]
I didn't want to bring extra dependency for this but I agree that it is inconvenient and will consider enabling the codemirror json plugin with the next release.

**Comment by ganigeorgiev** [comment]
This is implemented in the `develop` branch and will be part of the next v0.18.0 release (_there are no ETAs yet_)
