### ISSUE TITLE
Feature Request: Using reference columns for the one-to-many relations

### ISSUE THREAD

**Issue by fatihky** [pocketbase/pocketbase#3199]
Hi. The one-to-many relations are stored in the source table as a JSON array.  What about creating a reference column on the target table? That way, the database structure would be more intuitive. This might be an optional feature so existing users wouldn't be affected.

**Comment by ganigeorgiev** [comment]
I'm not entirely sure that I understand what do you mean.
You are free to create a helper junction collection that will contain just the ids as a more traditional SQL approach and have a relation field(s) pointing to it, but there are no plans to automate this.
