### ISSUE TITLE
NumberField doesn't allow decimals

### ISSUE THREAD

**Issue by KROSF** [pocketbase/pocketbase#32]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/24454660/178079991-8e6ac343-355a-473d-9325-6af05daedd93.png">

**Comment by ganigeorgiev** [comment]
Comma (`,`) is not a valid number character but it should work with dot (`.`).

**Comment by ganigeorgiev** [comment]
Actually, I've just tested it and indeed the `type=number` input is not allowing decimals because I've missed the `step` attribute. I'll add it in the next release during the weekend.

**Comment by ganigeorgiev** [comment]
Should be fixed in v0.2.0
