### ISSUE TITLE
nan error on quantity value

### ISSUE THREAD

**Issue by dgrunsted1** [pocketbase/pocketbase#3209]
I have a recipe website that I am making.  The basic data structure i am having issues with is a menu, recipe and ingredient tables.  menus contain recipes and recipes contain ingredients.  Originally I was just storing the ingredients as a json value in the recipes table.  I ran into an issue where pulling the recipe data as part of a a menu, i.e. using the expand function, my quantity value was being returned as nan, while all other ingredient data was showing up fine.  thinking this was an issue with my idiocy or a limitation of the json type I refactored to have an ingredient table, only to have the exact same issue.  when pulling menu->recipe->ingredient the quantity value is nan.  I look in the table on the admin console and its a a value not nan.  I pull a list of recipes the ingredients show up as expected.  what could be causing this?

**Comment by dgrunsted1** [comment]
this returns nan for t=only the qauntity values:
`const result_list = await pb.collection('menus').getList(1, 50, {
            filter: `user="${$currentUser.id}"`,
            expand: `recipes,recipes.ingr_list`
        });`

this returns the actual quantity value:
`const result_list = await pb.collection('recipes').getList(1, 50, {
            filter: `user="${$currentUser.id}"`,
            expand: `notes, ingr_list`
        });`

**Comment by ganigeorgiev** [comment]
I don't understand the above examples, but I don't think it is related to PocketBase or the JS SDK.

The NaN value could be a result from some operation with missing or undefined value, I'm not sure.

If you haven't identified the culprit, please create a **minimal** reproducible repo and I'll try to investigate it.

**Comment by dgrunsted1** [comment]
the value is not undefined in the db. other values in the same collection show when using expand function.  the value is not undefined when being pulled at the first level of expand. all that is being done is execute the the getlist function before console log.

**Comment by ganigeorgiev** [comment]
The JS SDK will never return NaN. It is a result from some client-side operation.

If you think that this is a PocketBase or JS SDK issue, please create a **minimal** reproducible repo and I'll have a look at it.
