### ISSUE TITLE
Problem After connecting the storage s3

### ISSUE THREAD

**Issue by siamakabi** [pocketbase/pocketbase#3210]
Hello
After connecting the storage space S3, the user table avatars are not shown.
![ewr45t4trtr](https://github.com/pocketbase/pocketbase/assets/79061836/e532386a-3f8a-46fa-9f0f-bd62f7b5f20e)

**Comment by ganigeorgiev** [comment]
Previously uploaded files have to be manually migrated (_there should have been a note in the Admin UI when enabling the S3 storage option_).

**Comment by ganigeorgiev** [comment]
_Side-note: If you use CloudFlare R2 as storage provider, keep in mind that it is not fully compatible with the S3 apis as several users reported issues with it - https://github.com/pocketbase/pocketbase/discussions/2952, https://github.com/pocketbase/pocketbase/discussions/2068._
