### ISSUE TITLE
Feature request: Adding the ablility to automaticly create collections 

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/pocketbase#3235]
this will open lots of possibilities for large apps and will make Pocketbase 1 step closer to being able to be used for production, but this idea might cause a lot of problems for servers, so I suggest to making it rate limited by default and that it requires authentication methods like needing a Pocketbase's admin account password to stop DDos attacks, it also needs to have a way to make api rules changes (prevent api rules changing on admin/manual created collections by defaul) and a way to difinshiate between auto created collections and admin/manual created ones on the admin dashboard

I hope that this idea will get added in feature releases as it makes making large app easier to make

**Comment by H1Mohamed** [comment]
well why cant it be automated with code, that is my question

**Comment by ganigeorgiev** [comment]
@H1Mohamed I don't understand what do you mean. The title of the issue doesn't match with the description.

If you want to create collections programmatically, please refer to https://pocketbase.io/docs/go-collections/.

Additionally, note that auto migrations are enabled by default so any change from the Admin UI will result in a migration file. This migraiton file can be safely commited in your repo and they will be executed automatically on `serve`.
