### ISSUE TITLE
Bad example in documentation for Custom Record Query

### ISSUE THREAD

**Issue by DblK** [pocketbase/pocketbase#3239]
As we can see [here](https://pocketbase.io/docs/go-records/#custom-record-query), we can see the usage of `dbx.HashMap` which does not exists.
It should be `dbx.HashExp` instead.

Since my [last discussion](https://github.com/pocketbase/pocketbase/discussions/3229), PR for doc seems to not be welcome so I am only doing this issue ;)

**Comment by ganigeorgiev** [comment]
PR for docs are welcome it just easier to directly fix the reported issue instead of waiting the user to prepare a PR.
