### ISSUE TITLE
Feature Request: Add Projects on top of Collections

### ISSUE THREAD

**Issue by The-Awesome-Tools** [pocketbase/pocketbase#324]
## Currently we have:

Collection_1
│
└───Table_1
└───Table_2

Collection_2
│
└───Table_1
└───Table_2

## Requested feature: 
It would be very useful to have Projects on top of collection.
The structure will look like:

```
Project_1
│
└───Collection_1
│     └─ table_1
│     └─ table_2
│   
└───Collection_2
│     └─ table_1
│     └─ table_2


Project_2
│
└───Collection_1
│     └─ table_1
│     └─ table_2
│   
└───Collection_2
│     └─ table_1
│     └─ table_2

```

This will allow to have multiple projects for multiple applications in a single PocketBase instance.

**Comment by ganigeorgiev** [comment]
Hi, Unfortunately at least for v1.0 I'm not planning to add multi-projects support.

You can follow this discussions - https://github.com/pocketbase/pocketbase/discussions/97#discussioncomment-3139409 and https://github.com/pocketbase/pocketbase/discussions/180.
