### ISSUE TITLE
Login into admin panel requires internet connection

### ISSUE THREAD

**Issue by gevera** [pocketbase/pocketbase#325]
Hey [ganigeorgiev](https://github.com/pocketbase/pocketbase/commits?author=ganigeorgiev)

I've noticed, when I am working locally in Pocketbase without an internet connection, i am not able to login into the admin panel. If I do connect to internet, Pocketbase will allow me to do it. It's not critical. Just inconvenient

Thank you for beautiful CMS.

**Comment by ganigeorgiev** [comment]
Hi, Yes there are several places where active internet connection is required - like the email MX domain validation, actual emails sending, s3 storage, oauth2 integration, etc.

In future releases I'll consider disabling the email MX domain validation, but at the moment complete offline development mode is not supported. You could follow this discussion - https://github.com/pocketbase/pocketbase/discussions/152
