### ISSUE TITLE
Feature Request: Maybe a wild one, running pocketbase in cloudflare wokers with D1

### ISSUE THREAD

**Issue by aerojeyenth** [pocketbase/pocketbase#3260]
Not sure if this is technically possible but still, I know we can run Go application in Edge Server-less environments Ref: [https://github.com/syumai/workers](https://github.com/syumai/workers ) 

Will it be possible to support running Pocketbase natively on Cloudflare wokers and also use the Edge database which comes with Cloudflare D1(SQLite based) ?

Since most of the Edge server-less platforms support wasm I think this can extend to other platforms(Vercel, Netlify etc., )

**Comment by ganigeorgiev** [comment]
Sorry, this is out of the scope and I have no plans working on this.
