### ISSUE TITLE
[Bug] Backup stuck forever on v0.18.0, eating up resources

### ISSUE THREAD

**Issue by kalmard-infinite** [pocketbase/pocketbase#3261]
I'm no expect on pocketbase or SQLite, so I have no clue what's going on here.

This is something I did not observe on previous versions but has been happening 80-90% (but not always!) of the time on 0.18.0.

Taking a backup:
- gets stuck forever
- takes up increasingly more and more disk space, to the point of eventually filling the entire disk
- increases cpu usage to 100%

Hard resetting the machine or killing the container resets disk usage to normal.

Backups on the instance are configured to save to S3 (confirmed working previously).

There is nothing relevant in stdout/stderr.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. We also have tests that runs without error.

How big is your database?
Could you test with an earlier version to rule v0.18.0 issue?

**Comment by ganigeorgiev** [comment]
I don't think this is PocketBase related and most likely it is some misconfiguration with Litestream but I'm not much familiar with it and I'm not sure how to help you debug it.

Note that when performing PocketBase backups we wrap the archive generation in a **transaction**, so double check whether Litestream is not holding a lock on the db or something else similarly.

In any case, if you think that this is a PocketBase issue, please provide more information about your deployment setup and ideally some **minimal** reproducible steps and I'll have a look.

**Comment by ganigeorgiev** [comment]
I've tested it both locally (Linux) and on S3 (Wasabi free trial) and it works fine for me - both the automated backups and manual initialized. My test `pb_data` is around ~500MB.

If you use Docker, ensure that the volume is mounted properly and accessible.

If you S3 - double check your storage configuration and permissions.
It could be also an issue with a vendor S3 APIs compatibility (in the past several users reported issues with Cloudflare R2 - https://github.com/pocketbase/pocketbase/discussions/2952).
To rule out S3 issue, you can try to temp disable it and test it with the local filesystem.

There is something happening in your setup but I'm not really sure how to help you further without some info or at least some reproducible steps.

**Comment by ganigeorgiev** [comment]
Also I forgot, If you have custom Go/JS hooks try to temp comment it to rule out a conflicting operation.

**Comment by ganigeorgiev** [comment]
Again, without information about your deployment setup I'm not really sure how to help you.

Where PocketBase is running and what command you are executing?
Are you able to reproduce it consistently?
Can you reproduce the issue locally?

**Comment by ganigeorgiev** [comment]
Indeed it could be a race condition introduced with v0.17.3 (https://github.com/pocketbase/pocketbase/commit/7a3223e4157f836942613c3a9c3691b16cc24420).

I'll investigate it further today.

**Comment by ganigeorgiev** [comment]
I wasn't able to make it "stuck" simulating your directory structure, but it is certainly a bug to have the local temp dir as part of the backups so that was removed in [v0.18.1](https://github.com/pocketbase/pocketbase/releases/tag/v0.18.1). Sorry for this.

Feel free to let me know if you stumble on the same issue again and I'll attempt to investigate it further.
