### ISSUE TITLE
Feature Request: Have relation field with "users" table mapping can be auto-filled during time of creation with jwt token. 

### ISSUE THREAD

**Issue by Jeyanthinath** [pocketbase/pocketbase#3274]
I have table which has comments, this is the table structure.

![image](https://github.com/pocketbase/pocketbase/assets/2253649/0687ae67-4996-4a0e-b7a4-0a0f09594778)

here, I have owner as the relation to the `default "users" table`

![Screenshot 2023-09-08 at 12 37 45 AM](https://github.com/pocketbase/pocketbase/assets/2253649/0df4c560-8972-4560-9ebc-1dc773556d8e)

If there is a toggle called "autofill" (only for this special "users" table relation), which I can toggle to get the user data auto-populated from the JWT Token of the user, any update happening on this field will have the owner details who updated it.

**Comment by ganigeorgiev** [comment]
Sorry, for now there are no plans for this as the request could be performed by entirely different auth collection or even not an auth record (eg. admin or guest).
