### ISSUE TITLE
`fields` query parameter not working as expected while authenticating

### ISSUE THREAD

**Issue by Mr-M1M3** [pocketbase/pocketbase#3278]
### NOTE: only tested while authenticating using password

I have an auth collection with two fields. 
```ts
Users{
   name: string;
   age: number;
  // other default fields
}
```
So, when I try to authenticate by hitting:
```
/api/collections/users/auth-with-password?fields=name
```
I expect (as the docs said): 
```ts
{
   token: string;
   record: {
      name: string;
   }
}
```
However, I get an empty object: 
```ts
{}
```

**Comment by ganigeorgiev** [comment]
The fields correspond to the API response structure.

The only restriction is the paginated list action to avoid having 2 different fields formats between `getList` and `getFullList`.

In other words, to return the JSON structure you expect, you can pass: `fields=token,record.name`.
