### ISSUE TITLE
Unable to filter records by @request.query.*

### ISSUE THREAD

**Issue by yivlad** [pocketbase/pocketbase#3287]
I have a list rule set up for my custom files collection,
```
@request.query.workspace = workspace || default = true
```
which is intended to allow users to access records if they know the workspace ID (workspace is a different collection) or if the record is marked as public (with default = true). However, this setup consistently returns an empty list. In the logs, I can see that it generates a suspicious query:

```
[0.00ms] SELECT `files`.* FROM `files` WHERE ((('' = [[files.workspace]] OR [[files.workspace]] IS NULL) OR [[files.default]] = 1)) AND ([[files.workspace]] = '5aw4ef0dyzq1ozk') LIMIT 200
```

This query always results in an empty list because no record has both default set to true and workspace set to '5aw4ef0dyzq1ozk'. What's interesting is that if I change the list rule to:
```
@request.query.workspace = workspace || default = false
```

It generates the following query:

```
[0.00ms] SELECT `files`.* FROM `files` WHERE ((('' = [[files.workspace]] OR [[files.workspace]] IS NULL) OR [[files.default]] = 0)) AND ([[files.workspace]] = '5aw4ef0dyzq1ozk') LIMIT 200
```

This query returns records with the provided ID but does not allow access to records with default set to true.

If I remove the default parameter and set the rule to:
```
@request.query.workspace = workspace
```

The generated query looks like this:
```
[0.00ms] SELECT `files`.* FROM `files` WHERE ((('' = [[files.workspace]] OR [[files.workspace]] IS NULL))) AND ([[files.workspace]] = '5aw4ef0dyzq1ozk') LIMIT 200
```

This query also returns an empty list because the expressions on both sides of the AND contradict each other.

I'm using Pocketbase v0.18.2, and it seems like there might be an issue with query generation. I'm not entirely sure, so I would appreciate advice on how to achieve my desired outcome.

**Comment by ganigeorgiev** [comment]
At first glance, the generated queries seems correct to me. Could you paste your collection configurations as JSON (_Admin UI > Settings > Export collections_) so that I can try to reproduce it?

**Comment by ganigeorgiev** [comment]
I've just tested it locally with the below collection structure and I'm not able to reproduce it.

```
{
    "id": "594xmcdfvo0ugye",
    "name": "test",
    "type": "base",
    "system": false,
    "schema": [
        {
            "system": false,
            "id": "oerxjfnl",
            "name": "default",
            "type": "bool",
            "required": false,
            "presentable": false,
            "unique": false,
            "options": {}
        },
        {
            "system": false,
            "id": "oeo5oqgm",
            "name": "workspace",
            "type": "relation",
            "required": false,
            "presentable": false,
            "unique": false,
            "options": {
                "collectionId": "yyd498z52k3qi59",
                "cascadeDelete": false,
                "minSelect": null,
                "maxSelect": 1,
                "displayFields": null
            }
        }
    ],
    "indexes": [],
    "listRule": "@request.query.workspace = workspace  || default = true",
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "options": {}
}
```

Make sure that you are sending the query parameter properly because in your case it seems that it is an empty string.

If you are still not able to identify the issue please export your collections configuration and how you are sending the request and I'll try to investigate it further.

**Comment by ganigeorgiev** [comment]
Also the final part of your query logs `([[files.workspace]] = '5aw4ef0dyzq1ozk')` doesn't look correct if you only provide the `workspace` as query parameter. Are you sure that you are sending `workspace` as plain query param and not as part of the `filter` expression?

**Comment by yivlad** [comment]
Hmm, you're actually right. `GET http://localhost:8090/api/collections/test/records?workspace=YOUR_ID` does return what I want. How do I achieve the same using pocketbase js client? I was testing it with
```ts
const fetchedData = await pb.collection("files").getFullList({
  filter: `workspace="${workspaceId}"`,
});
```
and it generated query `http://127.0.0.1:8090/api/collections/files/records?page=1&perPage=500&skipTotal=1&filter=workspace%3D%225aw4ef0dyzq1ozk%22`, which returns empty list.

**Comment by ganigeorgiev** [comment]
Pass the `workspace` as plain query parameter, something like:

```js
const fetchedData = await pb.collection("files").getFullList({
  workspace: workspaceId,
});
```

**Comment by yivlad** [comment]
Oh, didn't realise I can do that. Works like charm, thank you for the rapid response!
