### ISSUE TITLE
Inconsistent Goja default instances in CLI vs docs

### ISSUE THREAD

**Issue by veritymedia** [pocketbase/pocketbase#3288]
Small issue. When running pocketbase serve --help the --hooksPool flag says the default prewarmed goja instances is 50. On the other hand, the [docs say 25](https://pocketbase.io/docs/js-overview/#:~:text=prewarmed%20pool%20of%2025%20JS%20runtimes%2C).

**Comment by ganigeorgiev** [comment]
The default is `25` with v0.18+ (see https://github.com/pocketbase/pocketbase/blob/22b0a2b5863234a3f79c0e2e4e1664e7d1220251/examples/base/main.go#L41C1-L48C1).
