### ISSUE TITLE
Feature Request: Perform benchmark within admin UI

### ISSUE THREAD

**Issue by CovertCode** [pocketbase/pocketbase#3292]
I was using better-sqlite3 for benchmark on multiple cloud VPS and dedicated provider. They have pretty straightforward script to do that. It would be wonderful to have this within pocketbase admin UI to perform test by insert X number of records individually, bulk then read it individually and bulk.

**Comment by ganigeorgiev** [comment]
I think this will clutter the UI unnecessary and for now remains out of the scope.

For benchmarks you can check https://github.com/pocketbase/benchmarks.
