### ISSUE TITLE
Add Twitter Oauth option

### ISSUE THREAD

**Issue by janzheng** [pocketbase/pocketbase#33]
Hi there! If possible, could you add a Twitter Oauth login option?

Thanks!

**Comment by ganigeorgiev** [comment]
Hm, the last time I checked,  Twitter's OAuth2 api was still in beta, but [that doesn't seem to be the case any more](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code) and I will consider adding it to PocketBase in the near future.

**Comment by ganigeorgiev** [comment]
PocketBase now supports OAuth2 providers that don't return the user email address so @thomasdseao integration was included in the latest [v0.6.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.6.0).
