### ISSUE TITLE
Remove Password restrictions

### ISSUE THREAD

**Issue by zachsa999** [pocketbase/pocketbase#3300]
Hello, I love the project, what is the idea behind 10 character passwords? Lets leave that up to the user, no?

**Comment by ganigeorgiev** [comment]
10 chars is the minimum for the admin passwords.

For the auth collections user can change the min password from the auth collection options, but I just noticed that there is a js error when trying to expand the "Email/Password" accordion.

Will push a fix sometime later today.

**Comment by zachsa999** [comment]
Thanks for the clarification @ganigeorgiev
