### ISSUE TITLE
Option to Disable TLS validate on smtp port 25

### ISSUE THREAD

**Issue by Gustavo19951** [pocketbase/pocketbase#3301]
Hello

I currently have an SMTP with no TLS. Is it possible to have an option so that it does not validate this certificate?

![image](https://github.com/pocketbase/pocketbase/assets/42453150/b5065899-2bc5-44ae-b194-0b7ec3794cf3)

**Comment by ganigeorgiev** [comment]
I'm not entirely sure that I understand what the above error indicates, but for now there are no plans to enable the `InsecureSkipVerify` option if that is what you are asking as it will allow mitm attacks.

If you are looking for test mail servers, I usually use mailtrap.io
