### ISSUE TITLE
Unable to Edit Collections and Records via UI

### ISSUE THREAD

**Issue by AbdulHaseebHussainRI** [pocketbase/pocketbase#3302]
On the latest version of pocketbase on an Intel map, I'm unable to edit collections or add / edit records via the ui. Attached are the console errors I get. Creating collections via the ui seems fine.
<img width="1080" alt="Screenshot 2023-09-13 at 00 31 18" src="https://github.com/pocketbase/pocketbase/assets/93398687/aa9e1972-73ec-4d70-9d18-665bbfa972f5">

I've tried restarting my laptop, I've also tried older versions and also running pocketbase within my own go project, no solution seems to work.

**Comment by ganigeorgiev** [comment]
What is "_Intel map_"?

On what browser you are testing and what version?

Based on the errors it seems that `structuredClone` is not supported on the environment where you are testing.

**Comment by ganigeorgiev** [comment]
Check the browser compatibility table of `structuredClone` in https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility.

If the browser version is not the cause of the issue, feel free to provide more details on what browser you are testing and I'll try to investigate it further.

**Comment by AbdulHaseebHussainRI** [comment]
@ganigeorgiev Sorry I meant mac, seemed to sort itself out once I updated my chrome, thanks for your help
