### ISSUE TITLE
Username/Password authentication from Flutter Web

### ISSUE THREAD

**Issue by agreensh** [pocketbase/pocketbase#3312]
pocketbase 0.18.5 (linux arm64)
Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB) 

Trying to login with username/password now produces this exception:
"Expected a value of type 'Iterator', but got one of type 'DomIterator'"

pocketbase version and Flutter version both changed the same day. Was working before the updates (and still works from Android/iOS/Macos).
Any thoughts?

**Comment by ganigeorgiev** [comment]
Just tested it locally with PocketBase v0.18.5 and Dart SDK v0.15.1 and I'm not able to reproduce it.

```dart
import "package:pocketbase/pocketbase.dart";

void main() {
  final pb = PocketBase("http://127.0.0.1:8090");

  pb.collection("users").authWithPassword("test@example.com", "1234567890").then((result) {
    print("Success: $result");
  }).catchError((dynamic error) {
    print("Error: $error");
  });
}
```

Make sure that the SDK initialization url is correct and it responds with JSON (_note that the response could be also affected if you are behind a reverse proxy_).

If you are not able to identify the issue, feel free to provide more details about your setup and minimal reproducible steps and I'll have a look.

**Comment by agreensh** [comment]
After further investigation, it is adding an 'authStore' and 'httpClientFactory' on creating Pocketbase that is now causing the issue.
Without the authstore, it does still work. I am using "shared preferences" as suggested in the Flutter pocketbase doc, and again it was working.
Hope this helps.

`    
     final store = AsyncAuthStore(
         save: (String data) async => sp.setString(kPBLoggedInData, data),
         initial: sp.getString(kPBLoggedInData),
    );
    _pbProvider = PocketBase('https://.............',
        authStore: store, httpClientFactory: () => FetchClient(mode: RequestMode.cors));
`

**Comment by ganigeorgiev** [comment]
What was the previous version that you were using?

To rule out PocketBase SDK issue, try to remove the custom  `httpClientFactory`.
