### ISSUE TITLE
Password reset for user that doesn't exist has weird error message

### ISSUE THREAD

**Issue by ghostdevv** [pocketbase/pocketbase#3314]
If I request a password reset for a user that doesn't exist I get the following error in the request logs explorer:

```json
{
  "errorMessage": "sql: no rows in result set"
}
```

![image](https://github.com/pocketbase/pocketbase/assets/47755378/8b699895-5906-4652-9086-e98751f6e12d)

I'm not sure if this is a bug or not, but I assume it is since the error message appears to come from sqlite, and usually there is a more specific error message

Hope this helps! :pray:

**Comment by ganigeorgiev** [comment]
The above error could be returned if a user with the provided email doesn't exist (_I'll consider with the next release to provide a little more details to the error message_).

Specifically for this request there will be a validation error **only** if the email has invalid format. This is the only error that it is returned to the user.

For every other case, the errors are "swallowed" to avoid users enumaration.
