### ISSUE TITLE
Feature Request: Login with Patreon

### ISSUE THREAD

**Issue by FractalHQ** [pocketbase/pocketbase#3320]
My client wants users to be able to link their Patreon accounts.  I think this would be a great addition to the OAuth providers!

**Comment by ganigeorgiev** [comment]
I'm not planning working on this for the time being but user contributions are welcomed.

For a reference implementation you can check the recently added Yandex and Instagram PRs:
- (Yandex) https://github.com/pocketbase/pocketbase/pull/2762/files
- (Instagram) https://github.com/pocketbase/pocketbase/pull/2534/files

_(you can ignore the autogenerated `ui/dist` files; you can also skip the Go tests you are not sure how to change and I'll take care for them after the merge)_

**Comment by ghostdevv** [comment]
Submitted #3323
