### ISSUE TITLE
issue in view

### ISSUE THREAD

**Issue by apujayed** [pocketbase/pocketbase#3326]
SELECT factory
FROM inventory
INNER JOIN profiles
ON inventory.broker = profiles.id;

Invalid query - multiple statements are not supported

multiple query not support

**Comment by ganigeorgiev** [comment]
Try to remove the semicolumn at the end.

**Comment by mschmidm** [comment]
Had the same issue with the semicolon but in my case I got the error "Failed to update the collection".
Semicolons were allowed previously, in my case an update (I don't exactly remember which versions) caused my collection to break.
