### ISSUE TITLE
 pb.authStore.clear() doesn't clear the google session

### ISSUE THREAD

**Issue by ezdevapps** [pocketbase/pocketbase#3328]
I am using google provider for signing in. Works great!. One issue is that, in order to sign-out, as in the document, I am clearing the authStore. It does the signout in the app, but if I open my gmail, it opens the mailbox of the signed in user. Looks like it doesn't clear the google session. I need to sign-out from gmail in order to clear the google session. If I don't do this I will not be able to login to app with another google user, rather it repeatedly logs into the previous user logged in without prompting with the google sing-in popup.

**Comment by ganigeorgiev** [comment]
PocketBase has no control over the Google (or any other OAuth2 provider) auth session.

`pb.authStore.clear()` removes only the PocketBase related auth data from the local SDK instance.

See also https://github.com/pocketbase/pocketbase/issues/332.
