### ISSUE TITLE
Feature Request: Discord Auth Provider

### ISSUE THREAD

**Issue by IzMichael** [pocketbase/pocketbase#334]
Having Discord as an auth provider would be neat. IIRC it's a fairly simple api for implementing this

**Comment by ganigeorgiev** [comment]
This is already implemented by @karashiiro in [PR#335](https://github.com/pocketbase/pocketbase/pull/335).

It is currently only in the `develop` branch, but it will be available with the next v0.6.0 release.

**Comment by IzMichael** [comment]
oh, nice! ty
