### ISSUE TITLE
Does pocketbase will become another Parse? https://parseplatform.org/

### ISSUE THREAD

**Issue by jeremyspritelyco** [pocketbase/pocketbase#336]

**Comment by jeremyspritelyco** [comment]
https://parseplatform.org/

**Comment by ganigeorgiev** [comment]
Similar question was raised in https://github.com/pocketbase/pocketbase/discussions/103.

As mentioned in the above discussion, PocketBase was created for my other open source project - [Presentator](https://github.com/presentator/presentator) and all feature requests and improvements will be primarily aligned with its development.

If you haven't already, you can check the current v1.0.0 roadmap here - https://github.com/orgs/pocketbase/projects/2.
