### ISSUE TITLE
$os.exec() return type

### ISSUE THREAD

**Issue by Zehir** [pocketbase/pocketbase#3362]
Hello,

I think there is some issues with `$os.exec()`. According this [page](https://pocketbase.io/jsvm/functions/_os.exec.html), the return should be a `Cmd` but the description here don't really match the functions names. Like `Command("echo", "hello")` I suppose it's `exec("echo", "hello")`

The result of this should be a string
```typescript
const result = $os.exec("pwd")
console.log(typeof result.output())
```
But in reality it's a buffer, to get the real value I need to do :
```typescript
const resultData = String.fromCharCode.apply(null, result.output() as any)
```

And do we need to call `run()` ? Each time I tried to call `result.run()` I got a error message to say that it's already started.

Thanks for your help

Edit : Look like the correct way to read the result is :
```typescript
const resultData = readerToString(result.stdout)
```

**Comment by ganigeorgiev** [comment]
The JSVM documentation is autogenerated from the Go code and there will be always some inaccuracies (see https://github.com/pocketbase/pocketbase/discussions/2825 and https://github.com/dop251/goja/discussions/516).

_To some extend I'm starting to regret implementing the JS `pb_hooks`... In any case as mentioned in some of the other issues, I'll consider with the next release to expose more helpers for writer/reader Go interfaces but at the moment this is what we have._

**Comment by Zehir** [comment]
Thanks
