### ISSUE TITLE
pb_hooks api return 404

### ISSUE THREAD

**Issue by kimitaWanjohi** [pocketbase/pocketbase#3366]
I create a pb_hooks/main.pb.js file with the following code ``

routerAdd("GET", "/myapp/hello/", (c) => {
  let name = c.pathParam("name");

  return c.json(200, { message: "Hello " });
});
``

but now when I get /api/myapp/hello it retuns 404.
What could be the issue

**Comment by ganigeorgiev** [comment]
There is no `/api/` prefix in the registered endpoint.

Your public endpoint would be `https://example.com/myapp/hello/`.
