### ISSUE TITLE
How to change length of id in any colection

### ISSUE THREAD

**Issue by moisesBolano** [pocketbase/pocketbase#3370]
Hello Guys.

i'm prettend change lenght of id in any colection .

Request for Createnew row:

```
{
    "id" : "B53190BF-B242-493E-8756-47D75522E54B",
    "idBuyer" : "1111",
    ....
}
```

Response body api create:

`{
    "code": 400,
    "message": "Failed to create record.",
    "data": {
        "id": {
            "code": "validation_length_invalid",
            "message": "The length must be exactly 15."
        }
    }
}`

Thanks

**Comment by ganigeorgiev** [comment]
You can't. It is not customizable at the moment (_this may change in the future as there are plans to allow more native SQLite dev experience_).
