### ISSUE TITLE
Backup API/CLI command

### ISSUE THREAD

**Issue by ganigeorgiev** [pocketbase/pocketbase#338]
This was discussed in https://github.com/pocketbase/pocketbase/discussions/337.

It would be nice to have a backup API and/or dedicated console command to zip the entire PocketBase `pb_data` directory.

As mentioned in the above discussion, currently there are 2 major blockers to implement this easily:
- we have to find a way to generate efficiently the backup while the application is running (ideally without blocking for too long the regular app usage)
- we will have to decide how to deal with the uploaded files when S3 compatible storage is used (downloading them one by one may not be possible due to rate limits and high network traffic usage)

**Comment by skowrons** [comment]
The first problem could be solved by implementing essential something like a "Maintenance Mode" that blocks all API access. Combined with a scheduled backup this is a relatively solid solution. But it isn't feasible for application with a 24/7 up time.

GitLab has a few interesting strategies for backups. See their backup site https://docs.gitlab.com/ee/raketasks/backup_gitlab.html#backup-strategy-option.

 Basically there are two ways:
- just calling tar and gzip
- copy all data to a temporary directory and then call tar and gzip

From the provided link and their documentation:

> The default backup strategy is to essentially stream data from the respective data locations to the backup using the Linux command tar and gzip. This works fine in most cases, but can cause problems when data is rapidly changing.

> When data changes while tar is reading it, the error file changed as we read it may occur, and causes the backup process to fail. To combat this, 8.17 introduces a new backup strategy called copy. The strategy copies data files to a temporary location before calling tar and gzip, avoiding the error.

> A side-effect is that the backup process takes up to an additional 1X disk space. The process does its best to clean up the temporary files at each stage so the problem doesn’t compound, but it could be a considerable change for large installations. This is why the copy strategy is not the default in 8.17.

For the file problem. My suggestion would be to provide a flag that will include the S3 files or not. The default could be to not include external file storage solutions.

**Comment by ganigeorgiev** [comment]
Backup APIs and UI was implemented as part of [v0.16.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.16.0).

S3 uploaded files for now are not part of the generated backup as I couldn't found an optimal solution and it is left to the developers to handle it on their own (most S3 providers have backups offering).
