### ISSUE TITLE
Bug: folder left after file removal

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3382]
when you remove file the folder of thumb is left
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/1ff7c9c3-ae86-4af3-93db-e383edc7f43e)

**Comment by ganigeorgiev** [comment]
On what platform you are testing?
Could you provide some steps to reproduce it?

**Comment by ganigeorgiev** [comment]
I've tested on Linux with PocketBase v0.18.8 and I'm not able to reproduce it, aka. deleting a single record deletes all the files associated with it.

Note that the it is possible files to not be deleted in case of file permission issue or if you are deleting a collection file from the schema (the last one is a very low priority and tracked in https://github.com/pocketbase/pocketbase/issues/305).

If that's not case, please provide more details about your setup and ideally some reproducable steps and I'll have a look.

**Comment by pietru2004** [comment]
@ganigeorgiev operating/tested system windows... I have 2 fields for file storing. one for icon second for video

**Comment by pietru2004** [comment]
after adding and removing file from dashboard 2 times  Ihad 2 folders remaining

**Comment by ganigeorgiev** [comment]
@pietru2004 Are the directories empty?

**Comment by ganigeorgiev** [comment]
It is most likely related to the OS path separator. I'll test it tomorrow on a Windows VM.

**Comment by pietru2004** [comment]
so I just gona say what I did
I have such collection as test
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/7448c2e7-e752-4053-96ed-52f0131bc591)
I setted icon field for 1 record and after that removed it later I checked file structure wondering was folder removed... 
I seen it was not. 
I setted new icon for the file while monitoring folder and seen new thumb folder appearing. 
After removing thumg folder was empty but did not disappear...

**Comment by ganigeorgiev** [comment]
The issue is caused by the unnecessary OS specific separator path splitting, `\` vs `/` (_the filekey can only have `/` as that is used as separator prefix for the S3_).

I've submitted a fix in `master` (https://github.com/pocketbase/pocketbase/commit/e1fb5d26a56e8c10fc2f90bd7ff5acbb8cdf1d8b) and it will be available with the next minor v0.18.9.

I'll not rush a release as it shouldn't be a blocker and you can safely ignore the empty thumbs directory.

**Comment by pietru2004** [comment]
ok no problem... 
as it only happened in development and server/production is linux...
