### ISSUE TITLE
404: "The requested resource wasn't found." with a valid record on PATCH request

### ISSUE THREAD

**Issue by ItsCentric** [pocketbase/pocketbase#3383]
I'm running version `^0.18.0` and after coming back to my codebase after a few days it seems like my update call to the Pocketbase database has broken. I'm getting a 404 error telling me the record doesn't exist but if I look in the database the record does exist and the server does respond when I manually request it through the `/api/collections/users/records/:id` endpoint. I also tried running a PATCH request manually through the `/api/collections/users/records/:id` endpoint, only to be met with the same problem. Please let me know if there's any more information I could add to assist further

### My logs
![image](https://github.com/pocketbase/pocketbase/assets/89821311/05f777c3-7768-4347-9a7e-31308ac9aa81)
### The GET Request
![image](https://github.com/pocketbase/pocketbase/assets/89821311/c5636beb-43b7-4cab-be6e-4fb776a3731f)

**Comment by ganigeorgiev** [comment]
Double check whether your request satisfy the collection Update API rules, eg. whether you are authenticated (_see the note in https://pocketbase.io/docs/api-rules-and-filters/#api-rules_).

If that's not the case, please export your collections configuration as json (Admin UI > Settings > Export collections) and provide an example how you are sending the request and I'll have a look.
