### ISSUE TITLE
Bug: cpath args server crash

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3384]
I have been trying to use custom scripts/pb_hooks and if I have path
`http://localhost:8090/v/(arg here)`
if the place where argument would be is empty it might automatically return 404... 
I want for it to be treated as empty arg, mayby string length 0 or for it to cut one `/`, so link `http://localhost:8090/v/` would be `http://localhost:8090/v`

Basicaly trying to get pathParam that does not exists causes automatic 404

**Comment by pietru2004** [comment]
also I mean for case were there is no
custom route defined for  http://localhost:8090/v/

**Comment by ganigeorgiev** [comment]
I don't see how this is a bug but I'm having difficulties understand your description.

If you are looking for registering an optional trailing slash route currently there is no such middleware exposed in the JS pb_hooks (_I'll consider it with the next release_) and you have to define your route twice.

If that's not what you are trying to do, please elaborate.
