### ISSUE TITLE
Feature req: Rescue account

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3388]
I want to ask for something like super admin/rescue account that could be enabled via args or env variables. it would be only meant to change admins passwords.
This could be usefull for all the side projects that you placed on shelf for some time and did not write down password.

**Comment by ganigeorgiev** [comment]
This not document in the site docs at the moment but you can manage your PocketBase admins via the `admins` command. For example to change an admin password you can run:

```sh
./pocketbase admin update test@example.com 1234567890
```

_For more details you can use the `--help` flag, eg. `./pocketbase admin --help`._

**Comment by pietru2004** [comment]
Ok... thanks for info...
