### ISSUE TITLE
Expand collection from children

### ISSUE THREAD

**Issue by ajomuch92** [pocketbase/pocketbase#3389]
I don't know if this already exists, I was reading documentation and also trying but no good results. Is there a way to get the list of post related to a tag using `expand` parameter and during fetching tags (see image below)
![image](https://github.com/pocketbase/pocketbase/assets/32050436/9e37f45f-722d-429f-bf0c-6f9c9568b9f1)

**Comment by ganigeorgiev** [comment]
I guess what you are looking for is the [back/indirect-relation expand](https://pocketbase.io/docs/working-with-relations/#back-relation-expand), but there is one caveat - at the moment back-relation expand is only supported with single `relation` fields (_see the note at the end of the linked page_), aka. it won't work with multiple `relation` fields as in your example with the tags but it will work for the _"posts->comments"_ or _"users->comments"_.

The above limitation eventually may get removed in the future (_it is in the [roadmap](https://github.com/orgs/pocketbase/projects/2/views/1) to consider it but it is left aside for now_).
