### ISSUE TITLE
Feature/API SDK Request:  gdscript SDK

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3390]
Could there be API SDK for godot engine?
(yes I know I can just make http requests... and that is what I have been doing for now, but it would be nice to have godot API SDK)

**Comment by ganigeorgiev** [comment]
Sorry, at least until we reach a more stable version, there are no plans for now to work on other SDKs as it will be really hard for me to maintain, but community contributions are more than welcomed.

Unfortunately I don't have experience with Godot Engine and I'm not sure what to recommend, but if you or someone else want to work on an SDK you can use the [JS SDK](https://github.com/pocketbase/js-sdk) or the [Dart SDK](https://github.com/pocketbase/dart-sdk) as a reference (_I recommend more the Dart code as it is slightly easier to read in my opinion_).

**Comment by pietru2004** [comment]
ok
