### ISSUE TITLE
Events / Triggers

### ISSUE THREAD

**Issue by elamje** [pocketbase/pocketbase#34]
I'd like to help make events (or at minimum sql triggers) a thing for pocketbase. Being able to fire off in process/async tasks based on data changes would be a really nice application to get this closer to a low code solution. I understand that you can write your own Go code and build a single file binary, but what I'm talking about is more dynamic in nature. It could open up some interesting applications for admins to define 3rd party calls, web hooks, and be the building block for advanced functionality. I have no Go experience, so I'd like someone who is more familiar with the internals of the VM to help me understand what the limitations would be. 

I have a question that may be incredibly novice, but hopefully is helpful for other beginners looking at pocketbase. 
- Could Javascript or Go be written in admin, serialized into the db, and executed at runtime? Something to the tune of https://github.com/svaarala/duktape. What executing admin written Go/etc would open up is the ability to write cloud lambdas that are arbitrarily complex for long running processes. I also appreciate that this may overcomplicate the project.

**Comment by elamje** [comment]
My gut is that there is no way to build Go code dynamically, but I wonder if there is a javascript (https://github.com/svaarala/duktape) or lisp like language (https://github.com/glycerine/zygomys) that could be embedded in the binary.

**Comment by tonyhart7** [comment]
> My gut is that there is no way to build Go code dynamically, but I wonder if there is a javascript (https://github.com/svaarala/duktape) or lisp like language (https://github.com/glycerine/zygomys) that could be embedded in the binary.

there is way if you brave enough, I already build similiar in dart(flutter) so its parses the UI to the json, but Yeah its a hell hole

**Comment by elamje** [comment]
Ha, I would imagine embedding a lisp into this would be the simplest option, but very few users would know how to use it. Javascript events are probably the best from a market size perspective.

**Comment by ganigeorgiev** [comment]
PocketBase already has event hooks (https://pocketbase.io/docs/event-hooks/), but they are not dynamic (aka. you need to build your app).

There are several existing scripting interpreters for Go that allows executing dynamic code (eg. [anko](https://github.com/mattn/anko)), but they always will have some performance impact and will be more restrictive compared to what you could do by just embedding PocketBase in your Go app (eg. you have to specify what external libraries are allowed to be imported, global functions and variables visibility, etc.).

A more safer and user friendly alternative could be to implement a _workflow builder_ with some prebuilt configurable filter/action blocks that users can manage from the admin UI.

Adding support for something like this is possible, but it will take a lot of time to implement it properly and therefore at least for now it is out of the PocketBase scope.

**Comment by ganigeorgiev** [comment]
@elamje Just to let you know that I've outlined a new feature for integrating simple triggers in the prebuilt executable. You can share your feedback in https://github.com/pocketbase/pocketbase/issues/317.

**Comment by gedw99** [comment]
Async-api works well with Pocketbase.

the async-api is golang and code generated. Then you just hook into Pocketbase.

makes it easy to then built real time gui and api with the gui or api using the async-api layer being the glue between the 2 systems.
