### ISSUE TITLE
Feature Request : Export / Import a single Collection via JSONSchema

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/pocketbase#3403]
I manage multiple websites with Pocketbase

With the current system of importing collections, it is quite hard to import a single collection or a subset of collections if all other collections are not the same

I make manual modifications on the pb_schema.json to make it work, it does work

But if possible, adding a single collection from a schema would be great

**Comment by jonshipman** [comment]
In the interim, you can create a custom migration file. A restart of the pb binary will cause the migration file to run.

Another suggestion, a custom command for importing where you can pass in json as an argument. `cat some_json_file.json | pocketbase import-json`

**Comment by ganigeorgiev** [comment]
Support for export/import a subset of collections was added in the `develop` branch and will be available with the next v0.22.0 release (_there are no ETAs_).
