### ISSUE TITLE
Option to disable the installer

### ISSUE THREAD

**Issue by catdevnull** [pocketbase/pocketbase#3404]
One might want to disable the installer to avoid having someone set up the PocketBase instance before them.

**Comment by catdevnull** [comment]
Okay, cool. Can one use env variables in migrations, i.e. with `process.env`?

**Comment by ganigeorgiev** [comment]
Yes, but note that migrations are executed only once.

**Comment by catdevnull** [comment]
This is what I ended up doing: https://gitea.nulo.in/Sutty/containers-pocketbase/src/commit/68c85fdea38cd8f52ec8496db714587dc77f6684/1687801090_sutty_initial_admin.js
