### ISSUE TITLE
Bug : Data backup detected as Malware in Firefox

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/pocketbase#3410]
Note : might be an issue of Firefox. Same test with same instance / same backups on "Brave" browser had no such alert

See enclosed pictures

On pocketbase 0.17.5

![987](https://github.com/pocketbase/pocketbase/assets/136232300/fd4ac65b-5ba2-41d1-a4b0-18795f3f34b6)

New backup made a bit later had same alert
![87897](https://github.com/pocketbase/pocketbase/assets/136232300/71131f1e-8668-4427-9d5e-88f9d323a3d5)

On a side note : I have NO idea why, on this unused instance of pocketbase, 2 backups made with like 2 minutes yielded 2 backup files that are almost 20 kb difference, any idea why ? Is this like some random encryption padding ?
![9875](https://github.com/pocketbase/pocketbase/assets/136232300/78b0da34-c4a0-46da-bca8-d2c242633288)

FF Version : 
![7869](https://github.com/pocketbase/pocketbase/assets/136232300/7927d3c4-e5a4-464b-a698-6bf79b8b1564)

I could give you personally an admin account to access the PB instace for debugging or maybe JSONSchemas & the backups, there are no user or sensitive data yet

**Comment by ganigeorgiev** [comment]
I don't think there is anything we can do with that.

It is most likely a false positive that you should report to the antivirus software you use.

The backup is just zip archive of your `pb_data` directory (including any record uploaded files).

**Comment by MarArMar** [comment]
Most likely from firefox itself, as same backup with different browser does not block the download
