### ISSUE TITLE
Feature Request : Backup restore working on Windows

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/pocketbase#3411]
"Backup restore is still experimental and currently works only on UNIX based systems."

Would be great if we can have it on Windows too

(Love your work btw, no rush or anything, but just mentioning this as I wanted to use it)

**Comment by ganigeorgiev** [comment]
I may reconsider it in the future depending on the users demand but at least for the time being I'm not planning working on this as it will complicate unnecessary a lot of the internals for very little benefit.

If you need to restore a backup, you can manually unzip the archive and replace your existing `pb_data` directory.

User contributions are also welcomed (the backup restore code can be found at https://github.com/pocketbase/pocketbase/blob/fadd12cd225ee6056b29bd4d3d40d825d644d665/core/base_backup.go#L133.

**Comment by MarArMar** [comment]
Tried to restore the backup manually, did not work

Checked before if the collections were the same with import / export collections, it says "
Your collections configuration is already up-to-date!"

Had this bug : 

2023/09/29 10:47:55 Failed to apply migration 1695724454_updated_users.js: constraint failed: UNIQUE constraint failed: _collections.name (2067)

I renamed the collections at some point

**Comment by MarArMar** [comment]
Should I copy / paste the migrations file from the server too ?

**Comment by ganigeorgiev** [comment]
@MarArMar Without context or at least some reproducible steps I'm not sure how to help you.

Note that if you want to sync your db schema between different environments, the recommended approach is to use migrations ([Go](https://pocketbase.io/docs/go-migrations/) or [JS](https://pocketbase.io/docs/js-migrations/)). The prebuilt executable comes with automigrate enabled by default which will produce automatically a migration file in `pb_migrations` that you can safely commit to your repo and deploy to your targetted environment.

**Comment by MarArMar** [comment]
Ok interesting thanks

Will update if I solve the problem

**Comment by MarArMar** [comment]
Would be solved by https://github.com/pocketbase/pocketbase/issues/48

**Comment by ganigeorgiev** [comment]
If you have a local `pb_migrations` and trying to restore a backup from some other environment then it could fail because on initialization it will try to apply the missing local migrations on top of the backup. In the case of using a backup from somewhere else, you can delete your `pb_migrations` and start the application as usual with the new `pb_data`, but again the recommended approach to sync schema changes between environments is to use the migrations.

**Comment by MarArMar** [comment]
@ganigeorgiev Ok indeed deleting `pb_migrations` worked thanks
