### ISSUE TITLE
Feature Request : Allow a setting to change how long the id can be in collections

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/pocketbase#3420]
add a global setting to change the id length in collections, this could be helpful for big projects that somehow filled every id slot in a collection, possibly you can add privet collection setting to change the id length for that specific collection

**Comment by ganigeorgiev** [comment]
This was discussed several times in the past. It is in my todo as part of a bigger task to provide a more "native" SQLite dev experience, meaning that users will have more control over the system `id`, `email`, `username`, `created`, `updated`, etc. fields, but for now remains a low priority.
