### ISSUE TITLE
Feature request: Editor login

### ISSUE THREAD

**Issue by pawcoding** [pocketbase/pocketbase#3421]
### Background
I mostly use PocketBase as a content management system to manage content for various websites. Since I am only the developer and not responsible for the content of the pages themselves, the authors have their own admin credentials to add the content to the database themselves. Since the PocketBase interface is easy to use even for people without prior knowledge of databases, I don't have to create my own interface for editing the data.

### Proposal
I'd like to be able to restrict the permissions of these authors so that they can only edit the records, but do not have access to important technical settings such as mail, S3 or backups. The interface could be modified according to the permissions of these users and would then look something like this:

![image](https://github.com/pocketbase/pocketbase/assets/78467484/47c3d4d8-e565-4c6f-bd85-0c207de96f41)

#### Permissions
- View collections
- Create and edit records
- Change own email, avatar and password
- No API preview (optional)
- No ability to create or edit collections
- No access to logs
- No access to settings (except settings for own profile)

Each admin account would then need a boolean flag (root / superadmin / editor) that determines what type of admin it is. This can of course only be changed by a superadmin.

**Comment by ganigeorgiev** [comment]
At least for v1 (or at least until we stabilize the internal APIs) for now there no plans to introduce admin roles/permissions or restricted admin views.

_See also https://github.com/pocketbase/pocketbase/discussions/50._
