### ISSUE TITLE
Feature Request : Allow the ability to change languages in the admin dashboard

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/pocketbase#3422]
adding the ability to change the Ui language in the admin dashboard will open pocket base to a whole new audience, as of me, I have many friends that really loved the simplicity pocket base dashboard but had problems with the language as they speak Arabic and they're really weak with English. Our communities Can help you translate the Ui for You

**Comment by ganigeorgiev** [comment]
Sorry, for now there are no plans for this as it will be really hard to maintain.

See also https://github.com/pocketbase/pocketbase/issues/37 and https://github.com/pocketbase/pocketbase/pull/85.

**Comment by lifetin** [comment]
Many people hope to add language pack functionality, but they haven't upgraded to 1.0 or received language pack support in the past 2 years      😒😒😒

**Comment by ganigeorgiev** [comment]
@lifetin Please don't spam! You've already opened an issue in https://github.com/pocketbase/pocketbase/issues/7283 and commented on other older issues.

I'm sure that there is a language barrier, but I hope that you can understand that this is just a hobby project and the project is provided as it is. Please read the [FAQ](https://pocketbase.io/faq/). If you are not satisfied with the development pace, then please use something else, but don't spam again like that as it will result in permanent ban.
