### ISSUE TITLE
[BUG] DBX uses UTC instead of local time

### ISSUE THREAD

**Issue by miltkall** [pocketbase/pocketbase#3424]
Good afternoon,

**thank you very much for your amazing project and effort**. I will try to contribute in the future. Firstly let's resolve this issue.

Can you please explain, why you are using **.UTC()**, this return UTC time and ignores the timezone. 
https://github.com/pocketbase/pocketbase/blob/837134559fe048e24fb1eb129c5c10d218f7ef3d/tools/types/datetime.go#L51

The logs are fine, but records are created and updated using UTC (which in my case is 2 hours in the past, Europe/Berlin). Moreover, I have some columns with time information, which are also in UTC (again 2 hours in the past in my case).

Can we please fix this or explain why you implemented this way?

Many thanks and will try to contribute more to your project.

**Comment by ganigeorgiev** [comment]
This is working correctly.

All `date` field values are stored and returned as UTC.

Note that different users can have different local times and it is better in the db to have a single unified format.

If you want to show the dates in the user's local format, I recommend performing the conversion on the client-side.

**Comment by miltkall** [comment]
I see. Thanks

**Comment by miltkall** [comment]
I was using your DB as a framework and therefore came to this problem. Will have to write a go client to talk to the DB then. Thanks

**Comment by ganigeorgiev** [comment]
I'm not familiar with your use case and I'm not sure that I understand what do you mean by _"go client to talk to the DB"_ but note that storing dates with mixed timezones will significantly complicate the querying/filtering your data and I'd advice against doing it.
