### ISSUE TITLE
Proposal: Expand fields in-place

### ISSUE THREAD

**Issue by jiri** [pocketbase/pocketbase#3435]
I find the current solution of having the expanded relations in the `expand` property to be quite cumbersome. It duplicates the id of the expanded relation, which can now be accessed via either of `result.foo` and `result.expand.foo.id`. Moreover the type of the fields of `expand` is `Record | Record[]`, which leads to a type hint error every time a property is accessed on it that doesn't also exist on an array.

Has expanding the fields in-place been considered? I expect there's a reason to doing things this way, but I couldn't find anything in the issues or documentation.

**Comment by ganigeorgiev** [comment]
There are no plans for now to change the expand behavior. The main reason for the current implementation was to preserve the original Record fields data structure.

Note that, depending on the View API rule of related collection, when expanding it is also possible that not all relations will be returned, meaning that there could be some missing entries in the final result that didn't satisfy the rule constraint.

> Moreover the type of the fields of expand is Record | Record[], which leads to a type hint error every time a property is accessed on it that doesn't also exist on an array.

Hm, for this I'm not sure what would be the best here. I'll think a little more on it over the weekend and may consider changing it to `any`.

**Comment by ganigeorgiev** [comment]
About the `Record | Record[]` I forgot that this is actually no longer true since from JS SDK v0.17+ because we now return now POJOs and the `expand` type should be `{[key: string]: any}` already.

If you use an older SDK version you can check the [v0.17.0 CHANGELOG](https://github.com/pocketbase/js-sdk/blob/master/CHANGELOG.md#0170) as there are some minor breaking changes:
