### ISSUE TITLE
API Docs adaptative

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#3452]
Make the API Docs adapt, for example users must use a domain to insert twitter or x, so should be better that link instead of:   "twitter": "https://example.com",
also would be amazing to add "socialusername" for /socialusername not to put all the link?

![API Docs Adapatative](https://github.com/pocketbase/pocketbase/assets/5947268/2437fec0-8995-45b5-aa7d-bb3dcc7ec0d1)

**Comment by ganigeorgiev** [comment]
The preview is just an example.
I don't think this is necessary as it will complicate the docs generation code without much benefit.
