### ISSUE TITLE
Feature Request: Add adaptive fields.

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/pocketbase#3454]
add a type of fields that will be linked to a Boolean value, if the value is true, the field can be set to a value, if false the value will be set to none.
it is possible to do it manually but it will take a lot of server resources to do and it's very hard and not safe so having a built-in way will be a spectacular feature.
also I have a project that I'm working on on the moment so it will be useful

**Comment by ganigeorgiev** [comment]
Sorry, I'm not sure that I understand what is the use case for this, but for now there are no plans to add new field types.

**Comment by H1Mohamed** [comment]
lets say as an exsample that I had for some reason.
we have a collection containing 3 fields, a text field containing a post, a second boolean field called isPrivet, and a third json filed named AllowedUsers, the AllowedUsers list  **_MUST_**  be empty if the isPrivet is set to false, this is a very helpfull exsample to do it

**Comment by yanc0** [comment]
Hi @H1Mohamed ,

What about removing your boolean field and considering that your array is already sufficient ? 
You can do that with sql by using [IIF](https://www.sqlite.org/lang_corefunc.html#iif) sqlite function.

```sql
SELECT id, iif(allowedUsers = 'null', FALSE, TRUE) as isPrivate
FROM example
```

If `allowedUsers` is : 
  * `null` then the post is public
  * `[]` empty array then the post is private and no one can access it
  * `["foo", "bar"]` then the post is private: foo and bar can access it
