### ISSUE TITLE
Feature request: OAuth KeyCloak

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#3456]
Feature request: OAuth KeyCloak

**Comment by ganigeorgiev** [comment]
I think KeyCloak already supports OpenID Connect (OIDC) so you should be able to use the existing PocketBase OIDC provider.

**Comment by miguelgargallo** [comment]
Oh yeah! and it worked like a champ!
Just finding something less "LEGO" to mount, but is okay!
Thanks for your time! I appreciate @ganigeorgiev
