### ISSUE TITLE
Feature request: Authy Oauth push to login

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#3458]
Feature request: Authy Oauth push to login

**Comment by ganigeorgiev** [comment]
I don't know what Authy is but user contributions for new OAuth2 providers are welcomed.
You can use the latest [mailcow PR](https://github.com/pocketbase/pocketbase/pull/3364) as a reference.

**Comment by miguelgargallo** [comment]
Really? Oh created a small OAuth2 I will see of course to contribute!
