### ISSUE TITLE
Feature request: Database migration between collections

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#3459]
I created a new Auth table from a non auth table by duplicating, now I want to migrate data from users to users_new, how?

**Comment by ganigeorgiev** [comment]
There is no builtin import/export functionality (this eventually will be added as part of #48) and specifically for moving data between collections would be hard to generalize.

The best option would be to create custom SQL import scripts or if you want to do it progmattically you can use Migrations - [Go](https://pocketbase.io/docs/go-migrations/) or [JS](https://pocketbase.io/docs/js-migrations/).

**Comment by miguelgargallo** [comment]
I implemented in the past but with my own code and custom inside! but just fine!

**Comment by miguelgargallo** [comment]
Oh and! @ganigeorgiev thanks for your time, appreciate it!
