### ISSUE TITLE
Bug - binding form to RecordUpsertForm

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3463]
so I have tried binding `RecordUpsertForm` to the context, I fought it would work as `RecordPasswordLoginForm` and take form data from context

```js
routerAdd("post", "/upload", (c) => {
    const record = c.get("authRecord")
    let is_authed = (record!=null);
    try {
        const files = $app.dao().findCollectionByNameOrId("files")
        const record = new Record(files)

        const form = new RecordUpsertForm($app, files);

        c.bind(form);
        const fileRecord = form.submit();

        return c.redirect(307, "/v/"+fileRecord.get("id"));
    } catch (err) {
        // maybe redirect to an error page?
        console.log(err)
        console.log(c.request().postFormValue("tittle"))
        //return c.redirect(400, "/error");
    }
```

The error prints
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/b812b45c-fb7c-4320-848d-cf808ea0677e)
so from what I understand it says tittle is missing while it is set to value `ShelterTest`

**Comment by ganigeorgiev** [comment]
It is not a bug, the `RecordUpsertForm` works slightly differently (_the `bind` method allow populating only public struct fields but the record data of the `RecordUpsertForm` are dynamic as they depend on the collection_).

For working with the `RecordUpsertForm` you can check https://pocketbase.io/docs/js-records/#create-new-record-with-data-validations.
