### ISSUE TITLE
Feature Request: Make collection name fully visible

### ISSUE THREAD

**Issue by duytbp** [pocketbase/pocketbase#3467]
In my setup, collection names are a bit lengthy and some of them got cut-off with ellipsis (...).

Maybe we can show name inside a popover, or make sidebar width fit-content (it's 12.5% now in [vars.scss](https://github.com/pocketbase/pocketbase/blob/7fa1ff53c9bc7c535a89d78ba491c18987e3bb48/ui/src/scss/_vars.scss#L61C6-L61C7))

**Comment by ganigeorgiev** [comment]
There should be already a native browser tooltip with the full name on hover.

For now there are no plans to change the collections sidebar visualization, but it is in my todo to consider allowing users to "drag" the edge of the sidebar to manually control its width as it was requested several times before.
