### ISSUE TITLE
Pocketbase Restoration issue

### ISSUE THREAD

**Issue by ishukeshri2712** [pocketbase/pocketbase#3477]
Hi Guys I find a very unique problem in pocketbase that when i had taken the backup in pocketbase and tried to restore the backup i found that when i deleted some fields from a collection and tried to restore it i m  able to restore it through backup and it is visible in UI  but when i deleted the whole collection and tried  to restore it not able to restore collection is there any bug going on ??

**Comment by ganigeorgiev** [comment]
It is not a bug and it is most likely your `pb_migrations` are applying after the backup.

If you don't want this behavior, delete your migrations.

If that's not the case, please provide a **minimal** reproducible repo and I'll investigate it.

**Comment by ishukeshri2712** [comment]
i deleted the pb_migrations it get created automatically and still not able to find that in the collection i deleted one field and tried ti restore it works but when i deleted the collection i m not able to restore

**Comment by ganigeorgiev** [comment]
I'm not I follow.

The backup archive contains only your `pb_data` at the moment of the backup.
When you perform a restore, it will replace your existing `pb_data` with the one from the backup AND will apply any migrations that weren't applied in the backup's `pb_data` (_this is because the migrations can contain custom code that is required for the application to run_).

Again, if you want the exact same state as the one from the backup archive, try to delete your migrations.

**Comment by ishukeshri2712** [comment]
it worked thanks but pb_migration is created everytime i add another collection how to remove it permanently?? any idea??

**Comment by ganigeorgiev** [comment]
You can disable the automigrations by starting the executable with `--automigrate=0`.

For more details about the migrations please check [Go migrations](https://pocketbase.io/docs/go-migrations/) or [JS migrations](https://pocketbase.io/docs/js-migrations/)

**Comment by ishukeshri2712** [comment]
thanks bro you are great

**Comment by ishukeshri2712** [comment]
FROM alpine:latest

ARG PB_VERSION=0.18.9

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the image
# COPY ./pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# COPY ./pb_hooks /pb/pb_hooks

EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]   can you tell me how in dockerfile how can i make automigrate=0?? plse @ganigeorgiev

**Comment by ishukeshri2712** [comment]
FROM alpine:latest

ARG PB_VERSION=0.18.9

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the image
# COPY ./pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# COPY ./pb_hooks /pb/pb_hooks

EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]   can you tell me how in dockerfile how can i make automigrate=0?? plse

**Comment by ganigeorgiev** [comment]
You can add it as another item to the `CMD` instruction array, aka.:

```dockerfile
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080", "--automigrate=0"]
```

**Comment by ishukeshri2712** [comment]
Error: unknown flag: --auto-migration
unknown flag: --auto-migration
Usage:
  pocketbase serve [domain(s)] [flags]

Flags:
  -h, --help              help for serve
      --http string       TCP address to listen for the HTTP server
                          (if domain args are specified - default to 0.0.0.0:80, otherwise - default to 127.0.0.1:8090)
      --https string      TCP address to listen for the HTTPS server
                          (if domain args are specified - default to 0.0.0.0:443, otherwise - default to empty string, aka. no TLS)
                          The incoming HTTP traffic also will be auto redirected to the HTTPS version
      --origins strings   CORS allowed domain origins list (default [*])

Global Flags:
      --automigrate            enable/disable auto migrations (default true)
      --debug                  enable debug mode, aka. showing more detailed logs
      --dir string             the PocketBase data directory (default "/pb/pb_data")
      --encryptionEnv string   the env variable whose value of 32 characters will be used 
                               as encryption key for the app settings (default none)
      --hooksDir string        the directory with the JS app hooks
      --hooksPool int          the total prewarm goja.Runtime instances for the JS app hooks execution (default 25)
      --hooksWatch             auto restart the app on pb_hooks file change (default true)
      --indexFallback          fallback the request to index.html on missing static path (eg. when pretty urls are used with SPA) (default true)
      --migrationsDir string   the directory with the user defined migrations
      --publicDir string       the directory to serve static files (default "/pb/pb_public")
      --queryTimeout int       the default SELECT queries timeout in seconds (default 30)

**Comment by ishukeshri2712** [comment]
container not able to start

**Comment by ishukeshri2712** [comment]
thanks bro

**Comment by ishukeshri2712** [comment]
@ganigeorgiev Hi bro is there anyway that if backup is taken and stored in bucket we get a notification for that?? does pocketbase has this feature??
