### ISSUE TITLE
Expand not working

### ISSUE THREAD

**Issue by pzehle** [pocketbase/pocketbase#3482]
I just installed v0.18.9. Using the API, expand does not work at all.

URL I am using is: `/api/collections/trading_symbols/records?fields=*,expand.exchange&expand=exchange.*`

No matter how I change the fields and expand parameters, it just always returns the ID.

Here some pictures of the collections:

**Notice that the API rules for view and list/search are open to the public**

![Screenshot 2023-10-09 at 00 51 39](https://github.com/pocketbase/pocketbase/assets/27866874/88074eae-7079-4fb3-9544-32901eb3c7f0)
![Screenshot 2023-10-09 at 00 51 54](https://github.com/pocketbase/pocketbase/assets/27866874/a9809758-7947-4468-b5a1-841f8fadcefb)
![Screenshot 2023-10-09 at 00 52 06](https://github.com/pocketbase/pocketbase/assets/27866874/50e605f5-f7f1-45ec-bdc2-3746b0138a49)
![Screenshot 2023-10-09 at 00 52 11](https://github.com/pocketbase/pocketbase/assets/27866874/3f2b4058-0026-4921-87ec-793d02e65068)

Response comes like this (always):

```json
{
    "items": [
        {
            "collectionId": "as3bwqkwyf04cih",
            "collectionName": "trading_symbols",
            "created": "2023-10-08 22:33:01.561Z",
            "exchange": "ih1wsjay7ygj8z0",
            "id": "ytcb3qu6k8elajd",
            "is_active": true,
            "pair": "BTCUSDT",
            "updated": "2023-10-08 22:40:21.190Z"
        }
    ],
    "page": 1,
    "perPage": 30,
    "totalItems": 1,
    "totalPages": 1
}
```

**Comment by nedpals** [comment]
> URL I am using is: `/api/collections/trading_symbols/records?fields=*,expand.exchange&expand=exchange.*`

Replace `expand=exchange.*` with `expand=exchange`. The dot notation is reserved only for when you want to do nested expand (e.g. `comments.author` for when you want to expand the `comments` and the `author` at the same time).

https://pocketbase.io/docs/working-with-relations/

**Comment by ganigeorgiev** [comment]
@nedpals suggestion is correct. In other words, your final url if you don't need to restrict the returned fields, should be something like:

```
/api/collections/trading_symbols/records?expand=exchange
```
_Note that in order to be able to expand the `exchange` relation your client request must satisfy the View API rule of the `exchanges` collection._
