### ISSUE TITLE
Feature Request : Redirect to website when click on "Close" on default Password Change confirmation page

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/pocketbase#3499]
When a user successfully change their email, this page appears : 

![7574](https://github.com/pocketbase/pocketbase/assets/136232300/5f7d87d7-50fd-4ed2-b188-dd50175b82a5)

I believe a nice thing would be to redirect to the website when clicked on "Close"

Or maybe my browser do not do the expected thing here ? Should it close the page ? 

Maybe it is only a Firefox error : 

![image](https://github.com/pocketbase/pocketbase/assets/136232300/ec4d5c60-2ac4-416e-a2b1-b93eefcf9503)

"Scripts may not close windows that were not opened by script."

Edit : same behavior on brave :
![image](https://github.com/pocketbase/pocketbase/assets/136232300/2e32fe6e-02c4-4d66-bc36-042e36821c58)

I believe simply closing the page is totally good as well

**Comment by ganigeorgiev** [comment]
For now there are no plans to introduce extra configurations to the default confirmation pages.

But you can define your own custom confirmation pages by changing the "Action URL" in the _Admin UI > Settings > Mail Settings > {template}._
