### ISSUE TITLE
can pocketbase integrate with arduino ?

### ISSUE THREAD

**Issue by shidandev** [pocketbase/pocketbase#3503]
if yes, can i know how to setup that integration.
if no, can i request that integration as features?

**Comment by ganigeorgiev** [comment]
When using the cgo-free port (aka. `CGO_ENABLED=0`), PocketBase can compile only on the following platforms:
```
darwin	amd64   3.41.2
darwin	arm64   3.41.2
freebsd	amd64   3.41.2
freebsd	arm64   3.41.2
linux	386     3.41.2
linux	amd64   3.41.2
linux	arm     3.41.2
linux	arm64   3.41.2
linux	ppc64le 3.41.2
linux	riscv64 3.41.2
linux	s390x   3.41.2
windows	amd64   3.41.2
windows	arm64   3.41.2
```

When using cgo (`CGO_ENABLED=1`) technically it can compile to any Go supported environment - https://go.dev/doc/install/source#environment.

For Arduino - I guess it depends what hardware you have but in general I'm not sure if that will be possible as you'll have to probably use TinyGo, which doesn't support several of the packages that we rely on - https://tinygo.org/docs/reference/lang-support/stdlib/#nethttp.

This is out of the scope of the project for now, but user contribution to the documentation are welcomed.
