### ISSUE TITLE
Feature request: Make logging of user IP addresses optional (GDPR compliance).

### ISSUE THREAD

**Issue by cmaas** [pocketbase/pocketbase#3519]
Don't store user IP addresses by default, make the middleware for this optional. Reason: GDPR yadda yadda.

(Yes, you can store IP addresses under GDPR in some cases, but why bother with that stuff if I don't WANT to store them and have this kind of hassle? If I don't store them, I don't have to put that stuff in my privacy policy in the first place and don't need to care about the nuances of the GDPR.)

**Comment by ganigeorgiev** [comment]
This was raised before in https://github.com/pocketbase/pocketbase/issues/1477 (check the link if you need a workaround to "hide" the IPs).

In short, I don't think there is a GDPR issue here as the IP is not associated to a concrete user "session" and it falls under the "legitimate interests" section (GDPR Art.6-1f).

In any case, the logs structure and interface will change in the near future as part of the "Logs generalization" task to allow any kind of logs and I'll consider eventually allowing option to configure the default behavior.

**Comment by cmaas** [comment]
Thanks for the quick reply and sorry that I missed the first issue.

> In short, I don't think there is a GDPR issue here as the IP is not associated to a concrete user "session" and it falls under the "legitimate interests" section (GDPR Art.6-1f).

1. The IP address is considered personal information. Maybe I can't associate a specific IP to a specific session within PocketBase, but I (as person/entity responsible for data processing) might be able to correlate the IP with a user session by other means. Think: Running Pocketbase and other services on the same server. The source of the IP address is less important than the fact that I have personal data of someone.

2. Even if the logging of the IP address falls under legitimate interests, I still need to disclose that I log the IP address in my privacy policy, name a retention period and if someone wants a copy of all their data, I need to make an effort to find their IP address in the logs as well, since I logged it. It is always easier to simply state: "We don't log the IP address" than to try to justify the logging with some kind of "legitimate interest".

3. The "legitimate interest" section of the GDPR is kinda abused for everything. I recently read an interesting counter argument that is against IP logging: The usual stated legitimate interest for logging an IP is that you can help authorities resolve a crime if your server gets attacked. However, if you are super strict, "preventive logging" isn't a legitimate interest. Only after an attack launched, you can claim that you now have a legitimate interest to log all IP addresses. Not sure if we need to be this strict, but there is discussion about the finer aspects and it's not as clear cut as simply claiming "legitimate interest".

4. Collecting IP addresses is primarily a  business decision and the question is: do you really want to make that decision for all the individuals and businesses out there that use Pocketbase?

I'd appreciate if you consider these points for a future release, because the landscape of GDPR-compliant BaaS offers is really thinly spread. It might be a differentiator in favor of Pocketbase and after all, it's just a small entry in the config if someone makes the decision to log IP addresses.

**Comment by maietta** [comment]
@cmaas,

Place your instances behind proxies and either scrub or otherwise anonymize the IP's however you wish, but don't push the software developers to comply with various laws in various lands.

Did you know that all software that uses any form of encrypt illegal in some countries? People go to prison for possessing or using such software. People with your mindset are very reason those laws exist.

Think hard about this. Just leave the software developers alone. We're the one's making the world a better place, not your government.

**Comment by cmaas** [comment]
@maietta Totally get your perspective and I agree to some extend: an open source dev shouldn't be too concerned about random local laws in various countries. However, in this case, the dev behind pocketbase is from Bulgaria, which is an EU country. I simply suggested a small change that made compliance with the GDPR in his own regulatory zone more simple. Cheers!

**Comment by maietta** [comment]
@cmaas,,

Being in Germany, you have all people should know where your kind of thinking leads to.

The solution I proposed imposes no work on the part of someone who volunteers their time while also satisfying YOUR needs easily while also helping protect your instances. It's a win-win-win in my book.

The third option I recommend is to fork the project and make it yours. It is MIT licensed, after all. I will converse no further with you.

**Comment by ganigeorgiev** [comment]
Just for info in case someone stumble here, logs were generalized and refactored in `master` and there is now option to control the IP logging from the new log settings (it affects only new logs):
![logs_settings](https://i.imgur.com/MnZadzX.png).

_The changes will be available with the next v0.20.0 release (most likely sometime later today)._

**Comment by cmaas** [comment]
@ganigeorgiev Thanks for implementing and for mentioning it here!
