### ISSUE TITLE
Feauture Request: Remote Collection

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3524]
I want to ask for remote collections, it would be similar to like microsoft has `login.miscosoft.com` and you can login on `*.miscosoft.com`
So in nutshell it would be like:
- access keys/tokens for remote access of PB instances
- when user ask for login get data synced from db.

Also it could allow people to register on one service and use that account on other sites/services using the same DB/collection for auth

**Comment by ganigeorgiev** [comment]
There are no plans for shared PocketBase instances access if that is what you are asking as it will complicate too much the API rules.

**Comment by pietru2004** [comment]
well this is sad... but ok... I was kinda thinking of easy way to handle stuff, like make db just send request to other db... like redirect... and check for auth from that db

**Comment by pietru2004** [comment]
![obraz](https://github.com/pocketbase/pocketbase/assets/51274570/1da4fcf3-ff15-4a46-962d-59a5b489f8c9)
ALso service 1 and 2 are 2 other PB instances that do other tasks... like 1 handles forum and other handles blog posts

**Comment by ganigeorgiev** [comment]
No, sorry. At least for v1 multitenancy is out of the scope for now.

**Comment by pietru2004** [comment]
hm... well I guess best I can do is have bp send http request to auth instance and then get user ID and have it store string for user content
