### ISSUE TITLE
Feature Request: Allow to preserve filenames

### ISSUE THREAD

**Issue by codeit-ninja** [pocketbase/pocketbase#3526]
From the docs

> Each uploaded file will be stored with the original filename (sanitized) and suffixed with a random (10 chars) part (eg. test_52iWbGinWd.png).

Make it optional to add a random (10 chars) part.

Why?
This makes it easier when you have large quantities of files, that are publicly visible to be found just by the original file name instead of having to remember the 10 random characters part.

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/306.
