### ISSUE TITLE
Authstore is always null

### ISSUE THREAD

**Issue by Arinji2** [pocketbase/pocketbase#3527]
![image](https://github.com/pocketbase/pocketbase/assets/87296817/67a59c8d-0e9a-4754-8736-94506c224fb8)
Hiya, so as you can see..  i have a valid token which i load in, but it dosent seem to show anything in the authstore? How do i get the users data?

**Comment by ganigeorgiev** [comment]
Please don't post code as screenshot.

In any case this is not a PocketBase issue. The loaded cookie string is invalid - you are loading only the cookie value, but `loadFromCookie` expects a raw cookie string (aka. name, value and attributes).

If you are going to use a cookie abstraction then you don't need the store cookie helpers.
To load a token into the store, you can call `pb.authStore.save(token, model)`.
