### ISSUE TITLE
Feature Request : Please add SDK support for Kotlin

### ISSUE THREAD

**Issue by rizky201008** [pocketbase/pocketbase#3529]
I developing mobile application with native language using Kotlin but I don't find SDK for Kotlin or Java language so I can't use this for my native mobile app project.

**Comment by ganigeorgiev** [comment]
Sorry, until we stabilize the APIs there are no plans for other official SDKs for now, but user contributions are welcomed.

You can also check https://github.com/pocketbase/pocketbase/discussions/3079 and https://github.com/pocketbase/pocketbase/discussions/391.
