### ISSUE TITLE
Unhandled Exception: Bad state: failed to establish SSE connection

### ISSUE THREAD

**Issue by fabricioguedeshotmail** [pocketbase/pocketbase#3536]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] 
Unhandled Exception: Bad state: failed to establish SSE connection

 I'm not able to open a realtime connection, I'm using Flutter to make the request and it gives me this error, what could be wrong, do I need to release a specific port on the server?

Code Ex.

final pb = PocketBase(
          'https://dominio.com'); // Substitua pela sua chave API do PocketBase

      pb.collection('posts').subscribe('*', (e) {
        print('#######################');
        print(e.action);
        print(e.record);
        print('#######################');
      });

      // Subscribe to changes only in the specified record
      pb.collection('posts').subscribe('jrun6sfuxnr4fup', (e) {
        print(e.action);
        print(e.record);
      });

      // Unsubscribe
      pb.collection('posts').unsubscribe(
          'jrun6sfuxnr4fup'); // remove all 'RECORD_ID' subscriptions
      pb
          .collection('posts')
          .unsubscribe('*'); // remove all '*' topic subscriptions
      pb
          .collection('posts')
          .unsubscribe();

**Comment by ganigeorgiev** [comment]
It is difficult to tell what could be the cause of the error.

Unfortunately I'm not able to reproduce the issue locally (testing with the [example file](https://github.com/pocketbase/dart-sdk/tree/master/example) and Dart 3.1.2 in the console).

If you are testing with Flutter Web please note that the default Dart HTTP client doesn't support streamed responses on the web. For more details and a workaround you can check https://github.com/pocketbase/dart-sdk#limitations.

It could be also a connectivity issue, aka. make sure that the provided url is accessible and you can perform regular requests against it.

If the above doesn't help, please provide more details how you are testing:
- What Flutter platform you are targeting?
- What is your Dart and Flutter versions?
- What is your PocketBase binary version?
- Is the issue reproducable locally?

**Comment by fabricioguedeshotmail** [comment]
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (5 weeks ago) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

/api/realtime
id:3FKHjPAy5IOTcix3gspTtG1jb8QWYwVd86Lff4vE
event:PB_CONNECT
data:{"clientId":"3FKHjPAy5IOTcix3gspTtG1jb8QWYwVd86Lff4vE"}

**Comment by ganigeorgiev** [comment]
But what platform you are targeting?

If it is Web, please check https://github.com/pocketbase/dart-sdk#limitations.

**Comment by ganigeorgiev** [comment]
I've just tested with Flutter Desktop and Web and it works fine for me with PocketBase v0.19.0 and PocketBase Dart SDK 0.15.1.

It is most likely a client-side issue, but there are not enough details to understand what you are running and how are you testing in order to help you debug it.
