### ISSUE TITLE
[feature] Reorder collection fields from admin UI

### ISSUE THREAD

**Issue by paulocoutinhox** [pocketbase/pocketbase#355]
Hi,

Im creating a new collection and put columns/fields on wrong order.

Can you add support for reorder columns/fields from admin UI?

Something like an internal order field to make the form of create new record better.

In my example i new put "title" field on top/first, but is impossible:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/395096/187191202-5abf063a-34c8-44da-8772-b9cdff40fbcd.png">

Thanks.

**Comment by ganigeorgiev** [comment]
Collection fields can be currently reordered via the [Collection's create and  update APIs](https://pocketbase.io/docs/api-collections/) (fields are passed as an indexed array to the `schema` prop).

I'll consider adding fields reordering from the Admin UI in future release (most likely together with https://github.com/pocketbase/pocketbase/issues/259).

**Comment by ganigeorgiev** [comment]
@paulocoutinhox As a workaround, if you don't want to use directly the APIs, you can change the order via the Export/Import UI:
1. Go to "_Settings > Export collections_"
2. Copy the JSON and edit your collection in place (aka. reorder the `schema`  array of your collection)
3. Reimport the edited collection in "_Settings > Import collections_"

**Comment by paulocoutinhox** [comment]
Hi,

Thanks for answer.

I mean in admin interface. It will help me change my current manual process from my app to this web application.

I forgot: Thanks for this great project.

**Comment by ganigeorgiev** [comment]
This is now part of the [v0.8.0-rc1 pre-release](https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1).

**Comment by paulocoutinhox** [comment]
wow...nice...thanks
