### ISSUE TITLE
Feauture Request: Pocketbase Oauth2

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3567]
The https://github.com/pocketbase/pocketbase/issues/3524 in mind.
I want to ask for login Oauth2 using different pocketbase instance.

**Comment by ganigeorgiev** [comment]
If I understand correctly, you want PocketBase to act as an OAuth2 server/provider.

At least for v1 this unfortunately is not planned as it will complicate too much the internals and the way how the tokens are generated and managed (for example, we currently don't even have scopes and the access to a collection is determined based on API rules).

**Comment by pietru2004** [comment]
well this is sad but ok

**Comment by ganigeorgiev** [comment]
I understand your disappointment but PocketBase is primarily a hobby project and I want to avoid expanding its scope too much for now (_see also https://github.com/pocketbase/pocketbase/discussions/3271_).

**Comment by pietru2004** [comment]
Well atm pocketbase is my fav DB as it is simple to use and is mostly idiot prof (I mean the GUI-admin UI).
