### ISSUE TITLE
Support for SQL Check and Constraint bug?

### ISSUE THREAD

**Issue by pauserratgutierrez** [pocketbase/pocketbase#3570]
I tried the Unique Constraint of user1_id and user2_id. It works on one way but not the other. Values don't repeat but do repeat if I add them in reverse order.
![image](https://github.com/pocketbase/pocketbase/assets/73240206/89cd543e-95ce-4d0c-839f-98d975b9569b)
See how I have user1_id and user2_id already:
![image](https://github.com/pocketbase/pocketbase/assets/73240206/72686f41-24ce-4366-b4bb-29e74cf52023)
![image](https://github.com/pocketbase/pocketbase/assets/73240206/5801cb59-9ef6-4868-8009-3f71b28856cd)
And If I try to add it reversed, it adds anyway.
![image](https://github.com/pocketbase/pocketbase/assets/73240206/ad85f97a-e93a-4e05-a7f9-85e5433116c1)
I tried adding unique constraint 2 times with reversed columns in each, but it doesn't work either.
So would be cool to be able to limit also in that way.

For the segond suggestion. How can I make it so user1_id and user2_id can't be the same? Would be cool to have the ability to use CHECKS with operators:
![image](https://github.com/pocketbase/pocketbase/assets/73240206/6734c810-61d0-4722-b2f2-45732d675db4)

![image](https://github.com/pocketbase/pocketbase/assets/73240206/ed8f3ecc-0068-4ae9-8568-2ffd48e7ab3c)

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand the above, but in any case I don't think it is a bug because the unique constraint is maintained on SQLite DB level (note that the order of combined constraints matter).

For now there are no plans to allow `CHECK` constraints. You can handle those on application level - either when [using as framework](https://pocketbase.io/docs/use-as-framework/) OR with an API rule like (`user1_id != user2_id`)

**Comment by ganigeorgiev** [comment]
On second read, if you are trying to create a compound unique constraint of 2 fields, then adding a second index with the reverse order may no be very efficient in terms of storage but should do the job (not that if your collection already has duplicated entries, the index creation will fail).

**Comment by ganigeorgiev** [comment]
While searching to see how other databases handle this, in PostgreSLQ an usually workaround is to use an expression with LEAST/GREATEST.

The alternative in SQLite should be MIN/MAX (I haven't researched it or tested it in details so there could be some edge that I'm probably missing):

```
CREATE UNIQUE INDEX `idx_QjNONm2` ON `chats` (
  MIN(user1_id, user2_id),
  MAX(user1_id, user2_id)
)
``

The main drawback of the above is that because the index fields are now treated as expression, on duplication you'll get a generic API error instead of individual errors for the 2 fields.
