### ISSUE TITLE
Issue with S3 file storage and backups setup

### ISSUE THREAD

**Issue by ovniroto** [pocketbase/pocketbase#3572]
Hi, I'm new using pocketbase, and there is some kind of bug I'm not seeing when setup file storage with S3. I have created an IAM policy with access to GetObject, PutObject and DeleteObject from the bucket I created. I have added that policy to a new IAM user and created the access keys.

I have configured the S3 options in pocketbase with the data:
```
endpoint: s3.eu-west-3.amazonaws.com
bucket: mybucket
region: eu-west-3
access key: *access-key**
secret: *secret-key*
```

When saving, it connects to the bucket, creates a test file that I can see in the bucket, but does not delete it. 

I get this error:
![Error](https://i.imgur.com/5pqCUub.png)

Am I doing something wrong or is it a pocketbase bug? I am using version 0.19.0.

**Comment by ganigeorgiev** [comment]
I've tested earlier the integration with the DigitalOcean and Wasabi S3 offerings and it works fine for me.

I suspect that it is something with the IAM configuration but unfortunately I haven't used AWS in a while and I'm not sure that I'll be able to help you with it.

**Comment by ganigeorgiev** [comment]
_btw. You may also need the `ListBucket` permission._
