### ISSUE TITLE
[Bug] Numbers over 18 in length show incorrectly on the UI dashboard

### ISSUE THREAD

**Issue by TisLeo** [pocketbase/pocketbase#3579]
If I have a `number` type and I insert a number into one of the records that is over the length of 18, the numbers beyond index 18 show up as 0s.

E.g., here's a dummy number:
<img width="651" alt="image" src="https://github.com/pocketbase/pocketbase/assets/88405502/b6b5d637-f7cb-4f3b-97d0-9ff35ea21fd4">

And this is what it shows:
<img width="144" alt="image" src="https://github.com/pocketbase/pocketbase/assets/88405502/33b05686-9945-411d-b8d0-b03970a6c5c3">

If I try again with a larger number:
<img width="654" alt="image" src="https://github.com/pocketbase/pocketbase/assets/88405502/31124477-7a6b-4282-8c9f-aed09d8427d6">

It shows this:
<img width="166" alt="image" src="https://github.com/pocketbase/pocketbase/assets/88405502/da24b00d-c80b-477d-a403-c7f2d1a0b2e9">

I have updated the exe with `./pocketbase update` (newest when writing is 0.19.0).

**Comment by ganigeorgiev** [comment]
It is not a bug.

The max allowed `number` field value is the same as the JS Number, aka. ~2^53-1.

See also https://github.com/pocketbase/pocketbase/issues/1710, https://github.com/pocketbase/pocketbase/discussions/3113 and probably others.

**Comment by TisLeo** [comment]
Oh, thanks. I didn't find anywhere saying this - perhaps you could add the length limit to the website or dashboard so others don't get confused? Unless I am blind.
