### ISSUE TITLE
[Reature proposal] Endpoint supporting Raw SQL queries

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/pocketbase#3585]
Following https://github.com/pocketbase/pocketbase/issues/311,

For deployments with many records, some application migh find huge benefits, on specific cases, in doing Raw SQL queries.

The main example I have in mind is modify records in bulk

I believe a current workaround is doing manually endpoints ?

It might be very complex though, I am not sure

**Comment by ganigeorgiev** [comment]
There are no plans to allow executing raw SQL queries via the web APIs (or at least not for regular users) as it will be very difficult to execute it safely.

Bulk/transactional web APIs are planned and will be implemented sometime in the future as part of #48.

**Comment by MarArMar** [comment]
Ok thanks for the answer
