### ISSUE TITLE
Scheduler frequency, i.e., every 1 or every 15 seconds.

### ISSUE THREAD

**Issue by maietta** [pocketbase/pocketbase#3594]
It seems that the "cron" format does not support every second.

If there is existing support for this, I can't seem to find it documented and my experimentation doesn't yield anything more frequent than once per minute unless I add my own ticker function.

Please advise. Thanks!

**Comment by maietta** [comment]
It would appear that like "cron", there is no option to increase the frequency.

**Comment by seriousm4x** [comment]
I ran into the same problem. Why is this closed? Is there a workaround?

**Comment by ganigeorgiev** [comment]
@seriousm4x While there are existing non-standard cron implementations that support specifying seconds, milliseconds, etc., by default the minimum cron expression granularity is 1 minute (see https://en.wikipedia.org/wiki/Cron).

For finer control you'll have to maintain your own timer/ticker or use a custom scheduling library.
