### ISSUE TITLE
Feature Request: Delete After/Delete Event

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3601]
I want to ask for ability to configure in collection after how much time are items in collection cleared, how much time after creation or mayby after how many accesses to the record should it be removed
Related: https://github.com/pocketbase/pocketbase/discussions/3568

**Comment by stephdin** [comment]
You could extend PocketBase with Go/JavaScript and schedule a job, that runs e.g. every hour and deletes records older than a specific amount of time (https://pocketbase.io/docs/js-jobs-scheduling/). You should also be able to track the reads of a record with event hooks and using that for deletion (https://pocketbase.io/docs/js-event-hooks/#onrecordviewrequest)

**Comment by pietru2004** [comment]
IK, but I fought it would be good to have setting for that in collection settings

**Comment by ganigeorgiev** [comment]
For now this remains out of the scope as it would be difficult to generalize the criteria of delete/cleanup operation (see for example https://github.com/pocketbase/pocketbase/discussions/4610 where the user wants only the "pending" records to be deleted after a specific amount of time) and this is better left to the users to handle on their own.
