### ISSUE TITLE
Why I can't find this Email on DB

### ISSUE THREAD

**Issue by serkan-bayram** [pocketbase/pocketbase#3603]
```js
  // Create pocketbase instance
  const pb = new PocketBase("http://127.0.0.1:8090");

  // Auth as admin to create user
  await pb.admins.authWithPassword(
    process.env.dbUsername,
    process.env.dbPassword
  );

  // First, we check is this user already signed up
  try {
    const fetchUser = await pb
      .collection("users")
      .getFirstListItem(`email="9962755@ogrenci.bilecik.edu.tr"`);

    if (fetchUser) {
      return { ok: false, message: "Bu kullanıcı zaten kayıtlı." };
    }
  } catch (error) {
    console.log("Error on fetchUser:", error);
```

![image](https://github.com/pocketbase/pocketbase/assets/68502470/4ad91fcc-a8e7-4125-bd43-ae7a97769918)
![image](https://github.com/pocketbase/pocketbase/assets/68502470/1281d37f-a434-4328-8e74-821b8f4e5060)

**Comment by ganigeorgiev** [comment]
You can search users by email only if the `emailVisibility` flag for the specific user is set to `true` (aka. the "Public: on/off" email toggle in the Admin UI).

**Comment by ganigeorgiev** [comment]
On second read, you are executing it as admin so the API rule shouldn't matter.
Double check that there are no typos/spaces when searching for the email.

It works fine for me when testing on the live demo (pocketbase.io) with a filter `email="test2@example.com"`.

**Comment by serkan-bayram** [comment]
Somehow it got fixed after a while, I'll try to use that --debug thing if it happens again, thanks.
