### ISSUE TITLE
Feature Request: Enforce Case-Insensitive Email Matching for User Authentication

### ISSUE THREAD

**Issue by Rfluegel1** [pocketbase/pocketbase#3604]
I have come across an inconsistency in the authentication process when using email addresses. Currently, the system requires an exact case match for email addresses during authentication, leading to failed login attempts if the case does not match exactly. This behavior contrasts with the case-insensitive handling of usernames as seen in [this past request](https://github.com/pocketbase/pocketbase/issues/1602).

Email is [documented](https://pocketbase.io/docs/authentication/) as an alternative to username for authentication purposes. However, it fails to authenticate when the case of the email string does not match exactly, as demonstrated below:

1. Authenticates
```javascript
await pb.collection('users').authWithPassword('test.user@domain.dev', '12345678');
``` 
2. Returns invalid
```javascript
await pb.collection('users').authWithPassword('TEST.USER@domain.dev', '12345678');
```

For consistency and improved user experience, adopting a case-insensitive behavior for email addresses, akin to the handling of usernames, would be beneficial. This change could potentially reduce user login issues and support requests, thereby improving overall user satisfaction.

Here are a few examples illustrating the benefits of this feature:

1. Reduced user friction during the login process, particularly for new users unfamiliar with the case sensitivity requirement.
2. Consistent behavior between email and username authentication, aligning with common practices in other platforms and meeting user expectations.

---

I understand there might be technical or security considerations impacting this feature's feasibility. However, I am keen to learn if there are specific reasons for the current case-sensitive email handling, and I am open to discussing alternative solutions that achieve the same user-friendly outcome.

I have checked the issue tracker to the best of my ability and hope this isn't a duplicate request. Thank you in advance for considering this feature request and I am looking forward to any feedback or further discussion on this topic.

---

P.S. This body was mostly produced by chatGPT after clarifying my thoughts on this issue to improve the readability. Cheers

**Comment by ganigeorgiev** [comment]
This deliberate and was discussed in https://github.com/pocketbase/pocketbase/discussions/756.
