### ISSUE TITLE
Issue with Inline Image Upload in TinyMCE: Residual Data Retention

### ISSUE THREAD

**Issue by korosu** [pocketbase/pocketbase#3605]
![4.png](https://s2.loli.net/2023/10/26/D4RG5mH9h8pWVOa.png)

There seems to be an issue with how images are being handled within TinyMCE when using the Image/Inline feature. Upon uploading an image, it appears that the image file gets written somewhere within the data.db/data.db-wal file. However, after deleting the corresponding record, it's observed that the file size of data.db/data.db-wal remains unchanged. Even delete the entire collection didn't yield any results, indicating that the data isn’t being removed as expected.

**Comment by ganigeorgiev** [comment]
The "Inline" option embeds the image as base64 text, aka. it will be part of your record db data.
When deleting entries from the database SQLite by default doesn't free the claimed disk space for optimization purposes to minimize allocations and frequent changes in the internal tree structure (at the end it is expected that this space will be filled again with future entries).

If you want to force releasing the disk space you can run `VACUUM` eg. with the sqlite3 cli tool:
```sh
sqlite3 ./pb_data/data.db 'VACUUM'
```

**Comment by korosu** [comment]
Thank you for your explanation.
