### ISSUE TITLE
Feauture Request: multi templates under 1 slot

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3626]
Refered to https://github.com/pocketbase/pocketbase/discussions/3618

I want to ask to be able to bind many blocks under 1 name_space

`layout.html`
```
<body>
  {{block "content" .}}
    This is the default body.
  {{end}}
</body>
```

`Block1.html`
```
{{define "content"}}
  Block 1
{{end}}
```

`Block2.html`
```
{{define "content"}}
  Block 2
{{end}}
```

Basically if there are 2 blocks with the same defined name allow them to be placed under defined space in layout above.
As far as I checked it always places 1 block and does not add more than that.

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what is the desired behavior but there are no plans to extend or change the existing [Go templates syntax](https://developer.hashicorp.com/nomad/tutorials/templates/go-template-syntax).

If you are extending PocketBase with Go, you are free to use whatever template engine you want.

**Comment by ganigeorgiev** [comment]
If you want to render both `Block1.html` and `Block2.html` in the same block one after another, then you can render them as plain string separately (aka. invoke `render(data)` for each one) and then combine them in an array of strings that you can pass into the main template.

This will allow you to render their content in a for loop as raw html calling `{{.item|raw}}` for each entry.

**Comment by pietru2004** [comment]
ok

**Comment by pietru2004** [comment]
hm if I can ask is there no way to have go add multiple blocks under one slot?
I mean I see what you mean with calling `{{.item|raw}}`, but still that might be limiting bit cause
I want to have base page that can have multiple layout and each layout can have multiple blocks.

Unless I instead of passing block data to layouts pass already rendered blocks and then render layouts and pass rendered layouts to base page... hm...
