### ISSUE TITLE
Type error after starting pocketbase

### ISSUE THREAD

**Issue by Laecherlich** [pocketbase/pocketbase#3627]
Hey, after running the `serve` command the `types.d.ts `file is created. This file has a type error in line **17706**. Can someone please have a look and if necessary fix it?

![Screenshot 2023-10-28 at 13 45 55](https://github.com/pocketbase/pocketbase/assets/42747870/960cfc8c-c271-4306-ac66-3b198df06348)

**Comment by ganigeorgiev** [comment]
I'll consider updating the generated types with the next release, but this file is not required for PocketBase to work and you can ignore it.

**Comment by Laecherlich** [comment]
Okay thanks :) I am using a TypedPocketBase and when building the compiler complained, that the generated types have an error.

**Comment by ganigeorgiev** [comment]
I don't know what `TypedPocketBase` is but the above file is intended to be used only by your editors LSP when working with JS `pb_hooks` and when referenced manually in your hook file as shown in https://pocketbase.io/docs/js-overview/#typescript-declarations-and-code-completion.

**Comment by Laecherlich** [comment]
I meant this from the `js-skd` 

[TypedPocketBase](https://github.com/pocketbase/js-sdk#specify-typescript-definitions)

**Comment by ganigeorgiev** [comment]
Again, the above file has no relation to the JS SDK or your own custom types. It is used only as ambient TS declarations for the JS `pb_hooks`.

If for some reason your TS config is complaining about it, you can try to exclude it (probably you have a wildcard pattern somewhere defined that will traverse all directoris with to look for `.ts/.d.ts` files).

**Comment by Laecherlich** [comment]
Yes excluding the files worked, thanks

**Comment by ganigeorgiev** [comment]
The generated TS file was updated in `master` and will be available with the next minor release sometime later next week.

But again, the above file can be safely ignored since it is just a helper to provide ambient TS declarations (eg. autocomplete, docs on hover, etc.) when [PocketBase is used as framework](https://pocketbase.io/docs/use-as-framework/) with the [JS `pb_hooks`](https://pocketbase.io/docs/js-overview/).
