### ISSUE TITLE
[question] How to get the thumb image?

### ISSUE THREAD

**Issue by paulocoutinhox** [pocketbase/pocketbase#363]
Hi,

Im using your API to get post records:
https://pocketbase.io/api/collections/posts/records

It come with two images:
`"featuredImages":["XPHNJ1ikAoVAgDaMMIXCbAio00irrmIY.jpg","Jgihz6urldOM1ve3EyXbHWYaVqVh0hkK.jpg"]`

Three questions:
1 - How to get full image URL? We need concat with what? 
2 - There is any way to get full absolute image URL?
3 - How i can get thumb url? Because on form there is a thumb of 100x200

Thanks.

**Comment by ganigeorgiev** [comment]
You could check https://pocketbase.io/docs/files-handling/#file-url (_the documentation will be improved in the near future_).

I'll close the issue for now since the above link should answer your 3 questions, but if you are still having difficulties making it work, feel free to comment (or open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/categories/q-a)).

**Comment by paulocoutinhox** [comment]
Hi, nice. It works:
https://pocketbase.io/api/files/posts/UP06yiygImYTMCI/XPHNJ1ikAoVAgDaMMIXCbAio00irrmIY.jpg?thumb=100x200

<img width="135" alt="image" src="https://user-images.githubusercontent.com/395096/188200411-b73a3d82-d252-481a-be1b-aed19a0c6c3b.png">

As a fallback, it thumb size is wrong, it return the original image:
https://pocketbase.io/api/files/posts/UP06yiygImYTMCI/XPHNJ1ikAoVAgDaMMIXCbAio00irrmIY.jpg?thumb=100x123

But is strange that thumb 100x100 is not registered on admin but it works:
https://pocketbase.io/api/files/posts/UP06yiygImYTMCI/XPHNJ1ikAoVAgDaMMIXCbAio00irrmIY.jpg?thumb=100x100

<img width="279" alt="image" src="https://user-images.githubusercontent.com/395096/188200774-1e5c3eb5-f4ac-4f6b-a68f-6ea20dd3a479.png">


<img width="126" alt="image" src="https://user-images.githubusercontent.com/395096/188200693-21f32945-40ca-4bf0-a5df-a0c032f87eee.png">

**Comment by ganigeorgiev** [comment]
> But is strange that thumb 100x100 is not registered on admin but it works:

100x100 is a system thumb size and it is always available (it is listed in the tooltip on hover on the info icon near the Thumb Sizes label).

**Comment by paulocoutinhox** [comment]
Thanks, I tested this size by chance.
