### ISSUE TITLE
Unable to delete or modify empty collection

### ISSUE THREAD

**Issue by mrpn** [pocketbase/pocketbase#3642]
Hello, I mistakenly created an empty collection using pb_hooks and now I can't delete or modify it. Despite trying several methods, I've been unable to make changes. Could you help me on how to delete this collection? Further details are provided below.

### Collection details 
from Settings/Export:
```js
    {
        "id": "bly48a4tg23teep",
        "name": "",
        "type": "base",
        "system": false,
        "schema": [],
        "indexes": [],
        "listRule": null,
        "viewRule": null,
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    },
```

Migration file from pb_migrations folder:
`1698583110_created_.js`
```js
migrate((db) => {
  const collection = new Collection({
    "id": "bly48a4tg23teep",
    "created": "2023-10-29 12:38:30.405Z",
    "updated": "2023-10-29 12:38:30.405Z",
    "name": "",
    "type": "base",
    "system": false,
    "schema": [],
    "indexes": [],
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "options": {}
  });

  return Dao(db).saveCollection(collection);
}, (db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("bly48a4tg23teep");

  return dao.deleteCollection(collection);
})
```

### Delete methods I tried: 
First method: /pb_hooks/delete_one.pb.js
```js 
onAfterBootstrap((e) => {
    const collectionz = $app.dao().findCollectionByNameOrId("bly48a4tg23teep")
    $app.dao().deleteCollection(collectionz)
});
```
Results `2023/10/29 16:45:37 GoError: SQL logic error: unrecognized token: "{" (1) at reflect.methodValueCall (native)`

------
Second method: HTTP Delete Request for: `http://127.0.0.1:8090/api/collections/bly48a4tg23teep`:
```js
{"code":400,"message":"Failed to delete collection due to existing dependency.","data":{}}
```

Log from the web interface:
```
ID	3lnyu62yopgcxy7
Status	400
Method	DELETE
Auth	admin
URL	/api/collections/bly48a4tg23teep
Referer	N/A
Remote IP	127.0.0.1
User IP	127.0.0.1
UserAgent	HTTPie
Meta	
{
  "errorDetails": "SQL logic error: unrecognized token: \"{\" (1)",
  "errorMessage": "Failed to delete collection due to existing dependency."
}
Created	
2023-10-29
16:29:38 UTC
```

Edit: Just to note, I can't add fields, change the collection name, or delete through the web interface either. The only action I can perform is adding records.

**Comment by ganigeorgiev** [comment]
You should be able to delete the invalid collection with raw SQL, aka. something like:

```js
// just in case, make sure to have a backup of your pb_data before running it
$app.dao().db()
    .newQuery("DELETE FROM _collections WHERE id="bly48a4tg23teep"")
    .execute()
```

If the above doesn't help, feel free to let me know and I'll try to investigate it in more details.

**Comment by ganigeorgiev** [comment]
_I've added in my todo to consider adding a constraint on db level in the future to prevent the insertion of broken collection entries._

**Comment by mrpn** [comment]
Thanks for the quick response. Your suggestion worked perfectly.
