### ISSUE TITLE
sort by json field in collection search bar

### ISSUE THREAD

**Issue by HEAVYPOLY** [pocketbase/pocketbase#3650]
is it possible to sort by json field on the pocketbase collection search box?  For example sort by stats.canvasCount:
<img width="1278" alt="image" src="https://github.com/pocketbase/pocketbase/assets/24432677/b72e729f-dc98-43aa-a6d7-d98aa1e58423">

**Comment by ganigeorgiev** [comment]
No, it is not possible at the moment and I think it will clutter the Admin UI.

The use case for this in my opinion is not that common/generic and at least for now remains out of the scope.

**Comment by HEAVYPOLY** [comment]
ok, thank you for the quick response.
