### ISSUE TITLE
Access record Id after insertion

### ISSUE THREAD

**Issue by Clovis-krz** [pocketbase/pocketbase#3676]
It would be nice to be able to get the Id of a record after submitting the transaction. When i tried like below, i got an empty string
```
import (
    "github.com/pocketbase/pocketbase/forms"
    "github.com/pocketbase/pocketbase/models"
)

collection, err := app.Dao().FindCollectionByNameOrId("articles")
if err != nil {
    return err
}

record := models.NewRecord(collection)

form := forms.NewRecordUpsert(app, record)

form.LoadData(map[string]any{
    "title": "Lorem ipsum",
    "active": true,
    "someOtherField": 123,
})

if err := form.Submit(); err != nil {
    return err
}
print(form.Id)
```

**Comment by ganigeorgiev** [comment]
After successful `form.Submit()` it should be populated in the `record` model, aka. `record.Id`.

**Comment by Clovis-krz** [comment]
Oh ! I didn't realize that I was trying to do it from the form and not the record. Makes sense thank you very much it works great !
