### ISSUE TITLE
Feature Request: add linkeble Boolean values

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/pocketbase#3678]
I request a feature that lets you link any field to a Boolean field, if the Boolean is true, it lets us put data inside the field.
if not it will automatically set the field's data to non or empty.
Boolean fields linked to other Boolean fields will have the same data value as the linked one.
it may sound confusing, because it is.
it will work like relations in the Ui and Mabe you can make them linked accros collections.

**Comment by ganigeorgiev** [comment]
This seems similar to https://github.com/pocketbase/pocketbase/issues/3454.

I may revisit the request sometime in the future as something similar was requested before, but for now this remains out of scope for v1 as it could be ambiguous (eg. do the "disabled" fields validation need to apply?) and the same behavior could be more-less accomplished client-side.
