### ISSUE TITLE
FEATURE REQUEST: It's hard to understand what is happening in a migration file

### ISSUE THREAD

**Issue by babakfp** [pocketbase/pocketbase#3682]
Hi

I was looking into this migration file, to understand what kind of things I changed...

```js
/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const dao = new Dao(db)
  const collection = dao.findCollectionByNameOrId("bf6zd9b9bsb1zo5")

  collection.listRule = null
  collection.viewRule = null
  collection.createRule = null
  collection.updateRule = null
  collection.deleteRule = null

  return dao.saveCollection(collection)
}, (db) => {
  const dao = new Dao(db)
  const collection = dao.findCollectionByNameOrId("bf6zd9b9bsb1zo5")

  collection.listRule = ""
  collection.viewRule = ""
  collection.createRule = ""
  collection.updateRule = ""
  collection.deleteRule = ""

  return dao.saveCollection(collection)
})
```

I can see that some things are happening to a collection, but I don't know what collection these things are happening to.

**Proposed solution:**

I think simply adding a comment like this could solve the issue.

```js
// Collection Name: `users`
const collection = dao.findCollectionByNameOrId("bf6zd9b9bsb1zo5")
```

We can also do the same to explain the difference between the first and the second functions used inside the `migrate` function.

That's all.
thanks.

**Comment by ganigeorgiev** [comment]
I don't think this is necessary as the collection name should be already part of the autogenerated migration file.

**Comment by babakfp** [comment]
> I don't think this is necessary as the collection name should be already part of the autogenerated migration file.

I just noticed that 👍
