### ISSUE TITLE
Feature Request: Disable User Sign Up including Email and Password

### ISSUE THREAD

**Issue by c-nv-s** [pocketbase/pocketbase#3683]
In some use cases it is desired to disable/prevent user sign up and only allow admins to invite new users to the application ( think granting access to beta users of your production application, or an application for an exclusive user group )

it would be useful to be able to have a config switch that prevents anybody from creating an account even to the ``/api/collections/users/auth-with-password`` endpoint.

**Comment by ganigeorgiev** [comment]
You should be able to do that already by "locking" the auth collection Create API rule and set it to "Admin only".
