### ISSUE TITLE
Feature request: Hyphens in usernames

### ISSUE THREAD

**Issue by j0sh** [pocketbase/pocketbase#3697]
Hello,

It seems that hyphens are not allowed in usernames according to this regex:

https://github.com/pocketbase/pocketbase/blob/f4f3724b7a8bb6d84f2bd8682dff0dbe784cf49f/forms/record_upsert.go#L28

As a result, OAuth usernames that contain a hyphen end up with auto-assigned names like `<collection-name>_<random-number>`.

Is there a reason for this restriction, or could the regex be loosened up to allow for hyphens? Something like this should work:

```
var usernameRegex = regexp.MustCompile(`^[\w][\w\.\-]*$`)
```

Will be happy to send in a PR unless there is a reason for not allowing hyphens.

**Comment by ganigeorgiev** [comment]
It is just a requirement from my other open source project (Presentator).

The `username` and other system fields will be refactored in the future to allow customizations (see https://github.com/pocketbase/pocketbase/discussions/2752, https://github.com/pocketbase/pocketbase/discussions/2425#discussioncomment-5818276), but for now this is left aside.

I'll consider making an exception for the hyphen in the next release.

**Comment by ganigeorgiev** [comment]
The regex pattern was updated in [v0.19.4](https://github.com/pocketbase/pocketbase/releases/tag/v0.19.4).
