### ISSUE TITLE
Feature request: Resizeable textarea of TinyMCE 'source code'

### ISSUE THREAD

**Issue by kerimovok** [pocketbase/pocketbase#3715]
Small request for better experience while using TinyMCE
![soure code view](https://github.com/pocketbase/pocketbase/assets/136202877/b70a30f4-c9d8-45f1-be41-4b3f135e4259)

After deleting 'resize: none'
![style change ](https://github.com/pocketbase/pocketbase/assets/136202877/cbc876a5-d3bc-49cd-9ea3-c4b0b614631a)

OR add rows count
![rows count added](https://github.com/pocketbase/pocketbase/assets/136202877/89f5dc9b-c6bf-49d3-85b4-5b6c94054460)

**Comment by ganigeorgiev** [comment]
Hm, this seems to be a conflicting style with the TinyMCE skin css.

I'll consider fixing it with the next release.

**Comment by kerimovok** [comment]
Yeah, it is, thank you!
![image](https://github.com/pocketbase/pocketbase/assets/136202877/5c921977-2a08-48f1-8376-799054b4f2e1)

**Comment by ganigeorgiev** [comment]
It is still a PocketBase issue though as the skin.css is adapted from https://skin.tiny.cloud/t5/.

**Comment by ganigeorgiev** [comment]
I've submitted a small overwrite for the skin.css to behave the same as the default TinyMCE 6 theme.
The "fix" will be available with the next minor or v0.20.0 PocketBase release.
