### ISSUE TITLE
Limit scope for oidc - Exclude email from scope for steam openid

### ISSUE THREAD

**Issue by AlfredEVOL** [pocketbase/pocketbase#3727]
I am trying to setup OpenID connect for steam.

Steam doesnt provide and OpenID Connect Provider so I am using this [project](https://github.com/byo-software/steam-openid-connect-provider)

I try to connect and authenticate but get an error regarding the scope for the request, with email not present.

You can see the configuration [here](https://openid.steam.algata.in/.well-known/openid-configuration)

Is there a way to exclude email from the scope. Also, not sure if email scope is required in which case I guess this doesn't make sense.

Thanks

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what actually is the issue but you can request any scope when opening the provider sign-in url (_note that the url can be even constructed manually, it is not PocketBase related and `listAuthMethods()` is just a helper_).

If you use the "all-in-one" flow with the JS SDK, conveniently this can be done with the `scopes` option:

```js
const authData = await pb.collection("users").authWithOAuth2({
    provider: "oidc",
    scopes: "anything",
})
```

Also note that even if the provider doesn't return an email, you still may get an error when signing-up depending on whether for your auth collection the "Always require email" toggle is enabled (_can be changed from the collection options in the Admin UI_).

If that doesn't help, please consider filing a Q&A discussion with more details about your setup and ideally a code sample with your auth code.
