### ISSUE TITLE
Suggestion: use gchalk for colored console output

### ISSUE THREAD

**Issue by wdscxsj** [pocketbase/pocketbase#375]
On Windows 10, v0.5.2 doesn't look perfectly nice with the colored output.

In cmd.exe:

![Screenshot167](https://user-images.githubusercontent.com/863369/188126450-5ba19c0d-3285-4996-a5ae-2871a1adefd7.png)

In [ConEmu](https://github.com/Maximus5/ConEmu):

![Screenshot168](https://user-images.githubusercontent.com/863369/188126470-e46c06f4-9eb6-4c61-8960-e596a268faaf.png)

It does work well in the new [Windows Terminal](https://github.com/microsoft/terminal).

AFAIK [`jwalton/gchalk`](https://github.com/jwalton/gchalk) has a much better cross-platform support than `fatih/color`. The conversion is quite straightforward.

**Comment by ganigeorgiev** [comment]
Hm, thanks for reporting it. I'll have it in mind for the next release.

I prefer `fatih/color` because it is very compact (just a single file) and very easy to use. It should support Windows as well, but I'll have to probably replace the default stdout writer with `color.Output`.

**Comment by ganigeorgiev** [comment]
This should be fixed in master (I've tested it only with the default Windows 10 cmd).
The fixes will be available with the next bugfix/feature release.
