### ISSUE TITLE
I am starting to get `Failed to apply migration 1640988000_init.go: attempt to write a readonly database` suddenly

### ISSUE THREAD

**Issue by shahidcodes** [pocketbase/pocketbase#3761]
I am getting `Failed to apply migration 1640988000_init.go: attempt to write a readonly database`.

App was running properly. I had some issues with generated migrated so decided to remove everything, pb_data, and setup again. But after removing pb_data I am getting above error, not able to figure out what went wrong.

**Comment by ganigeorgiev** [comment]
I'm not sure how to help you debug but I don't think it is PocketBase related.

Double check that process user has read and write access to the `pb_data` directory.
To rule out other conflicting service, make sure that PocketBase is the only process that interacts with the database (aka. if you have Litestream, marmot, etc. try to disable them).

If you are not able to find the culprit, please create a **minimal** reproducible repo and I'll have a look.

**Comment by josep81** [comment]
I had the same problem when I delete all the rows from the `_migrations` table. Directly editing data.db.

I fixed it by adding a row with:

`1640988000_init.go,1640988000`
