### ISSUE TITLE
Can I use PocketBase using any backend solution of any programming language

### ISSUE THREAD

**Issue by MehdiLahlouMimi00** [pocketbase/pocketbase#3768]
Recently I wanted to use Pocketbase with the Rust Rocket library, is it possible?

**Comment by ganigeorgiev** [comment]
I'm not familiar with the mentioned library but you can interact with PocketBase via its web APIs - https://pocketbase.io/docs/api-records/.

Currently we have official SDKS only for JS and Dart.
SDKs for other languages for now are on hold at least until stable v1.0.0 release.
