### ISSUE TITLE
Some fields of AuthRecord seems to be available only when I make a clone of the object

### ISSUE THREAD

**Issue by square-foot** [pocketbase/pocketbase#3781]
Hi
I am new to pocketbase -- so I may be making a fundamental error here. Pardon me

I gave an extra field called "role" in the standard "users" collection. 

I noticed that in a route, I am unable to retrieve it directly 

```

....
  const info   = $apis.requestInfo(c)
  //info.authRecord.role  is null

  const authRecordClone= JSON.parse(JSON.stringify(info.authRecord))
  //now authRecordClone.role has the correct value 

```

Is this the normal behaviour or is it something I did not understand?

**Comment by ganigeorgiev** [comment]
`info.authRecord` is not a plain JavaScript object (that is what `JSON.parse(JSON.stringify(...))` will return).

To access and modify the record fields you can check https://pocketbase.io/docs/js-records/#getset-record-fields.
