### ISSUE TITLE
[feature request] json field maxLength limit like text maxLength limit

### ISSUE THREAD

**Issue by shynome** [pocketbase/pocketbase#3790]

**Comment by ganigeorgiev** [comment]
Without details what would be the use case for this and how `maxLength` is expected to work (eg. _based on what should be applied - the minified json version or on the raw serialized data?_), for now this remains out of the scope for v1.

It is possible the desired functionality to be handled eventually as part of https://github.com/pocketbase/pocketbase/issues/1154, but for now remains a low priority.

**Comment by shynome** [comment]
When allow user change JSONTypeField, user can upload too big json string
I also think JSON schema is better

**Comment by shynome** [comment]
When allow user change JSONTypeField, user can upload too big json string
I also think JSON schema is better

**Comment by ganigeorgiev** [comment]
_Just for info in case someone stumble here - a new `MaxSize` `json` field option was added in the develop branch to limit the max stored json data in the db (in terms of raw bytes). It will be available with the next v0.20.0 release soon. Option to limit the length of a json string prop and other json validations will be handled eventually in the future as part of #1154._
