### ISSUE TITLE
Proposal: mobile/responsive layout for admin UI

### ISSUE THREAD

**Issue by josip** [pocketbase/pocketbase#3803]
I would like to propose inclusion of a more responsive layout for the admin UI. With a mobile-friendly layout, people would be able to make quick changes or check up on logs on the go. Additionally even on desktops, this would allow the admin UI to be used more comfortably in split-screen type of a setup.

I have a [prototype](https://github.com/josip/pocketbase/commit/55b7737353adc7c8cd79ba26b2302590a3cb3441) working, but would like to consult if this is something you'd like to merge at all at this time, and if so, how would you like to approach it. Here's a quick demo:

https://github.com/pocketbase/pocketbase/assets/11433/6ccd32cf-a0d7-4a7f-9b5f-5b50a34ddeb8

Approach I've taken was to keep changes CSS-only, at the cost hiding some functionalities, notably collection search and section headers in the sidebar.

The changes were relatively small and have focused only on the sidebar, the rest of the UI was already well adopted for small screens.

**Comment by ganigeorgiev** [comment]
Thank you for the prototype link.

Something similar was suggested in https://github.com/pocketbase/pocketbase/issues/19 and https://github.com/pocketbase/pocketbase/pull/1867, but until we reach a more stable release, this for now remains out of the roadmap as it will be difficult to maintain while still making UI updates and I personally think that it will require major code changes to make it actually usable on mobile.

Also note that the Admin UI most likely will be refactored anyway sometime in the future as part of the planned plugins support (https://github.com/pocketbase/pocketbase/issues/898), but for now stabilizing the exposed Go APIs and improving the docs are with higher priority.

I'll close the issue for now but later we can revisit this and the other proposals.
