### ISSUE TITLE
MFA support

### ISSUE THREAD

**Issue by raizdev** [pocketbase/pocketbase#3840]
Any plans for adding MFA support? TOTP for example with google authenticator?

**Comment by ganigeorgiev** [comment]
I'm not planning working on TOTP for now as too many other tasks has accumulated, but email-code/otp for the admin auth exists in my todo.

In general this necessary need to be part of the core package and can exists as server-side Go or JS plugin.

See also https://github.com/pocketbase/pocketbase/discussions/1208.

**Comment by raizdev** [comment]
I would try to create JS plugin, thanks
