### ISSUE TITLE
Am I doing something wrong or is PocketHost down?

### ISSUE THREAD

**Issue by Jadi255** [pocketbase/pocketbase#3844]
Trying to access my instance at $instanceName.pockethost.io/_/, it returns "The requested resource wasn't found."

Here's my logs from Pockethost dashboard for today: 
2023-11-30T06:37:54.694Z stdout
Instance stopped
2023-11-30T06:37:54.730Z stdout
Starting instance
2023-11-30T06:37:55.494Z stdout
2023/11/30 06:37:55 Server started at http://0.0.0.0:8090
2023-11-30T06:37:55.494Z stdout
├─ REST API: http://0.0.0.0:8090/api/
2023-11-30T06:37:55.494Z stdout
└─ Admin UI: http://0.0.0.0:8090/_/

Running version 0.19.*

Any reason why the instance has been stopped?

**Comment by ganigeorgiev** [comment]
PocketHost is not directly related to PocketBase and I can't help you with it.

Note that everyone is free to offer PocketBase as a service if they want to and PocketHost is just one such example by @benallfree.

You can contact PocketHost and submit the report to their repo or discord channel - https://github.com/pockethost/pockethost/discussions.
