### ISSUE TITLE
Feature Request: Database hash for syncing data with client

### ISSUE THREAD

**Issue by RayyanNafees** [pocketbase/pocketbase#3857]
Can there be an entire database' hash string which the client can check if new data has been added to the pocketbase database ?

Every new Entry to the database will generate the new hash string (which can be treated like a version, much like git commits) for the data in the db

An endpoint needs to be maid available from pocketbase API that returns the database hash string to the client

The client will store the hash & the pocketbase data in the localStorage and when the user arrives at the client, it just displays the data

**to check if new data has been added to its pocketbase database, the client fetches the new hash from the Pocketbase Endpoint and if it founds a hash string different from what is stored in the client, ONLY then it refetches the new data for _syncing_**

**Comment by ganigeorgiev** [comment]
I don't fully understand the description nor the use case for this, but at least until we stabilizes the v1 APIs there no plans for now to add client<->server db syncing out of the box if that's what you are trying to do.

**Comment by RayyanNafees** [comment]
# Requirement
An endpoint that returns a hash like md5 of the database file (Since the db is sqlite, all of it is stored in a single file) to track for any additional changes to the database

# Use Case
For conditionally fetching content in offline-first apps, by checking if the md5 hash they have stored of the database is same as the md5 hash generated by Pocketbase of the sqlite db file, much like a "version" of the database (not version of pocketbase)

## Procedure
- Whenever Data is fetched from Pocketbase server, the client also stores its md5 hash with it from the pocketbase endpoint
- The client being offline-first, stores the data locally along with the md5 hash to check for db changes on the cloud later
- Whenever a user visits the client, it calls the endpoint to check if the md5 hash it has stored is same as the md5 hash generated by pocketbase of its db file (i.e, Data it has stored is same as the data stored in the pocketbase server)
- If both the md5 hashes match, it doesn't refetch the data for syncing
- if it gets a different md5 hash from the server from what is stored in the client (the DB file has changed in pocketbase due to new database entries or deletions or updates, and thus generated a different md5 hash) , then it refetches the data from Pocketbase and stores the new data offline and also storing the new md5 hash in the client for future db syncing
