### ISSUE TITLE
Can't access record fields, only id

### ISSUE THREAD

**Issue by 0x6775737461766f** [pocketbase/pocketbase#3878]
So, when i want to search for a recor for ex

`const record = $app.dao().findFirstRecordByData("users", "id", "iw173nymwtka2s9")
 console.log(record);
console.log(JSON.stringify(record));
console.log(typeof record);`

This is the output:

`2023/12/04 14:55:22 [object Object]
2023/12/04 14:55:22 {"avatar":"","collectionId":"_pb_users_auth_","collectionName":"users","created":"2023-12-04 17:37:11.424Z","emailVisibility":false,"id":"iw173nymwtka2s9","name":"USER","updated":"2023-12-04 17:37:11.424Z","username":"teste","verified":true}
2023/12/04 14:55:22 object`

But i can't access anything other than the record.id, if i try to access record.avatar, or record.name etc, it just goes blank, does anyone have a solution for me?

**Comment by ganigeorgiev** [comment]
The returned `record` is not a POJO.

For accessing the record data you'll have to use the designated getter and setters, eg. `record.get("yourField")`. List with commonly used methods and helpers you can find in https://pocketbase.io/docs/js-records/#getset-record-fields.
