### ISSUE TITLE
Feature Request: iOS Swift SDK

### ISSUE THREAD

**Issue by lalkrishna** [pocketbase/pocketbase#3880]
Start new project for  iOS Swift SDK

**Comment by ganigeorgiev** [comment]
Until we stabilize the v1 APIs there are no plans for other official SDKs for now, but user contributions are welcomed.

You can always interact with PocketBase directly using the available web APIs in https://pocketbase.io/docs/api-records/.

See also https://github.com/pocketbase/pocketbase/discussions/391.
