### ISSUE TITLE
Bug: Unable to edit collections from the UI

### ISSUE THREAD

**Issue by bogdanrbucur** [pocketbase/pocketbase#3881]
Noticed I am unable to edit any collections from the UI, the edit button is missing for all collections. I can't tell for sure when this happened, as I just noticed today when I wanted to edit the API permissions.

Running Pocketbase Windows x64 version 0.19.4 upgraded from 0.19.0. Have been using since 0.16 without issue.

![image](https://github.com/pocketbase/pocketbase/assets/84713004/26e413d7-220c-4447-90fd-1b87b724ee04)

I am the admin. I have tried creating and logging in with different admins, stopping and restarting Pocketbase, running in incognito, no luck.

![image](https://github.com/pocketbase/pocketbase/assets/84713004/c04f195c-84f3-42d9-abb1-fcb66e8b3f41)

I also don't see the option to add a new collection, I can't even remember where it was. It's like I'm not the admin anymore?

**Comment by ganigeorgiev** [comment]
I don't think it is a bug or at least I don't know how to reproduce it.

Make sure that you didn't enable the "Hide collection create and edit controls" toggle in the _Admin UI > Settings > Application_ section.

If that's not the case please open the browser inspect tool and check if there is a JS error.
You can also start PocketBase with `--debug` and see if there is anything printed in the console.

**Comment by bogdanrbucur** [comment]
> Make sure that you didn't enable the "Hide collection create and edit controls" toggle in the Admin UI > Settings > Application section.

Well this is embarrassing. If someone as stupid as me will ever be born, at least this might help them. Cheers.
