### ISSUE TITLE
how to protect some fields like mobile in user collection

### ISSUE THREAD

**Issue by KingKongxyz** [pocketbase/pocketbase#3884]
it's a very simple chat app, which user can see the other user's nickname or avatar, while not their mobile or the other information,
so it's collection view is open for everyone well only nickname and avatar should be seen, now all the fields is visitable which makes pocketbase very dangerous to use, any solution for api rules?

**Comment by ganigeorgiev** [comment]
API rules grant or restrict access to the collection records. There is no option at the moment for "private/hidden" feilds if that's what you are asking.

If you have such fields, you can move them to a new collection with its own API rules and create a `relation` pointing back to it.

If you have other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a).
