### ISSUE TITLE
Object has no member 'requireGuestOnly'

### ISSUE THREAD

**Issue by einarpersson** [pocketbase/pocketbase#3896]
According to [the docs](https://pocketbase.io/docs/js-routing/#builtin-middlewares) there exists a
```
// requires the request client to be unauthenticated, aka. guest
$apis.requireGuestOnly()
```

but using this throws
`TypeError: Object has no member 'requireGuestOnly' `

and I can't find it [here](https://pocketbase.io/jsvm/modules/_apis.html) either

**Comment by ganigeorgiev** [comment]
Hm, it seems that I've forgotten to add the binding. I'll update it with the next release.

If you want to emulate the same behavior as the middleware, you can try checking for the `authRecord` and `admin` context keys:

```js
if (c.get("admin") || c.get("authRecord")) {
    throw new BadRequestError("The request can be accessed only by guests.")
}
```
