### ISSUE TITLE
Bug: requestVerification endpoint fails with: HTTPErrorHandler response was already committed but request response is 204 

### ISSUE THREAD

**Issue by Plorenzo** [pocketbase/pocketbase#3908]
(I think this is a bug, but if it's expected behaviour feel free to move it to a discussion)

When you try to verify an email of a user that has not been registered yet: 

```ts
let email = some@email.com
pb.collection(Collections.Users)
			.requestVerification(email)
			.then((response) => {
				console.debug('verification email sent', response);
			})
			.catch((error: ClientResponseError) => {
				console.error(error);
			});
```

from the sdk perspective the request succeeds (debug statement is printed), but the there is an error in the backend and the email is not triggered:

```
[3.00ms] SELECT `users`.* FROM `users` WHERE `email`='some@email.com' LIMIT 1
2023/12/09 21:07:51 HTTPErrorHandler response was already committed: sql: no rows in result set
```

I assume this happens because is not expected to verify an email of a no user, if that is the case, I would expect that call to fail with a reasonable error. Also it would be useful if it was clarified in the docs that user creation must go first. 

To give context, I was doing this because I don't want to create users that don't have verified emails, so I was trying to verify the email first, then register the user.

**Comment by ganigeorgiev** [comment]
The logs are already refactored in the `develop` branch and the `already committed` shouldn't be logged anymore.

>  I was doing this because I don't want to create users that don't have verified emails, so I was trying to verify the email first, then register the user.

There is already a unique constraint for the `email` field and you don't have to todo any additional checks.
Also note that the `requestVerification` (and other similar public endpoints) will return 200 even if there is no user with the registered email.
