### ISSUE TITLE
Kotlin Multiplatform SDK

### ISSUE THREAD

**Issue by wakaztahir** [pocketbase/pocketbase#3909]
Kotlin Multiplatform SDK would work on Android / iOS / JVM / Web

All with a single project

This can be done easily using Ktor which is a multiplatform framework for Kotlin

If you are going to create a Android SDK, You must do it in Kotlin because that's the official language

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/discussions/391.
