### ISSUE TITLE
How to get field values from collection trigger

### ISSUE THREAD

**Issue by GalaxysHub** [pocketbase/pocketbase#3921]
I'm following the documentaion here to extend pocketbase with javascript: https://pocketbase.io/docs/js-overview/

I have a collection with a field named 'test_field' and want to get the value when a record is written to the collection. I have the following code in a file named main.pb.js in the pb_hooks directory

`
    onRecordAfterCreateRequest((e) => {
      console.log(JSON.stringify(e.record));
      console.log("e.record.id =>", e.record.id); //valid
      console.log("e.record.updated =>", e.record.updated); //valid
      console.log("e.record.created =>", e.record.created); //valid
      console.log("e.record.email =>", e.record.email); //function reflect.methodValueCall()
      console.log("e.record.username =>", e.record.username()); //function reflect.methodValueCall()
      console.log("e.record.name =>", e.record.name); //undefined
      console.log("e.record.test_field =>", e.record.test_field); //undefined
    });
`

logging e.record will show all the values in an object, but trying to get the "test_field" value will return undefined.

It seems like there are some system fields that do return values. The email and username fields return functions and id, created, and updated return values.

**Comment by ganigeorgiev** [comment]
The `record` model is not a standard JavaScript object and the dynamic schema fields at the moment can be accessed or modified via the [Record get/set helpers](https://pocketbase.io/docs/js-records/#getset-record-fields):

```js
const a = e.record.get("test_field");
```

_If you have further questions, please consider filing a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a)._
