### ISSUE TITLE
I would like to configure the test app request context timeout.

### ISSUE THREAD

**Issue by SkYNewZ** [pocketbase/pocketbase#3930]
Because of this hardcoded timeout value, testing our custom routes implementation is sometimes impossible. Can you maybe make it configurable ? Thanks

https://github.com/pocketbase/pocketbase/blob/98c8c986030bd7495629110c7dfc009b4cc8a681/tests/api.go#L93

**Comment by ganigeorgiev** [comment]
The hardcoded timeout was removed and replaced with a `Timeout` field.

The change is currently only in the `develop` branch and will be most likely available with the next minor v0.20.1 release within the next 1-2weeks.

**Comment by SkYNewZ** [comment]
Thanks for the quick answer!
