### ISSUE TITLE
Feature Request: Support for Connection String or Direct Connection Data"

### ISSUE THREAD

**Issue by bruno2pereira** [pocketbase/pocketbase#3952]
**Description**

We would like to request the addition of a new feature in Pocket Base that allows the inclusion of a connection string or direct connection data for the database. This would ease the process of altering the database through an external backend, providing greater flexibility for custom integrations.

**Proposed Tasks**
-  Implement support for connection string
-  Add option to provide direct connection data
-  Update corresponding documentation

**Comment by ganigeorgiev** [comment]
Loading and querying external data for now remains out of the scope for v1.

**Comment by ganigeorgiev** [comment]
On second read, it seems that you want something like a dsn db string. If that's the case, then this is also out of the scope for v1 and the available [Web API](https://pocketbase.io/docs/api-records/) is the recommended way external application to communicate with PocketBase.
