### ISSUE TITLE
An IP Blacklist for admin panel

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#3975]
A way to avoid that a stranger tried to access to admin panel (exclude users table)
![image](https://github.com/pocketbase/pocketbase/assets/5947268/f4a01048-a90f-4f0b-83d1-d5210b5f85b8)

**Comment by miguelgargallo** [comment]
If you fail more tha i++ eg:  times, you are out of try more things

**Comment by miguelgargallo** [comment]
So we can create the PocketBase IP Blacklist network to sync with other anonymous users and know potential banned users from others, to add to our list, something like pihole but tiny, for PB

**Comment by ganigeorgiev** [comment]
This will be handled eventually as part of https://github.com/pocketbase/pocketbase/issues/1232.

For now you have several options:
- define the IP whitelist/blacklist on cloud/OS firewall level
- define the IP whitelist/blacklist on reverse proxy (eg. nginx)
- use a middleware (Go or JS) and block manually the designated IP. Here is one such example with the [JS hooks](https://pocketbase.io/docs/js-overview/):
    ```js
    // pb_hooks/main.pb.js
    
    routerUse((next) => {
        return (c) => {
            // ip:port string (not sure if the below will work on ipv6 addresses)
            const addr = c.request().remoteAddr;
            const ip = addr.substring(0, addr.lastIndexOf(":"));

            if (ip == "YOUR_IP_TO_BLOCK") {
                throw new ForbiddenError("You are not allowed to access this resource")
            }

            return next(c);
        }
    })
    ```

**Comment by miguelgargallo** [comment]
Colossal thanks, THIS F* project is so complete, I wanna cry, THANKS cause what you do is simply amazing, you have a prospect so ATH! <3 continue working
