### ISSUE TITLE
Feature Request: Color Tag for Collections in UI

### ISSUE THREAD

**Issue by user0608** [pocketbase/pocketbase#4009]
Currently, I manage multiple collections through the user interface and have identified the need for a feature that facilitates the differentiation and management of these collections. 

- I propose the implementation of color tags, which would allow assigning a specific color to each collection, in this way we can easily differentiate collections that belong to the same context

thank you for your work

**Comment by ganigeorgiev** [comment]
There are no plans for this as I think
