### ISSUE TITLE
Exporting collections doesn't write maxSize value

### ISSUE THREAD

**Issue by mrmcrrobinson** [pocketbase/pocketbase#4029]
This is not a big problem *but something I have noticed*.

You needn't define the max size for an JSON object in pocketbase. When you export a collection with a JSON object. It will write a schema like such

```
{
        "system": false,
        "id": "bm6mc5rg",
        "name": "schema",
        "type": "json",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {}
}
```

However, the importer validation doesn't like the fact there is no `maxSize` value and requests you add one.

**Comment by ganigeorgiev** [comment]
I should have mentioned this in the release notes, sorry.

This is expected if your collections json was generated before v0.20.0.
With v0.20.0 we introduced the `maxSize` `json` field option and it is required to prevent abuse and storing large json strings in the database.

While there is a [system migration](https://github.com/pocketbase/pocketbase/blob/master/migrations/1702134272_set_default_json_max_size.go) that updates old existing collections with a default 2mb `maxSize`, there is nothing we can do for old exported json files (_without complicating the internals and adding a special validator case for the imported collections_) and you'll have to add the new option manually.
