### ISSUE TITLE
Duplicate an element

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4033]
I created an awesome element, but I need to create 3 more like this, a "duplicate" with "+_i++" number would be awesome, like logo_1, logo_2. For more see the image, also would be greate to automatically show the path of the file, on the pocketbase and or bucket:

![image](https://github.com/pocketbase/pocketbase/assets/5947268/205c467f-bc72-4b9b-9c3f-6b36cc02194b)
![image](https://github.com/pocketbase/pocketbase/assets/5947268/f4daed67-c5e7-4750-833f-2a9c1487e7f5)

**Comment by pnmcosta** [comment]
IMO this is a very specific use case, not sure it's something Pocketbase would necessarily have to handle

But for now could use the "Settings > Export collections" feature and then manipulate the collections JSON with your own code snipped and re-import ;)

**Comment by miguelgargallo** [comment]
Yeah that's what I do haha LMAO, yeah, but for some reason, maybe I am not the only one, so I decided to push it here

**Comment by ganigeorgiev** [comment]
This was added in the `develop` branch and will be available with the next v0.21.0 release.

I'm not sure if having multiple duplicated fields is the best way to handle it in your case or just convert your `file` field to accept multiple values, but I guess having an option to duplicate fields can help in situations where for example the i18n data is managed in the same collection (eg. have multiple fields like `enTitle`, `bgTitle`, etc. with the same options).
