### ISSUE TITLE
Don't always create the pb_data directory

### ISSUE THREAD

**Issue by wdscxsj** [pocketbase/pocketbase#404]
Thanks for this great project, and this is quite nitpicking. The `pb_data` directory is created even when showing the help or version number. It's annoying to manually remove it to keep the file system clean.

**Comment by ganigeorgiev** [comment]
The commands are executed after the `app.Bootstrap` call because sometimes they could have a need to access the database (this is true also for custom user register commands).

In a future release I'll try to exclude at least the `version` cmd from calling the bootstrap process.

**Comment by wdscxsj** [comment]
Thanks!

**Comment by ganigeorgiev** [comment]
This should be fixed in [v0.7.2 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.7.2).

The bootstrap process will NOT be initialized on:

- `./pocketbase --version / -v` call
- `./pocketbase [cmd] --help / -h` call
- on invalid/unsupported flags (eg. `./pocketbase --invalid`)

_Note that on invalid/unsupported command arguments (eg. `./pocketbase migrate invalid`) the bootstrap process will still be executed because the cmd arguments could be further validated inside the `Run` handler based on some app setting (eg. checking it against a db entry)._

**Comment by jkdoshi** [comment]
Based on your recent commits (and oh boy are you active!) I see that you're about to do some significant work the config subsystem. Not sure if this is the right place, but may I pile on suggest a config file + command line option combination that allow controlling of several things such as pb_data location, pb_public location (and name), ports, URL's etc.

The project is awesome. So much potential. I am already using it as a Go framework and not just a binary. Although SQLite will be my default choice, I truly hope you also add Postgres. If for nothing else, then to just put people's mind at ease while choosing pocketbase for their projects.

**Comment by ganigeorgiev** [comment]
@jkdoshi I'm not planning adding support for loading external config files, but in the recent [v0.7.2 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.7.2), we now have a new factory method `NewWithConfig` that allows loading a config struct that looks like this (more options will be added after users refactoring in #376):

```go
package main

import (
	"log"

	pb "github.com/pocketbase/pocketbase"
)

func main() {
	app := pb.NewWithConfig(pb.Config{
		DefaultDataDir: "YOUR_CUSTOM_DEFAULT_DIR",
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

The developers are free to use the config format and library of their choice if they want to keep their configurations in a file.

> I truly hope you also add Postgres.

Support for other databases for now has the lowest priority. If you haven't already, you could check the roadmap at https://github.com/orgs/pocketbase/projects/2.
