### ISSUE TITLE
SDK for java

### ISSUE THREAD

**Issue by NerminKarapandzic** [pocketbase/pocketbase#4057]
Hi, I'm currently using pocketbase for one of my projects and I ended up having to communicate with pocketbase apis from my java backend.
Was there plans to support SDK's for different languages like Java.
I'd be willing to work on this.

**Comment by ganigeorgiev** [comment]
At least until v1, there are no plans for other SDKs as it will be hard to maintain.
User contributions are welcomed (if you want to work on this I recommend checking the [Dart SDK](https://github.com/pocketbase/dart-sdk) as a reference).

See also https://github.com/pocketbase/pocketbase/discussions/391.
