### ISSUE TITLE
Question: Using PocketBase as a Relay Peer & Backend : A look at GunDB

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/pocketbase#4069]
Hi

I rececently came across gundb, https://gun.eco/

One is able to use localstorage, indexeddb to store content, which is awesome. Ive noted that it has some other adapters also for MySQL, MongoDB etc and are reading through for more insights.

I am wondering if its possible to perhaps use this with PocketBase. As pocketbase is also a web server on its own, can it be used as a relay peer and or perhaps be able to store the data to from / to gunDb. If so, what could be the best approach?

Perhaps this example can shed some light. https://dev.to/codesphere/set-up-a-decentralized-database-with-react-and-gundb-2e5m

Thanks in advance for your time.

**Comment by ganigeorgiev** [comment]
I have no experience with GUN but at least for v1 there are no plans for official integration with PocketBase.
