### ISSUE TITLE
Docs API details Response miss match.

### ISSUE THREAD

**Issue by pvbhanuteja** [pocketbase/pocketbase#4071]
I'm trying to do sometime like list collection. 

```
  try {
    const exisitingubscriptionStatusData = await adminpb.collection(Collections.SubscriptionStatus).getFirstListItem<SubscriptionStatusResponse>(pb.filter('subscription_id = {:id}', { id: subscriptionId }));
    // Your code here
  } catch (err) {
    console.log('Error:', err);
    // Handle the error
  }
```

Response

```
Error: ClientResponseError 404: The requested resource wasn't found.
{
  url: '',
  status: 404,
  response: {
    code: 404,
    message: "The requested resource wasn't found.",
    data: {}
  },
  isAbort: false,
  originalError: {
    status: 404,
    data: {
      code: 404,
      message: "The requested resource wasn't found.",
      data: {}
    }
  }
}
```

But the socs says https://pocketbase.io/docs/api-collections/#list-collections
<img width="870" alt="image" src="https://github.com/pocketbase/pocketbase/assets/33227278/bca7f7b2-64e9-4775-946b-d5bc97e6f615">

Actual reposnes match with the view collection 
https://pocketbase.io/docs/api-collections/#view-collection
<img width="910" alt="image" src="https://github.com/pocketbase/pocketbase/assets/33227278/965ff204-3112-4a3b-8834-79409dc258a9">

**Comment by ganigeorgiev** [comment]
The above responses are just example.

Additionally `getFirstListItem()` is only client-side SDK helper and it is explicitly documented that it throws 404 error in case no record is found for consistency with `getOne` (see [CrudService.ts](https://github.com/pocketbase/js-sdk/blob/7c100bb5148dceb285a6b41369656037a30a6d28/src/services/utils/CrudService.ts#L77-L88)).
