### ISSUE TITLE
v0.20.3 broke my view collection expansion API request

### ISSUE THREAD

**Issue by dschissler** [pocketbase/pocketbase#4072]
`v0.20.3` broke my (development) logged in homepage.  The view listing works in the admin panel, but just not with this `expand=site.siteResources(site),site.tier` option.  I don't know what is going on here.  Maybe something to do with the `0.20.3` JSON null changes?

```
ERROR GET /api/collections/v_sites/records?page=1&perPage=100&view=list&expand=site.siteResources(site),site.tier
└─ Something went wrong while processing your request.
   └─ malformed JSON; failed query: SELECT COUNT(DISTINCT [[v_sites.id]]) FROM `v_sites` LEFT JOIN `sites_users` `__collection_sites_users` LEFT JOIN `users` `__auth_users` ON `__auth_users`.`id`={:p0} LEFT JOIN `userGroups` `__auth_users_group` ON [[__auth_users_group.id]] = [[__auth_users.group]] WHERE (({:f4vDtn} = {:tw9ied} AND JSON_EXTRACT([[v_sites.status]], '$') IS {:tqAl1h} AND COALESCE([[__collection_sites_users.site]], '') = COALESCE([[v_sites.site]], '') AND [[__collection_sites_users.user]] = {:f6lsUb}) OR ({:fKDoTB} = {:tyo6Cw} AND [[__auth_users_group.rank]] >= {:tHnJ7G}) OR ({:fVUZDy} IS NOT '' AND {:fttcYh} = [[v_sites.site]] AND COALESCE([[__collection_sites_users.site]], '') = COALESCE([[v_sites.site]], '') AND [[__collection_sites_users.user]] = {:fNBghx}))
```

`v_sites`

```sql
SELECT
  (ROW_NUMBER() OVER()) as id,
  su.site as site,
  pInt.name as nameInt,
  pExt.name as nameExt,
  s.type,
  s.status,
  t.id as tier,
  s.created,
  s.updated,
  JSON_GROUP_ARRAY(
    JSON_OBJECT(
      'id', su.id,
      'site', su.site,
      'user', su.user,
      'type', su.type,
      'email', u.email,
      'name', u.name
    )
  ) as users
FROM sites_users su
/* sites */
LEFT JOIN sites s on su.site = s.id
/* users */
LEFT JOIN users u on su.user = u.id
/* internal point */
LEFT JOIN sites_points spInt ON spInt.site = s.id
LEFT JOIN points pInt ON spInt.point = pInt.id
/* external point */
LEFT JOIN sites_points spExt ON spExt.site = s.id
LEFT JOIN points pExt ON spExt.point = pExt.id
/* tier */
LEFT JOIN siteTiers t ON s.tier = t.id
WHERE
  spInt.type = 'int' AND
  spExt.type = 'ext'
GROUP BY su.site
```

**Comment by ganigeorgiev** [comment]
Hm, what are the possible values for `v_sites.status`?

**Comment by dschissler** [comment]
`sites:status`: single, nonempty

`skeleton, active, inactive, error, toggling, creating, moving, deleting`

**Comment by ganigeorgiev** [comment]
It doesn't make sense why the `expand` will trigger this.

Could you test again downgrading to v0.20.2?

**Comment by ganigeorgiev** [comment]
It is possible the latest `JSON_EXTRACT` wrapping to cause it to fail but I'm not sure why yet.

**Comment by dschissler** [comment]
> It doesn't make sense why the `expand` will trigger this.
> 
> Could you test again downgrading to v0.20.2?

I just downgraded to v0.20.2, and it works again.

**Comment by dschissler** [comment]
@ganigeorgiev Also feel free to let me know if I'm doing anything retarded with my SQL.

**Comment by dschissler** [comment]
I'm going to try without expansions and then to add them back one-by-one to isolate.

**Comment by ganigeorgiev** [comment]
I think I found the culprit. In views because we treat expressions as `json` this now may not work because `json_extract` will receive a column that wasn't json serialized and an extra normalization for this case will be needed. I'll try to create an automated test for this and will submit shortly after that.

**Comment by ganigeorgiev** [comment]
Is it possible to test the fix from `master` with your dateset?

**Comment by dschissler** [comment]
@ganigeorgiev Give me about 30 minutes to get to it.

**Comment by ganigeorgiev** [comment]
@dschissler I've pushed the latest changes as [v0.20.4](https://github.com/pocketbase/pocketbase/releases/tag/v0.20.4). If it still fail and your issue is caused by something else, please let me know and I'll try to investigate it further sometime later today.

**Comment by dschissler** [comment]
A quick check of v0.20.4 shows that it works now.
