### ISSUE TITLE
upload(S3 bucket) photos in the tinymce

### ISSUE THREAD

**Issue by siamakabi** [pocketbase/pocketbase#4079]
Hello
Please provide the possibility to upload(S3 bucket) photos in the tinymce text editor
Instead of saving as text base-64

**Comment by ganigeorgiev** [comment]
This is already supported but by selecting files from collections.

You can create a "Media" collection and upload your files to it and then select the "From collection" option from the editor.

![editor_screenshot](https://i.imgur.com/KCxlgBh.png)

**Comment by ganigeorgiev** [comment]
Note that you can upload a new file to the collection from the "From collection" popup, but it seems that there is a CSS issue with the searchbar that pushes the button out of the popup box and hides it.

I'll push a fix sometime later today.

**Comment by ganigeorgiev** [comment]
_The mentioned CSS bug should be fixed in [v0.20.5](https://github.com/pocketbase/pocketbase/releases/tag/v0.20.5)._
