### ISSUE TITLE
"go get" command is depreciated! can you update in README.md also?

### ISSUE THREAD

**Issue by rahulraikwar00** [pocketbase/pocketbase#4090]
here is a reference for that 
https://go.dev/doc/go-get-install-deprecation

![Screenshot 2024-01-05 202717](https://github.com/pocketbase/pocketbase/assets/54519734/5b82122a-f517-45eb-8655-fa173b1cfef0)

**Comment by ganigeorgiev** [comment]
`go get` is not deprecated. Its old usage for isntalling executable is deprecated, which in the README is not used this way but only for fetching the library and registering it in your go.mod.

If you want to use the prebuilt binaries you can check the "Assets" section under each release - https://github.com/pocketbase/pocketbase/releases.
