### ISSUE TITLE
Implementing SSR Integration

### ISSUE THREAD

**Issue by serkan-bayram** [pocketbase/pocketbase#4123]
In any case note that the above password authentication function could be slow if executed every time due to the bcrypt hash verification.

A better approach for admin authentication is to have a single server global admin instance that you can just import in your server-side actions. For example:

```js
// src/adminClient.js
import PocketBase from "pocketbase"

const adminClient = new PocketBase(process.env.dbURL);

await adminClient.admins.authWithPassword(process.env.dbUsername, process.env.dbPassword, {
  // This will trigger auto refresh or auto reauthentication in case
  // the token has expired or is going to expire in the next 30 minutes.
  autoRefreshThreshold: 30 * 60
})

export default adminClient;
```

And then in your serverside actions you can just import it and use it directly:

```js
import adminClient from "src/adminClient.js";

export async function voteEmoji(ratingId, emoji) {
    ...

    await adminClient.collection("emojis").create(data);

    ...
}

```

_Originally posted by @ganigeorgiev in https://github.com/pocketbase/pocketbase/issues/3903#issuecomment-1847842771_
 
------------------------------------------------------------------------------------------
 
Hi, I was trying to implement your suggestion but there is a some kind of issue: I set my single file of instance but I got an error that says: 

SyntaxError: await is only valid in async functions and the top level bodies of modules. 

Which I think it makes sense since there is not an async function in my "adminClient.js" how is this going to work? Am I missing something?

```js

import PocketBase from "pocketbase";

const pb = new PocketBase(process.env.dbURL);

await pb.admins.authWithPassword(
  process.env.dbUsername,
  process.env.dbPassword,
  {
    // This will trigger auto refresh or auto reauthentication in case
    // the token has expired or is going to expire in the next 30 minutes.
    autoRefreshThreshold: 30 * 60,
  }
);

export default pb;

```js

**Comment by ganigeorgiev** [comment]
I'm getting tired by this... If you have questrion please file a Q&A discussion.
