### ISSUE TITLE
Feature Suggestion : Row Height Optimisation / Compact mode.

### ISSUE THREAD

**Issue by calumk** [pocketbase/pocketbase#4128]
Defualt row height in the admin UI is 60px

Is there a reason for this? It seems a lot of blank space, could we consider dropping it to 52px, which seems to have not impact on layout.

(left, 60px, Right 52px)

<img width="1677" alt="image" src="https://github.com/pocketbase/pocketbase/assets/1183991/a3dfda08-2188-488c-b97d-a5efc40cb097">

vertical row padding could also be reduced to further optimise.

<img width="1669" alt="image" src="https://github.com/pocketbase/pocketbase/assets/1183991/db020f8a-cd86-4f62-b0ec-2530ab9153ca">

Could we maybe have a "compact" mode?

**Comment by ganigeorgiev** [comment]
> Is there a reason for this? 

Everything related to the UI is based on my personal preference.

> Could we maybe have a "compact" mode?

No, I don't think it will be a good idea as it will clutter the UI.

With that said, I've pushed in the `develop` a small change to reduce slightly the min row height.
