### ISSUE TITLE
Design Request: Adding a designated 'data' field in Records API.

### ISSUE THREAD

**Issue by RT-8** [pocketbase/pocketbase#413]
Adding a designated data field would simplify parsing Record objects in statically typed languages.

Current:
`{
  "@collectionId": "a98f514eb05f454",
  "@collectionName": "demo",
  "id": "ae40239d2bc4477",
  "updated": "2022-06-25 11:03:50.052",
  "created": "2022-06-25 11:03:35.163",
  "title": "test1"
}`

Suggested:
 `{
  "@collectionId": "a98f514eb05f454",
  "@collectionName": "demo",
  "id": "ae40239d2bc4477",
  "updated": "2022-06-25 11:03:50.052",
  "created": "2022-06-25 11:03:35.163",
  "data" : {
   "title": "test1"
    }
}`

Similar design can also be seen in [dart-sdk/record_model.dart](https://github.com/pocketbase/dart-sdk/blob/master/lib/src/dtos/record_model.dart) where inline data fields are parsed into a data collection.

**Comment by ganigeorgiev** [comment]
I'm not sure about this. I guess it depends a lot on the language you use and the unmarshaling services it provides.

Most of the time the flatten fields would be easier to parse if you have a custom DTO, which most users will have to do anyway, unless they prefer to work with untyped maps:

```go
type DemoDTO struct {
    CollectionId   `json:"@collectionId"`
    CollectionName `json:"@collectionName"`
    Id             `json:"id"`
    Title          `json:"title"`
    ...
}
```

Furthermore, having the fields directly to the root object, helps having a consistent data format when creating or updating records, aka. users can send back to the server the same json for update without requiring extra unwrapping/wrapping.

**Comment by RT-8** [comment]
For example. in C# the only reasonable way seems to be to unserialize dynamic flattened json by inheriting the shared properties into a new custom model. 

As such: 
```
public class PocketBaseRecord
{
    
    [JsonPropertyName("@collectionId")]
    public string CollectionId { get; set; }

    [JsonPropertyName("@collectionName")]
    public string CollectionName { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("updated")]
    public DateTime UpdatedAt { get; set; }

    [JsonPropertyName("created")]
    public DateTime CreatedAt { get; set; }
}


public class CustomRecordModel : PocketBaseRecord
{
    [JsonPropertyName("title")]
    public string Title { get; set; }
}
```
This approach works, but also removes the ability for the user to use a custom base-class and makes using the library less intuitive. 

Having a designated Data field would open up the ability to use generics and fix the previously mentioned issues.

```
public sealed class PocketBaseRecord<TRecordData>
{
    
    [JsonPropertyName("@collectionId")]
    public string CollectionId { get; set; }

    [JsonPropertyName("@collectionName")]
    public string CollectionName { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("updated")]
    public DateTime UpdatedAt { get; set; }

    [JsonPropertyName("created")]
    public DateTime CreatedAt { get; set; }
    
    [JsonPropertyName("data")]
    public TRecordData Data { get; set; }
}

public static class Example
{
    new PocketBaseRecord<CustomRecordModel>();
}


```

**Comment by ganigeorgiev** [comment]
@RT-8 Nothing is preventing you to move the fields into a map/generic structure similar to how is done in the Dart library.

As I said, this is too language specific and in Dart for example you'll not be able to pass a geneneric type as it is in your example because there is no generics for constructors/static methods so practically the "fromJson" parsing cannot happen without some additional "craftiness".

I don't want to have different presentations on what the data in the database looks like and what the users receive/submit.
