### ISSUE TITLE
ClientResponseError 0: The request was autocancelled.

### ISSUE THREAD

**Issue by fly1ted** [pocketbase/pocketbase#4140]
I catch the error (ClientResponseError 0: The request was autocancelled.) but it's still in the console and I don't want to cancel this behaviour globally coz it's useful. What am I doing wrong?

```javascript
useEffect(()=>{
    pb.collection('pages')
      .getFirstListItem('page = "/faq"')
      .then(v => setItemsFAQ(v.props))
      .catch(e=>{
        if(e.isAbort) return

        throw e
      })
  }, [])
```

**Comment by kerimovok** [comment]
If I'm not mistaken, you need to use the `request Key: "something..."` #3491

**Comment by ganigeorgiev** [comment]
For more info about autocancellation and why it may occur please check https://github.com/pocketbase/js-sdk?tab=readme-ov-file#auto-cancellation.
