### ISSUE TITLE
Treat numeric values when sorting as numbers

### ISSUE THREAD

**Issue by kerimovok** [pocketbase/pocketbase#4143]
Hi, it will be great to sort numeric strings as numbers.

 I don't know how the current sorting function works in the admin UI, but we could use
`String(aValue).localeCompare(String(bValue), undefined, { numeric: true })`

Reproduction: When using the `select` type column, numbers are stored as string (this could be treated as bug also, for someone)

![image](https://github.com/pocketbase/pocketbase/assets/136202877/dd6150d3-533e-48fc-8491-ec4288ac18b6)

I don't know how to make a pull request and also couldn't find the sorting function, so thank you in advance

**Comment by ganigeorgiev** [comment]
The `select` is expected to work only with string value(s).

The sorting in the Admin UI is based on the SQLite `ORDER BY` clause so sorting them only client-side with JS will not work.

Support for specifying a custom collation (including eventually natural sort) may be added somtime in the future as part of [task#33936705](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=collation&pane=issue&itemId=33936705) (_I've updated it to reference this issue as a reminder_) but remains a very low priority and there are no ETAs.
