### ISSUE TITLE
The context on routerAdd function js bindings are wrong

### ISSUE THREAD

**Issue by nhlmg93** [pocketbase/pocketbase#4145]
c.response().header().set() api is being generated wrong either by goja or your typescript. the set method only accepts a key and not a value.

![pocket_base_bug](https://github.com/pocketbase/pocketbase/assets/62121934/2912040c-2553-41c5-ac67-a12e8aadb146)

Note: the set will run and not error when just the key is passed like in the attached photo. however if you try to pass two it will fail. so i suspect its not the type generator.

**Comment by ganigeorgiev** [comment]
Hm, indeed the last argument is missing [from the declaration](https://pocketbase.io/jsvm/interfaces/http.Header.html#set) for some reason.

I'll move the issue to the tygoja repo and will investigate it sometime later this weekend.

**Comment by ganigeorgiev** [comment]
_Should be fixed in [v0.20.6](https://github.com/pocketbase/pocketbase/releases/tag/v0.20.6)._
