### ISSUE TITLE
Feature request: add OnRecordLogoutRequest and OnAdminLogoutRequest

### ISSUE THREAD

**Issue by Gys** [pocketbase/pocketbase#4151]
I want to add custom routes protected by authentication. For this I implemented keeping the jwt token in a cookie, as discussed in https://github.com/pocketbase/pocketbase/discussions/989

It works almost perfectly. My only problem is that after an admin or user logout, the cookie still keeps a valid token. This token also needs to be removed at logout. But I think that event is not traceable from a framework point of view? So therefore my request to add the events OnRecordLogoutRequest and OnAdminLogoutRequest so it is very simple to add code for resetting the token in the cookie.

**Comment by ganigeorgiev** [comment]
PocketBase doesn't really have sessions in the traditional sense so there is no builtin "logout" action and I don't think it make sense to have logout hooks.

Option to register custom/user-defined hooks to the `core.App` struct could be added eventually in the future but for now remains out of the v1 scope.
If you want to register custom hooks you can create a wrapper struct that embeds the PocketBase instance and defines additional [`hook.Hook`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.20.6/tools/hook#Hook) handlers.

**Comment by Gys** [comment]
`there is no builtin "logout" action`: I looked into the code and I understand now. A logout is a pure client side action, it means the client side js deletes its saved jwt token. There is no server side logout, my mistake. Therefore the token itself stays valid, limited only by the time set in the settings.
