### ISSUE TITLE
Proposal, make this possible, would safe lifes time `{message.user.username}`

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4162]
Proposal, make this possible, would safe lifes time `collection.users.user.id` or `{message.user.username}` to import the user.id easier

**Comment by miguelgargallo** [comment]
The idea is to call for records inside the proper script site, example:

```
<div class="w-full h-full overflow-y-auto p-2">
	<h2 class="text-xl font-semibold text-gray-900 mb-4">Messages</h2>
	{#each messages as message}
		<div class="p-2 bg-gray-100 rounded-md mb-2">
			<p class="text-sm text-gray-800">
				{formatTime(message.timestamp)}
			</p>
			<p class="text-sm text-gray-800">
				{message.user.username}
				{message.message}
			</p>
		</div>
	{/each}
</div>
```

**Comment by ganigeorgiev** [comment]
Nested relations fields can be accessed under the `expand` key and for now there are no plans to change that as it could have a lot of side effects otherwise.
