### ISSUE TITLE
Feature request: allow changing the name of the authorization header

### ISSUE THREAD

**Issue by thijsmie** [pocketbase/pocketbase#4163]
I'd like to deploy pocketbase inside a cluster that is managed by my company. However, due to the way the default authentication works there the "Authorization" header is already used for the Microsoft SSO. I was wondering if the "Meta" settings could allow you to specify the name of this header? Then I could set it to `X-PocketBase-Authorization` or something and I can use this wonderful piece of software without a header-rewriting proxy.

I would be willing to give making a PR a go myself but I'm a Python/C developer not a Go developer, so I'd like to check in if you would prefer doing it yourself or are willing to guide me through the process.

**Comment by ganigeorgiev** [comment]
I'm not sure if the use case is common enough to add a setting for it. Users will also have to manually specify the header name on SDKs level because currently the settings are accessible only by admins. It will require further documentation and may cause confusion as a lot of users may not be sure whether they need to change it or not.

For now I'll leave it out of the scope, but if there is users demand for it I may reconsider it.

As an alternative to a header rewrite proxy, you could also define a middleware that will load the auth context from your custom header. Here is an example using the [JS pb_hooks](https://pocketbase.io/docs/js-routing/#middlewares) (_I haven't tested it_):

```js
// pb_hooks/main.pb.js

// Middleware to load the auth context from a custom header.
routerPre((next) => {
    return (c) => {
        const token = c.request().header.get("X-Authorization");
        if (!token) {
            return next(c)
        }

        // strip the "Bearer " prefix if available
        // (the schema is not required and it is only for compatibility with the defaults of some HTTP clients)
        if (token.startsWith("Bearer ")) {
            token = token.substring(7);
        }

        try {
            const claims = $security.parseUnverifiedJWT(token)

            if (claims.type == "admin") {
                const admin = $app.dao().findAdminByToken(token, $app.settings().adminAuthToken.secret);
                c.set(claims.type, admin);
            } else if (claims.type == "authRecord") {
                const record = $app.dao().findAuthRecordByToken(token, $app.settings().recordAuthToken.secret);
                c.set(claims.type, record);
            } else {
                throw new Error("unsupported or missing token type:", claims.type);
            }
        } catch (err) {
            $app.logger.debug("invalid or expired token", "token", token, "error", err)
        }

        return next(c)
    }
})
```

On the client-side if you use the JS SDK you'll also have to attach to the [`beforeSend` hook](https://github.com/pocketbase/js-sdk?tab=readme-ov-file#send-hooks) to overwrite the sent request header:

```js
import PocketBase from "pocketbase";

const pb = new PocketBase("http://127.0.0.1:8090");

pb.beforeSend = function (url, options) {
    options.headers['X-Authorization'] = options.headers['Authorization']
    delete options.headers['Authorization'];
    return { url, options };
};

...

await pb.collection("example").getList(1, 40)
```

**Comment by thijsmie** [comment]
Thank you for the quick response! I'll just leave my code snippets here if anyone runs across it in the future. First, I rebuilt the admin UI:

```shell
git clone https://github.com/pocketbase/pocketbase
cd pocketbase/ui
npm install
```

I edited file `ui/src/utils/ApiClient.js` to include the snippet from @ganigeorgiev above.

```js
const pb = new PocketBase(
    import.meta.env.PB_BACKEND_URL,
    new AppAuthStore("pb_admin_auth")
);

pb.beforeSend = function (url, options) {
    options.headers["X-Authorization"] = options.headers["Authorization"]
    delete options.headers["Authorization"];
    return { url, options };
};
```

I edited `ui/.env` to always use the root path as pocketbase:
```bash
PB_BACKEND_URL         = "/"
```

Now rebuild
```bash
npm run build
```

Then I added the `dist` folder next to my pocketbase executable as `pb_admin` and added the following to `pb_hooks/main.pb.js` (you only missed one set of parenthesis 😄):

```js
routerPre((next) => {
    return (c) => {
        let token = c.request().header.get("X-Authorization");

        // strip the "Bearer " prefix if available
        // (the schema is not required and it is only for compatibility with the defaults of some HTTP clients)
        if (token.startsWith("Bearer ")) {
            token = token.substring(7);
        }

        if (!token) {
            return next(c)
        }

        try {
            const claims = $security.parseUnverifiedJWT(token)

            if (claims.type == "admin") {
                const admin = $app.dao().findAdminByToken(token, $app.settings().adminAuthToken.secret);
                c.set(claims.type, admin);
            } else if (claims.type == "authRecord") {
                const record = $app.dao().findAuthRecordByToken(token, $app.settings().recordAuthToken.secret);
                c.set(claims.type, record);
            } else {
                throw new Error("unsupported or missing token type:", claims.type);
            }
        } catch (err) {
            $app.logger().debug("invalid or expired token", "token", token, "error", err)
        }
        return next(c)
    }
})
routerAdd("GET", "/_/*", $apis.staticDirectoryHandler("./pb_admin", true))
```

**Comment by ganigeorgiev** [comment]
Hm, I forgot about the Admin UI part.
Although I'm not sure that I understand your setup and how the Microsoft SSO works, I think configuring a header rewrite proxy may be the better option here as it will be easier to maintain in case there is an update of the Admin UI.

**Comment by thijsmie** [comment]
The rewrite proxy still would not fix the admin frontend setting the authorization header and my cluster ingress just throwing that header away and overwriting it with the SSO token sadly. I have almost finished the setup to automatically download releases and apply a git patch file and then build a docker image, which will keep working as long as the specific files don't change very much. I think that level of maintenance is acceptable for me for now.
