### ISSUE TITLE
Configurable port

### ISSUE THREAD

**Issue by enstyled** [pocketbase/pocketbase#418]
Congratulations on the project, I love the idea and think it has great potential, especially combined with Litestream ❤️

As far as I can tell, the port `8090` is permanent and cannot be configured. It would be useful if it can be customised with environment variable. Some services assign a random port when the app boots, others are limiting the range of the ports you can use and 8090 might fall out of that range.

**Comment by ganigeorgiev** [comment]
@enstyled You can change the default application port with the `--http` flag, for example:

```sh
./pocketbase --http="127.0.0.1:3000"
```

PocketBase can also issue a Let's encrypt certificate for you (**if you have a public domain**), so to deploy PocketBase usually it is enough to run:

```sh
./pocketbase --http="yourdomain.com:80" --https="yourdomain.com:443"
```

There are other flags also available that you could check by running `./pocketbase --help`.
