### ISSUE TITLE
Serial ID Feature

### ISSUE THREAD

**Issue by damnkyro** [pocketbase/pocketbase#4182]
Yo

Is there a way to make an ID column work serially (auto incrementing with every record) instead of the uuid format made? Kind of something like below but idk how the person who took the screenshot did it:

![image](https://github.com/pocketbase/pocketbase/assets/94295643/930e6625-92c3-400d-b672-36be2ddc5066)

**Comment by ganigeorgiev** [comment]
No, we don't have autoincrement at the moment.
