### ISSUE TITLE
Add custom CORS middleware

### ISSUE THREAD

**Issue by Raudius** [pocketbase/pocketbase#4186]
I cant seem to be able to attach my own CORS middleware, possibly because PocketBase already adds its own CORS middleware to the echo server.

```go
mwCors := middleware.CORSWithConfig(middleware.CORSConfig{
	AllowOrigins: []string{"*"},
	AllowHeaders: []string{echo.HeaderOrigin, echo.HeaderContentType, echo.HeaderAccept},
	AllowMethods: []string{http.MethodGet, http.MethodHead, http.MethodPut, http.MethodPost, http.MethodDelete, http.MethodOptions, "PROPFIND", "PROPPATCH", "MKCOL", "COPY", "MOVE"},
})

app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
	e.Router.Use(mwCors)
})
```

Locally tested and a possible fix might be to delay the [attaching of the pocketbase middleware](https://github.com/pocketbase/pocketbase/blob/v0.20.7/apis/serve.go#L86) until after the [OnBeforeServe event](https://github.com/pocketbase/pocketbase/blob/v0.20.7/apis/serve.go#L170)

**Comment by ganigeorgiev** [comment]
This may change in the future but currently it is not possible to change/overwrite the default CORS middleware configuration (other than the origins).

Registering the default middleware at later stage, will register it twice. If you want your middleware to be registered before the default one you can use `e.Router.Pre`.
