### ISSUE TITLE
(i18n) multi language support

### ISSUE THREAD

**Issue by pr0ton11** [pocketbase/pocketbase#4189]
Would it be possible to support multiple languages for the data stored in pocketbase?

**Comment by ganigeorgiev** [comment]
At least for v1 there are no plans to add builtin handling for i18n fields. The recommended approaches currently are as for any other SQL database - use a language prefixed keys (eg. `enTitle`, `bgTitle`, etc.), keep each language in a separate collection or have multiple records with `relation` field to a language collection. See also https://github.com/pocketbase/pocketbase/issues/37#issuecomment-1179554998.
