### ISSUE TITLE
Feature Request: Telegram Auth Provider

### ISSUE THREAD

**Issue by safazi** [pocketbase/pocketbase#419]
https://core.telegram.org/widgets/login

**Comment by ganigeorgiev** [comment]
PocketBase supports only OAuth2 (with the PKCE flow when possible) for external auth providers.

Unfortunetelly Telegram doesn't seem to support OAuth2 at all or at least I can't find anything about it in the [API documentation](https://core.telegram.org/bots/api#making-requests) (only the legacy OAuth is mentioned).
