### ISSUE TITLE
If I change the rule of password length this should adapt

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4192]
If I change the rule of password length this should adapt

![image](https://github.com/pocketbase/pocketbase/assets/5947268/978d01ca-28e3-49b2-9889-e59255738209)
![image](https://github.com/pocketbase/pocketbase/assets/5947268/69eb17ec-a889-4a7f-ba7a-0321a53099b6)
![image](https://github.com/pocketbase/pocketbase/assets/5947268/647c932d-a9fa-4ccd-b792-b6533bd7cb96)

One more thing, thank you, I donate sometimes without expecting nothing, and even if this issue is not done, don't worry, guys you are doing an amazing job, thanks for everything. Seriously, this project is amazing and saves my time, with you devs I can make any project real. 

Thanks,
Miguel Gargallo 💖

**Comment by ganigeorgiev** [comment]
It should be fixed in the `develop` branch.
