### ISSUE TITLE
Serve fallback file when requested file does not exist

### ISSUE THREAD

**Issue by RoenLie** [pocketbase/pocketbase#421]
Hi!

Is there a standardized way to redirect back to /index.html whenever a requested file does not exist?

Reason why I am asking is because I am serving a SPA application, which handles its own routing.

I would like pocketbase to allow the SPA to handle routing requests that don't match existing files in the public directory.

At the moment I am using the example for serving public files, found in this repo.

app.OnBeforeServe().Add(func(e` *core.ServeEvent) error {
  // serves static files from the provided public dir (if exists)
  subFs := echo.MustSubFS(e.Router.Filesystem, "pb_public")
  e.Router.GET("/*",  apis.StaticDirectoryHandler(subFs, false))

return nil
})

Thank you!

**Comment by RoenLie** [comment]
I got it working by copying the apis.StaticDirectoryHandeler method and adding a check if the file exists.
But if there is an intended way to do this, it would be great.
.net exposes a method for this spesific purpose.
```endpoints.MapFallbackToFile("/index.html");```

```
func StaticDirectoryHandlerCustom(fileSystem fs.FS, disablePathUnescaping bool) echo.HandlerFunc {
	return func(c echo.Context) error {
		p := c.PathParam("*")
		if !disablePathUnescaping { // when router is already unescaping we do not want to do is twice
			tmpPath, err := url.PathUnescape(p)
			if err != nil {
				return fmt.Errorf("failed to unescape path variable: %w", err)
			}
			p = tmpPath
		}

		// fs.FS.Open() already assumes that file names are relative to FS root path and considers name with prefix `/` as invalid
		name := filepath.ToSlash(filepath.Clean(strings.TrimPrefix(p, "/")))

                // Checks if file exists, redirects to index if it does not.
		_, err := fs.Stat(fileSystem, name)
		if err != nil {

			return c.FileFS("index.html", fileSystem)
		}

		return c.FileFS(name, fileSystem)
	}
}
```

**Comment by ganigeorgiev** [comment]
@RoenLie Yes, overwritting the StaticDirectoryHandler is one way to do it. Another possible workaround could be to "extend" the global error handler:

```go
package main

import (
	"log"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
)

func main() {
	app := pocketbase.New()

	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		// serves static files from the provided public dir (if exists)
		subFs := echo.MustSubFS(e.Router.Filesystem, "pb_public")
		e.Router.GET("/*", apis.StaticDirectoryHandler(subFs, false))

		// redirect to homepage on missing file
		originalErrorHandler := e.Router.HTTPErrorHandler
		e.Router.HTTPErrorHandler = func(c echo.Context, err error) {
			if c.Path() == "/*" && err == echo.ErrNotFound {
				err = c.Redirect(http.StatusTemporaryRedirect, "/")
			}
			originalErrorHandler(c, err)
		}

		return nil
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

_After the users manamagement refactoring, I'll consider providing support for a fallback route to the static directory handler._

**Comment by RoenLie** [comment]
Great! thanks a lot for the quick response.

Really enjoying pocketbase so far, I believe it has great potential.
