### ISSUE TITLE
password reset and verifications links are not expiring

### ISSUE THREAD

**Issue by TSCSOftware** [pocketbase/pocketbase#4210]
I changed the password once by email. But you can do it again through that email.
Shouldn't it then show "This link has expired"?

I think these links should be changed so that they can be used only once.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. After successfully changing the record password all previously issued tokens should be invalidated.

Also note that with the next release, the password reset confirmation action will also mark a user as verified (if not already).
