### ISSUE TITLE
Feature request : option to allow building custom UI having app directory which gets bundled with executable 

### ISSUE THREAD

**Issue by zeet2020** [pocketbase/pocketbase#4225]
- option to allow adding custom ui or frontend app directory which get bundled, allowing building complete application in one executable, just like we have admin `http://localhost:8090/_/#/login`  on embedding ui application we get  `http://192.168.0.101:8090/app/`

**Comment by ganigeorgiev** [comment]
You can do that already with Go using the standard [`//go:embed` directive](https://pkg.go.dev/embed) (for an example you can check the `ui/embed.go`).

**Comment by zeet2020** [comment]
i need to update logic in api/base.go as well, to serve custom intex.html from  webapp.

**Comment by ganigeorgiev** [comment]
@zeet2020 I'm not sure that I understand what do you mean but for serving static files you can check https://pocketbase.io/docs/go-routing/#serving-static-files (replace `os.DirFS` with your embedded directory).
