### ISSUE TITLE
Feature suggestion: Support SQLite json_extract function

### ISSUE THREAD

**Issue by pchasco** [pocketbase/pocketbase#423]
SQLite has rich JSON operators which may cover many of the use cases that developers familiar with NoSQL/document databases are familiar with. It would be good if a subset of these could be made available via the query API.

https://www.sqlite.org/json1.html

In particular, I think the json_extract() function is of the most value, because it would enable filtering of data based on values in the JSON object. 

```dart
  final result = await client.records.getList(
    "example",
    page: 1,
    perPage: 20,
    filter: "status = true && created >= '2022-08-01' && json_extract(my_json_column, '$.path.to.property') = 'value'",
    sort: "-created",
  );
```

There are obvious performance considerations when using json_extract in a query without indexes. Fortunately, SQLite can index json_extract.

There are several other useful JSON functions supported by SQLite to unroll JSON structures and update JSON in-place. These are useful functions, but most of those operations are easily performed on the client.

If allowing developers to filter against JSON data without using an index is a concern, then it would be possible to constrain queries to use only indexed JSON paths, and to attempt to query without using an indexed path would be an error.

**Comment by ganigeorgiev** [comment]
Support for querying the `json` type field is in my todo.

This will be implemented with the dot-notation syntax (the same is used for querying nested relations) since for now I'm planning support only for `json_extract` anyway:

```
status = true && created >= '2022-08-01' && my_json_column.path.to.property = 'value'
```

**Comment by pchasco** [comment]
Amazing! Love it.

**Comment by lukepighetti** [comment]
Would also be great if we could constrain a JSON column to a basic schema

**Comment by pchasco** [comment]
If you want to constrain to basic schema, why not simply use a collection
field?

**Comment by ganigeorgiev** [comment]
I agree with @pchasco - if you need schema constraints it would be better to create a collection.

The UX definetelly could be improved, for example by adding a button in the relation field dropdown for creating "inline/sub" collections, so it doesn't interrupt the developer flow, but that will be handled separately (_most likely together with the planned changes for the relation dropdown in #100_).

**Comment by lukepighetti** [comment]
Consider a post that contains a bunch of links. We might not want a collection of links with a relation. We might opt for storing them as JSON. But we may want to ensure that the JSON conforms to a certain shape. That would be an example use case.

**Comment by pchasco** [comment]
You could confirm that as a part of data validation, or have a collection
with links. To me, the purpose is a json column in a relational database is
specifically to store arbitrary data.

A relational database already implements a powerful solution to the use
case, and duplicating that feature for json seems like a suboptimal way to
expend development effort.

**Comment by ganigeorgiev** [comment]
@lukepighetti I understand the possible use cases for this, but our implementation will be always limited and I'm sure that there will be cases where someone will want for example support for union types, types for array element, data validation, required fields, etc. and this will just add an extra layer of complexity to the existing collection schema management.

At least for v1.0.0, I'm not planning adding json field schema support. It would be better to invest the time to create a new "Repeatable/Group" field type where inside the group you'll be able to create your links structure just by adding other regular fields to the repeatable group.

**Comment by lukepighetti** [comment]
Perhaps doing the join is not as expensive as I imagine, I supposed I'd have to benchmark it.

**Comment by ganigeorgiev** [comment]
Just a note for anyone who is following here - this is already implemented and will be available in the next v0.8.0 release together with the users refactoring from #376.

Some implementation details:
- the json field props are supported for both sort and filter operations
- array fields are supported using the index of the array element. For example, if we want to query the first array element:
   ```
   myJsonField: {
      "a": [{"item": 1}, {"item": 2}]
   }
   
   myJsonField.a.0.item = 1
   ```
- trying to query a json prop with spaces or special characters outside of the currently allowed [fexpr identifier grammar](https://github.com/ganigeorgiev/fexpr#identifiers) will result in error (aka. the json prop in `{"a  b": 1}` is not queryable).

**Comment by pchasco** [comment]
Awesome! Any advice on indexing? Will we be able create indexes for JSON
property paths from the web?

**Comment by ganigeorgiev** [comment]
@pchasco Technically, SQLite allows creating indexes on expression (aka. `JSON_EXTRACT(...)`), so it is possible, but managing indexes from the Admin UI will be handled as part of issue https://github.com/pocketbase/pocketbase/issues/345 and https://github.com/pocketbase/pocketbase/issues/544 (this will be after v0.8.0 release since it already comes with a lot of changes).

**Comment by ganigeorgiev** [comment]
This is now available as part of the [v0.8.0-rc1 pre-release](https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1).

**Comment by FNG-2002** [comment]
Hello, didn't want to open a new feature suggestion as it fits to this.

Are there any plans on adding more JSON operator for sqlite like JSON_GROUP_ARRAY() ?
Then we can do stuff like this:

`SELECT json_object( 
    'PetId', PetId, 
    'PetName', PetName,
    'TypeId', TypeId 
    )
FROM Pets;`

to get:

```{"PetId":1,"PetName":"Homer","TypeId":3}
{"PetId":2,"PetName":"Yelp","TypeId":1}
{"PetId":3,"PetName":"Fluff","TypeId":2}
{"PetId":4,"PetName":"Brush","TypeId":4}
```

Running it on the data.db file works, but not on the View SQL for example.

Thanks :)

**Comment by FNG-2002** [comment]
Thank you so much! I actually forgot to provide an alias to json_object in the SELECT Statement.
