### ISSUE TITLE
file Upload wrong random suffix

### ISSUE THREAD

**Issue by fly1ted** [pocketbase/pocketbase#4236]
Strangely when I upload file named `ff.png` the suffix gets added without underscore _. Same happens for other files with two letters in the name.

<img width="658" alt="image" src="https://github.com/pocketbase/pocketbase/assets/8587695/7c1709ce-d52a-42fd-8250-a268e7658a9c">
<img width="659" alt="image" src="https://github.com/pocketbase/pocketbase/assets/8587695/51f5f469-c810-4c78-8b2a-229c9c34ef99">

**Comment by ganigeorgiev** [comment]
This is intentional and the behavior may change in the future but for now short file names (< 3 chars) are combined with extra random part.
