### ISSUE TITLE
Validation for a unique constraint/index on a "text" field is bugged

### ISSUE THREAD

**Issue by MobinAskari** [pocketbase/pocketbase#4238]
Pocketbase version: 0.21.1

The collection schema:
```
{
        "id": "33k8eew6vs8xu2o",
        "name": "words",
        "type": "base",
        "system": false,
        "schema": [
            {
                "system": false,
                "id": "ielji3mk",
                "name": "word",
                "type": "text",
                "required": true,
                "presentable": false,
                "unique": false,
                "options": {
                    "min": 5,
                    "max": 5,
                    "pattern": ""
                }
            },
            {
                "system": false,
                "id": "aznshfgs",
                "name": "number_id",
                "type": "number",
                "required": true,
                "presentable": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "noDecimal": true
                }
            }
        ],
        "indexes": [
            "CREATE UNIQUE INDEX `idx_x6YKA9s` ON `words` (\n  `word`,\n  `number_id`\n)"
        ],
        "listRule": "",
        "viewRule": "",
        "createRule": null,
        "updateRule": "",
        "deleteRule": null,
        "options": {}
    }
```

It will not throw an error if the "word" field is not unique and just creates the record:
![Screenshot (56)](https://github.com/pocketbase/pocketbase/assets/132358316/0aa6a4e0-46b1-4c74-8b70-90863f291805)

It works on the number_id field, and if the number_id value is not unique, it will also error on the "word" field
![Screenshot (55)](https://github.com/pocketbase/pocketbase/assets/132358316/afcb4e6b-18f4-4136-9576-521a63ddb9f7)

Trying to set a unique index only on the "word" will result in an error:
![Screenshot (57)](https://github.com/pocketbase/pocketbase/assets/132358316/42a566f5-6eae-4fa7-b157-838bf709d234)

But it works if it's on both of the "number_id" and "word" fields, but will only show a count of 1:
![Screenshot (58)](https://github.com/pocketbase/pocketbase/assets/132358316/4dbad975-d18c-49c7-be00-9db609dc6450)

**Comment by ganigeorgiev** [comment]
It is not "bugged" and it works as intended.

Having a combined fields unique index require the combined value of your fields to be unique (aka. `tests + 1` and `tests + 2`).
Having a single field unique index requires **only** the specific field to be unique and in your case it fails because you already have duplicated "tests" value for the "word" field.

**Comment by MobinAskari** [comment]
> It is not "bugged" and it works as intended.
> 
> Having a combined fields unique index require the combined value of your fields to be unique (aka. `tests + 1` and `tests + 2`). Having a single field unique index requires **only** the specific field to be unique and in your case it fails because you already have duplicated `tests` value for the `word` field.

Sorry for wasting your time, I wasn't aware of combined unique indexes 🙏
