### ISSUE TITLE
Feature: PocketBase as Auth Provider

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4239]
# PocketBase as Auth Provider
Be able to register in one PocketBase DDBB and login into another. This will allow users to connect DDBBs, yes. One single login for the rest of us.
Imagine to have a community, and you want to create a subscription license program, but you have other products, how I can achive to register and license a user of different sites in one single license web-app.
The idea is to be able to identify my users or myself between my PocketBases.

**Comment by ganigeorgiev** [comment]
This was asked several times before but at least for v1 there are no plans for this (see also https://github.com/pocketbase/pocketbase/issues/3567).
