### ISSUE TITLE
[Feature request] Persist cron task information in DB

### ISSUE THREAD

**Issue by kalmard-infinite** [pocketbase/pocketbase#4250]
Cron task information is lost when PocketBase is restarted / redeployed. For rarely running tasks (e.g. weekly) this may cause the task to never run at all, if PB is restarted more frequently than the period. Storing cron task information (e.g. last run) in the DB could solve this.

**Comment by ganigeorgiev** [comment]
Cron tasks are currently managed as code, aka. either as part of your `pb_hooks` or as part of your Go code, so there is no way for "information lost" on "restarted / redeployed".

If you use the JS pb_hooks, make sure that the pb_hooks are deployed toghether with your binary (if you are using Docker you can `COPY` the directory as part of the image).
The same apply for the `pb_migrations`.

Option to manage the cron tasks from the Admin UI (start/stop) exists in my todo but remains a very low priority and out of the scope for v1 at least for now.

**Comment by ganigeorgiev** [comment]
Also note that the cron tasks are not dependent on the time when the server was started/restarted.

If your schedule a cron task like: "*/30 * * * *", this will run on every half and hour (aka. 14:00, 14:30, 15:00, 15:30, etc.).
