### ISSUE TITLE
null for boolean field

### ISSUE THREAD

**Issue by step135** [pocketbase/pocketbase#4258]
Is already possible to set a boolean field to `null` by default? I see it as `false` by default, but it is already giving me information that user went for `false`. **And it is not true!!!** I don't know any other database that would disallow developers of `null`/unset value.

**Comment by ganigeorgiev** [comment]
This was an early decision and an intended behavior. The reasoning for this is explained in https://github.com/pocketbase/pocketbase/issues/122#issuecomment-1186466209.

For now there are no plans to add option for supporting null for the `bool` fields but there are plans in the future to allow custom fields, which eventually will enable users to define their own fields and constraints.

**Comment by step135** [comment]
Managing custom fields creates extra work for developers and it is not nice solution as this straightforward one. Sqlite has nullable data types, so why not making all of them here too?

**Comment by ganigeorgiev** [comment]
Because it is easier to work with the fields when you know that they always have a value.
From the linked comment above:

> This would also simplify the conditional checks pointed by Lex-2008 and in general it will be easier to integrate with languages that has sound null safety (eg. Dart).
