### ISSUE TITLE
Feature Request: Inline SQL editor

### ISSUE THREAD

**Issue by raizdev** [pocketbase/pocketbase#4266]
It would be nice to have an sql editor in pocketbase ui to fire some sql queries.

For example, if I want to update all the record in pocketbase from status x to y i have to write a migration file and restart the services to fire migration. In our cluster we use docker swarm then you will probably understand that is is not very convenient

**Comment by ganigeorgiev** [comment]
This will be implemented eventually as part of https://github.com/pocketbase/pocketbase/issues/2236, but remains a low priority.
