### ISSUE TITLE
Can't use top level functions in javascript hooks

### ISSUE THREAD

**Issue by nevenerep** [pocketbase/pocketbase#4269]
Route doesn't work when I try to call a top-level function. The code works fine when running it in a command.

"{"code":400,"message":"Something went wrong while processing your request.","data":{}}"

version 0.21.1

```
function test(){ return "test" }

routerAdd("GET", "/test", (res) => {
	const output = test();

	return res.json(200, { output });
})
```

When I run this code in a try-catch block, the error is "2024/01/30 15:24:13 ReferenceError: test is not defined"

EDIT: this also appears to happen with variables declared outside of the routerAdd scope. So a better title for this would be "Can't access any variables outside of routerAdd scope"

**Comment by JayJamieson** [comment]
@nevenerep I believe this is documented in the extending with Javascript. See [handlers scope](https://pocketbase.io/docs/js-overview/#handlers-scope).

**Comment by ganigeorgiev** [comment]
As mentioned above this is a known limitation. Please check the linked docs above.
