### ISSUE TITLE
No type declaration for require() while using typescript

### ISSUE THREAD

**Issue by nevenerep** [pocketbase/pocketbase#4270]
Following code shows an error in VS Code

```
/// <reference path="../pb_data/types.d.ts" />

const global = require(`${__hooks}/global.ts`)
```

"Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.ts(2580)"

**Comment by ganigeorgiev** [comment]
The same as https://github.com/pocketbase/pocketbase/issues/4271.
