### ISSUE TITLE
No type declaration for "module" when using module.exports in Typescript

### ISSUE THREAD

**Issue by nevenerep** [pocketbase/pocketbase#4271]
VSCode: "Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.ts(2580)"

```
/// <reference path="../pb_data/types.d.ts" />

module.exports = {
	test(){ return "test" }
}
```

**Comment by ganigeorgiev** [comment]
The generated types are just optional helpers for your lsp.
They are not required for your application to work and you don't have to use the explicit reference directive.
