### ISSUE TITLE
Feature Request : Add support for Cloudflare R2 (alternative to Amazon S3)

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/pocketbase#4274]
Those two products are very similar, the docs of Cloudflare specify : https://www.cloudflare.com/developer-platform/r2/

> Avoid vendor lock-in with our S3-compatible API

There is a whole doc on S3 API Compatibility : https://developers.cloudflare.com/r2/api/s3/api/

It is not a 1-to-1 and features have some small differences, but overall it might be a nice thing to add

In some scenarios R2 Pricing is advantageous to S3, especially on the "zero egress fees" : https://www.cloudflare.com/pg-cloudflare-r2-vs-aws-s3/

**Comment by ganigeorgiev** [comment]
You can use any S3 compatible storage (not just AWS).

> Cloudflare R2 has a free plan if you want to do tests on it

I think they require billing information upfront and I avoid entering my payment details. User contributions to "fix" it are welcomed. As mentioned in the linked issues, it is either a R2 compatibility issue with their S3 APIs or some obscure but with the official `aws-sdk-go` library.

**Comment by dedo1911** [comment]
@ganigeorgiev I'm having the same issue with MinIO, I can provide you a bucket for testing.
Files are being uploaded correctly, but no thumbs are being generated for svg (I'm not sure that's expected), but still files cannot be downloaded using PB api.
Using any other S3 client works perfectly and files are intact.

I've tried other file formats like png and I don't have any issue at all.

**Comment by ganigeorgiev** [comment]
@dedo1911 `svg` are vectors and we don't do any extra transformations to them. The currently supported thumb image formats are `image/png`, `image/jpg`, `image/jpeg`, `image/gif` (only the first frame).

**Comment by dedo1911** [comment]
@ganigeorgiev ok I didn't check that out yet. but still it should download something instead of 0 bytes or print an error somewhere:

<img width="761" alt="image" src="https://github.com/pocketbase/pocketbase/assets/1364496/19a4fcfc-94d9-408f-8e11-91a4b8419ca1">

**Comment by ganigeorgiev** [comment]
I don't think this is PocketBase related. For MinIO setup please check the guide in https://github.com/pocketbase/pocketbase/discussions/90#discussioncomment-3165097.

It is possible that there is some bug with the `aws-sdk-go` but the last time I tested I wasn't able to reproduce it with Vultr, DigitalOcean and Wasabi S3 offerings.

**Comment by dedo1911** [comment]
It's uploading/downloading every other type of file, I'm using it for both storage and backups on multiple websites without any other issues.
I tried to create a small standalone app using `aws-sdk-go` to download an svg and it downloads properly.
Problem is I don't see any useful log to understand what's going on on PB side

**Comment by ganigeorgiev** [comment]
Please open a new issue ideally with a minimal code sample and the file you are testing.
