### ISSUE TITLE
Unable to unmarshal from migrations schema at 32 bit systems

### ISSUE THREAD

**Issue by ramadhanafif** [pocketbase/pocketbase#4280]
When I tried to crosscompile pocketbase to ARMv7 (RaspberryPi) with this build command:
```
GOOS=linux GOARCH=arm CGO_ENABLED=0 GOARM=7 go build -o my-db-armv7.
```

And running them (with QEMU or native), it reports an error:
```
Error: Failed to apply migration 1706688626_collections_snapshot.go: json: cannot unmarshal number 5000000000 into Go struct field Collection.schema of type int
```

Which is strange, since the same code is running fine on my pc (x86 64-bit system). 

After a bit of tinkering, I found the offending part from the migration json data is:
```json
"options": {
	"mimeTypes": [
		"model/gltf-binary"
	],
	"thumbs": [],
	"maxSelect": 1,
	"maxSize": 5000000000,
	"protected": false
        }
```

Which I think is caused by the Collection.schema is following system native `size`. In my PC is 64-bit, while ARMv7 is 32-bit. 

I believe this could be fixed by changing the size from generic `int` to `int64`. However, I am not sure where in the code base I should make the changes to implement this.

**Comment by ganigeorgiev** [comment]
There are no plans for now to change field types.

If you want to modify it on your own you can find the options struct in https://github.com/pocketbase/pocketbase/blob/master/models/schema/schema_field.go#L628.

I'll consider testing it on 32bit system and eventually updating it during the planned refactoring but there are no ETAs.
