### ISSUE TITLE
Multiple language support?

### ISSUE THREAD

**Issue by jhh78** [pocketbase/pocketbase#4288]
Multiple language input is not supported?
I tried entering Japanese, but it got stuck in validation.
If there is a way to avoid this problem, please let me know.
<img width="339" alt="image" src="https://github.com/pocketbase/pocketbase/assets/51219166/596393b9-dcaa-4787-af2a-cadabae10b5a">

**Comment by ganigeorgiev** [comment]
See https://github.com/pocketbase/pocketbase/discussions/2752, https://github.com/pocketbase/pocketbase/issues/3697, https://github.com/pocketbase/pocketbase/issues/2462.

The builtin `username` field is currently limited and its regex cannot be changed. More control over the system fields will be available in the future but there are no fixed ETAs.
