### ISSUE TITLE
Website small typo

### ISSUE THREAD

**Issue by dxps** [pocketbase/pocketbase#43]
As I couldn't find the website docs to send a PR, I'm writing here.

In the homepage, there's a small typo:
> Dart SDK is comming soon
and it should be:
> Dart SDK is coming soon

This is an interesting project! Thanks for doing and sharing it! :pray:

**Comment by ganigeorgiev** [comment]
Thanks, should be fixed now.

_The source of the documentation is not public yet. I need to find time to clean it up and document the build process before open source it. You can follow this discussion -https://github.com/pocketbase/pocketbase/discussions/36_
