### ISSUE TITLE
Add dark mode theme

### ISSUE THREAD

**Issue by okabrionz** [pocketbase/pocketbase#4303]
## Description

Currently PocketBase lacks a dark theme option. It would be very useful to have a dark color scheme as an alternative theme.

A dark color scheme is easier on the eyes for users who spend a lot of time using the admin dashboard, and allows the app to blend in better for tools used at night. Many popular apps have added dark themes due to popular request.

## Expected Behavior

- A "Dark mode" toggle switch under User Settings
- When Dark mode is enabled:
  - The overall background changes to a dark gray / black
  - Text and foreground colors change to light gray
  - Borders change to match the darker background
- The setting should persist when user leaves or comes back to the app

## Suggested Implementation

- Add a boolean column `dark_theme` to user settings table
- Add a toggle to UI that updates this user setting value 
- Update CSS stylesheet with additional classes such as `.dark-theme` 
- Apply the dark theme styling overrides whenever the `dark-theme` class is found in the body

Please let me know if any other details are needed!

**Comment by ganigeorgiev** [comment]
There is already issue for this but remains a very low priority after the planned Admin UI refactoring - https://github.com/pocketbase/pocketbase/issues/407.

**Comment by rgfx** [comment]
I created a Tapermonkey script to enable a dark theme. Works really well. 

https://github.com/rgfx/pocketbase-dark
