### ISSUE TITLE
Problem with emoji in tags

### ISSUE THREAD

**Issue by siamakabi** [pocketbase/pocketbase#4308]
Hello
After the update
The presence of emoji in the content tags causes errors.

![یقثغفقتغفنعغنتامنتمنت](https://github.com/pocketbase/pocketbase/assets/79061836/6d594d96-ce11-4b32-af67-6305500636ee)
![Untitlffffffed](https://github.com/pocketbase/pocketbase/assets/79061836/eb3364c0-f964-46f7-9d79-a5973c2ec370)

**Comment by ganigeorgiev** [comment]
I don't understand but the above error doesn't look PocketBase related.

**Comment by siamakabi** [comment]
I am very sorry
I sent it wrong
