### ISSUE TITLE
Database Transection

### ISSUE THREAD

**Issue by jstbyte** [pocketbase/pocketbase#431]
Critical data Transection Features Is Required.

**Comment by ganigeorgiev** [comment]
Hi, bulk inserting records in a transactional manner will be handled in https://github.com/pocketbase/pocketbase/issues/48.

When [PocketBase used as framework](https://pocketbase.io/docs/db-queries/), you can execute multiple queries within a single transaction using directly the dao service, eg. [`dao.RunInTransaction(...)`](https://github.com/pocketbase/pocketbase/blob/master/daos/base.go#L61) (_the documentation will be improved in the near future_).
