### ISSUE TITLE
Feature Request: allow health check endpoint to respond to HEAD requests

### ISSUE THREAD

**Issue by james2doyle** [pocketbase/pocketbase#4310]
I'm currently using that endpoint to check the status of my server on Pockethost. Currently, it looks like `/api/health` will respond to `HEAD` requests with 404.

I think it would be ideal if it just responded with a `2xx` code instead of 404. And ideally an empty body.

**Comment by motdde** [comment]
Hello @james2doyle ,

Would there be a specific use case where the current `GET` request wouldn't be the ideal (work as intended)?

**Comment by ganigeorgiev** [comment]
Support for `HEAD /api/health` was added in `master` and it will be available with the next minor release.
