### ISSUE TITLE
Documentation: SvelteKit SSR Example incorrect

### ISSUE THREAD

**Issue by ww-wolt** [pocketbase/pocketbase#4316]
Last line from the SvelteKit SSR Integration Example from the PocketBase JS SDK documentation:
```
// send back the default 'pb_auth' cookie to the client with the latest store state
response.headers.append('set-cookie', event.locals.pb.authStore.exportToCookie());
```
The PocketBase documentation proposes setting the cookie via `headers.append(...)`. However the SvelteKit documentation officially states that this is not recommended or not working. 
> You cannot add a set-cookie header with setHeaders — use cookies.set(name, value, options) instead.

https://kit.svelte.dev/docs/load#headers

In my tests the `headers.append(...)` code for cookies still somehow works, but only when Javascript is enabled. When I turn off JavaScript in the browser and try to login (via SvelteKit form actions) I get an 405 Method Not Allowed error, which seems to be related to this unofficial way of setting the cookies: https://stackoverflow.com/questions/73098227/sveltekit-post-method-not-allowed-on-endpoint

Unfortunately I have not yet found a better solution which makes use of `cookies.set(name, value, options)`. If I just replace `headers.append(...)` with `cookies.set(...)` SvelteKit outputs the following error

> Error: Cannot use `cookies.set(...)` after the response has been generated.

There seems to be a general conflict. SvelteKit doesn't like setting cookies after the response has already been generated, however PocketBase likes to set the cookie after the response to reflect the latest auth store changes in the cookie.

**Comment by ganigeorgiev** [comment]
> You cannot add a set-cookie header...

I think this is only for the `load` function. The example uses `hooks.server.js`.
If you have a suggestion for better example feel free to open a PR to the [JS SDK repo](https://github.com/pocketbase/js-sdk).

**Comment by ganigeorgiev** [comment]
_And just as a side-note because a lot of users seems to jump straight to JS SSR without actually needing it, please check the comments in https://github.com/pocketbase/pocketbase/discussions/3792#discussioncomment-7620032 discussion._

**Comment by ww-wolt** [comment]
Thanks a lot for the quick response and the links provided. I was long time thinking of whether I should go with the SSR approach or use the direct communication with PB. I agree with the opinion of einarpersson in the linked discussion that it's not so clear how to combine the two approaches in a reliable way. 

In my case I need the SvelteKit server layer for certain scenarios, for example for additional Zod form validation or granting the user access to data of a paid third-party API only when correctly authenticated over PB. Because I need it anyways in certain cases I decided that it might be easier to do everything via JS SSR to circumvent edge cases that might occur when using both in combination.
