### ISSUE TITLE
Bug: Cannot disable some auth providers

### ISSUE THREAD

**Issue by pagoru** [pocketbase/pocketbase#4322]
I cannot disable auth providers if I don't fill some inputs and doesn't make a lot of sense.

![image](https://github.com/pocketbase/pocketbase/assets/1551265/604e991b-39c0-43ee-a155-816a0ce65867)

**Comment by ganigeorgiev** [comment]
I've submitted a fix for the js validations in `master` and it will be available with the next minor v0.21.3 release sometimes later this weekend.
