### ISSUE TITLE
UI: Lack of Visual Feedback Upon Successful Backup Restoration

### ISSUE THREAD

**Issue by babakfp** [pocketbase/pocketbase#4324]
Hi

https://github.com/pocketbase/pocketbase/assets/44144724/981d4243-4961-4e9a-b8e7-6c307b18c61a

I'm not sure if the same issue exists when backup restoration fails.

PocketBase version: `0.21.1`

**Comment by ganigeorgiev** [comment]
There is no easy way to do this because on backup restore we restart the app in the background and in my opinion it is not worth the dev effort.

**Comment by ganigeorgiev** [comment]
_Eventually I'll consider adding the backup operation as part of the planned job queue implementation sometime in the future._
