### ISSUE TITLE
Expand not working

### ISSUE THREAD

**Issue by gladson** [pocketbase/pocketbase#4331]
I just installed v0.21.3. Using the API, expand does not work at all.

![image](https://github.com/pocketbase/pocketbase/assets/1013698/a6fb455c-2ee6-42c0-8c8f-52df741dc228)

![image](https://github.com/pocketbase/pocketbase/assets/1013698/2afbb184-5b77-4039-9fd2-0a7996bdb7c9)

![image](https://github.com/pocketbase/pocketbase/assets/1013698/92ad747f-032f-4f22-8f4c-a5da49716a3e)

or 

![image](https://github.com/pocketbase/pocketbase/assets/1013698/8f76414f-774e-4df2-8d21-75260a83d013)

I followed the documentation but the action did not occur

![image](https://github.com/pocketbase/pocketbase/assets/1013698/68978fb5-bcb5-4ddf-85e4-e755c2d50f6a)

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. As mentioned in the docs make sure that your client request satisfy the View API rule of the related collection (in your case cities).

**Comment by gladson** [comment]
I understand, the View API rule is very important for the relationship to be successful and expand can be used.

Thanks.

To be able to appear, I had to disable the List/Search and the View rule to guarantee access to any request for now and it resolved it.

![image](https://github.com/pocketbase/pocketbase/assets/1013698/3fc047aa-7c0c-47e5-bbe0-b7e43fb705be)
![image](https://github.com/pocketbase/pocketbase/assets/1013698/a653c532-54d2-4169-a3d7-f3cf73ef424c)
