### ISSUE TITLE
How to apply filter in reverse relation expansions

### ISSUE THREAD

**Issue by aasutossh** [pocketbase/pocketbase#4334]
I have schema `products` and `product_details`. `product_details` contains the foreign key of `products` as column name `product`.
I want to filter `products` whose `product_details.details.battery_size=5000`.
`product_details.details` is a JSON field.

How do I do that?

**Comment by ganigeorgiev** [comment]
Back/indirect relation filtering is not supported at the moment (_it is in the roadmap_).

If you have other questions please use the [Discussions](https://github.com/pocketbase/pocketbase/discussions).
