### ISSUE TITLE
Issue with File Names Being Forced to Change Upon Upload

### ISSUE THREAD

**Issue by melodysdreamj** [pocketbase/pocketbase#4339]
When uploading a file in Dart, the name is forcibly changed. The actual name that appears is `example_document_NDxrvnruBf.txt` This is a serious issue because if we don't know the file name, we can't download it. This is especially problematic for images, as there's no way to obtain the image URL.

# Reproduction

```
import 'dart:typed_data';

import 'package:pocketbase/pocketbase.dart';
import 'package:http/http.dart' as http;

void main() async {
  Uint8List? imageByte = await downloadImageAsBytes('https://www.nme.com/wp-content/uploads/2021/02/iu-lilac-photo-edam-entertainment@2000x1270-1392x884.jpg');

  try {
    final pb = PocketBase('http://127.0.0.1:8090');

    var record = await pb.collection('files').create(
      files: [
        http.MultipartFile.fromString(
          'document', // the name of the file field
          'example content...',
          filename: 'example_document.txt',
        ),
      ],
    );
    print(record.id);
    print(record.collectionId);
    print(record.updated);
    print(record.created);
    print(record.collectionName);
    
    // file name changed
  } catch (e) {
    print(e);
  }
}
```

**Comment by ganigeorgiev** [comment]
This is an intended behavior and was discussed several times in the past (for example https://github.com/pocketbase/pocketbase/discussions/210).

>  This is a serious issue because if we don't know the file name, we can't download it.

That is not true. The uploaded file name will be available as part of the created record data - `record.getStringValue("yourFileField")` or `record.getDataValue<String>("yourFileField")` (_the data getters will be further simplified in the future to just `record.get<String>("yourFileField")`_).

To get a file url, check the Dart example from https://pocketbase.io/docs/files-handling/#file-url or:

```dart
cost
final url = pb.files.getUrl(record, record.getStringValue("yourFileField"), thumb: '100x250');
```

**Comment by melodysdreamj** [comment]
Thank you for your kind help!
