### ISSUE TITLE
`z-index` issue when previewing a video

### ISSUE THREAD

**Issue by babakfp** [pocketbase/pocketbase#4345]
Hi

![image](https://github.com/pocketbase/pocketbase/assets/44144724/50de3e6a-bbe0-4a58-8952-9165ea42698e)

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it with Chrome 121.0.6167.139 and Firefox 120.0.1.

What browser do you use?

**Comment by babakfp** [comment]
I couldn't reproduce it either.
I remember updating PocketBase to the latest version, but I don't know if this was before or after the issue.
Anyway, sorry for wasting your time.
