### ISSUE TITLE
Returning just ID when using getFullList with filter

### ISSUE THREAD

**Issue by bitpoke-YT** [pocketbase/pocketbase#4354]
Hello, I'm trying to make an app in flutter which need to get just the ids from a filtered GetFullList. I was wondering if there was a way to do this and if not, could it be added to the road map.

**Comment by ganigeorgiev** [comment]
It should be already already supported if you pass the `fields` query parameter:

```dart
final records = await pb.collection('example').getFullList(
  filter: '...',
  fields: 'id'
);
```
(for available query parameters you can refer to the API Preview docs in the Admin UI or check the general [Web API docs](https://pocketbase.io/docs/api-records/)).

If you have other questions please use the [Discussions](https://github.com/pocketbase/pocketbase/discussions).
