### ISSUE TITLE
HTTP update PATCH request triggers CORS error

### ISSUE THREAD

**Issue by discollizard** [pocketbase/pocketbase#4366]
I've been trying to update an entry in the database using the REST API in PocketBase, but it throws me a CORS error 
![image](https://github.com/pocketbase/pocketbase/assets/49206310/47b8fd29-9e9e-4af1-b10a-a112c21b113d)

I'm using SvelteKit and I've tried using the fetch API both from the client and the server, and the same error occurs.

![image](https://github.com/pocketbase/pocketbase/assets/49206310/21233c10-4108-4e15-bad7-43bbec981329)

I haven't found any kind of CORS allowed methods configuration for pocketbase while searching online. I've tried this call both on edge and on chrome. 

I found many resources explaning how to deal with CORS origin errors on PB but none talking about CORS methods.

Thanks in advance.

**Comment by ganigeorgiev** [comment]
This is not an issue with PocketBase because by default we allow all origins (unless you've explicitly specified the `--origins` flag).

Something else is happening here but without detail about your setup or at least some minimal reproducible steps I don't think I can help you.

**Comment by ganigeorgiev** [comment]
_Side-note: it is possible that the CORS issue to be caused by a failed request related to `localhost` vs `127.0.0.1` IPv4/IPv5 binding order, or in other words - try with `http://127.0.0.1:8090` as base address (see https://github.com/pocketbase/js-sdk/issues/21)._
