### ISSUE TITLE
Feature: Geospatial support

### ISSUE THREAD

**Issue by kedare** [pocketbase/pocketbase#4375]
Hello :)

I would love to see the possibility to use geospatial features on Pocketbase and on the sqlite database.

This is apparently possible using https://www.gaia-gis.it/fossil/libspatialite/index on sqlite (however I think pocketbase as it's pure-go vesion of sqlite ?)

Bonus if there is a map view in the admin interface when editing the entities.

Thank you.

**Comment by ganigeorgiev** [comment]
Support for loading custom SQLite builds like the linked SpatiaLite, SQLCipher will be available with the [planned refactoring](https://github.com/pocketbase/pocketbase/discussions/4355), but there are no plans for now to create builtin fields specific to that.
