### ISSUE TITLE
Feature request: Plugin extension providing authentication and authorization via API keys

### ISSUE THREAD

**Issue by BrettFraley** [pocketbase/pocketbase#4392]
Hello, I'm entirely new to Pocketbase. I have been doing lots of research before committing
to any development on my use case, and am happy to say that PB definitely meets my needs.

***My Use Case***
I'll be using PB for storing a large amount of databases containing hundreds of tables that already exist in my system.
I'm building a service layer to coordinate running multiple instances of Pocketbase, and working toward
a design that incorporates authentication and authorization using traditional API keys.

If this is a feature that the Pocketbase team is interested in, meaning the API key based auth (not the coordination of multiple instances), I'd be happy to work on this with a more general audience in mind and contribute back to the project.

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/3118.

User contributions for external plugins like the ones in https://github.com/pocketbase/pocketbase/tree/master/plugins. There are is promise that it will be merged in the main repo but if there is enough user demand I may reconsider it.
