### ISSUE TITLE
Reasons for doing, guidance on choosing it over the alternatives

### ISSUE THREAD

**Issue by dxps** [pocketbase/pocketbase#44]
Hi PocketBase community!

It would be helpful to document why this Firebase alternative exists, over the others like Supabase or AppWrite, for example.

While it might be premature to offer a complete material, at least it can be started and extended over time.
And this could also guide people why they should pick PocketBase, based on features and use cases.

Keep up the great work!

**Comment by ganigeorgiev** [comment]
Thanks for the suggestion. I'd try to find time in the future and will consider adding a comparison page with the other similar platforms.

**In the meantime, for those who stumbled on this issue:**
PocketBase was create to assist me in the development for my other open source project - [Presentator v3 #183](https://github.com/presentator/presentator/issues/183).
I wanted a self-contained portable platform that can be deployed with almost no configurations on any server (_you'll find that most of the Presentator issues are support related asking for help with self-hosting the platform_).
It certainly it's not capable to handle every case, but for small/medium sized applications, internal tools and such PocketBase is a great alternative to the existing open source alternatives (just to mention some - [Supabase](https://github.com/supabase/supabase), [Nhost](https://github.com/nhost/nhost), [Appwrite](https://appwrite.io/), [Appsmith](https://github.com/appsmithorg/appsmith) and probably more).
