### ISSUE TITLE
Serving with certbot certificate

### ISSUE THREAD

**Issue by KianBrose** [pocketbase/pocketbase#441]
Hello!
I run an nginx server with multiple websites at the same time using Cloudflare as a DNS. The problem is that in Cloudflare, I use the "Strict" option which requires me to create my own certificate and serve it when doing proxy passes. The problem I am facing now is that pocketbase doesn't have the option to let me use my own certificate.

Here is my configuration for other projects:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name pb.example.com;
    ssl_certificate /etc/letsencrypt/live/pb.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pb.example.com/privkey.pem; # managed by Certbot

    location / {
        if ($http_user_agent = Mozilla/4.0){
            return 503;
        }
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://192.168.0.125:8090/;
        proxy_redirect off;
        #try_files $uri $uri/ /index.php?$args;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name pb.example.com;

    return 301 https://pb.example.com$request_uri;
}
```
How can I make pocketbase work together with Certbot certificates?

**Comment by ganigeorgiev** [comment]
> The problem I am facing now is that pocketbase doesn't have the option to let me use my own certificate.

If you use nginx as a reverse proxy with certbot you don't need to load the custom certificate in PocketBase. Just start it with only the `--http` flag:

```
./pocketbase serve --http="127.0.0.1:8090"
```
