### ISSUE TITLE
feature request: add an official made with pocketbase badge

### ISSUE THREAD

**Issue by matthewjpyates** [pocketbase/pocketbase#4414]
Here is an attempt at a badge for made with Pocketbase.

![pocket_base_made_with](https://github.com/pocketbase/pocketbase/assets/49790388/1d31f591-e652-4e60-bcde-8d3e2dc37311)

I want to put something on a small webapp I am making to give credit to pocketbase, thought other might want to as well.

**Comment by ganigeorgiev** [comment]
Community contributions are welcomed but I don't think this needs to be part of the repo.

If someone needs it, you can find an SVG version of the logo in https://github.com/pocketbase/site/blob/master/static/images/logo.svg
