### ISSUE TITLE
Need to use a Custom ID less than 15 characters.

### ISSUE THREAD

**Issue by neos04** [pocketbase/pocketbase#4415]
Hi, I recently planned to use pocketbase as the backend for a device inventory management system for my Workplace due to it being open source, it's simplicity, and how easy it is to host. 

However I only just now realized that the default ID settings are gonna cause me and issue for the Device table. The company already used a specific ID convention for each Device using 6 characters for eg 'TAB100', but with pocketbase I have to use a 15 character string.

Now I defaulted to using the random ID, and singing 'TAB100' in a next field called 'device_name'. But then when it comes to using it as a Foreign Key for eg in 'Assignment' or 'Log' table it will be difficult to recognize the device as a random 15 Character string.

Is there a workaround? Or can this be resolved as soon as possible?

**Comment by ganigeorgiev** [comment]
The system `id` field length cannot be changed with the web APIs at the moment but more control over the system fields will be added during the [planned refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) (there are no fixed ETAs or deadlines).

> But then when it comes to using it as a Foreign Key for eg in 'Assignment' or 'Log' table it will be difficult to recognize the device as a random 15 Character string.

You can mark your `device_name` field "Presentable" from the field options.

**Comment by neos04** [comment]
First of thanks for the timely response, and yes I did mark the `device_name` field as presentable.

The issue was mainly a concern for the frontend for eg. when referencing data through a data table or creating new records while maintaining proper relationships...

However ig a workaround for now could be cutting the direct relationship and instead using the `device_name` column as the main reference to the Device table.

Nevertheless, love what you're doing with pocketbase man, keep it up 🙏🏽🔥.
