### ISSUE TITLE
PocketBase Collection Relations Automation

### ISSUE THREAD

**Issue by mfshaho** [pocketbase/pocketbase#4419]
e.g. i have two collections 

1. Publications
2. Authors

when i make a Relation data type in Publications Collection and i connect it to an existing Authors row or create a new one, it won't show in the Authors Collection that i have Publications related to this row in this Collection!

i have to add them manually!

**Comment by ganigeorgiev** [comment]
This already exists in the [roadmap](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=indirect&pane=issue&itemId=32121831) but remains a low priority.
