### ISSUE TITLE
Feature Request: Return ID on unique failure

### ISSUE THREAD

**Issue by teamcoltra** [pocketbase/pocketbase#4426]
Currently you get:

{
	"code": 400,
	"message": "Failed to create record.",
	"data": {
		"name": {
			"code": "validation_not_unique",
			"message": "Value must be unique."
		}
	}
}

If it could actually be

{
	"code": 400,
	"message": "Failed to create record.",
	"data": {
		"name": {
			"code": "validation_not_unique",
			"message": "Value must be unique."
		}
             "id": "3xk3937cx333l14"
	}
}

Then we don't have to make an additional call to get that ID (which I would guess is frequently the next call when someone gets a unique error)

**Comment by ganigeorgiev** [comment]
No sorry there are no plans for this out of the box as it will require a new different error response and it will complicate the validations for very little benefit.
