### ISSUE TITLE
Manual user email verification

### ISSUE THREAD

**Issue by KianBrose** [pocketbase/pocketbase#443]
Hello!
I am trying to create a user to be able to use the API and am getting this error when trying to authenticate on `/api/admins/auth-via-email`

```json
{
    "code": 400,
    "message": "Failed to authenticate.",
    "data": {}
}
```
Since I am not using a library and using "raw" requests, I forged my own JSON object like this:
```json
{
    "email":"mail@gmail.com",
    "password":"passssssword"
}
```
I tested this with the details I used when creating "my" admin account which did work as expected and threw back a token. 

I assume the issue stems from the fact the account is marked as "unverified" in the users tab.

The problem is that I want to be able to create an account for a co-worker with their own password so I don't have to share mine. 

I personally never work with mail servers since they are a real pain and would like to know if it's possible to manually verify an account from the dashboard / server commands and/or if this is what's causing the issue in the first place

Thank you

**Comment by ganigeorgiev** [comment]
This was asked previosly in https://github.com/pocketbase/pocketbase/discussions/169

In short,  "Admins" and "Users" in PocketBase are 2 different things.

"Admins" are like developer accounts or super-admins for the platform. They can access everything and API rules doesn't apply for them.

"Users" are your application users. They don't have access to the dashboard and are constrained by your collection API rules.

From your description, it seems that you want to create an admin account. To do that, you can go to "Settings > Admins" (or click on your avatar -> "Manage admins").
