### ISSUE TITLE
Feature Proposal: List of active hooks

### ISSUE THREAD

**Issue by birdy90** [pocketbase/pocketbase#4445]
To make sure that hooks are properly bound, it would be great to see a list of hook files that are recognized and are going to be processed during runtime

**Comment by ganigeorgiev** [comment]
I'm not entirely sure that I understand what do you mean by _"List of active hooks"_.

A hook is either registered or not. There is no such thing as "inactive" hook. All available hooks could fire depending on the app operation (including manually when `Trigger()` is called).

If you want to check whether your hook callback will be invoked, you can add a `debug` in your handler log via [Go](https://pocketbase.io/docs/go-logging/) or [JS](https://pocketbase.io/docs/js-logging/) (_they will be stored in the database only if the Min log level is `-4`; the Min log level can be set from the Admin UI > Logs > Logs settings modal_).

In any case, keep in mind that the internals will be refactored in the near future as part of https://github.com/pocketbase/pocketbase/discussions/4355.

**Comment by birdy90** [comment]
got it. thank you for your answer!
