### ISSUE TITLE
Improvement: Complete error checking in generated migration files

### ISSUE THREAD

**Issue by kisamoto** [pocketbase/pocketbase#4448]
I recently started using [`golangci-lint`](https://golangci-lint.run/).

One of the common errors is in the generated db migrations files and relates to `Error return value of `json.Unmarshal` is not checked (errcheck)`. Specifically I have observed this in the `// add` and `// update` sections of the migrations. The `json.Unmarshal([]byte(` is called without the proper error handling. I think it should probably become:

```
edit_my_field := &schema.SchemaField{}
err = json.Unmarshal([]byte(`{
 [...]
}`), edit_my_field))
if err != nil {
    return err
}
```

While I could exclude the generated files from my lint check it would be "correct" if we also added proper error handling in the db migration files.

I'm happy to take a run at it if you can help me get up to speed with an idea in the code where this may be?

**Comment by ganigeorgiev** [comment]
I've added the error checks in `master` and it will be available with the next minor release sometime later this week.

**Comment by kisamoto** [comment]
Incredible, thanks.
