### ISSUE TITLE
Cannot open pocketbase on linux, Raspberry Pi

### ISSUE THREAD

**Issue by george-martinec** [pocketbase/pocketbase#445]
-bash: ./pocketbase: cannot execute binary file: Exec format error

**Comment by ganigeorgiev** [comment]
I'm not sure what could be the reason for the above error.

Are you using the correct bundle with the suffixed architecture for Raspberry Pi? 

If not, then you must download the **armv7** bundle from - https://github.com/pocketbase/pocketbase/releases/tag/v0.7.2.

**Comment by ganigeorgiev** [comment]
If the above doesn't work, you can always compile the minimal PocketBase application on your own:

1. Clone the repo
2. Navigate to `examples/base` directory
3. Run just `go build` on the device  (or provide the correct `GOOS` and `GOARCH` for your platform if you are cross compiling).
