### ISSUE TITLE
Documentation: Example of Raw Query for Transaction Incorrect.

### ISSUE THREAD

**Issue by Oceanbao** [pocketbase/pocketbase#4452]
Dear Benevolent Author,

Just to point out one tinny mistake on the doc, which tripped me over since I'm SQL novice. The mistake is enclosed regarding the raw query to delete records. The correct raw query should be "DELETE FROM articles WHERE status = 'pending'".

Thank you for the project.

<img width="1146" alt="Screenshot 2024-02-29 at 20 41 54" src="https://github.com/pocketbase/pocketbase/assets/8447861/627b32e5-1c21-4d0c-b21b-12924137b982">

**Comment by ganigeorgiev** [comment]
Thank you. It should be fixed now.
