### ISSUE TITLE
Feature Request - Pocketbase OAuth2

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#4456]
I think it would be nice to have ability to auth users with another pocketbase instance... basicaly have 1 instance allow only OAuth2 with another pocketbase instance. I am having in mind auth systems like google and microsoft have, you can use the same account on many services, and they just redirect you to login.example.net

**Comment by ganigeorgiev** [comment]
I think this was discussed already - https://github.com/pocketbase/pocketbase/issues/3567.

**Comment by pietru2004** [comment]
erm sorry I forgot about that one...
