### ISSUE TITLE
 [BUG] JSON formatting issue on page navigation #55 

### ISSUE THREAD

**Issue by matthieuEv** [pocketbase/pocketbase#4462]
# The Bug

When I go back a page and come back to this page using the arrow left and right on the browser or other shortcuts like buttons on the mouse, the JSON formatting breaks, introducing `\n`, and adding a `\` every time the action is repeated

# How to reproduce

Just go back 1 page and come back when you are editing a record with a json field.

# Screenshots

## Before
![image](https://github.com/pocketbase/pocketbase/assets/95125079/fa1a9341-e29f-4157-9e8f-66e3561d4326)

## After first back
![image](https://github.com/pocketbase/pocketbase/assets/95125079/c146d404-1287-4374-8966-c2a35684fafc)

## After third back
![image](https://github.com/pocketbase/pocketbase/assets/95125079/cac322d0-a1c4-4e14-9f59-e3ef35e872f3)

`Pocketbase V0.21.3`

**Comment by ganigeorgiev** [comment]
I've submitted a fix in `master` and it will be available with the next minor v0.22.1 release sometime later this week.
