### ISSUE TITLE
Consistency improvement: "Registered users" rule changes API response to 200 for guest users

### ISSUE THREAD

**Issue by henk23** [pocketbase/pocketbase#4473]
For a list/search request like this:

```
$ curl https://example.com/api/collections/employees/records
```

When no filter rules are set, this is the response, which is what I expect:

```
{"code":403,"message":"Only admins can perform this action.","data":{}}
```

When I change the filter rule to `@request.auth.id != ""` ('Allow only registered users'), this is the response:

```
{"page":1,"perPage":30,"totalItems":0,"totalPages":0,"items":[]}
```

So without sending any Authorization header, I get a 200 response from the API.

Expectation would be to also receive a 403 response, since I'm not a registered user. 

This is not really a security problem, since I get no information about the collection. Just for consistency it would make sense to get a 403 response, right?

**Comment by ganigeorgiev** [comment]
From the [docs](https://pocketbase.io/docs/api-rules-and-filters/):

> PocketBase API Rules act also as records filter!
Or in other words, you could for example allow listing only the "active" records of your collection, by using a simple filter expression such as: status = "active" (where "status" is a field defined in your Collection).
> 
> Because of the above, the API will return 200 empty items response in case a request doesn't satisfy a listRule, 400 for unsatisfied createRule and 404 for unsatisfied viewRule, updateRule and deleteRule.
All rules will return 403 in case they were "locked" (aka. admin only) and the request client is not an admin.
