### ISSUE TITLE
Valid E-Mail is rejected

### ISSUE THREAD

**Issue by maurobalbi** [pocketbase/pocketbase#4483]
When trying to add a user with an unusual, yet valid Email, it's rejected. Maybe relevant discussion #756

![image](https://github.com/pocketbase/pocketbase/assets/30892320/1bd13a00-b669-4528-ab77-b33f51291d85)

**Comment by ganigeorgiev** [comment]
The linked discussion is not related to your issue.

You are entering the email value in the `username` field.

Usernames must satisfy the `^[\w][\w\.\-]*$` regex (there will be an option in the future to change it).

**Comment by maurobalbi** [comment]
Sorry, my bad, I suspected the UI to be at fault, but tried to add it manually in pocketbase and used the username field by accident. Thanks for the quick reply!
