### ISSUE TITLE
Availability to select fields on records

### ISSUE THREAD

**Issue by GD-coding** [pocketbase/pocketbase#4485]
Enable field selection on records like GraphQL or even like what supabase does

**Comment by ganigeorgiev** [comment]
We already have support for the `fields` query parameter.

```js
await pb.collection("example").getOne("RECORD_ID", {
    fields: "id,created"
})
```

You can find more information in the _Admin UI > API preview_ or in the general [Web APIs docs](https://pocketbase.io/docs/api-records/).

**Comment by GD-coding** [comment]
Thank you very much for the quick reply!
