### ISSUE TITLE
Possible nil reference OnAfterApiError

### ISSUE THREAD

**Issue by pnmcosta** [pocketbase/pocketbase#4498]
Was just going through the code to check something and gopls noticed this:

https://github.com/pocketbase/pocketbase/blob/314cd3db46fa98308d2764d18b4d892bc3e09b53/apis/base.go#L109

should be 

```
app.Logger().Debug("OnAfterApiError failure", slog.String("error", err.Error()))
``` 

instead.

**Comment by ganigeorgiev** [comment]
I've pushed a fixed in `master` and it will be available with the next minor v0.22.3 release sometime later this week.
