### ISSUE TITLE
Relation max select field required?

### ISSUE THREAD

**Issue by ayay01** [pocketbase/pocketbase#451]
Right now the relation data type has a required field called "max select". Is this an admin dashboard only thing, or is it limited how many relations a record can have? If it's the latter, could you please elaborate on why this has a limitation? There are many cases where the amount of relations are unknown to you, and you wouldn't want to specify a max amount.

**Comment by ganigeorgiev** [comment]
This was recently filed in https://github.com/pocketbase/pocketbase/issues/425.

It is already fixed in the users management refactoring in #376 and will be available after the refactoring release.

As a workaround for now, you can use the max allowed js integer - 9007199254740991.
