### ISSUE TITLE
Feature Request: Support for Sqlite triggers

### ISSUE THREAD

**Issue by carlosblanco** [pocketbase/pocketbase#4520]
Each column can have a section to create/update triggers for it.

https://www.sqlite.org/lang_createtrigger.html

**Comment by ganigeorgiev** [comment]
There are no plans for this as it will complicate too much the interface for very little benefit.

Prefer using the [app event hooks](https://pocketbase.io/docs/go-event-hooks/) if you want to react on model/record change (_with the [planned refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) the hooks will be further improved and simplified_).

If you really need triggers, you can register them with raw SQL as part of a db migration ([Go](https://pocketbase.io/docs/go-migrations/) or [JS](https://pocketbase.io/docs/js-migrations/)).

**Comment by carlosblanco** [comment]
Makes sense. 
How about generated columns? I was thinking of the simplest way to have something similar to functions

**Comment by ganigeorgiev** [comment]
You can create a helper [View collection](https://pocketbase.io/docs/collections/#view-collection) and apply the SQLite expression you need for the specific field.

Option to add virtual/computed record fields will be possible after the refactoring as there are plans to introduce a new `OnSerialize` hook.
