### ISSUE TITLE
Error when using SQL string concatenation in view collection

### ISSUE THREAD

**Issue by martinklepsch** [pocketbase/pocketbase#4533]
The query below works fine when just using it in SQlite directly but fails when trying to create a collection of `Type: View`. Not sure if this is a bug but maybe there is some too-eager validation? 

```
Invalid query - invalid identifier parts ['https://some-url.com?id=' || t.id AS template_preview_url].
```

```sql
SELECT 
  COUNT(g.id) AS generations_count, 
  t.id AS id,
  'https://some-url.com?id=' || t.id AS template_preview_url
FROM 
  templates t
LEFT JOIN 
  generations g ON t.id = g.template
GROUP BY 
  t.id
ORDER BY 
  generations_count DESC;
```

**Comment by ganigeorgiev** [comment]
It is a limitation of the existing query parsing (_I may consider replacing it in the future but I don't want to complicate further the implementation so for now it is left on hold_).
There are several other related discussions, but the easiest solution is to wrap your expression in a parenthesis, eg. `('https://some-url.com?id=' || t.id) AS template_preview_url`

**Comment by martinklepsch** [comment]
Thank you that helps! 🙏

**Comment by martinklepsch** [comment]
If there's a simple workaround like this I wonder if it maybe could be suggested in the error message? 

I honestly don't mind the workaround so this could just "solve" that problem?
