### ISSUE TITLE
Failed to delete collection due to existing dependency.

### ISSUE THREAD

**Issue by caonima212** [pocketbase/pocketbase#4536]
I duplicate 1 collections, then changed that collections name, then edit some field, then i decide to delete this collections, and this error ```Failed to delete collection due to existing dependency.``` appears. 
I also deleted all fields. How to delete this duplicated collections that i made?

![Screenshot 2024-03-10 040541](https://github.com/pocketbase/pocketbase/assets/162504977/6c783e36-b136-413a-b0e9-45d9625eb1b8)

PB [v0.22.3](https://github.com/pocketbase/pocketbase/releases)

**Comment by ganigeorgiev** [comment]
Make sure that there is on other collection referencing the one you try to delete (eg. check for relation fields in the other 2 collections).

If you need further help, please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details about your collections structure and some steps to reproduce (_you can export your collections configuration as json from the Admin UI > Settings > Export collections_).

**Comment by ganigeorgiev** [comment]
You can also check for a more detailed error message in the _Admin UI > Logs_ and/or start the executable with `--dev`.
