### ISSUE TITLE
Feature Request: Admin panel admins roles and permissions

### ISSUE THREAD

**Issue by Saad5400** [pocketbase/pocketbase#4549]
Having permissions for admins such as `edit:posts` only.

I'm coming from Laravel background with admin panels such as [Backpack](https://github.com/Laravel-Backpack/PermissionManager?tab=readme-ov-file#api-usage) and [Filament](https://github.com/althinect/filament-spatie-roles-permissions?tab=readme-ov-file#usage) which use [Spatie Auth](https://spatie.be/docs/laravel-permission/v6/basic-usage/basic-usage)

Would be great since there's already a very nice admin panel, it just needs a little bit more features to become the best admin panel

**Comment by ganigeorgiev** [comment]
This was discussed several times before - https://github.com/pocketbase/pocketbase/discussions/3827, https://github.com/pocketbase/pocketbase/discussions/3784, https://github.com/pocketbase/pocketbase/discussions/94#discussioncomment-3725219, etc.

This may change after the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) but at least for now there are no plans to introduce admin roles.
