### ISSUE TITLE
Feature Request: Update & Delete multiple records by query filter.

### ISSUE THREAD

**Issue by jstbyte** [pocketbase/pocketbase#455]
Examples,
Update by filter:- 
`client.records.update( 'posts' , null, { ..data } , { filter: 'privacy = "public"' } )`

Delete by filter:-
`client.records.delete('posts', { filter: 'dislike >= 500' } );`

**Comment by ganigeorgiev** [comment]
For now this not planned, because the behavior may not be clear for everyone. Bulk operations in a single collection will be handled in #48.

**Comment by Mashiane** [comment]
I was about to post a question related to this. I guess for now one will have to filter the records they want to delete first and then execute single deletes using the found ids for all the records found via some kind of a loop.

Your delete by filter example makes a lot of sense.

**Comment by makaempffer** [comment]
I wish this existed
