### ISSUE TITLE
Feature Request: Admin panel records ordering

### ISSUE THREAD

**Issue by Saad5400** [pocketbase/pocketbase#4550]
Having an option like 'orderable' for the collection. When true, the collection should have an 'order' attribute that can be changed by dragging the records in the collection UI.

[Something like this](https://backpackforlaravel.com/docs/6.x/crud-operation-reorder)

**Comment by ganigeorgiev** [comment]
Sorry but there are no plans for this at the moment.

As mentioned in your other feature request this may change after the refactoring or at least users will be able to customize the Admin UI on their own.

**Comment by Saad5400** [comment]
Looking forward for it!

Thank you for your quick reply. Please do keep it in mind, it'll be really great and eliminates the need for another admin panel on the frontend.
