### ISSUE TITLE
Open to 3rd parties to verify, no need email tokens

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4551]
![image](https://github.com/pocketbase/pocketbase/assets/5947268/16f82f3c-e567-4a8b-afd9-d0e98da86700)

**Comment by ganigeorgiev** [comment]
Please don't open issues without description. Neither the title, nor the screenshot make any sense as I'm probably missing some context.

If you need help, please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with as much details as possible about your use case and you are executing in general to stumble on the above log error.
