### ISSUE TITLE
Use port env when present.

### ISSUE THREAD

**Issue by ushieru** [pocketbase/pocketbase#4557]
Use port env by default when present. 

https://github.com/pocketbase/pocketbase/blob/20653ef786db55dc77ad13461a659a0e5a960083/cmd/serve.go#L33C1-L37C5.

```go
if len(args) > 0 {
        if httpAddr == "" {
                httpAddr = "0.0.0.0:80"
        }
        if httpsAddr == "" {
                httpsAddr = "0.0.0.0:443"
        }
} else {
        if port := os.Getenv("PORT"); port != "" {
		httpAddr = "0.0.0.0:" + port
	} else httpAddr == "" {
	        httpAddr = "127.0.0.1:8090"
        }
}
```

This can help make it easier to deploy with docker on platforms that give us a random port.

**Comment by ganigeorgiev** [comment]
I don't there is need for magic env variables.
It will require documentation and could results in collisions if we don't prefix them.
