### ISSUE TITLE
No error message when deleting column with dependency in view collection

### ISSUE THREAD

**Issue by ProJaCore** [pocketbase/pocketbase#4587]
Whenever I try to delete a Column let's say "**column_do_delete**" in a Base Collection which has a dependency in a View Collection e.g. "SELECT id, **column_do_delete** ...." the returned error message does not indicate, that a dependency is given:
returning: 
`{
  "code": 400,
  "message": "Failed to update the collection.",
  "data": {}
}`

[PocketBase v0.21.3](https://github.com/pocketbase/pocketbase/releases)

**Comment by ganigeorgiev** [comment]
You can find a more detailed error message in the _Admin UI > Logs_ section.

The collection error messages will be updated in the future as part of [task#35718374](https://github.com/orgs/pocketbase/projects/2/views/1?pane=issue&itemId=35718374)
