### ISSUE TITLE
Question: IN clause

### ISSUE THREAD

**Issue by saturn4er** [pocketbase/pocketbase#4596]
I'm exploring the capabilities of querying records and encountered a situation where I need to filter rows based on multiple values for a specific field. In SQL, this would typically be achieved using the IN clause, like so: `field IN (1, 2, 3)`.

Currently, it seems challenging to perform this type of query, especially when the number of values to filter by is determined at runtime, such as through a dynamic user filter interface. This scenario is common in applications requiring flexible user-driven queries.

**Comment by saturn4er** [comment]
I've discovered an [active issue](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=IN++filter&pane=issue&itemId=53224413) that relates to my query. 

I'll keep my issue open for now to aid others in finding this connection.

**Comment by ganigeorgiev** [comment]
IN/HAS operator exists in the roadmap but remains a low priority.

Note that depending on your use case an alternative could be to concatenate mutiple expressions with `||` (OR):

```js
field = "1" || field = "2" || field = "3"
```

**Comment by alpcanm** [comment]
> IN/HAS operator exists in the roadmap but remains a low priority.
> 
> Note that depending on your use case an alternative could be to concatenate mutiple expressions with `||` (OR):
> 
> ```js
> field = "1" || field = "2" || field = "3"
> ```
> 
> _edit: here is the [task from the roadmap](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=IN++filter&pane=issue&itemId=38816086)_

I also need this query. 
Unfortunately your answer does not give the result I want.  Any alternative ?

**Comment by ganigeorgiev** [comment]
@alpcanm Without details about your collections structure and what is the result you want I don't know what to help you.

In general the `IN` SQL operator is identical to the OR statements but in the case of PocketBase it will depend on the type of the field you are comparing (eg. single vs multiple relation).

In any case if you or someone else have further questions, please consider providing more details about your use case and what you are trying to do ingeneral by opening a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) as its format is more suitable for this.

**Comment by saturn4er** [comment]
The issue with sequential ORs is that you cannot use PocketBase.filter for filter parameters escape, or you need to implement some workarounds around this filter method.
console.log(client.filter("asd = {:asd}", {
    asd: [1,2,3]
}))
this produces:
asd = '[1,2,3]'

**Comment by alpcanm** [comment]
I have a collection called "rooms", I have a field called "members", in this field I keep data related to the "user" collection. And when I search by user id, the query returns empty.

Example 

SELECT * FROM roms WHERE members = 'anyUserId'

I am trying to bring the data whose userId is in the members

**Comment by saturn4er** [comment]
@alpcanm in your case, I think you need to store array of member ids in Members fields, and store members in separate collection, in such way you will be able to write smth like data.members.id="smth"

**Comment by alpcanm** [comment]
> @alpcanm in your case, I think you need to store array of member ids in Members fields, and store members in separate collection, in such way you will be able to write smth like data.members.id="smth"

I just add 2 members for each room. But i get this error 

`sql: no rows in result set`

**Comment by ganigeorgiev** [comment]
This issue is getting very messy. Please understand that questions are better discussed as part of individual [Discussion](https://github.com/pocketbase/pocketbase/discussions).

@saturn4er you can use map calling `client.filter` for each entry, for example:

```js
const arr = [1, 2, 3]

filter: arr.map((v) => client.filter("yourField = {:v}", { v })).join("||")
```

@alpcanm Arrayble fields are stored as serialized json array, or in other words if you want to search for a particular fields in raw DB query you'll have to use the [SQLite json functions](https://www.sqlite.org/json1.html) and more specifically `json_each`. For example:

```sql
SELECT *
FROM roms
LEFT JOIN json_each(roms.members) je
WHERE je.value = 'anyUserId'
```

But once again, if anyone has further questions, please be considerate and open a Q&A discussion.

**Comment by alpcanm** [comment]
> This issue is getting very messy. Please understand that questions are better discussed as part of individual [Discussion](https://github.com/pocketbase/pocketbase/discussions).
> 
> @saturn4er you can use map calling `client.filter` for each entry, for example:
> 
> ```js
> const arr = [1, 2, 3]
> 
> filter: arr.map((v) => client.filter("yourField = {:v}", { v })).join("||")
> ```
> 
> @alpcanm Arrayble fields are stored as serialized json array, or in other words if you want to search for a particular fields in raw DB query you'll have to use the [SQLite json functions](https://www.sqlite.org/json1.html) and more specifically `json_each`. For example:
> 
> ```sql
> SELECT *
> FROM roms
> LEFT JOIN json_each(roms.members) je
> WHERE je.value = 'anyUserId'
> ```
> 
> But once again, if anyone has further questions, please be considerate and open a Q&A discussion.

Thank you so much, it works for me.
