### ISSUE TITLE
Possibility to add tags on files

### ISSUE THREAD

**Issue by julianalsemmani** [pocketbase/pocketbase#4605]
Is it possible to request a feature so you can add "tags" on files?

Let's say you upload a receipt, then you can tag the file as a receipt.

**Comment by ganigeorgiev** [comment]
You can already do that if you add a `select` or `relation` field (_if the tags are stored in another collection_) to your collection.

**Comment by julianalsemmani** [comment]
But, let's say I have a "customer" collection, and each customer can upload multiple files, I won't be able to tag each of the files?

Would the solution be to create a own "files" collection, then have a relation between "files" and "customers" collections?

**Comment by ganigeorgiev** [comment]
> Would the solution be to create a own "files" collection, then have a relation between "files" and "customers" collections?

Yes, at least that is what I would do.
