### ISSUE TITLE
Feature Request: Auto Optimize Indexes

### ISSUE THREAD

**Issue by kabapy** [pocketbase/pocketbase#4609]
I have a running pocketbase installation with collections that contain 500k+ rows.

Performance was good at first, then it started to degrade with more rows added to the db. I started tinkering with the indexes trying to improve performance.

I think it would be great if the engine monitors repeated queries over a period of time. Then it creates or modifies the indexes automatically to improve performance based on real usage statistics.

**Comment by ganigeorgiev** [comment]
What indexes your application needs will depends greatly on the used filters, sorts and other dynamic variables.

I don't think an universal or generic solution for this exists, or at least definitely will not work for all cases (_if there was such SQLite and other databases will have done this already_).

There are plans to add "Indexes suggestions" in the Admin UI, similar to the `sqlite3 .expert` mode but remains a low priority and it will be always up to the user to decide whether they want the index or not.

Also keep in mind that adding extra indexes can sometimes cause more harm than good so they should be added carefully based on the specific use case and desired data flow

I'll close the issue for now as I don't think there is an actionable item here, but feel free to open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new/choose) if you have further questions. I can try to assist you with your problematic requests/queries if you elaborate on your collection structure and provide some details about what filters and/or api rules you use.
