### ISSUE TITLE
Feature Request: Support for SQLite Generated columns

### ISSUE THREAD

**Issue by carlosblanco** [pocketbase/pocketbase#4638]
Sqlite supports generated columns. This can be a great addition to pocketbase so it supports server side generated values depending on data created/updated https://www.sqlite.org/gencol.html

**Comment by ganigeorgiev** [comment]
At least for now there are no plans for this as it comes with too many edge cases.

Also note that computed/generated columns were initially planned as part of https://github.com/pocketbase/pocketbase/issues/311 but was superseded by the View collections as a more generic solution.

Additionally as explained in https://github.com/pocketbase/pocketbase/issues/4520#issuecomment-1984469992, after the refactoring users will have a special hook that will allow users to customize programmatically however they want the record model right before serialization.
