### ISSUE TITLE
And (&&) operator not working in API filter

### ISSUE THREAD

**Issue by migueljr** [pocketbase/pocketbase#4641]
Hi.

![image](https://github.com/pocketbase/pocketbase/assets/12215747/08acb1ae-3260-4fcc-b018-0baffaa24f8a)

I can't use && either. Notice how the postman handles this. he understands that it is an empty field.

**Comment by ganigeorgiev** [comment]
Please check the reply in https://github.com/pocketbase/pocketbase/issues/4546#issuecomment-2020109201.
