### ISSUE TITLE
Pluggable filesystem for the app to be deployed in serverless architectures

### ISSUE THREAD

**Issue by arunura** [pocketbase/pocketbase#4670]
Right now the filesystem is either a S3 bucket (of any provider) or the local filesystem. When I want to implement a different mechanism for storing files, it's almost impossible to plug something in due to the references in `NewFilesystem()` in `core/base.go`.

Making the filesystem a configuration (which implements required interfaces) will allow one to store the DB and collection files in all sorts of places (DB blob field, Redis, over a REST API, in memory store, etc).

This open up the project to community "filesystem" contributions, which in turn open up the app to some interesting deployment patterns (eg: google cloud run, edge compute, in general many serverless solutions).

**Comment by ganigeorgiev** [comment]
Sorry, there are no plans for this.

Note that the `app.NewFilesystem()` is used only for the uploaded files.

The SQLite database file must be on the local filesystem. With the [planned refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) users will be able to register their own `database/sql` compatible interface but as mentioned in the discussion at least for v1 I'm not planning supporting officially other SQL dialects.

**Comment by arunura** [comment]
Sounds good. Thanks for all the hard work and good luck with the refactoring.
