### ISSUE TITLE
Add additional event hooks

### ISSUE THREAD

**Issue by ganigeorgiev** [pocketbase/pocketbase#468]
_This was discussed in https://github.com/pocketbase/pocketbase/discussions/467 and https://github.com/pocketbase/pocketbase/discussions/727._

In addition to the existing [~~User~~ Record event hooks](https://pocketbase.io/docs/event-hooks/#record-hooks) and [Realtime event hooks](https://pocketbase.io/docs/event-hooks/#realtime-hooks), It would be nice to have also event hooks on:

- client SSE disconnect

- before/after broadcasting the SSE message (for each allowed individual client)

- before/after ~~user~~ auth record verification request and confirmation

- before/after ~~user~~ auth record password reset request and confirmation

- before/after ~~user~~ auth record email change request and confirmation

- api error response

**Comment by kethan** [comment]
Need events when file is uploaded, deleted etc, similar like appwrite channels would be great

**Comment by ganigeorgiev** [comment]
@kethan file upload/delete is part of the record create/update/delete, so the existing `OnModel*` and `OnRecord*` hooks handles those cases (the file changes can be detected as any other record field by just comparing the old and new value).

**Comment by kethan** [comment]
@ganigeorgiev So that means I can use that in realtime in frontend?

**Comment by ganigeorgiev** [comment]
@kethan I think there is some misunderstanding. This issue is for the Go [event hooks](https://pocketbase.io/docs/event-hooks/).

If you want to listen for realtime changes client-side (including uploaded/deleted files), you could directly subscribe either to the collection or to a specific record, eg: 


```js
// or client.realtime.subscribe('YOUR_COLLECTION/YOUR_RECORD_ID', function (e) {});
client.realtime.subscribe('YOUR_COLLECTION', function (e) {
    console.log(e.record.yourFileField);
});
```
(you could find more information in https://pocketbase.io/docs/api-realtime/)

**Comment by ganigeorgiev** [comment]
The following hooks were added in `master` and will be available with the next release:

```go
app.OnBeforeBootstrap()
app.OnAfterBootstrap()
app.OnBeforeApiError()
app.OnAfterApiError()
app.OnRealtimeDisconnectRequest()
app.OnRealtimeBeforeMessageSend()
app.OnRealtimeAfterMessageSend()
app.OnRecordBeforeRequestPasswordResetRequest()
app.OnRecordAfterRequestPasswordResetRequest()
app.OnRecordBeforeConfirmPasswordResetRequest()
app.OnRecordAfterConfirmPasswordResetRequest()
app.OnRecordBeforeRequestVerificationRequest()
app.OnRecordAfterRequestVerificationRequest()
app.OnRecordBeforeConfirmVerificationRequest()
app.OnRecordAfterConfirmVerificationRequest()
app.OnRecordBeforeRequestEmailChangeRequest()
app.OnRecordAfterRequestEmailChangeRequest()
app.OnRecordBeforeConfirmEmailChangeRequest()
app.OnRecordAfterConfirmEmailChangeRequest()
```
