### ISSUE TITLE
Buttons in emails with dark mode are not visible

### ISSUE THREAD

**Issue by rollermy** [pocketbase/pocketbase#4707]
Hey,

Both the button and the background are totally black on my phone.
![image](https://github.com/pocketbase/pocketbase/assets/7276924/9fc80cfd-6263-46aa-82b0-3721ee0657c7)

Not a huge deal, but this makes the experience less appealing for users with dark mode.

**Comment by ganigeorgiev** [comment]
There is no official support for dark mode at the moment (including for the mail templates).

The default templates and its styles can be changed from the _Admin UI > Settings > Mail settings_.

**Comment by ganigeorgiev** [comment]
Yes, that's one way to do it. Another possible workaround I guess could be to add a white (contrasting) border-color/outline to the button (_I'll consider it with the next minor release_).
