### ISSUE TITLE
Proposal: Add the ProviderUsername field to ExternalAuth

### ISSUE THREAD

**Issue by Kam1k4dze** [pocketbase/pocketbase#4716]
Currently only the `ProviderId` is stored in `ExternalAuth`. There is almost always a need to display a name from a linked external service to a user. As far as I understand, it is now necessary to manually process `username` or `name` via a hook, although maybe I'm just looking badly. 
So my suggestion is to add a `ProviderUsername` field to `ExternalAuth` that takes data from `AuthUser.Name` or `AuthUser.Username`. I think this would greatly simplify the interaction and improve the UX.
I apologize if it turns out I just haven't found where the username is stored.

**Comment by ganigeorgiev** [comment]
There are no plans for now to store any other OAuth2 information other than the id as it could change and will get out of sync (additionally not all OAuth2 providers returns a username).

To access the raw OAuth2 userinfo response you can inspect the result of the `authWithOAuth2()` call and more specifically the object under the `meta.rawUser` field.
