### ISSUE TITLE
Subsribing with a filter won't delete gone items.

### ISSUE THREAD

**Issue by DavBfr** [pocketbase/pocketbase#4717]
Creating a subscription with a filter with a boolean field, say "visible".

If I change the visible value from true to false I will not get any update or delete event. There is no way to know this record is gone.

I expect to get a delete event if the record is to disappear from the subscription. We receive an update event in case of an insertion which is not ideal but manageable.

maybe new events like insert / gone could be useful.

**Comment by ganigeorgiev** [comment]
This exists in the [roadmap](https://github.com/orgs/pocketbase/projects/2?pane=issue&itemId=56931794). You can also check https://github.com/pocketbase/pocketbase/issues/2522, https://github.com/pocketbase/pocketbase/discussions/4592 and probably others.
