### ISSUE TITLE
Thumb sizes not working?

### ISSUE THREAD

**Issue by uchoasvinicius** [pocketbase/pocketbase#4725]
I don't know if I understand very well how thumb size values work. I'm storing the images in an S3 bucket, but when I set 3 sizes for cropping (eg: 300x300, 480x700, 150x150) on the "Thumb sizes" field config of a file input, pocketbase only uploads 100x100, creating a thumbs folder with this single format inside. I thought pocketbase would generate the 3 formats plus the 100x100.

What am I doing wrong?

ENV： ubuntu22.04(x86) v0.22.8

**Comment by ganigeorgiev** [comment]
Thumbs are generated lazily on first access and only for files with the following mimetypes:

```
image/png
image/jpg
image/jpeg
image/gif  // only the first frame
```

To access a thumb you need to append the `?thumbs=WxH` query parameter, ex:

```
http://127.0.0.1:8090/api/files/COLLECTION_ID_OR_NAME/RECORD_ID/FILENAME?thumb=480x700
```

If you have other questsions, please use the Q&A discussions instead as the format is more suitable for this type of posts.

**Comment by 2234839** [comment]
Thumbs are generated lazily on first access and only for files with the following mimetypes:

Then, when accessing again (using a different thumb parameter), will it not be generated?
