### ISSUE TITLE
Users/auth-methods is returning empty array even after setting up the google client and secret in admin ui

### ISSUE THREAD

**Issue by jainmohit** [pocketbase/pocketbase#4729]

**Comment by ganigeorgiev** [comment]
Make sure that you have OAuth2 in the specific auth collection options:

![auth_collection_options](https://i.imgur.com/7rozzXJ.png)

I've tested it locally and it is working fine for me. There are also [integration tests](https://github.com/pocketbase/pocketbase/blob/master/apis/record_auth_test.go#L37) that verify the correct behavior.

If you are still not able to resolve, please provide clear reproducible steps.
