### ISSUE TITLE
Feature request: custom logger

### ISSUE THREAD

**Issue by Gys** [pocketbase/pocketbase#4740]
Hi!

Currently in Bootstrap() the BaseApp.logger is a private var. Why not make it public?

I want to use my own logger (sending logs to an external service) but because its a private var set with initLogger() in Bootstrap() there is no easy way to customize it. Or did I miss something?

**Comment by ganigeorgiev** [comment]
There are no plans to make the default app logger customizable but with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) there will be dedicated hooks that will allow listening to the individual log writes.

To some extend you can do that already with something like:

```go
app.OnAfterBootstrap().Add(func(e *core.BootstrapEvent) error {
	app.LogsDao().BeforeCreateFunc = func(eventDao *daos.Dao, m models.Model, action func() error) error {
		if log, ok := m.(*models.Log); ok {
			// do something with the log model...
			fmt.Println(log)
		}
		return action() // proceed with the normal operation
	}

	return nil
})
```

**Comment by Gys** [comment]
Thank you for the very fast reply!

From a first quick test this seems to only works for requests? Not for debug? Maybe also not for error or warning messages? Maybe I can set a level somewhere else?

**Comment by ganigeorgiev** [comment]
You can control the min log level from the _Admin UI > Logs > Logs settings_ popup.

**Comment by Gys** [comment]
Aha, did not know that one. Thanks!
