### ISSUE TITLE
Also, from one device, if you try to log in from different emails (Google)

### ISSUE THREAD

**Issue by MrNapcae** [pocketbase/pocketbase#4743]
Also, from one device, if you try to log in from different emails (I am authorized under 2 emails), then successful authorization will result in constraint failed: UNIQUE constraint failed: _externalAuths.collectionId, _externalAuths.recordId, _externalAuths.provider (2067)

_Originally posted by @MrNapcae in https://github.com/pocketbase/pocketbase/discussions/4742#discussioncomment-9108949_

**Comment by ganigeorgiev** [comment]
Please don't open issues like this.
