### ISSUE TITLE
Create duplicate record

### ISSUE THREAD

**Issue by samir64** [pocketbase/pocketbase#4754]
In Admin UI when I want to create new record, creates duplicates in database.
I'm using Pocketbase version 0.22.9

**Comment by ganigeorgiev** [comment]
I'm sorry but it is not clear what is the issue nor what you are trying to do.

If you are still not able to resolve your problem, please elaborate more clearly what is the issue and ideally provide some reproducible steps.

**Comment by ganigeorgiev** [comment]
For duplicating records from the Admin UI you can click on the "Duplicate" record panel option (_files can't be duplicated_).

![duplicate_screenshot](https://i.imgur.com/jUJK99v.png)

**Comment by samir64** [comment]
Sorry.
It was my fault.
In my event hooks, I repeated calling `next(c)`
And this made duplicated records
