### ISSUE TITLE
Bug? - View collection SQL error "Must be in valid format"

### ISSUE THREAD

**Issue by wRadion** [pocketbase/pocketbase#4759]
So I try to create a view from the UI and I got this error with this query:
```sql
SELECT DISTINCT (r.player),
  r.id, p.name, r.time, c.name
FROM runs AS r
JOIN players AS p ON r.player = p.id
JOIN categories AS c ON r.category = categories.id 
ORDER BY r.time
```

Error:
`3: Must be in a valid format.`

But no errors with this one (I've changed `c.name` with `c.slug` that's it):
```sql
SELECT DISTINCT (r.player),
  r.id, p.name, r.time, c.slug
FROM runs AS r
JOIN players AS p ON r.player = p.id
JOIN categories AS c ON r.category = categories.id 
ORDER BY r.time
```

Is it because "name" is a keyword or something? But then why `p.name` works? And yes, both "name" and "slug" are valid columns for this table (both are simple strings). I'm confused.

**Comment by ganigeorgiev** [comment]
The error messages will be improved in the future but as far as I understand the above is working correctly.

Both `p.name` and `c.name` will result in 2 fields with the same name ("name") which is not allowed. You can use an alias (eg. `c.name as otherName`) to workaround it.

**Comment by wRadion** [comment]
Aaaaah right, my bad, sorry for creating an issue for that.
