### ISSUE TITLE
Feature Request: Add "All/None" operator variants

### ISSUE THREAD

**Issue by brocococonut** [pocketbase/pocketbase#4762]
The current filtering methods are fantastic so far, and the ability to use back references has been amazing, but I find myself getting tripped up not being able to do the inverse of some of the operations - namely the following ones:
- ?= Any/At least one of Equal
- ?!= Any/At least one of NOT equal
- ?> Any/At least one of Greater than
- ?>= Any/At least one of Greater than or equal
- ?< Any/At least one of Less than
- ?<= Any/At least one of Less than or equal
- ?~ Any/At least one of Like/Contains (if not specified auto wraps the right string OPERAND in a "%" for wildcard match)
- ?!~ Any/At least one of NOT Like/Contains (if not specified auto wraps the right string OPERAND in a "%" for wildcard match)

The inclusion of them is great for filtering/searching, and chaining them together with `||`'s to create tag based filtering has been great as well. But without having a way to do something similar to all/none variants is extremely limiting. I propose adding the following operands (well, I've described them, I don't know what you'd choose to represent them with):
- None Equal
- All equal
- None Greater than
- All Greater than
- None Greater than or equal
- All Greater than or equal
- None Less than
- All Less than
- None Less than or equal
- All Less than or equal
- None Like/Contains
- All Like/Contains

These would really flesh out and bolster the search/filtering capabilities of Pocketbase.

Amazing work so far btw!

**Comment by ganigeorgiev** [comment]
I'm sorry but it is not clear what actually is the requested feature, nor the desired behavior.

We apply by default a "match-all" type of constraint for multiple valued fields if the operator is not prefixed with `?`, for example `users.status != "inactive"` requires **all** `users` `relation` entries to have status different from "inactive",

If that's not what you are looking for then please elaborate more clearly on the desired behavior.
