### ISSUE TITLE
Invalid or expired verification token

### ISSUE THREAD

**Issue by aruator** [pocketbase/pocketbase#4763]
hi,

if im creating a user, like following:

```
const user = { username: `${values.username}`, email: values.email, password: values.password, passwordConfirm: values.passwordConfirm, verified: false } as UserRecord

const userRecord = await this.pb.collection('users').create(user) as UserRecord
await this.pb.collection('users').requestVerification(userRecord.email)
```

the email is being send, but when i click the verification link, i'm always getting the
"Invalid or expired verification token." error.

the link is: https://pb.example.org/_/#/auth/confirm-verification/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJfcGJfdX..........

it was working as i implemented this some months ago, but now it wont. I haven't changed any settings.

**Comment by ganigeorgiev** [comment]
It is working correctly for me with the recent v0.22.9 release and we have [integration tests](https://github.com/pocketbase/pocketbase/blob/master/apis/record_auth_test.go#L914) that verify the correct behavior.

You can try to check the logs in the _Admin UI > Logs_ and/or start the executable with `--dev` to see if there is a more detailed error message.

Alternatively, you can also try to inspect the token payload by pasting it in https://jwt.io/ and see if the payload fields match your user ones.

If you are still not able to resolve it, please try to create a _minimal_ reproducible repo and I'll try to have a look it.

**Comment by ganigeorgiev** [comment]
Also note that `userRecord.email` could be empty if `emailVisibility` wasn't explicitly set to `true`.

**Comment by aruator** [comment]
Oh, sorry it looks like i have a problem withith the "onModelBeforeUpdate" hook for users, where im checking some custom props. I guess the method gets called on opening the verification link where the "verified" flag is being set.

Thank you for the quick response and your advises!
