### ISSUE TITLE
`$os.readFile` and `$os.getwd` use `/` as working directory in production enviroment

### ISSUE THREAD

**Issue by peter-pakanun** [pocketbase/pocketbase#4773]
I was trying to go production and have been following the instruction in the [doc](https://pocketbase.io/docs/going-to-production/)

But I noticed that my custom `.env` reader was throwing an error.

This code ran during `onBeforeBootstrap` hook:
```js
try {
  envFile = $os.readFile(".env");
} catch (e) {
  console.error(e);
}
```
And was throwing error:
```
Apr 17 22:01:43 poe-vpn.localdomain pocketbase[1464]: 2024/04/17 22:01:43 Loading environment variables
Apr 17 22:01:43 poe-vpn.localdomain pocketbase[1464]: 2024/04/17 22:01:43 GoError: open .env: no such file or directory
```

So I try logging out the working dir with `$os.getwd` and it logged root:
```
Apr 17 22:02:42 poe-vpn.localdomain pocketbase[1507]: 2024/04/17 22:02:42 /
```

`pb_migrations` got read just fine and new data also get written to `pb_data` so I think the working directory is set correctly.

My current workaround is to use `__hooks` variable and traverse up one directory to the root of project.

Note: it works when running `./pocketbase serve` but not as a systemd service, here's my systemd service file: `pocketbase.service`
```systemd
[Unit]
Description = poemaid-pocketbase

[Service]
Type           = simple
User           = root
Group          = root
LimitNOFILE    = 4096
Restart        = always
RestartSec     = 5s
StandardOutput = append:/root/poe-maid-sveltekit/errors.log
StandardError  = append:/root/poe-maid-sveltekit/errors.log
ExecStart      = /root/poe-maid-sveltekit/pocketbase serve --http="127.0.0.1:8099"

[Install]
WantedBy = multi-user.target
```

**Comment by ganigeorgiev** [comment]
It is working correctly.

Both `$os.getwd` and `$os.readFile` are directly mapped to the Go [`os.Getwd`](https://pkg.go.dev/os#Getwd) and [`os.ReadFile`](https://pkg.go.dev/os#ReadFile) methods (see [binds.go](https://github.com/pocketbase/pocketbase/blob/4cfabc61e682549a82f073b7be1d57959673e0da/plugins/jsvm/binds.go#L571)) and they follow the same rules for resolving their path based arguments.

**Comment by ganigeorgiev** [comment]
I forgot to mention that an alternative to the absolute path could be to define the [`WorkingDirectory` directive](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#WorkingDirectory=) in your service file.

**Comment by peter-pakanun** [comment]
So pocketbase didn't use working directory when resolving for `pb_*` but rather it's own binary path?

As it is not exptected that running pocketbase in a production enviroment puts its working directory on `/`, this should be mentioned in the [document](https://pocketbase.io/docs/going-to-production/) and the [WorkingDirectory directive](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#WorkingDirectory=) you mentioned should also be included in the example service file.

**Comment by ganigeorgiev** [comment]
`pb_data` by default is relative to the executable (you can inspect the defaults with `--help`).

For any std Go function (or its JS translation) the relative paths are resolved based on the current directory. It is not guarantee that it will be always `/` as this will depend on the platform and the user that is running the systemd service. I'll consider adding the `WorkingDirectory` directive in the example service file with the next release.
