### ISSUE TITLE
Feature Request:  is there is any way to make our own Custome storage system. 

### ISSUE THREAD

**Issue by hugo-abdou** [pocketbase/pocketbase#4779]
I have an application that uses Bunnystreem storage and I want to migrate from laravel to Pocetbase but I have this problem with storage because Bunneystreem is not supported how we can make our storage driver

**Comment by ganigeorgiev** [comment]
At least for v1 there are no plans for other storage implementations as it will be difficult to maintain.

Support for general file hooks will be added with the [ongoing refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) which eventually to some extend could allow integration with custom storage apis.
