### ISSUE TITLE
Issue with Hour Field Not Triggering in CronJob Registration

### ISSUE THREAD

**Issue by InSeok9068** [pocketbase/pocketbase#4782]
Hello, I am a developer using PocketBase in Korea. I am currently developing an extension in JavaScript to register CronJobs with fields for minute, hour, day, month, and week. I have confirmed that the minute and week fields are working correctly through tests, but the hour field does not seem to operate correctly even though I have input the correct numbers for the specific hours.

Pocketbase v0.22.4

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it locally with the latest v0.22.9 and it is working correctly for me.

If you are still not able to resolve it, then please elaborate a little more by providing minimal code sample/reproducible steps and I'll try to investigate it further.

If you have other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/4355).
