### ISSUE TITLE
Querying Auth Record from a PB Hook does not return the email field, if the user has emailVisibility set to false

### ISSUE THREAD

**Issue by LuminareHQ** [pocketbase/pocketbase#4783]
In PB hook files, an auth query should return the users email in the record, whether or not the user has set emailVisibility to true or false.

Currently, in v0.22.9, this is not the case and follows the emailVisibility value.

For context, both of these methods do not work and follow the emailVisibility value.
```
$app.dao().findRecordById("users", user_id)
$app.dao().recordQuery("users").where($dbx.exp("id = {:id}", {id: user_id})).limit(1).one(userRecordQuery)
```

**Comment by ganigeorgiev** [comment]
When serializing as json the retrieved record the `emailVisibility` flag is taken in consideration.

If you want to ignore it, you can call `record.ignoreEmailVisibility(true)`.
