### ISSUE TITLE
JSON fields not showing in admin item drill-down

### ISSUE THREAD

**Issue by j0sh** [pocketbase/pocketbase#4790]
On the latest Pocketbase release - 0.22.9, JSON fields do not seem to be populated when drilling down into items from the admin panel. The field stays in the 'Loading..' state. On the table view, the preview does show correctly.

Some screenshots:

**Working screenshot from table view**
![image](https://github.com/pocketbase/pocketbase/assets/292510/9009e46b-bb75-49c5-9ce1-d626c9b0408e)

**Drill-down that only shows the 'loading' indicator for the Data field**
![image](https://github.com/pocketbase/pocketbase/assets/292510/9efc1891-dc83-4b5b-bbeb-98fee357756d)

**Comment by ganigeorgiev** [comment]
It is correctly for me when testing in the live demo (pocketbase.io).

Could you paste the failing json?

What browser do you use? Could you check if there is a JS error in the browser console?

**Comment by j0sh** [comment]
Thanks for the hints.

The (Safari) browser console showed a bunch of 404 errors for the CodeEditor script. I hard-refreshed the page to check some other things and ... all my JSON fields started working again (after being broken for a couple days).

My guess is that when my Pocketbase was updated, the `CodeEditor-<hash>.js` was also updated. The admin page was probably trying to load an old version of the CodeEditor script which no longer existed.

Reminder to myself to hard-refresh admin tabs after a Pocketbase update :)
