### ISSUE TITLE
Problem with operator: `?=`

### ISSUE THREAD

**Issue by BijSven** [pocketbase/pocketbase#4793]
👋 Hey there, I was using Pocketbase to create collaborative functions, but know I have a problem because when using the `?=` operator an user with invalid credentials can access all items even if he / she didn't met the rule-requirements.

**Comment by BijSven** [comment]
Example: (members.id ?= @request.auth.id)

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean but I don't think there is an issue with the rules evaluation.

The above rule should require at least one of the `members` records to match with he current authenticated user.

If you have further questions please open a Q&A discussion with more details about your use case, the desired behavior and your collections structure (_you can export it from the Admin UI > Settings > Export collections_).
