### ISSUE TITLE
How can I filter a date using the equal = operator ?

### ISSUE THREAD

**Issue by rodridev97** [pocketbase/pocketbase#4797]
### I need to know how to filter a date so that it returns values ​​equal to that date without using time, only date. I tried the pocketbase filter and it doesn't work. For example

![Screenshot 2024-04-21 at 16 21 00](https://github.com/pocketbase/pocketbase/assets/98955724/9653ea29-5070-4da5-9ada-7fae094dd7aa)

![Screenshot 2024-04-21 at 16 22 40](https://github.com/pocketbase/pocketbase/assets/98955724/c5f94b47-d65d-4c68-b87b-6c0413edd592)

@ndarilek @yinshanyang @pnmcosta @mjadobson @ganigeorgiev 

### created = "2024-05-11"

**Comment by ganigeorgiev** [comment]
Please don't ping random users unnecessary.

The full date format is `Y-m-d H:i:s.uZ` (eg. `2024-05-11 19:55:27.123Z`).

To apply a partial date match you can use the `~` operator, eg. `created ~ '2024-05-11'`.
Alternatively, you can search using a range by speciyfing the min and max of a date, eg.

```js
created >= '2024-05-11 00:00:00.000Z' && created <= '2024-05-11 23:59:59.999Z'
```

If you have other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a).

**Comment by rodridev97** [comment]
thanks and sorry for the pings
