### ISSUE TITLE
Proposal: automatically load custom certificates from /pb_certificates

### ISSUE THREAD

**Issue by lucafabbian** [pocketbase/pocketbase#4807]
This issue was brought to attention a couple of years ago, and got reject due to pocketbase being in an early stage

As far as I understand, it would be as simple as changing `&tls.config` inside `apis/serve.go`.

A possible workflow could be to check for the existence of a `/pb_certificates` directory alongside `/pb_data`, and disable Let's Encrypt when custom certificates are found.

If you like the idea, I may work on it and provide a pull request. In my opinion, it will require little effort and save us from configuring a reverse proxy.

Let me know if you are interested.

**Comment by ganigeorgiev** [comment]
Sorry but there are no plans for this as it is not clear how this certificate would be configured/renew and I don't want to add another special directory to manage.

Users have access to the `http.Server.TLSConfig` via the `OnBeforeServe` hook and can customize it if there is really need for this.

Unless I'm misunderstanding something, this remains out of the scope for v1.
