### ISSUE TITLE
Feature Request: RSA Token/ minting record in token for M2M auth

### ISSUE THREAD

**Issue by redthorx** [pocketbase/pocketbase#4811]
I am currently looking at using pocketbase for my backend for frontend, and while i can create additional clients as users and use the `auth-with-password` to obtain tokens to perform M2M transactions, I would have to query pocketbase to obtain client information for each API call.

Using RSA tokens and having a [JWKS endpoint](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets), and also minting the record in the token would allow me to obtain client information securely without querying pocketbase for each API call

**Comment by ganigeorgiev** [comment]
I don't understand what is your use case but there are no plans for adding different type of auth tokens out of the box.

Support for Admin API keys eventually may get added in the future as this is commonly requested but for now remains out of the scope as I have some security concerns regarding its implementation.

See also https://github.com/pocketbase/pocketbase/discussions/4355.
