### ISSUE TITLE
Cross joins not working in view collections

### ISSUE THREAD

**Issue by TheEaterr** [pocketbase/pocketbase#4825]
I can' t manage to make cross joins work inside a view collection. I tried all syntax forms in https://www.sqlitetutorial.net/sqlite-cross-join/ and I either get an error or just one of the two collections I'm trying to join.

![image](https://github.com/pocketbase/pocketbase/assets/79149403/38f443f2-6b5d-4118-9b2c-78b4c499bea2)

Running on go 1.22.0

**Comment by ganigeorgiev** [comment]
It is not the `JOIN` that is failing but the duplicated `id` field (`rank.id` and `daily.id` will result 2 fields with the same name - `id`).

The view validation errors will be improved in the future, but for now you can try specifying an alias (eg. `daily.id as dailyId`).

If that doesn't help, feel free to let me know I'll to investigate it tomorrow.

**Comment by TheEaterr** [comment]
Wow what a fast answer ! Yes that does solve the format problem but the other one remains, the cross join isn't being made I only get each row of the first collection (with additional columns for the first row of the second one).

In any case, I was able to find a solution to my use case using nested selects. Thank you very much!

**Comment by ganigeorgiev** [comment]
> but the other one remains, the cross join isn't being made I only get each row of the first collection

This will depend on your query and data structure. The easiest way to rule out PocketBase issue is to run your query against the `pb_data/data.db` file using the `sqlite3` cli:

```sh
sqlite3 ./pb_data/data.db 'your query'
```

If you have other questions please open a new [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) as the threaded format is more suitable for this.

**Comment by TheEaterr** [comment]
It works fine using the sqlite cli, you can try anything using a cross join and the bug will appear.
`SELECT table1.id, table2.id as other_id FROM table1 CROSS JOIN table 2`

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. I've just tested it locally and both produce the same result. 

Once the query is saved it is executed as plain View by the specific SQLite driver (if CGO is enabled [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3), otherwise [modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite)).

Additionally I don't understand what is the purpose of the cross join in your case especially when there is no `ON` constraint.

I don't think I can help you further but if you have further questions please open a Q&A discussion with more details about your use case, what you are trying to do and an export of your collections configuration (_Admin UI > Settings > Export collections_).

**Comment by TheEaterr** [comment]
Hey I'm sorry for insisting but I really do think there is an issue. When using the live pocket demo, and this collection schema
[pb_schema_cross_join.json](https://github.com/pocketbase/pocketbase/files/15137357/pb_schema_cross_join.json)
you can see that the cross join has only 3 rows while it should have 6.

Cross joins do not have ON constraints, they make a cartesian product of the two tables ie a row for each pair of row in the two tables.

**Comment by ganigeorgiev** [comment]
If the `id` field is not unique then it is expected the result to have fewer rows.

Here is an updated query:

```sql
SELECT
  (ROW_NUMBER() OVER()) as id,
  posts.id as postId,
  messages.id as messageId
FROM posts CROSS JOIN messages
```

But again, you refuse to elaborate on your use case to understand the purpose of the cross join and the desired behavior so I'll stop engage to avoid further confusion.
