### ISSUE TITLE
Sending multiple emails in one cron hook was not completed without error message

### ISSUE THREAD

**Issue by xu4wang** [pocketbase/pocketbase#4827]
I'm using the cron hook to send emails for all the subscribers, currently 13 of them, every morning. However, recently I found it only sent out 10 emails. I cannot find any clue in the logs. Please find below the hook implementation as well as the logs it produced.

As it's showed in the log.  ` $app.newMailClient().send(message);` has been executed successfully for most of the emails, however when it sends to  ` somboday@somecompany.com`, something happened and it was not sent.

Note  `somboday@somcompany.com` is the 10th of the receiver,  there are still other 3 receivers left, the missing parts are the log for `sent email to  somboday@somecompany.com` and the other 3 email sending/sent logs.

I guess for some reason ` $app.newMailClient().send(message);` was interrupted when sending to `sombody@somecompany.com`, but I don't know how to investigate further, cannot find any thing wrong in the email address.

The hooks
------
```js
cronAdd("daily_rates", "30 1 * * *", () => {
  const records = $app.dao().findRecordsByFilter(
    "users", // collection
    "subscribed = true", // filter
    "-created", // sort
    0, // limit
    0 // offset
  );

  const data = {};
  //construct the data ...
  ...


  console.log("going to send email, there receiver number are: ", records.length);

  //process each task based on it's type, and update the task status to submitted
  records.forEach((progressRecord) => {
    const email = progressRecord.get("email");
    if (email) {

      const name = progressRecord.get("name");
      data.name = name;

      const html = $template
        .loadFiles(
          `${__hooks}/templates/layout.html`,
          `${__hooks}/templates/daily_rate.html`
        )
        .render(data);


      const message = new MailerMessage({
        from: {
          address: $app.settings().meta.senderAddress,
          name: $app.settings().meta.senderName,
        },
        to: [{ address: email }],
        subject: "Today's Special offer...",
        html: html,
      });
      console.log("sending email to", email);
      $app.newMailClient().send(message);
      console.log("sent email to", email);
    }
  });
});
```

The Logs produced
------ 
```

2024/04/26 09:30:00 going to send email, there receiver number are:  13
2024/04/26 09:30:00 sending email to ....com
2024/04/26 09:30:01 sent email to ....com
2024/04/26 09:30:01 sending email to ....com
2024/04/26 09:30:02 sent email to ....com
...
...
2024/04/26 09:30:13 sending email to somboday@somecompany.com
```

**Comment by ganigeorgiev** [comment]
I don't think this is a PocketBase issue (or at least I'm not sure how to reproduce it).

You can try to wrap the email send in a `try/catch` and log the error with [`$app.logger().error()`](https://pocketbase.io/docs/js-logging/#errormessage-attrs-).

Another reason why the number of records could differ from the number of sent emails could be because of the `if (email)` condition in case the `email` field is optional, so double check that all of the users have an email address.

If you still think that it is a PocketBase issue, please create a _minimal_ reproducible repo showing the email template you are sending and the complete data you are constructing.

**Comment by ganigeorgiev** [comment]
I forgot to mention that alternatively to manually wrapping the code with try/catch is to enable the "debug" min log level by going in the _Admin UI > Logs > Logs settings_ and set "Min log level" field to `-4` (_I'll consider updating in the future cron exec errors to be logged with error status instead_).

**Comment by xu4wang** [comment]
> I forgot to mention that alternatively to manually wrapping the code with try/catch is to enable the "debug" min log level by going in the _Admin UI > Logs > Logs settings_ and set "Min log level" field to `-4` (_I'll consider updating in the future cron exec errors to be logged with error level instead_).

Thanks. Yes. checked the debug log, confirmed it's SMTP server issue.
