### ISSUE TITLE
Feature Request: Templ

### ISSUE THREAD

**Issue by VictorioBerra** [pocketbase/pocketbase#4840]
https://github.com/a-h/templ

I'm not the biggest fan of Go's template stuff. This package looks way easier to work with.

This would be cool to have it built-in somehow with first-class support in PB.

**Comment by ganigeorgiev** [comment]
Sorry but for now there are no plans for this.

I don't understand what do you mean by "first-class support in PB" but there is nothing in PocketBase that prevents to use `templ`.
