### ISSUE TITLE
API rules operators

### ISSUE THREAD

**Issue by FifthWit** [pocketbase/pocketbase#4842]
So I have a system where the user can "like" a post but one user found that you can modify the patch request to change everything, like the name, so I wanted to make it so the when theres a patch request the likes can be over +-1 so you can only like one at a time but I dont think thats a feature

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand the purpose of the issue.

If you are asking to limit the increment value of a `number` field by just 1, then there is no such option and there are no plans to introduce it.

The better approach in your case would be to have a junktion collection, eg. "likes" that will contain 2 `relation` fields pointing to your user and other related record (eg. post). Then you can register a `UNIQUE` unique constraint (_under the "Unique constraints and indexes" collection fields options_) for the `user-post` pair to ensure that a single "user" can like a "post" only once.

See also https://github.com/pocketbase/pocketbase/discussions/4369 and the other linked discussions.

If you have other questions please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) instead with more details about your use case and what you are trying to do.
