### ISSUE TITLE
Feature Request: Postgres SQL Support

### ISSUE THREAD

**Issue by skrenes** [pocketbase/pocketbase#485]
Phenomenal work and in such a short time! I was wondering if you're open to supporting an optional connection to Postgres instead of SQL lite. I almost always take advantage of more advanced features and the ability to scale up would be great for greenfield projects.

I could even imagine a hybrid solution where user management is handled the same way, but the application model could live in Postgres.

I think it's amazing that pocketbase is so extensible as a Go framework/toolkit, so I'm sure it would be easy for me to just import [`pgx`](https://github.com/JackC/pgx), but as first class support, I think being able to use SQLite or Postgres could take this to the next level.

Thanks again for this amazing project!

**Comment by ganigeorgiev** [comment]
Support for other databases is in the [roadmap](https://github.com/orgs/pocketbase/projects/2), but it's a low priority for now.

You can also check this discussion - https://github.com/pocketbase/pocketbase/discussions/14#discussioncomment-3109447.
