### ISSUE TITLE
[Bug] rich text editor discards html when edited from a separate relationship table

### ISSUE THREAD

**Issue by Saad5400** [pocketbase/pocketbase#4857]
PocketBase v0.21.3

If I have a table record with a rich text editor attribute, I can create and edit it completely normally from the same table page, let's call this table A. However, if I have another table (B), which has a relation with A and I go to B's table page and edit one of the B table's records, and from within that record I edit the A table's relation record which has a rich text editor, it opens up as if it's just text without all the html markup I've written earlier. 

Perhaps some images would be better:

Editing the record from the same table page:
![image](https://github.com/pocketbase/pocketbase/assets/86385454/2778263b-572b-40fa-a5b4-3a1b27d32aa6)

Editing the very same record but from a relation table page:
![image](https://github.com/pocketbase/pocketbase/assets/86385454/c3e229d5-c3ba-4199-950b-a2654fd5522c)

As you can see that the markup is no longer used in the rich text editor.

I know that you're planning to change the text editor, if you haven't already. But please keep this bug in mind for testing. Thanks a lot in advance.

**Comment by ganigeorgiev** [comment]
Hm, I don't think this is related to the TinyMCE editor and it is most likely because in the relation popup the records are fetched with the `:excerpt` modifier for the `editor` type fields and passed as it is in the edit form instead of fetching the full record.

I'll push a fix sometime later this weekend.
