### ISSUE TITLE
Database transaction lock causing program to become unresponsive.

### ISSUE THREAD

**Issue by yxwzyyk** [pocketbase/pocketbase#4859]
When I create a custom route named 'createOrders', where I initiate a transaction and register hooks using OnModelBeforeCreate('orders'), and within it create 'orders_log', the program locks up when executing global.App.Dao().SaveRecord(logRecord).

**Comment by ganigeorgiev** [comment]
This is not a PocketBase issue. If you are inside of transaction you need to use the transaction `Dao` instance.

This will be simplified in the near future as part of the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and the App-Dao merge.

**Comment by yxwzyyk** [comment]
I understand, thank you for your reply.
