### ISSUE TITLE
Admin UI calendar picker calendar grid layout issues

### ISSUE THREAD

**Issue by Em1tt** [pocketbase/pocketbase#4865]
Hello, I've found a tiny bug with the rendering of the calendar in the Admin UI.

OS: macOS 14.3
Browser: FireFox 125.0.3

The issue: When creating a record manually through the Admin UI, when setting any DateTime property, the last column (Sundays) don't fit into the calendar selector, thus getting pushed into the next row.
<img width="659" alt="image" src="https://github.com/pocketbase/pocketbase/assets/55552821/1978c0d8-6dd0-412c-863a-41e8b62917b7">

Additional (maybe related information):
Resolution: 1470x956 (happens on multiple resolutions)
Device: Apple Macbook M3 Air 13"
I wasn't able to reproduce this on Safari.

Attached below are some related screenshots:
<img width="1117" alt="image" src="https://github.com/pocketbase/pocketbase/assets/55552821/7e53bf0d-62b6-4a2a-8766-da98a6cb2b53">
<img width="1117" alt="image" src="https://github.com/pocketbase/pocketbase/assets/55552821/12900c17-b256-4c09-9413-edf87ef92539">

**Comment by ganigeorgiev** [comment]
It seems that Firefox rounds slightly differently non-integer pixels. I've updated the flatpicker styles in `master` to accommodate this but I'll not rush a release as it is not something critical or a blocker.
