### ISSUE TITLE
Application URLs doesn't work

### ISSUE THREAD

**Issue by cvpsmith** [pocketbase/pocketbase#4869]
The app doesn't allow the creation of x-scheme-handler URLs, so URLs such as vscode:// , rustdesk:// , mailto: , etc. don't work.  So far as I can tell, the app **only** supports http:// or https:// type URLs.

**Comment by ganigeorgiev** [comment]
If you mean custom schemes for the mail Action urls then this is not supported at the moment. The mail templates and their configurations are migrated to each individual auth collection as part of the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and I'll consider loosing the validators.
