### ISSUE TITLE
Date picker in admin UI shows wrong dates/days

### ISSUE THREAD

**Issue by ArcoMul** [pocketbase/pocketbase#4894]
I had to triple check the date/day/year for this, but today -May 10- gets shown as a Saturday, even though it should be a Friday:

<img width="324" alt="image" src="https://github.com/pocketbase/pocketbase/assets/1388162/0cd2064e-bff5-452b-a12e-ed7050473768">

PS. Thank you for this amazing piece of software, it has been an absolute joy to work with.

**Comment by ganigeorgiev** [comment]
It is already fixed in `master` as part of https://github.com/pocketbase/pocketbase/issues/4865.

I'll push a new minor v0.22.12 release sometime later this weekend.
