### ISSUE TITLE
Accent-insensitive when using getList (filter)

### ISSUE THREAD

**Issue by guilhermeguidetti** [pocketbase/pocketbase#4896]
Hello! 

```js
await backendClient
            ?.collection("users")
            .getList(0, 10, {
              filter: `name?~"%${searchTerm}%"||username?~"%${searchTerm}%"`,
            });
```

I have a user named 'Hábito' with the accented letter 'á'. When I use the search code, typing 'Habito' without the accent, it doesn't return any results. Is there a way for the search to find the accented word even if my search query doesn't include any accented letters?

**Comment by ganigeorgiev** [comment]
There is no support for this out of the box at the moment.

If you have other questions please use the Q&A discussions instead.
