### ISSUE TITLE
Expand single attribute not working

### ISSUE THREAD

**Issue by ZeroPie** [pocketbase/pocketbase#4900]
Can't manage to expand only single attributes using dot notation.

I do have  admin permissions 
and can expand the whole collection succesfully
http://127.0.0.1:8090/api/collections/bookings/records?expand=class_id

When i try to expand a single attribute, it is not included
http://127.0.0.1:8090/api/collections/bookings/records?expand=class_id.price

same for the sdk.
this returns me the complete expanded collection 
``` 
const records = await pb.collection("bookings").getFullList({
      sort: "-created",
      expand: "class_id",
    });
    return records;
```

this doesn't return the expanded attribute
``` 
const records = await pb.collection("bookings").getFullList({
      sort: "-created",
      expand: "class_id.name,class_id.shortDescription",
    });
    return records;
```

**Comment by ganigeorgiev** [comment]
It is not expected to work this way. `expand` operates only with `relation` fields.

If you want to expand only the `name` and `shortDescription` fields you need to specify the `fields` query parameter, something like:

```js
await pb.collection("bookings").getFullList({
    sort: "-created",
    expand: "class_id",
    fields: "*,expand.class_id.name,expand.class_id.shortDescription"
});
```
If you have other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose) instead as the threaded format is more suitable for this.
