### ISSUE TITLE
S3 Compatible Storage from Linode

### ISSUE THREAD

**Issue by blujedis** [pocketbase/pocketbase#4902]
I'm assuming File Storage can be used with any S3 compatible storage as the documentation suggests.

However the configuration you see here does not work. 

Any suggestions or am I dumb thumbing it?

![Screenshot 2024-05-11 at 3 28 34 PM](https://github.com/pocketbase/pocketbase/assets/40702290/aac14832-5087-4b37-86a4-c23834e52087)

**Comment by blujedis** [comment]
Check that this works, well I get a "S3 connected successfully" badge in green now.

The endpoint from Linode when you copy it includes the bucket name just remove that. 

So in the above example remove ```pbdb.``` from the endpoint which will result in ```us-lax-1.linodeobjects.com```

That will allow you to connect.

**Comment by oscadev** [comment]
@blujedis where do you get the valid region name? In my linode settings, it has invalid names like "US, Chicago, IL"

**Comment by oscadev** [comment]
@blujedis nvm, its in the url as "us-ord-1"

**Comment by blujedis** [comment]
I've done the very same thing...might have something to do with the 18 hour days we put in figure this crap out LOL.
