### ISSUE TITLE
Admin UI Firefox performance issue

### ISSUE THREAD

**Issue by iskaa02** [pocketbase/pocketbase#4903]
When opening a panel in Firefox (record panel, create record panel, etc.), the corresponding tab experiences:
- CPU usage reaching 100%.
- Memory usage continuously increasing until the system runs out of memory.

This issue persists until the tab process is manually terminated.

A profiler log showcasing the problem can be found [here](https://profiler.firefox.com/public/zdbz1vtdgpb08b8rzgneqgwrkfae21gaapkvb0r/calltree/?globalTrackOrder=01&implementation=js&thread=1&v=10).

Possible Cause: The issue seems to be related to styles computation as shown in the profiler.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it locally with the live demo and Firefox 125 (Linux/Fedora).

I'm not sure that I'm reading the profile correctly but it seems that the reported issue originate from the "Firefox Relay" extension.

While the UI performance can definitely be improved (especially around the overlay panels) but for now I'm not planning investing time on this unless there are clear reproducible steps.

**Comment by adgrig** [comment]
For future reference - I have tested this with Firefox Relay enabled/ disabled and can confirm that was the culprit.
