### ISSUE TITLE
CRUD requests blocked by hooks return 200

### ISSUE THREAD

**Issue by DaniDipp** [pocketbase/pocketbase#4906]
I created the following hook using javascript
```js
onRecordBeforeCreateRequest((e) => {
	return false;
});
```
It properly prevents the creation of new records, but if record creation is attempted via POST request, the response is 200. I would expect something like a 400 to be returned since it was not successful.

**Comment by ganigeorgiev** [comment]
It is working correctly. Returning `false` just stops the hooks chain allowing you to write a custom response. If you want to return an error you can `throw` -https://pocketbase.io/docs/js-routing/#error-response.

Also note that the hooks are refactored and will change as part of https://github.com/pocketbase/pocketbase/discussions/4355.

**Comment by DaniDipp** [comment]
Thanks for the clarification. I didn't realize that the routing docs apply in this capacity to the CRUD hooks. But in hindsight it makes a lot of sense.
