### ISSUE TITLE
Presentable columns are not referenced, when nested inside another relation

### ISSUE THREAD

**Issue by LuminareHQ** [pocketbase/pocketbase#4909]
Note: This may be more of a feature request than a bug.

When in the Admin UI, using a relation field to another table, that itself has a relation field to another table, the final table only displays its row id, rather than the presentable fields, in the initial table.

![image](https://github.com/pocketbase/pocketbase/assets/70502610/f6e2f3f0-5cd7-4e1d-b4eb-dfe91c3783b6)
example displaying a file, a group, and a file name.

![image](https://github.com/pocketbase/pocketbase/assets/70502610/17c1c953-84dc-48b4-ad23-b61f38ad97fb)
What it should display, referenced from the groups table and the groupName column.

Steps to Replicate
1. Import below config.
2. Add a row in the groups table filling all fields
3. Add a row in the groupFiles table filling all fields, referencing the created group row.
4. Add a row in the groupRoleFiles table, referencing the created groupFile row.
5. Created row shows the file, the group row id, and the created groupFile, fileName column.

<details>
<summary>Collection Config</summary>
<pre>
[
    {
        "id": "_pb_users_auth_",
        "name": "users",
        "type": "auth",
        "system": false,
        "schema": [
            {
                "system": false,
                "id": "users_name",
                "name": "name",
                "type": "text",
                "required": false,
                "presentable": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "system": false,
                "id": "users_avatar",
                "name": "avatar",
                "type": "file",
                "required": false,
                "presentable": false,
                "unique": false,
                "options": {
                    "mimeTypes": [
                        "image/jpeg",
                        "image/png",
                        "image/svg+xml",
                        "image/gif",
                        "image/webp"
                    ],
                    "thumbs": null,
                    "maxSelect": 1,
                    "maxSize": 5242880,
                    "protected": false
                }
            },
            {
                "system": false,
                "id": "zzqfhk0d",
                "name": "parentDigitalSignature",
                "type": "text",
                "required": false,
                "presentable": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "system": false,
                "id": "v42osfu0",
                "name": "parentDigitalSignatureDate",
                "type": "text",
                "required": false,
                "presentable": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            }
        ],
        "indexes": [],
        "listRule": "@request.auth.id = id",
        "viewRule": "@request.auth.id != ''",
        "createRule": "",
        "updateRule": "@request.auth.id = id",
        "deleteRule": "@request.auth.id = id",
        "options": {
            "allowEmailAuth": true,
            "allowOAuth2Auth": true,
            "allowUsernameAuth": false,
            "exceptEmailDomains": null,
            "manageRule": null,
            "minPasswordLength": 8,
            "onlyEmailDomains": null,
            "onlyVerified": false,
            "requireEmail": false
        }
    },
    {
        "id": "eot6rotg3l2uy2q",
        "name": "groups",
        "type": "base",
        "system": false,
        "schema": [
            {
                "system": false,
                "id": "udw0k7sh",
                "name": "groupName",
                "type": "text",
                "required": false,
                "presentable": true,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            }
        ],
        "indexes": [],
        "listRule": null,
        "viewRule": "",
        "createRule": "",
        "updateRule": "",
        "deleteRule": null,
        "options": {}
    },
    {
        "id": "5yztem0bkw1r66l",
        "name": "groupFiles",
        "type": "base",
        "system": false,
        "schema": [
            {
                "system": false,
                "id": "bgqm4rdw",
                "name": "file",
                "type": "file",
                "required": false,
                "presentable": true,
                "unique": false,
                "options": {
                    "mimeTypes": [
                        "image/jpeg",
                        "image/png",
                        "image/svg+xml",
                        "image/gif",
                        "image/webp",
                        "application/pdf",
                        "text/xml",
                        "text/plain"
                    ],
                    "thumbs": [],
                    "maxSelect": 1,
                    "maxSize": 95000000,
                    "protected": true
                }
            },
            {
                "system": false,
                "id": "ymakcpud",
                "name": "group",
                "type": "relation",
                "required": false,
                "presentable": true,
                "unique": false,
                "options": {
                    "collectionId": "eot6rotg3l2uy2q",
                    "cascadeDelete": true,
                    "minSelect": null,
                    "maxSelect": 1,
                    "displayFields": null
                }
            },
            {
                "system": false,
                "id": "jwr0uivg",
                "name": "fileName",
                "type": "text",
                "required": false,
                "presentable": true,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": "",
        "updateRule": "",
        "deleteRule": "",
        "options": {}
    },
    {
        "id": "qnbcfhcbjtwo7b1",
        "name": "groupRoleFiles",
        "type": "base",
        "system": false,
        "schema": [
            {
                "system": false,
                "id": "dzjqskun",
                "name": "file",
                "type": "relation",
                "required": false,
                "presentable": false,
                "unique": false,
                "options": {
                    "collectionId": "5yztem0bkw1r66l",
                    "cascadeDelete": true,
                    "minSelect": null,
                    "maxSelect": 1,
                    "displayFields": null
                }
            }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": "",
        "updateRule": "",
        "deleteRule": "",
        "options": {}
    }
]
</pre>
</details>

This should show the group name, due to it being presented in both the groups table, and the group files table, and both tables have the groupName column as a presented field.

Note: The exported collections are cut down to display the issue directly.

**Comment by ganigeorgiev** [comment]
This is a known limitation, see https://github.com/pocketbase/pocketbase/issues/3666.

For now there are no plans to work on this as most likely the UI representation will change after the refactoring.
