### ISSUE TITLE
Change: No body uses bytes, please add a dropdown option to select, between bytes, mb, gb, tb, yb

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4937]
Change: No body uses bytes, please add a dropdown option to select, between bytes, Mb, Gb, T, Y

![image](https://github.com/pocketbase/pocketbase/assets/5947268/cad801ce-fe18-47a8-a4f7-9f9d6273aaf7)
![image](https://github.com/pocketbase/pocketbase/assets/5947268/827f179f-e350-46d6-9355-2c19beee7e8f)

**Comment by ganigeorgiev** [comment]
For now there are no plans for this as the error message will also have to be adapted but I may reconsider it in the future as the UI will change anyway with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355).
