### ISSUE TITLE
Can't connect Minio S3 instance

### ISSUE THREAD

**Issue by mtkgeek** [pocketbase/pocketbase#4944]
Hi there, I can't put into words how awesome pockebase is, big ups to you guys. I'm trying to connect a self hosted version of Minio and cannot for the life of me get it to work. I have looked at every other Minio and S3 issue already. Signature does not match error with force style turned on, unknown apierror when I turn it off. I used the Minio python SDK with these exact credentials and was able to upload a file. Any help would be appreciated.
![Screenshot 2024-05-17 at 11 11 02](https://github.com/pocketbase/pocketbase/assets/28762536/2f78f188-fb98-453b-bfdd-8fa97de1473d)

**Comment by ganigeorgiev** [comment]
I don't see how this is a PocketBase issue.

Please check https://github.com/pocketbase/pocketbase/discussions/90.

I've also tested the current S3 integration with the MinIO playground and it is working correctly for me. Make sure that provided configuration is correct.

**Comment by ganigeorgiev** [comment]
For completeness, here is the configuration I used:

```
- Endpoint:   https://play.min.io
- Bucket:     pbtest123456
- Region:     us-east-1
- AccessKey:  Q3AM3UQ867SPQQA43P2F
- Secret:     zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
- path-style: true
```

![playground_screenshot](https://i.imgur.com/Ov0ctYA.png)

**Comment by mvartuc** [comment]
I'm having the exact same issue. #79 doesn't help in this case at all for me since I'm not using minio locally.

**Comment by ganigeorgiev** [comment]
@mvartuc As mentioned above it works correctly for me when testing with the live play.min.io.
Make sure that you have the correct permissions and use the correct access and secret keys. Other than this I don't know how to help further.

**Comment by mvartuc** [comment]
@ganigeorgiev I've tested a few other services (coolify, python, rclone) using the same credentials and everything else but pocketbase was fine accessing my s3 storage, which led me to believe it's an issue with pocketbase. I'm sorry if this is a flawed logic but that's just the only thing I can think off.

**Comment by mtkgeek** [comment]
@mvartuc if you're using cloudflare for your minio instance, try turning of proxy, use DNS only.

**Comment by ganigeorgiev** [comment]
@mvartuc It could be a compatibility issue with `aws-sdk-go-v2`, I don't know (we have a special case for GCS), but in any case without clear reproducible steps there is nothing much I can help with and I'm not going to waste time on a wild goose chase.
