### ISSUE TITLE
Feature Request: More/Custom Variables | Customize E-Mail Confirm Screen

### ISSUE THREAD

**Issue by OfflinePing** [pocketbase/pocketbase#4959]
Hey,
I saw you are working on extending the customizability of the Admin UI and wanted to throw in that I'd be lovely to be able to change the way the screen looks on confirming an E-Mail. Also, it would be awesome to have more and or custom Variables for the E-Mails that you can Configure or maybe even make new E-Mail Templates for different things like News which you can then easily send out too

**Comment by ganigeorgiev** [comment]
Sorry but I don't understand what is the intention of this issue. For now there are no plans to change how the default email settings should look or work.

If you have concrete suggestions feel free to outline them but just saying _"it would be awesome to have more and or custom Variables"_ doesn't really make sense to me.
