### ISSUE TITLE
404 pb_hooks kills all logic

### ISSUE THREAD

**Issue by migueljr** [pocketbase/pocketbase#4974]
![image](https://github.com/pocketbase/pocketbase/assets/12215747/3ccb9beb-e094-40bc-aa98-608e6e79d1de)

I'm trying to do a search but when this record doesn't exist, nothing else is executed and the API returns 404. I would like to be able to handle this here in the code and respond even with code 200 with a different message. is it possible to do that? I wasn't able to.

**Comment by ganigeorgiev** [comment]
I don't understand why users continue to do this, but please don't post code as screenshot. It is hard to read, difficult to follow and search. in case someone else has a similar problem.

In any case if you can wrap the failing code with `try/catch` block and return the response you want. See also https://pocketbase.io/docs/js-routing/#error-response.

If you have further questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) instead.
