### ISSUE TITLE
Feature: Integrate payments zone: SEPA, HyperSwitch, Stripe, Lemonsqueezy

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4982]
Feature: Integrate payments zone: SEPA, HyperSwitch, Stripe, Lemonsqueezy

**Comment by ganigeorgiev** [comment]
I'm not aware of standard Payment APIs and it will highly depend on the specific provider.

The actual payment integration will also depends on the specific user project (ex. monthly/yearly/etc. subscriptions, metered/usage based, features based, etc.) so I don't see how this could be done in an universal/generic way.

Feature requests are welcomed but just saying "I want X" without any details or suggestions how X should work I'm not planning investing time on it.
