### ISSUE TITLE
filters not working in production

### ISSUE THREAD

**Issue by cramervincent** [pocketbase/pocketbase#4983]
### Description
I have Pocketbase running on a VPS, and the URL is set by NGINX to https://api.vincent-dev.xyz/.

The issue I'm experiencing is that when using filters or pagination, I always get all the results without the filter being applied. For example:

`https://api.vincent-dev.xyz/api/collections/products/records?filter=(price=62)`

### Expected Result:

Should return just 2 objects.

### Actual Result:

Returns all objects.

However, when I run the following command locally:

`curl "http://localhost:8090/api/collections/products/records?filter=(price=62)"`
I get the correct result of just 2 objects.

### `Steps to Reproduce`

- [ ] Deploy Pocketbase on a VPS.
- [ ] Set up NGINX to route the URL to https://api.yourdomain.com
- [ ] Use a filter in the API request, e.g., ?filter=(price=62).

### Expected Behavior
The API should return filtered results based on the specified filter criteria.

### Actual Behavior
The API returns all the records, ignoring the filter criteria.

### Further information
my NGINX config file

```
server {
    server_name api.vincent-dev.xyz;

    location / {
        proxy_pass http://localhost:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
    }

    location ~* ^/api/(.*) {
        proxy_pass http://localhost:8090/api/$1;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
    }

    location ~* ^/pb/(.*) {
        proxy_pass http://localhost:8090/_/$1;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api.vincent-dev.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.vincent-dev.xyz/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = api.vincent-dev.xyz) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name api.vincent-dev.xyz;
    return 404; # managed by Certbot
}

```

**Comment by ganigeorgiev** [comment]
I don't understand your nginx config but I don't think this is a PocketBase issue.

The `filter` query parameter is working correctly. There are also integration tests that verify the correct behavior.

Make sure that the query parameter value is URL encoded (the SDKs do this automatically). In your case your url should be:

```
http://localhost:8090/api/collections/products/records?filter=price%3D62
```

If you still think that this is a PocketBase issue, please export your collections configuration as json (Admin UI > Settings > Export collections) and I'll try to have a more detailed look, but again it is most likely a client-side error.

**Comment by ganigeorgiev** [comment]
Note that since you are using a variable (`$1`) in the `proxy_pass` directive you may have to forward manually the query parameters too, aka. try changing it to:

```
proxy_pass http://localhost:8090/api/$1$is_args$args
```

But as mentioned earlier I don't exactly understand your Nginx config and the need to be split in 3 components so it may not be what you are looking for.

**Comment by cramervincent** [comment]
Thank you so much, your last comment did the trick!
