### ISSUE TITLE
Feature request: upload files using Presigned URLs

### ISSUE THREAD

**Issue by yoel262** [pocketbase/pocketbase#4994]
It would be nice to be able to upload files directly to the bucket using Presigned URLs: 1. To save bandwidth 2. For faster uploads; but still be able to manage the files' lifecycle as if they were a standard Pocketbase `file` field.

As for the API, having the SDK abstract away the presigned url generation would be great (like using the same FormData mechanism for adding files, but under the hood make an intermediate request to Pocketbase to get the signed url, and then upload the files using it).

https://developers.cloudflare.com/r2/api/s3/presigned-urls/

https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html

Related: https://github.com/pocketbase/pocketbase/issues/3691

**Comment by ganigeorgiev** [comment]
There are no plans for this out of the box as it will complicate the existing file upload flow.
