### ISSUE TITLE
Feature Request: I would pay/donate to have Table and Column Descriptions added

### ISSUE THREAD

**Issue by MrRedBeard** [pocketbase/pocketbase#5002]
I would pay/donate to have Table and Column Descriptions added and integrated into the UI. 

SQLite does not support descriptions/comments natively so a separate table of metadata would be needed but only populated if data is provided and not zero length. This would help organize purpose and use of the tables/columns on the UI. 

I'm thinking a table with 3 columns type, name, description:
type: table, column
name: table name or column name
description: text

Thoughts, negotiations? 

![meta-mockup](https://github.com/pocketbase/pocketbase/assets/10256850/19a7a242-c5a1-4974-8e64-3b9cd7c85bcc)

**Comment by ganigeorgiev** [comment]
Option to eventually add "field instructions" exists in the [roadmap](https://github.com/orgs/pocketbase/projects/2/views/1) but remains a low priority.
