### ISSUE TITLE
Restore v0.18.6

### ISSUE THREAD

**Issue by mrwyndham** [pocketbase/pocketbase#5003]
Hey guys,

I am getting the following issue after restoring a database from the backups

<img width="1512" alt="image" src="https://github.com/pocketbase/pocketbase/assets/49445824/f3a69179-6657-40a9-b206-a499ee5f257a">

**Comment by ganigeorgiev** [comment]
Backups are complete snapshots (this includes the app settings). Based on the error most likely the restored backup data doesn't SMTP configured and the application fallbacks to the default `sendmail` unix command, which doesn't seem to be available on the deployed env.

Or in other words - make sure that your SMTP configuration is properly set.

If you other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose) as the threaded format is more suitable for this type of posts.
