### ISSUE TITLE
Server error occur, contact administrator” when disable webauthn register & passwordless

### ISSUE THREAD

**Issue by p39e** [pocketbase/pocketbase#5004]
Hello everyone,
we have a problem that is so complicated, namely when we turn off the “Webauthn Register / passwordless” feature it appears error “Server error occurred, contact administrator”, we deliberately turned off the feature because if the feature is active the error appears “Security key registration result is invalid.
WebAuthn is not supported by this browser. Try another one or contact your administrator.” is there anyone here who has the same problem? please help us, thank you.
![Screenshot_3](https://github.com/pocketbase/pocketbase/assets/49261402/b35dc321-5baa-472c-98df-613ead993fd3)

![image](https://github.com/pocketbase/pocketbase/assets/49261402/1379660f-5e08-4583-813e-0cdaa8927fb0)

**Comment by ganigeorgiev** [comment]
I don't think your issue is PocketBase related and I don't know from where this screenshot is from.

PocketBase doesn't have Passkeys/WebAuthn support out of the box (see https://github.com/pocketbase/pocketbase/issues/406).
