### ISSUE TITLE
Customising ID field

### ISSUE THREAD

**Issue by devbyVeriTech** [pocketbase/pocketbase#5021]
Please I want to know if I can use hyphens when creating a customised ID for my pocketbase app.

I’m creating a movie web app and I don’t want to use the ID in the url field.
I’ll prefer using the slug but in this case, I’ll still have to use the ID before I can get the single movies.

Any help on this?

**Comment by ganigeorgiev** [comment]
This was requested several times but it is not possible at the moment.

More control over the system fields will be available with the next release (see [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355); there are no ETAs yet).

**Comment by ganigeorgiev** [comment]
> I’ll prefer using the slug but in this case, I’ll still have to use the ID before I can get the single movies.

I forgot to mention that you can use the `getFirstListItem` helper if you want to retrieve a single record by a non-id field:

```js
await pb.collection("example").getFirstListItem(`slug="something"`)
```

**Comment by devbyVeriTech** [comment]
Actually I want to use it in a dynamic route (src/route/movie/[movieId]) so I’m kinda wondering how to replace the “await pb.collection("example").getFirstListItem(movieId)” with “await pb.collection("example").getFirstListItem(`slug="something"`)” dynamically.

**Comment by ganigeorgiev** [comment]
The filter parameter is a plain string. You can "embed" JS variables using concatenation or [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

Another alternative is to use the [`pb.filter()` helper](https://github.com/pocketbase/js-sdk?tab=readme-ov-file#binding-filter-parameters):

```js
const filter = pb.filter("slug={:slug}", { slug: "your slug" })
await pb.collection("example").getFirstListItem(filter)
```
