### ISSUE TITLE
Feature Request: Relation field readjustment

### ISSUE THREAD

**Issue by devbyVeriTech** [pocketbase/pocketbase#5028]
I’m working on a movie website, where I have the actors collection and a movies collection.
Now when creating a post for movies and I select some actors for that movie, I’ll still have to go back to the actors collection to link the movie again.

what I’m suggesting is, when I create a relation (actors relation in the movies collection), those movies that were linked to the actors should be able to show when I visit the actors collection also without me having to link them in the second collection again.
I just hope my explanation is understandable

**Comment by ganigeorgiev** [comment]
> I select some actors for that movie, I’ll still have to go back to the actors collection to link the movie again.

The `relation` field ideally usually will be only in one of the collection to avoid data duplication and syncing problems.

If you are asking for the UI to show the indirect relations or references then this already [exists in the roadmap](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=indirect&pane=issue&itemId=32121831) but remains a low priority.
