### ISSUE TITLE
Feature Request: wild card mime types for file fields

### ISSUE THREAD

**Issue by odama626** [pocketbase/pocketbase#5032]
It would be cool to allow `image/*` to allow all image types like the browser does

A valid MIME type string, with no extensions.
The string audio/* meaning "any audio file".
The string video/* meaning "any video file".
The string image/* meaning "any image file".

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers

**Comment by ganigeorgiev** [comment]
For now there are no plans for this as it will complicate unnecessary the UI and the validator checks. If you want to insert multiple mimetypes at once you can select one of the "presets":

![presets](https://i.imgur.com/tMiSF9L.png)
