### ISSUE TITLE
 "displayFields" is null

### ISSUE THREAD

**Issue by leuwenn** [pocketbase/pocketbase#5037]
Hi, 
When i export the collections configuration, all displayFields are null :
![Firefox_Screenshot_2024-06-06T10-20-58 854Z](https://github.com/pocketbase/pocketbase/assets/108098754/b954e2f1-ada6-47b1-b70d-5e0f50931d29)

![Firefox_Screenshot_2024-06-06T10-23-51 465Z](https://github.com/pocketbase/pocketbase/assets/108098754/6583b882-b75e-4480-b0cf-42a4aaea3338)

**Comment by ganigeorgiev** [comment]
It is expected because the field is deprecated (it is no longer used) in favor of `presentable`. It will be removed together with some other deprecated APIs with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355).
