### ISSUE TITLE
Proposal: Need for OpenAPI V3 specification for PocketBase API

### ISSUE THREAD

**Issue by itsmeadarsh2008** [pocketbase/pocketbase#5048]
PocketBase is a great backend solution for fast app development and deployment. Having an OpenAPI specification available for the PocketBase API would be very helpful to improve the developer experience and integration with different tools and platforms. **Currently, there's no official OpenAPI specification for the PocketBase API, making it challenging for developers to integrate and use PocketBase with OpenAPI-supported tools like Swagger and Postman to generate API clients.**

**Comment by itsmeadarsh2008** [comment]
I have analyzed #799, #945, and #208. It will enable everyone to store it at `{project_root}/openapi/openapi.json`. This makes it easier to generate SDKs, can be auto-synced with API docs using GitHub Actions, and release new versions.

**Comment by ganigeorgiev** [comment]
As mentioned in https://github.com/pocketbase/pocketbase/issues/945, this remains a very low priority for now.

Note that this doesn't necessary needs to be part of the repo and can be implemented externally as server-side "plugin" using the available app event hooks.
