### ISSUE TITLE
Feature: Add encrypted fields

### ISSUE THREAD

**Issue by mrjeanp** [pocketbase/pocketbase#5053]
Just wondering if there's a way to add encrypted fields here:
<img width="667" alt="image" src="https://github.com/pocketbase/pocketbase/assets/47196328/7984fecf-5be2-4c3a-b629-97b5536526ef">

I really love this project.

**Comment by ganigeorgiev** [comment]
Without details what and how they should work there are no plans for this for now.
See also https://github.com/pocketbase/pocketbase/issues/2798.
