### ISSUE TITLE
hooks watcher restarts for any file change in the pb_hooks directory

### ISSUE THREAD

**Issue by godmar** [pocketbase/pocketbase#5059]
Hi, I observed the following behavior by chance and thought I'd document it as a possible enhancement.

I understand from the documentation that JS files in the `pb_hooks` directory should end with `.pb.js` (or match the `config.HooksFilesPattern`), but in the log I see that PB restarts for any file change in the directory it watches:
```
File /pb/pb_hooks/.user_hook.js.swp changed, restarting...
2024/06/09 19:36:39 Server started at http://0.0.0.0:8080
├─ REST API: http://0.0.0.0:8080/api/
└─ Admin UI: http://0.0.0.0:8080/_/
File /pb/pb_hooks/result_hook.js changed, restarting...
2024/06/09 19:36:43 Server started at http://0.0.0.0:8080
├─ REST API: http://0.0.0.0:8080/api/
└─ Admin UI: http://0.0.0.0:8080/_/
```
`/pb/pb_hooks` is a directory mounted in a container with host Linux.

Should [`jsvm.go`](https://github.com/pocketbase/pocketbase/blob/970b00011f45f9da40a6b212c307ad0af3a3aaa9/plugins/jsvm/jsvm.go#L382-L398) check whether the changed file matches `HooksFilesPattern` before triggering a restart? 
If not, could it at least exclude events related to hidden (dot files)?

**Comment by ganigeorgiev** [comment]
This is an intended behavior in case there are template files or other resources because the hooks can't be "unloaded". You can disable the watcher with `--hooksWatch=false`.
