### ISSUE TITLE
Subject: Issue with Changing Password for OAuth2 Accounts

### ISSUE THREAD

**Issue by hugo-abdou** [pocketbase/pocketbase#5070]
Hello PocketBase Team,

I hope this message finds you well. I am encountering an issue with my application and I wanted to bring it to your attention.

When attempting to change the password for a user who has logged in via an OAuth2 provider (such as Google or GitHub), I receive an error, as shown in the attached screenshot. The root of the problem seems to be that, since the OAuth2 account does not have a password saved in the database, the application cannot update it.

I am looking to provide an option for users to switch from OAuth2 login to a password-based login. However, this functionality is currently blocked due to the issue above.

I hope this explanation is clear, and I appreciate your attention to this matter. I appreciate your support.

Best regards,

Hugo Abdou

Please feel free to adjust any personal details or specificities you need.

![image](https://github.com/pocketbase/pocketbase/assets/44982282/c0912ecf-53dc-43e6-82a2-602ee5b0febc)

**Comment by ganigeorgiev** [comment]
Please see https://github.com/pocketbase/pocketbase/discussions/5068.

**Comment by ganigeorgiev** [comment]
I also forgot to mention that an alternative if the user has an email is to send a password reset request.

**Comment by hugo-abdou** [comment]
@ganigeorgiev  thank you it seams like this how i should do it
