### ISSUE TITLE
Feature Request: Subcollections

### ISSUE THREAD

**Issue by AIDigitalAgencyInc** [pocketbase/pocketbase#5072]
Collection -> Doc -> Subcollection -> Doc

**Comment by ganigeorgiev** [comment]
Please don't open issues without elaborating how and what actually is the intended purpose of the request.

In any case, based only on the title there are no plans for now for subcollections. There is another similar feature request for subfields in https://github.com/pocketbase/pocketbase/issues/2491 but it is also out of the roadmap for now and remains open eventually for later consideration.

See also https://github.com/pocketbase/pocketbase/discussions/1212.
