### ISSUE TITLE
Support for @request.cookies when using database rules

### ISSUE THREAD

**Issue by phcoliveira** [pocketbase/pocketbase#5082]
Hello there. I was wondering if I could have access to the cookies when defining security rules. We already can use `@request.headers`, so the `cookie` header must be there as well. However, it is impractical to use it while defining rules, if not outright impossible.

I wanted to use a cookie in order to avoid creating anonymous users for a simultaneous game, without the need of deleting all of them at some point.

Perhaps I can use something like `@request.headers.cookie.match(teamId)`, but it is arguably more ergonomic to have it as `@request.cookies.team_id == teamId`.

Anyways, given that a WebSocket does not carry the original handshake headers at every message, I wanted to know how the macro `@request.headers` is still populated when the `@request.context == 'realtime'`. Seems like magic. Here is what ChatGPT has to say about it.

```
PocketBase can remember the initial headers for every WebSocket connection through a process that involves storing the initial HTTP request headers when the WebSocket connection is first established. Here's a detailed look at how this is typically managed:

WebSocket Handshake
Initial HTTP Request:

When a client initiates a WebSocket connection, it sends an HTTP request to the server with headers that include details such as cookies, authentication tokens, and other relevant information.
This HTTP request is intercepted by the server before the WebSocket protocol upgrade is performed.
Storing Headers:

During this initial handshake, the server can capture and store the HTTP headers associated with the request.
These headers are stored in the server's session or connection context, which is associated with the WebSocket connection.
Upgrading to WebSocket:

After capturing the headers, the server responds with an HTTP 101 status code to switch protocols from HTTP to WebSocket.
The WebSocket connection is established, and the initial request context, including headers, is retained in the server’s memory for the duration of the connection.
Using Stored Headers in PocketBase
PocketBase likely employs similar mechanisms to remember and utilize these headers for realtime database rules evaluation:

Session Management:

PocketBase retains the initial connection context, including the headers, in a session or connection object.
This context is accessible whenever a message is sent via the WebSocket, allowing the server to reference the stored headers.
Realtime API Context:

When evaluating access rules for realtime updates (@request.context == "realtime"), PocketBase can access the stored headers through the request context.
This allows the use of @request.headers in database rules, ensuring that even in realtime scenarios, the initial headers can be referenced for permission checks.
Example in Practice
When a WebSocket connection is initiated:

The server captures and stores the initial HTTP headers.
Throughout the WebSocket session, these headers remain accessible via the request context.
PocketBase can then use these headers in rule evaluations to ensure that proper access control is maintained.
Conclusion
PocketBase retains the initial HTTP headers by storing them in the connection context during the WebSocket handshake. This stored information is then used to enforce database rules throughout the lifetime of the WebSocket connection, ensuring secure and consistent access control based on the initial request headers.

For more technical details, you can refer to the [PocketBase documentation on API rules and filters](https://pocketbase.io/docs/api-rules-and-filters/) and [API Realtime](https://pocketbase.io/docs/api-realtime/).
```

WDYT? And thanks in advance.

**Comment by ganigeorgiev** [comment]
I'm sorry but I'm not going to read some random generated nonsense. Note that PocketBase uses Server-Sent Events (SSE), not WebSockets.

> I wanted to use a cookie in order to avoid creating anonymous users for a simultaneous game, without the need of deleting all of them at some point.

I'm not sure I follow. For now there are no plans to add special handling for cookies as I don't exactly understand the use case and what the above expression is supposed to represent.

If you just want to send some user specific value to the server and check it via the API rules you can pass it as a plain header instead (for the realtime subscruptions we create a stub `@request` object based on the subscribed topic's options). For example:

```js
pb.collection("example").subscribe("*", (e) => {
    ...
}, {
    // other options like expand, custom headers, etc.
    headers: {
        "X-Team-Id": "..."
    }
})
```

Then if you want to check it with the API rules you can do something like:

```js
// all header keys are normalized to lowercase and "-" is replaced with "_"
@request.headers.x_team_id = "something"
```

If the above doesn't help, feel free to elaborate a little more on your use case and the desired behavior but please don't use llm.

**Comment by phcoliveira** [comment]
@ganigeorgiev, although the snippets you wrote are useful, they are not what I had in mind. Consider this use case:

1. A registered user creates a team and become its admin.
2. The team id is a non-guessable token.
3. A QR code is generated using the team id, so others can join by reading it.
4. **Option 1**: each member of the rest of group can be signed in anonymously, which does require a user to be created in PB, only to be deleted later. 
5. **Option 2**: when reading the QR code, the server verifies that the team ID exists and sets an HTTP-only cookie.

Option 2 does not require a user record to be created, and the user would be automatically "signed out" when the cookie expires.

Your suggestion for explicitly passing the header `x-team-id` is good, but would not work with an HTTP-only cookie, as its value could not be read by the client. So, in order to the headers, the client would probably need to store the team-id and use at each subscription, which is possible to do, but not simpler.

**Comment by phcoliveira** [comment]
What I meant with this: `@request.headers.cookie.match(teamId)` is "check if the cookie header string matches the property `teamId` of the present record, whose security rules are being defined now".

**Comment by ganigeorgiev** [comment]
Thanks for clarifying.

Even if we had support to target a single specific cookie value from the API rules you still will not be able to use it with the realtime subscriptions unless we also serialize that with the subscription topic, which I'm not sure if it would be a good idea because it will also require adding further options to control whether to include "credentials" or not in order to emulate similar settings as sending regular http request.

The described use case seems very app specific and too limited to me (_you are essentially using the "team id" as API key and everyone acts on behalf that "team id" which may not be that useful because at some point you may need to separate the actions of each individual "anonymous" users so that they can later "upgrade" their account_).

I may reconsider adding special cookie handling in the future it if there is users demand for it or a more prominent use case arise but for now this remains out of the scope for v1.
