### ISSUE TITLE
Proposal: add API based end-to-end (aka e2e) testing

### ISSUE THREAD

**Issue by LinuxSuRen** [pocketbase/pocketbase#5085]
## Describe the feature
I'm the author of [api-testing](https://github.com/LinuxSuRen/api-testing) which is an API testing tool. It seems that no e2e testing in this project. I'd be happy to implement it if you believe it's worth.

In order to let you have a quick kowning about it. Please see also the user's of [api-testing](https://github.com/LinuxSuRen/api-testing/discussions/284).

**Comment by ganigeorgiev** [comment]
I don't think there is need for this. We have both unit and integration tests for most of the APIs.
