### ISSUE TITLE
Disable HTTPS/SSL (443 already in use)

### ISSUE THREAD

**Issue by tegola** [pocketbase/pocketbase#5087]
Hello,
I'm trying to setup pocketbase behing a reverse proxy (nginx) by proxying the 80/443 ports to the internal 8090 exposed by nginx, which I started running `./pocketbase serve pb.mydomain.com --http="0.0.0.0:8090"`.

When doing so, however, pocketbase whines about the port 443 being already used (of course):

```
2024/06/17 07:05:41 Server started at https://pb.mydomain.com
├─ REST API: https://pb.mydomain.com/api/
└─ Admin UI: https://pb.mydomain.com/_/
Error: listen tcp 0.0.0.0:443: bind: address already in use
```

Is there a way to disable https?

I also tried to expose the ssl port with `--https="0.0.0.0:8444`, but looks like there are issues with let's encrypt certificates, so I'd like to manage them myself.

Here's my nginx configuration (it's a custom config for [Hestia](http://hestiacp.com)).

```nginx
server {
        listen      <myip>:443 ssl;
        server_name pb.mydomain.com;
        error_log   /var/log/apache2/domains/pb.mydomain.com.error.log error;

        ssl_certificate     /home/myuser/conf/web/pb.domain.com/ssl/pb.domain.com.pem;
        ssl_certificate_key /home/myuser/conf/web/pb.domain.com/ssl/pb.domain.com.key;
        ssl_stapling        on;
        ssl_stapling_verify on;

        location / {
                proxy_set_header Connection '';
                proxy_http_version 1.1;
                proxy_read_timeout 360s;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_ssl_server_name on;
                proxy_ssl_name $host;

                proxy_pass http://127.0.0.1:8090;
        }
}


server {
        listen      <myip>:80;
        server_name pb.domain.com;
        return 301 https://$host$request_uri;
}
```

Thanks

**Comment by ganigeorgiev** [comment]
I have no experience with Hestia, so I don't think I can help you with that but if you have a reverse proxy (in your case Nginx) and probably certbot that takes care for the certificate then you don't need to specify a domain when starting the executable.

When you specify a domain PocketBase will attempt to issue a Let's encrypt certificate for you, but the certificate validation can happen only on 80/443 ports. Or in other words start the executable with just:

```sh
# to use the default 127:0.0.1:8090 port
./pocketbase serve

# or if you need to specify some different local port:
./pocketbase serve --http="127.0.0.1:6789"
```
_(note that if you want to bind to all IPv4 interfaces you can change 127.0.0.1 to 0.0.0.0)_

In any case this is not a PocketBase issue (although I guess the documentation could be improved regarding the reverse proxy integration). If you have other questions please use the [Discussions](https://github.com/pocketbase/pocketbase/discussions) as the threaded format is more suitable for this type of posts.

**Comment by tegola** [comment]
@ganigeorgiev letting pocketbase handle the certificate did indeed work. This is also a simpler setup.

Thanks!
