### ISSUE TITLE
New feature for create record

### ISSUE THREAD

**Issue by haoziy** [pocketbase/pocketbase#5091]
https://pocketbase.io/docs/api-records/#create-record
Need a new Feature For Multiple inserts
Insert Record one by one Very snow, low efficiency

**Comment by haoziy** [comment]
> https://pocketbase.io/docs/api-records/#create-record Need a new Feature For Multiple inserts Insert Record one by one Very snow, low efficiency

**Comment by ganigeorgiev** [comment]
Batch create/update/delete Web APIs have been already implemented as part of the [ongoing refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) (there are no ETAs yet).
