### ISSUE TITLE
Proposal: labels/folders for collections

### ISSUE THREAD

**Issue by lukepighetti** [pocketbase/pocketbase#5094]
Being able to pin collections is a really nice feature. It would be great if we could instead make labels (1-M relation) or folders so we can group these. A use case would be one pocketbase instance for multiple apps where some tables are shared and others are intended to be app specific.

<img width="325" alt="Screenshot 2024-06-18 at 7 53 00 AM" src="https://github.com/pocketbase/pocketbase/assets/666539/0d6383ed-7281-4cd5-9d58-9e9372b9040c">

**Comment by ganigeorgiev** [comment]
This was suggested before but I remain against it as it will clutter the UI.

I may reconsider it with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) but for now remains out of the scope.
