### ISSUE TITLE
Proposal: Allow Discord OAuth without Email scope

### ISSUE THREAD

**Issue by AtherActive** [pocketbase/pocketbase#5102]
Currently, when using the Discord OAuth, users are required to share their email, even when this could be avoided or is unneeded. Therefore, I would propose that an option is implemented that allows you to enable/disable Discord OAuth with Email. 

Below is a quickly-made mock-up of how it could look in the Admin UI:
![Screenshot 2024-06-19 150639](https://github.com/pocketbase/pocketbase/assets/34745358/df8221bb-2cc8-432b-af46-ae6efbd14263)

It could perhaps also work well with the already existing email toggle:
![image](https://github.com/pocketbase/pocketbase/assets/34745358/9f3ec837-5876-413e-ade9-0f3c0cf97172)

**Comment by ganigeorgiev** [comment]
The scopes are not hardcoded, they are just defaults.

Users can change them by directly modifying the provider auth url returned by `listAuthMethods`.

If you are using the "all-in-one" OAuth2 auth flow, then you can specify custom scopes using the `scopes` option:

```js
await pb.collection("users").authWithOAuth2({
    provider: "discord",
    scopes: ["identify"],
})
```

If you need further help, please open a Q&A discussion as the threaded format is more suitable for this.
