### ISSUE TITLE
Question Feature: How can i make a custom id field in pocketbase

### ISSUE THREAD

**Issue by yamadaOliva** [pocketbase/pocketbase#5108]
Thank you for creating such an excellent framework for the community. 
I would like to know how I can create a custom field, for example, (U000001) that auto-increments to (U000002, U000003), and so on. What steps should I follow to achieve this?

**Comment by ganigeorgiev** [comment]
You can't. The `id` field is not customizable at the moment and must always have 15chars length.

This is already changed with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355).
