### ISSUE TITLE
Notion authentication config

### ISSUE THREAD

**Issue by lucafaggianelli** [pocketbase/pocketbase#5124]
I'm trying to authenticate via Notion, I can use the generic OIDC provider, but I have a problem with the user info endpoint, apparently Notion doesn't expose the `userinfo` endpoint so I'm using a generic API endpoint for that:

<img width="558" alt="image" src="https://github.com/pocketbase/pocketbase/assets/4471043/8c69f95b-0786-44c3-95a3-402d8feb14d3">

Sadly though Notion needs a specific HTTP header (`Notion-Version`) for the API to work, so I tried to pass those header via code but it's not sent to the Notion API as Notion says that the version header is missing:

```ts
const authData = await pb.collection('users').authWithOAuth2({
      provider: 'oidc',
      headers: { 'Notion-Version': '2022-06-28' },
    })
```

So do you see a workaround to make the Notion auth work or should I create a new auth provider?

Edit: yes I just saw the open PR

**Comment by ganigeorgiev** [comment]
The generic OIDC provider is only for vendors that implements the OpenID Connect spec and I don't think Notion does (or at least I'm not able to find it in their documentation; if that's not true please post a link to the related docs).

In any case there is already a PR for a Notion client but it will be merged after [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355).

If you have other questions, please use the [repo's discussions](https://github.com/pocketbase/pocketbase/discussions) as the threaded format is more suitable for this type of posts.
