### ISSUE TITLE
Feature Request: Protected text field

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#5135]
I want to as kfor ability to set plain text fields as protected fields, it would be like password - when entering value it would show dots and it db it would show either nothing - if field accepts empty as input or show dots up instead of letters.
In record edit field would show up as dots if it has value.
This would allow to have secret values in non user collections in text fields

**Comment by ganigeorgiev** [comment]
See https://github.com/pocketbase/pocketbase/issues/2798, https://github.com/pocketbase/pocketbase/issues/5053.

**Comment by pietru2004** [comment]
ok I see
