### ISSUE TITLE
Feature Request: Add optional hint text to fields like Text, Url, or other similar types in Admin UI

### ISSUE THREAD

**Issue by devmuaz** [pocketbase/pocketbase#5146]
Hi There,

I was wondering if there's any possibility of adding a hint text to fields like `Text` or `Url` in the `Admin UI`, this would be so helpful if we have a collection that contains many fields that might look similar in the context of names, the hint here would explain exactly what this field does or require.

This feature would be a GREAT value to the `PocketBase`.

Thank You!

**Comment by ganigeorgiev** [comment]
This was suggested several times before and it exists in the [roadmap](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=instructions&pane=issue&itemId=37392385) to eventually reconsider it sometime in the future but for now remains a very low priority.
