### ISSUE TITLE
Linking an OAuth povider vs Signing In

### ISSUE THREAD

**Issue by mr-josh** [pocketbase/pocketbase#5151]
## The problem

Lets say we have 2 accounts:

**Account A** has a twitch account "twitch123" linked to it.
**Account B** has no twitch account linked.

Account B has access (with permission) to use the twitch account "twitch123". They go to link the twitch account with Account B and the request looks to behave correctly, however after clicking around a bit they realise its now Account A they're signed into.

## Fix discussion

Technically the `.authWithOAuth2(...)` is behaving correctly, and if it was just an login flow then this would probably be okay but in the case where we already have a login and we want to explicitly link Account B to "twitch123", it feels a bit confusing when the account just changes users. Maybe having something like a "This OAuth provider is already linked" message but I also understand is not really the intended purpose of the function.

For some references, Supabase has a beta feature where you can manually link an OAuth provider with the current signed in account: https://supabase.com/docs/guides/auth/auth-identity-linking#manual-linking-beta

I'm using pocketbase as part of a go project and am getting to know the ins and outs of things (though am still pretty fresh) but am happy to contribute a solution to this if we land on something.

**Comment by ganigeorgiev** [comment]
There is no support for linking multiple OAuth2 accounts from the **same** provider to a single PocketBase user and there are no plans for now to allow it as I'm not sure how that will work and how if "Account A" authenticate will choose which PocketBase user to use.

If you have an existing PocketBase user and want to explicit link an OAuth2 account (that hasn't been linked to another PocketBase user yet) it is enough to authenticate twice, eg.:

```js
await pb.collection("users").authWithPassword("test@example.com", "1234567890")

await pb.collection("users").authWithOAuth2({ ... }) // if the account is new then it will be linked to the test@example.com user
```

If you need further assistance or have other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead as the threaded format is more suitable for this type of posts.

**Comment by fondoger** [comment]
@dotmrjosh You can implement this with a custom hook.

```hook.go
	app.OnRecordAuthWithOAuth2Request().BindFunc(func(e *core.RecordAuthWithOAuth2RequestEvent) error {
		// User A tries to link an already registered User B via social login
		if e.Auth != nil && e.Record != nil && e.Auth.Collection().Id == e.Record.Collection().Id && e.Auth.Id == e.Record.Id {
			return e.Error(http.StatusConflict, "The oauth provider is already linked with another account", nil)
		}
		return e.Next();
	})
```
