### ISSUE TITLE
TestMailer causes Data Race warning

### ISSUE THREAD

**Issue by pnmcosta** [pocketbase/pocketbase#5157]
As per title, the [TestMailer](https://github.com/pocketbase/pocketbase/blob/master/tests/mailer.go) is not "routine safe":

```
==================
WARNING: DATA RACE
Read at 0x00c000fcd2b0 by goroutine 235:
  github.com/pocketbase/pocketbase/tests.(*TestMailer).Send()
      /root/go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.13/tests/mailer.go:27 +0x48
```

To give you some context, I have a cron job that may send many emails and I'm leveraging `routine.FireAndForget` cause I don't "care" about the result, unfortunately I get the data race warning.

I can create a reproducible example, but it's pretty obvious. 

Since this is not critical for the project, but slightly urgent for my feature release, I can help with a PR.

I notice you have `// @todo consider deprecating the above 2 fields?` comment but the `SentMessages` slice will also be impacted, should TestMailer have it's own lock?

**Comment by ganigeorgiev** [comment]
On second read, if you meant that the append operation is not concurrent safe - then I'll consider pushing an update sometime later this week together with the expected Go security fix - https://groups.google.com/g/golang-announce/c/zz9YfuJ6eCc.

**Comment by pnmcosta** [comment]
Yah, pretty sure it won't be safe to append to that slice either. I think a mutex would be a fix for both, I don't really care about performant TestMailer 😅

I'm getting my project up to date with the latest release and then do a patch on my PB fork.

**Comment by ganigeorgiev** [comment]
I've added a mutex in the `develop` branch that should silence the `Send` data race warning.

The refactoring comes with a slightly different TestMailer implementation that relies on getters and will be covered better by the mutex but again usage of `routine.FireAndForget` is prone to tests data races (_I'll see eventually in the future how feasible would be to replace the test implementation with the `//go:linkname`_).

**Comment by pnmcosta** [comment]
Awesome, thank you so much.

**Comment by pnmcosta** [comment]
Ah, didn't work, writes no longer triggers the warning, but reads still do, I'm asserting after my test scenario if the send value is correct. It warns both on reading the field or len the slice.

But please don't worry about this anymore (I'm sure you have bigger things with the refactoring) I'll have a look where `//go:linkname` may work for me (I'm not aware of what/how it works but am curious now).

**Comment by pnmcosta** [comment]
Yup, I'm using a bespoke `ApiScenario` to suit my job's setup, with delay, stats and before/after methods. I was asserting after the job run that the number of emails sent was correct.

Unfortunately I couldn't get `//go:linkname` to work, I made sure I was importing `unsafe` and the `pb\routine` packages but it never overrides the method. I tried with Vscode's unit testing and also manually with go test. Perhaps there's something else specific you need to do to make it work.

Since I already have another test to asserts mails are being sent and I only really need to know whether the job run processed the number I'm expecting I removed the mail check and just use the run stats to ensure all/none have been processed, which circumvents the data race issue on reads.

Thanks for all the help 🙇

**Comment by ganigeorgiev** [comment]
> Unfortunately I couldn't get //go:linkname to work

It is possible that the symbol path in the example I've provided is not correct. You could try with:

```go
import (
    ...
    "github.com/pocketbase/pocketbase/tools/routine"
    _ "unsafe"
)

//go:linkname fireAndForget github.com/pocketbase/pocketbase/tools/routine.FireAndForget
func fireAndForget(f func(), wg ...*sync.WaitGroup) {
    f()
}
```

If the above also doesn't work then it is possible that the Go compiler is inlining the `FireAndForget` function (_aka. it may require `//go:noinline` to the routine.FireAndForget declaration_).

**Comment by ganigeorgiev** [comment]
I've just tested the below and it is working correctly for me:

```go
package example_test

import (
	"sync"
	"testing"

	_ "unsafe"

	"github.com/pocketbase/pocketbase/tools/routine"
)

//go:linkname fireAndForget github.com/pocketbase/pocketbase/tools/routine.FireAndForget
func fireAndForget(f func(), wg ...*sync.WaitGroup) {
	f()
}

func TestFireAndForget(t *testing.T) {
	calls := 0
	routine.FireAndForget(func() {
		calls++
	}, nil)

	if calls != 1 {
		t.Fatalf("Expected calls %d, got %d", 1, calls)
	}
}
```

`go test ./... -v`

But as mentioned earlier, the above could have some unintended side-effects, so I'm not sure I could recommend it but if it is only for the tests I guess it should be fine.
