### ISSUE TITLE
Proposal: support typescript in pb_hooks

### ISSUE THREAD

**Issue by lucafabbian** [pocketbase/pocketbase#5159]
A big advantage of using js-based hooks is they can extend Pocketbase and they require no kind of preprocessing or setup.
One can write their server side functions, upload them and they just work out of the box.

In my humble opinion, it would be nice to support typescript out of the box too - compared to other technologies, typescript has a special role, and is already well integrated inside Pocketbase. Many people already use typescript on the client, it would be nice to be able to copy/paste functions from there without the painful experience of setting up another transpiler.

As far as I understand, this requires little effort thanks to packages like [go-typescript](https://github.com/clarkmcc/go-typescript/tree/master), which is already built on goja. If you wish, I can work on that and propose a pull request.

**Comment by lucafabbian** [comment]
why do you think it would be difficult to mantain? As far as I understand, you just have to wrap functions from 
`executeJS(code)` to `executeJS(removeTypes(code))`. I'm not talking about type generation and so on - those would be difficult to implement. I am just advocating for stripping types, the same way that tools like esbuild, babel and bun work. Again, there is already a package (go-typescript) that is able to do that with little effort, and is already built on goja, the same engine that power pocketbase, so it would be trivial to adapt it. It's just a middleware you set once and then should work forever.

I'm curious about other people needing this: other tools like bun make a great market point about it being a quality of life improvement.
That said, your choice. If you change your mind, I renew the availability to code it myself and submit a pull request.

**Comment by ganigeorgiev** [comment]
Because it is another external dependency that will be hard to keep up-to-date with the TypeScript development.

You are free to use `go-typescript` to transpile your .ts file. It doesn't need to be part of the main repo and can be implemented as a "plugin" similar to the JSVM.

Also see https://github.com/pocketbase/pocketbase/discussions/4355.
