### ISSUE TITLE
Feature Suggestion: Organizing Tables in Folders in the Admin-UI

### ISSUE THREAD

**Issue by uazapi** [pocketbase/pocketbase#5176]
Hello ganigeorgiev,

Congratulations on the excellent work with Pocketbase!

I would like to suggest a feature for the Admin-UI: the ability to create folders to organize tables. In projects with many tables, this would make navigation and management more intuitive and efficient.

Thank you for considering this suggestion.

Best regards,

**Comment by ganigeorgiev** [comment]
See https://github.com/pocketbase/pocketbase/issues/5094, https://github.com/pocketbase/pocketbase/issues/4455, https://github.com/pocketbase/pocketbase/issues/2438, https://github.com/pocketbase/pocketbase/issues/2297 and probably others.
