### ISSUE TITLE
does not support the '<=' operator"

### ISSUE THREAD

**Issue by chaojixiaoyao** [pocketbase/pocketbase#5187]
invalid sign operator "=<"

![not support](https://github.com/pocketbase/pocketbase/assets/33836706/db02609f-a7da-4f56-bd61-5e4148431de2)

**Comment by ganigeorgiev** [comment]
It is not a PocketBase issue. If you are sending the request manually make sure that the query parameters are properly URL encoded (the SDKs do this behind the scenes).

**Comment by chaojixiaoyao** [comment]
i make a mistake.  =< should replace with <=
