### ISSUE TITLE
admin not able to create two rows at once?

### ISSUE THREAD

**Issue by yongyi520** [pocketbase/pocketbase#5193]
### Issue: 
If I create two rows data set at once wrapped in Promise.all() on a test collection, it will abort one call, and succeed in another. 
![Screenshot 2024-07-09 at 19 16 35](https://github.com/pocketbase/pocketbase/assets/10789851/b866d42e-2956-44de-b265-0a58004ad3c4)

Is that supposed to happen? My thought was pocketbase has high concurrency? or is it high concurrency with different users?

![Screenshot 2024-07-09 at 19 12 03](https://github.com/pocketbase/pocketbase/assets/10789851/87c800e2-f639-44d1-b62a-d9e78459d507)

### Recreate the issue
1. Create a test collection
![Screenshot 2024-07-09 at 19 13 29](https://github.com/pocketbase/pocketbase/assets/10789851/e974c534-385a-4859-9c0b-f746598357ef)
2. Logg in as admin
3. Create two new dataset with this example code

const createTwoTest = [1, 2].map(async (i) => {
      return adminPb.collection('test').create({
        field1: `test ${i}`,
      })
    })
 await Promise.all(createTwoTest)

![Screenshot 2024-07-09 at 19 16 35](https://github.com/pocketbase/pocketbase/assets/10789851/a09e3e97-9721-4d8f-a9b2-a68db0e3eabc)
4. Get error that one request is aborted
![Screenshot 2024-07-09 at 19 12 03](https://github.com/pocketbase/pocketbase/assets/10789851/9d3ca654-3eb6-497a-93bd-13d179097faf)

**Comment by ganigeorgiev** [comment]
_Please don't post code as screenshots._

For the abort error see https://github.com/pocketbase/js-sdk?tab=readme-ov-file#auto-cancellation.

If you are using the JS SDK as admin, the auto cancellation usually should be disabled for this case as shown in the example in https://github.com/pocketbase/pocketbase/discussions/3792#discussioncomment-7621130.
