### ISSUE TITLE
Change the html sucess page from the google provider

### ISSUE THREAD

**Issue by WendelLuanEC** [pocketbase/pocketbase#5197]
I'm using authentication with the Google provider in my app, and I'd like to know if it's possible to change the html of the redirection page, here's a screenshot of the page I want to change
![Imagem do WhatsApp de 2024-07-09 à(s) 09 36 38_8274906a](https://github.com/pocketbase/pocketbase/assets/109864257/9cc09193-d366-4ed3-ac18-855005d841f1)

**Comment by ganigeorgiev** [comment]
It is not possible at the moment. If you want to provide your own redirect handler you can implement the "Manual code exchange" flow (_the second tab in the [OAuth2 integration example](https://pocketbase.io/docs/authentication/#oauth2-integration)_).

If you have other questions, please use the discussions instead as the threaded format is more suitable for this type of posts.

**Comment by ganigeorgiev** [comment]
I'm sorry but if you are going to post the same thing multiple places then this is just spam. Please move on.
