### ISSUE TITLE
listen tcp: lookup localhost on 45.90.28.20:53: no such host

### ISSUE THREAD

**Issue by abhijitnandy** [pocketbase/pocketbase#52]
On running `.\pocketbase.exe server`, I get the following error and the program terminates

```
2022/07/10 13:38:36 listen tcp: lookup localhost on 45.90.28.20:53: no such host
```

I'm running it on Windows 10 Pro.

**Comment by ganigeorgiev** [comment]
This is probably due to some missing default local network configurations (another user already reported this in https://github.com/pocketbase/pocketbase/issues/6#issuecomment-1179123311).

You could try starting the application with `127.0.0.1` instead of the default `localhost`, eg.:
```sh
pocketbase.exe serve --http="127.0.0.1:8090"
```

**Comment by abhijitnandy** [comment]
> This is probably due to some missing default local network configurations (another user already reported this in [#6 (comment)](https://github.com/pocketbase/pocketbase/issues/6#issuecomment-1179123311)).
> 
> You could try starting the application with `127.0.0.1` instead of the default `localhost`, eg.:
> 
> ```shell
> pocketbase.exe serve --http="127.0.0.1:8090"
> ```

Thank you. That worked!
