### ISSUE TITLE
Feature request: add token verification endpoint

### ISSUE THREAD

**Issue by nexus9111** [pocketbase/pocketbase#5200]
## Description:

I would like to request the addition of a token verification endpoint in PocketBase. This feature would be extremely beneficial for those of us who wish to use PocketBase behind our own API to manage our users.

## Use Case:

In my specific use case, I need to implement an auth guard middleware to ensure the security and validity of user tokens. By having an endpoint that allows us to verify the validity of tokens, it would greatly simplify the process of authenticating users and integrating PocketBase into our existing infrastructure. I can actually do it with Auth refresh enpoint but it would be nice to have a Auth verification enpoint

```js
const verifyToken = async (token) => {
    const pb = new PocketBase(/* ... */);
    pb.authStore.save(token, null);
    await pb.collection('users').authRefresh();
    return pb;
}
```

## Benefits:

- Enhanced security: Verifying tokens ensures that only valid tokens are accepted, thereby enhancing the overall security of the application.
- Improved integration: This feature would facilitate easier integration of PocketBase with custom APIs and middleware.
Simplified development: Having a built-in endpoint for token verification would reduce the need for custom implementations, thereby saving development time and effort.
- Thank you for considering this feature request. I believe it would be a valuable addition to PocketBase and would greatly enhance its functionality and versatility.

**Comment by ganigeorgiev** [comment]
There are no plans for this. See also https://github.com/pocketbase/pocketbase/issues/2997.
