### ISSUE TITLE
Are FindRecordById, FindFirstRecordByData, FindRecordsByIds safe to use without binds?

### ISSUE THREAD

**Issue by LittleRobertTables** [pocketbase/pocketbase#5214]
When calling filter in `FindFirstRecordByFilter`, `FindRecordsByFilter`, or `FindRecordsByExpr` with user-provided parameters, we need to [bind variables](https://pocketbase.io/docs/go-database/#binding-parameters) to avoid SQL-injection attacks. Are the other three "find" functions safe to use with user-provided data? 

For example, does the following code snippet pose a security risk?
```golang
app.OnRecordBeforeCreateRequest("invite").Add(func(e *core.RecordCreateEvent) error {
      email := e.Record.Email()
      
      user_record, err := app.Dao().FindFirstRecordByData("users", "email", email)
      if err != nil {
            return err
      }

      //...
      return nil
})
```

**Comment by ganigeorgiev** [comment]
The above code is fine, there is no need for escaping because internally the `email` argument is added as bind parameters (this is valid for all other similar methods).

If you have other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead.
