### ISSUE TITLE
Feature request: FULL TEXT search using SQLite FTS5 Extension

### ISSUE THREAD

**Issue by raulcarlomagno** [pocketbase/pocketbase#5225]
as pocketbase is highly coupled to SQLite, it opens the possibility to have plain text fields indexed for fulltext search
this will speed up text searching 
maybe is not easy to implement because a new table (virtual) must be synced with the base table

**Comment by ganigeorgiev** [comment]
Please see https://github.com/pocketbase/pocketbase/issues/193.
