### ISSUE TITLE
Upload large (10gb) files

### ISSUE THREAD

**Issue by eugeis** [pocketbase/pocketbase#5231]
Hello,
I want to use Pocketbase and be able to upload large (10gb) files and access them in the backend at file system, but the field type 'file' has a limit for file size. 

How I can change the limit of the file size?

Thanks,
 Eugen

**Comment by ganigeorgiev** [comment]
You can change the default "Max bytes size" limit from the `file` field options:

![file_field_options](https://i.imgur.com/Nl1JOO2.png)

Keep in mind that I haven't tested PocketBase with serving large files (eg. 1GB+) and I'm not sure if it would be the most performant and efficient way to do it especially if you are transferring the files over an S3 APIs and not the local filesystem.

In any case, if you have other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead as the threaded format is more suitable for this type of posts.
