### ISSUE TITLE
Pagination skipTotal parameter not working as intended

### ISSUE THREAD

**Issue by amandoee** [pocketbase/pocketbase#5251]
Hi, i am in the midst of implementing pagination on my application. I am using Flutter.

I have the understanding that the `skipTotal` parameter can be set to false to get all results between page 1 and the intended page number when trying to getList of collection like in this example:

`pb.collection('Event').getList(
          page: pagefrom1to,
          skipTotal: false,
          perPage: 1,
          filter: '$filterString',
          expand:'club,club.ClubEducation_via_club.education,club.ClubDescription_via_club.language,club.ClubDescription_via_club.name,EventDescription_via_Event.language,ClubEducation_via_club.education,UserEvent_via_event,EventTags_via_event.eventTag',
          sort: '+startDate',          
        );`

However, when i set parameter `perPage: 1` i get only 1 single record, regardless of whatever value i assign to `pagefrom1to`. I have tried values 1,2,3 and 4 for the `pagefrom1to` variable, while keeping `perPage: 1` . I get different records back when changing `pagefrom1to`, corresponding to the order of `startDate`. It seems that skipTotal is not working in the way i thought it was intended.

Is the way to go about this to manually loop and append to a List then? Thanks in advance.

**Comment by ganigeorgiev** [comment]
It is working as [documented](https://pocketbase.io/docs/api-records/#listsearch-records) (if it wasn't working the Admin UI wouldn't return any results).

`perPage` is the number of items to return in a single page (aka. limit).
`page` controls the page of the results (offset).

> Is the way to go about this to manually loop and append to a List then? 

I don't understand what do you mean by this.
