### ISSUE TITLE
getFullList doesn't list anything

### ISSUE THREAD

**Issue by aejenk** [pocketbase/pocketbase#5253]
This issue is confusing me... so I have a table `videos` that has multiple entries in it. The following are two logs - one showing a request from the Node SDK and the other being a request I made through my browser.
![image](https://github.com/user-attachments/assets/3d670752-1789-4d40-8a00-64fd05892d5f)
These requests are identical in every way apart from user agent - but for some reason the SDK one just doesn't return anything. I've tried multiple ways of calling as well.

```ts
const videos = await pb.collection(`videos`).getFullList()
const videos = await pb.collection(`videos`).getFullList({})
const videos = await pb.collection(`videos`).getFullList<Video>()
const videos = await pb.collection(`videos`).getFullList<Video>({})
const videos = await pb.collection(`videos`).getFullList<Video>(undefined)
const videos = await pb.collection(`videos`).getFullList<Video>({
            "requestKey": null,
        });
const videos = await pb.collection(`videos`).getFullList<Video>({
            "requestKey": null,
            "$autoCancel": false,
        });
const videos = await pb.collection(`videos`).getFullList<Video>(undefined, {
            // "sort": "-created",
            "requestKey": null,
            "$autoCancel": false,
            "filter": ``,
        });
```
I'm not seeing any errors too - and when I try to get a single video by ID, it ends up working. Not sure why this is happening - or how to debug it exactly. Been trying for a while.

I was using an old version - but I upgraded both the SDK ("pocketbase": "^0.21.3") and Pocketbase (v0.22.18) to latest and the issue still stands... any ideas/help?

**Comment by ganigeorgiev** [comment]
Make sure that your client request satisfies the List API rule of your collection.

As mentioned in the [API rules note](https://pocketbase.io/docs/api-rules-and-filters/#api-rules):

> PocketBase API Rules act also as records filter!
> ...
> Because of the above, **the API will return 200 empty items response in case a request doesn't satisfy a listRule,** 400 for unsatisfied createRule and 404 for unsatisfied viewRule, updateRule and deleteRule.
All rules will return 403 in case they were "locked" (aka. admin only) and the request client is not an admin.

If you have other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead.

**Comment by aejenk** [comment]
wait this doesn't answer my question at all -- the GUEST request is what returns all the data, and the AUTHENTICATED request returns nothing

**Comment by ganigeorgiev** [comment]
@aejenk Again, the list response would depend on your API rules. Without details about your collection or steps to reproduce there is nothing really much I can help with.

If you need further assistance, please open a Q&A discussion elaborating more on your use case a sample code how do you send the request and export of your collections configuration (Admin UI > Settings > Export collections).

**Comment by ganigeorgiev** [comment]
I've just tested against the live demo (pocketbase.io) and works correctly for me.

With curl:
```
# should return all messages
curl -X GET https://pocketbase.io/api/collections/messages/records \
  -H 'authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJQT1dNT2gwVzZJb0xVQUkiLCJleHAiOjE3MjMxMTg2NjIsImlkIjoicUVvb0JUSG9BR2tXVUtjIiwidHlwZSI6ImF1dGhSZWNvcmQifQ.KzQ_8C6qnV-IqXcGAZ_sJRI11PcmcuVqJUvjlx14Y4Q'

# should return empty array
curl -X GET https://pocketbase.io/api/collections/messages/records
```

With the JS SDK (`pb_public/index.html`):

```js
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.es.mjs"

        const pb = new PocketBase("https://pocketbase.io");

        pb.authStore.clear(); // reset any previously localStorage auth state

        // commenting the auth show result in empty messages
        await pb.collection("users").authWithPassword("test2@example.com", "1234567890");

        const records = await pb.collection("messages").getFullList()

        console.log(records);
    </script>
</body>
</html>
```

If you want to reverse the behavior (aka. only guest to have access) change the API rule to `@request.auth.id = ""`.

Again, without information about your API rules or at least some steps to reproduce there is nothing much I or anyone else could assist your. Make sure that:

- your API rules are correct
- there is no cache involved either by a reverse proxy or frontend framework (e.g. Next.js)

**Comment by aejenk** [comment]
Apologies - I got a bit exasperated by this issue, it's frustrating. I understand it's likely not an issue with Pocketbase - I'm mostly trying to find out what the bug is here - and since it's not authentication and also inconsistent (the same call on a _specific_ table works - a similar call filtering by ID works)

I ran a more extensive test here where I tried to make different kinds of request to the table:
```ts
        const videos = await pb.collection(`videos`).getFullList<Video>(undefined, {
            "$autoCancel": false,
        });
```
That one returned nothing.
```ts
        const videos2 = await pb.collection(`videos`).getFullList<Video>(undefined, {
            filter: `link ~ "jS0XMludWaE"`,
            "$autoCancel": false,
        });
```
This one, however, returned a single result - which matches what I expected.
```ts
        const videos3 = await pb.collection(`videos`).getFullList<Video>(undefined, {
            filter: `link ~ "youtube"`,
            "$autoCancel": false,
        });
```
This one, coming after, returns nothing as well. Even though when I run that filter via the UI, it returns all entries - it's meant to be a redundant filter.

Do you know what could be happening here, because I'm at a loss and I feel as if I am using this client incorrectly.
The filters on this table are a LIST/VIEW/CREATE rule of `@request.auth.id = "<static ID>"` - which if it's wrong should either return no results in all cases, or all results in all cases. 

I can try offering more info, but I'm not sure how much is needed to understand the full context.

**Comment by aejenk** [comment]
did 2 more tests:
```
        const videos3 = await pb.collection(`videos`).getFullList<Video>(undefined, {
            filter: `link ~ "jS"`,
            "$autoCancel": false,
        });
```
This one opens up the filter in the second example, and returns 5 entries - as expected.
```
        const videos3 = await pb.collection(`videos`).getFullList<Video>(undefined, {
            filter: `link ~ "j"`,
            "$autoCancel": false,
        });
```
This one opens up the filter even further, and returns 0 entries. I'm wondering if there's something wiping the result if it's too big...

**Comment by ganigeorgiev** [comment]
You refuse to provide details about your collections structure and how do you even initialize the SDK so that I can try to reproduce your problem locally and assist you.

In any case the call is using a legacy/deprecated format:

```js
const videos3 = await pb.collection(`videos`).getFullList<Video>(undefined, {
    filter: `link ~ "youtube"`,
    "$autoCancel": false,
});
```

It should be:

```js
const videos3 = await pb.collection(`videos`).getFullList<Video>({
    filter: `link ~ "youtube"`,
    requestKey: null,
});
```

If you think that there is a PocketBase issue, try to create a minimal reproducible repo and I'll have a look at it but until then you are just wasting your time (and mine).

**Comment by aejenk** [comment]
Apologies - I'll get right on that.

**Comment by aejenk** [comment]
I managed to fix it. For other people, the solution was to basically upgrade Node. I was using 18.12.1 -- and for some reason the SDK only fails silently and in some cases. Upgrading to the latest version fixed all issues - I probably missed a notice everywhere that said I needed an upgrade to Node.
