### ISSUE TITLE
Feature Request: Enable Pocketbase to Act as an OAuth Provider

### ISSUE THREAD

**Issue by dahjson** [pocketbase/pocketbase#5256]
The feature aims to enhance Pocketbase by providing OAuth capabilities, enabling Pocketbase applications to act as OAuth providers. This would allow third-party applications to securely access resources in a Pocketbase app through a standardized authentication and authorization protocol.

**Comment by ganigeorgiev** [comment]
This was requested before (ex. https://github.com/pocketbase/pocketbase/issues/3567), but at least for v1 it remains out of the scope (_external experimentation as server-side ["plugin" package](https://github.com/pocketbase/pocketbase/tree/master/plugins) are welcomed_).
