### ISSUE TITLE
Create admin in cli doesn't work properly

### ISSUE THREAD

**Issue by nexus9111** [pocketbase/pocketbase#5260]
Hi, first of all, I love pocketbase ❤️, but ...

I'm using a dockerized version of Pocketbase, and I would like to automate the creation of the first administrator, here is my dockerfile (it's based on [this one](https://github.com/muchobien/pocketbase-docker)):

**Dockerfile.pocketbase**
```
FROM alpine:3 as downloader

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG VERSION
ARG POCKETBASE_ADMIN_EMAIL
ARG POCKETBASE_ADMIN_PASSWORD

ENV BUILDX_ARCH="${TARGETOS:-linux}_${TARGETARCH:-amd64}${TARGETVARIANT}"

RUN wget https://github.com/pocketbase/pocketbase/releases/download/v${VERSION}/pocketbase_${VERSION}_${BUILDX_ARCH}.zip \
    && unzip pocketbase_${VERSION}_${BUILDX_ARCH}.zip \
    && chmod +x /pocketbase

FROM alpine:3
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

EXPOSE 8090

COPY --from=downloader /pocketbase /usr/local/bin/pocketbase

COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
```

**And here is the entrypoint:**
```bash
#!/bin/sh

/usr/local/bin/pocketbase migrate up
/usr/local/bin/pocketbase admin create $POCKETBASE_ADMIN_EMAIL $POCKETBASE_ADMIN_PASSWORD
/usr/local/bin/pocketbase serve --http=0.0.0.0:8090 --dir=/pb_data --publicDir=/pb_public --hooksDir=/pb_hooks
```

**Here are the container logs:**
```
2024-07-27 14:02:10 Applied 1640988000_init.go
[...]
2024-07-27 14:02:10 Applied 1718706525_add_login_alert_column.go
2024-07-27 14:02:10 Successfully created new admin foo@bar.com
2024-07-27 14:02:10 2024/07/27 12:02:10 Server started at http://0.0.0.0:8090
2024-07-27 14:02:10 ├─ REST API: http://0.0.0.0:8090/api/
2024-07-27 14:02:10 └─ Admin UI: http://0.0.0.0:8090/_/
```

---

I can access pocketbase at `http://0.0.0.0:8090/_/`, but it ask to create first user (but we saw in logs that it already created one. So I create a new one, and in admin list, the one created in the entrypoint doesn't exist.

I then connect to the container and type:

```console
~# /usr/local/bin/pocketbase admin create foo@bar.com SuperSecur3P@ssword
Error: Failed to create new admin account: constraint failed: UNIQUE constraint failed: _admins.email (2067)
```

I don't understand why it says that it exists, but can login with it, and don't see it in the admin list

Thank you ❤️

**Comment by ganigeorgiev** [comment]
It fails because you are trying to create every time a new admin account with the same email address when the container starts.

Additionally, you don't have to call `migrate up` as this it will be automatically invoked by the `serve` command.

The recommend approach for creating an admin account programmatically is usually as part of a migration because it will execute only once. For an example see https://pocketbase.io/docs/js-migrations/#creating-new-admin.

If you have other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead.

**Comment by ganigeorgiev** [comment]
Also note that the same flags `--dir`, `--publicDir` `--hooksDir` should be specified for all `/usr/local/bin/pocketbase` calls (this would explain why you may not be able to create the "see" the created admin because it will be created in a different `pb_data` directory).
