### ISSUE TITLE
Feature Request - Add additional notification backends

### ISSUE THREAD

**Issue by mikekuzak** [pocketbase/pocketbase#5269]
Hi,

Maybe additional notification backend plugins could be added ? 
Like ntfy.sh should be easy to add, as it can work directly with curl. 

Thanks

**Comment by ganigeorgiev** [comment]
It is not clear what actually you are asking but there are no plans for 3rd party integrations out of the box.

Users can implement it on their own when using [PocketBase as framework](https://pocketbase.io/docs/use-as-framework/).
