### ISSUE TITLE
RecordUpsertForm.submit() hanging when creating user record

### ISSUE THREAD

**Issue by mdnahas** [pocketbase/pocketbase#5278]
I love PocketBase!  Thanks for all your work on it.

I'm trying to create a user record in a server hook.  The submit() call hangs.

As you'll see below, I tried calling validate(), validateAndFill(), and drySubmit() and those all worked fine.  But submit() hangs.  (It also hangs without those calls.)

Partial source code:
```
            ...
            // User will set their own password when they click the link in the email.
            const alphanumeric = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
            const unguessablePassword = $security.pseudorandomStringWithAlphabet(20, alphanumeric)

            const record = new Record(userCollection)
            const form = new RecordUpsertForm($app, record)
            
            const formData = {
                // "id" not set until it is saved.
                // "username": generated by Pocketbase
                "password": unguessablePassword,
                "passwordConfirm": unguessablePassword,
                "email": email,
                "emailVisibility": true,
                "verified": false,
                "firstName": firstName,
                "lastName": lastName,
                "cell": cell,
                // "segment":
                "permissionsIsUES": false,
                // "permissionsConference": TODO: How to set to empty?
                // "permissionsHotel": TODO: How to set to empty?
            }

            console.log("User data: " + JSON.stringify(formData))  // TODO: Don't log passwords!!!!
            form.loadData(formData)
            console.log("loadData done")
            form.validate()
            console.log("validate done")
            form.validateAndFill()
            console.log("validateAndFill done")
            form.drySubmit
            console.log("drySubmit done")

            form.submit()  // validate + saveRecord
            console.log("submit done")

```
            ...
Output from "./pocketbase serve --debug --indexFallback=0"

> 2024/07/30 10:37:56 User data: {"password":"cj6O61iqHD26DU758LR2","passwordConfirm":"cj6O61iqHD26DU758LR2","email":"j@m.com","emailVisibility":true,"verified":false,"firstName":"Jack","lastName":"Miller","cell":"+566","permissionsIsUES":false}
> 2024/07/30 10:37:56 loadData done
> [0.00ms] SELECT {{_collections}}.* FROM `_collections` WHERE [[id]] = 'user_coll_id' OR LOWER([[name]])='user_coll_id' LIMIT 1
> [0.00ms] SELECT count(*) FROM `User` WHERE `email`='j@m.com' LIMIT 1
> 2024/07/30 10:37:56 validate done
> [0.00ms] SELECT {{_collections}}.* FROM `_collections` WHERE [[id]] = 'user_coll_id' OR LOWER([[name]])='user_coll_id' LIMIT 1
> [0.00ms] SELECT count(*) FROM `User` WHERE `email`='j@m.com' LIMIT 1
> [0.00ms] SELECT {{_collections}}.* FROM `_collections` WHERE [[id]] = 'user_coll_id' OR LOWER([[name]])='user_coll_id' LIMIT 1
> [0.00ms] SELECT count(*) FROM `User` WHERE LOWER([[username]])='user34851' LIMIT 1
> 2024/07/30 10:37:57 validateAndFill done
> 2024/07/30 10:37:57 drySubmit done
> [0.00ms] SELECT {{_collections}}.* FROM `_collections` WHERE [[id]] = 'user_coll_id' OR LOWER([[name]])='user_coll_id' LIMIT 1
> [0.00ms] SELECT count(*) FROM `User` WHERE LOWER([[username]])='user34851' LIMIT 1
> [0.00ms] SELECT {{_collections}}.* FROM `_collections` WHERE [[id]] = 'user_coll_id' OR LOWER([[name]])='user_coll_id' LIMIT 1
> [0.00ms] SELECT count(*) FROM `User` WHERE `email`='j@m.com' LIMIT 1
> [0.00ms] SELECT {{_collections}}.* FROM `_collections` WHERE `type`='auth' ORDER BY `created` ASC
> 

It hung there.   After I hit Control-C, the following was printed:

> ^C[101707.00ms] INSERT INTO `User` (`cell`, `created`, `email`, `emailVisibility`, `firstName`, `id`, `lastName`, `lastResetSentAt`, `lastVerificationSentAt`, `passwordHash`, `permissionsConference`, `permissionsHotel`, `permissionsIsUES`, `segment`, `tokenKey`, `updated`, `username`, `verified`) VALUES ('+566', '2024-07-30 15:37:57.486Z', 'j@m.com', true, 'Jack', 'jj416yv9yz4k18n', 'Miller', '', '', '$2a$12$rxMU9j7spfeCDWOKhdiVp.bUUSzw4yo9YZZwmgOccg9eeDd/t/IKS', '[]', '[]', false, '', 'lcI77vvxSXCANhUoMhGFuutkIzQv0IaoiXXsg8bOtlanxlBgG3', '2024-07-30 15:37:57.486Z', 'User34851', false)
> 2024/07/30 10:39:39 Error saving brand new record: sql: database is closed
> 2024/07/30 10:39:39 Log save failed: sql: database is closed

**Comment by ganigeorgiev** [comment]
I don't think this is a PocketBase issue, or at least I don't know how to reproduce it (the for is also used internally by the default update API request and there are automated tests that verify that it works correctly).

If you are running the above inside of a transaction, then you need to change the form Dao with that of the transaction, aka. `form.setDao(txDao)`, see https://github.com/pocketbase/pocketbase/discussions/5265.

In any case, if you still think that this is a PocketBase issue, please provide a **minimal** reproducible example or at least a more complete code sample with details about your collections configuration (Admin UI > Settings > Export collections).

**Comment by ganigeorgiev** [comment]
_As a side-note: for passwords (or any other security related context) prefer using `$security.randomStringWithAlphabet` instead of `$security.pseudorandomStringWithAlphabet`._

**Comment by mdnahas** [comment]
form.setDao(txDao) fixed it.  Thanks!

Good side-note!

I'll try to submit a better formatted issue in the future.  (I'm shocked at how few issues I have run into.  I'm impressed!)
