### ISSUE TITLE
Feature Request: Access user fields on email templates

### ISSUE THREAD

**Issue by AlejandroAkbal** [pocketbase/pocketbase#5280]
Would love to have access to user.name or user.username here
![image](https://github.com/user-attachments/assets/bd05a1ac-3068-4789-bb1e-cec56519172f)

**Comment by pepilipep** [comment]
@ganigeorgiev I would like to work on this. I am fine with discussing implementation details beforehand

**Comment by ganigeorgiev** [comment]
@pepilipep If you have suggestions how do you plan to implement it feel free to outline them but for now this remains out of the roadmap and it is left for later consideration (see also https://github.com/pocketbase/pocketbase/discussions/4355).

The mail templates handling in general will have to change in the future in some way as I currently don't exactly like how we have to maintain the mail templates in 2 different places (the system templates in the UI and the custom user defined as code, for example https://github.com/presentator/presentator/tree/master/templates).

**Comment by pepilipep** [comment]
@ganigeorgiev I see, sorry I hadn't noticed the discussion.
Please let me know if there is some work on the roadmap that is available for picking up by me.

**Comment by ganigeorgiev** [comment]
This is implemented as part of the ongoing refactoring. Users will be able to access stringified version of any non-hidden record field via the `{RECORD:*}` placeholders (e.g. `{RECORD:firstName} {RECORD:lastName}`).

**Comment by AlejandroAkbal** [comment]
Yup, its finally in, thank you <3
