### ISSUE TITLE
Feature Request: Hot reload on any additional files updated.

### ISSUE THREAD

**Issue by elmurphy** [pocketbase/pocketbase#5295]
I was playing with pocketbase, I like it. It's simple and useful. But I just got triggered. When *.pb.js files updated, it just send me a warning, "test.pb.js changed, please restart the app". Might be hot reload help us to speed up a little bit.

**Comment by ganigeorgiev** [comment]
This message is only for Windows. On Linux and other platforms that supports `execve` the application should restart automatically on `pb_hooks` file change.

Suggestions for `execve` alternatives are welcomed but for now I'm not planning working on a workaround for Windows.

**Comment by elmurphy** [comment]
Yep, I'm just seeing what's going on behind the scenes. I'm just using WSL for now, but I might be able to help with this issue in the future.
