### ISSUE TITLE
Delete records' select entries matching deleted select options

### ISSUE THREAD

**Issue by sean078** [pocketbase/pocketbase#5296]
If you

1. Create a collection with a select field that has options **a**, **b**, **c**
2. Create a record with **a**, **b**, **c**
3. Delete the option **c** from the collection (not the record)
4. The record will still show having all three old options selected

Could we have the deleted options removed from records that have selected them? Or provide this as an option when saving changes that delete a used option. Or alert the admin that the changes cannot be saved until **c** is manually removed from all records.

**Comment by ganigeorgiev** [comment]
This is expected and it is done to avoid accidental data loss. The same for example could happen if you change the `maxSelect` option from 3 to 2. The validator is applied only if the record is resaved.

You can create a migration (with [Go](https://pocketbase.io/docs/go-migrations/) or [JS](https://pocketbase.io/docs/js-migrations/)) to adjust the old data if necessary.

For now I'm not planning adding an option for this but I'll revisit it with the refactoring (or at least add a popup to warn user that they may have to normalize the old records manually).
