### ISSUE TITLE
Feature Request: Bulk download

### ISSUE THREAD

**Issue by DeluxeOwl** [pocketbase/pocketbase#5299]
Currently, you can only download documents individually. It would be nice to implement a bulk download feature that allows us to:

1. Provide an array of multiple documents
2. Initiate a bulk download
3. Receive a compressed file (e.g., ZIP) containing all selected documents

This feature would save time for users who need to download multiple documents at once and reduce the number of individual download operations.

Benefits:
- Improved user experience
- Time-saving for users who frequently download multiple documents
- Reduced server load by minimizing the number of individual download requests

**Comment by ganigeorgiev** [comment]
At least for v1 there are no plans to do this out of the box as it would complicate too much the existing file APIs (especially around the protected checks).

It could also cause performance issues for large (or many small) files that needs to be compressed.

The retention of the generated zip is also something that will have to be considered.

I may revisit it in the future if a more prominent use case arise, but for now if there is need it for it users can implement it on their own by registering a custom route (it could be also implemented as a "plugin" package in similar manner to https://github.com/pocketbase/pocketbase/tree/master/plugins).
