### ISSUE TITLE
Duplciate field names allowed in pb_migrations file

### ISSUE THREAD

**Issue by mdnahas** [pocketbase/pocketbase#5301]
I was able to create two fields with the same name in a Collection, using a file in the pb_migrations/ directory.
GUI showed two fields with same name, but acted like records only held one value.

This seems like something that should not be allowed.  

pocketbase version 0.19.3
Ubuntu 20.04.6 LTS

File:
```
/// <reference path="../../pb/pb_data/types.d.ts" />
migrate((db) => {
    const snapshot = [
        {
            "id":      "dummy_coll_id",
            "name":       "Dummy",
            "type":       "base",

            "listRule":   "",
            "viewRule":   "",
            "createRule": "",
            "updateRule": "",
            "deleteRule": "",
    
            "schema":     [
                {
                    "name": "d",
                    "type": "relation",
                    "required": false,
                    "options": {
                        "collectionId": "dummy_coll_id",
                        "cascadeDelete": false,
                        "minSelect": 1,
                        "maxSelect": 1,
                    }
                },
                {
                    "name": "d",
                    "type": "relation",
                    "required": false,
                    "options": {
                        "collectionId": "dummy_coll_id",
                        "cascadeDelete": false,
                        "minSelect": 1,
                        "maxSelect": 1,
                    }
                },
            ],
    
            "indexes": [
            ],
            "options": {}
        }
    ];
    const collections = snapshot.map((item) => new Collection(item));
    const delete_others = false
    return Dao(db).importCollections(collections, delete_others, null);
  }, (db) => {
    return null;
  })

```

Log message:
[0.00ms] CREATE TABLE `Dummy` (`created` TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL, `d` TEXT DEFAULT '' NOT NULL, `id` TEXT PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL, `updated` TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL)

**Comment by ganigeorgiev** [comment]
As mentioned in the [jsdoc of the method](https://pocketbase.io/jsvm/classes/Dao.html#importCollections) `Dao.importCollections` (or any other Dao method) doesn't perform validations on the persisted data.

This behavior has already changed with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and the form models are no longer necessary (there are no ETAs yet).

**Comment by ganigeorgiev** [comment]
_Side-note: I recommend upgrading to the latest PocketBase [v0.22.8 release](https://github.com/pocketbase/pocketbase/releases) as it comes with new logger, several bug fixes and performance improvements._

_You can check the [CHANGELOG](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md) to compare the changes from v0.19. Changes marked with "⚠️" are usually breaking or need special attention._
