### ISSUE TITLE
Proposal: add id, created, updated to RecordModel.data in Dart SDK

### ISSUE THREAD

**Issue by lukepighetti** [pocketbase/pocketbase#5303]
Currently you cannot access the id, created, or updated from the data field of RecordModel. This may seem reasonable since the Record is gauranteed to have these fields and thus have been given explicitly defined properties. However, in normal use it can be cumbersome to deal with.

```dart
    /// how it works today
    final x = await _pb.collection("users").create(body: {
      "username": anonUsername,
      "password": anonPassword,
      "passwordConfirm": anonPassword,
    });
    return PbUserModelMapper.fromMap({"id": x.id, "created": x.created, "updated": x.updated, ...x.data});
```

ideally we'd be able to do the following:

```dart
    final x = await _pb.collection("users").create(body: {
      "username": anonUsername,
      "password": anonPassword,
      "passwordConfirm": anonPassword,
    });
    return PbUserModelMapper.fromMap(x.data);
```

the shim i've been using is the following

```dart
extension on RecordModel {
  Map<String, dynamic> get row => {
        "id": id,
        "created": created,
        "updated": updated,
        ...data,
      };
}
```

**Comment by ganigeorgiev** [comment]
You can call the `toJson()` method and it should return the same map.

In any case, with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and the upcoming v0.23 release (there are no ETAs yet) the `id` (and other system) fields are now part part of the collections schema, aka. they will be accessible from the `data` map.

**Comment by lukepighetti** [comment]
AHHH thank you
