### ISSUE TITLE
Access sql.Conn

### ISSUE THREAD

**Issue by tgrosinger** [pocketbase/pocketbase#5315]
Is there any way I can access the underlying `sql.Conn` used by PocketBase. I am doing to do like [discussed here](https://github.com/pocketbase/pocketbase/discussions/4984) and use sqlc with PocketBase. Thank you.

**Comment by ganigeorgiev** [comment]
You should be able to access the underlying `sql.DB` from the value behind the `dbx.Builder` interface. Something like:

```go
dbxDB, _ := app.Dao().DB().(*dbx.DB) // inside transactions this could be *dbx.Tx
sqlDB := dbxDB.DB() // *sql.DB
sqlDB.Conn(ctx)
```

But in any case my recommendation from https://github.com/pocketbase/pocketbase/discussions/4984#discussioncomment-9554935 remains.

Note that the collections create/update APIs has changed significantly with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and it should be a lot more easier to manage collections programmatically if that is the reason behind sqlc in the first place.

_If you have other questions, please use the ["Q&A Discussions"](https://github.com/pocketbase/pocketbase/discussions) as the threaded format is more suitable for this type of posts._
