### ISSUE TITLE
Feature Request: Automatic saving of shema json when using go framework

### ISSUE THREAD

**Issue by thezachdrake** [pocketbase/pocketbase#5328]
When being used as a framework, most of us will have a local development version that is then built and deployed to our production environment. Obviously we wouldn't want to be pushing a copy of production data back and forth so it is expected that the local development environment is going to have dummy data. 

Right now if a new table is made locally (or even a new column or permissions rule) the best way to move that to the production environment is to save the schema json from the ui deploy that json to the prod server with the code, then in prod import that schema json. It would be beneficial for this to just be the default behavior (or one that can be set to happen) when using the framework. Something like: every time a table, column, or rule is made in the ui a new copy of the schema json is written out. Equally on startup, the app checks for a schema json in the root folder of the app and if one exists it is applied. Mimicking the behavior of when it is uploaded. 

In reality this can probably be done now with functions added to the main.go but the documentation does not describe any way to interact with the functionality that uploads and outputs the schema json. This would also allow us to edit the schema as code by making changes to the schema json in a repo and then building the application from Go.

**Comment by ganigeorgiev** [comment]
We have migrations for this (including automigrate to generate it automatically on change).

Please check https://pocketbase.io/docs/go-migrations/.
