### ISSUE TITLE
File uploading in React-Native doesn't work

### ISSUE THREAD

**Issue by KingiDE** [pocketbase/pocketbase#5342]
## Simple description
I have a piece of code inside my React-Native app (+ Expo) that uploads (at least thats the goal) a previously selected image from the local filesystem to PocketBase. This allows an existing user to update its profile picture. On PocketBase's side everything seems fine - no error gets thrown but the image field inside that record never updates. 

## Code Snippet
```js
// State (simplified)
const [profile, setProfile] = useState<{
  image: {
    valid: null | string;
    displayed: null | string;
  };
}>({
  // Image uri
  image: {
    valid: null,
    displayed: null,
  },
});

// Select image function 
onPress={async () => {
  let result = await ImagePicker.launchImageLibraryAsync({
    mediaTypes: ImagePicker.MediaTypeOptions.Images,
    quality: 1,
  });

  if (!result.canceled) {
    setProfile({
      ...profile,
      image: {
        ...profile.image,
        displayed: result.assets[0].uri,
      },
    });
  }
}}

try {
  console.log(profile.image.displayed);
  // Logs: file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Ftemplate-245e3fb3-c8c0-4ea3-8313-0d31d4819eef/ImagePicker/d8cdcd1e-e58b-46b2-b532-2d12cdc54e72.jpeg

  await pb
    .collection('users')
    .update(('<userid>', {
      username: '<username>', // intentionally hidden
      displayname: '<displayname>', // intentionally hidden
      profileinfo: 'test10',
      profileimage: {
        uri: profile.image.displayed, // TODO: Upload file
        type: 'image/jpeg',
        filename: 'd8cdcd1e-e58b-46b2-b532-2d12cdc54e72.jpeg',
     },
    });
} catch (e) {
  console.log('There occured an error');
}

```

## Expected behaviour
The file shows up in the PocketBase-Dashboard.

## Actual behaviour
The rest of the request gets applied (like `profileinfo`) but `profileimage` stays empty.

## Additional info
This is the file's uri (like above): 
![consolelog](https://github.com/user-attachments/assets/0d7fccf0-da30-4df1-8464-5ac939c9dfc7)

This is the dashboard after sending the request. As you can see the other field has been applied but not the profileimage:
![dashboard](https://github.com/user-attachments/assets/5fa01bfd-8211-4df0-bb3c-538b3b9aa3a0)

This is the DB-field. Only `.png`s and `.jpg`s are allowed:
![field](https://github.com/user-attachments/assets/1a0a6b85-aa0a-4c64-9c8c-2acf07195f0a)

This is the request log: Nothing fails (additionally the catch clause doesn't get executed inside the code):
![request](https://github.com/user-attachments/assets/473de06e-06dc-4061-968b-3ac8a8cf1a67)

**Software-Versions:** *(from package.json)*
- expo: "^51.0.24",
- react: "18.2.0",
- react-native: "0.74.5",
- expo-image-picker: "^15.0.7",

## Possible reasons:
1. **Excluded** The file seems to be of type `.jpeg` but only `.jpg`s are allowed. Let's try uploading a `.png` file. This is now the uri: `file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Ftemplate-245e3fb3-c8c0-4ea3-8313-0d31d4819eef/ImagePicker/2e33fc49-a806-4f80-a20c-63c6deb0378a.png` and when I update the `type` and `filename` field correctly it still doesn't work. Also the request doesn't error/fail.

**Comment by ganigeorgiev** [comment]
I don't think this is a PocketBase issue. Please see the comment in https://github.com/pocketbase/pocketbase/discussions/2002#discussioncomment-5254168 (notice that it also depends on what platform you are testing).

If you still think that it is a PocketBase issue, please create minimal runnable https://snack.expo.dev/ example and I'll try to have a look at it.

**Comment by ganigeorgiev** [comment]
Or in other words, you can try with something like:

```js
const data = new FormData();

data.append('username', 'yourUsername');
data.append('displayname', 'yourDisplayname');
data.append('profileinfo', 'yourProfileinfo');

let imageUri = profile.image.displayed;

if (Platform.OS === 'web') {
  const req = await fetch(imageUri);
  const blob = await req.blob();
  data.append('profileimage', blob);
} else {
  // passing an object works only on Android and iOS
  data.append('profileimage', {
    uri: imageUri,
    type: `image/*`, 
    name: imageUri.split('/').pop(),
  });
}

await pb.collection('users').update(('yourUserId', data);
```

**Comment by ganigeorgiev** [comment]
@KingiDE I don't think you are testing on the correct platform or at least I don't understand what do you mean by _"code throws an error in the console"_, but in any case without a minimal runnable expo example I don't think I'll be able to help you further.

The object FormData file syntax is Android/iOS specific and unless something has changed since my last time testing from the linked discussion it should work correctly. If it doesn't provide a minimal reproducible repo and I'll have a look at it.

**Comment by ganigeorgiev** [comment]
Ugh, I've decided to waste some time and create a minimal example. You can find it in https://snack.expo.dev/iLDGuQVkyC7jwrN96wFXN.

I confirm that it works correctly both in Web and Android.

Please note that the issues tracker is not a general dev support forum. If you have other questions consider using the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead as the threaded format is more suitable for this type of posts.
