### ISSUE TITLE
Feature Request: Add optional comment / description field to the collection fields API rules

### ISSUE THREAD

**Issue by OperativeThunny** [pocketbase/pocketbase#5343]
Feature Request: Add comment / description field to the collection fields API rules boxes to document the purpose of the filter setup.

So for example I am making a URL shortener with pocketbase, and I wanted to document that the API rule for update prevents changing the URL from the originally submitted URL, and it would be nice to have a field to document that because the rule I've input is not exactly obvious.

**Comment by ganigeorgiev** [comment]
This was discussed several times before in the past and it [exists in the roadmap](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=instruction&pane=issue&itemId=37392385) but remains a low priority for now.

**Comment by ganigeorgiev** [comment]
> it would be nice to have a field to document that because the rule I've input is not exactly obvious.

Note that you can comments in the API rules using double-slash, e.g. `// example comment`.
