### ISSUE TITLE
Bug: If you create a column named "active" then updates switch it to false or 0 if its a number field

### ISSUE THREAD

**Issue by OperativeThunny** [pocketbase/pocketbase#5344]
Bug: If you create a column named "active" updates switch it to false or 0 if its a number field

Example: I have a URL shortener app and when I was trying to update the click count, the "active" field would change to false no matter what values I set in the javascript on the client side (using the js sdk). I dunno if this is reproducible but once I renamed it to "is_active" things started working as expected. I suspect that this is a hidden field under the hood of pocketbase for the collections, but I didn't dig into it much. Hopefully this is reproducible.

**Comment by ganigeorgiev** [comment]
There is no such hidden field and I'm not able to reproduce it (or to be honest even understand the report).

If you still think that this is a bug, please provide clear reproducible steps or a minimal code sample illustrating the problem.

**Comment by ganigeorgiev** [comment]
If you are using Next.js make sure that what you are experiencing is not caused by its default cache. See also https://github.com/pocketbase/pocketbase/discussions/5313.
