### ISSUE TITLE
Scope doesn't return the data asked from scope on flutter

### ISSUE THREAD

**Issue by CreeperFarm** [pocketbase/pocketbase#5354]
### Discussed in https://github.com/pocketbase/pocketbase/discussions/5279

<div type='discussions-op-text'>

<sup>Originally posted by **CreeperFarm** July 30, 2024</sup>
Hi,
I'm having a huge trouble while I'm trying to get the user's birthday and his gender with google.
So I use the `.authWithOAuth2()` method with this code : 
```dart
pb.collection('users').authWithOAuth2('google',` (url) async {
        await launchUrl(url);
      },
      scopes: [
        'email',
        'profile',
        'https://www.googleapis.com/auth/user.gender.read',
        'https://www.googleapis.com/auth/user.birthday.read'
      ],
      createData: {
        "role": "user",
        "emailVisibility": true,
      });
```
and what it return is : 
```
{"token":"eyJhbGciOiJ..........45d5KuP0kxY","record":{"id":"jtsqafxtxkrzcho","created":"2024-07-30 18:15:05.283Z","updated":"2024-07-30 18:15:05.283Z","collectionId":"_pb_users_auth_","collectionName":"users","expand":{},"avatar":"","birthday":"","email":"usermail@gmail.com","emailVisibility":true,"gender":"other","role":"user","username":"users44988","verified":true},"meta":{"id":"107543407980256723726","name":"CreeperFarm","username":"","email":"usermail@gmail.com","avatarUrl":"https://lh3.googleusercontent.com/a/ACg8ocKqvZOBNq2nkrc4j_WYSMN_cruqDY0hLvLkAVF2q-RfFjdy8lCB=s96-c","accessToken":"ya29.a0A................sFXzyHIrF<…>
```

So, I don't get the answer of the scope. How can I get it so I can get the users birthday and his gender.

Thanks in advance for your answer and sorry my English is bad.</div>

**Comment by ganigeorgiev** [comment]
Please don't post the same thing multiple places.

In any case, PocketBase has nothing to do with the `scopes` and this is not a PocketBase issue. These scopes are only used to generate the url in `launchUrl` (you can print the launched url and confirm that the scopes are added as space separated list under the `scope` query parameter).

It depends on the OAuth2 provider and its OAuth2 app configuration whether the requested scopes will be returned or not. If there are returned, additional fields are returned under the `meta.rawUser` prop.

More than this I don't know how to help further.
