### ISSUE TITLE
Suggestion: add upload-meter to backups

### ISSUE THREAD

**Issue by bloor** [pocketbase/pocketbase#5355]
![image](https://github.com/user-attachments/assets/c66f621b-8e3a-4bcb-bd40-3a8916a65769)

Love the ease of backup/restore process, but I really need a progress bar for the upload. 
Makes me unease not knowing if the 1GB backup is uploading or crashed.

**Comment by ganigeorgiev** [comment]
I'm closing this as I don't think it is necessary (the Admin UI will be also refactored in the future and I don't see much point of unnecessary complicating it at the moment).
