### ISSUE TITLE
Feature Request: Static and Dynamic Default Attribute Values

### ISSUE THREAD

**Issue by hhhtylerw** [pocketbase/pocketbase#5374]
![image](https://github.com/user-attachments/assets/1932b556-850f-4620-b56e-1d5c6e83c70a)
A way to conveniently set static and dynamic default attribute values would be extremely convenient and help avoid having to directly extend the binary.  

Say you wanted to set a `created_by` attribute in your table. You could simply have a default value of `@request.auth.id`. You could manage direct write access to that attribute by using `@request.data.created_by:isset = false` in your API rules. 

To my understanding, the current way to do this (and disallow the user to put whatever they want for the field) is to create a new route that does this alongside my previously mentioned API rule. I think this is a little obtuse for something as simple/common as a default attribute value.

**Comment by ganigeorgiev** [comment]
There were several discussions about defaults in the past but I'm still against it as it is not clear when and how exactly the default will be applied - only on create, on update with empty value (we don't have null for non-`json` type fields), etc.

Even with the upcoming v0.23.0 and the new "Autogenerate pattern" option that will be available for the `text` field and applied only on missing create value was added more as a workaround to minimize the breaking changes with system fields like the `username`, `tokenKey`, etc. and I'm still not sure whether it was the best option here.

So for now this remains out the roadmap as the rules are not clearly defined but I may reconsider it in the future in case a more prominent use case arise.

**Comment by ganigeorgiev** [comment]
I forgot to answer this.

> To my understanding, the current way to do this (and disallow the user to put whatever they want for the field) is to create a new route that does this alongside my previously mentioned API rule. 

No, since we don't have defaults at the moment users are expected always to submit the desired value, aka. in your case users will have to submit as `created_by` their id manually. To prevent the user using an id of another user you can simply restrict it with a Create API rule such as `@request.data.created_by = @request.auth.id`.

**Comment by hhhtylerw** [comment]
> So for now this remains out the roadmap as the rules are not clearly defined but I may reconsider it in the future in case a more prominent use case arise.

I hope to see it, but I understand it's not a part of the vision for now.

> No, since we don't have defaults at the moment users are expected always to submit the desired value, aka. in your case users will have to submit as `created_by` their id manually. To prevent using an id of another user you can simply restrict it with a Create/Update API rule such as `@request.data.created_by = @request.auth.id`.

Somehow doing it this way never occurred to me, but it seems so obvious now. Thanks for the help.

**Comment by VittorioParagallo** [comment]
i upvote default value in general and i hope it will be reconsidered. I just checked the v0.23 and was hoping to see it, so i fell back to this post. My guess is that default values are on create in general in the other db solution i've never seen on update or at least i never tought about that. so just want to share my feeling that it could be a big benefit to have default values on create to reduce boilerplate.
