### ISSUE TITLE
Idea/Feauture Request: Flat File Mode

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#5379]
I recently found [automad](https://automad.org/). Flat file cms.
and I wonder it must be possible to make flat file database right?

**Note:** I realize this might be stupid idea/feature request.

There would be 2 folders.
- First holding collection schemas (CollectionSchemas/CollectionName).
- Second Holding folders named after collections which hold records (Collection/CollectionName/record)

I am writing this cause I think this could be used for easy scaling of db. You could use NFS mounted space as place to store records.

Mayby it even would allow for some load balancing/having many instances use the same mount point... not sure about that one.
It could be under secondary setting. Also I think it could be taking more disk space than it needs to.

**Comment by ganigeorgiev** [comment]
I don't understand what exactly you have in mind but there are no plans to change the database structure or replacing SQLite.

**Comment by pietru2004** [comment]
I was thinking of it as secondary mode...

**Comment by pietru2004** [comment]
Prbably gona try to make it one day to see would it work...
