### ISSUE TITLE
Verifications Email - Failed to locate a sendmail executable path.

### ISSUE THREAD

**Issue by MostafaAmer-dev** [pocketbase/pocketbase#5384]
I have added the send email to a route as below, and trying to test it using Postman with it URL but the response keeps returning 400

Check the below log file from Pocketbase Logs
[log_20240823185756474Z.json](https://github.com/user-attachments/files/16732724/log_20240823185756474Z.json)

`

PocketInstance.OnBeforeServe().Add(func(e *core.ServeEvent) error {
                e.Server.WriteTimeout = config.ReadWriteTimeout
                e.Server.ReadTimeout = config.ReadWriteTimeout
          
                e.Router.GET(mHeaders.SendEmailPath,
                        func(c echo.Context) error {
                                //                                utils.AppLogger().Println("reader = ", apis.RequestInfo(c).Headers)

                                reciever := stringUtils.AnyToString(apis.RequestInfo(c).Headers[mHeaders.EmailAddress])

                                return mFunctions.SendEmail(PocketInstance, "Account Verification", reciever)
                        },
                        apis.ActivityLogger(PocketInstance), apis.RequireGuestOnly())

                return nil
        })

`

**Comment by ganigeorgiev** [comment]
This is expected if you don't have the unix `sendmail` command available and enabled.

For universal test purposes I usually recommend testing with [mailtrap.io](https://mailtrap.io/) or [smtpbucket.com](https://www.smtpbucket.com/). You can setup the SMTP configuration from the Admin UI > Settings > Mail settings.

For other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose) instead as the threaded format is more suitable for this type of posts.
