### ISSUE TITLE
Feature Request: Bulk create option

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/pocketbase#5386]
in the current version of Pocketbase, it create more than 1 record we have to use a loop and send a request every time, I think that this is a very power consuming task that if done on a large scale could be a bottle neck, so I want an option to create records in a bulk, like a list of records in one single go, it would be really handy and it will save lots or resources on the server/client side of my app, and thanks!

**Comment by ganigeorgiev** [comment]
Bulk/transactional create/update/upsert/delete Web APIs are already implemented as part of the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and will be available with the next v0.23.0 release (there are no ETAs yet).
