### ISSUE TITLE
Control characters in automatic ID creation

### ISSUE THREAD

**Issue by EliteEPM** [pocketbase/pocketbase#5392]
Is there any way to control the auto ID generated when a new record is added? The first character occasionally being a number is causing an issue in another downstream system. Or is the only option to generate a random ID myself and use that when creating the record

**Comment by ganigeorgiev** [comment]
There is no option to change the default auto generate `id` pattern at the moment. You can submit your own generated id when creating the record (it must be 15 chars).

More control over the system fields, including the `id`, is already implemented as part of the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and it will be available with the next v0.23.0 release soon (there are no ETAs yet).
