### ISSUE TITLE
Bug: Can't save formatted 0-UUID in text field

### ISSUE THREAD

**Issue by DaniDipp** [pocketbase/pocketbase#5398]
When I try to save `00000000-0000-0000-0000-000000000000` in a field of type "text", it is saved as being empty. This is only a problem with a string of this exact format.

Workaround: removing the dashes. `00000000000000000000000000000000` saves fine.

**Comment by ganigeorgiev** [comment]
Should be fixed with [v0.22.20 release](https://github.com/pocketbase/pocketbase/releases) (_if not make sure to clear the browser cache_).
