### ISSUE TITLE
Able to update file attribute with @request.data.image:isset = false

### ISSUE THREAD

**Issue by hhhtylerw** [pocketbase/pocketbase#5436]
![image](https://github.com/user-attachments/assets/24530a80-4a7b-403a-90f3-ab5bc4d05a51)

Please correct me if I am wrong, but I seem to have run into a serious API rule problem.
I have an attribute in my table that holds a profile picture: 

![image](https://github.com/user-attachments/assets/62264103-f186-4708-b9f9-65986a6efb45)
I want to make it such that dashboard_users can not update this field and I have done so by ensuring that the image attribute is not set in update queries.

`@request.data.image:isset = false`

I am able to update the image regardless. 

Version:
`"dependencies": {
		"pocketbase": "^0.21.4"
	}`

**Comment by hhhtylerw** [comment]
![image](https://github.com/user-attachments/assets/a8f60b8c-d89d-49ae-a136-4a53d6c8dbc0)

**Comment by LuminareHQ** [comment]
To prevent users on the dashboard_users collection from updating, you can simply use `@request.auth.id != "" && @request.auth.collectionName != "dashboard_users"`, this allows users who are logged in, but not with the collection dashboard_users.

**Comment by ganigeorgiev** [comment]
I will consider documenting it better but files (when submitted as blobs) are not part of the `@request.data.*` attributes (`@request.body.*` with the next release) since they are not serializable.

Option to target the raw/resulting value could be added with the ongoing refactoring but I have so many other tasks to work on and I cannot promise anymore that I will be able to include it.

For now as a workaround you can create a hook and compare the `record.GetString("yourFile")` data.

**Comment by ganigeorgiev** [comment]
Just for info in case someone stumble here: for consistency with the upcoming new file Go apis (_users will be able to assign directly a file via `record.Set("image", file)`_), support for targeting the uploaded files with the `@request.*` filter field was implemented as part of the refactoring and will be available with the next v0.23.0 release.

For security and performance currently we serialize only the below uploaded file attributes:
- `size` (the length of the parsed multipart/form-data file header bytes)
- `originalName` (the name of the file as it was submitted)
- `name` (that actual file name that will be stored in the database; it is normalized and suffixed with a random part)

The next release will also introduce support for array index-like access to the body fields to accommodate multivalued fields access (`file`, `select`, `relation`) similar to the `json` field type, aka. `@request.body.yourFileField.0.size.originalName ~ "example"`.
