### ISSUE TITLE
Unable to GET single record from "users" collection

### ISSUE THREAD

**Issue by rmso27** [pocketbase/pocketbase#5442]
Hi,

I'm trying to get data from a single user record and I'm not able to do so. When I call _**http://127.0.0.1:8090/api/collections/users/records/6ptakfsdinln9wa**_, I get the following result:

```
{
  "code": 404,
  "message": "The requested resource wasn't found.",
  "data": {

  }
}
```

If I try to get the list with all records with **_http://127.0.0.1:8090/api/collections/users/records/_**, I get the following result:

```
{
  "page": 1,
  "perPage": 30,
  "totalItems": 2,
  "totalPages": 1,
  "items": [
    {
      "collectionId": "_pb_users_auth_",
      "collectionName": "users",
      "created": "2024-08-30 13:27:37.934Z",
      "emailVisibility": false,
      "group": "test group",
      "id": "6ptakfsdinln9wa",
      "name": "Ruben Oliveira",
      "updated": "2024-08-30 15:21:00.303Z",
      "username": "ruben.oliveira",
      "verified": false
    },
    {
      "collectionId": "_pb_users_auth_",
      "collectionName": "users",
      "created": "2024-08-30 15:11:24.268Z",
      "emailVisibility": false,
      "group": "test group",
      "id": "9703x3urpcr8672",
      "name": "Rodrigo Oliveira",
      "updated": "2024-08-30 15:21:08.941Z",
      "username": "rodrigo.oliveira",
      "verified": false
    }
  ]
}

```
As you can see, the ID that I'm trying to read exists.

I'm running PocketBase 0.22.20.

Thank you!

**Comment by ganigeorgiev** [comment]
This is not a PocketBase issue. We have [automated tests](https://github.com/pocketbase/pocketbase/blob/5547c0deded8f9cc329cd6f0670aef19e2a3001a/apis/record_crud.go#L98) that confirms the View action working correctly.

Make sure that your client request satisfies the View API rule of your collection.

If you have other questions, please use the Q&A discussions instead.

**Comment by rmso27** [comment]
Thank you! I'll do that
