### ISSUE TITLE
Feature Request: Field labels and field hints

### ISSUE THREAD

**Issue by marnixk** [pocketbase/pocketbase#5469]
Hi,

Thank you for this wonderful project! I was able to use it for a personal project recently, and really enjoyed the experience. 

After using it for a bit, I have a suggestion for the Admin UI that I would like to share.

It would be great if for each collection field, we would be able to specify two additional optional fields alongside the already required "Field name", namely:

- Field Label; and
- Field Hint

The label would be a more human-readable version of the "Field name" that is shown in the UI whenever currently "field name" is shown. The field hint, if specified, could show a little bit of extra information about a field in the interface while adding or updating records.

So for example in a table that has a comma-separated tag field you could specify:

- A field of type: Text
- with field name: 'tags'
- with field label: "Article Tags"
- with a field hint: "Use comma-separated values to specify tags"

I think this could help make the Admin UI even more easy to navigate and edit. Would love to hear your feedback.

**Comment by ganigeorgiev** [comment]
This was discussed several times before. There are no plans to add field labels but field hints/instructions [exists in the roadmap](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=instructions&pane=issue&itemId=37392385) to consider at later stage but remains a very low priority for now.

**Comment by marnixk** [comment]
Thanks for your reply, I understand, no worries.
