### ISSUE TITLE
[Feature Request] AI chat interface to perform operations

### ISSUE THREAD

**Issue by jeffscottward** [pocketbase/pocketbase#5475]
Citing from the end of my post over here, https://github.com/pocketbase/pocketbase/discussions/5313#discussioncomment-10534350, a way to do everything with Pocketbase by text/voice using an LLM. https://postgres.new is a fantastic example of this. And arguably PB could do even more than just the data modeling. Would be an interesting window.AI use case.

**Comment by ganigeorgiev** [comment]
there are no plans for this.

**Comment by jeffscottward** [comment]
Is it a time issue? I may be up for experimenting to get it working over the winter.

Or is it just not even wanted?

**Comment by ganigeorgiev** [comment]
Both. At the moment there are way too many other tasks to work on and I don't want to maintain an LLM integration that I personally don't see much use case for it, nor I think it needs to be part of the main repo.
