### ISSUE TITLE
Migrations inside pb_migrations are not being applied

### ISSUE THREAD

**Issue by Ethanol48** [pocketbase/pocketbase#5477]
I recently changed my computer and move out to college, I was working in a pocketbase project and I managed to copy all the folders from the project (except pb_data for security reasons), the changes that I've done to the database was made through the UI which created js files inside pb_migrations, and all the changes are reflected in multiple js files inside `pb_migrations`, the code seems fine, it looks like the documentation. 

But, for some reason I can't manage to push these changes to pocketbase, I tried the steps in [here](https://pocketbase.io/docs/js-migrations/), I don't know if I'm doing something wrong.

I've tried to create fresh migration files, and try to run `./pocketbase migration up`, but it always returns "No new migrations to apply"

**Comment by ganigeorgiev** [comment]
I don't think your issue is PocketBase related, nor there is anything in your description to help me reproduce it.

Make sure that the pb_migrations are located next to the executable (otherwise you have to specify the `--migrationsDir` flag).

To verify that the migrations were applied you can also explore directly the generated `pb_data/data.db` file with the sqlite3 cli tool:

```sh
// print all tables
sqlite3 pb_data/data.db '.tables'
```

If you still think that there is a PocketBase issue, feel free provide clear reproducible steps or repo and I'll try to investigate it but as of now there is nothing much I can help here.

**Comment by Ethanol48** [comment]
This is the structure of my project:

I have in the root my `main.go` which is where I run the instance of pocketbase. 
and then in the same directory I have my `pb_migrations` and `pb_data` (the data folder is not showing because of a plugin I have in neovim but is there),

in these migrations I create multiple tables and made changes to view rules,.. etc.

but none of these changes are reflected neither in the Admin UI nor the sqlite table.

![240903_20h09m36s_screenshot](https://github.com/user-attachments/assets/eda8af77-c40e-4e13-9dcf-ed5210ab1246)


For example in one of the files I create a table called "Clients" this is the source code:

```js
/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const collection = new Collection({
    "id": "9vwramynht0p05d",
    "created": "2024-08-06 11:40:43.319Z",
    "updated": "2024-08-06 11:40:43.319Z",
    "name": "Clients",
    "type": "base",
    "system": false,
    "schema": [
      {
        "system": false,
        "id": "y95sfyz3",
        "name": "id_user",
        "type": "relation",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
          "collectionId": "_pb_users_auth_",
          "cascadeDelete": false,
          "minSelect": null,
          "maxSelect": 1,
          "displayFields": null
        }
      },
      {
        "system": false,
        "id": "xmp2ahcf",
        "name": "nombre",
        "type": "text",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      },
      {
        "system": false,
        "id": "s3kcn3ra",
        "name": "cif_o_nif",
        "type": "text",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      },
      {
        "system": false,
        "id": "5olnar0k",
        "name": "is_accountant",
        "type": "bool",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {}
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX `idx_m7roMde` ON `Clients` (\n  `id_user`,\n  `cif_o_nif`\n)"
    ],
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "options": {}
  });

  return Dao(db).saveCollection(collection);
}, (db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("9vwramynht0p05d");

  return dao.deleteCollection(collection);
})
```

This in theory should be automatically synced I assumed by the documentation, but if I check the admin UI:

Admin UI:
![240903_20h25m40s_screenshot](https://github.com/user-attachments/assets/f9c648b9-f4a7-4cc2-ba72-b0939d30cd07)

sqlite:
![240903_20h30m11s_screenshot](https://github.com/user-attachments/assets/121d3074-5150-4bbc-8bc0-ced782f27ae1)

None of the files inside the `pb_migrations/` are not commited

**Comment by Ethanol48** [comment]
### Steps to reproduce:

1. Create a pocketbase project and create new collections and changes through only the Admin UI.
2. After that, there should be a `pb_migrations` folder.
3. Copy all the projects files excluding the folder `pb_data` into another directory
4. Run pocketbase in the new directory

**Comment by ganigeorgiev** [comment]
Your issue is not PocketBase related.

Based on the screenshot it seems that you have a custom `main.go`, aka. you are not using the prebuilt PocketBase executable.

The JSVM (and js migrations) are enabled only if you enable the Go plugin as shown in https://github.com/pocketbase/pocketbase/blob/5547c0deded8f9cc329cd6f0670aef19e2a3001a/examples/base/main.go#L95-L108.

If you have other questions elaborate in Q&A discussion what you are trying to do because for me the above doesn't make much sense (if you are using Go you can simply use the Go migrations as shown in https://pocketbase.io/docs/go-migrations/)

**Comment by Ethanol48** [comment]
Thank you for pointing that out, I was able to fix my problem

> Your issue is not PocketBase related.
> 
> Based on the screenshot it seems that you have a custom `main.go`, aka. you are not using the prebuilt PocketBase executable.
> 
> The JSVM (and js migrations) are enabled only if you enable the Go plugin as shown in
> 
> https://github.com/pocketbase/pocketbase/blob/5547c0deded8f9cc329cd6f0670aef19e2a3001a/examples/base/main.go#L95-L108
> .
> 
> If you have other questions elaborate in Q&A discussion what you are trying to do because for me the above doesn't make much sense (if you are using Go you can simply use the Go migrations as shown in https://pocketbase.io/docs/go-migrations/)
