### ISSUE TITLE
Suggestion: python sdk for pocketbase

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/pocketbase#5487]
I've noticed that pocketbase has only a javascript and a dart sdks, and I wonder if a python sdk (or sdks for any other language) are planned in the future, and if you're willing to accept a sdk made by the community and turn it into an official one, as me and many other python devs are willing to contribute to the development to pocketbaset .
and it won't be that hard to implement a 1-to-1 copy, as most javascript features are not that hard to move over ||as of my python knowledge goes||, as the creator of pocketbase you're free to make your own requirements as needed

thanks in advance

**Comment by ganigeorgiev** [comment]
You could check https://github.com/pocketbase/pocketbase/discussions/391, https://github.com/pocketbase/pocketbase/discussions/502, https://github.com/pocketbase/pocketbase/issues/2880, https://github.com/pocketbase/pocketbase/issues/564 and probably others.

There are no plans to work on other SDKs at the moment.

Community contributions are welcomed and there is no need your repo to be under PockerBase.
