### ISSUE TITLE
[Enhancement] API Delete rule to restrict everyone

### ISSUE THREAD

**Issue by bloor** [pocketbase/pocketbase#5488]
![image](https://github.com/user-attachments/assets/e9e96bdb-dc53-4f7d-94c3-ab84575cf023)

I am a dumb kid. I might delete stuff that should NEVER be deleted. Any way to use something like above that restricts even me, the dashboard admin, from deleting records through the admin-panel ? 

... or a checkbox on the table that prevents deleting ?
... or can we have restricted roles admins !?

**Comment by ganigeorgiev** [comment]
It may eventually be handled as part of https://github.com/pocketbase/pocketbase/issues/5096 but for now remains out of the scope.

**Comment by bloor** [comment]
Yas ! That would also be valid.
