### ISSUE TITLE
update record with a WHERE statement

### ISSUE THREAD

**Issue by mcmuchenje** [pocketbase/pocketbase#549]
Trying to update a record in a collection where i match a field which is not the RECORD_ID

not sure if this is possible is the javascript-sdk

Kindly requesting help

Big fan of the project by the way

**Comment by ganigeorgiev** [comment]
You can update a record only by its ID.

If you want to update by ussing different field, you can query first the record and then extract its id and send the update request.

In future we will add support for bulk update/create/delete which will allow providing a filter query, but that will be after the users and profiles refactoring (you could also check this discussion - https://github.com/pocketbase/pocketbase/discussions/545).

**Comment by hood** [comment]
This should not be marked as complete IMHO. Keeping it open makes sense in this case.

**Comment by ganigeorgiev** [comment]
@hood bulk update/create/delete will be handled together with the data import feature. You could subscribe to issue #48.

**Comment by ganigeorgiev** [comment]
@0x1337z If you are asking for updating a record using a `WHERE`/filter clause with the Web APIs, then No and there are no longer plans for this as it comes with too many edge cases. If you really need it you'll have to register your own route and operate with db helpers (using [Go](https://pocketbase.io/docs/go-routing/) or the [JSVM](https://pocketbase.io/docs/js-routing/)).

If you are asking for the bulk update/create/delete actions, then this is already implemented as part of the [ongoing refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) but again the individual operation would be similar to the existing APIs, aka. they require to provide the id of the record to update.
