### ISSUE TITLE
Issue: Backup download from admin site shows the auth type as guest

### ISSUE THREAD

**Issue by GD-coding** [pocketbase/pocketbase#5493]
Is this the intended behavior? Or could this also be a security vulnerability. Thank you for all the work you do on this. I am also on version 0.22.17, so not sure if this was fixed in a later update. I do not see any release notes that indicate so.

See the screenshot below

![Screenshot 2024-09-07 at 11 46 01 AM](https://github.com/user-attachments/assets/fad5dd98-d1ee-4b3e-89f0-fe8d559ba553)

**Comment by ganigeorgiev** [comment]
It is just an implementation detail, it is not a security issue.

The `auth` field in the logs indicates whether the request was sent with valid `Authorization:TOKEN` header, but backups download and [protected files](https://pocketbase.io/docs/files-handling/#protected-files) doesn't use the `Authorization` header and instead rely on a short-lived token send with the file GET request.

We also have automated tests that verify that backups are accessible only by admins - https://github.com/pocketbase/pocketbase/blob/5547c0deded8f9cc329cd6f0670aef19e2a3001a/apis/backup_test.go#L338.

In any case, if you think that something is a security issue the safest way will be furst to report it either via the GitHub security advisory or at support [at] pocketbase.io as  mentioned in the [Security policy](https://github.com/pocketbase/pocketbase?tab=security-ov-file#readme)
