### ISSUE TITLE
Feature Request: Bind bcrypt functions to $security helper in JSVM

### ISSUE THREAD

**Issue by minhchu** [pocketbase/pocketbase#5514]
Hi 

I think it'd be nice to have bcrypt functions in JSVM.

Something like:

```
$security.bcryptGenerateHash
$security.bcryptCompareHash
```

**Comment by ganigeorgiev** [comment]
I will consider it with the next release but you could elaborate a little more in what context do you plan to use them?

Note that usually when operating with auth record passwords there are existing helpers like `record.validatePassword(pass)` and `record.setPassword(pass)`.
