### ISSUE TITLE
Adding a schema definition endpoint

### ISSUE THREAD

**Issue by TheExiledCat** [pocketbase/pocketbase#5515]
I had a cool idea that could make pocketbase alot more accessible for specifically ORM's or other OOP implementations of a frontend client. 

Would it be possible for an endpoint to be added (something like /api/schema/(nothing for the entireschema or a collection id for a specific collection) that allows a frontend to query the schema before fetching data? 

This could also be used for making code generators that can for example generate OOP classes or types to more easily work with data in the frontend.

**Comment by ganigeorgiev** [comment]
You could do that already with the existing [Collections Web APIs](https://pocketbase.io/docs/api-collections/) (_requires admin auth token_).

If you want a more limited information (e.g. just the schema) and to allow for everyone to query, then you can create a [View collection](https://pocketbase.io/docs/collections/#view-collection) with a query like:

```sql
SELECT id, name, schema
FROM _collections
```

**Comment by TheExiledCat** [comment]
Would this allow me to get the schema from every collection at once as well?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TheExiledCat** [comment]
It would just be nice to have a builtin standard endpoint like that that u can set the api rules for as well from the dashboard. So a frontend (regardless of who setup the pocketbase backend) can always try to query for the schema from a standard endpoint or something (or am i missing something here that can already so that?)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ganigeorgiev** [comment]
Again, there is no need for dedicated endpoint. You can create a [View collection](https://pocketbase.io/docs/collections/#view-collection) with the specific `_collections` columns you want and it will generate a List and View APIs for you like for the regular colletion record APIs.

**Comment by TheExiledCat** [comment]
The reason why i tought a dedicated endpoint would be handy is for vases when you dont own the backend but want to just poll it for the schema.

And how exactly would i do it without using the view collections? So just using the web api? I cant find anything about it in the docs.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ganigeorgiev** [comment]
OK, I think we are going in circles and I really don't like this pointless back-and-forth.

Please refer to the links above. To create a "View collection" you can go in the Admin UI > "+ New collection" button > Choose "Type: View" > Paste the above SQL query and adjust the List and View API rules to your needs.

More than this I cannot help further.
