### ISSUE TITLE
timestamps and the javascript sdk: a footgun 🔫

### ISSUE THREAD

**Issue by 5P5** [pocketbase/pocketbase#5516]
# Problem setup

- Create rule: `@request.data.timestamp <= @now`
- sent example request with js-sdk: `pb.collection("post").create({text: "bla bla", timestamp: new Date()})`

this will always fail with **Failed to create record. DrySubmit create rule failure: sql: no rows in result set!**

# Why this happens

Reason being `Date.toJSON()` will return as timestamp the form `2024-09-13T02:44:06.941Z`  
yet pocketbase `@now` is a timestamp in the form of `2024-09-13 02:45:06.229Z`
mind the letter `T` instead of a space ` `!!!

root cause is this gullible `JSON.stringify()` https://github.com/pocketbase/js-sdk/blob/01951f3a42152e72b79ed5709435edf94dca279f/src/Client.ts#L343

> Date objects implement the toJSON() method which returns a string (the same as date.toISOString()). Thus, they will be stringified as strings. 
-- [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description)

NB:
in sqlite it is without T `"created" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ'))`  
in go source also without T https://github.com/pocketbase/pocketbase/blob/5547c0deded8f9cc329cd6f0670aef19e2a3001a/tools/types/datetime.go#L12

# funny enough this will always work

- Create rule: `@request.data.timestamp >= @now`
- sent example request with js-sdk: `pb.collection("post").create({text: "bla bla", timestamp: new Date()})`

json is `{text:"bla bla",timestamp:"2024-09-13T03:30:50.364Z"}`
@now `2024-09-13 03:30:51.652Z` (actually a greater time)

caused by the lexical sort `T` vs ` ` (space)

# how to fix this bad behavior

use a custom [replacer function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter)

however in the naive approach the value passed to the replacer function is already the Date.toJSON() string, so a typeof string 😢 
```js
JSON.stringify({text: "bla bla", timestamp: new Date()}, (key, value) => value instanceof Date ? value.split("T").join(" ") : value );
'{"text":"bla bla","timestamp":"2024-09-13T04:46:31.461Z"}' 
```

fortunately we can do some shenanigans via `this` to grab the original instanceof Date value and format it correctly 😄 
```js
JSON.stringify({text: "bla bla", timestamp: new Date()}, function (key, value) { return this[key] instanceof Date ? value.split("T").join(" ") : value });
'{"text":"bla bla","timestamp":"2024-09-13 04:47:06.548Z"}' 
```
I submitted a PR for this https://github.com/pocketbase/js-sdk/pull/310

**Comment by ganigeorgiev** [comment]
This is not an issue.

All PocketBase dates at the moment expects to be in the format 'Y-m-d H:i:s.uZ'. You are comparing iso8601 vs rfc3339 formats (on SQL level dates are compared as strings).

In the future there are plan to allow custom date formats as field options but for now this remains a low priority.

**Comment by 5P5** [comment]
> All PocketBase dates at the moment expects to be in the format 'Y-m-d H:i:s.uZ'. You are comparing iso8601 vs rfc3339 formats (on SQL level dates are compared as strings).

… yes, obviously.

Yet I argue, a standards mismatch in **pocketbase + sdk** *itself* is a major issue.

As of now timestamp comparison *is broken out of the box* in an everyday use case
and it is nowhere mentioned explicitly in the [docs](https://pocketbase.io/docs/api-rules-and-filters/#-macros) such a footgun exists.

This leads to a needlessly bad developer experience,
yet the sdk could implicitly take care of this.

A hint in the docs would be helpful at least 😃 

- Concerning later custom date formats:
I would assume those are a typeof string, thus would not be affected by the normalization.
Only a value instanceof Date will be normalized by the sdk to match the sql format.
