### ISSUE TITLE
Getting records for a specific date?

### ISSUE THREAD

**Issue by zettadam** [pocketbase/pocketbase#5523]
I can't find anywhere in the documentation and I checked macros (@day, etc.) how to construct a query returning all records for a specific date. I assume that this is such a common case and PocketBase would make it clearer.

Also, is it possible to use SQLIte `date` function with filters, like:

```js
const result = await pb.collection('posts').getFullList({ filter: 'date(created) = "2024-09-15"', sort: '-created'})
```

**Comment by ganigeorgiev** [comment]
It is not possible to use SQLite date filters as part of a filter expressions.

Dates are compared as strings. PocketBase stores dates in a rfc3339 compatible format (_mostly for compatibility reasons with earlier versions_) and full date format is `Y-m-d H:i:s.uZ` (aka. the same as what is returned in the API response).

If you want to filter all records that were created for the specified day you can use filter like:

```js
filter: 'created >= "2024-09-15 00:00:00.000Z" && created <= "2024-09-15 23:59:59.999Z"'
```

For other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose) instead.

**Comment by zettadam** [comment]
Thanks, @ganigeorgiev.
