### ISSUE TITLE
Issue: Function Declared Outside `routerAdd` Not Accessible Within Route Handler

### ISSUE THREAD

**Issue by hugo-abdou** [pocketbase/pocketbase#5528]
![image](https://github.com/user-attachments/assets/24fe0178-ac5a-41bf-b3a6-53c0b61bde6b)

### Description
When declaring a function outside of the `routerAdd` block, it becomes inaccessible within the route handler, resulting in a `ReferenceError`.

### Steps to Reproduce
1. Declare a function (e.g., `getCompletedLessons`) outside of the `routerAdd` block.
2. Attempt to use this function within a route handler.

### Current Behavior
Calling the function results in a `ReferenceError`:

### Expected Behavior
Functions declared outside of `routerAdd` should be accessible within route handlers.

### Code Example
`
javascript
const getCompletedLessons = (courseId, studentId) => {
// Function implementation
};
routerAdd(
"get",
"/api/v1/courses/:course/videos",
(c) => {
const courseId = c.pathParam("course");
const studentId = c.queryParam("student");
// This line causes the error
return c.json(200, getCompletedLessons(courseId, studentId));
}
);
`

### Environment
- PocketBase version: v0.22.19
- OS: ubuntu

### Additional Context
This issue limits the ability to organize code and separate concerns by defining reusable functions outside of route handlers.

### Possible Solution
Consider expanding the scope of functions declared outside `routerAdd` to be accessible within route handlers, or provide documentation on the correct way to structure code for reusability in this context.

**Comment by ganigeorgiev** [comment]
This is a known caveat of the current implementation. For this and others please refer to https://pocketbase.io/docs/js-overview/#caveats-and-limitations.

For more details why and how the JSVM works, you could check https://github.com/pocketbase/pocketbase/discussions/2825#discussioncomment-6376210.
