### ISSUE TITLE
Admin UI don't update in real time

### ISSUE THREAD

**Issue by lixelv** [pocketbase/pocketbase#5537]
I think it would be great to add auto-update functionality to the admin UI. Right now, when you change data in PocketBase, the changes aren’t reflected in the admin panel until you manually reload the page.

To improve this, you could implement real-time data updates in the admin UI.

Just a suggestion — the rest is up to you. And also, it is not an issue, it is a suggestion.

**Comment by ganigeorgiev** [comment]
There are no plans for this for now. It may added eventually as option in the future but for now major Admin UI changes out of the scope.
