### ISSUE TITLE
Sending emails with typescript extension hook has type error with the interface Address.

### ISSUE THREAD

**Issue by marcitqualab** [pocketbase/pocketbase#5538]
Hello, 

I have copy pasted the Send Custom email code into a main.pb.ts file with the pb types references.
`/// <reference path="../pb_data/types.d.ts" />`.

I am getting a type error on the `interface Address`. In my types.d.ts there are two Address interfaces.
```typescript
namespace mail {
 /**
  * Address represents a single mail address.
  * An address such as "Barry Gibbs <bg@example.com>" is represented
  * as Address{Name: "Barry Gibbs", Address: "bg@example.com"}.
  */
 interface Address {
  name: string // Proper name; may be empty.
  address: string // user@domain
 }
 interface Address {
  /**
   * String formats the address as a valid RFC 5322 address.
   * If the address's name contains non-ASCII characters
   * the name will be rendered according to RFC 2047.
   */
  string(): string
 }
}
```
And the error on VScode linting is this.
`
Type '{ address: string; }' is missing the following properties from type 'Address': name, stringts(2739)
'e.record' is possibly 'undefined'.ts(18048)
`
![pocketbase types error](https://github.com/user-attachments/assets/35e3a03c-8468-4a9e-8a96-5af11cdd02ce)

I am not sure if this is a typing error in the types.d.ts or I need to fix the TS code to send emails.

To reproduce this only create a .pb.ts file and copy paste the Send Custom Email example code of the official docs. https://pocketbase.io/docs/js-sending-emails/

Many thanks,
Marc

**Comment by ganigeorgiev** [comment]
The ambient TS declarations are autogenerated from the Go source code and the duplicated interface declaration is fine (they are merged/combined).

To "fix" the above error you can add empty `name` prop, aka. `{address: e.record.email ""}`.

I'll consider with the ongoing refactoring to provide a manual replacement for the `Address` interface to avoid "requiring" setting the name but for now remains a very low priority.

**Comment by marcitqualab** [comment]
Ok, thanks for the clarification.
