### ISSUE TITLE
Feature Request: Email query params

### ISSUE THREAD

**Issue by Armando-CodeCafe** [pocketbase/pocketbase#5556]
Hi, for cases where you have to verify users created by some admin for example (theres also more reasons this could be handy) it would be nice to be able to poll the query object inside of the email templates
something like {Query} would be nice. so for example when creating a new user we could pass a query param for their temporary name and password and then when sending the verification email do something like:

"Welcome to {APP_NAME}, a new account was made for you, the temporary password is {QUERY.PASSWORD}. Click button below to verify account"

This would allow alot more options when using the templates vs hooks.

P.S. as an extra example, this is how it could be used with for example the js sdk that already allows for adding query params to the call:

```typescript
   pb.collection("users").requestVerification(someEmail,{query:{password}})
 ```

**Comment by ganigeorgiev** [comment]
For now there are no plans for this because a mail send can be initiated without having access to a request context.

If users need more advanced mail customizations they will have to use the related mail send hook to overwrite the default template.
