### ISSUE TITLE
subscribe on view collection 

### ISSUE THREAD

**Issue by jesperordrup** [pocketbase/pocketbase#5564]
There is a few ways to allow views to work with subscribe.

The view is of course defined by a select statement referencing one or more collections (tables). Example a view could be called order_and_orderlines by a select statment that joins order and orderlines. 

* Idea 1: if any of the related tables is updated the view emits an event to the order_and_orderlines  subscripitons.
* Idea 2: add an option to ui to select which table events should be relayed to order_and_orderlines 

Edge case

the order_and_orderlines views where clause might filter out the updated row. This could be dealt with server side by checking the where clause or just not provide a record with the update

**Comment by ganigeorgiev** [comment]
No, sorry. There are no plans for this for now as there are too many edge cases since a view query could be practically anything.

**Comment by jesperordrup** [comment]
Might be.

My current workaround for that is to subscribe to the order collection just to trigger a fetch of the specified record in order_and_orderlines. Its clean and works and feels like something that could be implemented more direct by being able to specify the tables to bubble events from.

Such as:

Bubble events from

- [ ] orders
- [ ] order_lines

Let the event carry information about source.

And adding a text that explains that "view collections bubble event doesnt guarantee that the record is in the result" ...
