### ISSUE TITLE
Feature request: Make the Logs timeline zoomable and interactive

### ISSUE THREAD

**Issue by wdscxsj** [pocketbase/pocketbase#5566]
Currently multiple requests are combined on the timeline and it's hard to tell them apart. It would be nice if the timeline could be zoomed in to show individual request dots, and clicking a dot could jump to the corresponding record, or vice versa.

**Comment by ganigeorgiev** [comment]
The logs chart has been already made zoomable/pannable as part of the refactoring but the granularity for now remains hourly based so clicking on dots doesn't do anything.

I may reconsider it in the future but for now is of the scope.

**Comment by wdscxsj** [comment]
Thanks for your reply!
