### ISSUE TITLE
 Error when registering user through sdk

### ISSUE THREAD

**Issue by cetaru** [pocketbase/pocketbase#5572]
When registering a user through the js sdk, it does not verify that the email is valid and allows registering a user with spaces at the end of the email.
For example:
 await $pb.collection("users").create({
            name: "User1",
            email: "user1@gmail.com   ", 
            password:'12345678', 
            passwordConfirm:'12345678'
          });

will create the user and then you will not be able to log in.

**Comment by ganigeorgiev** [comment]
I've just tested it both locally with PocketBase v0.22.21 and the live demo, and it both cases the email validator works correctly for me when the domain part has a space:

```
{
    "code": 400,
    "message": "Failed to create record.",
    "data": {
        "email": {
            "code": "validation_is_email",
            "message": "Must be a valid email address."
        }
    }
}
```

If you want to inspect the returned response error, please check https://github.com/pocketbase/js-sdk?tab=readme-ov-file#error-handling.
