### ISSUE TITLE
Proposal: Choice to use DuckDB instead of SQLite

### ISSUE THREAD

**Issue by iNewmanity** [pocketbase/pocketbase#5576]
pocketbase is a really nice and fast Backend-as-a-Service, but wouldn't it be nice, to give users a choice to migrate and use duckdb, which is a alternative to sqlite. Could be implemented as a experimental feature first.

**Comment by ganigeorgiev** [comment]
For now there are no plans for this but with the upcoming v0.23.0 release (there are no ETAs yet) users will have the option to register externally any Go `database/sql` driver as long as it has compatible SQLite syntax dialect.

**Comment by Hu-Wentao** [comment]
cool, any update?

**Comment by ganigeorgiev** [comment]
@Hu-Wentao Please don't comment like that (at the minimum I consider it lazy and low-effort).

To load a custom driver you can check https://pocketbase.io/docs/go-overview/#custom-sqlite-driver. But again, this will work only with `database/sql` drivers compatible with the SQLite syntax. Support for other databases is not planned and out of the scope of the project.
