### ISSUE TITLE
creating a record, some errors end up in promise resolve than reject

### ISSUE THREAD

**Issue by SX-9** [pocketbase/pocketbase#5577]
![image](https://github.com/user-attachments/assets/debfd281-ef01-4cff-bbc2-2cf22bf61098)
Those `e` variables in the console are from the `.then` of the record creation in the `users` collection. For some reason the some fetch errors end up in a resolve promise rather than reject.

the first one is the fail request of registering a new user and the second was the sucessfull one

**Comment by ganigeorgiev** [comment]
_Please don't post code as screenshot. It is difficult to read and understand._

In any case it is not clear what you are trying to do, nor why do you think this is a PocketBase issue.

The JS SDK is a thin wrapper around the native `fetch`. The only difference regarding the `fetch` Promise resolution is that non 20x responses and other errors are normalized as `ClientResponseError` exception. For more details please check https://github.com/pocketbase/js-sdk?tab=readme-ov-file#error-handling.
