### ISSUE TITLE
Problems running latest Mac OS Sequoia 15.0

### ISSUE THREAD

**Issue by jeffscottward** [pocketbase/pocketbase#5580]
"pocketbase" can't be opened because Apple cannot check it for malicious software.
This software needs to be updated.
Contact the developer for more information.
Chrome downloaded this file today at
12:34 PM.

<img width="301" alt="Screenshot 2024-09-30 at 12 37 48 PM" src="https://github.com/user-attachments/assets/c5f7efe3-57c0-4c6c-97a9-eded54d81212">

**Comment by ganigeorgiev** [comment]
This warning unfortunately is unavoidable as I don't have mac nor I'm able to sign the binaries.

You can check https://github.com/pocketbase/pocketbase/issues/146 and https://github.com/pocketbase/pocketbase/issues/2819.
