### ISSUE TITLE
Check if current user has a password-auth set ?

### ISSUE THREAD

**Issue by bloor** [pocketbase/pocketbase#5598]
I have this scenario, where on my app users can either register emai/pass auth or straight register-via-socials.
![image](https://github.com/user-attachments/assets/b1a0a828-7376-4836-adf2-323f5fe2faee)

Now, my issue is.. if by accident I let my user unlink both social-logins. Due to him not having a password set, he is locked out.
His only option is to do a **lengthy** "password recovery" process on the binded email. 

**BUT(t)**
Is there a way to check if the user has not yet set a password so I could warn/or restrict him from unlinking his last social-auth ?
There is `$pb.collection(`users`).listExternalAuths($auth.user.id)` for external auths, is there something for normal auths ?

**Comment by ganigeorgiev** [comment]
Please don't open issues like this.

If you have a general question, use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose) instead.

If you have a feature request (or think that there is a bug) state it clearly and elaborate on the desired behavior.

In any case, if you want to prevent external auth unlinking based on some criteria, you can try attaching to the `OnRecordAfterUnlinkExternalAuthRequest` hook. One possible example with the JS pb_hooks could be:

```js
onRecordAfterUnlinkExternalAuthRequest((e) => {
    // check for example the total available external auths
    let externalAuths = $app.dao().findAllExternalAuthsByRecord(e.record)
    if (externalAuths.length < 2) {
        throw new BadRequestError("...")
    }
}, "users")
```
