### ISSUE TITLE
Clearer documentation on using as a framework

### ISSUE THREAD

**Issue by samuel-pratt** [pocketbase/pocketbase#56]
When running the default app provided [here](https://pocketbase.io/docs/use-as-framework/) with `go build && ./app`, instead of starting a server it gives the following printout for the pocketbase CLI, a CLI I can't find documentation on installing. Just curious if I'm missing something here, running from the downloadable executable works fine, but can't seem to use it as a framework.

```
PocketBase CLI

Usage:
  pocketbase [command]

Available Commands:
  help        Help about any command
  migrate     Executes DB migration scripts
  serve       Starts the web server (default to localhost:8090)
  version     Prints the current PocketBase app version

Flags:
      --debug                  enable debug mode, aka. showing more detailed logs
      --dir string             the PocketBase data directory (default "pb_data")
      --encryptionEnv string   the env variable whose value of 32 chars will be used 
                               as encryption key for the app settings (default none)
  -h, --help                   help for pocketbase

Use "pocketbase [command] --help" for more information about a command.
```

**Comment by samuel-pratt** [comment]
Closed because I figured it out, running with `./app serve` is the solution

**Comment by BunnyTheLifeguard** [comment]
> Closed because I figured it out, running with `./app serve` is the solution

Do you happen do know how to use it without building `go run && ?`

**Comment by ganigeorgiev** [comment]
@BunnyTheLifeguard Could you elaborate what actually you are trying to do?

If you want to just run PocketBase, you can download and start the prebuilt executable for your platform from the "Assets" section in https://github.com/pocketbase/pocketbase/releases. Extract the zip and start it by running `./pocketbase serve`.

---

If you want to embed PocketBase in your Go app (aka. using it as framework):

0. Run `go mod init` (if you haven't already) and run `go get github.com/pocketbase/pocketbase`

1. create a Go file `main.go`:
```go
package main

import (
    "log"
    "net/http"

    "github.com/pocketbase/pocketbase"
)

func main() {
    app := pocketbase.New()

    if err := app.Start(); err != nil {
        log.Fatal(err)
    }
}
```

2. To run it locally, execute `go run main.go serve`

3. To build, execute `go build` and then start the result binary:  `./yourapp serve`

**Comment by BunnyTheLifeguard** [comment]
@ganigeorgiev Oh thanks for the quick reply.
I was indeed planning on using it as a framework, so the command in step 2 was it, this should be in the docs :)
