### ISSUE TITLE
Expand documentation suggestion

### ISSUE THREAD

**Issue by adamshand** [pocketbase/pocketbase#561]
Hello,

I'm loving Pocketbase, such a fast and lightweight way to make data accessible via API.

A minor documentation suggestion.  I got really confused by the expand examples in the "API Preview".  Where it says:

> Auto expand record relations. Ex.: ?expand=rel1,rel2.subrel21.subrel22

I thought that rel1 was the collection, not the column. Took me ages to realise what I was doing wrong. It would have been helpful for me if the example was something like:

> Auto expand record relations. Ex.: ?expand=columnA,columnA.columnC

Anyway, thanks again for the great project!
Adam.

**Comment by ganigeorgiev** [comment]
Thanks, I'll have it mind when redesigning the collections API preview UI in relation of #376.
