### ISSUE TITLE
Change password length of OTP failed

### ISSUE THREAD

**Issue by raizdev** [pocketbase/pocketbase#5625]
While changing OTP password length i'm receiving failed due formatting

![image](https://github.com/user-attachments/assets/46100461-ff84-4ed6-8f45-fc57ee6998fd)

**Comment by ganigeorgiev** [comment]
It was fixed earlier today in https://github.com/pocketbase/pocketbase/issues/5617.

I'll push a `rc3` prerelease sometime tomorrow (eventually with fix for https://github.com/pocketbase/pocketbase/discussions/5623#discussioncomment-10873639).
