### ISSUE TITLE
Typo: requestOtp -> requestOTP

### ISSUE THREAD

**Issue by raizdev** [pocketbase/pocketbase#5628]
````
const req = await pb.collection('users').requestOtp('test@example.com');
````

Should be

````
const req = await pb.collection('users').requestOTP('test@example.com');
````

![image](https://github.com/user-attachments/assets/dd0c2863-1cbe-48a3-a831-270c4c147fcc)

**Comment by ganigeorgiev** [comment]
Thanks! I've fixed it locally and will push it with the other rc3 changes later this evening.

**Comment by raizdev** [comment]
Thx! The same for authWithOTP :)
