### ISSUE TITLE
[Suggestion] Do not automatically updating the auth record when the fields parameter is not empty

### ISSUE THREAD

**Issue by cddqssc** [pocketbase/pocketbase#5638]
For the Auth collection, when updating a record and specifying fields, the returned record should only contain the specified fields.
![image](https://github.com/user-attachments/assets/0debf749-5500-4f4c-87b9-3b7376257d93)

Regarding the Dart SDK, after executing collection("users").update, the auth record is automatically updated. 
![image](https://github.com/user-attachments/assets/569589e9-268f-416f-9127-35b0284ba7c1)

If I specify fields during the update, the existing auth record will be overwritten with the record that only contains the specified fields.
![image](https://github.com/user-attachments/assets/bae4b034-172e-45bc-a711-ffc9f86d3329)

Could you consider not automatically updating the auth record when the fields parameter is not empty?

**Comment by ganigeorgiev** [comment]
I'll consider it before the final v0.23 release as I'll have to think a little more on it but maybe a better option could be instead of skipping the entire authStore record update we could replace only the new updated fields.

**Comment by ganigeorgiev** [comment]
I've pushed a small [Dart SDK v0.19.0-rc2](https://pub.dev/packages/pocketbase/versions/0.19.0-rc2/changelog) update reflecting the above.
