### ISSUE TITLE
Empty SQL query hangs forever

### ISSUE THREAD

**Issue by slntopp** [pocketbase/pocketbase#5649]
I was testing something and by mistake had a variable with a query string empty. Executing it (or rather parsing the results) hangs forever until killed by the OS.

### How to reproduce

```go
var foo []struct {
	Bar string `json:"bar"`
}
if err := app.Dao().DB().NewQuery("").All(&foo); err != nil {
	panic(err)
}

fmt.Printf("%+v\n", foo)
```

Output:
```
[1.00ms] SELECT {{_params}}.* FROM `_params` WHERE `key`='settings' LIMIT 1
[0.00ms] SELECT {{_collections}}.* FROM `_collections`
[0.00ms] 
signal: killed
go run ./cmd/server/main.go sql test-stuck  254.63s user 64.77s system 109% cpu 4:51.43 total
```

### Expected behaviour

1. Return error for empty query
2. Add timeout to `func (r *Rows) all(slice interface{}) error`

### Versions, etc

MacOS, arm64

```
	github.com/pocketbase/dbx v1.10.1
	github.com/pocketbase/pocketbase v0.22.17
```

This happens with both CGo enabled or disabled.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it with CGO disabled (aka. `CGO_ENABLED=0 go run . serve`).

I think it is an issue with the CGO driver (eg. https://github.com/mattn/go-sqlite3/issues/950) but I'll consider applying eventually a workaround for it in the dbx repo (there is also https://github.com/mattn/go-sqlite3/issues/1284 that I'll have to experiement how to workaround but other tasks are with higher priority right now).

**Comment by ganigeorgiev** [comment]
It is the same issue as above, here is a minimal reproducible:

```go
package main

import (
	"database/sql"
	"log"
	"os"

	_ "github.com/mattn/go-sqlite3"
	// _ "modernc.org/sqlite"
)

func main() {
	os.Remove("./foo.db")

	// modernc driver name is "sqlite"
	db, err := sql.Open("sqlite3", "./foo.db")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	println("start")

	r, err := db.Query(``)
	for r.Next() {
		println("row...")
	}

	println("end")
}
```

In any case, this is is easy to workaound and I'll consider skipping the empty query execution from the dbx repo.
