### ISSUE TITLE
Feature Request: UI Collections sort order

### ISSUE THREAD

**Issue by felix-schindler** [pocketbase/pocketbase#566]
In the admin ui it would be helpful to choose how the list of collections should be sorted (created, a-z)

**Comment by ganigeorgiev** [comment]
Thanks. It is already in my todo and I'll consider it when redesigning the collections UI in relation to #376.

**Comment by ganigeorgiev** [comment]
@kymc At least for v1.0.0, I don't plan adding drag&drop order support for the collection records. We currently support only a "table view" for the records listing and this will not work well with the manual drag&drop sorting (with v0.8 there will be drag&drop sorting only for the collection fields, aka. columns).
