### ISSUE TITLE
[v0.23.0-rc] Record cannot be updated on Admin UI if id starts with 0

### ISSUE THREAD

**Issue by kaboc** [pocketbase/pocketbase#5687]
I think this operation with the same id was successful before v0.23.0-rc.

1. Change some values.
2. Press "Save changes".
3. "Failed to update record" error

![id_error](https://github.com/user-attachments/assets/dfce5215-9a6a-496b-9345-8ebc7e4082ab)

Interestingly, this does not happen if the id value starts with a number other than `0`.

**Comment by ganigeorgiev** [comment]
This is happening because of the FormData string value normalization.

I've pushed a fix in the `develop` branch.

**Comment by kaboc** [comment]
It worked! Thank you very much!
