### ISSUE TITLE
Echo Prometheus Middleware not working with PocketBase

### ISSUE THREAD

**Issue by jriegraf** [pocketbase/pocketbase#5695]
Hi, I'm trying to add Prometheus metrics to my PocketBase app and I followed the guide in the documentation: https://echo.labstack.com/docs/middleware/prometheus

so I tried to add them like this, using PocketBase 0.22.21:

```go
app.OnBeforeServe().Add(func(e *core.ServeEvent) error {

    // prometheus metrics
    e.Router.Use(echoprometheus.NewMiddleware("myapp"))
    e.Router.GET("/metrics", echoprometheus.NewHandler())    

```
but get this compiler error:

```
Cannot use 'echoprometheus. NewMiddleware("myapp")' (type "github. com/ labstack/ echo/ v4".MiddlewareFunc) as the type "github. com/ labstack/ echo/ v5".MiddlewareFunc
```
there seems to be a version conflict, since PocketBase is already on Echo V5, but the middleware repo still expects V4: https://github.com/labstack/echo-contrib/blob/415ca6f10389ba1c183a15aadf192417fde79f16/go.mod#L9

I'm not sure if this is a PocketBase or an echo issue. Anyway, are there any recommendations on how I can deal with the issue?

**Comment by jriegraf** [comment]
I just saw that PocketBase no longer uses Echo in the upcoming version (v0.23.0), is that right? therefore this issue is obsolete, I guess

**Comment by ganigeorgiev** [comment]
PocketBase <= v0.22.x uses echo v5_alpha and you are importing a middleware from v4 and this will not work.

I'm not aware if echo has ported the specific middleware to v5.

And Yes - the upcoming PocketBase v0.23.0 no longer uses echo and instead has a thin wrapper around the standard Go `net/http` routing.

For other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) as the threaded format is more suitable for this type of posts.
