### ISSUE TITLE
API Rules (Row Level Access rules)

### ISSUE THREAD

**Issue by DDuran19** [pocketbase/pocketbase#5704]
![image](https://github.com/user-attachments/assets/3821ddc3-e38c-4181-899a-08a98dda77c2)

I have announcements and features collection. On my features collectiions, there's a flag for every feature for my app.

![image](https://github.com/user-attachments/assets/44b5de53-d1cf-4918-8d81-f9abe2703d63)

So I want to setup a rule such that it should check features collection first if the announcements feature is turned on.. 

but I have trouble creating the expression,.,. I think I made a mistake 

```
@collection.features.name = "announcements" && @collection.features.status = "on"
```

**Comment by DDuran19** [comment]
Without the `@collection.features` the rest of the rule is working fine..

```
(@collection.features.name = "announcements" && @collection.features.status = "on") && ((from = "" && to = "") || (to = "" && from <= @now) || (from = "" && to >= @now) || (from <= @now && to >= @now)) && (target_users:length = 0 || (@request.auth.id != "" && target_users.id ?= @request.auth.id))
```
![image](https://github.com/user-attachments/assets/be158d23-03cf-46ac-8575-513a29d0fa70)
````json
{
"page": 1,
"perPage": 30,
"totalItems": 0,
"totalPages": 0,
"items": []
}
```

Here's the one without the `@collection.features`
![image](https://github.com/user-attachments/assets/0c579613-fdb2-49cf-ab0d-dd61bab1047c)
```json
{
"page": 1,
"perPage": 30,
"totalItems": 1,
"totalPages": 1,
"items": [
{
"announcement": "welcome!",
"collectionId": "gd8k1mao1a5059u",
"collectionName": "announcements",
"created": "2024-10-19 03:12:23.485Z",
"from": "",
"html": "",
"id": "cltx6uuiko4n5gy",
"images": [],
"target_users": [],
"to": "",
"type": "system",
"updated": "2024-10-19 03:12:23.485Z"
}
]
}
```

**Comment by ganigeorgiev** [comment]
@DDuran19 Please don't create issues like this as this is not a PocketBase issue.

Prefer using the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose), don't post code as screenshots and instead clearly elaborate on the desired behavior and what doesn't work (see also https://xyproblem.info).

**Comment by DDuran19** [comment]
Really sorry @ganigeorgiev  🙏 I created https://github.com/pocketbase/pocketbase/discussions/5705 for this. I promise I will not use this Issue tab ever again for non-Pocketbase issues :)
