### ISSUE TITLE
Feature Request: Enable filtering of Relational field

### ISSUE THREAD

**Issue by Developermayank** [pocketbase/pocketbase#5711]
![image](https://github.com/user-attachments/assets/9fdc5aaf-d7d3-414d-aed3-153e4dab6afb)

Kindly provide the feature of limiting/filtering of relational field data based on criteria similar to api rules.

**Comment by ganigeorgiev** [comment]
Please don't open issues like this. It is not clear what yo are looking for nor what you are trying to do. Try to elaborate a little more on your use case and the desired behavior.

For general purpose questions prefer using the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose).
