### ISSUE TITLE
Feature Request: Rate Limiting [IF ERROR]

### ISSUE THREAD

**Issue by vsnshanmuganathan** [pocketbase/pocketbase#5713]
In the latest beta i could see the Rate Limiting which is very useful, 
but it would be more better if we have an option to Restrict if there was an ERROR call.
I mean for example: 
If a request we receive from an un-authorised or if it returns ERROR response multiple times, then we can block that IP like that, the feature is similar to WordPress [WPS Limit Login plugin](https://wordpress.org/plugins/wps-limit-login/) but here in pocketbase we can set as per Admin on our own rules.

**Comment by ganigeorgiev** [comment]
No, sorry. There are no plans for this for now as it is starting to become too complicated.
