### ISSUE TITLE
Cannot use refresh auth on rc7 and rc6

### ISSUE THREAD

**Issue by Inovvia** [pocketbase/pocketbase#5721]
I tried using the sveltekit ssr code and I can login when i remove the auth refresh. However I cannot check or refresh the auth since i get errors.
```

// src/hooks.server.js
import PocketBase from 'pocketbase';

/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
    event.locals.pb = new PocketBase('http://127.0.0.1:8090');

    // load the store data from the request cookie string
    event.locals.pb.authStore.loadFromCookie(event.request.headers.get('cookie') || '');

    try {
        // get an up-to-date auth store state by verifying and refreshing the loaded auth model (if any)
        event.locals.pb.authStore.isValid && await event.locals.pb.collection('users').authRefresh();
    } catch (_) {
        // clear the auth store on failed refresh
        event.locals.pb.authStore.clear();
    }

    const response = await resolve(event);

    // send back the default 'pb_auth' cookie to the client with the latest store state
    response.headers.append('set-cookie', event.locals.pb.authStore.exportToCookie());

    return response;
}
```

Here are the errors:
![image](https://github.com/user-attachments/assets/2365432f-274a-45d7-83cb-0a116205de2c)

 message: 'Something went wrong while processing your request.',

**Comment by Inovvia** [comment]
I haven't check older rc releases yet if this occurs.

**Comment by Inovvia** [comment]
I tried reproducing it on local but it works!. My production pocketbase server is behind cloudflare access.

**Comment by ganigeorgiev** [comment]
I'm sorry, I don't have much experience with Cloudflare and I can't help you with it settings.

If you are still not able to make it work, you can try creating a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new/choose) with more details about your env configurations and maybe someone else more familiar with the Cloudflare offerings will be able to assist you.

**Comment by Danjoe4** [comment]
Try running your container in host networking mode.
