### ISSUE TITLE
Feature: Python support for pocketbase

### ISSUE THREAD

**Issue by n1rjal** [pocketbase/pocketbase#5737]
Hi, this might be a bit out of topic but I would like to make `Extend with python` funtionality in pocketbase. I looked though your feature roadmap and it is not there. But I would like to make it. 

If pocketbase is open to it, I would like to contribute with it.

Thanks,
Nirjal Paudel

**Comment by ganigeorgiev** [comment]
Feel free to work on it. It doesn't need to be part of the main repo and can exist as separate plugin in its own repo.

**Comment by hasansezertasan** [comment]
> Feel free to work on it. It doesn't need to be part of the main repo and can exist as separate plugin in its own repo.

I'm interested in this. Do you have any suggestions for how I can start working on it?
