### ISSUE TITLE
Filter always returns zero results when combining multiple expressions which use the ?= operator

### ISSUE THREAD

**Issue by rosahaj** [pocketbase/pocketbase#5738]
I noticed that, when combining two or more filter expressions which use the `?=` operator, the combined filter seems to always return zero results, even when all the individual expressions are true.

## Example

**Collections:**

![Diagram showing two PocketBase collections. The first collection is called movies and has a name field and a tags field. The name field has a text type and must be non-empty. The tags field holds one or more relations to records of the tags collection. The second collection is called tags and has a label field. The label field has a text type and must be non-empty. An arrow points from the movies collection to the tags collection, showing the relationship between the two (a movie record can have multiple tags relations).](https://github.com/user-attachments/assets/1dfea558-6d35-42d6-b41d-aef1d9f4f3da)

[View diagram at PocketBaseUML](https://pocketbase-uml.github.io/view#W3siaWQiOiI4c3BiMHJyOXoybTh0OXEiLCJuYW1lIjoibW92aWVzIiwidHlwZSI6ImJhc2UiLCJzeXN0ZW0iOmZhbHNlLCJzY2hlbWEiOlt7InN5c3RlbSI6ZmFsc2UsImlkIjoiMXgzanpldDciLCJuYW1lIjoibmFtZSIsInR5cGUiOiJ0ZXh0IiwicmVxdWlyZWQiOnRydWUsInByZXNlbnRhYmxlIjpmYWxzZSwidW5pcXVlIjpmYWxzZSwib3B0aW9ucyI6eyJtaW4iOm51bGwsIm1heCI6bnVsbCwicGF0dGVybiI6IiJ9fSx7InN5c3RlbSI6ZmFsc2UsImlkIjoiaHBlZXh2b2MiLCJuYW1lIjoidGFncyIsInR5cGUiOiJyZWxhdGlvbiIsInJlcXVpcmVkIjpmYWxzZSwicHJlc2VudGFibGUiOmZhbHNlLCJ1bmlxdWUiOmZhbHNlLCJvcHRpb25zIjp7ImNvbGxlY3Rpb25JZCI6InY5cHVzMjEwZnlmNXB1ZiIsImNhc2NhZGVEZWxldGUiOmZhbHNlLCJtaW5TZWxlY3QiOm51bGwsIm1heFNlbGVjdCI6bnVsbCwiZGlzcGxheUZpZWxkcyI6bnVsbH19XSwiaW5kZXhlcyI6W10sImxpc3RSdWxlIjpudWxsLCJ2aWV3UnVsZSI6bnVsbCwiY3JlYXRlUnVsZSI6bnVsbCwidXBkYXRlUnVsZSI6bnVsbCwiZGVsZXRlUnVsZSI6bnVsbCwib3B0aW9ucyI6e319LHsiaWQiOiJ2OXB1czIxMGZ5ZjVwdWYiLCJuYW1lIjoidGFncyIsInR5cGUiOiJiYXNlIiwic3lzdGVtIjpmYWxzZSwic2NoZW1hIjpbeyJzeXN0ZW0iOmZhbHNlLCJpZCI6ImtqYWdoMXNkIiwibmFtZSI6ImxhYmVsIiwidHlwZSI6InRleHQiLCJyZXF1aXJlZCI6dHJ1ZSwicHJlc2VudGFibGUiOmZhbHNlLCJ1bmlxdWUiOmZhbHNlLCJvcHRpb25zIjp7Im1pbiI6bnVsbCwibWF4IjpudWxsLCJwYXR0ZXJuIjoiIn19XSwiaW5kZXhlcyI6WyJDUkVBVEUgVU5JUVVFIElOREVYIGBpZHhfOEJkeXJuT2AgT04gYHRhZ3NgIChgbGFiZWxgKSJdLCJsaXN0UnVsZSI6bnVsbCwidmlld1J1bGUiOm51bGwsImNyZWF0ZVJ1bGUiOm51bGwsInVwZGF0ZVJ1bGUiOm51bGwsImRlbGV0ZVJ1bGUiOm51bGwsIm9wdGlvbnMiOnt9fV0=)

**Data:**
```js
const horrorTag = await pb.collection("tags").create({
    label: "horror"
})
const dramaTag = await pb.collection("tags").create({
    label: "drama"
})

await pb.collection("movies").create({
    name: "Twilight",
    tags: [horrorTag.id, dramaTag.id]
})
```

Setting the filter to either `tags.label ?= "horror"` or `tags.label ?= "drama"` returns the `Twilight` record as expected, but setting the filter to either
- `tags.label ?= "horror" && tags.label ?= "drama"` or
- `(tags.label ?= "horror") && (tags.label ?= "drama")`

returns zero records, even though both individual expressions are true.

**Tested PocketBase versions:** `v0.22.21`, `v0.23.0-rc8`

**Collections export (from `v0.22.21`):**
```
[
    {
        "id": "8spb0rr9z2m8t9q",
        "name": "movies",
        "type": "base",
        "system": false,
        "schema": [
            {
                "system": false,
                "id": "1x3jzet7",
                "name": "name",
                "type": "text",
                "required": true,
                "presentable": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "system": false,
                "id": "hpeexvoc",
                "name": "tags",
                "type": "relation",
                "required": false,
                "presentable": false,
                "unique": false,
                "options": {
                    "collectionId": "v9pus210fyf5puf",
                    "cascadeDelete": false,
                    "minSelect": null,
                    "maxSelect": null,
                    "displayFields": null
                }
            }
        ],
        "indexes": [],
        "listRule": null,
        "viewRule": null,
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    },
    {
        "id": "v9pus210fyf5puf",
        "name": "tags",
        "type": "base",
        "system": false,
        "schema": [
            {
                "system": false,
                "id": "kjagh1sd",
                "name": "label",
                "type": "text",
                "required": true,
                "presentable": false,
                "unique": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            }
        ],
        "indexes": [
            "CREATE UNIQUE INDEX `idx_8BdyrnO` ON `tags` (`label`)"
        ],
        "listRule": null,
        "viewRule": null,
        "createRule": null,
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    }
]
``

**Comment by ganigeorgiev** [comment]
It is working as intended although I agree it may not be very intuitive.

It doesn't return results because `tags.label` targets a single row-column value it cannot be 2 different things at the same time.

For more detailed explanation you check for example https://github.com/pocketbase/pocketbase/discussions/4319.
