### ISSUE TITLE
Add a way to label collections

### ISSUE THREAD

**Issue by Anatoly03** [pocketbase/pocketbase#5743]
it would be great to label/ flag collections under one category and label them, similar to how GitHub PRs are labeled and can be filtered for tags. "auth", "view" and "base" would be default tags respectively. This would mostly be an internal feature for the admin UI.

**Comment by ganigeorgiev** [comment]
No sorry, this was discussed several times before together with collection "groups"/"directories" but for now remains out of the scope since it could clutter the UI.
