### ISSUE TITLE
Save(m models.Model) seems to be unable to persist custom models with relations

### ISSUE THREAD

**Issue by RickCastle2018** [pocketbase/pocketbase#5745]
Hi @ganigeorgiev,

I've been using PocketBase as a framework with Go. I have an extended custom model of the User, like this:

```
type User struct {
	models.BaseModel
	models.CollectionAuthOptions

	Username        string                  `db:"username" json:"username"`
	Verified        bool                    `db:"verified" json:"verified"`
	EmailVisibility bool                    `db:"emailVisibility" json:"emailVisibility"`
	Email           string                  `db:"email" json:"email"`
	Name            string                  `db:"name" json:"name"`
	Avatar          string                  `db:"avatar" json:"avatar"`
	Role            types.JsonArray[string] `db:"role" json:"role"` // Stored as JSON array
	PromoterId      string                  `db:"promoterId" json:"promoterId"`
	Topics          types.JsonArray[string] `db:"topics" json:"topics"`
	Subscriptions   types.JsonArray[string] `db:"subscriptions" json:"subscriptions"` // Stored as JSON array
	PhoneNumber     string                  `db:"phoneNumber" json:"phoneNumber"`
	LanguageCode    string                  `db:"languageCode" json:"languageCode"`
	LastPaymentId   string                  `db:"lastPaymentId" json:"lastPaymentId"`
	Sex             string                  `db:"sex" json:"sex"`
	Region          string                  `db:"region" json:"region"`
	Chats           types.JsonArray[string] `db:"chats" json:"chats"` // Stored as JSON array
}
```

Here, you can see, that Chats and Topics are Multiple Relations (as I understand, under-the-hood, it's a simple JSON field). However, when I try to save it, I get a very strange kind of error: `553237602 sql: converting argument $9 type: unsupported type []string, a slice of string`

Here's how I save it, just like in the documentation:

```
if err := app.Dao().Save(user); err != nil {
    return err
}
```

As a workaround I tried creating another struct, with those fields as strings:

```
type SaveableUser struct {
	User
	Role          string `db:"role" json:"role"`
	Topics        string `db:"topics" json:"topics"`
	Subscriptions string `db:"subscriptions" json:"subscriptions"`
	Chats         string `db:"chats" json:"chats"`
}

func SaveUser(app core.App, user *User) error {
       sUser := &SaveableUser{
		User:          *user,
		Role:          MustMarshalJSONArray(user.Role),
		Topics:        MustMarshalJSONArray(user.Topics),
		Subscriptions: MustMarshalJSONArray(user.Subscriptions),
		Chats:         MustMarshalJSONArray(user.Chats),
	}
	if err := app.Dao().Save(sUser); err != nil {
		return err
	}

	return nil
}
```

Unfortunately, this kind of solution lead to the same error as before. I wonder, if you have any ideas what may have caused it and how to fix it (even a dirty hack would be great), because, looking through the source code of Dao for a couple of hours  I didn't get close to an answer.

Thanks!

P.S. I wanted to apologize, in my comment on another issue, I did not mean to appear entitled or mean, sorry. I respect and very much value your project and especially your serious approach to it.

**Comment by RickCastle2018** [comment]
Digging deeper, it seems like the SQL driver, even though I state the JsonArray type in my struct, it takes it as []string as I had to state the elements' type (types.JsonArray[_string_]) and, therefore, does not see and does not use Value() implementation of the [driver.Valuer] interface... Still no idea on how to actually make it work, obviously there is a mistake somewhere. I would really appreciate any help :)

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/4e2a3b8d-a2ec-4710-91f7-87af358c78c7">

**Comment by ganigeorgiev** [comment]
The problem is not with the `types.JsonArray` or the `User` struct itself but the embedded [`CollectionAuthOptions`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.22.22/models#CollectionAuthOptions). You shouldn't need that and you can remove it.

There are no details why do you embed it but note that the fields of `CollectionAuthOptions` were never intended to be stored as plain column values.

In any case, this is not a PocketBase issue. For other general questions please prefer the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) as the threaded format is more suitable for this type of posts.

_Side-note: with the upcoming v0.23.0 release (_there are no ETAs yet_), custom model structs like the above one will be discouraged and instead the recommended approach for typed Record operations will be through "Record proxies"._
