### ISSUE TITLE
Question: What is the difference between OTP, MFA and Verification?

### ISSUE THREAD

**Issue by jtruter7777** [pocketbase/pocketbase#5771]
I would like to know the different between the OTP, MFA and Verification because I'm going to be setting up registration and auth as mobile, not email. 

Can `Verification` be and `OTP`?
Isn't MFA not needed if I allow users to login only via an OTP to their mobile device?

I would appreciate any answers to this question :) Thanks!

**Comment by ganigeorgiev** [comment]
@jtruter7777 Please don't spam! The Q&A discussion is the better place for this type of posts. If someone can assist you then they will answer, I personally don't understand what do you mean and I can't help you.

https://github.com/pocketbase/pocketbase/discussions/5770

**Comment by jtruter7777** [comment]
apologies, thanks for moving this.
