### ISSUE TITLE
Suggestion: Jinja2 for templates

### ISSUE THREAD

**Issue by abdulhakam** [pocketbase/pocketbase#5776]
Hi, I am a junior react frontend developer, and I have used pocketbase in some of my smaller projects (that time I only used it for auth and data) and I really love it.
I recently found that there is templates feature too! but it uses go templates which is very fast but doesn't have much advanced features. 
I would like to suggest adding jinja2 support in templates since it is quite widely used by frontend developers as jinja and some other similar libraries (I have used hubl on hubspot it is almost the same as jinja).
it will allow for an all in one solution for small to medium sized projects.

once again thank you for such an awesome project!

**Comment by ganigeorgiev** [comment]
As far as I know Jinja templates are a Python thing so it is out of the scope of the project.

There are similar Go packages like https://github.com/flosch/pongo2, but I don't want to have a hard dependency on it. Users are free to use whatever template engine they want when using PocketBase as Go framework.

With that said, I have plans for writing a new template engine from scratch for Go with minimal custom syntax and I'll consider the JSVM too, but that will be after v0.23 release.

**Comment by abdulhakam** [comment]
awesome! I was going to suggest `gonja` for it but a new template engine will also be good (I thought jinja would be more familiar to more number of web devs but I can also learn new languages anyway).

and I think instead of including jsvm inside pocketbase, there could be a single executable of deno configured similarly like pocketbase executable (loading something like `app.js` from `js_runtime` directory or something like that where app.js will point to all kinds of project code files etc. just an idea where when pocketbase is started it will look in `./` if the deno/node single file is there and will start it parallel or ignore it if its not there it will just console log about js runtime not being there or something like that)
that single executable could be a separate sister project so that pocketbase shall remain single file backend and for extended js function just download and put the executable in the same folder as pocketbase!
this will help reducing the download size for those who won't use js code.
