### ISSUE TITLE
Proposal: JSVM functionality to load more templates for an existing renderer

### ISSUE THREAD

**Issue by benstigsen** [pocketbase/pocketbase#5785]
It would be nice if it was possible to extend a renderer with more templates
```js
const renderer = $template
  .loadString(`{{ template "head.html" }}`)
  .loadFS($os.dirFS(`${__hooks}/views/partials/*.html`));
```

**Comment by ganigeorgiev** [comment]
Without details what actually is the use case and why this is needed, I'm not planning further changes to current templates helpers.

Also note that I'm planning sometime in the future to write a new Go template engine that may replace the current one and I'll consider porting it also for the JSVM.

**Comment by benstigsen** [comment]
Okay let me expand on the use-case. Allowing for adding templates like that, would make PocketBase surprisingly powerful as a CMS for something like blogs or similar. It would allow one to mix template types or allow one to more easily get templates dynamically.

A way to do this, may be to expose `.Registry()` to the JSVM, so one had more control of templates loaded.

![image](https://github.com/user-attachments/assets/1f659d3b-d866-4f17-b11a-69ee90904464)

In conjuction with this, being able to name templates would make it extremely powerful.
```js
// assume we have variable "tmpl" from collection
const renderer = $template
  .loadString(tmpl.content, tmpl.name)
  .loadFS($os.dirFS(`${__hooks}/views/partials/*.html`))
```

I understand if this isn't a priority, but the restriction of having to choose _one of_ `loadString()`, `loadFile()` or `loadFS()` makes it hard to mix the templates, depending one where one got it from.

One could add `{{ define "${tmpl.name}" }}` and `{{ end }}` to each template content dynamically, then use `loadString()`, but that doesn't seem very optimal nor clean.

I understand not wanting to generalize PocketBase too much, as it may also increase the complexity, it is just a proposal after all, you're the boss :sunglasses:
