### ISSUE TITLE
process does not restart when pb_hooks is a symbolic link

### ISSUE THREAD

**Issue by lbensaad** [pocketbase/pocketbase#5789]
Hi, when the pb_hooks folder is a symbolic link (to another folder, created by `ln -s /path/to/pb_hooks`) changing hooks files (*.pb.js)  will not cause the process to reload/restart

**Comment by ganigeorgiev** [comment]
I've pushed a small update in https://github.com/pocketbase/pocketbase/releases/tag/v0.22.23 that will account for hooksDir being a symlink.

But note that there are a lot of platform differences and edge cases around symlink (absolute vs relative paths, symlinks between different volumes/drives, etc.) so it is possible that the current fix to not cover everything.

If the above fix doesn't suffice, please elaborate a little more on your use case (why it is needed in the first place), about your environment and ideally the exact command how did you register the symlink.

**Comment by lbensaad** [comment]
thanks it is working now.
I need it because the `pb_hooks` folder is in my `src` git repo folder, but the dev db is in `/tmp/pb_dev_db`. So I just link from `/tmp/dev_db/` to my `src/pb_hooks`
