### ISSUE TITLE
[v0.23.0-rc8] Custom models don't generate ID on save

### ISSUE THREAD

**Issue by AbyssWaIker** [pocketbase/pocketbase#5790]
After the refactor `RefreshId()` method was removed from `models.BaseModel` (now `core.BaseModel`) and I assume was supposed to be moved into `PK()` method
![image](https://github.com/user-attachments/assets/c30fcc0d-a404-43b7-b900-4edc751d56f1)

But PK() method does not check `IsNew()` and always assumes that field is not empty
![image](https://github.com/user-attachments/assets/e920a394-9f72-43ac-965a-f49e4a5967f7)

I wanted to make a PR but I don't know whether the intention was to make `RefreshId()` method later, add mothod's functionality into `PK()` method or move the functionality into (future) generated code somehow.

Thanks in advance for attention

**Comment by ganigeorgiev** [comment]
_Please don't post code as screenshot; ._

With v0.23+ custom model structs will be discouraged and instead Record "proxy/projections" will be recommended (there is an overview and example in https://github.com/pocketbase/pocketbase/discussions/2697#discussioncomment-11120702). There are no plans to reintroduce `RefreshId()`.

**Comment by AbyssWaIker** [comment]
And I just had found GenerateDefaultRandomId and thought that functionality was moved there, heh

Thank you for such a quick reply

I'll look into proxy/projections

(And I will avoid using screenshots in the future)
