### ISSUE TITLE
Cron Job Fails to Delete Associated Files from a Collection

### ISSUE THREAD

**Issue by rommyarb** [pocketbase/pocketbase#5791]
Hi, I have a scheduled cron job in my app that deletes rows from the wa_chat collection that are older than 7 days. The job runs daily at 6:30 AM (GMT+7). Below is the code snippet:

`main.go`
```go
package main

import (...)

func main() {
  app := pocketbase.New()
  app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
    scheduler := cron.New()
    // DELETE OLD wa_chat RECORDS OLDER THAN 7 DAYS, EVERY DAY AT 06:30 AM (GMT+7)
    scheduler.MustAdd("delete_7days_old_wa_data_records", "30 23 * * *", func() {
      del_query := "DELETE FROM wa_chat WHERE created < datetime('now', '-7 days')"
      if _, err := app.Dao().DB().NewQuery(del_query).Execute(); err != nil {
        println("❌ Error deleting old wa_chat records.")
        panic(err)
      } else {
        println("✅ Successfully deleted old wa_chat records.")
      }
    })
    scheduler.Start()
    
  // ...
}
```
**Problem**
I recently discovered that this query only deletes the database records but does not delete the associated files stored in the wa_chat collection's file-type column. As a result, my cloud storage volume has significantly increased. Currently, the only solution I have is to manually delete the files within the `storage/` directory.

**Request**
Is there an existing solution or best practice for ensuring that related files are deleted when the corresponding database rows are removed? Any guidance or code examples would be greatly appreciated.

**Comment by ganigeorgiev** [comment]
This is working as intended

Raw queries don't have any side-effects and don't trigger hooks. They operate only with the database.

Raw SQL queries should be used with extreme care as they can leave your application in a broken state. Instead prefer working with [Record models](https://pocketbase.io/docs/go-records/) (_with v0.23.0-rc they are simplified further_).

**Comment by ganigeorgiev** [comment]
Since date operations could be a little strange with Go, below is an example for your query using the Record model (_I haven't tested it_):

```go
records := []*models.Record{}

// adjust according to your requirements
//
// with v0.23.0-rc this could be written just as
// types.NowDateTime().AddDate(0, 0, -7).String()
created := time.Now().AddDate(0, 0, -7).Format(types.DefaultDateLayout)

err := app.Dao().RecordQuery("wa_chat").
    AndWhere(dbx.NewExp("created < {:created}"), dbx.Params{ "created": created }).
    All(&records)
if err != nil {
    app.Logger().Error("Failed to fetch records to delete", "error", err)
    return
}

for _, record := range records {
    err = app.Dao().DeleteRecord(record)
    if err != nil {
        app.Logger().Error("Failed to delete old record", "recordId", record.Id, "error", err)
    }
}
```
