### ISSUE TITLE
Proposal: Add new client size function to Broker

### ISSUE THREAD

**Issue by roughbits01** [pocketbase/pocketbase#5793]
Please disregard if this is not worth it. I'm pushing a metric which holds the number of clients. Today I'm doing this `len(app.SubscriptionsBroker().Clients())` and was wondering if it makes sense to expose the Length function from the store to avoid performing a shallow copy of the entire map every time I need to get the size.

**Comment by ganigeorgiev** [comment]
This was requested before. I'll consider it with v0.23.0.

**Comment by ganigeorgiev** [comment]
Since there are plans to add eventually other fields to the Broker struct, I've named the method for now `TotalClients()` _(it is in the `develop` branch)_.
