### ISSUE TITLE
Generated types.d.ts contains compile errors

### ISSUE THREAD

**Issue by lbensaad** [pocketbase/pocketbase#5797]
Using Pocketbase v0.23.0-rc9,  I tried to use the generated `pb_data/types.d.ts` file in a typescript project but It is giving me several compile errors like 
```
91 declare function routerUse(...middlewares: Array<string|((e: core.RequestEvent) => void)|Middleware): void;
                                                                                                     ~~~           
```
is missing `>` before `):void`

also:
```
  ../../../pb/pb_data/types.d.ts:522:11
    522 interface RequestInfo extends core.RequestInfo {} // merge
                  ~~~~~~~~~~~
    'RequestInfo' was also declared here.
  ../../../pb/pb_data/types.d.ts:545:15
    545 declare class RequestInfo implements core.RequestInfo {
                      ~~~~~~~~~~~
    and here.
```

also:

```
Namespace 'os' has no exported member 'args'.
847   export let args: os.args;

```

and several other error

**Comment by ganigeorgiev** [comment]
I've pushed a small updated in the `develop` branch that should resolve the mentioned errors.

Note that even with those fixes the types are intended to be used only as ambient TS declarations to assist your editor LSP and by being autogenerated from the Go source code there situation where errors/warnings are still possible and not easy fixable.
