### ISSUE TITLE
Feature request: Batch/transactions

### ISSUE THREAD

**Issue by Ruk33** [pocketbase/pocketbase#580]
### Why?
1) It's useful to make multiple operations 
and guarantee all of them are successful.

2) Performing multiple operations with
one network call improves performance and
efficiency although this is not the primary
reason for implementing this feature (# 1 is)

### Possible API usage
```js
const response = await transaction([
    {
        operation: client.records.create,
        collection: "foo",
        bodyParams: { "bar": 42 },
        queryParams: { "baz": 0 },
    },
    {
        operation: client.records.create,
        collection: "bar",
        bodyParams: { "foo": 24 },
    },
    ...
]);

response[0] // create "foo" response
response[1] // create "bar" response
```

Only if all the operations succeed, the promise
will be resolved, otherwise, it gets rejected
and the database won't reflect any updates.

If a promise gets rejected, the error should
only display the first operation that failed.

**Comment by ganigeorgiev** [comment]
This is already planned and will be part of #48. Your proposal for the API is a good one and I may reuse some part of the suggest format. Currently there are 2 main problems that prevents us to implement this easily - how the individual collections API rules will be handled and how multipart/form-data requests will be loaded. But this will be done after the users refactoring.

You could also check this discussions - https://github.com/pocketbase/pocketbase/issues/431, https://github.com/pocketbase/pocketbase/discussions/462, https://github.com/pocketbase/pocketbase/discussions/545 for the other users similar suggestions.
