### ISSUE TITLE
Feature Request: 2FA for administrator logins on the UI

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/pocketbase#5803]
Hi there

The current login for admins on the UI does not have 2FA authentication. Having this feature ensures that even if login credentials might be compromised, the additional feature of 2FA ensures that a confirmation, whether using the built in providers for such can be used.

Thank you for consideration.

**Comment by ganigeorgiev** [comment]
There is already MFA support (email/pass + OTP) in v0.23.
