### ISSUE TITLE
Is it possible to get oauth2 providers list from backend api?

### ISSUE THREAD

**Issue by trawor** [pocketbase/pocketbase#5817]
Thanks for the great work!

I'm trying to make auth plugins for LDAP/Radius, while there are some changes from v0.23 rc that providers are moved to auth collections option from settings

So I'm not sure how to contribute my code, please give an example that how to make an oauth provider plugin
or you can just write a draft in roadmap to guide

https://github.com/pocketbase/pocketbase/blob/6694215909209b7e7d98672d0ac6c55f6c52d9a5/ui/src/components/collections/OAuth2ProvidersListPanel.svelte#L38

**Comment by ganigeorgiev** [comment]
I'm sorry but it is not clear what you are asking.

Please clarify what you are trying to do in a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a).
