### ISSUE TITLE
Feature Suggestion: Dark Mode for Admin UI and Website

### ISSUE THREAD

**Issue by GSGSDgggdzez** [pocketbase/pocketbase#5826]
Hello PocketBase Team,

I hope this message finds you well! First, I want to express my appreciation for the incredible work you’ve done with PocketBase. It’s a fantastic tool that has greatly streamlined my development process.

As I’ve been using PocketBase, I’ve noticed that many users, including myself, often work during the night. I believe that adding a dark mode option for both the admin UI and the website could significantly enhance the user experience, especially for those of us who prefer a darker interface during late-night coding sessions.

Implementing a dark mode could not only improve usability but also align with current design trends that prioritize user comfort. I would love to contribute to this feature if there’s an opportunity to do so, whether through design suggestions or development assistance.

Thank you for considering this suggestion! I look forward to your thoughts.

Best regards,  

Defree harold

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/407. It remains a very low priority for now.
