### ISSUE TITLE
db-wal files are empty in automatic backups

### ISSUE THREAD

**Issue by GhaziTriki** [pocketbase/pocketbase#5831]
Hello,

I noticed a difference between manual and automatic backups. While manual backups `*.db-wal` files are not empty, automatic backups `*.db-wal` files are 0 bytes.

Using: PocketBase v0.22.23

**Comment by ganigeorgiev** [comment]
The content of the db sidecar files will depend on whether there was a recent checkout or not, aka. it is not fixed in size (technocally it may not even exist if there is no open WAL connection).

If you are experiencing a problem try to elaborate more clearly what actually it is and ideally provide the full error, and I'll try to investigate it but until then I'm not sure how to help further.

**Comment by GhaziTriki** [comment]
Good point for the WAL.

Aside regarding network mounted storage, I am using JuiceFS->MinIO to avoid those network mount issue. But it does not resolve the Network mount issue.

S3 Backup works perfectly by the way under self-hosted MinIO.

**Comment by GhaziTriki** [comment]
I also see a `test.txt` in the backups list. Is it usual?

![image](https://github.com/user-attachments/assets/c1965732-fb0c-4f05-b371-248983386c1a)

**Comment by ganigeorgiev** [comment]
The test files are only created during the S3 storage settings check. It should be automatically deleted after a successful check (aka. you have a green label in the backups/storage settings) but many S3 providers have "versioning" or various retention policies that may interfere with it.

You can either check your S3 configuration to disable versioning/retention or just leave it as it is and it will get eventually removed by the S3 provider once the versioning/retention period expire.

**Comment by GhaziTriki** [comment]
Thanks for the heads up @ganigeorgiev. It is indeed aside a self-hosted MinIO with versionining enabled in that bucket; the retention policy will clean it up later.

Another question; I don't see how we can put the backups inside a sub-directory of the bucket. Should I open a feature request?

**Comment by ganigeorgiev** [comment]
Technically with S3 there is no such thing as directory. Everything is just part of the object key (the part that contains the "directory path" is usually referred as "prefix").

With that said there is no support for specifying extra "subdirectory"/prefix and for now remains out of the scope (see https://github.com/pocketbase/pocketbase/issues/237).

**I recommended using a different bucket for each application** to avoid conflicts or accidental deletion in case of a bug in PocketBase or the other systems that interacts with the same bucket.
