### ISSUE TITLE
Feature Request : the ability to use .env file when pocketbase is served

### ISSUE THREAD

**Issue by kyranis-studio** [pocketbase/pocketbase#5832]
It will be a good idea to be able to use .env file to configure automatically your pocketbase instances using a flag --env=path_to_env_file this is some example :
- Set default admin with email and password 
- Access to custom environment variables within the migrations files:
example :
```
migrate((db) => {
    const dao = new Dao(db);

    const admin = new Admin();
    admin.email = $env.ADMIN_EMAIL
    admin.setPassword( $env.ADMIN_PASSWORD)

    dao.saveAdmin(admin)
}, (db) => { // optional revert
    const dao = new Dao(db);

    try {
        const admin = dao.findAdminByEmail($env.ADMIN_EMAIL)

        dao.deleteAdmin(admin)
    } catch (_) { /* most likely already deleted */ }
})
```

**Comment by ganigeorgiev** [comment]
There are no plans for now to add special handling for `.env` files. You could also check https://github.com/pocketbase/pocketbase/discussions/3181#discussioncomment-6816114.
