### ISSUE TITLE
A file can become orphnaed when cloning a record with unique constraints

### ISSUE THREAD

**Issue by GhaziTriki** [pocketbase/pocketbase#5845]
Hello,

We are experiencing an issue with a table that contains two fields:

- `name` (type: varchar) with a unique constraint
- `file` (type: file)

Here is the sequence of actions leading to the issue:

1. We create a new record with `name` set as "bbb" and attach a file to it.
2. We then attempt to duplicate this record by uploading a new file while keeping the `name` field unchanged.

As expected, we receive an error due to the unique constraint on the `name` field. However, the file upload still proceeds before the constraint validation takes place, resulting in the uploaded file being stored even though the record itself is rejected. This leaves us with an uploaded file that belongs to a non-existent record and requires manual deletion.

**Suggested Solution:**
We believe this behaviour could be improved if the file upload is only executed after validating all field constraints, thereby ensuring no orphaned files are left in the system.

**Comment by ganigeorgiev** [comment]
This is already fixed in v0.23.0-rc (it is in the `develop` branch). I'll consider backporting it to v0.22 sometime later this week.

**Comment by ganigeorgiev** [comment]
I've pushed a fix in `master` and it will be available with the next minor v0.22.24 release later this week.
