### ISSUE TITLE
Data gets overwritten in Backend when not refreshed

### ISSUE THREAD

**Issue by ArneNostitz** [pocketbase/pocketbase#5851]
I just experienced a surprising behaviour. 

I made an update in data through the API. But I had the database viewer open in safari. I clicked on the updated record (without refreshing first) - the record kept the outdated data in the detail view. hitting safe overwrites the updated data. 

nothing very serious but wasn't expecting that the record data is not refreshed when I open a record in detail view.

**Comment by ganigeorgiev** [comment]
The Admin UI doesn't listen for realtime events at the moment.

This may change in the future with the planned Admin UI rewrite but I already have enough on my hands and for now this remains out of the scope.

**Comment by ArneNostitz** [comment]
I dont mean that a realtime update is needed - I was just wondering that opening the details page of a record is not reloading the data. but I know that this is probably never happening in production anyway. 

AND: this is an amazing tool already!! I enjoy it so much. so thanks

**Comment by ganigeorgiev** [comment]
> I was just wondering that opening the details page of a record is not reloading the data.

This is already how it works in v0.23.0-rc (you can inspect the requests in the live demo https://pocketbase.io/demo/) but again there are no realtime listeners at the moment and it doesn't prevent submitting updates with stale data (after I manage to complete most of the other v0.23.0 remaining tasks I'll consider at least adding a warning before save if we detect that a new version exist).
