### ISSUE TITLE
Proposal to upgrade svelte 4.x -> 5.x

### ISSUE THREAD

**Issue by Developermayank** [pocketbase/pocketbase#5853]
Request for Upgrading of svelte 4.x to 5.x for the admin ui.

**Comment by ganigeorgiev** [comment]
Please don't open issues like this or at least elaborate why that would be beneficial. Are there any issues with the current version that you are experiencing?

In any case, there are plans to rewrite the Admin UI to make it extendable but that remains a low priority for now.
