### ISSUE TITLE
onModelAfterUpdate hook blocking writes to collection

### ISSUE THREAD

**Issue by moritz4** [pocketbase/pocketbase#5881]
The `onModelAfterUpdate` hook is triggered after successfully updating an existing model in the DB. My understanding is that fields in the collection are updated, and only then is the hook is triggered once that data is written into the DB meaning that any code in the hook is run only after the record has been updated in the DB. However, I'm finding that if I write data into the DB using the admin UI, but my hook has an error in it, it prevents the data being written to the DB.

Steps:
1) Create hook in `pb_hooks` folder
```
// onModelAfterUpdate hook is triggered after successfully updating existing model in the DB.
onModelAfterUpdate((e) => {
	throw new Error("Not implemented");
}, "test_collection");
```
2) Go to Admin panel and modify existing record in the `test_collection` collection
3) Admin panel shows error: `Failed to update record.`

Please do shout if I've misunderstood the expected behaviour!

**Comment by ganigeorgiev** [comment]
The record is updated (you can refresh the admin) but the error is surfaced to the API and this is expected.
