### ISSUE TITLE
Bug: Duplicating records does not work in rc

### ISSUE THREAD

**Issue by jerebtw** [pocketbase/pocketbase#5887]
When you try to duplicate a record, you get the error `Unable to load record with id ""`.

(Bug is also in the demo)

![image](https://github.com/user-attachments/assets/9f7e7dd6-a71a-4bdf-8f9d-8985bfc7d370)

**Comment by jerebtw** [comment]
Also in views when you open a record the id is duplicated

![image](https://github.com/user-attachments/assets/6c6f0cae-ddb0-47b5-9c34-625f5b117a02)

**Comment by ganigeorgiev** [comment]
Thank you, I've submitted fix in the `develop` branch for the reported issues.

Since it is not critical or a blocker, I'll not rush another prerelease/tag for now and will leave it with the final v0.23.0.
