### ISSUE TITLE
add bluesky to oauth providers

### ISSUE THREAD

**Issue by codegod100** [pocketbase/pocketbase#5890]

**Comment by ganigeorgiev** [comment]
I'm not planning working on other OAuth2 providers but user contributions are welcomed (as an example you can refer to the recent [WakaTime](https://github.com/pocketbase/pocketbase/commit/438ecd88a059bc1e7f41be10efe28606492907a8) and [Notion](https://github.com/pocketbase/pocketbase/commit/397b69041ebc10d711c5eb4458c426168c18aa6c) prs).
