### ISSUE TITLE
Add feature of self relation in relational field

### ISSUE THREAD

**Issue by Developermayank** [pocketbase/pocketbase#5896]
Add a feature for referencing the self relational field and also provide to reference the collection id of _collections table like the feature provided in Python Django contenttype framework.

**Comment by ganigeorgiev** [comment]
@Developermayank I don't understand what you are asking for but I'm tired.

I've asked you several times to not open issues like this and to try to provide some explanation what is this feature for and how it is intended to be used but you refuse to elaborate. Please stop spamming.
