### ISSUE TITLE
Feature Change Request: Update max length of password

### ISSUE THREAD

**Issue by itsmatteomanf** [pocketbase/pocketbase#5899]
Other authentication services don't actually care about password length requirements (at the high end). Why is PocketBase limited to 71 characters?

Firebase, for example, limits it to [4096 characters](https://firebase.google.com/docs/auth/web/password-auth#policy).
Supabase doesn't list a limit, at all.

If the password is correctly stored as it seems, the hash will be of a consistent length, regardless of input length. Can the limit be raised and/or removed? I'd still put the ability to restrict it, but not force it.

**Comment by ganigeorgiev** [comment]
PocketBase uses `bcrypt` for hashing the password and it truncates after the 72byte (the last one is a reserved for the null terminator).

Technically the Go `bcrypt` implementation (and probably other) would not complain if you try to hash longer strings but it would cause wrong assumption that the entire plain password is used.

There are no plans for now to change the password hashing unless there is an actual and prominent enough use case that may require it.
