### ISSUE TITLE
min 5 mins delay response for each realtime connection web api request | subscription api response docs misleading (insights preferred if any about related delima)?!

### ISSUE THREAD

**Issue by himmat12** [pocketbase/pocketbase#59]
### base_url
![image](https://user-images.githubusercontent.com/48753714/178155198-343c8605-3e5b-4cf9-ae55-5dbddd50417d.png)

### connect api response
![image](https://user-images.githubusercontent.com/48753714/178155263-66d0b93c-5934-467c-bd6a-acdfc1536c42.png)

### subscription api response
![image](https://user-images.githubusercontent.com/48753714/178155106-67bfab72-59d4-4f3c-8839-4a7a6eb0a133.png)

**Comment by ganigeorgiev** [comment]
This indeed is not documented (I'll make sure to add it the Realtime API docs), but if your connected doesn't receive any message for 5 mins than the connection will be closed. This is done to avoid leaks by "zombie"/forgotten connections.

When using SSE in the browser, the reconnect is automatic (if the client is indeed active).
