### ISSUE TITLE
Feature Request: Immediate fetch of the requested record(s) upon subscribing to the real-time API

### ISSUE THREAD

**Issue by corentin59** [pocketbase/pocketbase#5903]
Currently, when subscribing to the real-time API, you only receive events for subsequent changes to the specified record or collection. However, there is no way to immediately fetch the current state of the requested object as part of the subscription process. This requires an additional API call to fetch the current data, which increases complexity and latency.

I propose adding an option to the realtime.subscribe method to fetch and immediately return the current state of the requested object or collection as part of the subscription flow. For example:

When subscribing to a specific record or collection:
Include an option such as fetch: true.
This triggers the immediate dispatch of an event (e.g., create or a new event type like current) with the latest state of the requested resource.

`
pb.collection("my_collection").subscribe("record_id", { fetch: true }, (event) => {
    console.log(event.action, event.data);
});
`

In this scenario, the first event received would contain the current state of the record (create or current action), followed by other real-time updates.

**Additional context**
This feature would be particularly useful in scenarios where real-time data integrity is critical, and applications need an immediate and complete view of the object or collection when subscribing. It would streamline development and reduce the number of API calls required.

**Comment by ganigeorgiev** [comment]
This was discussed in the past but there are no plans for it for the time being as it complicates a lot of things (_especially for the wildcard topic since we'll have to duplicate more or less the same implementation for pagination, sorting and filtering_).
