### ISSUE TITLE
Feature Request: One time account creation Links

### ISSUE THREAD

**Issue by Ovi1kanobe** [pocketbase/pocketbase#5904]
### THE PROBLEM
Hey I came across a problem the other week where I had an application that I only wanted specific users to access. This would require that I create accounts for each user I want to access my app. The problem was I really wanted the convenience of OAuth with platforms like google, however there is no way to directly create a user account with someone else's OAUTH credentials.  The only solution I could think of was to allow account creation with one time codes.

### FEATURE PROPOSAL
Considering There may be more applications that want to restrict the creation of their users, I think it would benefit the app to have come with this functionality built in. The way this is implemented in pocketbase is beyond my expertise and I could offer suggestions but they would most likely be far worse than anything you could come up with. I am just bringing you this suggestion because I believe it could be useful for other applications in a more restrictive environment. If you believe this is a good idea, let me know and I will do my best to help.

### HOW I SOLVED THE PROBLEM USING THE CURRENT FUNCTIONALITY

In order to work around this, I did the following:
I created this hook:
<pre> 
onRecordBeforeCreateRequest((e) => {
	const admin = $apis.requestInfo(e.httpContext).admin;
	if(!admin){
	throw new ForbiddenError("You are not authorized to perform this action");
	}
},"users");
 </pre>

This is so I can disallow user account creation for users, while still allowing it on the admin ui. Keep in mind the only reason I did not implement any logic similar to my oauth hook was because for my use case, I did not want users to create accounts with username and password.
Then I created a hook for OAuth:
<pre>
    // empty Record means that it will try to automatically create one (if it can)
    if (!e.record) {
		const code = e.httpContext.queryParam("code","null");
		
		let codeExists = false;
		const currentCodes = $app.dao().findRecordsByFilter("oneTimeAccountCreationCodes", `1=1`);

		for(let i = 0; i < currentCodes.length; i++){
			const c = currentCodes[i];
			if(c.getString("code") === code && !c.getBool("invalid")){
				codeExists = true;
				break;
			}
		}

		if(!codeExists){
			throw new ForbiddenError("Invalid code");
		}

		let expiredCode = true;
		for(let i = 0; i < currentCodes.length; i++){
			const c = currentCodes[i];
			const expirationDateStr = c.getString("expiration");
			const expirationDate = new Date(expirationDateStr);
			console.log(expirationDate);
			if(expirationDate > new Date()){
				expiredCode = false;
				c.set("invalid", true);
				$app.dao().saveRecord(c);
			}
		}

		if(expiredCode){
			throw new ForbiddenError("Code has expired");
		}
    }
</pre>
The point of these hooks is for the client to pass in a valid one-time code in the query parameter that allows their account to be created. This allows me to send emails to clients that are basically "One Time Account Creation Links"

I then created a collection for these one-time codes with the following schema:
![image](https://github.com/user-attachments/assets/b6799ad1-d360-4645-a0b4-bae25eeef069)

**Comment by Ovi1kanobe** [comment]
Thank you for your response and your feedback, I have a quick question. I initially tried it with a filter but I was scared about SQL injection because the client can put anything in the query parameter. Is it safe for me to it this way?
`` $app.dao().findFirstRecordByFilter("oneTimeAccountCreationCodes", "expiration > @now && invalid = false && code = {:code}", { code }); ``

**Comment by ganigeorgiev** [comment]
It is safe as long as it is binded as `{:code}` parameter.

Optionally if you are concerned about denial of service attacks you can add a check for the query parameter length before executing the query (e.g. `if (code.length > 300) { throw new BadRequestError() }`).
