### ISSUE TITLE
Feature Request: collection and permisions templates 

### ISSUE THREAD

**Issue by capodisseny** [pocketbase/pocketbase#5910]
Would be great to be able to create template of collections and/or api rules so you can quickly generate the database schema.
Or an json object to modify it so you can copy paste structures.

Best!

**Comment by ganigeorgiev** [comment]
It is not clear what you are asking, nor how it is expected to work.

You can export/import collections configuration from the _Dashboard > Settings > Export/Import collections_ section.

**Comment by ganigeorgiev** [comment]
No sorry, I don't plan working on this for the time being unless a more prominent use case arise.

As of now adding buttons to copy-paste rules will just clutter the UI without bringing much value because there is no guarantee that the other collection have the fields that take part of the rule.

**Comment by capodisseny** [comment]
No worries, was just an idea. Thanks for your work! 🙌
