### ISSUE TITLE
DrySubmit create rule failure: sql: no rows in result set

### ISSUE THREAD

**Issue by em-kaa** [pocketbase/pocketbase#5928]
Hi guys,
I'm new to PocketBase, and currently stuck on the API rules. I'm trying to only allow users to create a record if their id is the same as "creatorID", but I am getting "DrySubmit create rule failure: sql: no rows in result set"... let me just show you...

//API rules

![image](https://github.com/user-attachments/assets/1154920b-d74b-4823-8c31-972c5e36b32c)

//my code

```
import fs from "fs"; // Import filesystem module
import PocketBase from "pocketbase";

const pb = new PocketBase("<REDACTED>");

// Authenticate the user
await pb
  .collection("users")
  .authWithPassword("<REDACTED>", "12345678");

// Prepare form data
const formData = new FormData();
formData.append("creatorID", "dsa9myhib75uqnx");
formData.append("diena", "Vasario 22 d.");
formData.append("tipas", "ansablis");
// redacted

formData.append(
  "kurinys",
  new Blob([fs.readFileSync("./song.mp3")]),
  "song.mp3"
);

await pb.collection("anketos").create(formData);
```

(I've gotten the same error making an API create rule for users "@request.data.emailVisibility != true", but gave up.)

**Comment by em-kaa** [comment]
hm.. using "@request.auth.id = @request.data.creatorID" worked, I don't see a difference between the two but I guess I'm just dumb...

**Comment by em-kaa** [comment]
Turns out because I'm dumb and used && instead of ||

**Comment by em-kaa** [comment]
I updated the field from a text one to a relation one. Now I'm experiencing the same thing, I've tried all of these:

```
@request.auth.id = creator.id

@request.auth.id = creator

@request.auth.id = @request.body.creator

@request.auth.id = @request.body.creator.id

@request.auth.id != "" && @request.body.creator = @request.auth.id

@request.auth.id != "" && @request.body.creator.id = @request.auth.id

@request.auth.id != "" && creator.id = @request.auth.id

@request.auth.id != "" && creator = @request.auth.id

@request.auth.id != "" && (
    // I am the original creator,
    @request.auth.id = creator.id
)

@request.auth.id != "" && (
    // I am the original creator,
    @request.auth.id =@request.body.creator.id
)
```

Without any luck. Any advice?

**Comment by ganigeorgiev** [comment]
@em-kaa It is not clear what is the issue, nor what you are trying to do because you are not providing the complete code sample to understand what is the body you are submitting (_are you sure that the authenticated user id matches with the one you are submitting? what is the "redacted" data?_).

If you are trying to ensure that the submitted relation field matches the authenticated user, then the rule:

```js
@request.auth.id != "" &&
@request.auth.id = @request.data.yourRelField
```

I've just tested it locally on PocketBase v0.22.27 with the below minimal `pb_public/index.html` and it works correctly for me:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@v0.21.5/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        await pb.collection("users").authWithPassword("test@example.com", "1234567890")

        await pb.collection("example").create({
            "yourRelField": pb.authStore.model?.id
        })
    </script>
</body>
</html>
```

In any case, the threaded format of the Q&A discussions is better suited for this type of posts.

If you are still not able to identify  the culprit:
- elaborate more clearly what actually is the issue and what you are trying to do
- export your collections configuration as json (Admin UI > Settings > Export collections)
- provide more details how you are testing (what PocketBase version, what JS SDK version, where your code is running and how)
- provide a more complete code sample and standalone code sample that can trigger the error

**Comment by em-kaa** [comment]
@ganigeorgiev Thanks for your quick reply! Unfortunately, your rule didn't work.
Here's a better explanation of what I'm trying to do, 
Im trying to check, if the user creating the record linking themselves in the "creator" field, and not another user. 

Here are my collections as json..
[pb_schema (1).json](https://github.com/user-attachments/files/17951611/pb_schema.1.json)

Im using PocketBase v0.23.0, SDK is v0.22.0, and I'm using React, but I don't my code is needed in this case, but here it is anyway.

import React, { useState } from "react";

import PocketBase from "pocketbase";
const pb = new PocketBase("<redacted>");

const Anketa: React.FC = () => {
  const [form, setForm] = useState({
    creator: "53jbn4b61i592cr",
    tipas: "ansamblis",
    kolektyvo_pavadinimas: "",
    sol_vardas: "",
    sol_pavar: "",
    sol_gimim: "",
    ansa_dalyviu_skaicius: 0,
    ansa_vaiku_amziaus_vidurkis: 0,
    ansa_amziaus_kategorija: "",
    solo_amziaus_kategorija: "",
    ansa_aktyv_mic_skaicius: 0,
    ansa_neaktyv_mic_skaicius: 0,
    kurinio_pavadinimas_autoriai: "",
    kurinio_trukme_min: 0,
    kurinio_trukme_sek: 0,
    kurinys: null as File | null,
    vadv_vardas: "",
    vadv_tel: "",
    vadv_elpastas: "",
    ar_reik_sask: true,
    sask_rekv: "",
    istaigos_pavadinimas: "",
    kolektyvo_pavadinimas2: "",
    vadovo_vardas_pavard: "",
    choreografo_vardas_pavard: "",
    akompaniatoriaus_vardas_pavard: "",
    diena: "",
  });

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] || null;
    setForm({ ...form, kurinys: file });
  };

  const handleChange = (field: string, value: any) => {
    setForm({ ...form, [field]: value });
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    pb.collection("anketos").create(form);
  };

**Comment by em-kaa** [comment]
@ganigeorgiev Thanks for your quick reply! Unfortunately, your rule didn't work.
Here's a better explanation of what I'm trying to do, 
I'm trying to check if the user creating the record, links themselves in the "creator" field, and not another user. 

Here are my collections as JSON.
[pb_schema (1).json](https://github.com/user-attachments/files/17951671/pb_schema.1.json)

I'm using PocketBase v0.23.0, SDK v0.22.0, and React. I don't think my code is needed in this case, but here it is anyway.

import React, { useState } from "react";

import PocketBase from "pocketbase";
const pb = new PocketBase("<redacted>");

const Anketa: React.FC = () => {
  const [form, setForm] = useState({
    creator: "53jbn4b61i592cr",
    tipas: "ansamblis",
    kolektyvo_pavadinimas: "",
    sol_vardas: "",
    sol_pavar: "",
    sol_gimim: "",
    ansa_dalyviu_skaicius: 0,
    ansa_vaiku_amziaus_vidurkis: 0,
    ansa_amziaus_kategorija: "",
    solo_amziaus_kategorija: "",
    ansa_aktyv_mic_skaicius: 0,
    ansa_neaktyv_mic_skaicius: 0,
    kurinio_pavadinimas_autoriai: "",
    kurinio_trukme_min: 0,
    kurinio_trukme_sek: 0,
    kurinys: null as File | null,
    vadv_vardas: "",
    vadv_tel: "",
    vadv_elpastas: "",
    ar_reik_sask: true,
    sask_rekv: "",
    istaigos_pavadinimas: "",
    kolektyvo_pavadinimas2: "",
    vadovo_vardas_pavard: "",
    choreografo_vardas_pavard: "",
    akompaniatoriaus_vardas_pavard: "",
    diena: "",
  });

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] || null;
    setForm({ ...form, kurinys: file });
  };

  const handleChange = (field: string, value: any) => {
    setForm({ ...form, [field]: value });
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    pb.collection("anketos").create(form);
  }

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce with your collection and PocketBase v0.23.0. Here is a minimal `pb_public/index.html` (_I've only enabled password auth for the user collection for easier testing_):

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@v0.22.0/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        // note: enable password auth for your user collection for simplicity
        await pb.collection("users").authWithPassword("test@example.com", "1234567890")

        await pb.collection("anketos").create({
            creator:                        pb.authStore.record?.id,
            tipas:                          "ansamblis",
            kolektyvo_pavadinimas:          "test",
            sol_vardas:                     "test",
            sol_pavar:                      "test",
            sol_gimim:                      "test",
            ansa_dalyviu_skaicius:          2,
            ansa_vaiku_amziaus_vidurkis:    1,
            ansa_amziaus_kategorija:        "Iki 8 m.",
            solo_amziaus_kategorija:        "4 - 7 m.",
            ansa_aktyv_mic_skaicius:        1,
            ansa_neaktyv_mic_skaicius:      1,
            kurinio_pavadinimas_autoriai:   "test",
            kurinio_trukme_min:             1,
            kurinio_trukme_sek:             1,
            kurinys:                        "",
            vadv_vardas:                    "test",
            vadv_tel:                       "test",
            vadv_elpastas:                  "test",
            ar_reik_sask:                   true,
            sask_rekv:                      "test",
            istaigos_pavadinimas:           "test",
            kolektyvo_pavadinimas2:         "test",
            vadovo_vardas_pavard:           "test",
            choreografo_vardas_pavard:      "test",
            akompaniatoriaus_vardas_pavard: "test",
            diena:                          "Vasario 22 d.",
        })
    </script>
</body>
</html>
```

Make sure that you are authenticated before submitting the response and that the submitted data are actually what you expect. More than I can't help further.

**Comment by ganigeorgiev** [comment]
_As a side-note, I also noticed that both collections have combined `created, updated`. Avoid using composite/combined indexes if you are not sure that your query will benefit from it because it could slow down your application (see https://github.com/pocketbase/pocketbase/discussions/3859#discussioncomment-7744045)._

**Comment by ganigeorgiev** [comment]
_Also another unrelated side-note since I noticed that the `users` collection id is using a checksum from an older release candidate and not the one that comes with the stable v0.23.0 migration: as mentioned in the [v0.23.0 changelog](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md#v0230), if you had previously migrated to one of the release candidates before v0.23.0-rc14 and have a full collection snapshot migration generated, then you may have to regenerate it again to avoid conflicts when deploying on a new environment._

**Comment by em-kaa** [comment]
> I'm not able to reproduce it with your collection and PocketBase v0.23.0. Here is a minimal `pb_public/index.html` (_I've only enabled password auth for the user collection for easier testing_):
> 
> ```
> <!DOCTYPE html />
> <html>
> <head>
>     <meta charset="utf-8" />
>     <title>Test</title>
> </head>
> <body>
>     <script type="module">
>         import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@v0.22.0/dist/pocketbase.es.mjs"
> 
>         const pb = new PocketBase("http://127.0.0.1:8090");
> 
>         // note: enable password auth for your user collection for simplicity
>         await pb.collection("users").authWithPassword("test@example.com", "1234567890")
> 
>         await pb.collection("anketos").create({
>             creator:                        pb.authStore.record?.id,
>             tipas:                          "ansamblis",
>             kolektyvo_pavadinimas:          "test",
>             sol_vardas:                     "test",
>             sol_pavar:                      "test",
>             sol_gimim:                      "test",
>             ansa_dalyviu_skaicius:          2,
>             ansa_vaiku_amziaus_vidurkis:    1,
>             ansa_amziaus_kategorija:        "Iki 8 m.",
>             solo_amziaus_kategorija:        "4 - 7 m.",
>             ansa_aktyv_mic_skaicius:        1,
>             ansa_neaktyv_mic_skaicius:      1,
>             kurinio_pavadinimas_autoriai:   "test",
>             kurinio_trukme_min:             1,
>             kurinio_trukme_sek:             1,
>             kurinys:                        "",
>             vadv_vardas:                    "test",
>             vadv_tel:                       "test",
>             vadv_elpastas:                  "test",
>             ar_reik_sask:                   true,
>             sask_rekv:                      "test",
>             istaigos_pavadinimas:           "test",
>             kolektyvo_pavadinimas2:         "test",
>             vadovo_vardas_pavard:           "test",
>             choreografo_vardas_pavard:      "test",
>             akompaniatoriaus_vardas_pavard: "test",
>             diena:                          "Vasario 22 d.",
>         })
>     </script>
> </body>
> </html>
> ```
> 
> _(Adjust the above user credentials, open the browser and navigate to `http://127.0.0.1` and check the console)_
> 
> Make sure that you are authenticated before submitting the response and that the submitted data is actually what you expect. More than this I can't help further.

That worked. Thank you!
