### ISSUE TITLE
Backup view showing all bucket files including non backup files

### ISSUE THREAD

**Issue by GhaziTriki** [pocketbase/pocketbase#5933]
The backup view is currently showing all types of uploaded files in from the bucket. It should show `pocketbase` backups only. Affected versions are 0.22 & 0.23

![image](https://github.com/user-attachments/assets/be4e3dc5-19c4-466b-8291-4718b6b8b77b)

**Comment by ganigeorgiev** [comment]
It is expected if you are using the same bucket.

I recommend keeping the backups separate from your uploaded files storage (that is also the reason why there is support for 2 different S3 configs).

**Comment by GhaziTriki** [comment]
I have a feeling that I already duplicated it from a previous issue I created. Sorry if I did so. What if the config of next 0.24 prevents using the same bucket for files and backups by design?

**Comment by ganigeorgiev** [comment]
I guess it is possible to add extra validations but I don't think it is really necessary. At the end we don't store references to the backups in the database and the listing is just a convenient method utilizing the ListObjects/ListObjectsV2 S3 API, meaning that anything that you put in the bucket for which you have permissions would be visible (this includes custom backup files generated via the hooks).
