### ISSUE TITLE
v0.23.0 on page `http://127.0.0.1:8090/_/#/settings` section `Authentication` is missing

### ISSUE THREAD

**Issue by lavren1974** [pocketbase/pocketbase#5943]
![Скриншот 25-11-2024 07 11 36](https://github.com/user-attachments/assets/5250db5d-5add-44fa-b2fd-53f095dece7b)

**Comment by ganigeorgiev** [comment]
See https://github.com/pocketbase/pocketbase/discussions/5938.

The mail templates, token options and OAuth2 providers are now under each auth collection option.

**Comment by lavren1974** [comment]
Found it! It worked! Thank you!!!
