### ISSUE TITLE
Why menu auth setting is missing in v.0.23.1

### ISSUE THREAD

**Issue by maxval030** [pocketbase/pocketbase#5954]
In previous versions of PocketBase, there was a menu specifically for configuring OAuth settings. However, this menu seems to have been removed in version 0.23.1. Can you explain why?

![image](https://github.com/user-attachments/assets/3377af2a-c54a-4f86-89eb-7aa9606f986f)

**Comment by ganigeorgiev** [comment]
It is still just moved under the options for each auth collection. See https://github.com/pocketbase/pocketbase/issues/5943, https://github.com/pocketbase/pocketbase/discussions/5938.

For other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose).
