### ISSUE TITLE
Restore backups is not working

### ISSUE THREAD

**Issue by PROTAG0N1ST** [pocketbase/pocketbase#5963]
### Pocketbase v0.23.1

![Screenshot 2024-11-27 171312](https://github.com/user-attachments/assets/d4bd6311-7748-40e6-afc9-a51295f029c7)

**Comment by ganigeorgiev** [comment]
Please don't open issues without description and some steps to reproduce. How did you generate the backup? Is the backup from before PocketBase v0.23.0?

I've just tested it locally and it works fine for me. We also have integration tests that verify the correct behavior.

**Comment by ganigeorgiev** [comment]
Note that if the backup restores also the superusers and their tokens to the state available in the backup, so you may need to either relogin (e.g. if you are restoring backup from an older version) or use superuser credentials from the time the backup was generated (if you don't remember them, then you can regenerate them with `./pocketbase superuser upsert EMAIL PASS`).
