### ISSUE TITLE
Suggestion: choose default display columns to visualize relation

### ISSUE THREAD

**Issue by PatschD** [pocketbase/pocketbase#5975]
<img width="1518" alt="image" src="https://github.com/user-attachments/assets/df3d3440-a35f-43fc-a244-000cc7f530a4">
right now, when we look at the table with relations, the id is displayed by default (which can be hard to interpret). It would be cool if I could select something like a "default display column" in the admin settings, and then the table would show that instead of the ID. 
thanks for Pocketbase. it's such a cool project!

**Comment by ganigeorgiev** [comment]
You can do that already through the "Presentable" field option in the related collection.
Note that the "Presentable" currently is limited up to 2 nested level depth (it may change in the future).

**Comment by PatschD** [comment]
oh yea! thank you
