### ISSUE TITLE
Missing Email Template Settings in PocketBase 0.23.3

### ISSUE THREAD

**Issue by jonm01** [pocketbase/pocketbase#5981]
After upgrading from PocketBase 0.22.* to 0.23.2, the email template menu is missing in the Mail Settings section. My previously configured email template is still functional, but I can no longer see any options to view or update it in the admin panel.

PocketBase version: 0.23.3

**Comment by ganigeorgiev** [comment]
The default email templates, token options and OAuth2 configurations can be found under your auth collection options (this also allows having different templates and configiration per auth collection).

For other questions, please use the Q&A discussions.
