### ISSUE TITLE
Feature request: Add a hook which is triggered on record create, update or delete

### ISSUE THREAD

**Issue by moritz4** [pocketbase/pocketbase#5990]
Google Firestore has an `onWrite` hook which is triggered whenever a record is created, updated or deleted.

Currently using the pocketbase JS extension, you have to write a separate hook for each of these, and with the limitations around scope for the JS engine, this results in having to duplicate code 3 times as far as I can tell:

```js
onRecordCreate((e) => {
    // custom code
}) 

onRecordUpdate((e) => {
    // custom code
})

onRecordDelete((e) => {
    // custom code
})

```

Would it be possible to introduce a hook to capture all three of these:

```js
// Create a hook which is fired on a record create, update or deletion
onRecordWrite((e) => {
    // custom code
}) 

```

**Comment by ganigeorgiev** [comment]
No, we already have enough Record hooks and I'm against adding more unless a more prominent use case arise.
