### ISSUE TITLE
[bug] permissions for single related fields

### ISSUE THREAD

**Issue by mirus-ua** [pocketbase/pocketbase#6009]
Hello. I found an odd behavior on PocketBase v0.23.4 and JS client 0.22.0

I have two tables: `portfolios` and `portfoliosMeta`. `portfoliosMeta` has a single relation to `portfolios` and has name `portfolio`

To protect records from other users I have these permission rules 
```
@request.auth.id = @collection.portfolios.user.id && @collection.portfolios.id = @collection.portfoliosMeta.portfolio.id

// also I've tried a simplified version
@request.auth.id = @collection.portfolios.user.id && @collection.portfolios.id = portfolio
```
  and it works correctly until I add more then one portfolios - portfoliosMeta relation, and after that it drops 404

I call it like this from the client:
```ts
pb
    .collection(Collections.PortfoliosMeta)
    .getFirstListItem(`portfolio = '${portfolioId}'`, {
      expand: "portfolio",
    })
```

Also, I tried different `get` methods from the pb js client. 
Maybe it works correctly and I didn't understand the permission rules, but anyway thanks for the help in advance 

I'm not sure when it happened, but as additional information, I have one more table with the same single relation to `portfolios`

**Comment by ganigeorgiev** [comment]
It is not a bug, or at least it is not is not clear how to reproduce it.

It is also not clear for which collection is supposed the above rule to apply.

`@collection.*` and other fields that results in multiple value apply by default a "match-all" constraint. If you want "any/at-least-one" type of constraint you need to prefix the operator with `?`, for example:

```js
@request.auth.id ?= @collection.portfolios.user.id && @collection.portfolios.id ?= portfolio
```

As a general recommendation, avoid excessive use of `@collection.*` fields as it could degrade the performance of your application if not use with proper care. If all you want is to filter a specific field of a relation, then using direct dot-notation should be sufficient:

```js
@request.auth.id != "" &&
@request.auth.id = portfolio.user
```

If you have further questions, please use the Q&A discussions and paste an export of your collections configuration as json (Admin UI > Settings > Export collections).
