### ISSUE TITLE
Feature request: Job Queue

### ISSUE THREAD

**Issue by delongZhai** [pocketbase/pocketbase#601]
Hello,

I have one feature request of implementing job queue. I think there is a need for running periodic jobs, some usage may include:
- For app that rely on external data source (API, RSS) that will be updated every X minutes, it need to fetch and store some data. It may need to be managed through a schedule or can be triggered manually for local testing purposes.
- For app that need some background processing, (send out an email if condition is met or something happen)

I think that this feature will be more useful for developer who want to extend and use pocketbase as a framework, like myself.

Requirements:
- We probably need a separate DB file (jobs.db) along with data.db and logs.db
- We probably need to implement following for Pocketbase
      - Meta table: storing schedule, job id, nextTime, previousTime, maxRetry, throttling, pending_queue_size, etc.
      - Queues table: storing a history of completed jobs and pending jobs. Should also accept parameters.
      - Register DAO: create job and job metadata
      - Producer DAO: create a pending job and assign it to a queue.
      - Consumer DAO: pull pending jobs and metadata related to the queue
      - A separate command (process) to be added in addition to migrate & serve
      - Scheduler tool to be run in that command.
      - A few more Hooks?

- We probably also need the admin site to be updated, so admin can administer when the job to be run, and the maximum job to be run.

Thank you for considering.

**Comment by delongZhai** [comment]
It's okay if this isn't going to v1.0, I can work out something in my fork. Any feedback is strongly appreciated!

**Comment by ganigeorgiev** [comment]
Similar topic was discussed in https://github.com/pocketbase/pocketbase/discussions/245.

This doesn't need to be tightly integrated in PocketBase. When you use PocketBase as framework, you can combine the exported internals with any 3rd party cron library you want. At the end, PocketBase is just a Go package.

You can also register your own console commands or custom api routes. Currently the [documentation](https://pocketbase.io/docs/use-as-framework/) is a bit lacking on this, but it will be improved in the near future.
