### ISSUE TITLE
Proposal: Uniq ID and "needValidate" or custom claims on jwt token

### ISSUE THREAD

**Issue by leviia** [pocketbase/pocketbase#6034]
Hello, first of all, thanks for your work, pocketbase is just amazing.

Currently it seems to not exist a way to revocate jwt token once given to user. 

It might be great to create an uniq id and a boolean "needValidate" or to allow to add custom values in the jwt claims.

https://github.com/pocketbase/pocketbase/blob/c6695b6a75f5daa2e156facb3cd276875676b82d/core/record_tokens.go#L61

This way, in the main.go, it would be possible to create a custom endoint (ie "api_token)" like 

```go
    app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.AddRoute(echo.Route{
			Method: http.MethodPost,
			Path:   "/api_token",
			Handler: func(c echo.Context) error {
			
			[security check and get PBuser]
			
			
			// create token
		    PBtoken, toc_err := tokens.NewRecordAuthToken(app, PBuser, "NeedValidate" or custom values)
                    if toc_err != nil {
                        log.Println("error when creating token")
                        return c.JSON(http.StatusAccepted, map[string]any{
                            "error": "token not created",
                        })
                    }

                        [Save id token in database if needValidate=true]
                        
                        
                        // return token and user
				return c.JSON(http.StatusOK, map[string]any{
					"token": PBtoken,
					"user":  PBuser,
				})
			},
		})

		return nil
	})		
`

This way we save the token id (not the token itself) in the database. 
And when the token is verified (custom logic to be implemented maybe in middleware ?),
then we check if the claim "needValidate" is present and equal to true. 
If so then we check in the database (custom record) if the id of this token is still valid
(ie 'select isRevocated from customToken when id=[caimID] and userId=[claimUserId]'). 

All of this is to permit in the graphical interface to have a way for the user/customer to 
generate api tokens and be able to manage them (ie disable/enable and delete tokens).

Thanks for all 

Arnaud

**Comment by ganigeorgiev** [comment]
There are no plans for now to complicate the tokens generation.

It is not documented very well at the moment but to invalidate tokens you can:
- change the user password (this invalidates all tokens issued for the user)
- change the `tokenKey` field (this invalidates all tokens issued for the user)
- change the shared token secret from the collection option (this invalidates all type specific tokens for all users)

**Comment by leviia** [comment]
Thanks for the answer 

Instead of complicating the tokens generation, only allowing to add custom claims in token might be enouth. 

Then we can implement our own custom logic in the token (with claims and middleware) to revokate only a specific token. 

Thanks for all the hard work you do everydays 

All the best 

Arnaud

**Comment by ganigeorgiev** [comment]
>  only allowing to add custom claims in token might be enouth.

This "only" does a lot of heavy lifting. Without any details what is the use case and why this is needed in the first place, it remains out of the scope.

In any case, nothing stops you to create your own custom auth token helper - https://github.com/pocketbase/pocketbase/blob/c6695b6a75f5daa2e156facb3cd276875676b82d/core/record_tokens.go#L51.
