### ISSUE TITLE
Extended with go: Serving templates

### ISSUE THREAD

**Issue by Aaron-Ochieng** [pocketbase/pocketbase#6038]
Is there a way I can serve/parse  my own templates and  data in pocketbase ??

**Comment by ganigeorgiev** [comment]
It is not clear what you are asking or trying to do, but you could check:
- Go: https://pocketbase.io/docs/go-rendering-templates/
- JSVM: https://pocketbase.io/docs/js-rendering-templates/

For other questions, please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead but try to provide a little more details about your use case.
