### ISSUE TITLE
Required bool can't be false

### ISSUE THREAD

**Issue by Anu-cool-007** [pocketbase/pocketbase#604]
### Setup
Collection with a required boolean field.
- Trying to create a row with the boolean field as `false`
- Trying to update the `true` value to `false`

### Schema
  ```
{
      "id": "i8u0fgfr6in9y1k",
      "name": "test",
      "system": false,
      "listRule": "",
      "viewRule": "",
      "createRule": "",
      "updateRule": "",
      "deleteRule": null,
      "schema": [
          {
              "id": "n43eefv4",
              "name": "test_bool",
              "type": "bool",
              "system": false,
              "required": true,
              "unique": false,
              "options": {}
          }
      ]
  }
```

### Issue
Creating the row with the field as `false` state throws `validation_error`.
After saving the field as `true`, it can't be changed to false and throws the same `validation_error`.

**Comment by Anu-cool-007** [comment]
Discussed in https://github.com/pocketbase/pocketbase/issues/263

**Comment by ganigeorgiev** [comment]
@Anu-cool-007 This is working as intended because PocketBase doesn't have `null` values and the "Required" check is performed against the zero-default (for bool that is `false`).

You could also check discussion - https://github.com/pocketbase/pocketbase/issues/526
