### ISSUE TITLE
Several questions about oauth2

### ISSUE THREAD

**Issue by huglemon** [pocketbase/pocketbase#6042]
I hope to complete the oauth2 google login process through pocketbase.
The current project is the app router mode of next.js.

I have completed the project configuration at https://console.cloud.google.com/,
Google's client id and secret have also been configured in the pocketbase users data table.
But now the login still cannot be completed, the performance is as follows:

1. When I get providers through the interface `List auth methods (users)`, there is no redirectUri in the two url fields in the returned Google object. Is this normal?

2. When I log in through the interface `authWithOAuth2({ provider: 'google' })`, an error will be reported:
`An error occurred while loading the submitted data.`
Background display:
`json: cannot unmarshal object into Go struct field recordOAuth2LoginForm.provider of type string`

After trying to change it to `authWithOAuth2('google')`, the error remains unchanged, but the background changes to:
`{
"data": {
"code": "cannot be blank",
"redirectURL": "cannot be blank"
},
"raw": "code: cannot be blank; redirectURL: cannot be blank."
}`

I'm wondering now, why is `authWithOAuth2({ provider: 'google' })` written in the document wrong? Or is there something wrong with how I use it?
And why there is no redirectUri?

Hope to get guidance, thank you very much

**Comment by huglemon** [comment]
The version I am using is 0.23.3

**Comment by ganigeorgiev** [comment]
1. Yes, it is expected users to concatenate it when using the "Manual code exchange" flow, aka. `authWithOAuth2Code` (the second tab in https://pocketbase.io/docs/authentication/#authenticate-with-oauth2). The redirect url is automatically appended by the "All-in-one" flow (aka. `authWithOAuth2`).

2. Without more code sample that can trigger the error I cannot help you. It is not even clear what SDK you are using (JS or Dart?)

Please read the documentation https://pocketbase.io/docs/authentication/#authenticate-with-oauth2 and make sure that you are using the latest PocketBase and JS/Dart SDK versions.

In any case, the issue tracker is for this type of posts. Please use the Q&A discussions instead.

If you need further help, provide a more complete **minimal** code sample that can trigger your reported errors, elaborate more on your environment and how you are testing.

**Comment by huglemon** [comment]
Sorry, I'll post it as a discussion next time.
Then I found the problem. 
It was very strange. 
I don’t know when my pocketbase npm package changed to version 0.11. T_T
