### ISSUE TITLE
Adding files using + notation doesn't work on version 0.22.27

### ISSUE THREAD

**Issue by abbjetmus** [pocketbase/pocketbase#6049]
Hi!

Not sure if this feature was added after the version I'm using 0.22.27. But adding a file using update with + notation doesn't add the file. Although removing files using - notation works. First function returns 204, but no files are added.

```ts
        async addBrfNewsAttachments(id: string, attachments: File[]): Promise<boolean> {
            console.log(attachments)
            return pb.collection(BRF_NEWS).update(id, { 'attachments+': attachments }).then(res => {
                return true
            }).catch(e => {
                console.error(e)
                return false
            })
        },
        async removeBrfNewsAttachments(id: string, attachments: string[]): Promise<boolean> {
            return pb.collection(BRF_NEWS).update(id, { 'attachments-': attachments }).then(res => {
                return true
            }).catch(e => {
                console.error(e)
                return false
            })
        }
```

**Comment by ganigeorgiev** [comment]
The `+` prepend/append `file` modified was added with v0.23.0.

For <= v0.22.x appending a file is done with using the file name, aka. `attachments`.

For the old available modifiers, please refer to the https://pocketbase.io/old/docs/collections/#overview table.

For v0.23+ available modifies, please refer to https://pocketbase.io/docs/collections/#fields.

For other questions, please use the Q&A discussions.
