### ISSUE TITLE
Proposal: Field Show Rule

### ISSUE THREAD

**Issue by Anatoly03** [pocketbase/pocketbase#6052]
In the recent update, there's now a boolean for collection fields, `Hidden`, which explicitly hides a field. I propose the abstraction `fieldShowRule` that is executed for every field and determines whether it can be seen in a request.

Migrations:

- `Hidden` should become `null`, just like per convention, only admins can see the value.
- `Not Hidden` should become the empty string (`""`), just like per convention, the value is always shown.
- `users.email` should get the rule `emailVisibility = true`, so this behaviour of "connecting two fields" can be reproduced with other fields or omitted completely.
- `emailVisibility` should no longer be a system field, as this behaviour can be implemented with field show rules.
- `*.id` should always be the empty string (`""`) (hard coded).
- Special system fields like `password` or `tokenKey` should be explicitly hard coded to be hidden.

Use Cases / UI Ideas

- Hiding meta attributes like ban state, verify state, and various fields under access control.
- Currently a red `Hidden` label is seen in the Admin UI, this could be kept for `fieldShowRule = null`.
- A new, orange label `Restricted` label could be useful to mark fields with `fieldShowRule:length > 0`.

**Comment by ganigeorgiev** [comment]
No sorry, there are no plans for this for now as it will complicate a lot of things and could degrade the performance.

If you want to guard specific fields behind an API rule, move them into a separate collection.
