### ISSUE TITLE
Incorrect error message when writing too many characters to text field with default 'max length'

### ISSUE THREAD

**Issue by moritz4** [pocketbase/pocketbase#6053]
If I create a collection with a text field and leave the default 'max length' option (which is 5000 characters) and then try to write too many characters, the error message says that the max length allowed is 0, rather than 5000

```js
routerAdd("GET", "/test", (c) => {
	try {
		const collection = $app.findCollectionByNameOrId("myCollection");
		const record = new Record(collection, { myTextField: "A".repeat(5001) });
		$app.save(record);
	} catch (e) {
		console.error(e);
	}
});

// GoError: myTextField: Must be less than 0 character(s).
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ValidatePlainValue method in TextField to correctly display the max length in the error message when it's set to the default value of 5000.

You can review changes in this commit: https://github.com/mnmnk43434/pocketbase-pocketbase-6053/commit/7306a9ecaf37f90c33fbe09a4de54fa52f7ea38c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ganigeorgiev** [comment]
I've submitted a fix in `master` and it will be available with the next minor release.

With that said, please don't use LLM for this type of things.
