### ISSUE TITLE
JSVM documentation of `fileFromUrl` should be documented as `fileFromURL`

### ISSUE THREAD

**Issue by carlreid** [pocketbase/pocketbase#6058]
The [docs on $filesystem](https://pocketbase.io/jsvm/modules/_filesystem.html) state that to save a file from a URL, it should be called with `fileFromUrl`. It should be `fileFromURL`.

Attempting to use `fileFromUrl` will result in `object has no member 'fileFromUrl'` errors. I discovered that the casing differs, and should be `fileFromURL` after iterating over the keys of `$filesystem`;
```js
    for (const [key, value] of Object.entries($filesystem)) {
      e.app.logger().info('filesystem', 'key', key)
    }
```

As I understand it after reading other discussions, this is generated from the Go types? I do [see in these docs](https://pocketbase.io/docs/go-filesystem/#saving-files), that the correct casing of URL is used. So I assume it might be just some documentation generation problem?

In any case, nothing too major. Hopefully this issue alone might help others if they hit the same issue at least 😅

**Comment by ganigeorgiev** [comment]
Thank you. It is an issue with the generated type. I've pushed a fix for the JSVM reference documentation but the fix for ambient type declarations will be available with the next minor release sometime later next week.

**Comment by carlreid** [comment]
Thanks for the release @ganigeorgiev. Really enjoying working with PocketBase 👍
