### ISSUE TITLE
Dependency `@codemirror/autocomplete` not found on npm

### ISSUE THREAD

**Issue by btwiuse** [pocketbase/pocketbase#6061]
It seems the package has suddenly disappeared a few hours ago from npm, resulting in the following error when installing the ui dependencies:

```
[alarm@localhost ui]$ npm i
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@codemirror%2fautocomplete - Not found
npm error 404
npm error 404  '@codemirror/autocomplete@^6.0.0' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.

npm error A complete log of this run can be found in: /home/alarm/.npm/_logs/2024-12-08T18_31_53_298Z-debug-0.log
```

Visiting the https://www.npmjs.com/package/@codemirror/autocomplete page gives an empty page:

![image](https://github.com/user-attachments/assets/f5badde7-dc0c-469d-86bc-58ce2951aa05)

**Comment by ganigeorgiev** [comment]
It is possibly some temporary issue with NPM because other packages also seems to result in 404.

**Comment by ganigeorgiev** [comment]
The registry is in the process of infrastructure upgrade - https://status.npmjs.org/ (I don't recommend spamming about it and wait for the resolution of the maintenance).
