### ISSUE TITLE
Ability to add or remove hook tags from Records

### ISSUE THREAD

**Issue by OptimisticSean** [pocketbase/pocketbase#6074]
It seems like it's not possible to do it currently, or I probably missed it. Are there any plans to let the user modify Record.HookTags so that specific record does not trigger hooks registered for the tags? 

By the way, thanks for all your hard work on pocketbase!

**Comment by ganigeorgiev** [comment]
It is not clear what do you mean but note that the record hook tags are based on the the related collection id and name and it cannot change (nor I see why does it needs to).

Also note that the tags are just a convenient mechanism and it can be replaced with simply doing something like:

```go
app.OnRecordCreate().BindFunc(func(e *core.RecordEvent) error {
    if !someCondition {
        return e.Next()
    }

    ...

    return e.Next()
})
```

Feel free to open a [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) but please don't treat the issues tracker and discussions as low effort LLM chat and try to provide more details about your use case and what actually you are trying to do.
