### ISSUE TITLE
Unabled to find OTP to update its sentTo field

### ISSUE THREAD

**Issue by sadovojav** [pocketbase/pocketbase#6075]
Added MFA. Use instruction - https://pocketbase.io/docs/authentication/#multi-factor-authentication

Received: WARN Unabled to find OTP to update its sentTo field (either it was already deleted or the id is nonexisting)
![CleanShot 2024-12-10 at 13 18 47@2x](https://github.com/user-attachments/assets/aa95d4b5-1161-4993-b5cc-6d0fc43336b0)

The email was sent correctly. And has OTP code.

MFA: email + OTP

Tables in database:
_otps and _mfas is empty

Code like this:
![CleanShot 2024-12-10 at 13 24 11@2x](https://github.com/user-attachments/assets/05e79bdc-f6c8-4c6b-a198-c342ef37e1e5)

[PocketBase v0.23.5](https://github.com/pocketbase/pocketbase/releases)

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. Here is a minimal `pb_public/index.html` example:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <div id="content"></div>

    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@v0.22.1/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        try {
            await pb.collection('users').authWithPassword('test@example.com', '1234567890');
        } catch (err) {
            const mfaId = err.response?.mfaId;
            if (!mfaId) {
                throw err; // not mfa -> rethrow
            }

            // the user needs to authenticate again with another auth method, for example OTP
            const result = await pb.collection('users').requestOTP('test@example.com');

            // check your email or the console if in --dev mode
            let code = prompt("Please enter your code");

            await pb.collection('users').authWithOTP(result.otpId, code, { 'mfaId': mfaId });

            document.getElementById("content").innerText = JSON.stringify(pb.authStore.record);
        }
    </script>
</body>
</html>
```

Make sure that:
- you are testing against the correct environment
- the OTP you are targeting hasn't expired
- you don't have custom hooks that could interfere with the _mfas/_otps records creation

If you are still not able to identify the culprit, please create a **minimal** and I'll try to investigate it further but as of now it works correctly for me.

**Comment by ganigeorgiev** [comment]
Also note that in the dual screenshot, the received `otpId` from left differs from the submitted one on the right side.

**Comment by sadovojav** [comment]
> Also note that in the dual screenshot, the received `otpId` from left differs from the submitted one on the right side.

This is not important in this moment. Question about empty tables. 
I does not see any INSERT to _otps or _mfas in DB on --dev mode.

1. Does not use any hooks for _mfas
2. Duration OTP - 180s

Use PB as framework

**Comment by ganigeorgiev** [comment]
There is a cron that automatically delete expired tokens every 30mins so it is possible what the missing records in your case to be from that.

Again it works correctly for me. Please test the above minimal example and if you are still having the same issue, feel free to create your own **minimal** repo that triggers the error and I'll try to investigate it.

**Comment by sadovojav** [comment]
I found issue. This is the refactoring bug after update code  to v0.23. On some my global hook -> OnRecordCreate
return nil ---> return e.Next().
You were right about hook. I didn't finish watching
