### ISSUE TITLE
Remove special characters from API response object keys

### ISSUE THREAD

**Issue by Perceval62** [pocketbase/pocketbase#609]
# Context
Hi, I wanted to say that this is a really cool project.
I decided to take it for a quick spin by building a tiny Twitter/FB/social media clone. 

For my front end, I used Rust's Yew.rs because I wanted to learn that too.
But there was one fixable pain point that stuck out.

# Problem

When I serialized the Pocket Base Api responses I couldn't use all of Rust's excellent Serde library's full potential because there were "@" in some keys.
That didn't prevent me from serializing the rest of the keys though.

I know Rust has no officially supported SDK for PocketBase but this might be a problem for adoption and interconnection with other technologies.
 
# Replication

Make any collections in pocket base, then look at the API previews:
![image](https://user-images.githubusercontent.com/31328738/191823875-6858d274-206c-4d21-ae3e-6fdb912b231a.png)

In Rust, the code to deserialize this would look like this

```Rust
// Types of what we expect to get in the API response
#[derive(serde::Serialize, serde::Deserialize, Debug)]
pub struct PostsApiResItems{
    id: String,
    created: String,
    updated: String,
    post: String,
    author: String,
    likes: u32
}

#[derive(serde::Serialize, serde::Deserialize, Debug)]
pub struct PostsApiRes {
    page: u32,
    perPage: u32,
    totalItems: u32,
    items: Vec<PostsApiResItems>
}

/* snip later and after auth */
// Here "ret" is the returned string from any HTTP request library.
// Serde does type inference and tries to parse the given string into the structs we defined above.
// It ignores fields that are not in the structs
let res: PostsApiRes = serde_json::from_str(&ret).unwrap();
```

Since Rusts variable names are unable to contain special characters like "@" any rust code that interfaces with PocketBase 
will be unable to have access to items such as @collectionId and @collectionName. 

I haven't yet dug further for other examples of this.

From what I understand, this information is marked as such, because the request maker would know this information already at the time of the request.

Evidently This whole problem would not exist if I decided to use a mainstream loosely typed language... my bad  

# Potential Solutions

* Option A: Remove the special characters in the API object keys, this would be a breaking change :(
* Option B: Pull myself by the bootstraps and build a rust SDK that remembers information tagged like this.
* Option C: I missed something and this whole issue has no point in existing

**Comment by ganigeorgiev** [comment]
I'm not familiar with rust, but there are `rename` and `alias` attributes of serde that you could try - https://serde.rs/field-attrs.html#rename. (we do something similar in the Dart SDK - https://github.com/pocketbase/dart-sdk/blob/master/lib/src/dtos/record_model.dart#L19).

With the ongoing refactoring in #376 for v0.8.0 release, the `@collectionId`, `@collectionName` and `@expand` are already reserved field names and they no longer have the `@` prefix.

**Comment by Perceval62** [comment]
Would you guys like an eventual Rust SDK ?
Would it provide value to the pocketbase project ?
I kinda like the idea of trying it
@ganigeorgiev

**Comment by Perceval62** [comment]
Alright, thanks for the warning.
Have an excellent day!
