### ISSUE TITLE
how to access session from inside and Event Hook

### ISSUE THREAD

**Issue by a4amado** [pocketbase/pocketbase#6106]
how to access session from inside and Event Hook

```js
/// <reference path="../pb_data/types.d.ts" />

onRecordCreate((e) => {
    
  e.user ??? how to do this
    


    e.next(); // Continue with the request
}, "posts");


```

**Comment by ganigeorgiev** [comment]
There is no such field as `e.user` (if you used an llm to generate this code, please stop!).

Note also that `onRecordCreate` is a db model hook, aka. it could be triggered by a non-request context (cli, cron, when manually invoking `$app.save(record)`, etc.) and has no information about the request that may have triggered it.

For the request hooks you can check https://pocketbase.io/docs/js-event-hooks/#request-hooks. The event of a request hook inherits all RequestEvent fields and methods from https://pocketbase.io/docs/go-routing/. Or in other words:

```js
onRecordCreateRequest((e) => {
    // see https://pocketbase.io/docs/js-routing/#retrieving-the-current-auth-state
    let auth = e.auth // could be null or auth record (user, superuser, etc.)

    e.next();
}, "posts");
```

In any case, the issues tracker for this type of posts. For other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead as the threaded format is more suitable for it.

**Comment by a4amado** [comment]
The behavior I'm looking for is to ensure that the createdBy passed is equal to the user's ID, to prevent Identity Spoofing.

**Comment by ganigeorgiev** [comment]
You can do that with an API rule such as `@request.auth.id != "" && createdBy = @request.auth.id`.

You can also enforce the field value with the hook by doing something like:

```js
onRecordCreateRequest((e) => {
    if (e.hasSuperuserAuth()) {
        return e.next() // ignore for superusers
    }

    // overwrite the submitted createdBy with the id of the currently authenticated user
    e.record.set("createdBy", e.auth?.id)

    e.next();
}, "posts");
```

But again, please for other questions, use the Q&A discussions.

**Comment by a4amado** [comment]
`But again, please for other questions, use the Q&A discussions.`
oh sorry, i didn't notice it the first time.
I got used scanning the text rather than reading it
