### ISSUE TITLE
Impersonate SuperUser Token expired after 24 hours

### ISSUE THREAD

**Issue by nelreina** [pocketbase/pocketbase#6113]
Pocketbase version 0.23.4 :

I was under the impression that API Token for _superuser will be permanent / only expires when password change . 
But after doing some testing I realize that after 24 hour of creation it expired . "Error: Only superusers can perform this action". I am using Node JS Api btw...

Did not tried newer version because there is nothing about this issue mentioned in the release notes. 

I really want to use this feature for server to server communication.

**Comment by nelreina** [comment]
Ok I found out where the 24 hours are set . But still I though it was a non refteshable token

**Comment by ganigeorgiev** [comment]
It is working correctly.

The "non-refreshable" means only it can't be renewed once issued. Its duration is still limited and depend either on the collection token option or the user provided duration value.

For other questions, please use the Q&A discussions as the threaded format is more suitable for this type of posts.

**Comment by nelreina** [comment]
Thank you for your quick response , Will do Q&A discussion next time ! :)

**Comment by mojitoo2** [comment]
how can I change the token duration please ?

**Comment by nelreina** [comment]
Its easy , here are the steps

<img width="2850" height="1704" alt="Image" src="https://github.com/user-attachments/assets/134c6914-a38f-47c2-9f5a-55dfea4b831a" />

<img width="2850" height="1704" alt="Image" src="https://github.com/user-attachments/assets/8785eb47-fa18-4f03-861f-076fb0b983e3" />

<img width="984" height="1219" alt="Image" src="https://github.com/user-attachments/assets/9f452d1a-b3e9-4ba6-b953-f9e3158c8f10" />

<img width="998" height="1297" alt="Image" src="https://github.com/user-attachments/assets/ca991b7b-2077-4813-9084-45028a32d71d" />

**Comment by ganigeorgiev** [comment]
Just to clear some eventual misunderstanding, the above duration @nelreina showed in the screenshots is usually for the regular auth tokens.

Unlike regular auth tokens, impersonate auth tokens allow custom duration for each generated token during their creation:

![impersonate_popup_screenshot](https://i.imgur.com/QuDNgc0.png)

If this is is still not clear, please open a Q&A discussion elaborating what is actually the problem you are experiencing in the first place to understand better from where the misunderstanding is coming from.

**Comment by nelreina** [comment]
When I changed this field I did not have any problems with duration anymore , since I open this issue. I know you say to open a discussion , I am replying now to your comments @ganigeorgiev .  For me this was the fix for my problem ! Just to be clear I use the impersonate token !

**Comment by ganigeorgiev** [comment]
@nelreina Neither you, nor @mojitoo2 provided details how do you even generate the impersonate token in the first place.

As a last attempt to explain how it works, if no explicit duration is specified for the impersonate tokens then they fallback to their collection option duration _(this is the "Default to the collection setting" placeholder in my screenshot but I'll consider how to make it more clear in the future)_.

Or to give an example:


```dart
// create an impersonate token with custom duration
const impersonateClient = await pb.collection("_superusers").impersonate("USER_RECORD_ID", 3600)

// create an impersonate token with the auth duration in the collection options
const impersonateClient = await pb.collection("_superusers").impersonate("USER_RECORD_ID")
```

In any case, I'd advice against setting a large (e.g. more than 2 weeks duration for the regular auth tokens) in your auth collection options.

Impersonate tokens on the other hand (especially for superusers) are often used in server-server communication and in that case having a custom longer duration make sense, but again don't confuse it with the regular auth token so changing the auth token duration in the collection options in this case would be wrong.

**Comment by nelreina** [comment]
@ganigeorgiev, I don't know any other way to create  the impersonate token other then in the UI, and UI does not give the option to set a duration. I though that in the _superuser options I needed to set it. Again no where in the UI I can find it. 

I did not know that I can do this with the code. Thank you for this info!! 💯 

I use the impersonate token for server to server communication only. I use  pocketbase more for configuration of applications most of the times. I have a couple that is client based but for them Its the regular username/password or oauth2 

<img width="492" height="267" alt="Image" src="https://github.com/user-attachments/assets/2753ed72-a83d-4587-81bc-7b08c707700c" />
There is no duration option here !

**Comment by ganigeorgiev** [comment]
> There is no duration option here !

There is literally "Token duration (in seconds)" input in the popup.

I want to assist people but this is just silly.

**Comment by nelreina** [comment]
@ganigeorgiev  Yes you are correct ! This is silly . My bad I must have read over it so many times. In my mind this was where the output token  comes. Again my bad. Sorry for wasting your time ! My apologies 🙏🏾🙏🏾

**Comment by mojitoo2** [comment]
@ganigeorgiev i'am sorry but the UI is missleading
