### ISSUE TITLE
error parsing regexp: invalid escape sequence: `\u`

### ISSUE THREAD

**Issue by BaoBaoJiu** [pocketbase/pocketbase#6116]
![Screenshot 2024-12-15 213904](https://github.com/user-attachments/assets/5f6fcb2f-e6f6-443f-9e79-37d2d5960e18)

**Comment by ganigeorgiev** [comment]
This doesn't look like a valid regex expression. You can test it with https://regex101.com/ (make sure to switch to the Go flavor from the sidebar).

**Comment by chnfyi** [comment]
@BaoBaoJiu, for Go flavor you can use the `x{4e00}` notation. So you can try `^[A-Za-z0-9\x{4e00}-\x{9fa5}]+$` or with all the chinese characters `^[A-Za-z0-9\p{Han}]+$`.
