### ISSUE TITLE
API keys (Impersonate auth token) are invalidated after database migration V0.23.6

### ISSUE THREAD

**Issue by pkariuki** [pocketbase/pocketbase#6117]
To reprodue on V0.23.6

1. Generate impersonate auth token for table users.
2. Create a migration file for table (not users in my case)
3. Run ./pocketbase migrate up

The impersonate auth token does not work anymore.

**Comment by ganigeorgiev** [comment]
No sorry, this doesn't make sense.

Nevertheless I followed your steps and I'm not able to reproduce it. Make sure:

- the token hasn't expired
- you haven't changed the related user password
- you don't have a custom middleware or something else that may interfere with the token validation

Feel free to provide more details how you are testing and I'll try to investigate it further, but as of now it is working correctly for me.

**Comment by ganigeorgiev** [comment]
I forgot to mention that you can also start the executable with `--dev` to check for more detailed errors and logs in the console in addition to the ones in the _Dashboard > Logs_ section.

**Comment by ganigeorgiev** [comment]
Also note that you don't have to manually run `migrate up` and all new/unapplied migrations will execute automatically on `serve`.
