### ISSUE TITLE
Static Files not serving 

### ISSUE THREAD

**Issue by ShivvDog623** [pocketbase/pocketbase#6121]
I am having an issue with the Newest PocketBase update. The files in my pb_public won't serve with this route I am using with the new Syntax that is being used. I changed the "/*" to "/" and that worked but it will only serve my HTML file and not the CSS or JS files included in that directory! Is there a fix for this?

<img width="658" alt="Screenshot 2024-12-15 at 8 23 17 PM" src="https://github.com/user-attachments/assets/275c21b6-d732-44f8-bf84-635896598944" />

**Comment by ganigeorgiev** [comment]
You are missing the wildcard `{path...}` parameter. See https://pocketbase.io/docs/go-routing/#serving-static-directory.

Regarding the routing rules, please read https://pocketbase.io/docs/go-routing/#routes.

For other questions, please use the Q&A discussion as the threaded format is more suitable for this type of posts.

**Comment by ganigeorgiev** [comment]
Also if you are upgrading from v0.22.x to v0.23.x please follow the upgrade guide in https://pocketbase.io/v023upgrade/go/.

**Comment by ganigeorgiev** [comment]
@ShivvDog623 Please don't post the same questions in multiple places. There is an example in the linked documentations above.

**Comment by ShivvDog623** [comment]
Thanks for the help guys! I did not realize that Go used Elipsis as a wild
card path for all directories. I had thought {path...} meant that I needed
to add my own wildcard path.
