### ISSUE TITLE
Support for Multiple client_id Values for Sign in with Apple Integration

### ISSUE THREAD

**Issue by Laestry** [pocketbase/pocketbase#6151]
When integrating Sign in with Apple with Pocketbase, it’s necessary to use different client_id values for native iOS apps and web applications. Apple requires the native app to use the app’s Bundle ID as the client_id, while web integrations must use a separate Service ID. Currently, Pocketbase only allows configuring a single client_id, which creates a conflict when trying to support both native and web Sign in with Apple flows within the same Pocketbase instance.

currently this code using the package sign_in_with_apple works for me.:
```
final credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
      );

      final authData = await pb.collection('users').authWithOAuth2Code(
        'apple',
        credential.authorizationCode,
        '', // The code verifier
        redirectURL,
        createData: {
          "name": credential.givenName ?? '',
          "family": credential.familyName ?? ''
        },
      );
```
 before that I did:
```
   final authData =
          await pb.collection('users').authWithOAuth2(provider, (url) async {
        await launchUrl(url);
      });
```
During that I noticed if somebody wants to have a web and mobile app version of their app they won't be able to have apple auth0 for both of them.

**Comment by ganigeorgiev** [comment]
I'm sorry but it is not clear what is supposed to change and it seems to be too provider specific.

> wants to have a web and mobile app version

I don't know what do you mean by this and why you must have 2 different OAuth2 apps for the same provider (_maybe you want both PocketBase + the native Apple sign in?_) but usually using the web/server/etc. provider OAuth2 option should be used for the PocketBase OAuth2 integration no matter whether your app is a web, desktop or mobile.

Feel free to open a PR with your suggestion but I'm not planning working on this for now (and specifically for the Apple OAuth2 integration I don't have Apple developer account to test it; see https://github.com/pocketbase/pocketbase/discussions/5074).

**Comment by Laestry** [comment]
An example use case is having a admin dashboard using Sveltekit and the main app using Flutter. 
The issue with apple auth0 is that they require one client_id for the web version and one for the native app version if it uses the build in sign in option.
For the web it needs the com.example.name.service client id and and for the native app it uses the apps bundle id as the client id.
But I just realized you can just add another OIDC configuration, it looks like this:
| **Field**                  | **Value**                                    |
|----------------------------|----------------------------------------------|
| **Client ID**              | `com.example.name.service`         |
| **Client Secret**          | *(Your generated JWT client secret)*         |
| **Display Name**           | `Apple Web Auth`                              |
| **Auth URL**               | `https://appleid.apple.com/auth/authorize`    |
| **Token URL**              | `https://appleid.apple.com/auth/token`        |
| **Fetch user info from**   | `ID Token`                                    |
| **JWKS Verification URL**  | `https://appleid.apple.com/auth/keys`         |
| **Issuers**                | `https://appleid.apple.com`                    |
| **Support PKCE**           | `Checked`                                     |

Not sure if this needs a PR, but I imagine it be helpful to mention this in the docs? I could write something up, also I saw a lot of people asking how to use the build in sign in option. A good example in the docs could be helpful?
@ganigeorgiev

**Comment by Laestry** [comment]
just for clarification I use this approach:
```
final credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
      );

      final authData = await pb.collection('users').authWithOAuth2Code(
        'apple',
        credential.authorizationCode,
        '', // The code verifier
        redirectURL,
        createData: {
          "name": credential.givenName ?? '',
          "family": credential.familyName ?? ''
        },
      );
```
Because I don't need to open a web tab in my Flutter app to authorize the user and I can assign their name and family name, which doesn't work with authWithOAuth2Code

**Comment by ganigeorgiev** [comment]
Again, you shouldn't need that.

You should be able to use the web/server/etc. OAuth2 app option with both web and mobile.

If the main reason you are doing this is for better UX, for Flutter specifically I've used in the past https://pub.dev/packages/flutter_custom_tabs and it is almost seamless (at least based on my tests on Android).

> Because I don't need to open a web tab in my Flutter app to authorize the user and I can assign their name and family name, which doesn't work with authWithOAuth2Code

Then help me to make it work. Again, I don't have Apple developer account and I cannot test the integration on my own. The name is expected to be returned only the first time the user authorizes the Apple app. If that doesn't happen then it is possibly that the change from https://github.com/pocketbase/pocketbase/discussions/5074#discussioncomment-10318343 doesn't work the way I thought it should.

Also note that while Apple is technically an OIDC provider (_if you squint hard enough_) it comes with many peculiarities and I'm not sure I can recommend it (see https://bitbucket.org/openid/connect/src/master/How-Sign-in-with-Apple-differs-from-OpenID-Connect.md).

**Comment by Laestry** [comment]
> You should be able to use the web/server/etc. OAuth2 app option with both web and mobile.
yes it absolutely works with this approach as long as you use the service id:
```
   final authData =
          await pb.collection('users').authWithOAuth2(provider, (url) async {
        await launchUrl(url);
      });
```
But the weird part is that you need to use the apps bundle id as a client id if you want to use the build in sign in widget inside the app not in a browser. Personally I'm willing to go the extra mile for the perfect seamless experience. 
I'd love to contribute to pocketbase, but it would be my first time contributing to an opensource project. Also I've tested the OIDC provider for both the launch url and build in sign in version. They work, even though apple auth0 is defo wierd.
I'll open a PR for the fix for the change in #5074 but I currently don't see an option to add the given and family name in the users create fields map, just a combined fullName.

**Comment by ganigeorgiev** [comment]
> I currently don't see an option to add the given and family name in the users create fields map, just a combined fullName.

At the moment only the standardized fields (id, avatar, username, fullname, etc., aka. those in [`auth.AuthUser`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.23.11/tools/auth#AuthUser)) can be automapped. For any custom fields you'll have to send a manual update call with the extracted `authData.meta.rawUser` fields.

**Comment by fondoger** [comment]
Hi @Laestry. FYI, this feature is supported in my PostgreSQL fork. https://github.com/fondoger/pocketbase/commit/eed6f438c2249172d3548fd875339288ad712c8b

<img width="652" height="304" alt="Image" src="https://github.com/user-attachments/assets/8dc80413-39a0-40d9-a99c-89d6cebb92df" />
