### ISSUE TITLE
Feature request: Toggle to compress api response using gzip in admin UI

### ISSUE THREAD

**Issue by enaaab460** [pocketbase/pocketbase#6162]
I couldn't find a straightforward way of doing this using existing settings, or through hooks
is gzip middleware in routing just for html endpoints?
if not what hook should i add it to
Thanks

**Comment by ganigeorgiev** [comment]
There are no plans for this. You can try registering a global middleware and conditionally call the [builtin gzip middleware handler](https://pocketbase.io/docs/go-routing/#builtin-middlewares), something like (_I haven't tested it_):

- Go:
    ```go
    app.OnServe().BindFunc(func(se *core.ServeEvent) error {
        se.Router.BindFunc(func(e *core.RequestEvent) error {
            if strings.HasPrefix(e.Request.URL.Path, "/api/") {
                return apis.Gzip().Func(e)
            }
            return e.Next()
        })

        return se.Next()
    })
    ```

- JS:
    ```js
    routerUse((e) => {
        // conditionally invoke the gzip middleware handler
        if (e.request.url.path.startsWith("/api/")) {
            return $apis.gzip().func(e)
        }
        return e.next()
    })
    ```

For other questions, please use the Q&A discussions as the threaded format is more suitable for this type of posts.
