### ISSUE TITLE
Bug [Minor]: Changing application url in the default email templates is not reflected only when a test mail is sent from Setting -> Mail Setting

### ISSUE THREAD

**Issue by sukantamaikap** [pocketbase/pocketbase#6166]
Pre-Requisit:
Setup Email on Pocketbase. I'm using MailHog. Both MailHog and Pocketbase running as part of a docker-compose.

Steps to Reproduce

1. Customize Default Reset Password Email Template by going to Users Collection -> Edit Collection -> Option
  - Update the link for `Reset Password` button and save it. 
  - Now send a test mail from here. Receive the email and inspect the email code. You will see the button link reflects the change you made.
2. Now, go to Settings -> Mail Settings and hit `Send test email. Choose Password Reset from the template options.
3. Receive the email and inspect it. The link change is not reflected here!!

<img width="689" alt="1 Updated_Reset_Password" src="https://github.com/user-attachments/assets/5ff6ef1f-b813-404e-a999-99e4a8f99526" />

<img width="1190" alt="2 Mail_Sent_using_js_SDK" src="https://github.com/user-attachments/assets/2e03d545-2b98-4276-868d-02b1accea2f0" />

<img width="1199" alt="3 Mail_sent_from_Settings" src="https://github.com/user-attachments/assets/26f2d0a5-3fd0-4229-942e-aaa8ad1d3ce0" />

Please note, this change works just fine when an email is sent using pocketbae js sdk too.

**Comment by ganigeorgiev** [comment]
It is working correctly, although I agree that it is confusing.

Each auth collection (`users`, `_superusers`, etc.) has their own mail templates.

When sending a test email from the mailer settings we fallback to the `_superusers` collection templates.

I've added in my todo to consider eventually adding a collection picker for the mailer settings popup (_or at least mention that the template is for the `_superusers` collection_).
