### ISSUE TITLE
Proposal: Faster response for auth when the SMTP server is down

### ISSUE THREAD

**Issue by rosbiefs** [pocketbase/pocketbase#6171]
In case the SMTP server is offline, authentication takes a long time (42115ms)
I guess this is caused by the login alert. In the request log it said:
[recordAuthResponse] Failed to send login alert

This is only a minor inconvenience, but I thought it's worth noting.

Really love pocketbase BTW!

**Comment by ganigeorgiev** [comment]
This was recently discussed as part of https://github.com/pocketbase/pocketbase/issues/6152.

I've researched it and the current mailer and underlying Go std `net/smtp` package doesn't support context cancellation at the moment and a proper fix for now is left for later consideration ([task#91734790](https://github.com/orgs/pocketbase/projects/2/views/1?pane=issue&itemId=91734790)).

A temp workaround was added in the `develop` branch that will eagerly interrupt the blocking call if the auth alert email send takes longer than 15s and will be available with the next v0.24.0 release (_there are no ETAs yet_).
