### ISSUE TITLE
Error when I try to auth admins with email and pass

### ISSUE THREAD

**Issue by algo-uno-10** [pocketbase/pocketbase#6180]
Code: 

async function getAdminToken() {
        
        const authData = await pb.admins.authWithPassword(env.POCKETBASE_ADMIN, env.POCKETBASE_PASS);
        console.log('Admin Token:', authData.token);
        return authData.token;
}

Error:

  url: 'http://127.0.0.1:8090/api/collections/_superusers/auth-with-password',
  status: 404,
  response: {
    code: 404,
    message: "The requested resource wasn't found.",
    data: {}
  },
  isAbort: false,
  originalError: {
    url: 'http://127.0.0.1:8090/api/collections/_superusers/auth-with-password',
    status: 404,
    data: {
      code: 404,
      message: "The requested resource wasn't found.",
      data: {}
    }
  }
}

----

any solutions are appreciated

**Comment by ganigeorgiev** [comment]
There were several reported similar issues in the past (for example https://github.com/pocketbase/pocketbase/discussions/6110).

Make sure that the JS SDK and PocketBase versions are compatible with each other.

If you are using PocketBase executable <= v0.22.x (_you can find it in the bottom-right corner of the UI_), then the max compatible JS SDK version is [v0.21.5](https://github.com/pocketbase/js-sdk/blob/master/CHANGELOG.md#0215) (aka. < 0.22).

If you are using PocketBase executable v0.23+, then you should use JS SDK v0.22+.

You can refer to the respective CHANGELOGS for more details:

- PocketBase executable - https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md

- JS SDK - https://github.com/pocketbase/js-sdk/blob/master/CHANGELOG.md.

For other questions, please use the Q&A discussions instead.

**Comment by abhranil26** [comment]
Getting the same error when i do it via the web api!

**Comment by abhranil26** [comment]
Got it! the new endpoint is /api/collections/_superusers/auth-with-password
