### ISSUE TITLE
Unique identity fields form doesn't update when Identity/Password accordion is expanded

### ISSUE THREAD

**Issue by chnfyi** [pocketbase/pocketbase#6184]
Hi, on the dashboard we always have to expand the Identity/Password accordion to update the unique identity fields form.

If it's already expanded when a unique index is added or removed, then we need to collapse and expand another time to update the form. In this situation, _Save and continue_ doesn't update it directly either. The expected behavior would be an instant form update.

**Comment by ganigeorgiev** [comment]
I've pushed a "fix" for now in the `develop` branch as it is not a blocker or something critical.

_I'm still not entirely sure about the interactions between the indexes change and the select values (e.g. we currently on index delete the selected value is cleared) but at least now the select should show the latest extracted fields no matter of the panel open state._
