### ISSUE TITLE
Add option to skip TLS certificate verification for S3 backup endpoints

### ISSUE THREAD

**Issue by janlauber** [pocketbase/pocketbase#6185]
## Problem
When trying to connect to an S3-compatible endpoint that uses HTTPS with a self-signed or untrusted TLS certificate, the connection fails with TLS verification errors. Currently, there is no way to bypass this verification for development or testing scenarios where using such certificates is necessary.

This makes it impossible to use PocketBase with S3-compatible servers that use self-signed certificates without modifying the certificates at the system level.

## Example Error
When attempting to connect to such an endpoint, you get errors like:
![image](https://github.com/user-attachments/assets/a9838a29-b3a5-4a01-bf46-254ab4ab4b1e)

## Implementation
I'm not the best "coder" but I will try to implement something which can handle this and open up a PR.

**Comment by ganigeorgiev** [comment]
Sorry but I have no plans for this.

Similar to the SMTP related questions in regards to self-signed certificates, for me the correct solution is to properly load/install the certificates on the system where PocketBase is running and not ignore it.

**Comment by janlauber** [comment]
@ganigeorgiev 

Thank you for your feedback. First, I want to apologize for not following the proper process of discussing the feature before submitting a PR. While I followed the CONTRIBUTING.md guidelines, I should have paid more attention to the readme regarding feature discussions.

That being said, I respectfully disagree with the decision and would like to explain my reasoning:

## Security Considerations
You currently allow HTTP endpoints in the S3 configuration, which transmits data completely unencrypted. In contrast, self-signed HTTPS certificates still provide encryption, just without trusted verification. From a security perspective, this creates an interesting contradiction - allowing completely unencrypted connections (HTTP) while rejecting encrypted ones with untrusted certificates.

## Development Workflow
In modern development environments, especially in microservice architectures and containerized setups, self-signed certificates are commonly used for:

- Local development environments
- Integration testing
- Staging environments
- CI/CD pipelines

This is such a common practice that many similar tools explicitly support this scenario:
- **Velero**, a Kubernetes backup tool, includes a `--insecure-skip-tls-verify` flag specifically for handling self-signed certificates when communicating with storage backends
- **Docker** allows configuring insecure registries for development purposes, acknowledging the need for self-signed certificates in development environments
- curl, aws cli etc...

## Practical Impact
The current stance forces developers to either:
1. Use completely unencrypted HTTP connections (currently supported)
2. Modify system-level certificates for every development machine and CI runner
3. Set up and maintain a proper certificate infrastructure even for temporary testing

The first option is less secure than allowing self-signed HTTPS, while the latter two add significant overhead to development workflows.

Would you be open to reconsidering this feature specifically for non-production use cases? The implementation could include clear warnings about the security implications, similar to how the tools mentioned above handle this scenario.

**Comment by ganigeorgiev** [comment]
No sorry, I don't want this for now.
