### ISSUE TITLE
"ReferenceError: Dao is not defined" at initial migrating

### ISSUE THREAD

**Issue by Strehk** [pocketbase/pocketbase#6192]
Hey there!

I tried to deploy a docker image with pocketbase inside, but I got this error and don't know whats going on:

`Error: Failed to apply migration 1735157667_created_mission.js: ReferenceError: Dao is not defined at <eval>:65:13(109)`

I checked back in my dev environment and could reproduce the error locally after deleting my data and restarting `pocketbase serve`.

The migration in the Error Message is the very first migration created by pocketbase and I have not tinkered with a single migration – they are all generated by pocketbase and none got deleted.

Here is the content of the migration; All of the migrations as well as the codebase to reproduce can be found [here](https://github.com/Strehk/camping-manual/tree/4d098e297a4bd5c88f9910378b2027ae4cdce1a5/backend/pb_migrations).

```
/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const collection = new Collection({
    "id": "8ag64scawxr32no",
    "created": "2024-12-25 20:14:27.654Z",
    "updated": "2024-12-25 20:14:27.654Z",
    "name": "mission",
    "type": "base",
    "system": false,
    "schema": [
      {
        "system": false,
        "id": "osu0lmjv",
        "name": "title",
        "type": "text",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      },
      {
        "system": false,
        "id": "brg2bpt3",
        "name": "description",
        "type": "text",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      },
      {
        "system": false,
        "id": "qyzpk1lv",
        "name": "faIcon",
        "type": "text",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX `idx_hdeUpgC` ON `mission` (`title`)"
    ],
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "options": {}
  });

  return Dao(db).saveCollection(collection);
}, (db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("8ag64scawxr32no");

  return dao.deleteCollection(collection);
})
```

**Comment by chnfyi** [comment]
You are using PocketBase v0.23.12. Note that v0.23.0 comes with many breaking changes and requires manual migration steps. Please check the [related changelog](https://github.com/pocketbase/pocketbase/releases/tag/v0.23.0), the JSVM upgrade guide [here](https://pocketbase.io/v023upgrade/jsvm/) and the new documentation.

For example, the Dao abstraction has been removed and most of the old Dao methods are now part of the `$app` instance.

```javascript
// v0.22.x
migrate((db) => {
    const dao = new Dao(db);

    const settings = dao.findSettings()
    settings.meta.appName = "test"
    settings.logs.maxDays = 2

    dao.saveSettings(settings)
})

// v0.23+
migrate((app) => {
    const settings = app.settings()
    settings.meta.appName = "test"
    settings.logs.maxDays = 2

    app.save(settings)
})
```

**Comment by Strehk** [comment]
Thanks for the quick response!

That is weird, because I was on v0.22.x when the issue occured and only upgraded to v0.23.x today when I got stuck and thought it would maybe be an idea to upgrade and try again.

But anyway, I guess this is obsolete then anyways since dao got replaced?

For anyone having trouble with that as well, I meanwhile found a workaround:
1. make sure you have a backup of your pb instance
2. delete the `pb_data` folder
3. delete the `pb_migrations` folder
4. start the instance and restore the backup
5. run `pocketbase migrate collections` to generate a brand new migration file

**Comment by chnfyi** [comment]
For information, your issue occured when you were on v0.22.x probably because the Dao instance - `new Dao(db)` - is missing in the upgrade function.

```javascript
/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const dao = new Dao(db);
  const collection = new Collection({
    "id": "8ag64scawxr32no",
    "created": "2024-12-25 20:14:27.654Z",
    "updated": "2024-12-25 20:14:27.654Z",
    "name": "mission",
    "type": "base",
    "system": false,
    "schema": [
      {
        "system": false,
        "id": "osu0lmjv",
        "name": "title",
        "type": "text",
        "required": true,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      },
      {
        "system": false,
        "id": "brg2bpt3",
        "name": "description",
        "type": "text",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      },
      {
        "system": false,
        "id": "qyzpk1lv",
        "name": "faIcon",
        "type": "text",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX `idx_hdeUpgC` ON `mission` (`title`)"
    ],
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "options": {}
  });

  return dao.saveCollection(collection);
}, (db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("8ag64scawxr32no");

  return dao.deleteCollection(collection);
})
```

**Comment by ganigeorgiev** [comment]
@Strehk or anyone else stumble here, please read the upgrade and guide and follow the recommended upgrade steps in https://pocketbase.io/v023upgrade/jsvm/#upgrade-overview.
