### ISSUE TITLE
How to upload a very large file, such as 10G

### ISSUE THREAD

**Issue by try1995** [pocketbase/pocketbase#6193]
I saw that there was a limit on the size of upload files in the code, I modifed the limit to 10G, but the web interface upload was still wrong. my file storage is oss.

**Comment by ganigeorgiev** [comment]
I'm your but your question doesn't make sense to me.

Make sure that you are saving the correct file size (it is in bytes). Also note that the PocketBase wasn't really tested and optimized to work with very large files and I'm not sure I can recommend it for that purposes.

In any case, the issues tracker is not the place for this type of posts. Please use the Q&A discussions but try to elaborate more on the actual problem - what is your current configuration, how you are testing, what is the returned error, etc.
