### ISSUE TITLE
access client ip in record event

### ISSUE THREAD

**Issue by ramyak-mehra** [pocketbase/pocketbase#6197]
Is there an easy way to access client ips inside record event hooks, the only way i could think of is adding a middleware that sets the context with the ip and later down inside the hooks we access it though event.Context, but that doesn't seem to work either 

```golang
app.OnServe().BindFunc(func(se *core.ServeEvent) error {
		// register a global middleware
		se.Router.BindFunc(func(e *core.RequestEvent) error {

			e.Request = e.Request.WithContext(context.WithValue(e.Request.Context(), "ip_address", "{{get_ip}}"))
			return e.Next()
		})

		return se.Next()
	})```

**Comment by chnfyi** [comment]
You can read the client IPs inside hooks.
```go
// The IP of the last client connecting to your server.
// The returned IP is safe and can be always trusted.
// When behind a reverse proxy (e.g. nginx) this method returns the IP of the proxy.
// https://pkg.go.dev/github.com/pocketbase/pocketbase/tools/router#Event.RemoteIP
ip := e.RemoteIP()

// The "real" IP of the client based on the configured Settings.TrustedProxy header(s).
// If such headers are not set, it fallbacks to e.RemoteIP().
// https://pkg.go.dev/github.com/pocketbase/pocketbase/core#RequestEvent.RealIP
ip := e.RealIP()
```

**Comment by ramyak-mehra** [comment]
reading the client ip is not the issue, that i got from the docs, accessing the value inside something like RecordEvent is the issue

```golang
	app.OnRecordValidate("user_votes").BindFunc(func(e *core.RecordEvent) error {

		app.Logger().Warn(fmt.Sprintf("%+v", e.Context.Value("ip_address")))
		return e.Next()
	})

**Comment by chnfyi** [comment]
Record model hooks have no access to the request context. 

From my understanding, you'll need to :
- add an `ip_address` field to your `user_votes` collection
- extract the client IP inside a *Request hook
- access it with `record.Get("ip_address")` in your Record model hooks

**Comment by ramyak-mehra** [comment]
i need to have access to client ip before creating the record entry, so that i can add it here, can't send it from the client side

**Comment by ganigeorgiev** [comment]
Only `*Request` suffixed hook have access to the request info.

Please explore the available hook in https://pocketbase.io/docs/go-event-hooks/#request-hooks.
