### ISSUE TITLE
Documentation on user creation

### ISSUE THREAD

**Issue by carlosmpv** [pocketbase/pocketbase#620]
Hi, I loved this tool!
The only problems I had until now has been related to documentation.

![image](https://user-images.githubusercontent.com/44536711/192005833-b7a2983f-20be-4988-ba0c-9702d011dbfc.png)
On create user JS example, I was assuming that profile updating would work just as in this image when actually you have to authenticate the recently registered user in order to update its profile.

Also, even though is quite obvious the necessity of user to be authenticated in order to update profile just by checking API rules
![image](https://user-images.githubusercontent.com/44536711/192006738-f63a81f5-642d-47bb-b55e-e391a2c45fae.png)

It doesn't seem so clear on records update example
![image](https://user-images.githubusercontent.com/44536711/192006861-422b7151-41e5-4696-926c-29afe03ed0e7.png)

Thanks, have a good day!

**Comment by ganigeorgiev** [comment]
Yes, it is a little confusing at the moment. This will be resolved with the ongoing refactoring in #376.
