### ISSUE TITLE
[Bug Report] API rules fail when using hidden field

### ISSUE THREAD

**Issue by enaaab460** [pocketbase/pocketbase#6201]
I am listing a collection, and using a Search API rule to limit records to those matching the user (relation). 
`@request.auth.id = user.id`
I works fine this way.
When I set the user field to hidden, I get no records.
`{
    "data": {},
    "message": "Something went wrong while processing your request.",
    "status": 400
}`

Using Pocketbase 0.23.12 & JS-sdk
Is this expected behaviour?

**Comment by ganigeorgiev** [comment]
It is not very intuitive but it works correctly. The hidden fields checks at the moment apply when:
- the finalizer field is hidden (`user.id` is the same as `user`)
- the hidden field is NOT part of `@collection.*`, `@request.*` operand
- the request is NOT authenticated as superuser

I've added it to the roadmap to consider expanding the hidden field checks and ignore them in case it is executed as part of an API rule but this will be done eventually with the next release together with some other API changes related to https://github.com/pocketbase/pocketbase/discussions/6073.

**Comment by ganigeorgiev** [comment]
I've pushed a small experimental change in the `develop` branch that normalizes the hidden field checks, which also should allow targeting any hidden field in the List API rule.

I'll have to do a couple more tests, but if you want to check it you can clone the develop branch and build PocketBase on your own:

0. _[Install Go 1.23+](https://go.dev/doc/install) (if you haven't already)_
1. Clone the `develop` branch:
   ```sh
   git clone -b develop --single-branch https://github.com/pocketbase/pocketbase.git
   ```
2. Navigate to `examples/base`
2. Run `CGO_ENABLED=0 go build`
3. Start the created executable by running `./base serve`.
