### ISSUE TITLE
Some documentation errors in https://pocketbase.io/docs/go-collections/ and https://pocketbase.io/docs/go-migrations/. 

### ISSUE THREAD

**Issue by harrysidi** [pocketbase/pocketbase#6207]
Hello  people,
I found some minor documentation errors:

1. `&core.UrlField` need to change to  `&core.URLField` . In https://pocketbase.io/docs/go-migrations/#creating-collection-programmatically
2. `types.Pointer("id = @request.auth.id")` doesn't work on golang 1.23.4. I used:  `&[]string{"@request.auth.id != ''"}[0]`. In https://pocketbase.io/docs/go-migrations/#creating-collection-programmatically 
https://pocketbase.io/docs/go-collections/#create-new-collection
https://pocketbase.io/docs/go-collections/#update-existing-collection
https://pocketbase.io/docs/go-migrations/#creating-collection-programmatically

Warm Regards, (and Happy new year)
Harry

**Comment by ganigeorgiev** [comment]
1. I've pushed a fix for the typo.

2. `types.Pointer(...)` is correct, the migrations example is missing an import statement (`"github.com/pocketbase/pocketbase/tools/types"`).

For other docs related issues, feel free to open issues/PRs directly in the https://github.com/pocketbase/site repo.
