### ISSUE TITLE
pb.authStore.isValid is always True

### ISSUE THREAD

**Issue by fts11259375** [pocketbase/pocketbase#6208]
After the Token expires, /auth-refresh returns 401, but pb.authStore.isValid is still True

**Comment by ganigeorgiev** [comment]
Also note that the token can be considered invalid even it is not expired (e.g. in case of password change). Again, the default store `pb.authStore.isValid` only loosely check the token expiration state to determine whether to send it with the request or not but the actual token verification always happen on the server.
