### ISSUE TITLE
Superuser not showing up in users table

### ISSUE THREAD

**Issue by abacef** [pocketbase/pocketbase#6209]
I want to see the super user in the users table. I created a super user from the `./pocketbase create` command before I ever ran `./pocketbase serve`, and once it was served, I dont see the user in the table on the UI

**Comment by ganigeorgiev** [comment]
Superusers are kept in their own system auth collection `_superusers`:

![superusers_screenshot](https://i.imgur.com/OVyt42u.png).

Note that PocketBase allow more than one auth collection. Please spend some time reading the documentation and more specifically https://pocketbase.io/docs/collections/
