### ISSUE TITLE
OAuth2: Authenticate a new/existing user directly through Google Access Token

### ISSUE THREAD

**Issue by Adarsh077** [pocketbase/pocketbase#625]
### Before PocketBase: 
For google login in Flutter I use [google_sign_in](https://pub.dev/packages/google_sign_in) package for native android login experience.

Flow:
1. [google_sign_in](https://pub.dev/packages/google_sign_in) gives me a access token in flutter frontend
2. That access token is sent to our server
3. Server sends a request to google api https://www.googleapis.com/oauth2/v3/userinfo with that token.
4. User details are returned as response from the above google api.
5. Create a new user from those user details in our server
6. Create and send our user token back to client/sdk.

### PocketBase
I believe right now this is not possible in pocketbase.
Is there any chance for this to be available in pocketbase before v1.0.0?

**Comment by ganigeorgiev** [comment]
PocketBase implements the PKCE flow, which is similar to your described flow.

You can find a web example in https://pocketbase.io/docs/manage-users/#auth-via-oauth2.

I don't plan adding support for different OAuth2 grant types. There are plans to simplify the OAuth2 in https://github.com/pocketbase/pocketbase/issues/55.
