### ISSUE TITLE
Case-insensitive matching for unicode.

### ISSUE THREAD

**Issue by alex-knyaz** [pocketbase/pocketbase#627]
Hi.

Currently, LIKE operator is not case-sensitive for Unicode characters, aside from ASCII range.

According to SQLite documentation:

```
The LIKE operator does a pattern matching comparison. The operand to the right of the LIKE operator contains the 
pattern and the left hand operand contains the string to match against the pattern. A percent symbol ("%") in the LIKE 
pattern matches any sequence of zero or more characters in the string. An underscore ("_") in the LIKE pattern matches 
any single character in the string. Any other character matches itself or its lower/upper case equivalent (i.e. case-insensitive matching).

Important Note: SQLite only understands upper/lower case for ASCII characters by default. 
The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. 
For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE. 
The ICU extension to SQLite includes an enhanced version of the LIKE operator that does case folding across all unicode characters.
```

Could you consider supporting this?

**Comment by ganigeorgiev** [comment]
For now this is not planned but I may consider it in the future.

I have 2 main concerns:

1. We'll have to create custom builds of the for both https://github.com/mattn/go-sqlite3 and https://gitlab.com/cznic/sqlite (currently the ICU extension is marked as TODO and it is not loaded in the prod build config - https://gitlab.com/cznic/sqlite/-/blob/master/generator.go#L188).

2. This may increase the binary size significantly if we load the extension by default (although I haven't tested it so it may not be so bad):
    > The default configuration of SQLite only supports case-insensitive comparisons of ASCII characters. The reason for this is that doing full Unicode case-insensitive comparisons and case conversions requires tables and logic that would nearly double the size of the SQLite library. 

_I'll leave the issue out of the roadmap for now, but I'll keep it open as reminder to check it later after we manage to complete some of the other more major tasks (if you haven't already, you can check our roadmap here - https://github.com/orgs/pocketbase/projects/2)._

**Comment by alex-knyaz** [comment]
Ok, thanks for the update.

**Comment by ganigeorgiev** [comment]
I'm closing the issue for now as it will be difficult for me to maintain a fork of the custom SQLite builds it we want to have it out of the box.

If someone stumble here and needs case-insensitive unicode comparisons, you can build PocketBase on your own with `CGO_ENABLED=1` and the `sqlite_icu` tag:

0. [Install Go 1.19+](https://go.dev/doc/install) (if you haven't already)
1. Clone/download the repo
2. Navigate to examples/base
3. Run `CGO_ENABLED=1 go build -tags "sqlite_icu"`
4. Start the created executable by running `./base serve`

**Comment by ganigeorgiev** [comment]
Just for info since this problem is being reported from time to time - with PocketBase v0.23.0+ the CGO driver is no longer builtin by default _(to avoid conflicts with other CGO drivers)_ and in order to enable the ICU extension, you need to explicitly load it first like in the example https://pocketbase.io/docs/go-overview/#github-commattngo-sqlite3.

You can find steps and a complete code sample with all the `example/base/main.go` copied in https://github.com/pocketbase/pocketbase/issues/6604#issuecomment-2727445264.
