### ISSUE TITLE
Server-side computed fields

### ISSUE THREAD

**Issue by walking-octopus** [pocketbase/pocketbase#644]
Server-side computed fields can help design neater APIs, avoid client-side tampering, improve sorting, and maybe help write more complex access rules. They could be implemented as a field type where users can specify the value with a syntax similar to access rules.

**Comment by ganigeorgiev** [comment]
This is already in the roadmap and will be implemented as part of https://github.com/pocketbase/pocketbase/issues/311.

**Comment by walking-octopus** [comment]
Thanks!
