### ISSUE TITLE
[FR] Add collection from JSON

### ISSUE THREAD

**Issue by VladimirCores** [pocketbase/pocketbase#664]
Simply convert input json to collection fields from UI.

![image](https://user-images.githubusercontent.com/442111/192977575-245d56b8-3934-4169-9459-7b2571ab1401.png)

**Comment by ganigeorgiev** [comment]
You can already do this (kind of) by using the export/import collections" APIs ("Settings > Export/Import Collections" and use the "Export/Load from JSON" buttons).

But in general better import/export for both collections and records data will be handled as part of #48.

**Comment by VladimirCores** [comment]
That is a great news, thank you : )
