### ISSUE TITLE
Refused to display 'PDF_URL' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by amomesso** [pocketbase/pocketbase#677]
Hello,
I have a problem with Pdfs.
Basically i need to open the pdf saved on pocketbase inside an iframe to make it viewable on my site.
I build the url of the pdf via an api call to poketbase using the name of the pdf generated by pocketbase and the id that the api returns to me. if I open the url directly from the browser it loads it correctly while if I try to view it inside an iframe it gives me the following error: Refused to display 'PDF_URL' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
What can I do?
Thank you

I'm using PocketBase v0.7.7

**Comment by ganigeorgiev** [comment]
This is to protect from clickjacking.

I'll have to think a little more on this. Maybe we can add an exception for the files API only.

For now, if you want to allow iframe embedding in external websites, you'll have to use a reverse proxy like nginx and change the `X-Frame-Options` response header from there (eg. via the [`add_header` directive](https://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header)).

**Comment by ganigeorgiev** [comment]
An exception for the files serving api was added in `master`. The fix will be included in the next minor bugfix release v0.7.8 (sometime next week).
