### ISSUE TITLE
Please add CLIENT SDKS EXAMPLE to include filtering and sorting on multiple fields

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/pocketbase#703]
Hi

Thanks for this amazing product. Can you please add another example on the client SDK that shows how to filter & sort on multiple fields? It does not seem that its immediately clear how to do that?

I thank you.

**Comment by ganigeorgiev** [comment]
The documentation will be redesigned in the near future.

For filtering - you can multiple expression with `&&` and `||`, eg. `status = 'pending' || status = 'active'`.

For sorting - use comma as separator, eg. `created,-someField,+test`, where `-` is for DESC and `+` for ASC (this is the default and can be skipped).

**Comment by Mashiane** [comment]
Thank you so much
