### ISSUE TITLE
FR: Ability to return only specified columns with getList / getFullList

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/pocketbase#704]
Hi there

I'm wondering, in cases where you dont want the complete data-set to have all columns from your records, is it possible just to indicate which columns should be returned by a getList / getFullList?

For example, for all the records in my collection, I just want to return the ID and or another 2 additional columns, how can I do this without having to return the whole schema per record?

Thank you.

**Comment by ganigeorgiev** [comment]
This was recently discussed in https://github.com/pocketbase/pocketbase/discussions/700 and https://github.com/pocketbase/pocketbase/discussions/354.

At the moment this is not currently supported, but I may consider it for a future version.
