### ISSUE TITLE
Question: How to create a record in a collection using own id with JS SDK?

### ISSUE THREAD

**Issue by Mashiane** [pocketbase/pocketbase#707]
Hi there

Most examples I have found even from internet searches do not use an own id. Can you please advise how to achieve this?

const data = { ... }; 
const record = await client.records.create('fbpages', data);

**Comment by ganigeorgiev** [comment]
@Mashiane You can just set it as part of your `data` object, eg.:

```js
const data = {
    'id': 'YOUR_ID',
    ...
};
const record = await client.records.create('fbpages', data);
```

There are 2 caveats when dealing with custom ids:
- they can be only 15 chars string (this limitation will be removed after introducing the `IN` filter operator support)
- the ID cannot be changed after create

**Comment by Mashiane** [comment]
Thanks, I see now, I was using the same approach strangely, I think I missed something.

**Comment by Mashiane** [comment]
When you said, "If the above limitations are blocker for your use case, then you can create a custom text field, eg. customId and use that as identifier when querying records."

When performing updates and deletes, you will have to first get the ID linked to this custom field and use that for updates & delete transactions?

**Comment by ganigeorgiev** [comment]
> When performing updates and deletes, you will have to first get the ID linked to this custom field and use that for updates & delete transactions?

@Mashiane Yes, that's correct since the SDK currently doesn't support update/delete by custom filter. There will be a helper method in the future for that, but for now if you want to target a single record using a custom identifier you'll have to use something like:

```js
const result = await client.getList("fbpages", 1, 1, { filter: 'customId = "YOUR_CUSTOM_ID"' });
const record = result.items[0];

await client.records.delete("fbpages", record.id);
```

**Comment by Mashiane** [comment]
Awesome, thank you so much!
