### ISSUE TITLE
Feature Request: Allow admin to generate a JWT token for any given user

### ISSUE THREAD

**Issue by dievardump** [pocketbase/pocketbase#718]
Hi, first of all, thanks for your work, pocketbase is just amazing.

I'm mostly working with decentralized stuff (web3 etc...) where emails/password or OAuth are generally not used. 

To identify users, we use message signing with privateKey/publicKey schemes:

- user is always identified by their publicKey
- server generates a unique message and send to the user
- user "sign" this message with the corresponding private key
- server verifies message has been signed with the private key corresponding to the expected public key 
- user is identified

It can not be added as an OAuth2 provider, but what would greatly help would be to allow Admins to generate JWT tokens for any given user.

A bit like:

```js
import PocketBase from 'pocketbase';

const client = new PocketBase('http://127.0.0.1:8090');

await client.admins.authViaEmail('test@example.com', '123456');

// verify custom credentials
const userData = await verifyCredentials(request);

// generate jwt and return to user
const jwtData = await client.users.generateJWTFor(userData.id);
``` 

Then the client can auth using this jwt token.

```js
import PocketBase from 'pocketbase';

const client = new PocketBase('http://127.0.0.1:8090');

const jwt = await authCurrentUserWithSomethingElseThanEmailPassword();

// authenticate as regular user
const userData = await client.users.authWithJWT(jwt);
...

```

This would greatly simplify the task for any of us that are creating and using authentication processes that are not email/pass or OAuth2 based (I'm thinking sms-signing, username/pass, public/private key message signing, etc...)

Because for the moment, to be able to identify my users I actually have to:
- associate a completely random email address to them (we do not collect any email)
- create an endpoint that verify my custom credentials (profile.ethereumAddress, unique message, signature)
- generate a random password & update the user.password
- send back the random email & newly generated password
- identify the user with those credentials

This is not so bad, it works and does what it's expected to do, but if I could completely disable the email/password provider and just generate JWTs directly from the SDK with an Admin token, this would be really perfect and feels way less hacky (and ease the process of creating other auth schemes)

**Comment by ganigeorgiev** [comment]
@dievardump Thanks for the detailed description. Something similar was recently discussed. in https://github.com/pocketbase/pocketbase/discussions/725.

After the users refactoring from #376 and the v0.8 release, I'll consider:
- adding "user impersonate" action for admins
- adding a helper method in the SDKs to allow sending request with custom auth tokens f

**Comment by dievardump** [comment]
Thank you for your answer.

- Impersonating users for admin would be a great add for sure.

I'm not really certain to understand the custom token part though. I don't really want it custom, I just want to be able to generate a token that I can send to the front so it can be identified as the user corresponding to this token.

JWT tokens contain information, and I really don't want to mess with the information is inside this token (i.e I don't want to custom it). I just want to be able, as an admin, to generate the token 'on the go' given a user id and to be able to transfer it to the front, so it can be used.

I don't really understand how I would identify my user with id `a9an7unisc` (already in the database) with the `client.authStore` that you mentioned in #725 

How do I get the "YOUR_TOKEN" for `a9an7unisc`?

**Comment by ganigeorgiev** [comment]
@dievardump

> I'm not really certain to understand the custom token part though. I don't really want it custom, I just want to be able to generate a token that I can send to the front so it can be identified as the user corresponding to this token.

Sorry for the confusion. By "custom" I meant token that differ from the one in the AuthStore because currently in order to send an authenticated request you have to do something like this:
```js
// "authenticate" as the user associated with the token,
// but since we don't have the user data, we create a dummy object with the minimal required props
client.authStore.save(token, { verified: false })

client.records.getList("example", 1, 50);
```

In any case, the users impersonate action will provide the functionality that you want (aka. getting an auth token for a user and authenticating with it), but that will be handled after v0.8 release.

**Comment by dievardump** [comment]
That's awesome. Thank you for your availability and quick answers.

**Comment by gedw99** [comment]
This is a really useful use case for me also. 

In larger system where PocketbaE in a small part the JWT representing a User is often stored and maintained in sone global system. 

For example NATS has its own Auth system and I already am using it with Pocketbase. 

The mapping of a NATS jwt or UserID to pocketbaae is kept in NATS and when I call into Pocketbase ( via NATS ), I lookup the one stored in NATS and add it to the Context so that PocketBaae can use it. 

I just wanted to highlight this because it seems to relate to this use case, and already started working on this , so the proposed feature of this Issue is very useful to me and possibly others .

**Comment by awarebayes** [comment]
I ended up with roll-my-own JWT token, works fine:

```go
// main.go
package main

import (
	"github.com/golang-jwt/jwt/v5"
	"github.com/joho/godotenv"
	"github.com/labstack/echo/v5"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/models"
	"log"
	"os"
	"time"
)

func main() {
	_ = godotenv.Load("../.env")
	app := pocketbase.New()

	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.GET("/api/get_jwt", func(c echo.Context) error {
			// or to get the authenticated record:
			authRecord, _ := c.Get(apis.ContextAuthRecordKey).(*models.Record)
			if authRecord == nil {
				return apis.NewForbiddenError("Only auth records can access this endpoint", nil)
			}

			id := authRecord.GetId()
			username := authRecord.Username()

			token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
				"id":         id,
				"username":   username,
				"expiration": time.Now().Add(7 * 24 * time.Hour).Unix(),
			})

			privateKey := os.Getenv("ACCESS_PRIVATE_KEY")
			pkStream := []byte(privateKey)

			tokenString, err := token.SignedString(pkStream)

			if err != nil {
				return apis.NewBadRequestError("Something went wrong while signing JWT: "+err.Error(), nil)
			}

			return c.JSON(200,
				map[string]any{"token": tokenString},
			)
		})

		return nil
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by danielo515** [comment]
So, in my case I have my app already running with a custom authentication method.
My server is capable of issuing JWT tokens, how can I configure pocketbase to either:

1. Accept those tokens?
2. Let me generate a token from an admin account and send that token back to the user?

**Comment by ganigeorgiev** [comment]
`POST /api/collections/{:collection}/impersonate/{:recordId}` endpoint was implemented as part of the [ongoing refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and it will be available with the next v0.23.0 release soon (_there are no ETAs yet_).

The JS and Dart SDKs equivalent method creates a new "impersonate" client with the impersonated state loaded in. Note that the impersonate tokens are not refreshable and can have custom duration (_aka. allow also acting as static API key_):

```js
// authenticate as superusers (with v0.23.0 admins is converted to a special system auth collection "_superusers"):
await pb.collection("_superusers").authWithPassword("test@example.com", "1234567890");

// impersonate
const impersonateClient = pb.collection("users").impersonate("USER_RECORD_ID", /* specify optional token duration in seconds */)

// log the impersonate token and user data
console.log(impersonateClient.authStore.token);
console.log(impersonateClient.authStore.record);

// execute a request as the impersonated user
impersonateClient.collection("example").getFullList();
```

**Comment by danielo515** [comment]
This is awesome, thanks.
Any reason why the token is not refreshable?

**Comment by ganigeorgiev** [comment]
@gedw99 Note that the changes are not public yet.

@danielo515 Because the impersonate tokens allow custom duration and being refreshable doesn't make much sense in this case (if you want to extend an impersonate token duration you can simply generate a new one). Additionally this way we can add support for static API keys, which is a common request for server-server communication. Note also that the returned SDK impersonate client uses a non-persistent store by default (aka. the token is stored only as part of the created instance in memory) since otherwise this could conflict with the main `pb.authStore` state.

**Comment by danielo515** [comment]
Thank you for the clarifications @ganigeorgiev .
It is still not ideal, but much better than nothing. I think in the cases where I need this, I could deal with this limitations

**Comment by ElliotHYLee** [comment]
I have a separate CMS that checks whether the requested PoEcktbase JWT is valid or fake. With the impersonated token without refresh, all the backend validation fails and cannot support the user-side login from the admins. PB might need a separate token verification API  other than refresh..?

**Comment by ganigeorgiev** [comment]
@ElliotHYLee For now I remain against adding a new endpoint as it would be confusing and for most cases unnecessary. With that said, I'll consider with the next release to update the auth refresh call to not return error when an impersonate token is provided and just return the same token (aka. no `exp` claim renewal) and the latest user data associated with it.

**Comment by thelaith** [comment]
Can we implement Passkeys as a default feature in Pocketbase? Seems like an ideal usecase
