### ISSUE TITLE
Add a Homebrew formula as a goreleaser target

### ISSUE THREAD

**Issue by christophberger** [pocketbase/pocketbase#73]
Hi @ganigeorgiev and team, 

Congrats on this great project. 

I'd like to suggest adding a Homebrew formula to the release targets. This would be a convenient way of staying up to date with new releases of pocketbase.

**Comment by christophberger** [comment]
Thanks for the quick reply. I completely understand your concerns.

A while ago, I tested goreleaser and wrote a blog article about adding a Homebrew release target: [Packaging a project release (goreleaser part 2) · Applied Go](https://appliedgo.net/release2/). Maybe that helps with evaluating the long-term implications of that step.

**Comment by zuisong** [comment]
```ruby
class Pocketbase < Formula
  desc "Open Source realtime backend in 1 file"
  homepage "https://pocketbase.io/"
  url "https://github.com/pocketbase/pocketbase/archive/refs/tags/v0.6.0.tar.gz"
  sha256 "5a4e39b959697873b0e5b1b05b0edab59984e7287faf2ddb1c7be51b4b28d517"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/pocketbase/pocketbase.Version=#{version}"), "./examples/base"
  end

  test do
    assert_match "pocketbase",
       shell_output("#{bin}/pocketbase -v")
  end
end
```

**Comment by ganigeorgiev** [comment]
_Old issues cleanup: I'm closing this as I don't plan working on it. Community maintained version seems that already exists - https://formulae.brew.sh/formula/pocketbase._
