### ISSUE TITLE
Feature Proposal: Protect User Creation with Captcha

### ISSUE THREAD

**Issue by Morpheus0x** [pocketbase/pocketbase#731]
I think it would be a great feature to protect user creation with a captcha challenge.
This would require minimal changes to the user create API and to the admin dashboard.
The user create API endpoint should have an optional body parameter called captchaPasscode.
Nothing has to be added to the client SDKs, I think. Because AFAIK all bodyParams should just get passed to the PocketBase API.

If this is a wanted feature, I would be willing to implement this.
As an example, I would implement the [hCaptcha](https://docs.hcaptcha.com/) provider, since this is what I would be using.
The Pocketbase Admin panel just needs an option to select a captcha provider, if any.
Additionally, a text input field is needed for the provider account secret.

When a POST request is made to the PocketBase create user API endpoint, another post request should be made by PocketBase to the hCaptcha `/siteverify` endpoint, which verifies captchaPasscode. Depending on the response, either allow user creation or return an error.

**Comment by Morpheus0x** [comment]
Ok, sounds good. Yes, hCaptcha is API compatible with reCaptcha.

**Comment by brewhousedigital** [comment]
Want to toss this out too, Cloudflare just announced this as a privacy-focused captcha replacement

https://blog.cloudflare.com/turnstile-private-captcha-alternative/

**Comment by Morpheus0x** [comment]
Awesome, and it also seems to be API compatible

**Comment by zenomeki** [comment]
There's google's enterprise reCaptcha as well...

**Comment by mattmccray** [comment]
Is there really no better solution than the abomination of *Captcha?

Serious question, not just a vent.

**Comment by zenomeki** [comment]
> Is there really no better solution than the abomination of *Captcha?
> 
> Serious question, not just a vent.

honey-pot fields, sso, mfa, ... nothing else really...

**Comment by tigawanna** [comment]
What about the cloudflare one

**Comment by adam-ah** [comment]
> Is there really no better solution than the abomination of *Captcha?

There are alternatives, Ali and Binance both use this: completing an image by moving the missing piece in place (and verifying the X/Y error). Code example here https://pub.dev/packages/slider_captcha

**Comment by adam-ah** [comment]
Agreed @Morpheus0x, protecting the user create API is essential. Currently a two-liner bash script can cause havoc on the backend.
Captcha is unfortunately the best option for this.

Instead of changing Pocketbase, I think example code / handlers would be enough as not everyone would need the exact setup.

**Comment by danibjor** [comment]
Rate limiting those APIs could be done via the public facing reverse proxy. Would take away the wast majority of script kiddies. 

One way of doing it; https://caddyserver.com/docs/modules/http.handlers.rate_limit

**Comment by JokerQyou** [comment]
What about the admin dashboard? I can restrict access to normal APIs by using OAuth2 and disable password authentication, and enabling captcha or whatever other alternatives on the OAuth2 provider side. But the superadmin login page does not use OAuth2. So maybe the login entrance for superadmin should be secured with captcha?

**Comment by ganigeorgiev** [comment]
@JokerQyou It is not clear what you are trying to protect against but you can enable 2 factor authentication for the superusers (password + OTP) and eventually enable also the rate limiter.

In any case, please don't hijack old issues and discussions especially when they are not related to the original one.
