### ISSUE TITLE
Remove user from database does not reflected on client

### ISSUE THREAD

**Issue by VladimirCores** [pocketbase/pocketbase#733]
![Record_select-area_20221006144920](https://user-images.githubusercontent.com/442111/194305493-4444ccce-4fc7-494d-b8f1-93e4c162d2fc.gif)
Should I do user removal and cleanup of localStorage manually?

**Comment by ganigeorgiev** [comment]
PocketBase API is stateless, aka. there are no sessions (even the tokens are not stored in the database), so the client SDK has no way to know whether the token is still valid or not before making a new request to the server.

Currently you have to manually cleanup the `client.AuthStore`, but I'll consider in the next v0.8 release to do that in the background on 401 http response.

In any case, in v0.8, the users will be a regular collection and you'll be able to subscribe for realtime account changes (including deletion).

**Comment by VladimirCores** [comment]
I find a way how to check the user existance:
```js
const isUserValid = client.authStore?.isValid;
  const user = isUserValid
    ? await client.users.getOne(client.authStore.model.id).catch(() => {
        client.authStore.clear();
      })
    : null;
```
Thanks anyway ;)

**Comment by ganigeorgiev** [comment]
@VladimirCores Yep, that's one way. You can also call `client.users.refresh()` and similar to your example catch the error and clear the store.
