### ISSUE TITLE
File in Collection is not hidden from restricted users

### ISSUE THREAD

**Issue by jumper385** [pocketbase/pocketbase#743]
**Issue:**
Files in a restricted collection are not hidden away like other row entries (i.e. I can view the file from an incognito tag)
**Reproduction:**
1. Wrote an Entry 
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/17038915/194716136-2f8e34cb-4707-4a84-a205-4eee07391032.png">

Links were created to access the files 
NOTE: you can try reproduce this with this link here:
http://digism.xyz:8090/api/files/expenses/gyqca1y4hwc3nik/img_20220625_154709_bH4VnhP1zq.jpg)

2. Checked image while authenticated and not authenticated. Both times the images were viewable. When removing the file ID however, and tried to access the parent route of the original API link, I was given a 404 error.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17038915/194716404-c48b0336-2b54-446c-a3db-6825be108e6a.png">

This is accessing the file with the link

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17038915/194716432-c01afd95-6f16-47da-84af-cca5bb8e768d.png">

This is accessing the parent route of the original URL

**Question**
Is this supposed to be a feature or a problem. I'm not great with Go and Auth stuff but I can try and help out if its NodeJS stuff.

**Comment by jumper385** [comment]
You're welcome to access the site - its just a bit buggy as I've just quickly whipped it up. It's located at digism.xyz:5789

**Comment by ganigeorgiev** [comment]
Currently all uploaded files are public by default. They can be restricted only if you use PocketBase as framework.

Support for private/protected files will be added in the near future, but that will be handled after the upcoming v0.8 release.
You could subscribe to this issue https://github.com/pocketbase/pocketbase/issues/215.

An example how to implement protected file routes with a custom file token action could be found in https://github.com/pocketbase/pocketbase/discussions/254#discussioncomment-3300330.
