### ISSUE TITLE
Feature Request: Adding Microsoft AD Oauth2

### ISSUE THREAD

**Issue by WouterVandeWiele** [pocketbase/pocketbase#746]
Hi all,
Would it be possible to add Microsoft AD as an authentication option? Not sure if it is on the roadmap or a wish list.

I see there is a similar issue open for Apple Signin (#202). Past few days I had some time and was looking through the instructions provided in that thread and came up with this: https://github.com/WouterVandeWiele/pocketbase/commit/99d55f3e25a55673c4469d05e596319a934f74a2

Unfortunately I could not test it yet on a "Microsoft 365 Developer Program - E5 subscription" due to a [technical issue.](https://learn.microsoft.com/en-us/answers/questions/1035772/unable-to-setup-microsoft-365-developer-program-e5-1.html) :disappointed:

**Comment by ganigeorgiev** [comment]
This was requested previously on the support mail too.

I'll consider it for a future a release, but for now it is a low priority.

**Comment by astrojarred** [comment]
This would also be super useful for my use case. @WouterVandeWiele if you don't resolve the issue with the developer program in the next week or so let me know and I could try to help test.

**Comment by WouterVandeWiele** [comment]
@astrojarred thanks for the offer, fortunately the problem with the test tenants was solved.

So a small update: I was able to create the a test instance, register an app, create a client secret and located the auth and token endpoints to use.

Next I took the example from the documentation "[Auth via OAuth2](https://pocketbase.io/docs/manage-users/#auth-via-oauth2)" and served them locally.

- The index.html page works fine, it finds the Microsoft auth provider and when clicked redirects to the auth url
- Going through the login flow, and at the end I get redirected to the redirect.html page
- Initially on the redirect.html page, it says `Authenticating...` next the promise returns:
```
Failed to exchange code.
ClientResponseError 400: Failed to authenticate.
```
In the logs it displays: [`Missing required ExternalAuth field`](https://github.com/pocketbase/pocketbase/blob/master/daos/external_auth.go#L78), and after some investigation I saw that the ProviderId is empty.

This ProviderId seems to originating from the SQLite DB `_externalAuths` table, but when I try to inspect this table it is empty.

To try and debug this issue, I've also added google oauth. When I first login via google I can see this log message:
```
INSERT INTO `_externalAuths` (`created`, `id`, `provider`, `providerId`, `updated`, `userId`) VALUES ...
```
But nothing similar shows up when authenticating with the Microsoft user ☹️ 

So I'm currently trying to find out why the microsoft auth provider is not creating an entry.

**Comment by ganigeorgiev** [comment]
@WouterVandeWiele `ExternalAuths.ProviderId` is the ID that is returned from the provider's `FetchAuthUser` call, so make sure that you've properly mapped the Microsoft API response to the AuthUser struct.

**Comment by WouterVandeWiele** [comment]
@ganigeorgiev thanks, that was it. Now it works :smile: 

- the userApiUrl should have been https://graph.microsoft.com/v1.0/me
- the json was not properly parsed. Maybe this Microsoft Graph explorer might help somebody in the future:
https://developer.microsoft.com/en-us/graph/graph-explorer

Awaiting #376 to make a pull request.

**Comment by astrojarred** [comment]
@WouterVandeWiele That's great news, congrats and thanks for the hard work. I'm looking forward to making good use of your PR.

**Comment by ganigeorgiev** [comment]
@WouterVandeWiele Just to let you know that I've just pushed a v0.8.0 pre-release, so feel free when you find time to make a PR against the `rc` branch (https://github.com/pocketbase/pocketbase/tree/rc) and I'll review it.

**Comment by WouterVandeWiele** [comment]
Ok, I merged the changes and tested it again on the Azure test instance. Small remark is to update the documentation code samples (if not already on the to-do list), because the SDK interface slightly changed.

E.g.: [Auth via OAuth2](https://pocketbase.io/docs/manage-users/#auth-via-oauth2)
In the links page example: 
`const authMethods = await client.users.listAuthMethods();` changed to `const authMethods = await client.collection('users').listAuthMethods();` and similarly for the Redirect handler page.

On the redirect page, maybe it is also nice to show how to handle a refresh? e.g.:
```javascript
// parse the query parameters from the redirected url
const params = (new URL(window.location)).searchParams;

// load the previously stored provider's data
const provider = JSON.parse(localStorage.getItem('provider'))

// compare the redirect's state param and the stored provider's one
if (provider.state !== params.get("state")) {
    throw "State parameters don't match.";
}

// (re)authenticate and fetch user data via user api url
if (client.authStore.isValid == true) {
    // auth refresh
    client.collection('users').authRefresh(
    ).then((authData) => {
        document.getElementById("content").innerText = JSON.stringify(authData, null, 2);
    }).catch((err) => {
        document.getElementById("content").innerText = "Failed to exchange code.\n" + err;
    });
} else {
    // authenticate
    client.collection('users').authWithOAuth2(
        provider.name,
        params.get("code"),
        provider.codeVerifier,
        redirectUrl
    ).then((authData) => {
        document.getElementById("content").innerText = JSON.stringify(authData, null, 2);
    }).catch((err) => {
        document.getElementById("content").innerText = "Failed to exchange code.\n" + err;
    });
}

```

**Comment by ganigeorgiev** [comment]
@WouterVandeWiele Thank you, I'll review and test the PR later today. The site documentation is still for v0.7.9 and this week I'll start working on adapting it for the v0.8 changes (including simplifying the site code so that it can be open sourced and edited by contributors).

I'm not sure that I understand the refresh example though. I think it will be confusing to have it in the redirect and it's better to keep the example minimal. In addition, with v0.8 there is also support for "logged user linking" (there will be documentation for that), which means that now it is possible to allow linking an already authenticated app user with the OAuth2 account even if it return a different email address, eg.:

```js
// authenticate
client.collection('users').authWithPassword("test@example.com", "123456");

// if this is the first time OAuth2 authenticating, link the authenticated OAuth2 account to the previous authenticated user (only if not associated already to another account!)
client.collection('users').authWithOAuth2(...);
```

**Comment by WouterVandeWiele** [comment]
Ah, I think I'm masking a problem with the re-authentication and/or reloading.

The first time going through the OAuth login sequence, the redirect page correctly displays the response of `client.collection('users').authWithOAuth2(...)`, but when I reload the redirect page it displays:

```
Failed to exchange code.
ClientResponseError 400: Failed to authenticate.
```

Pocketbase logs displays a message for url `/api/collections/users/auth-with-oauth2` with Meta:
```
{
  "errorDetails": "oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\\r\\nTrace ID: <id>\\r\\nCorrelation ID: <id>\\r\\nTimestamp: 2022-10-31 10:38:43Z\",\"error_codes\":[54005],\"timestamp\":\"2022-10-31 10:38:43Z\",\"trace_id\":\"<id>\",\"correlation_id\":\"<id>\"}",
  "errorMessage": "Failed to authenticate."
}
```
When trying with the code snipped that rechecks authentication (via `(client.authStore.isValid == true)`) the authWithOAuth2 record displayed each time the redirect page is reloaded.

**Comment by ganigeorgiev** [comment]
The Microsoft provider is merged in the `rc` branch and it will be available with the final v0.8.0 release.

**Comment by ganigeorgiev** [comment]
@jkdoshi Hm, this looks similar to https://github.com/pocketbase/js-sdk/issues/176.

You can check the suggestions from https://github.com/pocketbase/js-sdk/issues/176#issuecomment-1486604357.

I'll create a trial Microsoft dev account and will investigate it sometime later this week.

**Comment by ganigeorgiev** [comment]
@jkdoshi I've just tested with a demo azure account and indeed the email is returned as `null` in the auth response (you can verify it by inspecting the `meta.rawUser.mail` auth response field).

I suspect that there is something additional that needs to be configured in the OAuth2 app, but I'm not very familiar with the Microsoft ecosystem and can't say for sure what are the requirements to return the email in the `meta.rawUser.mail` field (_note that it is returned in `meta.rawUser.userPrincipalName` but as far as I understand this is just the sign-in identifier and it could be something else, eg. an username_).

You can also try to authenticate and run the `/v1.0/me` query in the graph explorer and see if the `mail` field will be set - https://developer.microsoft.com/en-us/graph/graph-explorer.

Alternatively, you can also try to use the generic OpenID connect provider (`oidc`) since Azure AD seems to support it (you'll need to enable the `openid`, `email` and `profile` scopes/permissions for your Microsoft OAuth2 app).

**Comment by jkdoshi** [comment]
Just got Oauth2 with Microsoft fully working (including getting user's email), so I wanted post an update here.

See my comment [here](https://github.com/pocketbase/js-sdk/issues/176#issuecomment-1518939458).
