### ISSUE TITLE
Feature Request: Support JSON:API standard 

### ISSUE THREAD

**Issue by Baltazore** [pocketbase/pocketbase#748]
Hello there

Thanks for a wonderful solution to solve needs of frontend developers for simple backend.

I am wondering if it is possible to add JSON:API formatted responses from BE APIs ? [JSON:API](https://jsonapi.org) is a great standard that solves BE to FE communication format problems and it would be great if Pocketbase had it.

If it is already possible please let me know. I don't have any go knowledge, but I can try to implement it if someone willing to navigate me in codebase 

Thanks a lot.

**Comment by Shaglock** [comment]
This would be useful. Can somebody provide info on how to implement this?

**Comment by ganigeorgiev** [comment]
What format problems this will solves?

From the examples on their website, the format looks verbose, contains too much unnecessary information and it's hard to understand the data at first glance.

Unless there is a real benefit that I'm missing and its not just a personal preference, for now I don't plan supporting the JSON:API response format.

If you want to implement it, you can always create response wrappers using the [before event hooks](https://pocketbase.io/docs/event-hooks/#record-hooks) (you can return your own response by stopping the hook propagation with `return hooks.StopPropagation`).

**Comment by Baltazore** [comment]
Hey @ganigeorgiev  thanks for quick reply
 
 I can agree that format it a bit verbose, but it is not a problem for a modern browser. 
 Main benefit of having standard format - is standard itself. It is well defined and thoroughly documented on a website, so there is no questions between BE and FE teams on how response should look like for given query. Also there is a good specification around how to deal with errors. This is a huge benefit for any team that I worked with. There are [lots of libraries](https://jsonapi.org/implementations/) that already have build-in JSON:API support, with would play nicely with Pocketbase 
 
 Anyway I will try to use hooks as you suggested. Have a nice day.

**Comment by ganigeorgiev** [comment]
I disagree. Using the above format will make way more harder to integrate with any typed backend language.

Serializing for example the above format into the below simple DTO will be a lot more harder than directly matching the corresponding json fields as it is now. Here is for example how we are doing it in the Dart SDK:

```dart
@JsonSerializable(explicitToJson: true)
class AdminModel implements Jsonable {
  String id;
  String created;
  String updated;
  int avatar;
  String email;
  String lastResetSentAt;

  AdminModel({
    this.id = "",
    this.created = "",
    this.updated = "",
    this.avatar = 0,
    this.email = "",
    this.lastResetSentAt = "",
  });

  static AdminModel fromJson(Map<String, dynamic> json) =>
      _$AdminModelFromJson(json);

  @override
  Map<String, dynamic> toJson() => _$AdminModelToJson(this);

  @override
  String toString() => jsonEncode(toJson());
}
```

In order to convert the suggested json:api format into the above dto, it will require manually iterating the unmarshaled json and assigning each property separately.
