### ISSUE TITLE
Changing file storage settings should warn user in case of existing files

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/pocketbase#77]
If you change storage settings (http://localhost:8090/_/#/settings/storage), already uploaded files become unavailable. I think it's unreasonable to attempt to copy all files to a new place, and generally this scenario is kinda unsupported - you're expected to set your storage settings **before** uploading files - but I believe that showing a big scary warning might be a good thing - like when you do some schema changes, UI reminds you that some linked changes might have to be changed elsewhere.

**Comment by gedw99** [comment]
https://github.com/peak/s5cmd Supports mirroring content . Might be a useful thing for when a user changes the s3 endpoint.

You could easily move your file data to wherever as part of any change in settings.

**Comment by ganigeorgiev** [comment]
A warning message and suggestions to use rclone or s5cmd was added in [v0.2.4 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.2.4).

The warning should be visible only when you change the storage type.
