### ISSUE TITLE
Complete URLs are not allowed in S3 storage endpoint

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/pocketbase#78]
"endpoint" option in S3 storage settings (http://localhost:8090/_/#/settings/storage) Must be a valid IP address or DNS name. But if I read it correctly, AWS SDK library accepts both hostname only or fully qualified URI: https://github.com/aws/aws-sdk-go/blob/main/aws/config.go#L44

I believe that specifying full URL might be useful when specifying non-standard port or http vs https protocol.

**Comment by ganigeorgiev** [comment]
This should be fixed in [v0.2.4 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.2.4).
