### ISSUE TITLE
[Help] FindUserByToken requires baseTokenKey

### ISSUE THREAD

**Issue by VirusBLITZ** [pocketbase/pocketbase#785]
Hello,

I'm trying to extend pocketbase's already great backend.
however when I try to get the user by their token the method also requires a "baseTokenKey"... Where do I find this baseTokenKey?

Thanks already

**Comment by ganigeorgiev** [comment]
@VirusBLITZ The base token key depends on the issued token type (auth, password reset, verification, etc.). You can access the base token keys from [`app.Settings().*` struct](https://github.com/pocketbase/pocketbase/blob/master/core/settings.go):

```go
app.Settings().UserAuthToken.Secret
app.Settings().UserPasswordResetToken.Secret
app.Settings().UserEmailChangeToken.Secret
app.Settings().UserVerificationToken.Secret
```

You can also check how the tokens are constructed in the `tokens` subpackage -  https://github.com/pocketbase/pocketbase/tree/master/tokens

**Comment by VirusBLITZ** [comment]
Thanks m8! ❤️
