### ISSUE TITLE
Feature Request: Option to fallback to index.html incase a file does not exist (For SPA, Angular, ...)

### ISSUE THREAD

**Issue by d0x** [pocketbase/pocketbase#811]
To serve SPAs written in Angular, pocketbase needs a configuration to fallback to a default route.

In our case `example.com/redirect` needs to be served from `pb_public/index.html` so that an oauth2 redirect will be routed to the application and not to a 404 error

An proper nginx config would look something  like this:
            
```
location / {   
   try_files $uri $uri/ $uri.html /index.html;
}
```

**Comment by ganigeorgiev** [comment]
"SPA mode" is already implemented in v0.8. Expect a pre-release within the next 1-2 weeks.
