### ISSUE TITLE
Feature Request: Cloudinary support

### ISSUE THREAD

**Issue by Dave136** [pocketbase/pocketbase#819]
Hi there! As the title suggest, i don't know if this feature is already taken as part of road map, if not, it would be a nice feature to be able upload files to cloudinary service, providing the necessary config. 

Postdata: Thanks a lot for this project. IT IS AMAZING!

**Comment by ganigeorgiev** [comment]
At least for v1.0, there are no plans to add support for other storage APIs.
In the future there will be event hooks for before file upload to allow developers to intercept only this part of the model persistence and implement their own handling, but for now this a low priority.
