### ISSUE TITLE
Feature Request: Offline Sync and offline first caching in client libraries (compete with Firebase and Amplify)

### ISSUE THREAD

**Issue by algoflows** [pocketbase/pocketbase#866]
Would love to see offline sync within client libraries, this could then compete with the likes of Amplify and Firebase.

- Offline first with caching and persisted client data
- Detect online then sync mutations and remote data. 

Thoughts?

**Comment by ganigeorgiev** [comment]
For now there are no plans to add support for offline data sync out of the box and this is left to the developers to handle on their own. Some users already created their alternative like https://github.com/rodydavis/pocketbase_drift and probably others.

Once we reach a stable version, I may consider adding official support, but for now remains out of the scope of v1.0.0

**Comment by laurentpayot** [comment]
@algoflows see #67
