### ISSUE TITLE
"Empty" Auth collection not possible in 0.8.0-rc1

### ISSUE THREAD

**Issue by barnsza** [pocketbase/pocketbase#872]
Auth collections already have a considerable number of system fields (id, created, updated, username, email, emailVisibility, verified) and some use cases for such collections may not wish to add additional fields. Could you consider allowing such collections to be made without additional fields?

**Comment by ganigeorgiev** [comment]
I actually thought of this initially, but at the end decided to leave it as it is to minimize the conditional validators.

I'll reconsider it for the final v0.8.0 release.

**Comment by ganigeorgiev** [comment]
This is implemented in the `rc` branch and will be available with the final v0.8.0 release later this week.
