### ISSUE TITLE
Feature Request: Display field for relation

### ISSUE THREAD

**Issue by GKinif** [pocketbase/pocketbase#881]
When using a relation field, it would be very nice to be able to pick which field of the relation will be displayed, in order to avoid seeing only uuid when viewing a collection

**Comment by pgswow** [comment]
Support this issue.

**Comment by ganigeorgiev** [comment]
A new `RelationOptions.DisplayFields` was added and it was implemented in the `develop` branch as part of the relations UI refactoring in #976. It will be available with the next v0.12.0 release soon.

**Comment by inqrt** [comment]
Sorry to reopen but did you guys drop this in the latest release? I remember I had the option to chose what to display in the picker but somehow in the latest version, I cannot find this anymore. If so, please bring it back, was super helpful :)

**Comment by ganigeorgiev** [comment]
@inqrt Sorry, I forgot to mention it in the release notes - it was replaced in v0.18.0 in favor of a new individual "Presentable" toggle option available under each field. This was done to avoid the "Display fields" values duplication when a single collection is referenced more than once and/or by multiple other collections.

**Comment by inqrt** [comment]
thanks @ganigeorgiev for the quick reply - but how can I use the presentable setting to achieve the same as before (or can I at all?)

**Comment by ganigeorgiev** [comment]
If you have 2 collections `A` and `B` and `B` has a relation to `A`, then you can go to the `A` settings and mark the `A` fields that should be preferred when `A` record is displayed in the Admin UI relation listings.

Previously the "Display fields" were managed from within the `relation` field in the `B` collection, but as mentioned earlier this resulted in unnecessary duplication when a single collection is referenced more than once.

**Comment by inqrt** [comment]
Ah super, thanks, that clarified it 👍
