### ISSUE TITLE
Resource not found when trying to update a record.

### ISSUE THREAD

**Issue by mystique09** [pocketbase/pocketbase#892]
I've been trying to solve this error, but I can't seem to find what's the real problem. The resource does exist tho.

This is the code snippet to update the record.
![snippet](https://user-images.githubusercontent.com/50514928/199404835-985e5399-2df4-40f9-aee1-d7a58cdc376f.png)
The error says it can't find the resource, idk why tho.
![error](https://user-images.githubusercontent.com/50514928/199404806-f487704e-cb39-4407-a491-4056dcbd3cd6.png)
But the resource exist if we try to visit the provided link.
![exist](https://user-images.githubusercontent.com/50514928/199404974-04679a6d-f0f7-432e-b03c-3229c3e3c39c.png)

**Comment by mystique09** [comment]
Updating the profile record works, but the posts record doesn't.
![profile_update](https://user-images.githubusercontent.com/50514928/199405739-54d77b3a-e2a8-430f-b107-e5e6ace94ab5.png)

**Comment by ganigeorgiev** [comment]
@muellercornelius I cannot reproduce the issue (both with PocketBase v0.7.9 and v0.8.0-rc1).

Make sure that you have access permissions to perform the update action by checking your API rules (404 will be returned if the request doesn't satisfy the filter rule).

**Comment by mystique09** [comment]
Owhhhhhhhhhhhhhhhhh you were right the problem was the filter rule, mismatch @request.user.id = author.id(instead of author.userId). Thankyou!

![lmao](https://user-images.githubusercontent.com/50514928/199419411-ed31ccd9-11e1-4e5b-b997-4aa26dc51aa8.png)
