### ISSUE TITLE
Feature Request: Add ability to change/add descriptions to Collections and Fields

### ISSUE THREAD

**Issue by Lofter1** [pocketbase/pocketbase#906]
It would be nice to have the ability to add a separate description field to collections and fields or to make the description that they already have editable. Something like "Number value." explains what type the field is, but I don't know whether there is a specific range for the value, if it has to be unique, if there is a specific regex for it etc.

That can also help if a field (or the collection) needs some description or explanation on how it should be used. 

Would this be possible?

**Comment by ganigeorgiev** [comment]
In the future we may improve the auto generated hint texts but custom description field for now is not planned because it may ended up cluttering the UI making the schema magement experience too overwhelming (the same reason why we also don't have a dedicated field label input).
