### ISSUE TITLE
Feature request: API rules for users collection

### ISSUE THREAD

**Issue by z89** [pocketbase/pocketbase#910]
Hi,

Is it possible to set API rules for the users system collection through the UI? I know you can set rules for the profiles collection, however I want to restrict the public from creating users by setting an API key. Will I have to do this in an extended pocketbase instance? Is there a particular reason why there is no UI for setting API rules for the users collection? Thanks for letting me know.

**Comment by ganigeorgiev** [comment]
This is already implemented in v0.8.0-rc.

You can check it in the live demo - https://pocketbase.io/demo.

**Please note that there are some breaking changes in v0.8.0 and some manual migration steps may be required.
For v0.7.x -> v0.8.0-rc you can refer to the rc1 changelogs - https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1.**

You can download the latest release candidate (rc2) from the "Assets" section in https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc2.

Stable v0.8.0 will be available within the next 1-2 weeks.
