### ISSUE TITLE
Add official dockerhub image

### ISSUE THREAD

**Issue by EriksonGM** [pocketbase/pocketbase#92]
Just create a official dockerhub account and publish this amazing project.

```
FROM alpine:3.6
ARG POCKETBASE_VERSION=0.1.2

# Install the dependencies
RUN apk add --no-cache \
    ca-certificates \
    unzip \
    wget \
    zip \
    zlib-dev

# Download Pocketbase and install it for AMD64
ADD https://github.com/pocketbase/pocketbase/releases/download/v${POCKETBASE_VERSION}/pocketbase_${POCKETBASE_VERSION}_linux_amd64.zip /tmp/pocketbase.zip
RUN unzip /tmp/pocketbase.zip -d /usr/local/bin/
RUN chmod +x /usr/local/bin/pocketbase

# Notify Docker that the container wants to expose a port.
EXPOSE 8090

# Start Pocketbase
CMD [ "/usr/local/bin/pocketbase", "serve" ]
```

This is an example made for [bscott](https://github.com/bscott) / [pocketbase-docker](https://github.com/bscott/pocketbase-docker) credits to him.

**Comment by KROSF** [comment]
here one with multiarch support https://github.com/muchobien/pocketbase-docker

**Comment by bscott** [comment]
I'll update mine for Multi-Arch - Be aware of #41

**Comment by gaby** [comment]
@EriksonGM @bscott Can you uodate the base image to alpine 3.15? The version you are using is several years old.

Latest release notes are here: https://www.alpinelinux.org/posts/Alpine-3.13.12-3.14.8-3.15.6-3.16.2-released.html

**Comment by insuusvenerati** [comment]
Hey all! Despite my best efforts, I haven't been able to get pocketbase to work in Docker. With a very basic Dockerfile I always only get `curl: (56) Recv failure: Connection reset by peer` or `ERR_CONNECTION_RESET` in the browser. 

```
FROM alpine:3.16

ADD https://github.com/pocketbase/pocketbase/releases/download/v0.7.2/pocketbase_0.7.2_linux_amd64.zip /tmp/pocketbase.zip
RUN unzip /tmp/pocketbase.zip -d /usr/local/bin \
    && chmod +x /usr/local/bin/pocketbase \
    && rm /tmp/pocketbase.zip

RUN adduser -D pocketbase pocketbase
USER pocketbase
WORKDIR /home/pocketbase

EXPOSE 8090

CMD ["pocketbase", "serve"]
```

**Comment by ganigeorgiev** [comment]
@insuusvenerati The above error is not related to PocketBase or at least not directly and it is probably due to some other network setup that you may need to tune.

_When you run `./pocketbase serve` Pocketbase will start a HTTP server on `127.0.0.1:8090` (you can change the defaults with the `--http` flag)._

**Comment by xrd** [comment]
@insuusvenerati I believe you need to change the CMD to something like this: `["/usr/local/bin/pocketbase", "serve" , "--http", "0.0.0.0:8090"]` Without that, it listens on localhost only inside the container, and even though you have exposed the port, that port is not on the "any" interface, and as such, not able to receive connections.

**Comment by filipemeneses** [comment]
To reduce even more the image size, it's possible to use `FROM scratch`, the version `0.7.5-linux-arm64` have around 10MB. I used [bscott](https://github.com/bscott/pocketbase-docker) as reference to [create this one](https://github.com/filipemeneses/pocketbase-scratch/blob/main/Dockerfile)

**Comment by sanathusk** [comment]
It would be great if an official  dockerhub image  from Pocketbase team was available.It would instill confidence amount developer that it is official and well maintained .

**Comment by LivingWithHippos** [comment]
Quick version just to try stuff using google distroless containers and caddy as reverse proxy. Files are mapped to `/data/pocketbase` to avoid losing data between builds. Executable size 35.8M, final image size 39.9 MB.

**Dockerfile**

```Dockerfile
FROM alpine:latest AS downloader

ARG pocket_version=0.39.10
ARG pocket_url=https://github.com/pocketbase/pocketbase/releases/download/v${pocket_version}/pocketbase_${pocket_version}_linux_amd64.zip

ADD $pocket_url /tmp/pocketbase.zip
RUN unzip /tmp/pocketbase.zip -d /tmp/
RUN chmod +x /tmp/pocketbase

FROM gcr.io/distroless/static-debian13
COPY --from=downloader /tmp/pocketbase /pocketbase

CMD ["/pocketbase", "serve", "--http=0.0.0.0:8090"]
```

**docker-compose.yml**

```yaml
services:
  pocketbase:
    build: .
    # or this if building the image with the script
    # image: pocketbase:0.39.10
    restart: unless-stopped
    container_name: pocketbase
    #ports:
      # REST API: http://127.0.0.1:8090/api/
      # Admin UI: http://127.0.0.1:8090/_/
    #  - 8090:8090                      
    networks:
      - caddy
    volumes:
      - /data/pocketbase/:/pb_data

networks:
  caddy:
    external: true
```

**Caddyfile**

```yaml
pocketfile.domain.com {
    reverse_proxy pocketbase:8090
}
```

**bonus build script to use tagged images in the docker compose**

```
#!/usr/bin/env bash

version="0.39.10"
docker build . --build-arg pocket_version="$version" --tag "pocketbase:${version}" --tag "pocketbase:latest"
```

**Comment by hAhl2** [comment]
Recently discovered CapRover which is an open-source PaaS (https://github.com/caprover/caprover) that one can self-host and deploy one-click apps(https://github.com/caprover/one-click-apps/tree/master/public/v4/apps).  Is there an official docker image for pocketbase https://github.com/caprover/one-click-apps/issues/785?

**Comment by reneManqueros** [comment]
@LivingWithHippos would scratch be better than distroless?

**Comment by LivingWithHippos** [comment]
> @LivingWithHippos would scratch be better than distroless?

It's similar, distroless has a couple more things (CA certificates, timezones support)so the difference in size should be below 5 MB.

**Comment by buldezir** [comment]
please check this https://github.com/buldezir/pocketbase-docker , i made multiarch (actually just x64 and arm) image with admin account precreate.

**Comment by pr0ton11** [comment]
https://github.com/pr0ton11/pocketbase-docker
I provide an alpine image based on muchobien that always provides latest release, is multi-arch and has a way of overriding the listen address from environment

**Comment by realitymolder** [comment]
What about making https://hub.docker.com/r/spectado/pocketbase the official docker image? Why not ask an already maintained image to be recognized as the official image? 
It seems that this image is updated constantly, and also the downloads are highest 10k +

**Comment by gladson** [comment]
my contribution to the discussion.

https://github.com/gladson/pocketbase-docker

https://hub.docker.com/r/gladson/pocketbase

**Comment by Nezteb** [comment]
There is [an example Dockerfile in the "going to production" docs](https://pocketbase.io/docs/going-to-production/#using-docker). Whether or not the maintainers consider that Dockerfile/image "ideal" for distribution I do not know.

It might be helpful to link to that Docker section on [the docs homepage](https://pocketbase.io/docs/), in case people do a quick browser search for "docker", see no results, and think there is no official guidance on using Pocketbase with Docker. 😅

**Comment by jesseadams** [comment]
Why is this being ignored?

**Comment by ganigeorgiev** [comment]
@jesseadams Because I'm not sure if it is necessary and it is left for later consideration.

It is also not a blocker or something too difficult users to do it on their own if there is need for it (see the [example Dockerfile from the docs](https://pocketbase.io/docs/going-to-production/#using-docker)).

Additionally even if there was an official Docker image it will work only when using the prebuilt PocketBase executable and the moment when you have to extend it with Go you'll have to create your own image anyway.

**Comment by Basster** [comment]
You can cut the size of the image inhalf easily, by applying a multi-stage build and running the final binary from scratch:

```Dockerfile
FROM alpine:latest AS download

ARG PB_VERSION=0.22.18

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

FROM scratch AS runner

COPY --from=download /pb/pocketbase /pb/

# uncomment to copy the local pb_migrations dir into the image
# COPY ./pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# COPY ./pb_hooks /pb/pb_hooks

EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
```

On my M1 MacBook:

Image size from docs: 99.76MB
Image size multi-stage: 54.89MB

Maybe someone could update the docs?

**Comment by Meiye-lj** [comment]
also developing a dockerfile for [pocketbase](https://github.com/Meiye-lj/Dockerfiles/tree/master/pocketbase)

**Comment by gaby** [comment]
> also developing a dockerfile for [pocketbase](https://github.com/Meiye-lj/Dockerfiles/tree/master/pocketbase)

That's a very inefficient Dockerfile. The final image will be huge.

**Comment by ganigeorgiev** [comment]
I'm closing this issue since I don't plan for now publishing an official Docker Hub image and I consider the example Dockerfile sufficient for most cases. Additionally, as mentioned in the comments above, when extending PocketBase with Go you'll need a custom Dockerfile anyway and having an official image will be just confusing.

I don't think abstracting essentially 10 lines is really worth the maintenance burden and the various edge cases that will comes with it as there will be always someone unhappy (someone may not want ca-certificates to be copied in the image and to inherit the hosts one, others may want to install ssh related utilities for scp/rsync, etc.).

**Comment by gaby** [comment]
@ganigeorgiev The point is me as a user want to just run pocketbase, I don't want to deal with building an image, setting ci/cd, etc. At the end of the day Pocketbase can be use as both a library and a product. Having an official Docker image is for the product use-case.

**Comment by ganigeorgiev** [comment]
@gaby Again, I'm not willing to take the maintenance burden of maintaining a Docker Hub image that doesn't really do much and doesn't cover all cases. It will be confusing and unnecessary.
