### ISSUE TITLE
Feature Request: API rules for files

### ISSUE THREAD

**Issue by z89** [pocketbase/pocketbase#949]
Hi,

The security issue I'm facing is that every file is accessible via the /api/files/ route with no API rules. I want to be able to restrict access to these files so that anybody who has a leaked URL will be denied access. I could setup an extended pocketbase instance and write a custom API to apply my own access control, but it still doesn't fix the issue that files can be obtained through the default route.  

Theoretically (without rate limiting etc.) someone could brute force the id's to find files as well (albeit computationally expensive). Providing API rules for files would remove any possibility of these events occurring and would be a great help to increase security. 

Is there any reason why this shouldn't be implemented?

**Comment by ganigeorgiev** [comment]
It is already in the roadmap. Will be handled in https://github.com/pocketbase/pocketbase/issues/215 sometime after the v0.8.0 release.
