### ISSUE TITLE
Error: TLS handshake error : acme/autocert: missing server name

### ISSUE THREAD

**Issue by nzee** [pocketbase/pocketbase#95]
While serving Pocketbase with https flag, getting error "TLS handshake error : acme/autocert: missing server name"

**To reproduce:**
```
Ubuntu 22.04
wget https://github.com/pocketbase/pocketbase/releases/download/v0.2.4/pocketbase_0.2.4_linux_amd64.zip
unzip
./pocketbase serve --http="IP_Address:80" --https="IP_Address:443"
```

Any pointers on how to fix this?

**Comment by ganigeorgiev** [comment]
Lets's encrypt doesn't allow issuing certificates on bare IPs, so you need to have a proper domain if you want to use the auto Let's encrypt certificate (see https://community.letsencrypt.org/t/ssl-on-a-ip-instead-of-domain/90635) that PocketBase generate.

Alternatively, you can put PocketBase behind a reverse proxy (eg. nginx) and use your own custom certificate.

Unless I'm missing something, I don't think there is anything that could be done in PocketBase to fix this.
