### ISSUE TITLE
Can't create new collection on 0.8.0-rc2

### ISSUE THREAD

**Issue by tinawng** [pocketbase/pocketbase#955]
Hi,
Since my update to 0.8.0-rc2 I can no longer create new collections.
I try to create a new one using the admin dashboard and got the following error:
![image](https://user-images.githubusercontent.com/8183977/200281861-12725d68-fb9a-4a56-91bd-c7315a4ef1dc.png)
Not sure to understand what happens, I tried to create a collection with just a simple string field and another one with a field named `options` (🤷‍♀️) but still got the error.

Thanks.

**Comment by ganigeorgiev** [comment]
Hm, it doesn't seem that you've migrated completely to v0.8.0-rc.

Please note that v0.8.0 has breaking changes and some manual migrations steps are required.

You can learn more about the changes and how to migrate from v0.7.x in https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1 (v0.8.0-rc2 has no breaking changes from v0.8.0-rc1).

Stable v0.8.0 could be expected In the next 1-2 weeks.

**Comment by tinawng** [comment]
Oh, I completely skipped the data migration part! It's all good now.
Sorry 😓
