### ISSUE TITLE
HTTPS with self signed certificates

### ISSUE THREAD

**Issue by shadowempire123** [pocketbase/pocketbase#957]
Hi,
I could not find a guide how to start pocketbase with a self signed certificate.
I would need something like:
`./pocketbase serve --https="127.0.0.1:443" --key="key.pem" --cert="cert.pem"`

this is not working for my server setup (company network):
```
avl6212t pocketbase_0.7.10]$ ./pocketbase serve --http="avl6212t:80" --https="avl6212t:443"
> Server started at: https://avl6212t:443
  - REST API: https://avl6212t:443/api/
  - Admin UI: https://avl6212t:443/_/
2022/11/07 13:13:59 listen tcp xxx.xx.xx.xx:443: bind: permission denied
```
(replace ip address with xxx)

thx for any help

**Comment by ganigeorgiev** [comment]
This was recently discussed in https://github.com/pocketbase/pocketbase/discussions/930.

Self-signed certificates are currently not supported. You can put PocketBase behind a reverse proxy like caddy/nginx/apache and manage the certificate from there.
