### ISSUE TITLE
Collection users: length username

### ISSUE THREAD

**Issue by pgswow** [pocketbase/pocketbase#961]
Hello!
When creating a user, there is a limit on the number of characters:
"The length must be between 4 and 100."
Is it possible to lower the limit to at least 3 characters?

**Comment by ganigeorgiev** [comment]
I've updated the mininum characters requirement to 3 in the `rc` branch. It will be available in the final v0.8.0 release.

**Comment by jacksonsophat** [comment]
@ganigeorgiev is it possible customize the min length for the username?

**Comment by ganigeorgiev** [comment]
@jacksonsophat No, at the moment it is not possible (_it may be added in the future, but for now remains a very low priority_).
