### ISSUE TITLE
Any one can access files

### ISSUE THREAD

**Issue by DCRalph** [pocketbase/pocketbase#981]
I have a collection of files and have everything locked to admin but anyone can still access the file.

I get the error "{"code":403,"message":"Only admins can perform this action.","data":{}}" when trying to list the records but if you put in the URL you still can get to the file

I have tried on a separate computer that has never been logged in to an admin account and that still has access.

Is this expected behavior?

**Comment by ganigeorgiev** [comment]
Yes, files are "public" by default. Private/Protected files will be implemented in the near future. You can check this issue https://github.com/pocketbase/pocketbase/issues/215.
