### ISSUE TITLE
Long Text makes overlay panel unable to scroll

### ISSUE THREAD

**Issue by dustinknopoff** [pocketbase/pocketbase#99]
https://user-images.githubusercontent.com/23691663/178813881-bfde08fe-4db9-4437-a900-524f7fd8a9fb.mov

Here's an example of me trying to select a relation but the content re-scrolls up

**Comment by ganigeorgiev** [comment]
This should be fixed in the recent [v0.2.5 release](https://github.com/pocketbase/pocketbase/releases).
